### ISSUE TITLE
the spawn facet button should be locked for desktop users (and possible locked behind being in UI edit mode)

### ISSUE THREAD

**Issue by Kirv-goldblade** [Yellow-Dog-Man/Resonite-Issues#1003]
### Describe the bug?

if a desktop user clicks the spawn facet button the facet will spawn into their UI space and be untouchable and impossible to remove by common means

### To Reproduce

well in desktop mode click spawn facet on any available facet and realize it's not stuck in front of your face

### Expected behavior

since desktop users can't edit their UI space they should not be able to spawn objects into their UI space

**Comment by gameboycjp** [comment]
I think a better solution would be fixing dashboard editing on desktop. It's always been broken, and facets are a pretty useful feature, at least to me.

**Comment by Kirv-goldblade** [comment]
that would be optimal yes but baring that a lock would at least help avoid having to restart should accidents happen (since as it stands restarting resonite is the only way for a desktop user to get rid of a spawned facet to my knowledge)

**Comment by gameboycjp** [comment]
Yeah, but why lock off a pretty decent chunk of functionality when it could be fixed instead? What about if edit mode disabled the 2D overlay mode temporarily? That's another pretty quick solution.

**Comment by Frooxius** [comment]
Yes, the plan here is to just fix the facet editing in desktop, rather than mask this bug. 

We have issue for that here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/628

I'm closing this one, as we don't plan on doing this.
