### ISSUE TITLE
Active Sessions discord bot is not working

### ISSUE THREAD

**Issue by Lexevolution** [Yellow-Dog-Man/Resonite-Issues#1006]
### Describe the bug?

The Resonite Bot on the discord is not currently running/updating with the correct info.

### To Reproduce

Go to this link: https://discord.com/channels/1040316820650991766/1154514016899711008
(this is the `#active-sessions` channel in the Resonite discord)

### Expected behavior

For the Resonite Bot to update its own message contents with correct information.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/31176843/69b46d8f-631d-4a42-a4a8-3da2b796a0aa)

### Resonite Version Number

N/A

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Log Files

N/A

### Reporters

Lexevo

**Comment by ProbablePrime** [comment]
I'll look at this when I can, but it is a low priority.

**Comment by ProbablePrime** [comment]
Tis now :)

Thank you for the report, sorry it took so long.
