### ISSUE TITLE
Cannot open world orb

### ISSUE THREAD

**Issue by Sajimachan** [Yellow-Dog-Man/Resonite-Issues#101]
### Describe the bug?

以下のエラーが表示され、NeosVRで作成し、引き継ぎを行ったワールド 「さじまのせかい/Sajima no sekai」のセッションを立てることができません。
念のため、確認をとりましたがNeosVR側では特にセッションの作成やワールドを遊んでいる状態で問題はありません。
正直、 どのような不具合が、 どのような理由で発生しているかわかりません。
お手数をおかけしますが、確認、可能ならば問題なく遊べるように修正もよろしくお願いします。

The error as shown in the attached image occurred, and despite multiple attempts retring, the session for the specified world could not be opened. I have created and uploaded several worlds in NeosVR, but only "sajima no sekai" has has such this error.

then I am not sure what kind of error this might be, but it is the first world that I've created in NeosVR, and I really want to restore it at all costs.

### To Reproduce

world link: https://go.resonite.com/record/U-sajima/R-ab21abc1-eb1d-4769-a39f-8fc6bd0e3055

### Expected behavior

・バグの原因を突き止める。
・他のNeosVRから引き継いだワールド同様に、このワールドがResoniteでも遊べるようにする。
・そもそもワールドに行くことができないので、どのような理由でバグが出ているかの分かりやすい理由が知りたい。

I want it to be accessible to everyone as before, and be removed items and other items that are causing bugs.

### Screenshots

![1image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147888437/0cbdf266-2ab1-43af-a3b2-70422789b6d9)

### Additional Context

・NeosVRから引き継いだ日からこのバグは改善されていません。
・先行登録時点で、一度Resoniteの窓口でチケットを発行しましたが、バグ受付の窓口がその時点で存在しなかったためにそのフォームは閉鎖されてしまいました。

this bug has continued to occur continuously from the time of prior-registration to the current version, Beta 2023.10.13.743.
I issued ticket once, but have already been closed as the issue reception desk does not exist.

### Reporters

Resonite ID/ @sajima

**Comment by ProbablePrime** [comment]
Thank you, I have re-structured this to be a bug.

Please provide a log file if you have it.

**Comment by Sajimachan** [comment]
Of course.
this is the log file that I prepared when the world could not be opened.

[DESKTOP-9MT11P8 - 2023.10.13.743 - 2023-10-14 13_06_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12902355/DESKTOP-9MT11P8.-.2023.10.13.743.-.2023-10-14.13_06_10.log)

**Comment by Frooxius** [comment]
Fixed this in 2023.10.17.464, thank you!

**Comment by Sajimachan** [comment]
thank you very much!!
