### ISSUE TITLE
New Components: BooleanUserOverrideGather and NumericUserOverrideGather

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1014]
### Is your feature request related to a problem? Please describe.

Currently, it's quite easy to create both fully networked and fully local systems in Resonite. It is however quite challenging to create a mixture of both by de-localizing multiple local states into a single shared state.

### Describe the solution you'd like

New components to de-localize multiple local states into a value that's identical for all users.

Specifically, I'm requesting two new components:
- [ ] BooleanUserOverrideGather
      This components acts like a ValueUserOverride<bool> for a field, however, it can drive fields based on a set operation over all current overrides. Those field drives would be for "Any", "All", and "None". The resulting values would be identical for all users, since the overrides are part of the datamodel and syced to everyone.
- [ ] NumericUserOverrideGather
      The functionality is identical to the BooleanUserOverrideGather, but it can be created for every numeric type and the set operations field drives are "Min", "Max", "Sum" and "Average".

The proposed changes to the existing ValueUserOverride / ReferenceUserOverride components from #974 and #1013 would be relevant for these nodes as well, as they behave on the same principle.

### Describe alternatives you've considered

Manually writing functionality to delocalize multiple local values per project. This is however quite awkward or overly complicated with the currently available tools.

### Additional Context

This could massively simplify exsiting creations which depend on doing a set operation of localized values, like the doors in the cloud home pieces or a custom hover / click effect for objects / UIX elements that should appear for everyone if any user is hovering over the object. It could also help with game worlds for situations in which you want to find the largest or lowest score from multiple users.

**Comment by Frooxius** [comment]
I think these would be good additions for simplifying a bunch of setups. I'll look into these at some point.

**Comment by Frooxius** [comment]
Added these in 2024.5.23.1416! I hope they help a bunch!

**Comment by ProbablePrime** [comment]
These are useful the more you think about them, Thank you for requesting them now they're in and floating around my brain I'm sure I'll find some cool uses for them!

**Comment by Frooxius** [comment]
Yusss, these will fit into a lot of patterns.

Even something like "Ready" for a game, you can now do with this.

**Comment by JackTheFoxOtter** [comment]
> These are useful the more you think about them, Thank you for requesting them now they're in and floating around my brain I'm sure I'll find some cool uses for them!

Yus! They simplify a very common problem in a pretty generic way.
