### ISSUE TITLE
Ability to prompt someone with text, set by the world-creator, and "Accept" or "Don't Join" options, when they try to join a session.

### ISSUE THREAD

**Issue by NukiRaccoon** [Yellow-Dog-Man/Resonite-Issues#1020]
### Is your feature request related to a problem? Please describe.

Sometimes people have worlds open for work, and a couple people will join to talk or hang out with them, then other people will join because it is an active world and turn a workspace into a party.  Sometimes you just want people to agree to things when they join.

Currently, there is drama over a user who has content in her world that some users are upset by, but unless you see it in the preview, you may not know what is in that world until after you join.

### Describe the solution you'd like

As part of these protoflux systems which allow the person who runs a world to accept or deny joins, it would be good to have another option to send a text message to the person trying to join, with a simple yes or no response option.  Perhaps this could even be part of the settings on a session.

This would basically just be a pop-up that would display whatever text the person put in there, with basic yes or no type buttons.

### Describe alternatives you've considered

In the world I mentioned where there is some drama, a pop-up appears in front of the user's view, effectively forcing them to click yes or no before they have a good view of things.  It has a list of the session rules.  If they click yes it disappears, if they click no it turns into a middle finger and mutes them.

I have seen other implementations of this same system, some of which don't have a no option, some of which simply boot the user, some of which hide or show content, and it could potentially do all sorts of things... but I'm really asking for something that decides whether a user joins a session / world.

That is the current way to do it, but this still involves the user loading into the world, and the pop-up having to actually load for them before they can see it and respond to it.  The system I am requesting would show up before they join the world, and would only give the World Creator control over the text.

**Comment by Zyro1331** [comment]
This effectively reminds me of the "Creator Note" and "Content Warning" system in another VR platform called Rec Room, where when you are about to join a world, your interface will show a modal displaying potential Content warnings, and notes left by the creator. It would be nice to create this warning system for either a session or world basis, either by being physically implemented in the session menu and in a revamped "World Metadata" window you can access on your owned worlds. 

This would be really useful for adding content warnings to worlds that have **flashing lights, intense motion, loud audio, mature themes, etc..** to make sure people know what they're about to get into.

I could also see this be useful for interactive worlds, which could let creators write down known issues or small patch notes to read before someone enters it.
I approve of this feature as I would believe it could encourage more social hangout spaces, such as simply notifying a user about to join that builder permissions are disabled for everyone to reduce the amount of people working on their things and more people just socializing. _(No offense to the workaholics, **cough cough** me **cough**)_

**Comment by JackTheFoxOtter** [comment]
I think this would be a welcome change, especially in regards to content warnings, which have become sort of a standard for platforms that server user content. Examples here would be social media platforms which allow presenting content warnings which the user will have to aknowledge before the post is shown to them.

I would however suggest separating content warnings from a sort of more general session info / rules dialog. Reason being that on said platforms, you as the user have the option to disable content warnings in your account settings. If sessions have session rules the joiner is expected to read, being able to disable those in the settings would be conterproductive. At the same time, not being able to disable content warnings might be an issue for some people as well.

**Comment by FlameSoulis** [comment]
I'm guessing this would be a sister system to the Protoflux-powered session ban system?

**Comment by NukiRaccoon** [comment]
> I'm guessing this would be a sister system to the Protoflux-powered session ban system?

I think it would be different, because we are talking about something you put into the world description, which has text that people have to agree to before they join it.

**Comment by FlameSoulis** [comment]
> I think it would be different, because we are talking about something you put into the world description, which has text that people have to agree to before they join it. Thus, it would be the opposite.

Oh, like those prompts for live streams and all that: just a basic one. That makes more sense.

**Comment by ProbablePrime** [comment]
Superseeded by #1445
