### ISSUE TITLE
Font with loading and camera is different

### ISSUE THREAD

**Issue by Blaziewazie** [Yellow-Dog-Man/Resonite-Issues#1024]
### Describe the bug?

Font on loading/default avatar  and camera is different

### To Reproduce

log into a world and you should see it when someone is loading

### Expected behavior

font is ment to be that same

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/45274967/9e2454e2-e446-405e-bfd7-89c5da3f3c94)

### Reporters

Lydiawhyte0744
its_sox
karl

**Comment by Frooxius** [comment]
I don't quite understand what is the issue here?

The font is different from what exactly? Can you show a comparison?

**Comment by Chundelac** [comment]
I think they mean that the two fonts on the picture are different, you can clearly see it on the A letter.

**Comment by Blaziewazie** [comment]
> I don't quite understand what is the issue here?
> 
> The font is different from what exactly? Can you show a comparison?

look at the avatars font and and cameras font the fonts are slightly different no big deal though

**Comment by Zandario** [comment]
One is Poppins, one is Noto Sans
