### ISSUE TITLE
New Component: ValueCast

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1025]
### Is your feature request related to a problem? Please describe.

Currently, it is only possible to cast value types using ProtoFlux.

### Describe the solution you'd like

A ValueCast component analogous to the ReferenceCast component under Transform > Drivers.

### Describe alternatives you've considered

Casting values using ProtoFlux instead.

**Comment by Zyzyl** [comment]
This already exists to an extent. Under the Uncategorized category there are a bunch of Convertible*Driver<T> components. e.g ConvertibleFloatDriver<bool> takes a bool field as an input and drives a float target field

**Comment by JackTheFoxOtter** [comment]
I see. I assume there is a reason those can't be combined into a single component with two generic types? These do fix my issue, but they should probably be moved to Transform > Drivers as well.

**Comment by JackTheFoxOtter** [comment]
Closing in favor of #1251 - This already exists, just isn't where I expected it to be. Thanks @Zyzyl!
