### ISSUE TITLE
Make "bake non-driven blendshapes" action non-destructive

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1028]
### Is your feature request related to a problem? Please describe.

A very frequent optimisation for avatars is baking non-driven blendshapes. Currently, it is not possible to "undo" this action at a later point, which means users are required to save a backup version of their avatar before they baked the blendshapes in case they decide later on that they want to change or drive some blendshapes they have previously baked. This can quickly lead to users accidentally using the wrong version of their avatar, deleting the version before they applied the blendshapes, making changes to the wrong version of their avatar and having to manually transfer them over later, forgetting to bake an avatar after making changes to the non-baked backup, or just not baking their blendshapes at all because they like to keep the ability to edit them later on, and don't want to deal with multiple versions.

### Describe the solution you'd like

I would like the original version of the mesh to be saved the first time a user clicks the "bake non-driven blendshapes" button for a mesh, and the button "restore original blendshapes" to be added. This option would restore the previously saved state of the blendshapes before they were baked. This would allow for a non-destructive avatar optimization workflow, which would significantly reduce the friction currently present in this process, and hopefully lead to more people baking their blendshapes.

### Describe alternatives you've considered

Using the manual backup method, but as outlined above, I don't think this is a very elegant workflow. Enhancements like object versioning could help, but wouldn't fully remove the friction, as users would still need to make sure they edit the correct version of the avatar, and might end up having to transfer changes manually from one saved version to another if they made changes to the wrong version.

**Comment by Frooxius** [comment]
I don't think we can really do this one, because it would defeat the whole purpose of the baking. The benefit of it is that it gets rid of the excess data that's not really needed, but this would effectively keep it, on top of the newly baked data. 

There are some potential approaches to making the workflow easier to use, but I don't think this is one of them. You'd need to have a separate version saved, but one of the ideas is that you configure your edit version with what needs to be baked and such and whenever you save it, it auto-saves optimized versions.

That way you still have the original as well as optimized "variant" of it.

**Comment by Banane9** [comment]
> I don't think we can really do this one, because it would defeat the whole purpose of the baking. The benefit of it is that it gets rid of the excess data that's not really needed, but this would effectively keep it, on top of the newly baked data.

Hmmm, you wouldn't need to keep the unbaked data in the resource for the baked mesh though, just a pointer / link *to* that original data - which would most likely have to be stored either way as people want an unbaked version to continue working from.

I'd consider it similar in functionality the non-destructive nature of setting the max size on StaticTexture components, although I'm not sure how that's handled on the backend exactly.

**Comment by JackTheFoxOtter** [comment]
> I don't think we can really do this one, because it would defeat the whole purpose of the baking. The benefit of it is that it gets rid of the excess data that's not really needed, but this would effectively keep it, on top of the newly baked data. 

I was thinking about this more in regards to the original data being preserved on the cloud, not in the world. Baking blendshapes of the mesh would replace the current mesh with a new one. But I would assume it should be possible to just keep the original mesh linked to the new one on the backend. The point of baking blendshapes is optimizing the mesh for display in-game, which this would still do. It would just keep the new mesh asset linked to the old mesh asset, which could be restored on-demand when the user presses that button.

**Comment by Frooxius** [comment]
There's not really pointers like that though. It's not sufficient to store all the necassary data either, because there might be more complex relationships. So having something to accommodate without impact adds a lot of engineering complexity and doesn't fit into the system so well.

The texture size analog is not quite applicable here, because the avatars are complex objects, so they don't have individual variants the way base assets do.

I think the approach I proposed above would work best, because there are additional optimizations you can (and should) do as well and making all of the non destructive, especially in a chain, would explode in complexity with this approach.

**Comment by JackTheFoxOtter** [comment]
I was assuming this could be implemented on an asset level, which was what I was talking about. Apologies if I was unclear, I didn't mean this as a full automatic avatar backup, just keeping the unbaked mesh asset around so you can revert to it later. When you click the bake non-driven blendshapes button on a SkinnedMeshRenderer, doesn't that alter the base mesh asset? If baking blendshapes does more than that idea doesn't apply, I wasn't aware of any complex relations there. But I might not fully understand what exactly the bake button does if it goes beyond changing the mesh data.

**Comment by Frooxius** [comment]
No, that part is clear, what I am saying is that you can't have it work that way.

Baking the blendshapes remaps the blendshape map on the skinned mesh renderer and number of references within the hierarchy. It also erases a number of information - like what was state of those blendshapes before and what might've been referencing those.

You'd need to save that information somewhere too to be able to restore things to previous state, which is a lot of additional engineering (the mesh asset is not suitable for this) and then the tooling to properly process and reverse and operate with this too is a lot of additional engineering too. It would also only work for this specific bake option and none of the others, so if you apply any other optimizations (e.g. splitting by blendshapes), you'd be back to square one. 

The method I propose would use mostly existing mechanisms, wouldn't be as big engineering cost and would work with any optimization methods.

**Comment by JackTheFoxOtter** [comment]
All right, thanks for explaining! Sorry for the confusion on my part.
