### ISSUE TITLE
Unfocusing exit session by any means delays application shutdown process until re-focused

### ISSUE THREAD

**Issue by Mrdabup** [Yellow-Dog-Man/Resonite-Issues#103]
### Describe the bug?

When you exit resonite while requesting to join a world, your request to join is prioritized while exiting. This will soft lock your game unless you terminate the program.

While being in this "zombie" state, your microphone still works, your radial menu still works, and movement* still works.
The thing that doesn't work is the main menu, as it gets disabled when exiting resonite.

*You cannot look around in first person, only using the observer camera [F6]

### To Reproduce

1. Request to join a world 
2. Exit RESONITE (by pressing the exit and "Save Home" button)
3. If done correctly, you will join the world that you requested while exiting resonite

### Expected behavior

1. All join world requests being canceled
2. Your items get synced and you exit resonite

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows, Android / Quest

### What headset if any do you use?

Quest 2, Desktop

### Log Files

[DESKTOP-44DGH14 - 2023.10.13.743 - 2023-10-13 19_49_41.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12900658/DESKTOP-44DGH14.-.2023.10.13.743.-.2023-10-13.19_49_41.log)

### Reporters

Mrdab (mrd.a)

**Comment by Frooxius** [comment]
Thank you, fixed in 2023.10.17.464!
