### ISSUE TITLE
Add cc to extensions known to be text

### ISSUE THREAD

**Issue by RobertBaruch** [Yellow-Dog-Man/Resonite-Issues#1030]
Requester: **Xekri** (my github account is under my real name)

### Is your feature request related to a problem? Please describe.

Importing a .c, .h, or .py file results in a nice text display. However, importing a .cc file results in the generic "unknown type" file visual.

### Describe the solution you'd like

Include cc in the list of text assets (`AssetHelper.associatedExtensions`)

### Describe alternatives you've considered

Rename `cc` files to `cpp`. However, `cc` is a known "standard" C++ file extension. To be fair, it's an older, more UNIX-ey extension than `cpp`.

**Comment by ProbablePrime** [comment]
This should be easy, i'll take a look

**Comment by Frooxius** [comment]
Merged this in 2024.6.24.1317, thanks!
