### ISSUE TITLE
Invalid SSL cert for go.resonite.com

### ISSUE THREAD

**Issue by archer007** [Yellow-Dog-Man/Resonite-Issues#1033]
### Describe the bug?

go.resonite.com presents an SSL certificate for yellowdogman.com

### To Reproduce

Go to any go.resonite.com URL, for instance https://go.resonite.com/record/U-Aeo/R-84e4cd8e-5689-4f81-a76a-0690bce24f3a

### Expected behavior

go.resonite.com should present a valid SSL cert by using it's own dedicated SSL cert or using a multi-SAN cert

### Screenshots

![ydm_cert](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/86111/e3ec7e9a-a554-42af-923d-fb672cbd46ca)

### Resonite Version Number

2023.12.21.1127

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Quest 3

### Log Files

N/A

### Additional Context

This might be causing headless downloads to fail, but it might be unrelated. See partial log from headless below

resonite-headless  | Session updated, forcing status update
resonite-headless  | Session updated, forcing status update
resonite-headless  | Failed gather for https://go.resonite.com/record/U-Aeo/R-84e4cd8e-5689-4f81-a76a-0690bce24f3a, path: /home/steam/resonite-headless/Headless/Cache/Cache/9gy48far98k661sg
resonite-headless  | GatherJob https://go.resonite.com/record/U-Aeo/R-84e4cd8e-5689-4f81-a76a-0690bce24f3a, State: Failed, StatusCode: 0, Progress: 0.00, Started: 01/01/0001 00:00:00
resonite-headless  | Failed the retrieve file for https://go.resonite.com/record/U-Aeo/R-84e4cd8e-5689-4f81-a76a-0690bce24f3a, returned path: null

### Reporters

Archer42

**Comment by archer007** [comment]
I was using the wrong type of URL for loading worlds from headless. This appears to be just a general problem

**Comment by ProbablePrime** [comment]
Collating this into https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1295 they are caused by the same issue, which is that we never setup this URL.
