### ISSUE TITLE
Stereo Side-by-side imported Photo now twice width.

### ISSUE THREAD

**Issue by markjeffcock** [Yellow-Dog-Man/Resonite-Issues#1035]
### Describe the bug?

When importing a Stereo Photo, side-by-side LR version the resultant photo appears twice the expected width.

### To Reproduce

Upload of a stereo LR side-by-side image of a LandRover.
I'm seeing a stereo effect but with an aspect ration of 8:3 instead of 4:3. 

Attached a stereo SBS of a Landrover.
![LandRover_2x1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/66623848/4161a221-f402-43cd-8e1c-484c3c892d26)

### Expected behavior

I'd expect a 4:3 aspect ratio, with the different L & R images going to the left & right eye to give a stereo effect.
Current behaviour gives a stereo effect but with an aspect ration of 8:3 instead of 4:3. 

### Screenshots

![LandRover in Resonite](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/66623848/1c96babd-cc85-4725-8604-c8cd010a579f)

### Resonite Version Number

Beta 2023.12.21.1127

### What Platforms does this occur on?

Windows, Android / Quest

### What headset if any do you use?

Quest 3

### Log Files

n/a

### Additional Context

In your 21/12/2023 (PDF Support and more) release there is this note in

Tweaks:- Imported/generated images are now always setup with TextureSizeDriver, which will make the quad update its aspect ratio when the image changes.

Is this change mis-interpreting the required aspect ratio for a side-by-side stereo photo and setting the quad to double the width? Presumably if that is the effect it would also have an issue with top/bottom stereo picture and double their height?

### Reporters

MarkJ  (MarkJeffcock) mark.jeffcock@gmail.com
Harolddd (Silver Man 3D)

**Comment by Frooxius** [comment]
Fixed in 2024.1.19.687, thanks!
