### ISSUE TITLE
Strange facet issue after using -ResetDash command on [Pre-release] Beta 2023.12.29.1306

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#1036]
### Describe the bug?

It appears that some ProtoFlux on the facets (Particularly the OnlineStatus, VoiceMode & VersionNumber facets) that drive the visuals appear to break and behave weirdly after using the -ResetDash launch argument. (See Screenshots attached below)

This appears to not affect anything else, I used custom facets beforehand like Mirracle and my personal work-in-progress battery facet and even while this bug occurred, those facets were untouched and operated perfectly fine. I proceeded to use another -ResetDash to try and fix it, but it persists.

### To Reproduce

1. Opt-into the current Resonite pre-release (Beta 2023.12.29.1306 as of writing) 
2. Enter the -ResetDash launch argument in Steam
3. Launch Resonite
4. If your dashboard is already open, you might see the facets on the top left will be partially broken. 

### Expected behavior

I expect the VoiceMode, OnlineStatus, and VersionNumber facets to not have strange visual issues, and properly animate when the user clicks on them.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/9c667385-9a87-4ce8-af59-69a09f5b88a0)

(Clicking the VersionNumber does add it to the clipboard, but the feedback animation is completely broken)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/b460bf8d-f252-4c8f-b278-af0a8869e143)

### Resonite Version Number

Beta 2023.12.29.1306

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MANGOVRG - 2023.12.29.1306 - 2023-12-31 08_01_41.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13801653/MANGOVRG.-.2023.12.29.1306.-.2023-12-31.08_01_41.log)

### Reporters

@zyro1331

**Comment by Nytra** [comment]
It was noted here https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/814#issuecomment-1872410706

Though a dedicated issue is good I guess

**Comment by ModernBalloonie** [comment]
This happens to the visuals that are supposed to slide out on the buttons like "Create new world".

**Comment by Zyro1331** [comment]
This issue appears to have been fixed in current release Build 2024.1.3.393!

Closing this issue now
