### ISSUE TITLE
not allowing login or password reset - 'invalid credentials'

### ISSUE THREAD

**Issue by GhoulHound** [Yellow-Dog-Man/Resonite-Issues#1039]
### Describe the bug?

attempting to login, it wont accept my email, username or password. when trying to reset my password when assuming thats the issue, the reset email delivers correctly, it accepts the reset code but then when entering my new password and going to accept it, it displays 'invalid credentials' and the password reset does not work. this continues to happen each time i try to log in.

### To Reproduce

i would try logging out then in to reproduce it though only a couple other people have reported this bug over on discord.

### Expected behavior

i expected to be able to log in and use my account as normal.

### Resonite Version Number

Most recent.

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2, Desktop

### Log Files

[PENDULUMPC - 2023.12.21.1127 - 2024-01-01 04_50_42.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13802796/PENDULUMPC.-.2023.12.21.1127.-.2024-01-01.04_50_42.log)

### Additional Context

it happens both on my quest and desktop. im looking at making a new account as a solution but there may be issues with using my email thats already registered and id like to keep my stuff if possible.

### Reporters

myself ghoulhound, kurotori

**Comment by DanteTucker** [comment]
I have seen quite a few users report this recently. Here is a screenshot showing the invalid credentials error appearing over the reset password dialog after clicking set new password, something that shouldn't happen.
![invalidcredentials](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/407025/4c00968e-5363-444d-a0d1-c9a2266d11bb)

**Comment by Frooxius** [comment]
Hello! Thanks for the report, this should be fixed with latest cloud update now.

Can you please try logging in again and see if it works this time?
