### ISSUE TITLE
Add "MakeNonPersistent" option to GrabInstancer

### ISSUE THREAD

**Issue by marsmaantje** [Yellow-Dog-Man/Resonite-Issues#1055]
### Is your feature request related to a problem? Please describe.

Currently when using GrabInstancers for props in a world, all instances are persistent, meaning they clutter up the world if it is saved.

### Describe the solution you'd like

Add an option to the GrabInstancer to make instanced copies non persistent when spawned.

### Describe alternatives you've considered

A bit of flux on the instance that sets it to non persistent on duplicated.
Or when the world starts it sets the instance itself to non persistent until the world is saved.

**Comment by ProbablePrime** [comment]
This is a cool idea, especially good for event maps etc. I'll take it as a "fun project" so don't expect it to have a high priority but I can totally handle this.

**Comment by Nytra** [comment]
Sorry to derail the issue but if you are doing work on the GrabInstancer could you also take a look at this request please? https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/839

**Comment by ProbablePrime** [comment]
Thats unfortunately not that simple, so will have to wait.

**Comment by ProbablePrime** [comment]
Separate please, sorry I know its a bore, but its very common for users to add additional requirements to issues that suddenly get attention and if I responded/acted on every single additional request the initial request would never actually land and launch.

**Comment by marsmaantje** [comment]
> Separate please, sorry I know its a bore, but its very common for users to add additional requirements to issues that suddenly get attention and if I responded/acted on every single additional request the initial request would never actually land and launch.

Understandable, I have made it a separate feature request, thank you for the answer.

**Comment by Frooxius** [comment]
Merged this in 2024.1.24.834, thanks for request!
