### ISSUE TITLE
MulDeltaTime and DivDeltaTime ProtoFlux nodes are not continuously changing

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1070]
### Describe the bug?

When using the MulDeltaTime or DivDeltaTime nodes, the values from them will not continuously change even when plugged into a display node. They require ContinuouslyChangingRelay or changing inputs to have their values update.

This is contrary to the DeltaTime node which does continuously change. It doesn't make sense that they don't all continously change.

### To Reproduce

1) Create a MulDeltaTime or DivDeltaTime node
2) Input a constant value such as 1
3) Pull out a display node and see that the value does not change

### Expected behavior

The value outputs continuously change.

### Screenshots

![2024-01-04 12 00 06](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/4e211102-9ad0-4454-8025-5eea82495665)

### Resonite Version Number

Beta 2024.1.3.1265

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Quest 2, Desktop

### Log Files

[DESKTOP-H976HO2 - 2024.1.3.1265 - 2024-01-04 11_56_45.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13829580/DESKTOP-H976HO2.-.2024.1.3.1265.-.2024-01-04.11_56_45.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: nytra)

**Comment by Frooxius** [comment]
This has been changed in 2024.1.12.1336, thank you!
