### ISSUE TITLE
Compression changes texture sizes by as much as 30%

### ISSUE THREAD

**Issue by 5H4D0W-X** [Yellow-Dog-Man/Resonite-Issues#1079]
### Describe the bug?

After importing certain textures, their reported size is incorrect until "Uncompressed" is turned on.

### To Reproduce

import this texture: 
![testpattern](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/99607717/f34f940f-6458-4c0b-85ea-43f97e21bccd)
or create your own texture (9x9 size always seems to exhibit the bug). Inspect the texture or add it to a component that returns the size of the texture, it should show 12x12. Turn off compression and watch the size change to 9x9.

### Expected behavior

Quality diminishes, but size of the texture does not change.

### Screenshots

![2024-01-05 07 44 32](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/99607717/95ee5e7d-0c82-4b7c-b958-dacee9f5b794)

top: compressed (note the size being reported as 12x12)
bottom: no compression (correct 9x9 size being reported)

these images use the same asset URL and the only setting that was changed is setting the textures to point filtering

### Resonite Version Number

Beta 2024.1.3.1265

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

Will add ASAP

### Reporters

Rustybot | @ rustybot

ShadowX | @ shdw_x

**Comment by art0007i** [comment]
if I had to guess it's trying to align to a specific size to compress it better. probably working as intended but we'll see

**Comment by Frooxius** [comment]
This is expected behavior.

The compression algorithms typically work on blocks of 4x4 pixels. As a result, if the texture is compressed, it's size must be aligned to a multiple of 4, hence 12 pixels.

It is not possible to have both compressed texture and size that's not multiple of 4. You have to choose one or the other.
