### ISSUE TITLE
Separate the save button from the create folder button

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#108]
### Is your feature request related to a problem? Please describe.

the whole save vs make folder thing is something that seems very confusing for new users in my experience.  Having them being distinct, dedicated buttons would help ease onboarding

### Describe the solution you'd like

split buttons, only have them enabled and/or visible when contextually appropriate

### Describe alternatives you've considered

not sure, perhaps the button as-is could be made more clear, but i'd rather them be separate

### Additional Context

zangooseoo

**Comment by Frooxius** [comment]
We won't be implementing this for existing UI, it will be reworked completely by #1119 

I'm closing this one as duplicate, since this will be handled implicitly by the UI rework.
