### ISSUE TITLE
Desktop mode resolution is not reset when switching between full-screen and windowed modes with Alt+Enter

### ISSUE THREAD

**Issue by simmplicity-evergarden** [Yellow-Dog-Man/Resonite-Issues#1080]
### Describe the bug?

Resonite does not reset or fix resolution when switching from windowed mode to full-screen mode using Alt-Enter. Resonite will appear blurry (due to scaled-up resolution) and/or have black bars to adjust for the different aspect ratio.

### To Reproduce

1. Launch Resonite in desktop mode.
2. Use Alt+Enter to switch to windowed mode
3. Resize the window to be smaller with a different aspect ratio. Making the window thinner is the clearest example. 
4. Use Alt+Enter to switch back to full-screen mode.

### Expected behavior

Resonite should resize to the native size of the display.

### Screenshots

Windowed mode:  
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/134457357/633ac84e-d68e-4a7b-badc-fda5a1bf4261)
Full-screen mode:  
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/134457357/fccaac37-db1b-4b9f-aabc-8d264ba82c6d)

### Resonite Version Number

Beta 2024.1.3.1265

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop

### Log Files

[EVERGARDEN - 2024.1.3.1265 - 2024-01-05 11_46_40.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13844470/EVERGARDEN.-.2024.1.3.1265.-.2024-01-05.11_46_40.log)

### Reporters

Discord: 
- simmpli.city
- Whippersnatch Pumpkinpatch#2008 (Replication on Linux)
- felowl (Replication on Windows)

Resonite:
- Roxaaanne (Replication on Windows)

**Comment by Frooxius** [comment]
This has been fixed with 2024.4.30.495 with the new resolution settings. 

I missed this issue due to there being another Resolution issue, sorry!
