### ISSUE TITLE
Protoflux node to get Slot or User from reference ID

### ISSUE THREAD

**Issue by RobertBaruch** [Yellow-Dog-Man/Resonite-Issues#1082]
### Is your feature request related to a problem? Please describe.

We have a References/ReferenceID node which gets the RefID for any IWorldElement. However, we don't have the inverse, getting an IWorldElement (User, Slot, or anything else having a RefID) from a RefID.

My ulterior motive is that I have [a mod](https://discord.com/channels/1040316820650991766/1192908461525188689) that implements a WASM interpreter. Inside WASM, I can only use numeric values, not object references, so using a RefID is ideal. I can transfer world elements from Resonite to WASM by just passing in their RefID, but I can't do the inverse.

### Describe the solution you'd like

A Protoflux node that converts from RefID to IWorldElement.

As a side effect, this would enable mods to convert from RefID to IWorldElement in C#.

### Describe alternatives you've considered

Every time I pass a Slot or User to WASM, I get its RefID and enter it into a dictionary in the mod. Every time WASM calls a hosted function which returns Slots or Users (e.g. implementing Slot.GetParent), I enter those in the dictionary as well. This way, my hosted function (e.g. Slot.GetParent) can receive Slot/User arguments from WASM using their RefID.

The problem with this approach is that we don't generally know when we want to remove a RefID/WorldElement pair from the dict. That would require another mod patch to detect when it happens, but I'd like to patch as little as possible, since each patch is vulnerable to changes in Resonite.

### Additional Context

Requester: Xekri (my github account is under my real name)

See also [Discord post](https://discord.com/channels/1040316820650991766/1192908461525188689) in user-creations about my mod.

![MicroPython on Resonite](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/1783950/8e6625f1-c2d7-4734-b9b0-26f8295c4668)

**Comment by Banane9** [comment]
You can write RefIDs into any field that accepts IWorldElements and it will automatically be resolved to that object (if it applies)

**Comment by RobertBaruch** [comment]
> You can write RefIDs into any field that accepts IWorldElements and it will automatically be resolved to that object (if it applies)

You're saying that somewhere in the C# code is something that will convert a RefID to whatever that RefID refers to. I haven't found any such thing. Do you have an idea where it might be?

**Comment by Frooxius** [comment]
You can't convert RefID into IWorldElement directly, you need to look it up in the ReferenceManager.

I'm not sure if we'd want to add a node for this right now, since that might potentially lead to some brittle usage and bad usage patterns, that we'd want to avoid, without having a better system in place.

RefID's are generally something that's intended to be more internal and not directly interacted with.

**Comment by RobertBaruch** [comment]
Thanks, Froox, this probably means that I should make my own reference IDs. I will then have to patch in to when the referent object gets deleted otherwise my mod would hold on to the referent object.

**Comment by Frooxius** [comment]
If you're making a mod, why not just use the RefereceManager to look up the items?

**Comment by RobertBaruch** [comment]
I haven't found ReferenceManager in any assembly. Do you know which assembly it's in?

**Comment by Frooxius** [comment]
Ooops sorry, it's ReferenceController

It's in the main FrooxEngine.dll one

**Comment by RobertBaruch** [comment]
Ah! I remember looking at that early on in my investigation, but I wasn't certain whether RegisterReference/UnregisterReference got called when Slots or Users were created/destroyed.

**Comment by RobertBaruch** [comment]
Seems to work, thanks!
