### ISSUE TITLE
Add Clear Cached PDF to StaticDocument Component

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#1091]
### Is your feature request related to a problem? Please describe.

Currently it seems it is not possible to clear cached results from remotely hosted PDFs, and the first accessed PDF for a given URL will always be shown.

### Describe the solution you'd like

A button should be added to the `StaticDocument` component as well as an associated action for clearing the cached result for the current URL.

You can test that this is the case by using the Wikipedia browser created here:

resrec:///G-Bright-Spark/R-C88BA0DEF27D09513A8BBA40B5B21F212F75F67B11193935A3D7BF9E0DC2F593

where the pages should update daily.

### Describe alternatives you've considered

There is no alternative currently.

**Comment by Frooxius** [comment]
This wouldn't quite fix the problem unfortunately. The asset system assumes that assets are generally immutable. 

Even if there was a button that would clear the asset for you, it would not guarantee that everyone else would get the new version - it would just clear it for you, which could be confusing, as different users would see different versions of the document.

Because of that, we'll not be adding this button.

We can investigate other solutions to this, that would be more robust.

**Comment by lxw404** [comment]
It can also be argued that it is confusing as well at the moment since users are already seeing different versions of the document from one another, because the first time they load the page it will always show that version for them and never change, which is especially problematic for a living information source such as Wikipedia.

Would a viable solution in some way include the ability to mark an asset as dynamically loaded with some checkbox so that on first load, it will ignore cache and load it directly?

I've also tested that this issue arises with other dynamically changing assets hosted on websites as well, such as [Lorem Picsum](https://picsum.photos/200/300) for images, so I am assuming this issue will probably pop up in every single asset context.

**Comment by Banane9** [comment]
> I've also tested that this issue arises with other dynamically changing assets hosted on websites as well, such as [Lorem Picsum](https://picsum.photos/200/300) for images, so I am assuming this issue will probably pop up in every single asset context.

Correct, all assets are assumed to be static and will never be checked again for changes if a cached version is found.

> The asset system assumes that assets are generally immutable.

---

> Would a viable solution in some way include the ability to mark an asset as dynamically loaded with some checkbox so that on first load, it will ignore cache and load it directly?

That would sound like a good idea - you can also change the URL to retrigger downloading an asset (e.g. by appending something after an `?` or `#`).

**Comment by lxw404** [comment]
True you can append to the URL, however many API endpoints (such as the one I mentioned already) do not allow this though since they require arguments to be passed in that way, so I wouldn't count on that working for most things...

Tangentially, I'd consider it to be an important addition considering we will soon have a Resonite Wiki which will be a host of dynamic content, and of course I am eager to bring this content in-game in document form, which necessitates being able to account for updating pages and other assets.

**Comment by Banane9** [comment]
> True you can append to the URL, however many API endpoints (such as the one I mentioned already) do not allow this though since they require arguments to be passed in that way, so I wouldn't count on that working for most things...

As long as you assign it to a parameter that isn't used by the API or something that's ignored anyways (i.e. the `#` anchor), it shouldn't affect what's being returned.


> Tangentially, I'd consider it to be an important addition considering we will soon have a Resonite Wiki which will be a host of dynamic content, and of course I am eager to bring this content in-game in document form, which necessitates being able to account for updating pages and other assets.

Yea, it would be a good addition to things in general if you know something is gonna be dynamic.

**Comment by Frooxius** [comment]
It definitely is confusing when they see different asset.

What I'm saying is that this is not the right solution for it.

We should investigate and engineer something more robust.

It's be mostly on our end to do that. But this is why we generally recommend in our guidelines to focus issues on the bug/problem (in this case the PDF not updating when changed on remote server), not particular solution.

**Comment by lxw404** [comment]
Understandable, my focus was on one thing and what I viewed would solve it (which is a required field), but it has led to a better understanding of a larger issue now.  I will close this issue and revise it with the more general purpose of this request which in my view is that: assets which are dynamic are not updating when changed on remote sources.

**Comment by Frooxius** [comment]
Yeah that sounds good, thank you! If actually recommend posting this one as a bug instead.
