### ISSUE TITLE
Chirality input initially displays -1 ?

### ISSUE THREAD

**Issue by rassi0429** [Yellow-Dog-Man/Resonite-Issues#1094]
### Describe the bug?

If the Equip Tool node, for example, displays the input of a side, "-1" is displayed.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91118218/92c01da1-71ec-45a6-ab45-c96532ea5a8c)

In this case, I thought that the tool would be set in the dominant hand, but it was never set.
This input can only be set to "right" or "left" by pressing the left and right buttons, and cannot be set back to "-1".

I wasn't sure if this was a bug or not.

### To Reproduce

In the Protoflux tool, spawn the Equip Tool node and spawn the inputs of the Side.

### Expected behavior

I expected the right hand or -1 input to be the user's dominant hand.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91118218/92c01da1-71ec-45a6-ab45-c96532ea5a8c)

### Resonite Version Number

Beta 2024.1.3.1265

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-UPS4R4A - 2024.1.3.1265 - 2024-01-07 22_16_28.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13853552/DESKTOP-UPS4R4A.-.2024.1.3.1265.-.2024-01-07.22_16_28.log)

### Reporters

discord: kokoa
resonite: kokoa0429

**Comment by Nytra** [comment]
It's not a bug

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/703

**Comment by rassi0429** [comment]
Ah, I searched but couldn't find it.
thank you. This issue is considered unnecessary and will be closed.

**Comment by rassi0429** [comment]
I forgot to search for closed issues.

**Comment by Frooxius** [comment]
Yes this is by design. See the other issue.
