### ISSUE TITLE
Protoflux wires shouldn't update whenever their global position changes

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Resonite-Issues#1104]
### Describe the bug?

As already discussed in #1090, the `ProtoFluxWireManager` component updates on every frame when its global position changes. This happens even when disabling the obvious source of those updates, namely the `Slot_WorldTransformChanged` method on it, which marks it as having changes. These updates commonly causes the StripeWireMesh driven by the wire manager to also update, regenerating its mesh.

As described in #1090, this causes severe performance issues when trying to move large amounts of nodes. Decreasing the number of steps on the wires would hold this effect at bay for longer, as less vertices have to be regenerated. However, while this is a reasonable performance improvement by itself, it doesn't actually fix the underlying cause:
Namely, that the wires don't necessarily need to update when their global position changes - only when their position changes relative to the node they're connecting to. In common use cases, for example, moving a Redprint with nodes on it, this is not the case, and performance could thus be improved if these updates were not triggered.

### To Reproduce

Move a redprint or other parent of a large amount of unpacked protoflux network. Performance significantly decreases. 

### Expected behavior

The wires connecting nodes should only update when actually necessary to decrease mesh data changes where possible and thus improve performance.

### Screenshots

Screenshot of the setup used to generate the logs - the nodes were moved around using the shared parent:

![Three protoflux nodes connected in a chain with a shared parent to move them around.](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/554d81aa-6222-4d66-b8a2-95644c9b928b)

### Resonite Version Number

latest

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Index

### Log Files

With mods to add logging to the relevant methods: `ProtoFluxWireManager.OnChanges` and `WireMeshBase.UpdateMeshData`

[BANANE9-GAMING - 2024.1.3.1265 - 2024-01-07 23_48_33.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13867873/BANANE9-GAMING.-.2024.1.3.1265.-.2024-01-07.23_48_33.log)

<details>
<summary>Log section showing that OnChanges runs and the mesh is updated even with the `Slot_WorldTransformChanged` method blocked from triggering changes.</summary>

```
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] On Changes on slot ID5C0300
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Pre-Changes-Values: Position: [-52,58299; 2,100381; -24,23948]; Tangent: [92,47395; 4,971813; 88,362]; Orientation: [-0.2949477; -0.2318623; 0.6575918; 0.6533136]; Width: 31,99999
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Post-Changes-Values: Position: [-52,58299; 2,100392; -24,23948]; Tangent: [92,47395; 4,971813; 88,362]; Orientation: [-0.2949477; -0.2318623; 0.6575918; 0.6533136]; Width: 31,99999
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] On Changes on slot ID5DDE00
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Pre-Changes-Values: Position: [78,01507; -6,329649; 54,30572]; Tangent: [-127,3789; 0,7074906; 12,57383]; Orientation: [-0.05931139; 0.01032817; -0.7065733; 0.7050743]; Width: 31,99999
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Post-Changes-Values: Position: [78,01507; -6,329639; 54,30573]; Tangent: [-127,3789; 0,7074906; 12,57383]; Orientation: [-0.05931139; 0.01032817; -0.7065733; 0.7050743]; Width: 31,99999
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Blocked World Transform triggering On Changes
23:49:49.238 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Blocked World Transform triggering On Changes
23:49:49.239 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Update Mesh Data on slot <WIRE_POINT>
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] On Changes on slot ID5C0300
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Pre-Changes-Values: Position: [-52,58299; 2,100392; -24,23948]; Tangent: [92,47395; 4,971813; 88,362]; Orientation: [-0.2949477; -0.2318623; 0.6575918; 0.6533136]; Width: 31,99999
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Post-Changes-Values: Position: [-52,58298; 2,100408; -24,23948]; Tangent: [92,47395; 4,971813; 88,362]; Orientation: [-0.2949477; -0.2318623; 0.6575918; 0.6533136]; Width: 31,99999
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] On Changes on slot ID5DDE00
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Pre-Changes-Values: Position: [78,01507; -6,329639; 54,30573]; Tangent: [-127,3789; 0,7074906; 12,57383]; Orientation: [-0.05931139; 0.01032817; -0.7065733; 0.7050743]; Width: 31,99999
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Post-Changes-Values: Position: [78,01505; -6,329624; 54,30569]; Tangent: [-127,3789; 0,7074906; 12,57383]; Orientation: [-0.05931139; 0.01032817; -0.7065733; 0.7050743]; Width: 31,99999
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Blocked World Transform triggering On Changes
23:49:49.254 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Blocked World Transform triggering On Changes
23:49:49.255 ( 60 FPS)	[INFO] [ResoniteModLoader/BoundedUIX] Update Mesh Data on slot <WIRE_POINT>
```

</details>

### Additional Context

I'm not sure what the best approach to do this would be, as wires would still need to update when a non-shared parent's or the individual nodes's transforms change. Ideally, any transform changes to the shared hierarchy of two nodes would not attempt to update the wire(s) between them. Only transform changes in the individual hierarchies should cause these.

The simplest fix for the majority of cases would perhaps be, to simply add an approximate check before triggering the rebuilding of the wire mesh, so that a change of .00001 doesn't trigger it.

### Reporters

Banane9

**Comment by Frooxius** [comment]
Hmm looks like the approximate comparison wasn't actually implemented, I thought it already was. 

In either case, it's now part of 2024.1.12.1336, which should help reduce the number of unnecessary updates. Thanks!
