### ISSUE TITLE
NormalScale Does Not Affect Fresnel Material

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#1117]
### Describe the bug?

When using a `NormalMap` on a `FresnelMaterial`, the `NormalScale` does not affect its intensity.

### To Reproduce

* Create a new `FresnelMaterial`
* Apply an interesting `NormalMap`
* Change the `NormalScale` to **0.00**
* Apply the material to a quad to view it

The following item is a reproduction of the above steps:

resrec:///U-LuxKitty/R-C9EB0DD73E53BB4868ACBF8065FA7162F2942864B84CF6E620D9009413E691EB

### Expected behavior

The `NormalScale` should affect the normal intensity just as in every other material with this parameter.

### Screenshots

![Resonite_HyH0cYLMV3](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/463146e8-f2dd-433d-98a3-2ec36eb89568)

The `NormalScale` in this is 0.00 which should have the same effect as no `NormalMap`, however the normals are still being pronounced.

### Resonite Version Number

2024.1.3.1265

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[Fresnel NormalScale - 2024.1.3.1265 - 2024-01-10 20_24_33.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13896115/Fresnel.NormalScale.-.2024.1.3.1265.-.2024-01-10.20_24_33.log)

### Reporters

LuxKitty

**Comment by Geenz** [comment]
I've found the solution to this.  The problem was Unity was stripping instance parameters from the shader.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/341813/fdce95b1-2539-4635-8a09-6a22f3b39afd)
