### ISSUE TITLE
Support Leap motion controller 2

### ISSUE THREAD

**Issue by mata75** [Yellow-Dog-Man/Resonite-Issues#1138]
### Is your feature request related to a problem? Please describe.

It would be great if it supports hand tracking with Leap Controller camera Sensor

### Describe the solution you'd like

https://www.ultraleap.com/developers/

### Describe alternatives you've considered

The possibility of controlling the avatar's hands with hand tracking devices

**Comment by Frooxius** [comment]
We already do have Leap Motion support, but I believe it might not work with the newer SDK's?

**Comment by ProbablePrime** [comment]
Froox is right, additionally this is a duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/8
