### ISSUE TITLE
steam_appid.txt has been missing since Build 2024.1.12.1336, causing SteamAPI failing to initialise when not launching through Steam

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#1147]
### Describe the bug?

In Build 2024.1.12.1336 (according to Steam manifest history), steam_appid.txt was removed from the root directory of the Steam Resonite installation.

This results in SteamAPI failing to initialise if you don't launch Resonite directly through hitting "Play" in Steam - often common if you are using multiple shortcuts to the Resonite exe to have multiple sets of launch arguments.

### To Reproduce

Download Resonite from Steam, browse to the original file location and try to launch Resonite directly through running Resonite.exe.

Observe that SteamAPI fails to initalise (will not show that you are playing Resonite in Steam + an exception will be thrown at the top of the Resonite log

### Expected behavior

SteamAPI to initialise correctly

### Resonite Version Number

Beta 2024.1.13.83

### What Platforms does this occur on?

Windows

### Log Files

[ERIS - 2024.1.13.83 - 2024-01-14 13_37_55.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13929938/ERIS.-.2024.1.13.83.-.2024-01-14.13_37_55.log)

### Additional Context

https://steamdb.info/depot/2519832/history/?changeid=M%3A5806059613488525279

### Reporters

bredo

**Comment by bredo228** [comment]
Figured I'd add this in quickly: If you manually create steam_appid.txt and fill it out with the correct app id for Resonite, SteamAPI functions as normal so this is caused by the file being missing.

**Comment by Frooxius** [comment]
Fixed in 2024.1.19.687 thanks!

The file got lost with the updated build process.
