### ISSUE TITLE
[Wiki] allow user css files

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#1148]
### Is your feature request related to a problem? Please describe.

MediaWiki has a feature which allows users to create custom css files to change how the website looks for them. I think this is a cool feature and it would allow users to tweak how the website looks to their personal preference.

### Describe the solution you'd like

Enable the [$wgAllowUserCss](https://www.mediawiki.org/wiki/Manual:$wgAllowUserCss) setting

### Describe alternatives you've considered

not doing this

### Additional Context

the MediaWiki page for that setting states that "It may increase security risk to users", I am guessing they mean that a user could basically lock themselves out of using the wiki if they make a css that hides all elements for example, I don't see any other way that allowing custom css files would be insecure.

**Comment by ProbablePrime** [comment]
I'm not sure about this one, If there are issues with CSS on our theme we should correct them globally rather than allowing users to edit them.

What kind of CSS changes are you looking to make @art0007i

**Comment by art0007i** [comment]
it's not issues in the css, but rather I'd like to just make a bunch of changes that I prefer to the skin I'm using that shouldn't necessarily be in the global version. Like in my specific case I want to try to make the vector skin darkmode. User css files would also allow to easily test some changes that could later be applied to global css files too.

**Comment by ProbablePrime** [comment]
I have made the decision that this will not be supported for now. I apologize but the wiki needs to stabilize a little more as we still have some theming issues.
