### ISSUE TITLE
Pulling the output of ValueLerpUnclamped<bool> causes an exception

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#1150]
### Describe the bug?

When pulling the output of a `ValueLerpUnclamped<bool>`, the world will crash (if host) or you will be kicked from the session (player).

### To Reproduce

1. Open new world
2. Using a Flux tip and the node Math -> Interpolation -> `ValueLerpUnclamped<T>`, select the `bool` type in the node picker
3. Spawn node and pull output with "R"
4. World crash (if host) or kick from world (player)

### Expected behavior

The type `bool` shouldn't be available for interpolation (not even sure how that would work).

### Screenshots

![Resonite_bYoPvdtf4H](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/a4da91f6-758f-4e9c-8755-0510e2a90c50)
![Resonite_KYXw6uBoCy](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/14fb3bad-abed-4025-be7d-547188e0a5f5)

### Resonite Version Number

Beta 2024.1.13.8

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index; Desktop

### Log Files

[J4 - 2024.1.13.8 - 2024-01-14 11_19_09.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13930923/J4.-.2024.1.13.8.-.2024-01-14.11_19_09.log)

### Reporters

j4 | j4.lc (Discord)

**Comment by TisFoolish** [comment]
Will it crash the world or the user out of the world if you're not the host?

**Comment by jae1911** [comment]
Testing with a headless, seems it only kicks players from the world if not host.

Title and contents adjusted.

**Comment by Frooxius** [comment]
Fixed in 2024.1.19.687, thanks!
