### ISSUE TITLE
Avatar Creator Incorrectly Sets IK Bone References

### ISSUE THREAD

**Issue by Thekster93** [Yellow-Dog-Man/Resonite-Issues#1153]
### Describe the bug?

The avatar creator does not appear to correctly set the IK bone references for the Lykanos avatar. As shown in the included screenshot, the bone references for the hips, spine and chest are not set to the correct bones upon clicking "create" in the avatar creator. Issue exists for both the blender file and FBX extracted from the unity package.

### To Reproduce

1. Import either the FBX or the blender file for the Lykanos.
2. Use the avatar creator to turn the model into an avatar.
3. Enter the avatar and physically move by moving your headset and not via controllers. Upper body should look "decoupled" from lower body.
4. Check the VRIK in an inspector to verify that the hips, spine, and chest bone references are not set correctly.

### Expected behavior

The hips, spine, and chest IK bone references for the Lykanos avatar would be correctly set to the hips, spine and chest respectively.

### Screenshots

![2024-01-14 20 41 28](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/87515516/6145e7a6-4012-4e81-a41a-f75e4f9438d8)
![2024-01-14 20 41 38](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/87515516/3eed8ad6-1a81-4343-bc72-2c814ae063cb)
![2024-01-14 20 42 02](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/87515516/026681cc-913a-4662-9eac-125378620afb)
![2024-01-14 20 42 13](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/87515516/93d93850-77ce-47bd-9060-431d097306be)
![2024-01-14 20 59 41](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/87515516/e057acad-1547-46a1-b272-fff12ca932bd)

### Resonite Version Number

2024.1.13.83

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus Quest 2

### Log Files

[KWINDOWS-PC - 2024.1.13.83 - 2024-01-14 16_55_29.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13933374/KWINDOWS-PC.-.2024.1.13.83.-.2024-01-14.16_55_29.log)

### Additional Context

After converting to an avatar, in the VRIK:
- Hips get set to "Spine"
- Spine get set to "Chest"
- Chest is left null

As this is a paid model, I am uncertain what files or content I can provide without violating the terms set forth by the creator of the model. However, I am happy to demonstrate the issue within Resonite if it will help resolve this issue.

### Reporters

Kori299

**Comment by bredo228** [comment]
If you're comfortable with using Blender, can you try rename the "Hip" bone to be "Hips"?

**Comment by Thekster93** [comment]
> If you're comfortable with using Blender, can you try rename the "Hip" bone to be "Hips" and then reimporting the avatar?

Renaming bones I can do. After importing the new blender file, the bones are correctly detected and set. 
![2024-01-14 23 24 55](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/87515516/2808f5f8-577a-4c95-a6b4-33a8d22e3984)

**Comment by bredo228** [comment]
Cool, just an issue with the bone naming on that specific avatar then - Resonite has requirements for bone naming in order to set up the IK - you can find these at https://wiki.resonite.com/Humanoid_Rig_Requirements_for_IK

(apologies if this double posts, i think github ate my response via email)

**Comment by Thekster93** [comment]
> Cool, just an issue with the bone naming on that specific avatar then - Resonite has requirements for bone naming in order to set up the IK - you can find these at https://wiki.resonite.com/Humanoid_Rig_Requirements_for_IK
> 
> (apologies if this double posts, i think github ate my response via email)

Darn. I was simply unfortunate enough to have purchased an avatar with an invalid name for the pelvis then. Thank you for the help! I suppose I'll go ahead and close this issue since it's a documented requirement.

**Comment by Electronus** [comment]
It might actually be a good idea, to post reopen this as either a request for a tweak to allow this type of naming or make a new post for it.

this seems to be a fairly common issue.
