### ISSUE TITLE
NewLine is repeated twice in Strings/Constants

### ISSUE THREAD

**Issue by 989onan** [Yellow-Dog-Man/Resonite-Issues#1154]
### Describe the bug?

The "NewLine" node constant is repeated twice in Strings/Constants menu, and the first one is non functional.

### To Reproduce

Open protoflux browser, navigate to Strings, then constants. There are two "NewLine" entries there

### Expected behavior

there should only be one

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29756848/bd4e1668-a396-4f66-b69b-0580433cd188)

### Resonite Version Number

Beta 2024.1.13.83

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[CHEW-PC - 2024.1.13.83 - 2024-01-14 21_51_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13934361/CHEW-PC.-.2024.1.13.83.-.2024-01-14.21_51_14.log)

**Comment by BaxterOttoman** [comment]
These both give different outputs, one being the Linux line ending (the new line character) and the other the windows line ending (carriage return character followed by the new line character).
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15233062/f7cfb06d-4404-41ae-b7a6-338368950a09)

**Comment by 989onan** [comment]
Ah there it goes, yeah this is fixed
