### ISSUE TITLE
ProtoFlux Node ExternalObjectInputWithFilter`2 causes a world update exception

### ISSUE THREAD

**Issue by 989onan** [Yellow-Dog-Man/Resonite-Issues#1159]
### Describe the bug?

Evaluating the input of ExternalObjectInputWithFilter`2 of any type causes a world update exception

### To Reproduce

spawn provided item, click button and crash to local.

### Expected behavior

this node shouldn't cause a world update exception, and just return null.

### Screenshots

Item that causes a crash using the node: resrec:///U-989onan/R-fb48f151-27e4-486e-b716-32249348f59c

### Resonite Version Number

Beta 2024.1.13.83

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[CHEW-PC - 2024.1.13.83 - 2024-01-15 15_35_46.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13942873/CHEW-PC.-.2024.1.13.83.-.2024-01-15.15_35_46.log)

**Comment by Frooxius** [comment]
Why did you use this node? This one is normally not meant for direct use. We'll likely just make this node not able to be spawned.

**Comment by Frooxius** [comment]
Fixed in 2024.1.19.687! You should no longer be able to instantiate those node types.
