### ISSUE TITLE
Add support for copying texture/image data into clipboard

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1164]
### Is your feature request related to a problem? Please describe.

Currently the only media that can be copied into the clipboard is text from text field. Being able to copy other media - e.g. textures and audio clips would allow to more easily interact with external software - e.g. copying a texture, pasting into Photoshop, editing and pasting it back in.

### Describe the solution you'd like

Add support for copying in-game textures/images into the clipboard. There will likely be a new "Copy" context button and a button in the inspector for the textures to initiate the action.

### Describe alternatives you've considered

The textures can be exported to a file, but this adds additional steps, which is slower.

### Additional Context

We'd also consider adding additional formats - e.g. audio data, but we'll do this through a separate issue.

**Comment by 5H4D0W-X** [comment]
Pressing CTRL-C on desktop while holding a compatible object (e.g. photo) or reference to an asset should copy the asset to the clipboard as well

**Comment by Frooxius** [comment]
This is now supported in 2024.1.24.834!
