### ISSUE TITLE
Supporter Badge

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#1176]
We currently use a very old Patreon Logo to represent Patreon Supporters in-game.

We'll be updating this to use a new badge designed by the content team, this badge will be used as a generic "Supporter" badge that is applied regardless of any supporting method. So if we add other methods than Patreon in the future this badge will be used.

![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/323b46b6-4a97-42ea-95c7-29844d33dcfe)
![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/97bff63a-5a79-4cc8-9f51-c6b45a897169)
![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/47813405-738f-4484-abaa-c2b2e830bdc6)

It looks like this in-game:

![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/196d3cd6-ea1e-46ef-aec5-b3d03c2b89c1)

**Comment by TehTurk** [comment]
Is there a reason the supporter badge looks like this? It looks kind of funky to indicate general support/monetary contribution to the platform.

**Comment by ProbablePrime** [comment]
tagging in @ChromaShiba 

This design was completed literally months ago though :D

**Comment by TehTurk** [comment]
All good! I imagine it was a time where feedback might not have been aplenty

**Comment by ShrikeAlvaron** [comment]
My first thought when I see it is a coin, so personally it fits for a monetary supporter badge

**Comment by TehTurk** [comment]
I mean I guess? I thought it was some energy particle, or something from a really old video game. Like the empty space in-between makes it feel more like a pokemon badge. Coins are rounder. Though I will hold off on adding more personal thoughts until Chroma chimes in. 

 I'm here more asking why, because it's not what I would think at first glance indicating that.

**Comment by Charizmare** [comment]
Out of curiosity, would this also include changing the "Patreon" channel in the discord and changing the name of the "Is User Patron" Proto(flux) node?

**Comment by lxw404** [comment]
My only suggestion to this is to have colored reflections so it looks metallic (either by using `PBS_Metallic` directly, or giving the specular map some [color](https://docs.unity3d.com/Manual/StandardShaderMaterialCharts.html)).

**Comment by ProbablePrime** [comment]
This is in my current "Launch Promises" update, so is happening soon.

**Comment by ProbablePrime** [comment]
I have transferred this to Ryuvi while I work on other matters.

**Comment by Frooxius** [comment]
This is now live in 2024.9.13.672! Thanks!
