### ISSUE TITLE
abillity to turn off radial ui menu items without turning them off

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#1178]
### Is your feature request related to a problem? Please describe.

wish there was a way to disable the ability to click on context menu buttons without disabling them in the scene inspector

### Describe the solution you'd like

a simple button or option to not allow people to click on context menu items when they are "disabled"

### Describe alternatives you've considered

just disabling them outright

**Comment by ProbablePrime** [comment]
In the ContextMenuItemSource component, you can toggle "ButtonEnabled" to prevent clicking on the item, it also greys out the item automatically for you.
