### ISSUE TITLE
ProtoFlux object crashing world in less than 30 seconds

### ISSUE THREAD

**Issue by archer007** [Yellow-Dog-Man/Resonite-Issues#118]
### Describe the bug?

A sign originally made in the legacy game that uses HTTP GET to call an API, runs some manual JSON parsing, and display text data crashes worlds in less than 30 seconds when it is spawned out

resrec:///U-Archerj2/R-df0f78fe-9109-4c6e-9c37-50dac132a3bf

### To Reproduce

Spawn out the sign and wait for less than 30 seconds

### Expected behavior

I expected the sign to have odd technical issues or simply work since it had been migrated over but I did not expect it to hard crash worlds

### Resonite Version Number

2023.10.13.723

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Valve Index

### Log Files

https://pastebin.com/Z5846peK

### Additional Context

I used the Logix node OnLoad so I am not sure if that is contributing to the problem. It's very hard to debug when it quickly crashes a world, including your local and cloud world

### Reporters

Discord: archer5574

**Comment by Zyzyl** [comment]
I took a quick look at this. The ProtoFlux on this item is quite complex (over 200 nodes), I don't think the development team is likely to sort though this on their own. The OnLoaded is not a problem _per se_, the problem can be triggered by calling the same bit of flux by other methods (button, manual call input). This item can be made eaiser to debug by opening the debug window (Dash Home screen, bottom right), going to the "Web Hosts" tab and removing the entry for "lemmy.world". After doing that, the object does not cause crashes unless accessing that site is approved again because the flux downstream of GET string cannot execute.

**Comment by archer007** [comment]
The problem was the almost immediate crash and removing the permission for the GET appears to stop that. Thank you! I will likely close this issue if I don't run into any further problems debugging. It was my first Logix project so I'd love to make sure it stays running in Resonite

**Comment by shadowpanther** [comment]
It'd be better to narrow the issue down to a minimal combination of nodes that still cause the crash.

**Comment by LucasRo7** [comment]
I tried separating and running different parts of the code separately

If you don't allow access to the 3rd party host, the code won't fetch the new text, and will only have to process a string of 5934 characters which were stored when the object was saved. If you do allow 3rd party access, it'll do the GET request and process a limited number of entries of the JSON before it reaches execution time limit and stops
Reaching execution time limit is the only reason it doesnt crash immediately after the GET request, when I tried to run this part of the code, I got a string of 520k characters, which is basically ~1Mb of text

After the GET request and the processing of the received data, starts the part of the code that is set to run every 30 seconds. From what I understand, that part is trying to do this:
```
For every single character in the text
	Count every "||" in the text

Pick a random number between 1 and that number divided by 3
Multiply the result by 3 and subtract 2

For every single character in the text
	Count every "||" in the text
	If the count == the chosen random number,
		Append the character to a variable

Make sure to replace all \" with "
If there's a "astodon", "eddit", "emmy" or "moderator" in the string, repeat everything from the start
```

This is what the flux actually does (in general):
```
For every single character in the text
	Substring 1 character
	If its a "|", add 0.5 to a variable

Count up two variables up to that number divided by 3, but using a while loop??

Pick a random number between 1 and the second count(which should be equal to the first count/3)

For every single character in the text
	Substring 1 character
	If its a "|", add 0.5 to a variable
	Else
		StringJoin the character to an unused variable **
		If the count == the chosen random number,
			StringJoin the character to a variable (which is driving the text in the sign)
			Replace all \" with "
			If you find "astodon", "eddit", "emmy" or "moderator" in the string
				Repeat everything from the start
```


I think the biggest issue is that you are trying to substring every character and use string join on that megabyte of text. 
A simple for loop counting of the "||" already takes 1 whole second to run, and a loop that adds every single character is enough to reach execution time limit before reaching 100k characters(the second for loop does exactly that, without even using the result)

World crashing aside, I think this boils down to a optimization problem, there are probably better ways to process, store and index all the messages, without having to repeatedly scrub through ~1Mb of text every 30 seconds

**Comment by Zyzyl** [comment]
Hey @archer007 - did you have any more problems with this? If not I'd suggest closing this issue to help keep the repo tidy

**Comment by archer007** [comment]
Thank you for the analysis. I will likely just rewrite this as it is poorly optimized
