### ISSUE TITLE
IsHostAccessAllowedUrl Node with null Url Input causes World Crashed

### ISSUE THREAD

**Issue by rabbuttz** [Yellow-Dog-Man/Resonite-Issues#1180]
### Describe the bug?

IsHostAccessAllowedUrl Node with null Url Input causes World Crushed.

### To Reproduce

To reproduce the bug, just spawn IsHostAccessAllowedUrl Node and spawn a Display node or connect to other nodes with null Url.

### Expected behavior

World Crushed will be shown.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49971163/6fedcfff-4c1c-41cd-bda1-7e7218980290)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49971163/335b13a4-9881-40c2-ab5b-b24c78b4b249)

### Resonite Version Number

Beta 2024.1.13.83

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[RABBUTTZ - 2024.1.13.83 - 2024-01-18 19_26_44.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13975448/RABBUTTZ.-.2024.1.13.83.-.2024-01-18.19_26_44.log)

**Comment by Frooxius** [comment]
This has been fixed in 2024.1.19.687, thanks!
