### ISSUE TITLE
ProtoFlux Procedural Wire Meshes twist badly

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1181]
### Describe the bug?

This was an issue before already, but is much more noticable now that the wire resolution has decreased. The procedural mesh used for the ProtoFlux wires isn't twisting in a desirable way. Even slight misalignments of the nodes causes ugly twisting, see screenshot provided by Shrike.

If this is revisited, an additional thing that I was meaning to suggest was allowing the wires to have two node connection positions, the current one plus one that's 180° twisted or "flipped", then prefer the connection position that results in the least amount of twist. This way, in constallations where it currently has to twist 180° because the node on the other side is flipped, it could stay flat with no twist necessary.

### To Reproduce

Spawn ProtoFlux nodes and connect the wires.

### Expected behavior

The wires should be visually pleasing to look at, and connect "flat" to each socket, gracefully twisting until it reaches the node on the other side. If both nodes are facing the same way, and one is just rotated around the forward axis, I think the wire should try to stay completely flat and only form a curve in a sort 2D sense, without twisting.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/fd86548c-cf86-4cea-a751-12527be5262f)

### Resonite Version Number

2024.1.13.83

### What Platforms does this occur on?

Windows

### Log Files

N/A

### Reporters

Shrike, Jack

**Comment by epicEaston197** [comment]
To add to this I think raising the segment count of the wire mesh to 32 would help greatly

**Comment by JackTheFoxOtter** [comment]
> To add to this I think raising the segment count of the wire mesh to 32 would help greatly
No. The higher vertex count previously was just masking the issue with the twist math. I think fixing the twist should be enough to make the wires look good again. The resolution should be fine once they twist properly.

**Comment by Banane9** [comment]
I noticed this the other day too and tried some different orientations, but none seemed to make the twisting go away.

This was even a problem with nodes snapped to a Redprint, where any miniscule offset would cause the wire to be at an angle to the surface.

**Comment by VirgilCore** [comment]
This is a result of the recent change of the protoflux wires being changed from having 128 subdivisions to 16

**Comment by JackTheFoxOtter** [comment]
> This is a result of the recent change of the protoflux wires being changed from having 128 subdivisions to 16

Partially, the wires were always a bit weird, but you didn't notice with the higher resolution. I think it's just that the high subdivisions were masking the weirdness of the twisting math enough that noone really noticed, at least not negatively.

**Comment by Frooxius** [comment]
I've reworked the math completely in 2024.1.24.834, wires should now behave much better. Thanks for report!
