### ISSUE TITLE
3D Texture Doesn't Upload To Other Users In The Session

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#1193]
### Describe the bug?

When a user uploads a 3D Texture to a session, no other users get the asset until it is uploaded directly to the cloud.

### To Reproduce

* Import a 3D Texture
* Have a second user join the session

Here is link to a reproduction item that can be spawned by one user in the world while another user in the world observes:
resrec:///G-Bright-Spark/R-F1A54F3183CCE88A788295DF87893011438A0F948C66441EA44F3F1371C28AEA

### Expected behavior

The 3D Texture should upload to all users in a session.

### Screenshots

Uploading User:

![2024-01-19 08 24 10_rz](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/140f35ef-d209-4ed7-96d7-41b8b348261c)

Observing User:

![2024-01-19_08 24 04](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/767e463c-c57e-4891-8922-2d97bb1311fd)

### Resonite Version Number

2024.1.18.755

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

Uploading User:

[3DTexture_LocalUpload - Originating User - 2024.1.18.775 - 2024-01-19 03_18_15.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13986826/3DTexture_LocalUpload.-.Originating.User.-.2024.1.18.775.-.2024-01-19.03_18_15.log)

Observing User:

[3DTexture_LocalUpload - Other User_-_2024.1.18.775_-_2024-01-19_08_18_37.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13986827/3DTexture_LocalUpload.-.Other.User_-_2024.1.18.775_-_2024-01-19_08_18_37.log)

### Reporters

LuxKitty, Nytra

**Comment by Nytra** [comment]
This affects locally uploaded 3d textures. Other users will not be able to see it by default. However if Direct Load is enabled on the 3d texture it will be able to be seen by others.

**Comment by Frooxius** [comment]
What was the URL of the local texture in the replication? The screenshots are too low resolution to read that.

**Comment by Nytra** [comment]
@Frooxius

![2024-01-19 10 27 17](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/af7f3ea5-ccc4-4ce7-a7db-a5099d9d6dc1)

**Comment by Frooxius** [comment]
Thanks!

**Comment by Frooxius** [comment]
Fixed this in 2024.1.24.834! Thanks!
