### ISSUE TITLE
References to "UserRef" break when duplicating object.

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#12]
### Describe the bug?

Some component use what's called a UserRef to store references to Users. These components include ValueUserOverride, DestroyOnUserLeave and a bunch of other ones. Any references to any field within the UserRef itself will be broken when duplicating.

### To Reproduce

1. Create an empty object
2. Attach a DestroyOnUserLeave component to it
3. Attach a ReferenceField<IWorldElement> to it
4. Drag and drop any field from the UserRef on the DestroyOnUserLeave component into the reference field.
5. Duplicate the empty object
6. The reference field will be null on the new object even though it should totally get carried over

### Expected behavior

The reference does not get cleared when duplicating an item

### Screenshots

before duplicating:
![inspector before duplicating](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/038a28f1-0263-49a5-80ec-d68bf780dc95)

after duplicating: 
![inspector after duplicating](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/83007a1f-47c6-4c04-966e-03ae608304a2)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Additional Context

To me this is a very problematic bug as I have many creations that are completely broken by this bug.

### Reporters

art0007i

**Comment by DaryeDev** [comment]
Bump!

**Comment by art0007i** [comment]
ok I've made a log and a reproduction item.

Item Link:
`resrec:///U-art0007i/R-3ac097f6-b15f-4b11-8e0f-4ea044146c93`
Log:
[ROTHORN - 2023.10.13.743 - 2023-10-18 14_05_12.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13024494/ROTHORN.-.2023.10.13.743.-.2023-10-18.14_05_12.log)

the reproduction object displays the state of a few reference fields, which all get reset to null (ID0) after duplication.

The log and item also reproduces issue #27, as both issues are very similar

**Comment by Frooxius** [comment]
Thanks for the info, I'll take this one on. I'm aware this was an issue in pre-release testing that we didn't get the time to tackle.

**Comment by Frooxius** [comment]
This is fixed now, thanks! In 2023.11.8.335
