### ISSUE TITLE
Historic storage space awards

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#1201]
We'll be applying historical storage space awards to accounts from the prior events:
- Translation rewards
- MMC
- Twitch Stream Rewards.

If you received one of these **in the past**, and have **not** previously direct messages me, please direct message me on discord the details and I'll get them allocated in **the future when I am able to.**

**Comment by ProbablePrime** [comment]
I've started work on this, we need some tooling to handle it. Space awarding on Resonite requires a sort of Audit trail to store where and why the space was awarded.

We have these for patreon and storage sharing etc, but not for these random events from years ago :D.

I'll check with Froox on the best approach.

**Comment by ProbablePrime** [comment]
Froox got back to me and I have the right path forward here yay.

**Comment by ProbablePrime** [comment]
These have been handed out, if you dont have it correctly fill in this form: https://files.yellowdogman.com/apps/forms/embed/bTTaqdSeTp9WneQkmwiSfW74 and i'll get back to you.

**Comment by XDelta** [comment]
btw, the translation option on that form says price instead of prize

**Comment by ProbablePrime** [comment]
Thank you
*fixes*
*cries in the corner*
