### ISSUE TITLE
[Linux] LNL update now causes LNL connections to not work

### ISSUE THREAD

**Issue by yoshiyoshyosh** [Yellow-Dog-Man/Resonite-Issues#1226]
### Describe the bug?

after the recent LNL update, Linux native is unable to make connections with neither NAT punchthrough nor the LNL relay, and either falls back to steam network sockets if launched through steam, or is unable to connect entirely if not launched through steam. 

### To Reproduce

1. use Linux native
2. try connecting to a session
3. observe how it does not connect via NAT punchthrough nor the LNL relay

### Expected behavior

ability to connect to instances with NAT punchthrough or the LNL relay

### Resonite Version Number

2024.1.23.176

### What Platforms does this occur on?

Linux

### Log Files

[launched through steam](https://gist.github.com/yoshiyoshyosh/f0bdc241f9e2aa3ba9e25f3bdab02f55)

### Additional Context

there appears to be a non-linux library trying to be loaded (the filename gives off "this should be a native lib" vibes)

### Reporters

yosh

**Comment by sveken** [comment]
Seeing this on docker too.

**Comment by Frooxius** [comment]
It looks like the library is mistakenly detecting that it's running on Windows, rather than Linux and tries to use the Windows implementation of the sockets. I'll have a look.

**Comment by Frooxius** [comment]
This should be fixed in 2024.1.23.613, thanks!
