### ISSUE TITLE
IPv6 Direct Connections do not work since the update to LNL 1.2.0

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#1228]
### Describe the bug?

Since the update to LNL version 1.2.0, direct IPv6 connections to sessions do not work, failing to establish a connection.

### To Reproduce

Try to connect to a headless session (easiest) over a direct IPv6 connection. You will need to use the "OpenWorld" node for this.

The ReSync lounge is always open and can be used to test this: `lnl://v6.us01.voxelbone.cloud:25570`

### Expected behavior

Connection to be established and the world joined.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/e86803c4-44e3-425b-83e0-213d32532581)

### Resonite Version Number

Beta 2024.1.23.176

### What Platforms does this occur on?

Windows, Linux

### Log Files

[linuxheadless - pluto - 2024.1.23.176 - 2024-01-23 20_17_55.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14020028/linuxheadless.-.pluto.-.2024.1.23.176.-.2024-01-23.20_17_55.log)
[windowsclient - ERIS - 2024.1.23.176 - 2024-01-23 20_18_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14020031/windowsclient.-.ERIS.-.2024.1.23.176.-.2024-01-23.20_18_35.log)
[windowsheadless - DYSNOMIA - 2024.1.23.176 - 2024-01-23 20_36_20.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14020032/windowsheadless.-.DYSNOMIA.-.2024.1.23.176.-.2024-01-23.20_36_20.log)

### Reporters

bredo
Ocelot342
Canadian_RedZ

**Comment by Frooxius** [comment]
Did this work before the change?

**Comment by bredo228** [comment]
> Did this work before the change? From my understanding IPv6 support required mods.

Yes, this worked before the change. The mods facilitated joining through the session browser etc, but you could directly connect through the "OpenWorld" node with no issues.

**Comment by jae1911** [comment]
Yeah can also confirm it worked before, I use v6 for my personal stuff.

**Comment by Frooxius** [comment]
I see! Thanks for the info.

I think this might be due to the native sockets not supporting IPv6. I'll probably just disable those for now.

**Comment by bredo228** [comment]
[ERIS - 2024.1.19.687 - 2024-01-23 22_36_59.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14021656/ERIS.-.2024.1.19.687.-.2024-01-23.22_36_59.log)
[glaceon - 2024.1.19.687 - 2024-01-23 09_36_18.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14021670/glaceon.-.2024.1.19.687.-.2024-01-23.09_36_18.log)


Couple logs from Build 2024.1.19.687 showing the direct connection functioning properly

**Comment by bredo228** [comment]
Works again in Build 2024.1.23.613!

**Comment by Frooxius** [comment]
Thanks! Closing this!
