### ISSUE TITLE
Allow Importing of Armatures without Mesh.

### ISSUE THREAD

**Issue by Azavit** [Yellow-Dog-Man/Resonite-Issues#1232]
### Is your feature request related to a problem? Please describe.

I have found cases where I want to import a .fbx/.glb/.blend that has a baked animetion on an armature for creating Anchor based animetions using pose constraints.

This could also be used for other things such as points in space where one wants to put objects or any other data that doesn't include mesh data.

### Describe the solution you'd like

For the import to not just fail to import a file with out a mesh but still with object position data and animetions.

### Describe alternatives you've considered

Applying a skinned mesh to the armature and removing the mesh once it is in Resonite.

**Comment by Frooxius** [comment]
This should already be possible. If the import fails, you'll need to provide us with diagnostic information - sample file and logs.

You can also just delete the SkinnedMeshRenderer after importing, keeping the armature.

**Comment by Azavit** [comment]
OH it does work now, thought it wasn't working due to the comment here and previous experiences.
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1204#issuecomment-1905305073

Sorry for the issue.
