### ISSUE TITLE
Paste into StaticTexture2D Asset to Replace It

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#1237]
### Is your feature request related to a problem? Please describe.

With the addition of pasting textures between Resonite and external applications, there is a much added fluidity to modifying and updating things in game, however when pasting a texture into a field, it will currently only replace the singular reference to that texture.

Sometimes you have a texture being used in multiple places and materials, and it is beneficial to be able to replace them all at once, say for instance when you are working in photoshop and you want to test a change on every single instance of a texture in the world so that you can iterate quickly on changes you are making.

### Describe the solution you'd like

There should be some sort of UI on the `StaticTexture2D` itself to allow pasting to update that asset with a new URI of the pasted asset.

### Describe alternatives you've considered

The alternative is to paste the image, import as new asset, inspect that new image, find the asset url, and then copy and paste into the old asset, which is quite tedious.  I'm not aware of any other ways to do this at the moment.

**Comment by Frooxius** [comment]
Added this in 2024.1.26.617, thanks!
