### ISSUE TITLE
Import Dialog spawns incorrectly

### ISSUE THREAD

**Issue by darbdarb** [Yellow-Dog-Man/Resonite-Issues#1245]
### Describe the bug?

When pasting an image or video to get the import dialog to pop up it spawns facing away unless ur facing the direction it spawns in

### To Reproduce

1. Screenshot or import an image from clipboard
2. Import dialog spawns

### Expected behavior

Import dialog should be facing you

### Screenshots

i was standing here when importing ![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/27961710/817f34be-2725-4a18-bf3d-f348c1f6697a)
its facing this way 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/27961710/961adcff-ba5d-45be-a9dd-c42c163a11fa)

### Resonite Version Number

2024.1.24.840

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index with FBT without it behaves normally, Desktop

### Log Files

[DESKTOP-KQ0I277 - 2024.1.24.840 - 2024-01-26 14_10_12.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14059891/DESKTOP-KQ0I277.-.2024.1.24.840.-.2024-01-26.14_10_12.log)

### Reporters

1. darbdarb, Discord: darbdarb_
2. Sox, Discord: its_sox
3. Charizmare, Discord: charizmare

**Comment by darbdarb** [comment]
Importing the image faces you which is intresting

**Comment by Frooxius** [comment]
Fixed in 2024.1.26.617, thanks!
