### ISSUE TITLE
Add UIXCanvasBlank and UIXCanvasSample to CreateNew\Object

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1249]
### Is your feature request related to a problem? Please describe.

When doing UIX it is preferred to have a starting point instead of creating the canvas and image all by scratch this is more commonly achieved by creating a facet but this comes with some bloat like the text and the image in the main background being transparent that has to be modified later 

so i'm proposing that you could add UIXCanvasBlank and UIXCanvasSample to the create new menu as seen in the dev logs

### Describe the solution you'd like

i would like to see UIXCanvasBlank and UIXCanvasSample added to the create new menu

example from the latest dev log
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/525ba3a2-b4e3-483a-9289-8deb4ce239a2)

### Describe alternatives you've considered

Using a facet instead but this comes with the above bloat that I mentioned before

### Additional Context

since this is so useful for debugging for development I think the community should be able to have it as well

**Comment by Frooxius** [comment]
This has already been done since you saw it in the devlogs - it's just not merged into the main branch.

Remember devlogs are showing work-in-progress that's not necessarily been released yet, but that's coming.

**Comment by epicEaston197** [comment]
I know that but I just noticed it a lot in the dev Logs relating to the settings rework but it never appeared in public builds and just thought it would be really useful to have

**Comment by Frooxius** [comment]
That's what I'm saying - the reason it's not appearing in public builds is because it's part of work in progress builds. You don't need to make issues for things like this - they're already implemented, they just haven't been merged in.

Once the settings are done and these changes are merged in and released, the features you see in devlog will be available to everyone.

**Comment by epicEaston197** [comment]
okay thanks that makes a lot of sense I will be closing this issue as it's not necessary
