### ISSUE TITLE
Unshare button is greyed out when trying to unshare a public folder, but is interactive everywhere else

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#126]
### Describe the bug?

When trying to unshare a public folder, or item, the button is greyed out. 

The button is interactive with either nothing selected, or a item/folder selected that cannot be unshared by the user.

### To Reproduce

Try unshare a public folder or item.

### Expected behavior

The unshare button should not be blocked when trying to unshare.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91010433/1b4d1120-3228-4602-97cd-81795a32efaa)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, HP reverb G2 (although, headset doesn't affect this issue)

### Reporters

Resonite: Stellanora

Discord: stellanora

**Comment by Enverex** [comment]
I just noticed this. It basically seems to have it's functionality inverted; Everything in my inventory has the "Unshare" option (despite not being shared) EXCEPT for the one shared folder I do actually have shared, wherein the Unshare option greys out when I click that folder.

**Comment by TeknoCatron** [comment]
Still the case in Beta 2023.11.25.49
Function of the unshare button is inverted and being mentioned by several users.
Can we please get this moving to the right direction as people are unable to unshare folders/items still.

**Comment by Frooxius** [comment]
I'll try to have a look soon.

**Comment by Frooxius** [comment]
Fixed in 2023.11.28.1365, thanks!
