### ISSUE TITLE
Title on Cloud Status Facet is not localised

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#1267]
### Describe the bug?

The title "Cloud Status" is not localised on the default Cloud Status Facet (even if spawned from the Resonite Essentials folder) despite the key `Indicator.ServerStatus.Status` existing (for instance, tested with French).

### To Reproduce

1. Change game locale to another one that has the `Indicator.ServerStatus.Status`
2. Spawn the facet from Resonite Essentials -> Facets -> Templates
3. See it is not localised

Alternatively:
1. Spawn the facet
2. Inspect it
3. Go through the hierarchy until you end up with the two "Text"
4. Observe that the status itself ("Good", "Slow", etc) are driven correctly by `LocaleStringDriver` but the title itself isn't

### Expected behavior

The title should be driven by `Indicator.ServerStatus.Status` and be localised.

### Screenshots

The default:
![Resonite_CqcRDHc5cC](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/edebcd5f-e691-4e54-a336-c63705a3e57a)

With the `LocaleStringDriver` added (as it should be shown):
![Resonite_pNYOk5stcB](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/d029463e-4cb3-4319-9d37-8d6ba50af4b2)

### Additional Context

Issue was also reported on the locale-specific repo: https://github.com/Yellow-Dog-Man/Locale/issues/37

### Reporters

U-j4 | j4.lc (Discord)

**Comment by RyuviTheViali** [comment]
This has been fixed on the server status facet, and will be pushed to existing versions of the facet once a version update for the facet can be done. Closing this in the meantime though, thanks
