### ISSUE TITLE
not meeting password complexity falsely errors as "passwords don't match'

### ISSUE THREAD

**Issue by SpudsMcCat** [Yellow-Dog-Man/Resonite-Issues#127]
### Describe the bug?

if your password does not meet the minimum complexity for some reason (say no lower-csse letters) the error reports that password do not match

### To Reproduce

make a password that lacks requirements
enter it identically
read error message 

### Expected behavior

error states that the password does not meet required complexity. would be be nice to list what is missing, or the requirements again 

### Resonite Version Number

2923.10.7+ cloud update

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop 

### Reporters

Spuds

**Comment by ProbablePrime** [comment]
I'm working in the area of registration errors already, so i'll grab this.

**Comment by ProbablePrime** [comment]
Ok,
This string is "Account.ErrorPasswordMismatch" and it is only used twice within our codebase. In both cases, it is used in correct locations.

I cannot reproduce this at all. I will however update the locale string for invalid password to include the requirements, this is a good call.

**Comment by ProbablePrime** [comment]
@SpudsMcCat Second call, do you have more information?

**Comment by SpudsMcCat** [comment]
sorry, missed the Q first time. this was while creating a new user from the game. I was in desktop modr

**Comment by SpudsMcCat** [comment]
I just attempted this again and got the correct error message.
ok to close.

**Comment by ProbablePrime** [comment]
Thank youu!
