### ISSUE TITLE
Cloud home music player is set to 1.49x speed by default

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1270]
### Describe the bug?

The music player in the default cloud home world is set to 1.49x speed by default.

Cloud home world record URL: resrec:///G-Resonite-Team/R-c3f6fd32-d82f-4f48-80f1-87a05b184650

### To Reproduce

Load default cloud home world and check the music player

### Expected behavior

Music player speed set to 1.00x by default

### Screenshots

![2024-01-29 19 47 29](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/8ce9ad6d-9541-48a1-9d37-1aee1f8e82fd)

### Additional Context

N/a

### Reporters

Nytra (discord: nytra)

**Comment by RyuviTheViali** [comment]
This has been fixed in the Cloud Home now. Closing this, thanks!
