### ISSUE TITLE
Update status page

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#1272]
Our status page(status.yellowdogman.com), is currently using Cachet.

Cachet's functionality is unfortunately somewhat limited and it is undergoing a re-write by the original author.

@sveken Recommended, https://github.com/louislam/uptime-kuma and we'll swap over to that.

We can easily get discord alerts about outages too!

**Comment by ProbablePrime** [comment]
Got a test page up here: https://status2.yellowdogman.com/

It is looking very nice, the only thing we'd miss would be the metrics at the bottom. Plus Discord alerts are working:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/ae3f7719-4151-4749-bbc5-488f2d56d2c2)

I'll finish the overhaul tomorrow.

**Comment by jae1911** [comment]
If you also want some more fine-grained data, I can also recommend having a [Grafana](https://grafana.com/) on the side.

I'm using it for https://status.tedomum.net as well as a bunch of other projects and personal use.

(Could also be used to get funny graphs from the wiki :D https://grafana.wikimedia.org/d/000000208/edit-count?orgId=1)

**Comment by ProbablePrime** [comment]
@jae1911 My issue with Grafana has always been having a datasource that makes it truly shine.

Uptime Kuma can write directly into Prometheus so I'm looking into that.

Do you have any experience with it?

**Comment by jae1911** [comment]
I've never used Grafana in pair with Uptime Kuma but testing it, could create this [test dashboard](https://m.cheese.j4.lc/public-dashboards/57da9bd92c10442c888535ced182100c) pulling data from a [test instance of Uptime Kuma](https://reso.dash.test.j4.lc/status/test).

I also usually use it with [node_exporter](https://github.com/prometheus/node_exporter) to get machine stats (also shown on the test dashboard).

I also need to test however it is done to pull out stats from MediaWiki.

**Comment by jae1911** [comment]
Great!
If you want them, I can give you a compose and all the related configs as well.

**Comment by ProbablePrime** [comment]
Sure if you have a working compose hit me with it.

I'll be open sourcing our compose files when i can too. Giving back to the community etc.

**Comment by ProbablePrime** [comment]
The last part of this is moving Metrics from the bottom of the old cachet status page to a new location. 

This is now done: 

![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/da82f9da-2392-4545-90d9-16733f348fa8)

But I still need to do the following items:
- [ ] Configure grafana to have the correct hostname
- [ ] Figure out making the above dashboard public
- [ ] Double check with the team on the publicity of the data

After that we'll decomission cachet and be up on uptime kuma with grafana for the metrics.

**Comment by jae1911** [comment]
To make a dashboard public it's pretty easy nowadays: https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/

Otherwise, there's still the option of creating an org with anonymous access enabled.

**Comment by ProbablePrime** [comment]
I've read the link you've provided before. What I want is metrics.yellowdogman.com to default to showing any unauthed user the above dashboard. 

The public link feature often creates really long unwieldy urls, which I do see you have as CNAMEs but that means extra urls to remember.

It sounds like the Org idea is probably best.

**Comment by jae1911** [comment]
The anonymous org thing will give something like that: https://monit-grafana-open.cern.ch/ with a homepage and everything.

It's also pretty easy to setup: https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/#anonymous-authentication

**Comment by ProbablePrime** [comment]
You are the best, thanks!

**Comment by ProbablePrime** [comment]
And we're out. Copy pasta'ed announcement here:

> I decommissioned our old status page, and replaced it with the one I was experimenting with. You can now find that at https://status.yellowdogman.com/ It works very nicely. Alerts from stuff going down are sent to ⁠alerts and we're working on making those... make more sense. Some of the formatting is weird 🙂
> 
> As our old status page provided some publicly accessible metrics and our new one does not, I also created https://metrics.yellowdogman.com/ which has these same metrics. All of the metrics featured on this page have been public since launch but not rendered nicely and now they are. Each chart has a description and a link to a wiki page for more information(that I may or may not have written yet).
> 
> If you'd like to discuss these new shiny toys, head to: ⁠New Status page and Metrics Dis…
> 
> 🙂 Enjoy!
> 
> Oh and the system that powers all of these new websites is open source at: https://github.com/Yellow-Dog-Man/monitoring-compose

> A huge thanks to @Sveken @bredo @Jae “awa” J4 for their help.
