### ISSUE TITLE
Static when adjusting pitch on procedural SineWaveClip audio component

### ISSUE THREAD

**Issue by mwalker420** [Yellow-Dog-Man/Resonite-Issues#1280]
### Describe the bug?

I'm encountering static (or crackling sounds) when dynamically adjusting the frequency of the procedural audio SineWaveClip component. This is all pretty new to me to I'm not even sure if I'm setting up audio properly. Currently There's a SineWaveClip being fed into an AudioClipPlayer which I think I successfully set to loop. Then AudioClipPlayer is then fed into and AudioOutput component.

It all sounds fine if I don't move the frequency slider but I want to have some interaction that changes the frequency dynamically. Is there a better way to handle audio or is this a issue with the component?
![ProceduralAudioSineWave](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/77633057/459731a1-fad5-4f78-a8a5-576bae1a7780)

Other users in the same space hear the same issue.

### To Reproduce

create a slot with the components described above, ensure the clip is playing back in loop mode then adjust the pitch slider manually.

### Expected behavior

A clear tone changing pitch without crackling.

### Resonite Version Number

2024.1.27.608

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest via Steam Link

### Log Files

[LIAM - 2024.1.31.744 - 2024-01-31 17_18_24.log.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14119245/LIAM.-.2024.1.31.744.-.2024-01-31.17_18_24.log.zip)

**Comment by Banane9** [comment]
This is likely to be an expected effect of the generated sine waves not lining up with each other. Similar to when audio clips are cut together without looking at their values being (near) zero.

If you have a constant sine wave, you can change the speed to adjust its frequency.

**Comment by VirgilCore** [comment]
It would be nice to allow it to cross fade to avoid sample clipping like this, but i think that would require audio processing tools to be implimented first

**Comment by Frooxius** [comment]
@Banane9 Is correct, this is just effect of suddenly swapping out the generate sine wave and ending up in a middle of the new one (or rather, any random part of it). 

It's the same as if you cut audio clip of sine wave at random point and stitched another one after it, that's also cut at random point - you get a sudden jump (unless they happen to line up), which is where the static comes from.

It's not really something solvable on this level - if you want to vary the pitch gradually, I recommend using the playback speed, which is designed to do that continuously. You can drive it with the DrivePlayback too.

**Comment by mwalker420** [comment]
It's a bummer that the SineWaveClip can't generate a smooth transition. Adjusting the playback speed seemed like a good alternative but unfortunately I can't find a way to drive the playback speed - I tried creating a drive node on the little value box at the end of the playback line of the component (using the flux tool) but no flux node is created. Is there an alternative for driving the playback speed?

**Comment by Nytra** [comment]
There is a ProtoFlux node called PlaybackDrive in the Media category
