### ISSUE TITLE
Remember me function doesn't work anymore after security update

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#1281]
### Describe the bug?

Remember me for 30days function doesn't work anymore after security update

### To Reproduce

close resonite and your not loged in anymore

### Expected behavior

Remember me for 30days if not active for long time

### Resonite Version Number

Beta 2024.1.31.744

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop, Oculus

### Log Files

Log too big to upload

### Reporters

slythefloof, glitchflux, pyroboy

**Comment by XDelta** [comment]
If you haven't logged in for a few days, the security update 2024.1.27.608 was followed by some session tokens being reset requiring a re-login. As far as I've seen so far, the 'remember me' has been working fine.

**Comment by SlyTheFloof** [comment]
> If you haven't logged in for a few days, the security update 2024.1.27.608 was followed by some session tokens being reset requiring a re-login. As far as I've seen so far, the 'remember me' has been working fine. I've not needed to relogin as expected.

I relogged after said security update and sometimes my auth token just kills it's self when my user is respawned and logs me out as a anonymous user and all my friends are offline and i have no inventory but i'm full well still connected to the servers

it's so random there is no exact way to get logs for it GlitchFlux and Pyro also has the same issue sometimes

**Comment by SlyTheFloof** [comment]
It seems approximately 13 hours of uptime logged in will force a logout of sorts
GlitchFlux's log attached

i would say it happened in the last 5 min of the logs can't get the exact point GlitchFlux did marker it with f3
[Uploading GLITCHTITAN2 - 2024.1.31.744 - 2024-01-31 22_03_41.log…]()

**Comment by SlyTheFloof** [comment]
[GLITCHTITAN2 - 2024.1.31.744 - 2024-01-31 22_03_41.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14130155/GLITCHTITAN2.-.2024.1.31.744.-.2024-01-31.22_03_41.zip)
Here is the log file from GlitchFlux's end as requested in a .zip format.
I still have yet to capture the issue again myself but i did have the issue

**Comment by SlyTheFloof** [comment]
new log file with better logs issue can be recreated every 12 hours

[GLITCHTITAN2 - 2024.1.31.744 - 2024-02-01 11_45_33.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14135191/GLITCHTITAN2.-.2024.1.31.744.-.2024-02-01.11_45_33.zip)

**Comment by Nytra** [comment]
I have encountered this a couple of times. Although I don't have any clean (mod free) logs to submit. When it happens it spams the log with SignalR failed to initialize and causes the file to get quite large.

**Comment by Frooxius** [comment]
I think I know why this is happening. It seems that when the token is refreshed, the client fails to obtain the new one for some reason. 

I'll rework how the token refresh swap happens a bit to prevent this from happening.

**Comment by Frooxius** [comment]
This should be fixed in 2024.2.2.906, thanks for report!
