### ISSUE TITLE
UV map misalignments

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#1287]
### Describe the bug?

Models that use a mirrored UV map have a visible seam along the edge of the texture when you're about a meter away from the model. 

### To Reproduce

Import a model with a mirrored UV map and stand about a meter away.

[Free model I used for example](https://booth.pm/en/items/5379546)

### Expected behavior

Textures don't have a seam.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/89ac918d-bacd-4f10-975a-852f3f56bbc0)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/10d38f31-c851-451b-b456-118d0da719fa)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/d9ba4d98-8c7e-4038-b26a-38d733fca77c)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/0f1aaeda-dd0b-4287-8827-49c7146f283e)

### Resonite Version Number

2024.2.2.1015

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2, Desktop

### Log Files

[BUFU - 2024.2.2.1015 - 2024-02-02 23_12_07.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14149624/BUFU.-.2024.2.2.1015.-.2024-02-02.23_12_07.log)

### Additional Context

Setting a very small texture offset seems to fix this at a distance, but looks incorrect when close.

**Comment by Banane9** [comment]
That's an issue with your textures, not with the game.

At a distance, lower resolution mipmaps of the texture will be used. Because your texture is only exactly up to the edge of the UV islands and black around it, that will bleed into it, producing the apparent seam. The same issue appears with transparent backgrounds. You'll want to use dilation on your UV islands in the texture to avoid this.

**Comment by Frooxius** [comment]
@Banane9 is correct, you'll need to update your textures to get rid of this.

I think in this particular case, the simplest solution is to just switch your texture wrap from "Repeat" to "Clamp". This will prevent the mipmaps from bleeding over to the other side of the texture which is black.

I'm closing this issue as there's nothing on our end to do with this.

**Comment by Banane9** [comment]
Setting texture repeat to clamp could fix the very obvious face seam at least, if the island goes right up against the texture edge.
It will likely still leave issues in other places - but it may be "good enough".

**Comment by Frooxius** [comment]
Yeah. If there's a small gap between the face and the edge, then they'll have to bleed that color.

But this texture looks like it's designed to be used with clamp, so it might just fix it up.

**Comment by ko-tengu** [comment]
It's got some room in the textures, and it's enough for other platforms, but it seems to for sure be a mipmap problem here at least.

**Comment by Banane9** [comment]
> It's got some room in the textures, and it's enough for other platforms, but it seems to for sure be a mipmap problem here at least.

Hard to tell whether it has any dilation on the texture with the tiny bit visible in the screenshots. In any case, "it's fine on another platform" is meaningless without exact details about the setup there. E.g. disabling mipmaps or a custom shader that ignores them / sample differently would "fix" it as well. Ultimately, it's a problem with the textures though.

**Comment by Frooxius** [comment]
At this point, I'd strongly recommend setting the texture to "Clamp" first and seeing if that fixes it.

Yes, there's lots of different variables. Perhaps on other platforms the mipmaps are disabled or it's already set to Clamp instead of Repeat. There could be lots of different stuff. 

Setting it to "Clamp" and seeing if that fixes it is the quick.
