### ISSUE TITLE
Convex Hulls cause a memory leak

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#1291]
### Describe the bug?

Using convex hulls causes a memory leak

### To Reproduce

1. Create a new world
2. Spawn out a convex hull brush
3. Draw 5 or so Convex Hulls
4. Watch your memory use sky rocket

### Expected behavior

Convex Hulls should perform normally.

### Resonite Version Number

2024.2.2.906

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Index

### Log Files

[ALFRED - 2024.2.2.1015 - 2024-02-02 23_39_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14150608/ALFRED.-.2024.2.2.1015.-.2024-02-02.23_39_36.log)

### Additional Context

Worlds that use a lot of convex hulls are currently death traps. To avoid some trolling I will not list any but have provided a list in the internal team discord.

Panda also experienced this in just deleting convex hulls.

This might be the same issue as: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1290 or 1290 might be separate Charlie was participating in helping me reproduce but the issue looked different so I kept them as two items.

A video from Panda is here: https://cdn.discordapp.com/attachments/850883244501368855/1203246881379979274/Funny_Leak_Cause_Convex_Hulls.mp4

### Reporters

So many people jumped in to verify this. Medra was the one who DM'ed me, but the others listed below helped reproduce, diagnose or just experienced the issue in the Resonite Down Under server.

Medra, ProbablePrime, Panda, Bredo, Sveken, Charlie-san, Beef, Unintentional, Canadian_RedZ, ocelot342

**Comment by ProbablePrime** [comment]
This is likely some sort of weird side effect of this change:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/a0e70473-12b1-44d6-a10e-b1aa5f575d66)

From the 2024.2.2.906 update.

**Comment by LeCloutPanda** [comment]
Here is my log file incase you need more logs in the future: [GEOFF - 2024.2.2.1015 - 2024-02-03 18_49_01.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14150665/GEOFF.-.2024.2.2.1015.-.2024-02-03.18_49_01.log)

**Comment by Canadian-RedZ** [comment]
Here is my log files also
Windows -> [REDZ-LENOVO - 2024.2.2.1015 - 2024-02-03 02_31_29.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14150771/REDZ-LENOVO.-.2024.2.2.1015.-.2024-02-03.02_31_29.log)
Debian/Linux -> [RedZ-Lenovo_-_2024.2.2.1015_-_2024-02-03_03_13_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14150773/RedZ-Lenovo_-_2024.2.2.1015_-_2024-02-03_03_13_10.log)

**Comment by Frooxius** [comment]
We'll have to report this to author of BepuPhysicsV2, it's probably the code not clearing up some memory it allocates, so it accumulates on repeated runs. 

If anybody wants to have a look at the backported code before I get to it, it's here: https://github.com/Yellow-Dog-Man/bepuphysics2/commit/64795acd9b078e3a09aff60e4079a540b8d0c74e

**Comment by Banane9** [comment]
> This is likely some sort of weird side effect of this change:

I'm not sure about it being completely _new_ - this could explain what happened about two weeks ago, where I got up to some very spicy RAM usage that also went up pretty fast 🤔 

![Task Manager showing Resonite with 45GB RAM used](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/21f3c29d-9f1e-4a16-92fa-11331f6e323b)

Here's a log in any case (puush because GitHub only allows 25MB and this was at the end of a long session I was hosting, where convex hull brushes came out at some point to show them off to new people):
https://puu.sh/K0ae6/346bdf5626.log

**Comment by Frooxius** [comment]
Is there a way to confirm that the leak before was also due to convex hulls specifically? 

They can happen for a number of reasons, so I don't want us going down a wrong rabbit hole.

**Comment by Banane9** [comment]
> Is there a way to confirm that the leak before was also due to convex hulls specifically?

Not specifically - it just reminded me of that occasion and I wanted to provide the log just in case it does have anything relevant.

**Comment by Frooxius** [comment]
Would anyone be able to jump on an older build (I think one in the pre-release might work) and see if this can be replicated with old BepuPhysicsV2 too?

That way we'd know that we have to look for source of this issue outside of the changed code.

**Comment by LeCloutPanda** [comment]
> Is there a way to confirm that the leak before was also due to convex hulls specifically?
> 
> They can happen for a number of reasons, so I don't want us going down a wrong rabbit hole.

If you look at the video I provided to Prime it shows the leak is due to convex hulls because I used the bruh to cause the leak.

**Comment by Banane9** [comment]
> If you look at the video I provided to Prime it shows the leak is due to convex hulls because I used the bruh to cause the leak.

Pretty sure Froox was just replying to my comment about it potentially happening before the update as well.

**Comment by LeCloutPanda** [comment]
> > If you look at the video I provided to Prime it shows the leak is due to convex hulls because I used the bruh to cause the leak.
> 
> Pretty sure Froox was just replying to my comment about it potentially happening before the update as well.

My bad you are most likely correct, I have an archived build from pre-release when I got access to the game as a mentor so I'll do more testing and note my findings when I do some testing.

**Comment by Canadian-RedZ** [comment]
> Would anyone be able to jump on an older build (I think one in the pre-release might work) and see if this can be replicated with old BepuPhysicsV2 too?
> 
> That way we'd know that we have to look for source of this issue outside of the changed code.

Here is a test done with Steam's pre-release build 2024.1.21.825 
 -> https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/20827894/c85f2280-75e0-40b6-bf70-2942f0191ffb
Here is the log from the same test -> [REDZ-LENOVO - 2024.1.21.825 - 2024-02-03 11_14_03.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14152149/REDZ-LENOVO.-.2024.1.21.825.-.2024-02-03.11_14_03.log)

**Comment by Nutcake** [comment]
> We'll have to report this to author of BepuPhysicsV2, it's probably the code not clearing up some memory it allocates, so it accumulates on repeated runs.
> 
> If anybody wants to have a look at the backported code before I get to it, it's here: [Yellow-Dog-Man/bepuphysics2@64795ac](https://github.com/Yellow-Dog-Man/bepuphysics2/commit/64795acd9b078e3a09aff60e4079a540b8d0c74e)

It looks like when merging in the changes from upstream you accidentally left in a debug struct called DebugStep, which balloons up with huge amounts of data but has zero actual use beyond troubleshooting. 
I've created a PR on your fork of BEPU that reverts that part back to upstream, fixing the issue: https://github.com/Yellow-Dog-Man/bepuphysics2/pull/3

**Comment by bredo228** [comment]
Did a comparison of Build 2024.1.19.687 and Build 2024.2.2.1015

2024.1.19.687:

[DYSNOMIA - 2024.1.19.687 - 2024-02-04 10_15_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14154305/DYSNOMIA.-.2024.1.19.687.-.2024-02-04.10_15_14.log)

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/f7c71644-a1b9-4c72-8f52-69b117a87c99

2024.2.2.1015:

[DYSNOMIA - 2024.2.2.1015 - 2024-02-04 10_18_39.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14154306/DYSNOMIA.-.2024.2.2.1015.-.2024-02-04.10_18_39.log)

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/e2602def-d0c9-42a6-8f3d-ee09de4c8936

**Comment by ProbablePrime** [comment]
Thank you all for the work!

It does look like: https://github.com/Yellow-Dog-Man/bepuphysics2/pull/3

Will fix us up.

**Comment by Frooxius** [comment]
This has been merged in 2024.2.5.848, thank you!
