### ISSUE TITLE
Face tracking doesn't appear to work anymore.

### ISSUE THREAD

**Issue by portalsam1** [Yellow-Dog-Man/Resonite-Issues#1293]
### Describe the bug?

Face tracking has stopped functioning for me since a recent update, SRanipal shows as initialized but the game does not recognize it in the log file.

### To Reproduce

Launch Resonite with a lip tracker on and plugged in

### Expected behavior

SRanipal shows as initialized so lip tracking should be recognized and function.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/41414314/f0602e34-f6c5-4b26-b05f-11bc11241d81)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/41414314/d402349b-f60c-4446-b848-ac175ef687e9)

### Resonite Version Number

Beta 2024.2.2.1015

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index + HTC Facial Tracker

### Log Files

[DESKTOP-RYZEN9 - 2024.2.2.1015 - 2024-02-03 02_43_58.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14151149/DESKTOP-RYZEN9.-.2024.2.2.1015.-.2024-02-03.02_43_58.log)

### Reporters

portalsam

**Comment by ohzee00** [comment]
Have you tried steps in https://wiki.resonite.com/Face_and_Eye_Tracking_(Troubleshooting) ? Namely the -ForceSRAnipal param?

It shows as green, meaning that it is actively being used, does it show up as green before Resonite is launched?

**Comment by Frooxius** [comment]
Does it work in any other apps for you? 

We didn't touch anything with face tracking in the last update and it does work for me and other people, so this is most likely something specific to your machine.

**Comment by portalsam1** [comment]
The issue has suddenly stopped after a few days with thorough testing and I was unable to reproduce it. I apologize for wasting your time.

**Comment by ohzee00** [comment]
Ya didn't waste anyone's time! Just glad ya were able to fix it, trust me I'm sure a lot of us understand the annoyances of SRanipal being temperamental
