### ISSUE TITLE
Video texture providers cannot be inserted into a material texture slot

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1298]
### Describe the bug?

Video texture providers cannot be inserted into a material texture slot

### To Reproduce

Import a YouTube video or one from your computer or your preferred service provider then attempt to insert the video into a material slot you cannot drag and click it in or drag and drop

### Expected behavior

I should be able to insert a video texture into a material texture slot

### Resonite Version Number

2024.2.2.1015

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

I don't think log files are useful in this situation but I'll provide log files if requested

### Reporters

@epicWaston197

**Comment by ohzee00** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/c296efda-dd24-4da2-a866-7836b1eb0b09

I'm honestly unsure what you mean, do you mean the video itself? Because Video Texture Providers do work.

**Comment by ProbablePrime** [comment]
I think easton is describing setting it directly from the video player. As in drag the video player into the material slot.

**Comment by epicEaston197** [comment]
> I think easton is describing setting it directly from the video player. As in drag the video player into the material slot.

Yes i cannot grab a video player and put it into a material slot or any similar material texture input

**Comment by epicEaston197** [comment]
I can confirm this happens with the default video player by unfavoring it instead of my custom one

**Comment by RyuviTheViali** [comment]
I've added a reference proxy to the video player. Closing this, thanks!
