### ISSUE TITLE
Command to rename groups

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#1301]
### Is your feature request related to a problem? Please describe.

no command present for renaming groups

### Describe the solution you'd like

addition of command for renaming groups

### Describe alternatives you've considered

n/a

### Additional Context

zangooseoo

**Comment by ExoTheWicker** [comment]
I think this would be a relatively easy thing to implement

**Comment by jae1911** [comment]
Already requested in #394

**Comment by gentlecolts** [comment]
Thank you for pointing that out, closing this
