### ISSUE TITLE
Local Instance showing as "[Machine ID] Home"

### ISSUE THREAD

**Issue by ProtogenDelta** [Yellow-Dog-Man/Resonite-Issues#131]
### Describe the bug?

Ever since the fix for user homes pushed in `2023.10.13.202`, Local Machine instances (i.e. the loading instance, previously just "Local") are showing as `{Machine ID} Home`.

This is occurring on both Linux and Windows.

### To Reproduce

Launch Resonite
Open the worlds menu, and observe the local instance's name

### Expected behavior

The name should be "Local" (i.e. without the quotes)

### Screenshots

![Screenshot of the local instance details pane in the worlds tab](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47292121/039476f5-658e-4cf6-8bcc-6a22133a469c)
![Screenshot of the local instance next to a separate home instance](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47292121/3820586f-0571-45fc-bfbe-9e655a3aeb36)
![Screenshot from a facet of currently joined worlds, credit to shdw_x on discord](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47292121/01da6ee0-47eb-487b-861f-01ef094ef4c3)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop

### Log Files

- [Pastebin: DELTA-ROVER - 2023.10.13.743 - 2023-10-14 12_45_17.log](https://pastebin.com/G6bz96fz)

### Additional Context

N/A

### Reporters

`leocatto` on Discord
`shdw_x` on Discord

**Comment by ProbablePrime** [comment]
Ye, I'm on it. Thank you

It is my fault *face palms*

**Comment by ProtogenDelta** [comment]
All good @ProbablePrime, Just figured it would be good to open an official tracking issue for it.
