### ISSUE TITLE
Update video player close button to preserve assets and allow undo

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#1311]
### Describe the bug?

Mitigates #1310. Currently, the close button on the top right corner of the default video player is set to call the `Destroy` method. In the case of #1310 where the video player is referenced dynamically, closing it with the `Destroy` method causes a crash. When preserving assets, this crash does not occur.

### To Reproduce

Press the 'close' button on the top right corner of the video player.

### Expected behavior

Destroying a video player with the close button should be an undo-able action, and the assets should be preserved unless the user explicitly destroys without preserving assets.

My recommendation would instead be to have the button trigger `Undoable Destroy` (Undo > Undoable Destroy) with `PreserveAssets` enabled in ProtoFlux.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/c17b81c0-50e3-455c-af08-a9d517ffa825)

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/c11a3a49-c481-482f-855c-d019db1019d0

### Reporters

Resonite: Shifty / GitHub: @shiftyscales / Discord: shiftyscales

**Comment by RyuviTheViali** [comment]
I have set the video player to perform an undoable destroy on itself while preserving assets. Closing this now, thanks!
