### ISSUE TITLE
Grab Area edit mode visual hard to see

### ISSUE THREAD

**Issue by alizardguy** [Yellow-Dog-Man/Resonite-Issues#1318]
### Is your feature request related to a problem? Please describe.

With the change of color space the Fresnel material on the Grab Sphere visual under the user's GrabArea Anchor is almost invisible in most lighting conditions, prior the sphere was a very good debug visual while working on avatars.

### Describe the solution you'd like

Choose more visible colors for the edit mode Grab Sphere visual.

### Describe alternatives you've considered

Positioning my own sphere visuals on my hand proxies when in edit mode with flux.

### Requesters

alizard

**Comment by TisFoolish** [comment]
I feel a material that changes the colors (like ChannelMatrixMaterial) would be better instead of trying to pick a color as there will *always* be conflicts otherwise.

**Comment by Frooxius** [comment]
Merged fix in 2024.7.4.1347!
