### ISSUE TITLE
Proxy Issues: Can't connect to api.resonite.com (connection refused)

### ISSUE THREAD

**Issue by RubberDuckShobe** [Yellow-Dog-Man/Resonite-Issues#1319]
### Describe the bug?

When I launch the game, it passes the loading screen, but it can't load the inventory and every widget on the dashboard is blank.
Inspecting the logs reveals that the game can't connect to `api.resonite.com`.

### To Reproduce

1. Open the game
2. Wait
3. Look at the log file

### Expected behavior

The client connects successfully and lets me log in.

### Screenshots

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/42943070/3debd271-b71e-4128-a837-47dd2b872ae7)

### Resonite Version Number

2024.2.5.848

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[PC_NAME_REDACTED - 2024.2.5.848 - 2024-02-08 10_30_57.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14207317/PC_NAME_REDACTED.-.2024.2.5.848.-.2024-02-08.10_30_57.log)

### Additional Context

The network I am testing on is a school network. Everything has to run through a proxy, Windows is configured correctly to use the proxy server.
Web browsers and other games all seem to work fine, only Resonite exhibits this behavior.

### Reporters

m1nt_ (Resonite) / the_crescent_moon (Discord)

**Comment by ShrikeAlvaron** [comment]
If you're on a school's network it's highly likely they're blocking game sites, which would include the entire resonite.com domain.  What happens if you try to go to say https://api.resonite.com/sessions in your browser?  Depending on the service your school is using it might show an error about it being blocked or may just not connect.

**Comment by RubberDuckShobe** [comment]
It does work in the browser.

**Comment by RubberDuckShobe** [comment]
I've actually already re-synced the clock because it used to be several
hours behind.

**Comment by ProbablePrime** [comment]
This log file shows significant trouble trying to connect to basically any of our infrastructure. 

When you say that it doesn't work in the browser, what happens when you try?

**Comment by RubberDuckShobe** [comment]
I think you misread, it *does* work in the browser. Bad phrasing on my part!

**Comment by ProbablePrime** [comment]
Does your computer utilize any VPN, Proxy or Firewall style items?

**Comment by RubberDuckShobe** [comment]
Yes, the PC uses a proxy. It‘s set in the system‘s network settings.

**Comment by ProbablePrime** [comment]
Resonite does not currently support proxy servers. But we plan to add this functionality soon.

**Comment by Geenz** [comment]
Apologies - we _do_ support proxy settings which may be set via a configuration file.

In the installation folder, you may create a "Config.json" file and set some settings for a proxy server like so:
```JSON
{
    "proxy" : {
        // Whether to autodetect proxy settings using Internet Explorer's settings.  Defaults to false.
        "autoDetect": true,
        // Whether to bypass the proxy on local domains.  Defaults to true.
        "localBypass": true,
        // List of domains to bypass the proxy with.
        "bypassDomains": [""],
        // HTTP/S proxy to use for all web requests.
        "address": "addresshere",
        // The port to communicate with the proxy over.
        "port": 9999,
        // Determines the source of the proxy server's credentials.
        // Valid options are:
        // DefaultSystemCache
        // NetworkCache
        // UsernamePassword
        // Defaults to the system cache.
        "credentialStore": "DefaultSystemCache",
        // Proxy server's username. Only used when credentialStore is set to UsernamePassword.
        "username": "testUser",
        // Proxy server's password. Only used when credentialStore is set to UsernamePassword.
        "password": "qwertyuiop"
    }
}
```

If you set `autoDetect` to true, you may need to set the `credentialStore` to `NetworkCache`.  We haven't seen a lot of usage of this feature, so feel free to give it a spin and give us feedback!

**Comment by RubberDuckShobe** [comment]
Thank you! I'll have time to test this tomorrow.

**Comment by ProbablePrime** [comment]
Apologies for the automated closing here. 

This should be fixed by an upcoming release and I'll comment here again when its out. We're not sure if it will resolve your issue so once it's out if you can try we'll be able to close this properly.

Thank you.

**Comment by RubberDuckShobe** [comment]
Thanks for the comment! Unfortunately, I won't be able to test in the same
environment (on the school library PC) anymore because I'm actually
graduating in a few days! I'd need to find a way to replicate the same
network conditions at home (setting up a proxy and blocking all traffic
that doesn't go through it).

**Comment by ProbablePrime** [comment]
Ahh excellent, we'll call this one "fixed" when the update comes out.

We have a business client with a very strong proxy that the change i made fixes so Im hopeful.

Congratulations on graduating.

**Comment by ProbablePrime** [comment]
In 2024.7.4.1347 we have some proxy fixes that should resolve this one.
