### ISSUE TITLE
Play One Shot Priority option does not set priority on spawned audio

### ISSUE THREAD

**Issue by Ruikio** [Yellow-Dog-Man/Resonite-Issues#132]
### Describe the bug?

Play One Shot [Set Priority] does not set the spawned audio clip's priority.

### To Reproduce

- Set up a Play One Shot
- Tell it to set Priority to something like 32
- Turn off an Empty Object
- Set Play One Shot to spawn on the Empty Object's root
- Trigger Play One Shot
- Inspect the Play One Shot Audio & see Priority is not set

### Expected behavior

The spawned audio file having it's priority set appropriately.

### Screenshots

![2023-10-14 02 58 25](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/42963569/e94ddd4f-869a-4d66-8495-570b79ae8e10)

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

HTC Vive Pro Eye, Valve Index

### Reporters

Rukio

**Comment by Ruikio** [comment]
> When submitting reports, please include log files from replicating the issue as well as a link to an object/world in which the bug can be replicated as per our [best practices](https://github.com/Yellow-Dog-Man/Resonite-Issues#best-practices-for-bug-reporting) @Ruikio.
> 
> Edit the metadata for replication worlds created to be accessible to anyone, and enable 'don't show in session lists' so any instances of the world are not publicly visible while opened.
> 
> As a sanity check, I also set the speed of the clip low so I could test against a non-disabled slot too.
> 
> **Replication world:** `resrec:///U-Shifty/R-14d7dd44-62da-4d09-a98d-bbeb9c6e5358`
> 
> **Log:** [SHIFTY-LAPTOP - 2023.10.13.743 - 2023-10-16 11_04_18.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12920384/SHIFTY-LAPTOP.-.2023.10.13.743.-.2023-10-16.11_04_18.log)
> 
> If I had to do this for each of the 200+ issues are opened I would have a lot of work ahead of me, please save the team the time and effort by following the best practices, and include everything we need to replicate the issue.

I can look into providing the mentioned info going forward sure.

You said you set the speed, although I'm not sure what that has to do with the mentioned bug above. Was your test successful on changing the priority? If so it might be good to put that in this post at least that way I know if I need to continue doing what you've mentioned above on this topic. @shiftyscales

**Comment by Ruikio** [comment]
If I need to provide further details, I do need to know if I have to set this up for you.

Did you manage to get this to work? To my understanding it would just be a Play One Shot + Setting Priority to 32. You'd set the root to an empty object that's disabled so you could inspect the spawned output.

From your response I'm not sure if you managed to replicate it or not. As I said, I'll take your recommendations going forward but for this one were you successful or not? @shiftyscales

**Comment by Frooxius** [comment]
Fixed in 2023.10.17.464, thank you!
