### ISSUE TITLE
Highlight hover and choice of options in session tab

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#1320]
### Is your feature request related to a problem? Please describe.

When trying to quickly see what option is selected in the session tab of the dashboard, I often have to completely stop what I'm doing and double check what I'm seeing.
For instance, in the world accessibility setting, there is too much of a gap between the name of the option and the selected option itself to be readable easily.

![Resonite session accessibility setting.](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/ae7df567-ca0d-48d5-8eab-72b2942e0d14)

### Describe the solution you'd like

Add a visual indicator of what you're hovering on and what's selected.
This could be achieved by having a lighter/darker background on hover and when something is selected.

An example of colour change on hovering (taken on this very page):

![Mouse cursor going over the tabs of this page, going darker on hover.](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/5f414f8b-685f-4e96-93ba-74d1053617f8)

Another way of doing this would be for each line of setting to display a different colour to help differentiate them like a lot of web tables do (example table from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table)):

![Table showing each line with a different colour.](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/df9f0cb1-58ae-4b80-9dba-e5fc68510a78)

### Describe alternatives you've considered

None.

### Requesters

U-j4 | j4.lc (Discord)

**Comment by shiftyscales** [comment]
We are not likely to make incremental updates to legacy UIs like this one. Thank you for the recommendation.
