### ISSUE TITLE
Add a component that contains a description of an item.

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [Yellow-Dog-Man/Resonite-Issues#1325]
### Is your feature request related to a problem? Please describe.

I propose one unified way to denote an object has information about itself and let it be accessible for tools to read.  For example, a heads-up display that gives item information. 

### Describe the solution you'd like

A simple text component, typically found in an object's root can provide context or useful tool information.

### Describe alternatives you've considered

While some creators create separate items that consist of changelogs, howtos, and general info, this kind of metadata could easily exist in the tool or object itself. Comments could also be used, but without tags for comments, these could be overlooked as implementation details.

### Additional Context

A simple field should be very simple to implement, relative to other larger changes. The community can then either use it or ignore it at their discretion.

**Comment by ProbablePrime** [comment]
Thanks for making an issue, we'd unfortunately not be able to provide this with Resonite in it's current state.

Our goal for items like this is our Item Workshop/Marketplace/Licensing system which will be similar to the world browser(with descriptions and names) or RedX(the community tool).

I think, i'll link this back to: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/33 as that's the closest i can find right now.

Until then, what I see people do is to make a "credits" slot that has a bunch of text fields on it that talk about who made it etc.

**Comment by XDelta** [comment]
Depending on what you want the visual display to be, you could set similar up on your own items. IE for a game world to have tooltip type text when you grab something or if you just want info about it stored on the item, a combination of dynamic variables for readable by code fields and as mentioned above a credits slot using either slot names or the `Comment` component to just add whatever text.
