### ISSUE TITLE
Indirect Writing does not work when the IVariable is from a different Protoflux node group

### ISSUE THREAD

**Issue by LucasRo7** [Yellow-Dog-Man/Resonite-Issues#1333]
### Describe the bug?

If you use a node to get an IVariable, you can do an indirect write. but if you send the IVariable through a Dynamic Impulse with Object, you cannot do an indirect write if the indirect write is in a different node group from the variable.

This happens with either `Indirect Write`, `Indirect Increment`, `Indirect Decrement` or `Indirect Write Latch` nodes.

Furthermore, the behaviourr changes depending on what the IVariable is referencing:
- if you are trying to indirectly write to a `Data Model Store`, the `Indirect Write` node outputs a 'failure' pulse
- if you are trying to indirectly write to a `Store`, the `Indirect Write` node outputs a 'success' pulse
- if you use a `Field as Variable` node the Indirect write node does not output anything.

I haven't tested `Local` variables since as far as I understand, a dynamic impulse changes context, therefore it would't write anything anyway

### To Reproduce

1. Create a `DataModel Store` or a `Store` Variable of any type.
2. Connect it to an `Indirect Write`, it'll create a `Ref To Output` node for you.
(You can verify the indirect write can change the value in the variable.)
3. Connect the output of the `Ref To Output` node into a `Dynamic Impulse Trigger With Object`
4. Create a `Dynamic Impulse Receiver With Object` with the same generic type as the dynamic trigger node.
5. Connect an `Indirect Write` to the dynamic impulse receiver
(I also suggest creating a `Pulse Display` for both outputs of the indirect write)
6. Set both the dynamic impulse trigger and receiver with the same name
7. Connect a `Root Slot` node to the target hierarchy of the dynamic impulse trigger node
(Doesn't have to be root, you can use a reference to any slot, as long as it's a parent of the dynamic impulse receiver)
8. Call the dynamic impulse trigger with value, if you've done everything right, the indirect write will have no effect on the variable

You can also use a `Link` node to make sure both the dynamic impulse trigger and receiver is on the same group. 
After doing this (or connecting the dynamic impulse trigger and receiver in any other way) and calling the dynamic impulse trigger, you'll observe that the indirect write does change the state of the variable.

Alternatively, you can spawn the item in this folder: `resrec:///U-LucasRo7/R-497620C3C4E38718154C178F84A5C90E8509CAB7E11053791DD749A547C3FD62`

Of course, feel free to try an `Indirect Increment`, `Indirect Decrement` or an `Indirect Write Latch`, the results are exactly the same

### Expected behavior

I expected the indirect write to work even though the IVariable object is from a different node group.
This is the behaviour of the programming language of another platform where FrooxEngine is/was used.

### Screenshots

This is the result after pressing every call node in the example folder
![2024-02-12 05 31 20](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7934266/f56c37dd-0aa0-44f2-b9e4-a5dfde577046)

Here's a link to the example folder:
`resrec:///U-LucasRo7/R-497620C3C4E38718154C178F84A5C90E8509CAB7E11053791DD749A547C3FD62`

### Resonite Version Number

2024.2.5.848

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2 running through Steam Link

### Log Files

[DESKTOP-CPP5K63 - 2024.2.5.848 - 2024-02-12 02_52_29.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14235443/DESKTOP-CPP5K63.-.2024.2.5.848.-.2024-02-12.02_52_29.log)

### Additional Context

I thought I was being SO clever with this to make dynamic impulses "return" a value back

### Reporters

LucasRo7

**Comment by JackTheFoxOtter** [comment]
Out of curiosity, would it work if you use Field As Variable, but pass the IField reference through the dynamic impulse and then use the Field As Variable node on the receiver side? Because then it might be because the IVariable type is somehow bound to the current context.

**Comment by LucasRo7** [comment]
> Out of curiosity, would it work if you use Field As Variable, but pass the IField reference through the dynamic impulse and then use the Field As Variable node on the receiver side? Because then it might be because the IVariable type is somehow bound to the current context.

Yes, if you send the IField instead of the IVariable, it does work. But that doesn't work with `Store` variables, as they don't have a field and it's a bit convoluted if all you want to do is to write to a variable

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7934266/3a6ca2cb-c785-4a2c-8e5e-2f3c930acb61)

**Comment by JackTheFoxOtter** [comment]
All right. That said though, this would bring the behavior on-par with the legacy language, so it's not a regression.

**Comment by Banane9** [comment]
If I remember @mpmxyz's explanation correctly, sending a dynamic impulse to another protoflux node group creates a new execution context - so any variables are disconnected from the calling context.

**Comment by Frooxius** [comment]
This is expected behavior. All variables that you want to write to need to be part of the same node group.

If they are part of a different node group, they effectively do not exist for that group - and you cannot write into something that doesn't exist.
