### ISSUE TITLE
Button for set values method in data preset component

### ISSUE THREAD

**Issue by amplified1** [Yellow-Dog-Man/Resonite-Issues#1338]
### Is your feature request related to a problem? Please describe.

Method doesn't have an inspector button, didn't realize it existed because of this.

### Describe the solution you'd like

Add a button to the component that references this method.

### Describe alternatives you've considered

Using method proxy, less convenient option

### Additional Context

N/A

### Requesters

@_amplified_

**Comment by stiefeljackal** [comment]
The `DataPreset` component already contains a method called `SetValues()` that will write the current field value or reference back to the preset. At the moment, you will need to grab the method out as a `Method Proxy` in order to call it, so this is a workaround that you can at least utilize. A button for this on the inspector would still be good to have.

**Comment by amplified1** [comment]
> The `DataPreset` component already contains a method called `SetValues()` that will write the current field value or reference back to the preset. At the moment, you will need to grab the method out as a `Method Proxy` in order to call it, so this is a workaround that you can at least utilize. A button for this on the inspector would still be good to have.
> <img alt="image" width="404" src="https://private-user-images.githubusercontent.com/20023996/304310874-f89bedd6-353f-4a14-9eae-fc2bb7be7549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MDczNjQsIm5iZiI6MTcwNzgwNzA2NCwicGF0aCI6Ii8yMDAyMzk5Ni8zMDQzMTA4NzQtZjg5YmVkZDYtMzUzZi00YTE0LTllYWUtZmMyYmI3YmU3NTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEzVDA2NTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkOWFmMGYyNWU1ZjAyZjI4NTVmNTE2Mjg4ZmRhMDZlM2UxNWVjZGVhNmYxNDRiNGQxYjI2ZDcxMzg1MjNmMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_xvfeUQGxI_lzv8nxZw346YQbdk6NwotoHcoyPRZgw">

Re-wrote feature request, feel a little silly for not noticing the exposed method but it definitely should have a button

**Comment by ProbablePrime** [comment]
I thought I did this already!

Thanks for the item
