### ISSUE TITLE
Setup CI/CD pipeline for LiteNetLib

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1345]
### Is your feature request related to a problem? Please describe.

We're currently using the official NuGet for LiteNetLib library used for networking.

We need to make some modifications to our fork and push updates with those changes.

### Describe the solution you'd like

Setup same CI/CD process with custom NuGet package for our fork here: https://github.com/Yellow-Dog-Man/LiteNetLib

### Describe alternatives you've considered

Manually compiling, which would make the build process messy again.

### Additional Context

This is because of this request: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1324

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/LiteNetLib/actions/runs/7908853878/job/21588833115

1.2.0-ydm-0.1.0 just shipped up to Nuget. This includes all changes up to the head of master of the original version of LNL.

You should now be free to make changes and use our usual flow to get our changes on Nuget and easier to integrate.

**Comment by Frooxius** [comment]
Awesome, thank you so much!
