### ISSUE TITLE
Add ProtoFlux nodes for building UIX (UIBuilder nodes)

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#135]
### Is your feature request related to a problem? Please describe.

If we could have nodes which could execute functions of a UIBuilder it would make it possible to dynamically create UIX in ProtoFlux. It would make it a lot easier to make UIX because instead of needing to add each component manually we could call UIBuilder functions like `UIBuilder.Button`, `UIBuilder.SplitHorizontally`, `UIBuilder.HorizontalElementWithLabel` which would speed up the workflow drastically.

### Describe the solution you'd like

Add ProtoFlux nodes for building UIX. The nodes would use the existing UIBuilder class.

### Describe alternatives you've considered

A wizard in the DevTool's Create New menu that lets us build UIX? 

### Additional Context

N/a

**Comment by JackTheFoxOtter** [comment]
I think this would be a bit too specific to create nodes for it. Once we get component level access in the future, you will likely be able to implement the functionality you're looking for yourself. However, technically, one could already build a custom UIX builder, by using template slots for the different UI elements and duplicating them whenever necessary. The nodes you're proposing would basically create slots, attach components and link up fields. That's three different kinds of actions which I think would be better suited for three different nodes. There is also a performance issue with programatically creating UI every time it's needed. I agree that a visual UI builder would be cool - but I think this should already be possible. I might poke the idea in the future.

**Comment by Nytra** [comment]
Having access to the official UIBuilder already in the game would make it easy to create UIX that complies with official styles set by Resonite. When you use it, it would create the UIX in the exact same way that inspectors and other such built-in UIX is made. That would be an advantage of having this feature.

**Comment by Nytra** [comment]
Closing this because I don't think it's a good idea anymore
