### ISSUE TITLE
Deleted records recovery command provided zip with mostly 0 byte files.

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#1357]
### Describe the bug?

I used the `/requestDeleteRecovery` command attempting to find an object I deleted about 2 weeks ago. However I noticed that even when doing `/requestDeleteRecovery 30d *` The bot said it only recovered 1 item. Curiously, the zip that was emailed to me contained 32 files showing every item I had actually deleted in that time span. Most of these were 0 byte frdt files. 

The content of the deleted object isn't all that important but in trying to see if I could recover it, I found it odd what objects were and were not able to be recovered in some manner? Potentially a bug in actually providing the files as it still knows they existed, the path and the name.

### To Reproduce

Not sure how I can /quickly/ reproduce this from scratch with deleting items as it seems likely to have some time aspect to it.

Use the `/requestDeleteRecovery` command and possibly see some or multiple 0 byte files of things you deleted in the past 30 days

### Expected behavior

Files within the last 30 days to be recoverable or atleast mostly recoverable (structure/components without assets). In this case I only wanted some of the components/nodes from the object

### Screenshots

The 1 file recovered was among legacy control images I had saved at some point. I deleted these all at the same time and only 1 was recoverable.
![6f72602e75](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/bb8a7a2f-60ca-43a6-8cae-e8f9897e7b75)

### Resonite Version Number

2024.2.12.1430

### Log Files

Occurs outside client aside from bot interaction via a message in game.

### Reporters

_deltawolf

**Comment by XDelta** [comment]
The item attempting to be recovered was about 16 days old or so. Using shorter time frames like the last 20 days gets the same result getting a hand full of deleted things with only 1-2 having a file size, the rest being 0 bytes

**Comment by Frooxius** [comment]
We'll have to look into this.

Are we able to replicate this? Say with a testing account?

**Comment by Frooxius** [comment]
Ah thanks for the info! Yeah that seems like something is going wrong there. I'll have a poke.

**Comment by XDelta** [comment]
@shiftyscales Curious if you make an item and delete it shortly after, then request delete recovery again so it gives you a zip if you see a similar thing occur in the zip file that I see

**Comment by ExoTheWicker** [comment]
I have also had a similar situation where a user I believe @989onan, deleted an item and it could not be recovered, but when I did it it worked just fine

**Comment by XDelta** [comment]
I made an object 4 days ago, (2/16) while testing and just attempted to recover the object today (2/20) to find that my zip again only 'recovered' 1 object but again includes the names and empty files for all the other objects. In this case I had again run the command `/requestDeleteRecovery 30d *`, the only object that was returned was the same one from my initial post. The testing object was already non-recoverable.

**Comment by XDelta** [comment]
Also ran `/requestDeleteRecovery 5d *` to try to specifically get the one test object but the bot reports `Nothing found to recover`

**Comment by ExoTheWicker** [comment]
> How long was it between when that other user deleted the item and attempted to recover it compared to you, @ExoTheWicker? Narrowing the range on how long items can actually be recovered from would help.

Less than 15 minutes.

**Comment by 989onan** [comment]
I'm also having this issue right now. I cannot get my item back due to a corrupted resonitepackage and this was the only way of getting an avatar I built back from storage

**Comment by shiftyscales** [comment]
@Frooxius - Any chance you could look into this soon, please?

**Comment by Frooxius** [comment]
I'll try looking into this soon, probably tomorrow.

**Comment by Frooxius** [comment]
I've pushed an update to the cloud which should fix this. Try running the command again, it should now recover everything.

If there's still issues, let me know and we'll reopen this. Thanks for the report!
