### ISSUE TITLE
color picker does not have option for choosing sRGBAlpha

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#1361]
### Describe the bug?

sometimes I want to use sRGBAlpha, but using a color picker this isn't possible. additionally editing a color which is sRGBAlpha will have neither sRGB or Linear light up in the color picker.

### To Reproduce

open color picker
there is no way to put the color into sRGBAlpha mode

### Expected behavior

some way to put the color into sRGBAlpha, such as this
![color picker with sRGBAlpha option](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/e86d7c70-1644-4061-b0d5-7e6c609e330e)

**Comment by Frooxius** [comment]
This is intentional.

sRGBAlpha is specifically to support legacy content and provide better compatibility with it.

You should not be using it for any new content. If you do use it for new content, you risk breakage and issues, which we will not support fixing.

**Comment by Frooxius** [comment]
It might be good to add this to the Wiki!

**Comment by Geenz** [comment]
We'll also be disabling it overall in the near-ish future to explicitly prevent new content from (easily) being made from it through ProtoFlux or otherwise.
