### ISSUE TITLE
Add In Poiyomi Toon AND/OR a Roughness/Smoothness Map for materials

### ISSUE THREAD

**Issue by hunterbrust** [Yellow-Dog-Man/Resonite-Issues#1369]
### Is your feature request related to a problem? Please describe.

Without a Roughness/Smoothness map I cannot make parts of meshes shiny in the right way. Metallic map is not enough. Poiyomi Toon has those maps built in and way more features that I would love to have in resonite

### Describe the solution you'd like

Add Poiyomi Toon as a material option

### Describe alternatives you've considered

add/update materials to include roughness/smoothness maps/masks.

### Requesters

Buckybrust

**Comment by Stellanora64** [comment]
You can already do this via the alpha channel of a mantellic map, see more here: https://wiki.resonite.com/PBS_Metallic .

**Comment by ProbablePrime** [comment]
Stella is quite right. Please take  alook at that link.
