### ISSUE TITLE
Unremovable Unmigrated Contacts For legacy accounts

### ISSUE THREAD

**Issue by DrShadowfish** [Yellow-Dog-Man/Resonite-Issues#1371]
### Describe the bug?

Unmigrated users are unremovable via remove contact button , ongoing bug from the start of resonite to current build.

### To Reproduce

Log onto a legacy account ( Transferred into resonite at launch) go to contacts and try to remove via remove contacts 

### Expected behavior

remove contact button should remove the contact like a transferred user

### Resonite Version Number

Beta 2024.2.12.1430

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

Vive 2018 , Quest 2

### Log Files

[TYLER-ADMIN - 2024.2.12.1430 - 2024-02-18 15_48_30.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14324425/TYLER-ADMIN.-.2024.2.12.1430.-.2024-02-18.15_48_30.log)

### Reporters

bobcatkill , DrShadowfish

**Comment by jae1911** [comment]
I can reproduce it as well.

For instance, from my account `U-j4`, I cannot remove the unmigrated users `Huske`, `Traveling` or `VerdantRose` only to cite a few (got at least 20 of those there that cannot be removed).

**Comment by DrShadowfish** [comment]
got the email shifty .my account is U-DrShadowfish / DrShadowfish         unmigrated are SoroHeadless , BrutusThunderpaw , Irishnincompoop , dagses , NightscaleTheDraqgon , BryceGaming606 , Nekudoth , Lomros Fadeshadow , DornGall

**Comment by FlameSoulis** [comment]
Can confirm this is still an issue as of Beta 2024.5.7.505.

[DEMONDOGGO-PC - 2024.5.7.505 - 2024-05-08 17_54_51.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15255511/DEMONDOGGO-PC.-.2024.5.7.505.-.2024-05-08.17_54_51.log)

**Comment by Frooxius** [comment]
This should be fixed in 2024.6.5.198, thanks!
