### ISSUE TITLE
UIX Canvas Rect Has NaN Values For Some Users

### ISSUE THREAD

**Issue by RyuviTheViali** [Yellow-Dog-Man/Resonite-Issues#1374]
### Describe the bug?

When working on finalizing the default Document Display panel, I have stumbled upon an issue where the panel is invisible to any other user in the session aside from the user who spawned the document display.

Namely, this issue occurs only when the canvas as a ContentSizeFitter on it with both HorizontalFit and VerticalFit not set to "Disabled". 

In the Document Display example, the issue is remedied only when the Rect of the included DocumentPageTexture is changed from its default [0;0;1;1] (i.e. when zoomed in on).

### To Reproduce

Either:
- Spawn out the item provided in this folder (resrec:///U-Ryuvi/R-E421F5AD00E60131CE7A94A18605F92230086ABCB4B2C63CB788DE4A5B007056)
- Notice how for the user who spawned the item, it shows normally
- Notice how for any other user, the panel is not visible

Or:
- Save the item in the above folder to your inventory
- Set it as your favorited document display
- Import a document
- Notice how for the user who spawned the item, it shows normally
- Notice how for any other user, the panel is not visible

In either case:
- Notice how for any other user than the one who spawned the item, the RectTransform on the Canvas slot of the item has NaN values for all Bounds fields
- Notice for the user who spawned the item that only the Bounds Y and Height values appear as NaN, yet the panel is still visible

Further test:
- The issue appears to partly remedy if a user changed the Rect on the included DocumentDisplayTexture (by clicking and dragging on the displayed document to zoom into the document page), with the document being properly visible to all users - however, the NaN values in the Canvas' RectTransform's Bounds field are still present.

### Expected behavior

NaN values shouldn't be present in the RectTransform, and subsequently the visual state of this example item included should be synced for all users.

### Screenshots

NaN values for a user other than the user who spawned the example item:
![20240218202602_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/386dfce8-abdc-4cdc-bb45-1700d3091b22)

NaN values for the user who spawned the example item:
![20240218204831_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/694d738c-0dca-4afd-820f-ab22e209266d)

What a user who didn't spawn the example item sees when a user spawns said item (it is invisible to the user):
![20240218203408_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/ed3b6646-6cb6-4fcf-9ebf-74564b7f4824)

What the example item should look like normally:
![20240218194719_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/241f4652-1d66-49b5-a90a-b546a8a89380)

### Resonite Version Number

Beta 2024.2.12.1430

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

User who spawns the example item: [DESKTOP-SH3F0U4_-_2024.2.12.1430_-_2024-02-18_20_30_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14325832/DESKTOP-SH3F0U4_-_2024.2.12.1430_-_2024-02-18_20_30_10.log)

User who is present but did not spawn the example item (invisible to this user): [RYUVI-TOWER - 2024.2.12.1430 - 2024-02-18 20_29_00.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14325845/RYUVI-TOWER.-.2024.2.12.1430.-.2024-02-18.20_29_00.log)

### Additional Context

This issue hasn't been tested with other example objects, but this item isn't doing anything strange in terms of utilizing UIX to show UI, aside from a dynamically-scalable canvas using a ContentSizeFitter on the canvas root slot.

### Reporters

Ryuvi (Discord: ryuvi)
Aegis_Wolf (Discord: aegis_wolf)

**Comment by Frooxius** [comment]
I can look at this myself, but since this has already been added to ProbablePrime's backlog, I'm not sure who's actually working on this right now.

@ProbablePrime Are you working on this one?

**Comment by ProbablePrime** [comment]
Go for it @Frooxius

**Comment by Frooxius** [comment]
Okay, I found the source of the issue. The LayoutElement that's under `Main Area -> PDF Interaction -> PDF View` has driven "MinWidth". 

When user joins, this gets driven as NaN. @RyuviTheViali I'm unsure how is this value computed, there's probably some division by zero happening. By fixing that, you should be able to fix this on your end.

However I am also making change to the code to reject any metrics that result in NaN's, because they end up "corrupting" the state. This will fix any cases of this happening generally. However even with that, you should not feed the LayoutElements any NaN values.

**Comment by Frooxius** [comment]
Fix is in 2024.3.12.87, which will prevent the NaN's from propagating.

However I still recommend checking the driving logic, because there might be something odd with that too that's making it result in NaN's.
