### ISSUE TITLE
Resonite 98 facet fonts hard to read

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#1375]
### Describe the bug?

The number font for the new Resonite 98 facets has some particularly bad numbers, especially in the context facets are often used.

### To Reproduce

Spawn the FPS facet

### Expected behavior

Numbers to be clearly distinct

### Screenshots

![Screenshot 2024-02-12 111132](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/fb756d7d-680a-4213-af3a-11666bae1dc0)

**Comment by ExoTheWicker** [comment]
I agree that the font is difficult to read.

**Comment by ko-tengu** [comment]
Some personal preferences that fit the theme would be along these options.
https://www.dafont.com/pc-senior.font
https://www.dafont.com/modern-dos.font
https://fontsarena.com/sysfont-by-alina-sava/

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/dfe3ea8f-9fee-4c6b-b9c3-f05b975a2ff0)
A quick mockup of each font I made.
