### ISSUE TITLE
Finger Photo Settings

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#139]
### Is your feature request related to a problem? Please describe.

These are all based off Mods that I have found very helpful to add additional options to the Finger Photos.

### Describe the solution you'd like

Capture Private UI:
I know we can do this with the streaming camera, I would like to be able to also with the finger photo so you can get in nice and close to only point at what you are trying to show someone

Finger Photo Resolution:
I have an ultrawide monitor, so I'd like to have my finger photos take pictures in that aspect ratio for easy wallpapers.     Normal Finger Photo are 1920x1080, and 2560x1440 for timed.
I'd like something like 2560x1080 for normal and like 5120x2160 for timed photo.

Adjust Timed Photo Length
Sometimes I don't need as long of a timer or I need a longer timer.  

### Describe alternatives you've considered

https://github.com/art0007i/CapturePrivateUI

https://github.com/LeCloutPanda/Resolutions

https://github.com/rassi0429/ChangePhotoTimer

**Comment by 5H4D0W-X** [comment]
I think this issue can be closed now since most of these settings are implemented in the new settings @Frooxius

**Comment by troyBORG** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10406330/7446793a-f071-4d60-9fc0-b7ad9066561c)
Yes.  I saw them in a screenshot.
Not sure about private UI capture.   But I do see resolution and timer.

**Comment by Frooxius** [comment]
Added the private UI option in 2024.4.17.1420, closing this now, thanks!

**Comment by Frooxius** [comment]
This is the quick photo capture - finger photo gesture + key combination in desktop.

Other cameras have their own systems and configuration options on themselves.

**Comment by TisFoolish** [comment]
Without mods though you can't capture private UI, which is why I asked

**Comment by Frooxius** [comment]
@TisFoolish As I've already stated to you in another thread, you do not need mods to capture private UI.

You now have two options:
1) Interactive camera, which has "Render Private UI" option in its dialog
2) This new settings for Quick Photo Capture

No mods are necessary.
