### ISSUE TITLE
Quick links in the dash as facets to moderation/support tickets and bug reporting

### ISSUE THREAD

**Issue by AeoMayo** [Yellow-Dog-Man/Resonite-Issues#1396]
### Is your feature request related to a problem? Please describe.

Common complaint I see is that there's no easy way to find the moderation/support ticket site and people aren't 100% sure where to report bugs. I feel like facets with hyperlinks to these places on the default dash would help with this and also lighten the load on mods and staff in repeatedly having to give the links in Discord.

### Describe the solution you'd like

Hyperlink dash facets to the sites in question.

### Describe alternatives you've considered

N/A, there really isn't any outside of the current status quo of bouncing people around and forcing them to ask or search

**Comment by Frooxius** [comment]
We already have issue for that here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1123

**Comment by ko-tengu** [comment]
I think this could still be a useful secondary consideration as a short term triage fix, simply a facet button to open the moderation/support page. The full help page is a good long term goal but there's room for an immediate simple answer.
