### ISSUE TITLE
Overwork the World Browser UX

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1397]
### Is your feature request related to a problem? Please describe.

I was actually surprised to not find an issue about this yet (many incremental improvement suggestions tho), so I thought I'd create it. Currently, the world browser is functional, but not very easy to use / confusing for new users. Since it is one of the central pieces of the UX, in my opinion, it would be a good idea to overwork it.

### Describe the solution you'd like

A rework / overhaul of the world browser to improve usability and readability. The biggest pain points in my opinion are:
- It is not intuitive to understand which sessions are currently opened. They are sorted to the top and have a red "X" in the corner, however they are also still affected by the current filter, which can make them disappear from the grid alltogether. I would prefer the active sessions to be displayed separately from the browser / search grid itself, and clearly labeled as "Opened Sessions" or "Worlds you're in", with a descriptive "Leave" or "Close" button, instead of just an "X" in the corner.
- The two-level menu structure for clicking on a session from the browser grid, to opening the small preview, to then expanding to the full panel is confusing. I've met many new users that didn't even realize that there is a second layer to the menu, because the arrow in the corner is rather non-descriptive and confusing. I'd vote for replacing that with a single level.
- The search doesn't tell you about the search syntax. Clicking on the search bar could expand it to show a panel briefly describing how to use the search. I'd also like search parameters like tags to be visually highlighted. Being able to enter more advanced search commands (similar to GitHub's search) would be nice. If the possible search commands are displayed below the search bar, clicking them should automatically add them to the current search (to reduce the amount of typing required for VR users).
- The custom filter is nice, even if a little confusing to set up. It would be nice if users were able to save custom filters, or even edit the default ones (although if the latter is possible it should probably also be possible to easily reset the filters to default). If the search syntax is expanded, the configuration panel might not even be necessary anymore. A button near the search bar for "Save current search" could replace it.

### Describe alternatives you've considered

Leaving it as is. But I don't think that's a good idea.

### Additional Context

Easy session / world discoverability is important. One of the complaints I've heard more frequently is that it's difficult to find people / active session on Resonite. While the social aspects can't be fixed by improving the UI, I think making the world browser more easy to use could make it easier for some people to find active sessions and people to join. I've also seen a correlation between new users complaining about bad performance and new users being unaware that they can close the 4 sessions they've been through prior.

### Requesters

JackTheFoxOtter

**Comment by JackTheFoxOtter** [comment]
The thing is, I'm not sure how much sense it makes to make tickets for many individual changes when I believe the entire UX of the world browser should be reconsidered as a whole. I purposefully made this a single ticket because I think it's worth looking at the entire thing, not the individual pieces on themselves.

**Comment by Zyzyl** [comment]
Maybe start with a Discussion post to get general feedback from the wider community? That could then be used to identify specific problems which can be spun out into more focused issues.

**Comment by Frooxius** [comment]
The decision whether to overwork something or keep doing incremental improvements is a decision that the engineering will make, it's not something you should try to decide on our behalf.

From our end, we mostly care about the individual issues and feature requests and the overall experience.

You can open Discussion for that yes if you want to discuss these before submitting issues and we can have a look. There are often a number of ways to address some issues too, so us understanding the common problems is important as well.

**Comment by JackTheFoxOtter** [comment]
Opening a discussion first seems like a better idea. I'll close this ticket in favor of #1399, then will make individual issues about the open points once some time for discussions has passed.
