### ISSUE TITLE
GlobalDelegate and DelegateProxy components make world unjoinable

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#14]
### Describe the bug?

If you attach a `GlobalDelegate<T>` or `DelegateProxy<T>` component to any slot in a world, it will immediately disconnect all users but the host, and make the world unjoinable forever afterwards.

### To Reproduce

* Create an empty slot.
* Attach either the component `GlobalDelegate<T>` or `DelegateProxy<T>`.

### Expected behavior

These components should probably not crash people out of the world.

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### Reporters

LuxKitty, Nytra

**Comment by Nytra** [comment]
I think it is specifically when you make these components with an invalid type as T, for example making GlobalDelegate<Slot> or DelegateProxy<Slot> causes an exception

**Comment by lxw404** [comment]
Here are two separate sets of logs, they are labeled by the component that was added as well as whether it was the `Host` of the session or the `Guest`.  Both instances, the guest joins the host in a completely empty world, then the offending component is added and they get disconnected and can never rejoin.

[DelegateProxy - Host - 2023.10.18.449 - 2023-10-18 07_57_11.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13024671/DelegateProxy.-.Host.-.2023.10.18.449.-.2023-10-18.07_57_11.log)
[DelegateProxy - Guest -_2023.10.18.449_-_2023-10-18_12_56_15.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13024680/DelegateProxy.-.Guest.-_2023.10.18.449_-_2023-10-18_12_56_15.log)


[GlobalDelegate - Host - 2023.10.18.449 - 2023-10-18 08_01_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13024674/GlobalDelegate.-.Host.-.2023.10.18.449.-.2023-10-18.08_01_34.log)
[GlobalDelegate - Guest -_2023.10.18.449_-_2023-10-18_12_59_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13024681/GlobalDelegate.-.Guest.-_2023.10.18.449_-_2023-10-18_12_59_34.log)

**Comment by Frooxius** [comment]
Merged fix in 2024.7.15.1359, thanks!
