### ISSUE TITLE
Black Body Color nodes return value in linear, not sRGB color space

### ISSUE THREAD

**Issue by PJB3005** [Yellow-Dog-Man/Resonite-Issues#1402]
### Describe the bug?

I was testing the Black Body Color(X) nodes to document them on the wiki, and found that they return the incorrect color space. Checking dnSpy, I found the [table](http://www.vendian.org/mncharity/dir3/blackbody/UnstableURLs/bbr_color.html) that appears to be used by the ProtoFlux nodes and it appears the incorrect values from the table are being used.

The ProtoFlux nodes return the "R G B" column values, which are linear sRGB, however the ColorX variant of the node returns them with a color space of sRGB, which is incorrect.

For example, entering a color value of 1000 Kelvin causes the node to return `[1.0000; 0.0401; 0.0000; 1.0000; sRGB]` (`#FF0A00`) from the table, however according to the table, the correct sRGB value for this is `#FF3800`, which is what you get when you run the color value through linear -> sRGB.

### To Reproduce

Run a BlackBodyColor result through linear -> sRGB and check the results against the table linked above.

ProtoFlux I made below for screenshot: `resrec:///U-1NgTRNUEoIC/R-0329bf92-1cd8-4c28-90c9-9e6845fab0fe`

### Expected behavior

BlackBodyColor should return values in sRGB space, e.g. a value of 1000 Kelvin should return `#FF3800`

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8107459/66390d82-ccce-4915-be89-525ad661b324)

### Resonite Version Number

Beta 2024.2.12.1430

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[GLACEON - 2024.2.12.1430 - 2024-02-25 17_13_30.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14396964/GLACEON.-.2024.2.12.1430.-.2024-02-25.17_13_30.log)

**Comment by BlueCyro** [comment]
Just adding here that I've noticed this as well. Until this is fixed, you can plug a colorX into a "ColorXSetProfile" node and leave the color space input blank, as it will default to converting the colorX to linear space.

Not ideal, but for the moment it simplifies the process demonstrated above to a single node.

**Comment by BlueCyro** [comment]
Stealing this one from geenz with his permission :3

**Comment by ExoTheWicker** [comment]
good luck @BlueCyro !

**Comment by ExoTheWicker** [comment]
![Dvjngo3XcAEE3K1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/6e9a6b82-eea4-4d98-9b27-f8aa0dd69726)

**Comment by Frooxius** [comment]
Merged the fix in 2024.10.29.1229! Thanks!
