### ISSUE TITLE
Some built-in assets reference Discord CDN links

### ISSUE THREAD

**Issue by paradoxical-autumn** [Yellow-Dog-Man/Resonite-Issues#1405]
### Describe the bug?

Some assets, such as the keyboard background and spatialized audio icon, reference (now dead) Discord CDN links, making asset download impossible.

This issue is _only_ present after clearing the cache as the assets have to be redownloaded.

### To Reproduce

1. Clear the game's cache
2. Open an affected asset, such as the default keyboard or any media player (those are the only two I know of)
3. The mentioned textures do not download.

### Expected behavior

These assets are downloaded from Resonite's cloud, rather than Discord's CDN, meaning these textures load properly.

### Screenshots

Video demo of this issue: https://youtu.be/6R4RVuE2IpU

### Resonite Version Number

Beta 2024.2.12.1430

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

[DESKTOP-TGC19W - 2024.2.12.1430 - 2024-02-25 21_22_43.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14397934/DESKTOP-TGC19W.-.2024.2.12.1430.-.2024-02-25.21_22_43.log)

### Additional Context

I am only aware of these two assets referencing Discord links, but it is not unlikely that there are more assets.
I have also verified that I'm not using a custom keyboard, media player, audio stream, etc.

### Reporters

- paradox19 (Resonite username) / paradoxical_autumn (Discord username)
- Spacee1 (Resonite username)

**Comment by TisFoolish** [comment]
While this should definitely be changed to an internal link, the Discord link likely isn't dead. Instead it  it likely that it just lacks the now hard required tracking section

**Comment by paradoxical-autumn** [comment]
> While this should definitely be changed to an internal link, the Discord link likely isn't dead. Instead it  it likely that it just lacks the now hard required tracking section

You're right, the links aren't dead as they can still be fetched by the Discord API* but in the context of the game, they effectively are as trying to open them results in an error due to the lack of a valid tracker.

* (just pasting the URLs into Discord proves this, the image still embeds but has a tracker appended automatically)

**Comment by Nytra** [comment]
This is probably a Content issue, not a Bug

**Comment by paradoxical-autumn** [comment]
> This is probably a Content issue, not a Bug

I've just realised that 🤦
_(...and I've also realised that I can't edit the labels on this post.)_

**Comment by Nytra** [comment]
I think this mainly affects new users who don't have existing cache/database. I deleted my database and cache and I found that the default VR keyboard was transparent presumably because of a missing asset due to this.

**Comment by RyuviTheViali** [comment]
The default worlds and items have been updated to not use external CDN links. If any further links are found, please re-open this issue. For now though I'll go ahead and close this, thanks!

**Comment by paradoxical-autumn** [comment]
Heya! I've found another asset:
- The "featured" text in the cloud home.
![2024-04-11 13 51 36](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/110392755/8cb00492-4832-45ab-b767-4043d5595e5b)

*(If it's patched, it'll only affect people without a cloud home. Welp, everyone with a cloud home will just have this be forever broken.)*

**Comment by paradoxical-autumn** [comment]
(Oh, I can't reopen issues. So... @RyuviTheViali sorry for the ping.)

**Comment by paradoxical-autumn** [comment]
The panel was removed in an update to the cloud home - closing this issue!

**Comment by Nytra** [comment]
spatialized audio icon on the audio player and video player in the cloud home is not loading due to it being a dead discord CDN link

**Comment by Frooxius** [comment]
Can you make a new issue please?
