### ISSUE TITLE
Local Home fails to load and is not recreated if Assets folder was cleared

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#1414]
### Describe the bug?

I hadn't been in Resonite for some time, and I have a script on my machine running daily that deletes Cache and Assets files that weren't accessed in some time. Now that I start Resonite, Local Home doesn't load, and as I don't use a Cloud Home, I have only Userspace. What happens is I spawn in a black void (no platform), with only Dash opening in front of me and no hands/lasers to use that Dash. I've been able to F8 to Screen mode, log in and start the Cloud Home, but it is not possible using only VR.

### To Reproduce

I suspect that clearing the Cache files might play a role here (see the log below), so:
* Be playing Resonite beforehand, so you have a database
* delete all files in your Cache folder
* launch Resonite
* spawn in black void with no hands

### Expected behavior

Local Home loads in its default state

### Resonite Version Number

2024.2.12.1430

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3 via StaemLink

### Log Files

[VIXEN - 2024.2.12.1430 - 2024-02-26 19_34_37.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14409720/VIXEN.-.2024.2.12.1430.-.2024-02-26.19_34_37.log)

I think the relevant part is this:
```
19:35:02.432 (  0 FPS)	Fetching home world record: resrec:///M-bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey/R-Home
19:35:02.678 (  0 FPS)	OldVersion: -1, NewVersion: 5, Modified: False
19:35:02.722 (  0 FPS)	OldVersion: -1, NewVersion: 1, Modified: False
19:35:03.936 (  0 FPS)	OldVersion: -1, NewVersion: 0, Modified: False
19:35:04.054 (  0 FPS)	Workspace Private/RadiantDash/Screens initialized to default
19:35:04.055 (  0 FPS)	OldVersion: -1, NewVersion: 4, Modified: False
19:35:04.073 (  0 FPS)	Workspace Private/RadiantDash/TopBar initialized to default
19:35:04.090 (  0 FPS)	Requesting gather for: local://bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey/_4f-_aORIk2ETjg3NzVO2w.lz4bson
19:35:04.103 (  0 FPS)	Failed gather for local://bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey/_4f-_aORIk2ETjg3NzVO2w.lz4bson, path: D:\Games\ResoniteData\Cache\w44vahp3znx9wgv1
GatherJob local://bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey/_4f-_aORIk2ETjg3NzVO2w.lz4bson, State: Failed, StatusCode: 0, Progress: 0.00, Started: 01/01/0001 00:00:00
19:35:04.103 (  0 FPS)	Failed the retrieve file for local://bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey/_4f-_aORIk2ETjg3NzVO2w.lz4bson, returned path: null
19:35:06.515 (  0 FPS)	Error logging in: BadRequest
Login.InvalidCredentials
19:35:06.534 (  0 FPS)	Rebuild: 240.4977 ms, Nodes: 1044, Groups: 127
19:35:06.574 (  0 FPS)	Starting Steam Voice Recording
19:35:06.925 (  0 FPS)	Failed gather for https://media.discordapp.net/attachments/229405986387918848/1118634140733014198/9slice-round-1-2_0.33_2.png, path: D:\Games\ResoniteData\Cache\xfa093p2kybcp143
GatherJob https://media.discordapp.net/attachments/229405986387918848/1118634140733014198/9slice-round-1-2_0.33_2.png, State: Failed, StatusCode: Forbidden, Progress: 0.00, Started: 01/01/0001 00:00:00
19:35:06.925 (  0 FPS)	Failed Load: Could not gather asset variant: version=3&compression=BC3_Crunched&quality=100&width=128&height=128&mips=True&filtering=Bilinear&colorPreprocess=None&alphaPreprocess=None, file: , for: https://media.discordapp.net/attachments/229405986387918848/1118634140733014198/9slice-round-1-2_0.33_2.png, instance: 721403392
19:35:06.962 (  0 FPS)	Loading a Machine Home World, failed. State: OK with error: 
19:35:06.962 (  0 FPS)	Halting creation of default Machine Home World
```

### Reporters

shadowpanther

**Comment by Nytra** [comment]
Looks like its trying to access discord URLs, so this might be related to this issue https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1405

**Comment by shadowpanther** [comment]
> If so, you are effectively corrupting your own database.

I've been deleting non-accessed files both in Assets and Cache (both mapped to another drive) for some time and had no issues. Also notice that failed gather job refers to `D:\Games\ResoniteData\Cache\` folder where Cache is, not Assets.

Also also, besides Local Home missing there were no issues with assets loading and functioning once I started Cloud Home, so the database itself is not corrupted.

Okay, trying to reproduce with a fresh database and only Cache cleared I get this:
```
20:31:37.976 (  0 FPS)	Creating a new Machine Home from the template URL: resrec:///G-Resonite/Worlds/HomeTemplates/Local
20:31:38.174 (  0 FPS)	Requesting gather for: resdb:///0759f73b26d416590f58b99ec994b9f927acc7999e01afb583ac2a7ce9c47922.brson
20:31:38.316 (  0 FPS)	Got asset at path: D:\Games\ResoniteData\Cache\s5zft4po768jqlku, loading world
...
20:32:03.888 ( 60 FPS)	World Saved! Name: Local. RecordId: M-bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey:R-Home. Local: 0, Global: 0
```

So the Local Home template seems to be loading from the Cloud. I've saved homes to have something to work with.

Step two, again clearing Cache:
```
20:36:49.164 (  0 FPS)	Fetching home world record: resrec:///M-bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey/R-Home
20:36:49.636 (  0 FPS)	Requesting gather for: local://bwe7u9date4dxcijwg8m4n8meytecgbrx4tdhqxc7s9w3xr43dey/yAtaiF17ZUSWHJVdpqGEvg.lz4bson
20:36:49.638 (  0 FPS)	Got asset at path: D:\Games\ResoniteData\Assets\yAtaiF17ZUSWHJVdpqGEvg.lz4bson, loading world
```

Now the Local Home is being loaded from Assets. Okay, now that I know this, I can understand why clearing everything from the Assets folder would cause saved Local Home to no longer be there. The thing that requires a fix here is recreating Local Home like the first time if the file is missing.

The Assets folder is not stored with Resonite's installation (like a static asset), so I did not expect this behaviour of not repairing it on startup if something's missing.

**Comment by Frooxius** [comment]
> > If so, you are effectively corrupting your own database.
> 
> I've been deleting non-accessed files both in Assets and Cache (both mapped to another drive) for some time and had no issues. Also notice that failed gather job refers to `D:\Games\ResoniteData\Cache\` folder where Cache is, not Assets.

You're not 100 % guaranteed to instantly run into the issue by deleting files from Assets, but that doesn't mean it can't happen.

It's sort of like saying "I've been removing random screws from my car and I've been having no issues". Nothing might happen for a bit, but eventually something will likely break.

**Comment by shadowpanther** [comment]
> Looks like its trying to access discord URLs, so this might be related to this issue #1405

The log contains this reference (UI is loading at the same moment), but the issue is not related.

**Comment by shadowpanther** [comment]
> You're not 100 % guaranteed to instantly run into the issue by deleting files from Assets, but that doesn't mean it can't happen.

True. And I do realise that removing only not-accessed files saved me from having the issue earlier.

But on the other hand, recreating the Local Home from scratch seems to be the logical fix if the Local Home's asset is missing.

**Comment by shadowpanther** [comment]
> If the asset for the local home is missing- I'd say a better option would be to run a database repair (which can be forced with [`-RepairDatabase`](https://wiki.resonite.com/Database_repair) if you wish to run it manually). But your issue is more effectively resolved by #140.

Database repair does not fix the issue, I've tried.

**Comment by Frooxius** [comment]
Yeah database repair wouldn't be able to fix this - the file is just gone, it has nowhere to get it from.

Your only two options here are to either:
1) If you have backup or way to restore the deleted files
2) Start with a fresh database

**Comment by shadowpanther** [comment]
> 2\. Start with a fresh database

That's what I ultimately did, but as I've said, having Resonite recreate the Local Home if the asset is missing would be a better solution as it would allow less technically-minded users to avoid the issue.

**Comment by Frooxius** [comment]
I don't think that's a safe choice to do, because it can exacerbate data loss.

It's not expected that files will be missing like that, so rather than trying to silently ignore it, it's one of those moments where we want things to more visibly break, so the situation can be looked into.

**Comment by shadowpanther** [comment]
Okay then, another possible solution would be to have fallback hands in Userspace if no other world is loaded. This would at least allow to interact with Dash.

**Comment by Frooxius** [comment]
That solution is still in conflict with our goal of having this have a more visible breakage.

We don't really want to optimize for corruption states, especially if continuing use can increase the corruption.

**Comment by shiftyscales** [comment]
Based on the aforementioned conversation, I am closing this out as not planned as it doesn't sound like there is anything we can / want to do here
