### ISSUE TITLE
Enable PageImages extension on the wiki

### ISSUE THREAD

**Issue by PJB3005** [Yellow-Dog-Man/Resonite-Issues#1416]
### Is your feature request related to a problem? Please describe.

The wiki has this spot for images in the search results:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8107459/66b531e1-61b6-4a90-b57b-887ddb4349a2)

However, there's no way to actually get anything to show there, currently. It seems the [PageImages](https://www.mediawiki.org/wiki/Extension:PageImages) would be responsible for these, but it's not currently enabled on the wiki.

### Describe the solution you'd like

Could the PageImages extension be enabled? Assuming that does it.

### Describe alternatives you've considered

None.

### Additional Context

https://discord.com/channels/1040316820650991766/1154514026177507438/1212151277715197962

**Comment by ProbablePrime** [comment]
I dont think this would actually work, I looked into it before and it seems that the skin we use isn't hooked up to use it.

https://github.com/search?q=repo%3AStarCitizenTools%2Fmediawiki-skins-Citizen+citizen-typeahead__thumbnail&type=code is a search through the codebase of the skin to find the areas it touches the search result thumbnail. I've traces this through several times and I can't find a place where it does anything other than placing the default thumbnail icon.

If you can find material that sheds some light on this please let me know.

**Comment by ProbablePrime** [comment]
:)
