### ISSUE TITLE
Prevent voice message recording from being interrupted when the cursor leaves the button

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#142]
### Is your feature request related to a problem? Please describe.

This is a mod that fixes voice message so if your laser travels out of the tiny box it doesn't cut off your voice message midway.

### Describe the solution you'd like

When you click on the voice message button as long as you keep your trigger held it should on recording until you let go of the button.

### Describe alternatives you've considered

https://github.com/Ryn-Fox/EasyVoiceMessageResonite

### Additional Context

I've sent so many messages by accident with only saying as few words because I wasn't paying attention where my laser was.

**Comment by Frooxius** [comment]
I've merged a fix for this in 2024.7.4.1347!
