### ISSUE TITLE
ChildParentAudioClipPlayer crashes world

### ISSUE THREAD

**Issue by marsmaantje** [Yellow-Dog-Man/Resonite-Issues#1420]
### Describe the bug?

If you add and then remove a ChildParentAudioClipPlayer to a slot, the world will crash once a child is added or removed from that same slot.

### To Reproduce

1. Create a ChildParentAudioClipPlayer on a slot (slot A)
2. Delete the just created component
3. have someone (not host) parent something underneath slot A
4. Crash

### Expected behavior

You don't crash

### Resonite Version Number

2024.2.12.1430

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-K2H0L1O - 2024.2.12.1430 - 2024-02-29 01_41_19.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14441360/DESKTOP-K2H0L1O.-.2024.2.12.1430.-.2024-02-29.01_41_19.log)
Started Resonite -> created empty world -> invited friend -> created/destroyed component -> had friend create child under slot

### Additional Context

When decompiling the code to take a look at the component (I know this isn't indicative of the source code, but it is what is being run on the client), I noticed the component subscribes to the child added and removed events on the slot, but never unsubscribes when being destroyed.

### Reporters

marsmaantje
Elektrospy

**Comment by marsmaantje** [comment]
It also happens if the user joins after the component has already been removed.
If the host causes the crash (by adding/removing a slot) everyone else leaves the session, but the host remains.
If anyone else causes the event the world crashes completely.

**Comment by marsmaantje** [comment]
I'll hit F3 next time when submitting bug reports, thanks for the info.
<br>

> This issue otherwise seems to have everything it needs to be looked into

Do you still want the other log files?

Also, just made a replication item. Spawn it in the world, click the button and then grab the smaller box.
`resdb:///c5669157b0fa12773a403bd147e43d67d9ee1d7ad37d8dda556665269125ad01.brson`

**Comment by Frooxius** [comment]
Merged fix in 2024.7.4.1347, thanks!
