### ISSUE TITLE
ButtonValueShift ignores MaxIsExclusive

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#1435]
### Describe the bug?

`ButtonValueShift` increments the value up to `Max` even if `MaxIsExclusive` is set to `true`.
This only happens if `WrapAround` is set to false:
```C#
if ((bool) this.MaxIsExclusive)
            Coder<T>.Sub(a3, Coder<T>.Abs(this.Delta.Value));
```
It looks like it is a forgotten assignment because it works with `WrapAround` set to true:
```C#
if ((bool) this.MaxIsExclusive)
              obj = Coder<T>.Sub(obj, Coder<T>.Abs(this.Delta.Value));
```

### To Reproduce

Setup a `ButtonValueShift<int>` on a button with `MaxIsExclusive=true` and `WrapAround=false`. Initialize the referenced target with a value just below `Max` and hit the button.
Prepared Example:
resrec:///U-TheAutopilot/R-2974feef-1445-4d02-a265-0b17047f230b
![ButtonValueShift_Setup](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/860ca19a-51a4-4631-bd00-30e675e7114a)
![ButtonValueShift_Before](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/06fa597b-b1ca-4867-b232-1e683fa99d88)
Click the button and you observe the following:
![ButtonValueShift_After](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/113014a1-958f-4985-abb5-5a3809a8d233)

### Expected behavior

`Max` should not be reached with `MaxIsExclusive` enabled:
![ButtonValueShift_Expected](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/1372baa3-bf15-4071-921d-b1f6e8d927c5)

### Resonite Version Number

2024.3.1.1178

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ANONYM - 2024.3.1.1178 - 2024-03-03 14_43_38.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14473154/ANONYM.-.2024.3.1.1178.-.2024-03-03.14_43_38.log)

**Comment by Frooxius** [comment]
Merged fix in 2024.6.24.1317, thanks!
