### ISSUE TITLE
User ID does not reset when Reset User ID is selected

### ISSUE THREAD

**Issue by MargoSizemore** [Yellow-Dog-Man/Resonite-Issues#144]
### Describe the bug?

When a reserved username is registered, the user ID will not be reset, even if the checkbox is checked for the prompt to confirm that you want to reset the user ID.

### To Reproduce

1. Create an account for a different platform that Resonite reserves usernames from.
2. Create an account for Resonite with that same username.
3. Check the box to reset the user ID.
4. Go to a new world as the new user.
5. Open a user inspector and check the user ID.

### Expected behavior

The user ID would be reset to a randomized snowflake user ID.

### Screenshots

https://youtu.be/jjrfCqBiIkA

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2 via VD, Desktop

### Log Files

[DESKTOP-8VH59O8 - 2023.10.13.743 - 2023-10-14 00_52_00.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12902552/DESKTOP-8VH59O8.-.2023.10.13.743.-.2023-10-14.00_52_00.log)
[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12902553/Player.log)

### Additional Context

I believe this feature is incredibly important for people such as myself who can't properly migrate because they're unwilling to continue to have their deadname as their user ID, as it's constantly used and displayed by people, and I personally found it a major source of discomfort in Neos, as every time I went into any world with any sort of thing that displays info about users I was terrified they'd look at me and it was the only thing I could think about.

### Reporters

MargoSizemore on Discord is me, who has discovered, reported, and replicated this bug 5 times.
shrikealvaron on Discord has also replicated this bug, as seen [here in the Resonite Discord](https://discord.com/channels/1040316820650991766/1154514008481742980/1161362327577301072).

**Comment by Frooxius** [comment]
The fix has been merged to the cloud, I'm closing this one!

**Comment by MargoSizemore** [comment]
Also, I don't know if it's related, but contacts who changed their name in Resonite still show up as their names were in Neos.
