### ISSUE TITLE
Recording on Resonite camera when moving fast causes artifacting  

### ISSUE THREAD

**Issue by Nexulan** [Yellow-Dog-Man/Resonite-Issues#1449]
### Describe the bug?

When the camera moves at a quick speed it causes artifacting/pixelation making shots lower quality 

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38895890/72a6ac7c-d953-42c6-874f-8f109975b790

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38895890/eb481e01-9d48-4b3b-821a-82b9e752f21d

### To Reproduce

Can be reproduced anywhere with the camera when recorded with OBS

### Expected behavior

Clear shots without artifacting

**Comment by Geenz** [comment]
Some of this looks like video compression artifacts?

**Comment by TisFoolish** [comment]
Yeah, all I see is compression artifacting.
