### ISSUE TITLE
Protoflux: need way to add components to slots, either empty or as copy.

### ISSUE THREAD

**Issue by NukiRaccoon** [Yellow-Dog-Man/Resonite-Issues#1459]
### Is your feature request related to a problem? Please describe.

Was building a part-maker for the Snap Furniture, but they didn't work properly.  Realized I needed to put an Object Root on the pieces themselves for the Snap Tool to properly reparent them all.  There's no ProtoFlux for adding an Object Root, so I have to do it manually.

Also noticed there's not a way to add Grabbable.

### Describe the solution you'd like

Two potential new nodes:
- Add Empty Component (Slot)
- Copy Component (Slot, Component)

The first would create a component with the default ("empty") setup under the slot, as if it were pulled from the Component Picker.

The second would take an existing Template Component and add it to the slot, copying anything over.

### Describe alternatives you've considered

The two suggestions are effectively alternatives of each other.

The current workaround is to either find a slot-structure that lets you copy in a Template Slot, or to create the component manually.

### Requesters

Nuki

**Comment by lxw404** [comment]
This was requested here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/57

A prerequisite for this is also mentioned here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1103

**Comment by Frooxius** [comment]
Yes, this is a duplicate, closing.
