### ISSUE TITLE
Gizmos are too easy to accidently inspect

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [Yellow-Dog-Man/Resonite-Issues#1460]
### Is your feature request related to a problem? Please describe.

When trying to select the parts of an object, I will often accidentally inspect the gizmo. While this does allow for custom modification or examination of the properties of said gizmo, in a majority of cases, it is an annoyance.

### Describe the solution you'd like

Make gizmos unable to be selected by pressing secondary on them with the DevTool. (Maybe make an option, but this feels pretty pointless for a majority of cases.)

### Describe alternatives you've considered

Shrinking self or growing objects to better select the intended part.

### Requesters

@EmergencyTemporalShift

**Comment by Frooxius** [comment]
I don't understand what do you mean by "selecting a gizmo"? Gizmos don't really have selection mechanism, other than the corner "dots" of the bounding box. Is that what you mean?

Screenshots or video would help.

**Comment by Banane9** [comment]
In my opinion, the proposed fix is reasonable - in the vast majority of cases, you don't want to select gizmos with the dev tool, so they should be treated as "invisible" to it, unless selecting gizmos specifically toggled on.

**Comment by Frooxius** [comment]
Ah yes, this is a simple tweak, we can make it so gizmos cannot be selected, since there's not really much reason to ever select them, since they're temporary anyways.

**Comment by EmergencyTemporalShift** [comment]
A component that makes things unable to be selected by clicking directly might be useful?

**Comment by Frooxius** [comment]
If you want a new feature like that, please make a separate request.

**Comment by Banane9** [comment]
> A component that makes things unable to be selected by clicking directly might be useful for indicators and status.

As long as you don't add a collider with laser hitting active to it, they will only be targettable using the "tip at center" method anyways.

**Comment by EmergencyTemporalShift** [comment]
I wanted to make sure it had any chance of being useful before making a whole new issue

**Comment by Frooxius** [comment]
The dev tip should fully ignore gizmos when selecting in 2024.5.29.27, thanks!
