### ISSUE TITLE
Tintable option for Glyphs on DynamicSpriteFont

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#1469]
### Is your feature request related to a problem? Please describe.

Currently using sprites from a `DynamicSpriteFont` do not have a way to use the text color from text they are used in and instead always use the sprite unchanged.

### Describe the solution you'd like

I'd like an option per glyph to be tintable on `DynamicSpriteFont`.

### Describe alternatives you've considered

Coloring the glyph to be a specific color manually.

If I needed more than one color then making additional variants of glyphs.

Creating a font that overrides unicode characters to replace them with a new glyph.

### Requesters

_deltawolf

**Comment by Frooxius** [comment]
Added this in 2024.5.23.1416!

Can I get a custom BoTC icon now? :3
