### ISSUE TITLE
Custom view visual's minimum and Max distance will be infinity and Max scale is Nan

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1472]
### Describe the bug?

When creating a custom view visual by grabbing it from the user root and putting it on your avatar and deleting components that would destroy it then saving your avatar with the custom view visual then re equipping it 

go into freeform camera mode your minimum and maximum distance will be Infinity and the max scale will be Nan On The Voice slot of the view visual

### To Reproduce

1. Create Your custom View Visual with your usual method (I use the one on my user root, removing the components that delete it)
2. Save Your Avatar (wait for Sync) to re-equip it
3. Use your view visual and inspect the voice slot the minimum and Max distance will be infinity and Max scale will be Nan

here's a video demonstration with subtitles highlighting every step of the video
https://www.youtube.com/watch?v=cx92revZ9BA

### Expected behavior

I should be able to take the view visual from my user root and put it on my avatar and have it worked no differently than it was on my user root

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/6098ba53-835b-46d7-816c-4809ce75a18e)

### Resonite Version Number

2024.3.1.1178

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.3.1.1178 - 2024-03-11 14_36_51.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14563257/DESKTOP-DAN95E7.-.2024.3.1.1178.-.2024-03-11.14_36_51.log)

### Additional Context

Note: your voice from the view visual will be muted resulting in you not being able to talk to other users using your custom view visual

### Reporters

@epicEaston197, Nordwick

**Comment by epicEaston197** [comment]
> How do you have the AvatarAudioOutputManager component configured, @epicEaston197- it is what controls the Min/Max Distance and Scale.
> 
> Can you please provide a copy of the view visual you are using? It sounds like it's probably misconfigured in some way.

The copy of the view visual I'm using was the one in my user root as described in the issue and I have touched none of its configurations

**Comment by epicEaston197** [comment]
[Resonite issues 1472](https://studio.youtube.com/video/AVB

> I saw that- but could you please still provide a copy of the avatar you made in this issue? It saves me time over having to go through all of the same replication steps you show off there so I can directly compare an unmodified view visual spawn object to the one you saved there.

Ohh sure I'll put it in a folder thanks for asking

resrec:///U-epicEaston197/R-A4E32FDF9561484D703D603915DDE81D3ECD210D0928B58C7969F59C26774FAE

**Comment by epicEaston197** [comment]
Hey I would like an update on this issue as I believe I've provided everything necessary for this issue to be replicated and for it to potentially be fixed if there's any more information I need to give please ask

**Comment by epicEaston197** [comment]
okay so an update so i've redone the recreation steps and I did not run into the same issue for some reason so this issue **_might_** be resolved but i'm not sure if it is

**Comment by shiftyscales** [comment]
Going to close this issue for now then- if you see it occurring again- please feel free to report it on this issue, or make a new one and it can be looked into further, @epicEaston197.

**Comment by epicEaston197** [comment]
okay apparently the issue popped up again randomly (it's the exact same avatar with absolutely no changes made)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/82a8ea97-6455-426f-9ec3-f900c0a9e7aa)\
