### ISSUE TITLE
World crashes when attaching world root to CanBeGrabbed

### ISSUE THREAD

**Issue by lill-la** [Yellow-Dog-Man/Resonite-Issues#1478]
### Describe the bug?

World crashes when attaching world root to CanBeGrabbed

### To Reproduce

Connect nodes to CanBeGrabbed
Slot: world root slot
Grabber: any grabber
Output: display

### Expected behavior

Do not crash

### Resonite Version Number

2024.3.12.87

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[FEIRIL - 2024.3.12.87 - 2024-03-12 11_26_57.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14566513/FEIRIL.-.2024.3.12.87.-.2024-03-12.11_26_57.log)

### Reporters

lill

**Comment by Frooxius** [comment]
Fixed this in 2024.3.12.1169, thanks!
