### ISSUE TITLE
Resonite Cloud Home target practice area non-functional

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#1479]
### Describe the bug?

The target practice area located in the balcony no longer works as expected, and will not react to projectiles or display correctly.

### To Reproduce

Visit the Resonite [Cloud Home](https://api.resonite.com/open/world/G-Resonite/R-1183403c-3388-4c53-a459-146544a6dd78) after March 9th 2024, and go to the Balcony on the right, enable the targets with the switch.

### Expected behavior

The targets should be assigned with the correct materials and react to projectiles.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/a7ebb9a8-5122-4ad7-95cb-06477196c924)

### Reporters

@zyro1331 on Discord

**Comment by ShrikeAlvaron** [comment]
Is this only on new copies of the home or does it affect old homes as well?  I can test on my own copy of it in a bit

**Comment by Zyro1331** [comment]
> Is this only on new copies of the home or does it affect old homes as well? I can test on my own copy of it in a bit
This is on a fresh copy of the Cloud Home, existing homes that have been saved before the recent Cloud Home update will not be affected.

**Comment by RyuviTheViali** [comment]
@AegisTheWolf I have a hunch that the manual asset deduplication ran on the world not long ago could be the cause for this issue. I can look into restoring function to the target range.

**Comment by Nytra** [comment]
It looks like some of the flux in the targets is trying to write to materials which don't exist

if you ran material deduplication in the asset optimization wizard you need to be careful with that I had it break one of my worlds before

**Comment by Zyro1331** [comment]
This issue has been fixed as of 4/23/24, and had been fixed for over a month ago. Closing this issue as solved.
