### ISSUE TITLE
ParticleBrush sets the wrong ParticleStyle reference.

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#1480]
### Describe the bug?

With today's update, you can now set particles in the brush tool, but while playing with it, I found a bug.
When "ParticleTemplateHandling" is set to "CloneComponent", the cloned ParticleSystem does not refer to the correct ParticleStyle.

In this case, when you paint something with a brush, a Slot named "Brush Strokes" is generated.
This Slot contains the ParticleSystem and ParticleStyle duplicated from the brush.
If you check the "Style" field in ParticleSystem, you will see that it refers to the ParticleStyle before the duplication. (In other words, the ParticleStyle in the Brush Strokes Slot is not used.)

![2024-03-12-11 35 51](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/d7eeaa29-f17c-4494-b8b0-1c2691b18228)

I think the ParticleStyle in the Brush Strokes Slot should be referenced.

### To Reproduce

There is a brush in this folder to reproduce this problem.
resrec:///U-orange/R-851AF98DF7A71D6AEB3718B42ADA8234303D26A05644C0F27E57B0856DD151BB

1. Remove the brush from the folder.
2. Paint something.
3. Examine the stroke in the inspector and you will see that the ParticleSystem refers to the ParticleStyle in the brush.

### Expected behavior

ParticleSystem should refer to the ParticleStyle in the Brush Strokes Slot.

### Resonite Version Number

2024.3.12.87

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, VIVE Pro

### Log Files

[MENTAIKO - 2024.3.12.87 - 2024-03-12 20_26_55.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14571681/MENTAIKO.-.2024.3.12.87.-.2024-03-12.20_26_55.log)

### Reporters

orange3134

**Comment by Frooxius** [comment]
Fixed this in 2024.3.12.1169, thank you!
