### ISSUE TITLE
A more generic way of changing gizmos without the context menu

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1485]
### Is your feature request related to a problem? Please describe.

i want a way to be able to edit gizmo options without the context menu i want to be able to create custom UI that would be able to edit gizmo options 

The title of this issue is subject to change i don't really know what to call it

### Describe the solution you'd like

I propose a component called CurrentGizmo it would have an integer number like an index the index would determine which gizmo is selected this would be really good for UI since I can just send a dynamic impulse with data or do a button value set to select different types of gizmos

### Describe alternatives you've considered

None really all the methods used to edit the gizmos is in the context menu and there's no clear way to extract or move them around so i can use them in other contexts

### Additional Context

currently I have an inspector that can be split into two halves with a button press and parented to my view visual 

but I still need to use the radial menu if I want to edit gizmo options I would like to create a UI for this but currently the methods used for switching gizmos resides in the radial menu and there's no clear way to access or activate them

### Requesters

@epicEaston197

**Comment by Nytra** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/599

**Comment by epicEaston197** [comment]
> #599

that is selection not editing gizmos those are two separate things

**Comment by Nytra** [comment]
gizmos would likely be overhauled with the new selection system

**Comment by Banane9** [comment]
> gizmos would likely be overhauled with the new selection system

I doubt the gizmos would be significantly overhauled - they already got overhauled compared to the legacy platform. It's more about what you can use them on.

**Comment by epicEaston197** [comment]
> > gizmos would likely be overhauled with the new selection system
> 
> I doubt the gizmos would be significantly overhauled - they already got overhauled compared to the legacy platform. It's more about what you can use them on.

Yes I agree with this this issue is more about how the gizmos' mode is changed

**Comment by ko-tengu** [comment]
I agree with this because while the switching system we have now is generally better than neos' was, it's much slower and a lot of extra button presses if you're doing any amount of 3d work that needs the gizmos.

**Comment by Banane9** [comment]
> it's much slower and a lot of extra button presses if you're doing any amount of 3d work that needs the gizmos.

Yea, going from one press to four presses, having to take your focus of the gizmo as well, was really a step back, imo. As far as I can tell, you can also only switch the mode of the last gizmo you created, not even the one you last interacted with.

**Comment by ko-tengu** [comment]
Yeah, it's tied to the dev tool, so even dropping the tool for a second can break the link and force you to reselect your target.

**Comment by Frooxius** [comment]
Fog a generic way of changing gizmos, you can already build your own systems to do this. On the DevTool you can find a number of SyncMethods that you can call from ProtoFlux at the bottom:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/5a59f1a0-1d4e-4fea-9633-25660703530e)

For our own plans, we plan to introduce "Tool Facets", where each tool provides its own facet UI on the opposing hand when equipped, which will have the common quick-to-access options. Without that in place, Context Menu is a good hold-over.
