### ISSUE TITLE
Errors while using a specific GeometryLineBrushTool from Resonite Essentials

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1489]
### Describe the bug?

Equipping one of the Geometry Line Brush Tools from Resonite Essentials produces a number of errors while using it. Most noticeably when equipping this tool it will not position itself inside of the hand and will instead float in space somewhere. When using the tool to draw and pressing the context menu buttons some errors are produced.

When inspecting this particular tool one thing that is different about it compared to others is that it has a second GeometryLineBrushTool nested inside of it.

### To Reproduce

Equip the tool and try using it

Tool link: `resrec:///G-Resonite/R-ad0d9311-481e-423d-825d-e9b6dbc61c93`

The tool is called "Geometry Line Brush (Neon Tubes)"

### Expected behavior

The tool works as normal

### Screenshots

![2024-03-13 14 47 05](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/0e3fe5d7-9291-4425-bb00-499a8ab7a06a)

![Screenshot 2024-03-13 144753](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/61178e0a-c62d-483d-a78f-adb5c220d83c)

### Resonite Version Number

Beta 2024.3.12.1169

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[DESKTOP-H976HO2 - 2024.3.12.1169 - 2024-03-13 14_42_09.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14589479/DESKTOP-H976HO2.-.2024.3.12.1169.-.2024-03-13.14_42_09.log)

### Additional Context

N/a

### Reporters

Nytra (discord: nytra)

**Comment by Nytra** [comment]
There are still a lot of errors in the log which could mean there is something in the code to look into:

```
Exception Updating held tooltip: Element: IDC75500, Type: FrooxEngine.GeometryLineBrushTool, World: Local, IsRemoved: False, IsDestroyed: False, IsDisposed: False, Enabled: True
Element: IDC74A00, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: Geometry Line Brush (Neon Tubes), T: [-0.004690147; 0.009839128; -0.001637271], R: [-0.7022326; -0.4173919; 0.1519549; 0.556384], S: [0.9999993; 0.9999996; 1], ActiveSelf: True, IsDestroyed: False
Element: ID1A7500, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: Holder, T: [-0.03100017; 0.1166692; 0.6284325], R: [0.1868565; -0.3702334; -0.654147; -0.6325374], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID1A5000, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: Grabber, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID520300, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: GrabArea Anchor, T: [-0.01; -0.06; 0.1], R: [0; 0; 0; 1], S: [1; 0.9999999; 1], ActiveSelf: True, IsDestroyed: False
Element: ID2CD800, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: VR_Glove_Right, T: [-0.2379711; 1.197242; 0.04212809], R: [-0.5938064; 0.7085748; 0.3319903; -0.1873449], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID127900, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: User <noparse=8>Nytra 👾 (ID2F00), T: [0.8532665; -0.0002761303; -0.2354369], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID114F00, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: SpawnPoint, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID2400, Type: FrooxEngine.Slot, World: Local, IsRemoved: False, Slot name: Root, T: [0; 0; 0], R: [0; 0; 0; 1], S: [1; 1; 1], ActiveSelf: True, IsDestroyed: False
Element: ID0, Type: FrooxEngine.World, World: Local, IsRemoved: False
.

System.InvalidOperationException: Output field can be only updated from the update methods of its component
  at FrooxEngine.BrushTool.Update (System.Single primaryStrength, Elements.Core.float2 secondaryAxis, FrooxEngine.Digital primary, FrooxEngine.Digital secondary) [0x005dd] in <05370dbfb3db4c81be613b3292bb5757>:0 
  at FrooxEngine.InteractionHandler.OnInputUpdate () [0x006f3] in <05370dbfb3db4c81be613b3292bb5757>:0 
```

**Comment by Frooxius** [comment]
We'd only look into those if they happen on properly configured brushes.

The errors might be happening because the brush is misconfigured and being updated improperly - in which case those are expected.
