### ISSUE TITLE
better websockets

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#1513]
### Is your feature request related to a problem? Please describe.

so, i'm making a project with websockets and i'm thinking, hmmmm this is a bad idea, because the websocket message sending node doesn't ask for a user in which could be bad or good depending on what your point of view is.

### Describe the solution you'd like

a seprate section for wss like nodes where if you connect through localhost, you cannot pass a user to it so it allows people to do wss:// connections.

### Describe alternatives you've considered

creating a plugin to provide this would be a option but i'm not to great at mod creation.

### Requesters

@charlie_san

**Comment by ProbablePrime** [comment]
You can already use wss urls, provided your websocket server has the appropriate setup.

All websocket connections do indeed need a user.

**Comment by ProbablePrime** [comment]
Websockets utilize the host allow access system, users must allow a website before items will connect to it. 

As a rule of thumb don't add 127.0.0.1 or localhost to this list and instead setup an additional localhost alias.

**Comment by WattleFoxxo** [comment]
lilbro used self signd certs 💀
