### ISSUE TITLE
Add Pinned FAQ/Links to Steam Discussions

### ISSUE THREAD

**Issue by FlameSoulis** [Yellow-Dog-Man/Resonite-Issues#1519]
### Is your feature request related to a problem? Please describe.

Lately, it just feels like the Steam discussions is left to the few who do peruse it and people who have no idea about the other communication channels, be it Discord or even GitHub. Many things like "I'm crashing" or "how do I do X" are things that could be answered if the Discord was mentioned and bug reports were pointed at the GitHub.

### Describe the solution you'd like

Just add a pinned discussion in General Discussions with links to the Discord and GitHub, and explain the current state in a simple way. Heck, even add the Wiki since that was brought back.

### Describe alternatives you've considered

There really isn't any alternative as far as I'm aware.,

### Additional Context

I think much of the questions that end up in the discussions also paint the platform as a buggier mess than it actually is, so having no mention on where to post things or sources of other information. Many people's source of information is going to be Steam Discussions for a product on Steam.

### Requesters

Flame Soulis (flamesoulis)

**Comment by DanteTucker** [comment]
I have added a pinned post with links and descriptions of our various resources.
