### ISSUE TITLE
Log file sometimes gets spammed with message `Error running discord callbacks: NotRunning`

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1522]
### Describe the bug?

Sometimes when launching Resonite the log file will be full of a message about an error running discord callbacks.

The exact message: `Error running discord callbacks: NotRunning`

I definitely did have Discord running on my computer when this error happened.

### To Reproduce

~I don't know of any exact steps to reproduce this, but it has happened to me several times over the past months. It seems to be rare.~

1. Make sure Discord is running on your computer
2. Start Resonite normally
3. Kill the Discord process on your computer (You can right click Discord in taskbar and click "Quit Discord")
4. Note that the log file is now spammed with the message

### Expected behavior

This message is not spammed in the log file.

### Resonite Version Number

Beta 2024.3.12.1169

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[DESKTOP-H976HO2 - 2024.3.12.1169 - 2024-03-21 05_13_03.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14685983/DESKTOP-H976HO2.-.2024.3.12.1169.-.2024-03-21.05_13_03.log)

Edit with new log file after following above replication steps:

[DESKTOP-H976HO2 - 2024.3.12.1169 - 2024-03-22 08_45_02.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14720001/DESKTOP-H976HO2.-.2024.3.12.1169.-.2024-03-22.08_45_02.log)

### Additional Context

N/a

### Reporters

Nytra (discord: nytra)

**Comment by Nytra** [comment]
@shiftyscales Having tested it now, it does seem this can be replicated by simply killing the Discord process after Resonite has started running.

New replication steps:

1. Make sure Discord is running on your computer
2. Start Resonite normally
3. Kill the Discord process on your computer (You can right click Discord in taskbar and click "Quit Discord")
4. Note that the log file is now spammed with the message

New log file following the above steps:

[DESKTOP-H976HO2 - 2024.3.12.1169 - 2024-03-22 08_45_02.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14719969/DESKTOP-H976HO2.-.2024.3.12.1169.-.2024-03-22.08_45_02.log)

**Comment by ProbablePrime** [comment]
Yeah i know what this is.

**Comment by ProbablePrime** [comment]
@Nytra Did Discord restart, update or lose internet connection during this period?

**Comment by Nytra** [comment]
@ProbablePrime I don't recall, sorry.

**Comment by ProbablePrime** [comment]
Ok, It seems like if Discord restarts or "blips" we need to re-instantiate the link to it. The docs aren't great in this area.

**Comment by ProbablePrime** [comment]
I've been taking a look at this one and updated things. In a branch, I've swapped the logging to only log, status codes that are not "Not Running", "Not Installed"

We have no way, to detect or receive an event from Discord for when it turns from NotRunning -> Running. So we basically have to "keep" guessing.

With Not Installed, we also disable the Discord functionality, when we detect, that. This might help/resolve #2022 too but I want to double check how the Headless responds after this change.

**Comment by ProbablePrime** [comment]
Was about to get this rolling before I went on vacation, it's close.
