### ISSUE TITLE
Picarto Compatibility 

### ISSUE THREAD

**Issue by Faeith** [Yellow-Dog-Man/Resonite-Issues#1543]
### Is your feature request related to a problem? Please describe.

Inability to stream through a Picarto.tv hotlink pasted.
Through that of profile link or stream link.

### Describe the solution you'd like

Greetings,

It would be dearly appreciated for Picarto to be enabled. As it is presently supported by yt-dlp.

### Describe alternatives you've considered

Twitch is an alternative howbeit Picarto is my comfort platform for art. I have not located other sources to stream my artwork. Twitch is heavier. And I find it smoother to see my brush strokes via Picarto.

### Additional Context

Have a beautiful day!
This is not essential but a delightful possibility.

### Requesters

Faeith

**Comment by Frooxius** [comment]
Added in 2024.6.10.1405, thanks!
