### ISSUE TITLE
Add ParentUserSlot to CommonSpawnArea to specify the slot users are parented under

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#1548]
### Is your feature request related to a problem? Please describe.

Currently if you use a CommonSpawnArea there is ParentUser bool that can turned on and off, this is useful when you want to parent users underneath a slot _however_ you can not specify the slot. The component needs to be on the slot you want users to be parented under. 

This makes it difficult for complex spawn setups, or if the slot where users are parented under needs to be culled for whatever reason ex: a spawn "zone" where users usually move out of into other zones where they're reparented.

### Describe the solution you'd like

Having the ability to define the slot where users are parented would be really appreciated and allow much more flexibility for an already useful component.

### Describe alternatives you've considered

A alternative that could be done is place the component on a slot then use protoflux to properly reparent users underneath a slot I want them to be under _without_ the CommonSpawnArea component being on the slot itself.

### Additional Context

The reason why I'm requesting this that in a map that I'm helping with making, I have a defined spawn area that is under a culling zone which is critical for the system. However I realized thanks to Prime's help, that disabling the slot means disabling the component, which if you fall out of the world and get teleported, you get teleported to world origin due to the CommonSpawnArea being disabled.

I can't really move the spawn area on another slot else users are outside a culling system, and using a workaround of reparenting users properly doesn't seem right when the functionality of the CommonSpawnArea _almost_ does it.

### Requesters

ohzee

**Comment by Frooxius** [comment]
This is a very minor change that will not take longer than 5 minutes to do, I don't think revising the spawn system is necessary for this.

**Comment by ProbablePrime** [comment]
Ezpz

**Comment by Frooxius** [comment]
Merged this in 2024.7.12.933, thanks!
