### ISSUE TITLE
[Wiki] Separate community content from reference material

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#1549]
### Is your feature request related to a problem? Please describe.

I'll call them 'community pages' or 'community content' for now but any page that refers to specific worlds, groups, user made content being on the 'top level' of the wiki path seems odd and can potentially conflict with future official pages. Additionally having it under a specific namespace allows it to be specifically excluded/included from searches. 

When I am searching for something on the wiki, I want the default search to be only the 'reference' material like most other game wikis and never community content unless I specifically choose to search community pages/namespace. (in addition to or exclusively)

An example of some possible confusing pages that could easily exist and make the wiki less usable could be `/Menu_Dash` for some 'Menu Dash' world that might be a game versus the reference material page `/Dash_Menu`. 

Some existing categories kinda are trying to be this but don't make a given page as clear it is in that category or that it is community content.

### Describe the solution you'd like

Some form of `https://wiki.resonite.com/community/SomeCommunityContent` instead of `https://wiki.resonite.com/SomeCommunityContent` so that links going to these pages are more clear they aren't for official content or reference material.

Along with a header on community content pages to inform a user viewing that page it is community content instead of official content or reference materials. An example of which appears to be setup for the Satire pages or atleast manually added to the top as `{{Satire}}`

I think https://www.mediawiki.org/wiki/Extension:NamespacePaths would do this? didn't look around much, might be something that can be done without additional extensions

### Describe alternatives you've considered

None

### Additional Context

Some examples are currently put in `Category:Satire` or `Category:Community_Worlds` but an overarching category would probably be the best for all of these to be put into.

It isn't as bad an issue currently but it is only going to get worse as more community content type pages exist and they'll start obscuring the useful pages.

### Requesters

_deltawolf

**Comment by ProbablePrime** [comment]
This will be resolved mostly through #536 where we'll be upgrading search to be actually useful. With it in place you wont have issues separating these concerns. I'll update that with some more notes.

In Wiki's everything is either in the Main Namespace or other namespaces that are setup with a theme. We already have:
1. ProtoFlux:
2. Component:

For technical items and a few others for some administrative purposes.

The categorization system of the wiki, combined with #536 should make this a non issue. I don't want to move community content out of the main namespace as the main namespace is already starting to be quite empty.

**Comment by ProbablePrime** [comment]
gah 536 is wrong

**Comment by ProbablePrime** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1185 this one! I meant this one

**Comment by XDelta** [comment]
For the searching directly portion it may help? Still seems like unless I always go to an advanced search, my search may still be cluttered with other results for content that wouldn't be useful if it is always left in the main namespace.

Maybe it would be assisted further in these community content pages all being assigned in a namespace so that with the more advanced search is easier to just exclude them.

**Comment by ProbablePrime** [comment]
Its easier to include rather than exclude. In this case the search solution we have has "presets" and we'll be making a preset for technical matters and one for non technical matters. using these should help.

I know its called advanced search but it ties into regular search too, for regular we'll just set most of the advanced settings on the user's behalf so they get a good deal of insight.

There's some docs here: https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/AdvancedSearch/%2B/master/docs/settings.md

**Comment by XDelta** [comment]
> In this case the search solution we have has "presets"

So the technical preset would need to exclude the main namespace to not include several of the pages/types of pages I mentioned? Just seems odd to me to leave some of these in the main namespace. It could be a case of no one has moved them somewhere else or an appropriate category for them doesn't exist yet.

Beyond searching, having either some header (provided by namespace/category) or differing url path I think would help make a given page more clear it isn't a base game object/system/component/etc as I mentioned currently appears to happen for Satire pages atleast (which might just be manually added anyhow).

**Comment by ProbablePrime** [comment]
I'll re-evaluate this when we add search, but I don't want to provide additional friction to our editors at this time. If it is a problem once the new search is implemented it will be revisited. thank you.
