### ISSUE TITLE
Create system to convert old settings to the new system [COMMUNITY FEEDBACK WELCOME]

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1554]
### Is your feature request related to a problem? Please describe.

The new settings system that's currently being worked on ( https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/584 ) presents a completely new system for storing and managing setting data internally.

As such, it is not compatible with the old settings and without additional work, will effectively lead to all user settings being reset.

### Describe the solution you'd like

Implement conversion algorithm that will convert some key settings from the old system into the new system on the first initialization.

Since this requires additional time and complexity, we need to decide which old settings are worth putting time into converting and which we'll ask users to simply reconfigure once the new system rolls out.

Currently the key settings that we should probably convert are:
- [x] Host access settings (URL's and IP's that you allowed/blocked access to)
- [x] User restriction settings (blocking avatars, users, bans of users from worlds and sessions)
- [x] Screenshot auto-save path (this can be long and can take a bit of time to compose one to your liking)
- [x] Laser smoothing settings (these can take a good bit of fiddling to get to your liking)
- [x] User height (this is used by a lot of things, so we don't want this one to reset quietly)
- [x] Noise gate threshold
- [x] Smooth/Snap turn
- [x] Smooth Turn Speed
- [x] Snap Turn Angle
- [x] Smooth Turn Exclusive Mode
- [x] Use Head Direction For Movement
- [x] No-Clip Speed
- [x] Double-click interval
- [x] UI language
- [x] Don't send realtime message read status
- [x] Whisper attenuation volume

At the moment though, I'm not considering any others, because most are easy and quick enough to reconfigure. However if you feel particularly strongly about any and feel that they should be auto-converted?

If so **make sure to provide reasoning** for why given setting should be auto-converted. Each one you add means more work on our end, so it needs to be justified.

If the setting takes 5 seconds to reconfigure to your liking, we probably won't spend engineering time making that auto-convert.

### Describe alternatives you've considered

Not converting anything and having users manually re-create all their settings, but that is too extreme, particularly with the host access, bans and such.

### Additional Context

We need to determine these now. Once the conversion happens, you won't be able to re-convert them again without completely wiping all the new settings.

**Comment by sveken** [comment]
I agree with the ones already mentioned, but i would also recommend the noise threshold for the reasons above.

**Comment by Frooxius** [comment]
Ok added!

**Comment by TisFoolish** [comment]
The three settings I'd like to see converted are 

User volume settings
Dash open/close speed (I detest how slow the default speed is)
Dash curvature

**Comment by Frooxius** [comment]
@TisFoolish What is your reasoning for these?

**Comment by TisFoolish** [comment]
I have all three/seven values changed and would rather not have to experiment to figure out what feels good? Especially volume since the slides are going to be properly linear with the new ui.

**Comment by Frooxius** [comment]
Does this take significant amount of time to find the right values again?

**Comment by Banane9** [comment]
> Does this take significant amount of time to find the right values again?

I would say, if someone is very concerned about any specific values that won't be ported - they can write those down too. It's not like this is an unannounced surprise change, where you couldn't prepare.

Taking a screenshot would capture almost all values.

**Comment by Zyro1331** [comment]
Converting some of the common Locomotion settings like _Movement Deadzone_, _Use Head Direction for movement_, and _Smooth Turn_ would be very appreciated.

**Comment by TisFoolish** [comment]
I'd say it takes the same amount of time to test and figure out good sound settings as it does to set up noise gate and threshold. You have to test with multiple users around, sound effects, etc.  My volume settings are from months in Res and are very, very finely tuned. 

> I would say, if someone is very concerned about any specific values that won't be ported - they can write those down too. It's not like this is an unannounced surprise change, where you couldn't prepare.

That doesn't work when one set of sliders is linear and another is log. 80% on one isn't the same as 80% on another. Also, unless you have a mod userspace UI doesn't appear in photos.

**Comment by Frooxius** [comment]
We can consider adding these if the more interest.

You do not need mods to take screenshot. Either take one in desktop mode or enable "Show private UI in the streamer camera".

**Comment by Banane9** [comment]
> That doesn't work when one set of sliders is linear and another is log. 80% on one isn't the same as 80% on another.

80% as the displayed value should be the same on both, the difference is in where the slider is to achieve that value - at least when using the default Sliders without postprocessing the value.

**Comment by Frooxius** [comment]
Thanks for the feedback! I've implemented most of the conversions now, though they still have to be verified (I only tested them myself quickly).

You can check the initial post to see what settings are being converted now. I've included a few extra there that were not requested, because they were in same place as others that were requested.

I can still do more based on the feedback, this is just the state it's in right now.

**Comment by TisFoolish** [comment]
Why not just do all of them? I get that it's extra work, but isn't that better than inconveniencing already established users? Especially since you were able to do quite a few of them in a single day AND there are going to be a LOT of more casual users who won't know about the switch and won't have a backup of their old settings, and will thus lose everything that wasn't initially converted over. Most people are not the type of person to pay attention to devlogs, github feeds, or even just the discord server in general.

**Comment by Frooxius** [comment]
Because it's A LOT of extra work and engineering time is precious. Doing all of them could add another week worth of development just for this - and we could do a lot of other things in that week that will have more long term benefit. That's too high of a cost to pay.

If the setting takes 5-10 seconds to set back to what you like without too much fiddling or it doesn't have that much of an impact, then it's not worth spending potentially hours of engineering effort on it.

You're also making a lot of assumptions:
- It took more than one day
- The conversion hasn't been fully verified, which means the work isn't quite done. In fact, some of the settings have turned into a bit of a rabbit hole that I've been dealing with today, even though they seemed simple
- Different settings have differing level of complexity to convert, some will take much longer than others to properly map

**Comment by Frooxius** [comment]
Added!

**Comment by darbdarb** [comment]
How do i get my settings back on stable build?, reverted back and now the menu is all outta wack (i know thats why its in testing phase I'm not complaining just curious how I get my settings back)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/27961710/0c8b3c67-26e3-46ac-8c69-b98ed12232f2)

**Comment by Frooxius** [comment]
@darbdarb Please read the post: https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/1597

**Comment by Frooxius** [comment]
Last call for any feedback on this!

**Comment by Frooxius** [comment]
I've fixed the user restriction settings.

The other two actually turned out to be trickier, because those were separated between Screen & VR and converting those from the old system to the new is a lot more complicated.

I'll see what I can do there.

**Comment by Frooxius** [comment]
Ok I managed to implement a system that converts those as well now! This should all be done. 

I've published 2024.4.15.1108 prerelease if you want to verify yourself, but I did check and it seems to work fine.

**Comment by Frooxius** [comment]
Closing this now too!
