### ISSUE TITLE
Intense blur on skybox (desktop)

### ISSUE THREAD

**Issue by LuZanth** [Yellow-Dog-Man/Resonite-Issues#1563]
### Describe the bug?

When in desktop, the skybox (and any UI directly exposed to the skybox) experience extreme amounts of blur

### To Reproduce

1. Be in desktop
2. Have FarClip above 83,886
3. look at skybox
4. (optional) open a ui panel or screenshot with the skybox behind it

### Expected behavior

Little or no blurring

### Screenshots

![20240329193102_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35347126/e02d02af-3303-4176-a91c-4841c02018e3)
![20240329193551_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35347126/d0556251-e596-40fc-ac80-fb8899550af2)

### Resonite Version Number

Beta 2024.3.12.1169

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-GF4046V - 2024.3.12.1169 - 2024-03-29 19_29_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14809163/DESKTOP-GF4046V.-.2024.3.12.1169.-.2024-03-29.19_29_35.log)

### Additional Context

There is no movement in either screenshot, this happens while completely still

### Reporters

Lu Zanth

**Comment by LuZanth** [comment]
Turns out having a FarClip above 83,886 will trigger it

**Comment by Frooxius** [comment]
Why is the FarClip set to such high values?

You will get a lot of other visual artifacts too (e.g. with shadows), because the Near & Far clip determine the distribution of values in depth buffer and other things, so it might be just things getting out of usable range.

I'd recommend go keep it under 8192 overall. 

We're probably not going to prioritize this anytime soon based on this.

**Comment by LuZanth** [comment]
Understandable. I am aware this is edge-case territory. I think the reason my FarClip was so high was a lag spike happened while I was adding it, and I kept it because I didn't immediately notice any problems
