### ISSUE TITLE
fresnel lerp material does not work when using Polar UV

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#1581]
### Describe the bug?

FresnelLerpMaterial appears pink (missing shader) whenever a LerpTexture is set and LerpTexturePolarUV is set to true.

### To Reproduce

spawn reproduction object: resdb:///242d2839029c862d73a65fcd42002fc49709b21c69b85f6392dd7c27117f6f6a.brson
it will be pink

### Expected behavior

it is not pink

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/8c4447db-39bb-4d9b-bfea-c0c3133d4ad8)

### Resonite Version Number

Beta 2024.3.12.1169

### What Platforms does this occur on?

Windows

### Log Files

n/a

**Comment by Geenz** [comment]
Probably related to #200, #174, and #1117

**Comment by Geenz** [comment]
This has been fixed for the next shader update.
