### ISSUE TITLE
Allow RenderTransformOverwrride to specify "only for active user" regardless of render context

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1589]
### Is your feature request related to a problem? Please describe.

Currently, the RenderTransformOverride component when set to UserView render context will only override for the active user of the hierarchy - which makes sense as a default behavior for an avatar, but not necessarily for other applications. In the same way, overwrites for other render contexts like Camera or Mirror will always be active for every user, and you can't limit them to only a specific one.

### Describe the solution you'd like

The "only for active user" functionality that the component already seems to have for UserView to be separated from the render context, so it can be toggled independantly, for all render contexts. Perhaps it could even expose a user field as well so that it doesn't have to be hierarchy based.

### Describe alternatives you've considered

Using multiple overwrites, driving the default or overwritten transforms with unique values per users, or achieving the desired effect in other ways (not always possible). I think the change would be valuable since it would allow for more flexibility without (from my understanding) much additional complexity.

### Additional Context

Originally reported as a bug in #1582

**Comment by Frooxius** [comment]
I don't really understand what you're asking for with this. Can you give me some examples? Like when this would render and not render?

UserView specifically means "this is transformed when the user owning it is seeing it from first person perspective". It's not really something that's separable.

**Comment by JackTheFoxOtter** [comment]
Something I was trying to do in a recent project was having an override for another render context (Portal) that should only be applying to the the active user. A way I found to achieve this by driving the overridden transform so that it's only active for the user I was wanting it to be active for. When I saw the other issue I figured it could simplify those kinds of setups by making the default behavior to decide which user should have the view overwridden for more customizable so it's not only limited to the UserView context, by separating the user view and the "only for active user" behavior into two settings that can be configured independantly.

**Comment by JackTheFoxOtter** [comment]
> Well- in that case, @JackTheFoxOtter and based on Frooxius's earlier questioning- it'd probably be better to have a mechanism to assign 'ownership' of a UserView context when the object exists outside of the hierarchy of the user?

Yeah that's basically my idea. Be able to explicitly say either "this should only happen for the active user" for every render context or even exposing a user field so that behavior is fully customizable.

**Comment by Frooxius** [comment]
So you want the object to render only to specific user?

I am still having trouble understanding this. An example of scenarios where the object is rendered and where it's not would help.

**Comment by JackTheFoxOtter** [comment]
Well, it should have it's render transform overwritten only for specific user(s), but rendered for everyone. That's not just useful for hiding objects, you can also do a lot of other cool effects with it.

**Comment by Frooxius** [comment]
Why not just drive the transform with different values for specific users?

**Comment by JackTheFoxOtter** [comment]
> Why not just drive the transform with different values for specific users?

Driving the actual transform of the slot doesn't allow the same effects - it would apply to all render context. Driving the overridden transform on the RenderTransformOverride would work, as I said that's the solution I found in my use-case as well. I think having options on the RenderTransformOverride to specify a user / always the active user directly could simplify those setups, and if a user reference field is exposed, also work better with other functionality, like the AvatarUserReferenceAssigner for disconnected hierarchies, as Shifty brought up as an example.

**Comment by Frooxius** [comment]
What would be the difference between driving the transform for specific users and what you are requesting?

**Comment by JackTheFoxOtter** [comment]
Simpler setup. I think my assumption was not necessarily correct that this would be a simple change. I figured since someone else was asking about it (in the context of overriding the UserView / first person view for everyone in the linked bug report) it might be worth to submit the idea separately, because I liked it, and it could perhaps help others. But if UserView is intended to be the only render context override limited to a specific user, perhaps this wouldn't be the best approach.

**Comment by Frooxius** [comment]
If simpler setup is the only reason, I don't think we'd add this for that purpose. 

Render overrides are specifically meant for scenarios that cannot be achieved at all simply by driving, because it would require the value to be driven with different values in different render contexts, that all happen "at the same time" from perspective of the data model.

**Comment by JackTheFoxOtter** [comment]
Yeah I understand that. I've slept over it, and I think my confusion was based on the meaning of "UserView".

The only thing you actually cannot currently do by driving the RenderTransformOverride's target transform fields to different values per user is overwriting the transforms **only** in the "FirstPersonView" context. I suppose both UserView and ExternalView should only apply to the active user for the purose of modifying / hiding parts of their avatar / third person camera model only for them in those render contexts. Then, for purposes of other creations, it might be useful to additionally add "FirstPersonView" and "ThirdPersonView" as non user-specific render contexts that apply for everyone, which could then be used for driving different values per user like you can already do with Camera / Mirror / Portal.

The only alternative to this I see would be using the data model transform as the "FirstPersonView" transform, and having multiple RenderTransformOverride components to override all other available render contexts to the same value, which I would think isn't a good solution. Either that or injecting multiple RenderTransformOverride components into each present user.

**Comment by JackTheFoxOtter** [comment]
Closing this because the original request is already possible for the most part. I'll go through what's possible and what not with RTOs currently and create a new issue for specific functionality if there's actually the need for it.
