### ISSUE TITLE
Create icons for new setting UI categories

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1591]
### Is your feature request related to a problem? Please describe.

The new setting UI introduces concept of categories for different setting types, which can include icons.

### Describe the solution you'd like

Create icons that will make it easy to visually distinguish the setting categories from each other. Currently we have following categories:

- Controls
- Devices
- Profile
- Audio
- Network
- Security
- Misc
- Privacy
- User Interface
- Graphics

This is how it looks right now with temporary icons:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/2a7f96e5-8d23-4632-aee2-2cbc3363470c)

### Describe alternatives you've considered

N/A

**Comment by ChromaShiba** [comment]
Awesome! This is looking great, I'll get started on this today!

**Comment by ChromaShiba** [comment]
Alright I have some icons for this UI. Will throw them at @RyuviTheViali to test via our discord first before updating the press kit. 
![Settings_Misc](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/c75613df-a17e-411f-a3fc-40911f86defe)
![Settings_Network](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/adb99614-2704-4e14-bb73-e80353f8fdf3)
![Settings_Privacy](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/4e020f6c-5a4b-4972-9dc7-26b6cfaf00d3)
![Settings_Profile](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/ed969754-7902-4ec2-93fe-1975e6972fb0)
![Settings_Security](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/8498cad1-8d73-400c-8ff7-4d80fb7befa4)
![Settings_UserInterface](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/1dcbabe4-3501-4cc1-8e22-40c45906c603)
![Settings_Audio](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/cb37960f-346e-4876-9bd5-e4f9e91b4436)
![Settings_Controls](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/2e95e8e4-7613-4e6d-9cfd-3436c4346a1c)
![Settings_Devices](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/147d43a3-1ad2-44ea-a861-26c7c329c851)
![Settings_Graphics](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/1388f450-5d03-4e7c-bade-93efebe7dca8)

https://discord.com/channels/1005158886736658512/1214724012706627644/1225189372727398500

**Comment by TisFoolish** [comment]
Of these, which is the privacy one?

**Comment by ChromaShiba** [comment]
> Of these, which is the privacy one?

Red glasses for now

**Comment by Frooxius** [comment]
Ok since these have been done, I'm closing this! Thank you!
