### ISSUE TITLE
World Tags Should Be Editable/Should Not Auto Generate

### ISSUE THREAD

**Issue by FlameSoulis** [Yellow-Dog-Man/Resonite-Issues#1592]
### Describe the bug?

When a world is made or saved, any words used in it are saved as tags. This is additive as the name of the session changes and is backed up.

So, what's the bug? Well, because you cannot edit it, if you use a world for friendly activities, said words are then saved on the world. As you cannot remove them, if you then do any edits to said world to make it extra friendly, the terms cannot be removed, and the world is basically virtual waste.

### To Reproduce

1. Create a new world!
2. Name it "Free hugs".
3. Save the world (to inventory).
4. Rename the world to "A Lovely Vista."
5. Save the world (again).
6. Observe that the tags should now be "free, hugs, a, lovely, vista."

### Expected behavior

Tags not being based on old keywords? This is a cross of a bug and feature request.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/6835457/2590f16d-b77b-42ec-8e65-02ab41b2703e)

### Resonite Version Number

2024.3.12.1169

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Quest Pro

### Log Files

N/A

### Additional Context

The shown world is a dev world that would have been for NSFW (free hugs), but I liked the clean environment and then saved it as "Blank Dev World." I then wanted to prepare for helping out more, re-used the world, and then noticed the tags. The world has no TOS-breaking content.

### Reporters

Flame Soulis (flamesoulis)

**Comment by ProbablePrime** [comment]
Your item is a correct issue however, you **can** edit tags using the edit meta data option of a world orb. This will change them.

**Comment by Frooxius** [comment]
This is intentional behavior. The reason for this is that we do not support full text search for worlds - searching is done by tag matching (which is also reason for why you need to specify a whole word).

If we removed the auto-generation behavior at the moment, it would effectively make it impossible to search the worlds by their name.

Once we implement full text search solution, we can revisit that part.

However like prime says, you should be able to edit the tags and remove any that are not part of the name itself - any that are part of the name will be auto-added back though.

**Comment by FlameSoulis** [comment]
> Your item is a correct issue however, you **can** edit tags using the edit meta data option of a world orb. This will change them.

Where would the metadata be? Inspecting the world orb was my first goto, but only it's name shows up.

**Comment by ProbablePrime** [comment]
Click the World Orb and then selected Edit Meta Data: https://youtu.be/8GoJhA3cXsk?t=34

**Comment by badhaloninja** [comment]
You can also edit meta data from the world browser after clicking on a world,

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/1661241/461515d1-fa8a-4d8f-ba87-1f882e55b76a

**Comment by FlameSoulis** [comment]
> Click the World Orb and then selected Edit Meta Data: https://youtu.be/8GoJhA3cXsk?t=34

Confirmed! Didn't know about those extra options.

> You can also edit meta data from the world browser after clicking on a world,
> Recording.2024-04-02.211536.mp4

Maybe if the world is published? In my session, the options beyond copy session URL do not exist.

Closing issue.

**Comment by badhaloninja** [comment]
> Maybe if the world is published? In my session, the options beyond copy session URL do not exist.

This world is not published, it looks like you have to click the `<new session>` button to see these options
