### ISSUE TITLE
[Setting rework] Dashboard cannot be moved/Freeform Dash doesn't work.

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1605]
Issue: Dashboard cannot be moved/Freeform Dash doesn't work.

Freeform dash doesn't work in the settings or the facet.

_Originally posted by @ModernBalloonie in https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/1597#discussioncomment-9003034_

**Comment by JackTheFoxOtter** [comment]
As of `Beta 2024.4.5.28` this only seems partially resolved, the dash will now be grabbable when starting the game with `-ResetDash`, but the "Freeform" setting still doesn't seemt o toggle freeform mode. There is a DynamicVariableDriver on there, I would assume that probably needs to be a SettingSync component as well like the rest?

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/618e1a17-9748-4ef0-9ff2-8fb9f821072c

**Comment by JackTheFoxOtter** [comment]
Oh, oops! If you've just fixed this while I was writing this post, feel free to discard it!

**Comment by JackTheFoxOtter** [comment]
Nope, just verified on `Beta 2024.4.5.1238`, the "Freeform" setting still has no effect.

**Comment by Frooxius** [comment]
@JackTheFoxOtter Does moving the dash work?

**Comment by Frooxius** [comment]
@JackTheFoxOtter Also how are you switching the Freeform dash?

If you are doing it through the facet, can you try switching it from the new Settings UI and see if that one works?

**Comment by JackTheFoxOtter** [comment]
Yup, that works! Just the "Freeform" setting, the property on the actual dash is driven by a the cloud bool `G-Resonite.Userspace.RadiantDash.Freeform`

**Comment by JackTheFoxOtter** [comment]
> @JackTheFoxOtter Also how are you switching the Freeform dash?
> 
> If you are doing it through the facet, can you try switching it from the new Settings UI and see if that one works?

I was specifically talking about the button in the new settings page. I didn't touch the facet (I always forget that exists >.>)

**Comment by Frooxius** [comment]
@JackTheFoxOtter I've pushed another build 2024.4.5.1261

Can you replicate the bug with that one and me logs please?

**Comment by JackTheFoxOtter** [comment]
Verified on `Beta 2024.4.5.1261`, the facet works, the setting doesn't. I launched the game, toggled the "Freeform" setting a couple times - it didn't change the freeform mode, then tried the facet, that one worked, then quit the game.

[J4-C - 2024.4.5.1261 - 2024-04-05 23_35_59.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14891019/J4-C.-.2024.4.5.1261.-.2024-04-05.23_35_59.log)

**Comment by Frooxius** [comment]
When you say that the facet works, do you mean that it actually makes the dash toggle to freeform and not?

Does moving & scaling dash work?

**Comment by JackTheFoxOtter** [comment]
> When you say that the facet works, do you mean that it actually makes the dash toggle to freeform and not?

Yes. The "Freeform" setting on the settings page doesn't toggle freeform, the freeform facet on the home page does however.

> Does moving & scaling dash work?

Yes.

**Comment by Frooxius** [comment]
Oh I see now. This is actually because the "Freeform" setting isn't used at all, it's controlled by a cloud variable. I've just removed it.
