### ISSUE TITLE
OnlineStatus facet has invisible text on startup

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#1612]
### Describe the bug?

The initially selected state "Invisible" on the facet "OnlineStatus" is displayed with invisible/background colored text.
Clicking on the button changes the text to a dark/visible color.

### To Reproduce

I started the prerelease version (2024.4.3.1385) and the initial status "Invisible" was selected automatically. (without user interaction)
I was unable to reproduce this visual bug on the "normal" version. (2024.4.3.1170)

### Expected behavior

The text "Invisible" should be visible.

### Screenshots

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/9cf6d947-f2fc-460f-aa20-f7ccab8bc469)

**Comment by mpmxyz** [comment]
Is the `Offline` status supposed to be selectable? What does it do? -> Does it trigger an "offline mode" that disconnects you from the cloud or is it just a read-only status that tells you the user is not logged-in?

**Comment by RyuviTheViali** [comment]
The facet has been adjusted to properly show offline status if necessary - the update will become available when the version of the facet can be incremented. Closing, thanks!
