### ISSUE TITLE
Reflection probes fail to bake

### ISSUE THREAD

**Issue by RueShejn** [Yellow-Dog-Man/Resonite-Issues#1629]
### Describe the bug?

when trying to bake a reflection probe it will not generate the cubemap

### To Reproduce

make a reflection probe and try to bake it

### Expected behavior

it will finish its proces and the texture will be "unknown" format 

### Screenshots

![Resonite_EWoOGbfeg9](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/65612998/642cb66b-1eb0-49a2-8b84-77b59ce41bec)

### Resonite Version Number

Beta 2024.4.3.1170

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[Uploading DESKTOP-L6KVB13 - 2024.4.3.1170 - 2024-04-05 16_29_41.log…]()

**Comment by Geenz** [comment]
Investigating this one.

**Comment by Geenz** [comment]
No - not yet.  Will be able to look at it this week.

**Comment by Geenz** [comment]
Just did a small peek at this - it looks like Compressonator doesn't like the format we're requesting for cube maps.  I'll do some additional digging - I know we recently-ish updated that dependency which may be what's throwing things off here.

**Comment by ProbablePrime** [comment]
I've downloaded the logs from our asset worker to explore, Ill find the exceptions to start.

**Comment by ProbablePrime** [comment]
Froox has a fix, it'll be releasing soon.

**Comment by Frooxius** [comment]
I've fixed this in 2024.4.26.10

The Compressonator.NET definitions for CMP_FORMAT enum were just out of date, so I had to copy & paste them: https://github.com/Yellow-Dog-Man/Compressonator.NET/commit/4a862e1d14bcf66b60b2441d76a263e2d2e8847e

Closing, thanks!
