### ISSUE TITLE
Slider hamburger icon Z fighting with back of slider handle

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1632]
### Describe the issue.

The hamburger icon on the slider handle is Z fighting with the slider handle causing it to be partially visible or not visible at all

### To Reproduce

Open your settings menu and find a float slider somewhere

### Expected behavior

The hamburger icon on the slider handle should always be visible

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/aa57b8be-759e-4b35-908d-2ce03310d9af)
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/ffe6d6d1-c232-456e-b5f0-a2852b4e4e30

### Resonite Version Number

Beta 2024.4.5.1261

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A

### Additional Context

I thought this would be important to note when you take a slider out as a facet the handle is visible from the back which I don't think is intended
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/01fd01b9-ac16-4b0f-9f9e-194f072186b7)

### Reporters

@epicEaston197

**Comment by 5H4D0W-X** [comment]
This is probably happening because a material was assigned to the slider handle to fix an issue where the handle would appear behind the slider bar when being dragged to either end.

**Comment by Frooxius** [comment]
I've made a tweak to this myself to fix this for now, but I'm keeping this open, since it might have some side effects and might require a better fix.

I just reverted the slider handles to use the default UI material.

**Comment by RyuviTheViali** [comment]
After testing the sliders in a variety of situations, Froox's fix seems to be handling well. I'll go ahead and close the issue since it seems all is well. Thanks!
