### ISSUE TITLE
New facet upgrade method completely breaks home menu

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1633]
### Describe the issue.

all of my facets on my home menu look like dots my profile facet only displays my profile picture my status one only displays, online, away and busy and it's also only three dots with a background

but the facet auto upgrade did work i clicked on the version number one that looks like a dot at the moment and it copied the version number to my clipboard so they function properly it's only visually that there are messed up

(all custom facets unaffected)

### To Reproduce

Open your home menu on the new prerelease

### Expected behavior

My facets shouldn't be collapsed into a singularity on my home menu

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/e52214fd-c654-4831-9809-249d7aa1fd5e)

### Resonite Version Number

Beta 2024.4.5.1261

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.4.5.1261 - 2024-04-06 13_43_32.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14894409/DESKTOP-DAN95E7.-.2024.4.5.1261.-.2024-04-06.13_43_32.log)

### Additional Context

I heard this can be fixed just by grabbing your facet and placing it back onto your menu as I'm in desktop mode and not running mods I cannot fix this myself I also don't wanna touch anything with my dash so i don't break my settings menu

it also only affects the home menu the world's menu is completely fine

### Reporters

@epicEaston197

**Comment by epicEaston197** [comment]
> This issue isn't specific to the prerelease I believe, however. I've observed the facets breaking this way when spawned from the component on the live build as well.

Huh I did not know this thanks for updating my issue I thought this was an issue with the prerelease sorry for any confusion that this may have caused

**Comment by epicEaston197** [comment]
i noticed that the content team is still assigned to this issue but I believe engineering should be assigned to this as I don't think the content team can fix this

**Comment by Nytra** [comment]
It happened to me on Beta 2024.4.11.484. Here is a log file:

![20240411170418_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/bfa08981-aa33-4b32-97da-24d33e6a798d)

[DESKTOP-H976HO2 - 2024.4.11.484 - 2024-04-11 17_03_07.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14948581/DESKTOP-H976HO2.-.2024.4.11.484.-.2024-04-11.17_03_07.log)

**Comment by Frooxius** [comment]
I don't think this is a content issue, since there were changes to UIX that I have done, that might've affected this and the sizing. I'll have a look.

**Comment by Frooxius** [comment]
@shiftyscales That's somewhat related, but not the same issue. When you spawn them like that, they just default to their minimum size, instead of preferred, because they're not really placed anywhere.

In this case, the issue was that on the repair/upgrade, the facet data was reset, which it shouldn't have.

The facets spawned out like that aren't actually "broken", they're just really small. We can address that issue separately, but that's not so urgent for this.

**Comment by AegisTheWolf** [comment]
From looking at them, the Facet component appears to not be setting the preferred default scale of the canvas of the spawned facet from constructing a default facet from components (this was done in main build) It may be doing that same thing in the pre release when going into this).

![2024-04-11 19 21 15](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/65252793/4de54698-4a02-4c3b-909a-29bb92e4ce28)
![2024-04-11 19 21 22](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/65252793/7fb14f7c-d897-4753-88e2-e74ebcf54678)

**Comment by AegisTheWolf** [comment]
> @shiftyscales That's somewhat related, but not the same issue. When you spawn them like that, they just default to their minimum size, instead of preferred, because they're not really placed anywhere.
> 
> In this case, the issue was that on the repair/upgrade, the facet data was reset, which it shouldn't have.
> 
> The facets spawned out like that aren't actually "broken", they're just really small. We can address that issue separately, but that's not so urgent for this.

beat me to it

**Comment by epicEaston197** [comment]
This issue definitely needs to be fixed before the settings menu can be released

**Comment by Frooxius** [comment]
I already have a fix for it, but I haven't pushed the build out yet.

**Comment by Frooxius** [comment]
@epicEaston197 Can you verify that it's fixed with 2024.4.12.105 for you please?

**Comment by epicEaston197** [comment]
> @epicEaston197 Can you verify that it's fixed with 2024.4.12.105 for you please?

Yes my face it's properly upgraded without any issues and for some reason kept the background
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/67913514-99b5-4bb3-91c8-b1ac0a9e0c67)

**Comment by Frooxius** [comment]
Okay, thank you!

Yeah, it might be more prominent now after the update, it should preserve whatever size there was.
