### ISSUE TITLE
Using the german decimal separator ',' tricks Resonite in calculating a wrong user height 

### ISSUE THREAD

**Issue by Muppeq** [Yellow-Dog-Man/Resonite-Issues#1639]
### Describe the issue.

German uses ',' instead of '.' as a decimal separator in numbers. I was playing around with the new settings in the prerelease and testing the user height input with '1,75 m', Resonite converted that input into '280 cm'. 

I guess the code just discarded the ',' and the remaining string '175 m' was used and limited by some sanity check to 280 cm.

The set language does not seem to have any influence. This happened with the language set to German, but nothing changes when I set it to English.

The old settings code in the release branch just discards the whole input and keeps the old value.

### To Reproduce

Set user height to '1,75 m'

### Expected behavior

Result: '175 cm'

### Resonite Version Number

Beta 2024.4.5.1261

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-0HLEJ4K - 2024.4.5.1261 - 2024-04-07 19_47_32.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14898995/DESKTOP-0HLEJ4K.-.2024.4.5.1261.-.2024-04-07.19_47_32.log)

### Additional Context

I personally would just accept both , and . as a separator regardless of the set language or locale.

**Comment by Banane9** [comment]
Same underlying cause as #905 I suppose.

Related: #429
