### ISSUE TITLE
[feedback] Two separate inputs for imperial height

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1642]
### Describe the issue.

If you're using a VR keyboard it's really time consuming and tedious to type something like "`6' 2"`"

### To Reproduce

Go to profile and attempt to type your imperial height into the settings input you'll notice it's tedious to type

### Expected behavior

Having two different inputs to put in your height

### Screenshots

Something like this would be perfect
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/96244038-ca95-4d17-92da-31c9b5f6f972)

### Resonite Version Number

Beta 2024.4.5.1261

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

There's no crashes and there's no bug here this is just feedback

### Additional Context

I was talking with Peter the engineer and they brought this up and i thought it was actually a really good idea so that's why I'm requesting it

### Reporters

@epicEaston197

**Comment by Banane9** [comment]
How often do you change your height so that taking a few seconds longer to type ' and " is of consideration? 👀

**Comment by epicEaston197** [comment]
> How often do you change your height so that taking a few seconds longer to type ' and " is of consideration? 👀

it's not how often you do it it's the convenience of doing it typing this is just tedious to do on a keyboard especially for someone not familiar with Resonite and isn't that user friendly
it's way better just to type a number into two different fields that is much easier for a user to understand

**Comment by Banane9** [comment]
> typing this is just tedious to do on a keyboard especially for someone not familiar with Resonite and isn't that user friendly

if typing an imperial measurement properly once is _tedious_... consider how tedious it would be to engineer a solution to split one value into two fields, but only for imperial users... _just so they can save 5 seconds typing a value once_

**Comment by kythyria** [comment]
Having a separate field for imperial would be a little odd, having *two* such fields so you can tab or click to the feet field would be downright odd--and I'd expect them to read `6.1666'` and `74"` to go with `1.82m`.

**Comment by Frooxius** [comment]
I don't think this is worth the engineering complexity on our end. The system is made so it supports parsing variety of units in one. We don't have a way to handle splitting text field to multiple easily.

User height is only typed in once usually, or rarely enough, that I don't think the time we need to put into this would be justified, over other issues and improvements we can make.

**Comment by epicEaston197** [comment]
> I don't think this is worth the engineering complexity on our end. The system is made so it supports parsing variety of units in one. We don't have a way to handle splitting text field to multiple easily.
> 
> User height is only typed in once usually, or rarely enough, that I don't think the time we need to put into this would be justified, over other issues and improvements we can make.

okay that is understandable another solution that would be feasible and would only use one text field is to automatically know feet and inches with only numbers 

for example if you wanted to make your height "`5' 8"`" all that you would have to type "`5 8`" into the text box that's easier to type and it's still one text field

**Comment by TisFoolish** [comment]
> for example if you wanted to make your height "5' 8"" all that you would have to type "5 8" into the text box that's easier to type and it's still one text field

While easier and faster, a normal user would not at all be able to intuit that you can do that in the field. That's just not a common option for inputting an imperial length.

What would be nice is being able to click a button and the setting page tries to automatically figure out the VR user's height and fills in the fields itself. Users can then tweak the values to be more accurate.

**Comment by epicEaston197** [comment]
> What would be nice is being able to click a button and the setting page tries to automatically figure out the VR user's height and fills in the fields itself. Users can then tweak the values to be more accurate.

yeah that would be cool as well but it would mean i would have to close this issue as it's a feature request not sure if I need to though

**Comment by Frooxius** [comment]
> > for example if you wanted to make your height "5' 8"" all that you would have to type "5 8" into the text box that's easier to type and it's still one text field
> 
> While easier and faster, a normal user would not at all be able to intuit that you can do that in the field. That's just not a common option for inputting an imperial length.
> 
> What would be nice is being able to click a button and the setting page tries to automatically figure out the VR user's height and fills in the fields itself. Users can then tweak the values to be more accurate.

I don't think that is the case, because the user will see the default height in there, formatted with their preferred units. I think that should be clear enough indicator on how to type it in - we don't need to autodetermine their height, we just let them tweak the default one.

But with the new description sidebar we can also add the info there, which can further help. The old startup page also mentions this.

**Comment by TisFoolish** [comment]
> I don't think that is the case, because the user will see the default height in there, formatted with their preferred units. I think that should be clear enough indicator on how to type it in 

I don't see how that would allow a user to intuitively know that a short hand exists, which is what Easton suggested and I'm arguing against.  I think the current system is fine and the auto detection button is more about just improving user experience.

**Comment by Frooxius** [comment]
> > I don't think that is the case, because the user will see the default height in there, formatted with their preferred units. I think that should be clear enough indicator on how to type it in
> 
> I don't see how that would allow a user to intuitively know that a short hand exists, which is what Easton suggested and I'm arguing against. I think the current system is fine and the auto detection button is more about just improving user experience.

They would know it, because they would see in the field. You suggested yourself that the autofill would help. I don't see why would default value vs autodetected make a difference here?

**Comment by Banane9** [comment]
> > > I don't think that is the case, because the user will see the default height in there, formatted with their preferred units. I think that should be clear enough indicator on how to type it in
> > 
> > 
> > I don't see how that would allow a user to intuitively know that a short hand exists, which is what Easton suggested and I'm arguing against. I think the current system is fine and the auto detection button is more about just improving user experience.
> 
> They would know it, because they would see in the field. You suggested yourself that the autofill would help. I don't see why would default value vs autodetected make a difference here?

Foolish is merely talking about the `5 2` for `5"2'` that Easton suggested, not about the as-is format with units.
Auto-detect is just a separate suggestion to make it extra quick for VR users.

**Comment by TisFoolish** [comment]
Thank you Banane, that is exactly what I was trying to convey

**Comment by Frooxius** [comment]
I see, sorry, I thought they were related things - the auto-detect prefills values so user can see how they are formatted.

In that case I think just mentioning it in the "description" pane would help - we provide few samples of how the values can be formatted.

**Comment by epicEaston197** [comment]
> I see, sorry, I thought they were related things - the auto-detect prefills values so user can see how they are formatted.
> 
> In that case I think just mentioning it in the "description" pane would help - we provide few samples of how the values can be formatted.

Maybe a slider for determining height?
Wouldn't involve the keyboard at all

**Comment by TisFoolish** [comment]
Would be imprecise. You'd have to have a range from 2 feet (for those with dwarfism) to maybe 7 and a half feet for the really tall.

**Comment by epicEaston197** [comment]
> Would be imprecise. You'd have to have a range from 2 feet (for those with dwarfism) to maybe 7 and a half feet for the really tall.

8 feet should also be included there too also it being imprecise wouldn't be that big of a deal because the text box would remain there like float sliders

**Comment by ModernBalloonie** [comment]
To be honest a suggestion: It would be cool if there was a height autodetect button in the future that detects your head position in the playspace and compares to the ground and just automatically sets that number.

**Comment by Frooxius** [comment]
That should be a separate request. We generally ask to not mix two separate requests in one issue.

**Comment by ModernBalloonie** [comment]
> That should be a separate request. We generally ask to not mix two separate requests in one issue.

Ah okay i'll make a seperate post then.
