### ISSUE TITLE
Editor for editing blendshape keys

### ISSUE THREAD

**Issue by Fukuro99** [Yellow-Dog-Man/Resonite-Issues#1644]
### Is your feature request related to a problem? Please describe.

I purchased an avatar with many blendshape keys.
The avatars were relatively light in capacity, but would freeze when loading the avatar.
This is what the wiki describes and the blendshape keys need to be reduced. However, this is not easy to do within Resonite.
SkinnedMeshRenderer has a button called "Bake Non-Drive Blendshape" that does this, but it is a pain to have to drive the blendshape keys that you want to keep. It would be easier to choose the shape key you want to remove.

### Describe the solution you'd like

Please implement an editor for editing blendshapes.
The ability to delete blendshapes would be sufficient, but merging blendshapes would be even better.

### Describe alternatives you've considered

Drive the blendshape key you want to keep and press the "Bake Non-Drive Blendshape" button.
Or remove it with a blender or other software.

**Comment by JackTheFoxOtter** [comment]
The rational behind is that if a blendshape isn't driven, it won't change unless someone explicitly sets a new value via the inspector. For avatars in particular, I recommend that once you've dialed them in to your liking, you just bake all non-driven blendshapes. Keep in mind that once a toggle is set up for a blendshape, it also becomes driven, so those won't work. The downside of this is of course that your choices are "locked in" after you press that button. So my recommendation is always to leave blendshapes unbaked for your work version that you edit, and then create a copy that you bake for actual public use. That way, you always keep the non-baked version around for later editing.

**Comment by Fukuro99** [comment]
The method you presented is a good idea and I'm putting it into practice right now.
My point was that I wanted a way to get rid of unwanted blendshapes a little easier.

**Comment by JackTheFoxOtter** [comment]
Oh yeah I know, I think more control is generally good. I was just trying to explain the rational behind the "bake non-driven blendshapes" button, as for the use-case of avatars, that should be what you want to use in 99% of cases.

**Comment by Frooxius** [comment]
You can now bake/remove individual blendshapes in 2024.5.29.27!

**Comment by Fukuro99** [comment]
Thank you Frooxius! This is what I was looking for.
