### ISSUE TITLE
Add Unreal file support

### ISSUE THREAD

**Issue by EwoktheGood** [Yellow-Dog-Man/Resonite-Issues#1649]
### Is your feature request related to a problem? Please describe.

Currently importing UMAP files does not function

### Describe the solution you'd like

Please add support for .UMAP files to be imported

### Describe alternatives you've considered

I have already attempted to convert it to other files types but to no availfile

### Requesters

Feron

**Comment by Geenz** [comment]
We’re extremely unlikely to add support for these sorts of formats any time soon. These are very engine specific, and are likely to break version to version from other engines.
