### ISSUE TITLE
Graphic Setting - Max Texture Size

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#1658]
### Is your feature request related to a problem? Please describe.

When rendering textures a lot of them are not optimized to the level that would be good enough for a lot of lower end systems

### Describe the solution you'd like

add an option to the the new graphics settings tab that would force all textures locally to have a maximum texture resolution that is specified by the user.

### Describe alternatives you've considered

there isnt really an alternative as currently there is no way of optimizing textures without just informing the creators that they should be lowering their textures resolution

### Additional Context

I currently have 8GB of VRAM and have experienced worlds where I'm the only person that feels major lag issues. When that happens, if I optimize world textures, the issue goes away, as it seems my GPU is running out of VRAM. Other people with cards like the 1050ti would have even worse issues

**Comment by Frooxius** [comment]
This is a planned addition, but won't happen until after the new settings are released.

**Comment by Frooxius** [comment]
Added in 2024.5.3.467! Thanks!
