### ISSUE TITLE
Replace First Substring Crash

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#1659]
### Describe the bug?

when using the replace first substring flux node, if you set a start index to a number that is larger than the bounds of the provided string it will crash the user and sometimes the world when pulling out the display node

### To Reproduce

pull out a replace first substring node and fill in the string inputs with data of whatever you want
fill the startindex input with an int that is larger than the bounds of the data
finally pull out the display output, this will crash the world.

### Expected behavior

for the replace first substring data to be error handled correctly and to have the node handle invalid data gracefully 

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/04a53a60-c5bc-4a8e-9e01-97176b88e9f7)

### Resonite Version Number

2024.4.3.1170

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[User - 2024.4.3.1170 - 2024-04-11 01_35_31.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14941516/User.-.2024.4.3.1170.-.2024-04-11.01_35_31.log)

**Comment by Frooxius** [comment]
Fix merged in 2024.7.10.1399, thanks!
