### ISSUE TITLE
Power user/options menu

### ISSUE THREAD

**Issue by Bisclaveret** [Yellow-Dog-Man/Resonite-Issues#166]
### Is your feature request related to a problem? Please describe.

Resonite currently does not seem to have an options menu similar to the old NeosLauncher menu to select options and pass arguments through to the program without long lists of command line arguments.	

### Describe the solution you'd like

A menu system to load options similar to the older menu.  I know a lot of steam users never really interacted with this menu as it wasn't something you selected as an option on steam load, but as standalone I used this all the time because it was much easier and quicker to change options than pass command line arguments.

This can also help simplify optional settings as you know with clicking a radio button it's passing the correct info to the client rather than hoping you've gotten your CLI shortcut written correctly.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147937462/31e9b23b-6afe-4741-a165-e9821f3866d0)
 

### Describe alternatives you've considered

-

**Comment by troyBORG** [comment]
I know you can set the command arguments pretty easily in Steam...
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10406330/4e62bcb5-4274-4225-bb69-44295d165932)

**Comment by iamgreaser** [comment]
I still have a custom launcher (which I'd be making more use of once I can actually sync records in the Linux version) but that's mostly for controlling a list of installed mods. It supports ResoniteModLoader mods and LD_PRELOAD shims.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/138113/213b23d8-6ea9-435a-aeee-218868006f2c)

(if you're wondering about the .so files: The disabled one is what I was building to diagnose the failed texture loading, the relevant enabled one is the one which focuses entirely on working around the bug, and the other one dates back to NeosVR which works around Unity getting about half way towards supporting an IME.)

**Comment by MargoSizemore** [comment]
> I still have a custom launcher (which I'd be making more use of once I can actually sync records in the Linux version) but that's mostly for controlling a list of installed mods. It supports ResoniteModLoader mods and LD_PRELOAD shims.
> 
> 
> 
> ![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/138113/213b23d8-6ea9-435a-aeee-218868006f2c)
> 
> 
> 
> (if you're wondering about the .so files: The disabled one is what I was building to diagnose the failed texture loading, the relevant enabled one is the one which focuses entirely on working around the bug, and the other one dates back to NeosVR which works around Unity getting about half way towards supporting an IME.)
> 
> 

Now I'm curious about what piss and superpiss is

**Comment by ProbablePrime** [comment]
This will most likely be covered by: https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/614 so I will close in favor.
