### ISSUE TITLE
Scroll position does not reset between tabs

### ISSUE THREAD

**Issue by kulzae** [Yellow-Dog-Man/Resonite-Issues#1662]
### Describe the issue.

When scrolling down a section the scroll position is retained between tabs. This means if you scroll to the end of one tab and switch to the next you need to scroll up to see the settings at the top

### To Reproduce

scroll down on audio tab then switch to user interface tab

### Expected behavior

The scroll would reset between tabs so you always start at the top of the settings list for that tab

### Resonite Version Number

2024.4.11.484

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[RENEGADE - 2024.4.11.484 - 2024-04-11 09_49_16.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14946970/RENEGADE.-.2024.4.11.484.-.2024-04-11.09_49_16.log)

**Comment by 5H4D0W-X** [comment]
This should be easy to fix by adding a ButtonValueSet<float2> on any button that sets the datafeed path to reset the position

**Comment by Frooxius** [comment]
I'll need to handle this, since we need to add mechanism to trigger the reset, which we do not have right now.
