### ISSUE TITLE
Suddenly I have two settings menus!

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#1667]
### Describe the issue.

I logged into the prerelease and it seems that I have two settings menus. One using the old coloration and one using the new coloration. My dash is a little weird though because it was messed up by saving my dash in the prerelease, so I have a mangled settings menu in the duplicate that shows nothing.

### To Reproduce

I'm not really sure how to reproduce this, but my settings menu was messed up in an earlier build which caused this. What's interesting is that the duplicate settings menu, looks the same in the live build as it does the pre-release. So the old settings menu must of came back somehow?

### Expected behavior

For there to only be one settings menu.

### Screenshots

![20240411190308_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/0b39b54a-4f79-4fdc-a35b-9acc6395c178)
The new settings menu is fine, it's just it gave me a second settings menu!

Here's the live build for comparison, (my settings menu is messed up, but that's expected because I saved my dash).
![20240411190837_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/1079ee85-1f45-4362-b2bf-25d841f90e2d)

### Resonite Version Number

2024.4.12.105

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Quest Pro

### Log Files

[DESKTOP-QBGCSAQ - 2024.4.11.484 - 2024-04-11 18_57_50.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14953133/DESKTOP-QBGCSAQ.-.2024.4.11.484.-.2024-04-11.18_57_50.log)

### Reporters

modernballoonie

**Comment by Frooxius** [comment]
If you saved the settings and loaded on the old build, it's likely what ended up mangling in. It's not really something we account for, since we don't expect people will be normally going back and forth in the builds normally.

Does it go away if you reset your dash?

**Comment by ModernBalloonie** [comment]
> If you saved the settings and loaded on the old build, it's likely what ended up mangling in. It's not really something we account for, since we don't expect people will be normally going back and forth in the builds normally.
> 
> Does it go away if you reset your dash?

I loaded up the old build, reset my dash, and then I went to prerelease to test. It went away!
