### ISSUE TITLE
Y and Z axis values are linked in settings UI on "Hand tracking offset" setting

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#1668]
### Describe the issue.

Currently observable on the "Hand tracking offset" setting- it is not possible to edit the Y or Z axis values without setting both at the same time to the same value.

### To Reproduce

Edit either the Y or Z values on this setting, and note they are linked.

### Expected behavior

All axis should be separately editable.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/39724d8c-55a4-4d8e-9839-da4539f104a6

### Resonite Version Number

2024.4.12.105

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

Nothing of note is printed to the log when this occurs.
[SHIFTY-LAPTOP - 2024.4.12.105 - 2024-04-11 19_40_20.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14953404/SHIFTY-LAPTOP.-.2024.4.12.105.-.2024-04-11.19_40_20.log)

### Additional Context

Discovered this while re-testing the migrated settings. This appears to be a regression as previously in #1604 the values were properly separated.

### Reporters

@shiftyscales

**Comment by RyuviTheViali** [comment]
This issue has been resolved! I forgot to adjust the target value for the Z text field as it was still set to "y". Closing, thanks!
