### ISSUE TITLE
When you reorder a list element in the inspector, its reference proxy source gets set to null so you can no longer grab a reference to it

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1672]
### Describe the issue.

When using the list reorder feature the element loses its reference proxy source so you can no longer grab a reference to it.

Creating a new inspector fixes the issue.

### To Reproduce

1) Reorder a list element
2) Try to grab the reference to it (by grabbing the index number at the left side). It doesn't work.

### Expected behavior

The reference proxy source does not get set to null when reordering a list element

### Screenshots

![2024-04-12 10 33 47](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/80f0faa8-5214-47d7-974e-f2897afd5748)

### Resonite Version Number

Beta 2024.4.12.527

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[DESKTOP-H976HO2 - 2024.4.12.527 - 2024-04-12 11_20_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14957554/DESKTOP-H976HO2.-.2024.4.12.527.-.2024-04-12.11_20_35.log)

### Additional Context

N/a

### Reporters

Nytra (discord: nytra)

**Comment by Frooxius** [comment]
Is it for the moved element? Is it for the element it swapped with? Is it for all of them?

Does this persist if you re-open the inspector completely?

**Comment by Nytra** [comment]
So it seems this is actually a bit deeper than I originally thought. When you move any element down, it gets its reference proxy set to the element which is one index higher in the list than it should be. There will then be two elements which give the same reference proxy. You can test this by moving an element down and then grabbing the references and checking the names. The null ref only happens if you move the second-to-last element down, then it gets a index which is outside the bounds of the list by one which results in it being null.

Creating a new inspector fixes the problem.
