### ISSUE TITLE
"Camera" settings missing from settings menu

### ISSUE THREAD

**Issue by LexiBasilisk** [Yellow-Dog-Man/Resonite-Issues#1678]
### Describe the issue.

In the process of testing #1554 I noticed that the "Camera" settings seem to be missing entirely from the settings menu of my new testing account.

### To Reproduce

All I had done was launch the preview build after setting up settings to convert on the live build.

As far as I'm aware this account might not ever have opened the camera control panel- so perhaps that could be a relevant factor(?)

### Expected behavior

The camera settings should be present on the settings UI.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/550a47b4-e0bd-47b4-bcae-7624d5e3588f)

### Resonite Version Number

Beta 2024.4.12.1259

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 1 

### Log Files

[SHIFTY-LAPTOP - 2024.4.12.1259 - 2024-04-13 19_09_47.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14969292/SHIFTY-LAPTOP.-.2024.4.12.1259.-.2024-04-13.19_09_47.log)

### Additional Context

As mentioned above- I noticed this while testing settings migration from the live build.

### Reporters

@shiftyscales

**Comment by Frooxius** [comment]
Have you opened the Interactive Camera dialog?

The new setting system is dynamic and settings will be registered when something actually needs them. If you never use the interactive camera, they won't be there.
