### ISSUE TITLE
User Active View Targetting Controller Node outputs a Null Reference in VR

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#1679]
### Describe the bug?

After testing on multiple users, it appears that the User Active View Targetting Controller node outputs a null reference while in VR despite a valid active targetting controller reference existing on the avatar. Both users were using a Valve Index at the time.

### To Reproduce

1. Spawn a User Active View Targetting Controller Node
2. Input a Local User node or a Reference to a specific User
3. View the output in VR

### Expected behavior

The node should return the Active View Targetting Controller of the User.

### Screenshots

![2024-04-14 07 50 38](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/f36449a7-140b-46b2-9c63-4ad17360774d)

### Resonite Version Number

Beta 2024.4.3.1170

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[DESKTOP-1E2V3A8 - 2024.4.3.1170 - 2024-04-14 01_51_58.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14970030/DESKTOP-1E2V3A8.-.2024.4.3.1170.-.2024-04-14.01_51_58.log)

### Additional Context

The node behaves properly in desktop mode.

### Reporters

code807
LuxKitty

**Comment by Frooxius** [comment]
This is not a bug, but correct output.

When you're in VR, there is no active view targeting controller, because those are relevant only in desktop mode, therefore the output is null.

The reference on the avatar is irrelevant - that targeting controller is not active, because they are in VR.
