### ISSUE TITLE
Add min and max field to number type settings

### ISSUE THREAD

**Issue by RueShejn** [Yellow-Dog-Man/Resonite-Issues#1684]
### Is your feature request related to a problem? Please describe.

currently on the pre release you can set number fields to unintended values
most notably the open and close speed can be set to a negative number breaking the dash for desktop users 

### Describe the solution you'd like

adding a min and max value will allow us to set safe default bounds for these numbers

### Describe alternatives you've considered

could be done with protoflux but would not be good practice

**Comment by RyuviTheViali** [comment]
Okay, the relevant fields have been set so that the input text for the settings is clamped (or capable of being clamped). Closing this, thanks!
