### ISSUE TITLE
Nameplate visbility default facet broken

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1687]
### Describe the bug?

Since today, the nameplate visibility default facet appears broken.

### To Reproduce

Launch the game with -ResetDash

### Expected behavior

The default facet not to be broken.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/6cf231b4-7ed7-4b44-88c1-63251de2d202)

### Additional Context

Resonite version `Beta 2024.4.3.1170`

### Reporters

harmonicafenneccat on Discord

**Comment by RyuviTheViali** [comment]
I've fixed this issue! Turns out I accidentally deleted the relevant facet, but the missing facet has been reinstated. Closing this, thanks!
