### ISSUE TITLE
add a factorial node

### ISSUE THREAD

**Issue by Fukuro99** [Yellow-Dog-Man/Resonite-Issues#1688]
### Is your feature request related to a problem? Please describe.

Resonite does not have a node to compute factorial.
It is a little time-consuming to calculate factorials in Flux, and since factorials are used in various formulas, it is better to have a node for this purpose.

### Describe the solution you'd like

Receives input as type Int and outputs as type Int.
There is a C# library that implements this function.

https://learn.microsoft.com/ja-jp/dotnet/api/opentk.functions.factorial?view=xamarin-ios-sdk-12

### Describe alternatives you've considered

Calculated using Flux.

**Comment by Frooxius** [comment]
This is easy to add, but we'll likely add long and float/double versions too. Factorials tend to grow to large numbers really fast.

**Comment by Frooxius** [comment]
Reassigning to @BlueCyro so he can add his first node! This one should be simple enough!

**Comment by BlueCyro** [comment]
Should be in once the internal PR passes review :3

**Comment by Frooxius** [comment]
Merged this in 2024.7.11.1293! THanks!
