### ISSUE TITLE
Volume settings input does not match formatting

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#1689]
### Describe the issue.

The volume settings are formatted as a percentage, but internally still seem to be using a float value from 0-1. While adjusting the settings, I set the master volume to 100- assuming it would be 100% but it instead set it to 10,000%.

### To Reproduce

Try to type in a volume using the same formatting as it is displayed in.

### Expected behavior

The visuals/formatted values should match the input units so the user doesn't accidentally set their values higher than intended.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/ae89d59d-b64d-4770-8e6e-aac0e3f2d08c

### Resonite Version Number

2024.4.12.1259

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[SHIFTY-LAPTOP - 2024.4.12.1259 - 2024-04-15 11_11_49.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14982976/SHIFTY-LAPTOP.-.2024.4.12.1259.-.2024-04-15.11_11_49.log)

### Additional Context

Discovered when Resonite was suddenly extremely loud after entering what I believed to be valid volume values. Also relevant to #1684 as these values should be clamped to their max value, and not go past it.

### Reporters

@shiftyscales

**Comment by RyuviTheViali** [comment]
I'm unsure if this is something I can adjust on the content side of things, as the string format `P` maps 0.0 - 1.0 to 0% - 100%. I think the value internally would have to be changed from 0.0-1.0 to 0.0-100.0, however the formatting supplied by `P` would also have to be updated I believe.

**Comment by Frooxius** [comment]
I'll probably need to implement something to make the text editor be aware of the formatting.

**Comment by Frooxius** [comment]
I've made the text editors now be aware of the % formatting, which fixes this! Closing this now, it'll be in the release. Thanks!
