### ISSUE TITLE
textures as webimages

### ISSUE THREAD

**Issue by Mrs-Feathers** [Yellow-Dog-Man/Resonite-Issues#169]
### Is your feature request related to a problem? Please describe.

i would like support for textures that can be called via a web url.. like "https://example.com/image.png" to be the side of an object.

Why?: 
I would like to use grafana which we use as a service monitor to show application service status and graphs in world. these graphs only update every 30 minutes so being cached is fine but the ability to be able to use web graphics as textures or just being able to show images in placeable displays would be amazing and super helpful to our making a realistic space station style control room

### Describe the solution you'd like

you could edit an object and copy a web url that is an image to be the face of an object. images that don't render or links that aren't images could just show up as untextured.

### Describe alternatives you've considered

using the GUI interactable menus you can place, if you could load websites there, we'd be able to  get the same thing set up. if a browser like that was able to work in world, we could make working computers and sensors and graphs to be able to make a realistic looking space station or nuclear control room which is really fun and cool.

**Comment by shadowpanther** [comment]
Just pasting an image URL into the Texture2D URI field should work, but the last time I tried that the image was cached forever and did not update. You can add a meaningless parameter to the query string (?rnd=12345) to circumvent the cache.

Also, just pasting an image URL in-world should give you an object with the texture already having this URL set. Like this:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/ce8330be-e566-4a54-b75c-79bc960c79d3)

**Comment by rassi0429** [comment]
I think if direct load is checked, it will not be cached

**Comment by shadowpanther** [comment]
It would still not auto-refresh though. And even with DirectLoad it still shows the first image it got for this exact URL.

**Comment by rassi0429** [comment]
Oh, sorry. My items were refreshing with garbage query parameters

**Comment by ProbablePrime** [comment]
Thanks for making this issue.

As Shadow says, we already have web image support and a number of ways to break our caching. Due to this I'll be closing this issue. If you'd like to request that there is an option to "never cache" then you'll have to open that as a separate feature request. This is done to avoid confusion with other issues.

Thank you for making the issue.
