### ISSUE TITLE
Disabled sliders are half the length of non-disabled sliders

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#1692]
### Describe the issue.

When disabling sliders (a good test case are the positional/rotational smoothing sliders)- while disabled, the bar is half of the length it usually is.

### To Reproduce

Disable a slider, e.g. the positional/rotational smoothing sliders in Devices > Tracking Smoothing

### Expected behavior

The sliders should retain their full length while disabled.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/fbb94aba-7685-4b94-89e3-0919a9dea196)

### Resonite Version Number

Beta 2024.4.15.1234

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus Quest 1

### Log Files

[SHIFTY-LAPTOP - 2024.4.15.1234 - 2024-04-15 13_58_57.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14984360/SHIFTY-LAPTOP.-.2024.4.15.1234.-.2024-04-15.13_58_57.log)

### Additional Context

Discovered this in the same session as #1691.

### Reporters

@shiftyscales

**Comment by RyuviTheViali** [comment]
The shortening of the sliders was intentional, to better differentiate between enabled and disabled sliders.

**Comment by RyuviTheViali** [comment]
I could have the sliders as a whole become dimmer or faded out instead of changing size. With enough contrast it should still be clear that the sliders are disabled when faded/darkened.

**Comment by Frooxius** [comment]
You could also change the symbol on them perhaps or the visual of the handle? So it's clear that it can't be interacted with.

**Comment by RyuviTheViali** [comment]
I'll take into consideration some things here and see what I can do. :>

**Comment by ohzee00** [comment]
Hopefully not throwing too many ideas at you but if you wanted to convey that it's disabled and that unticking the toggle will stop that, could you make the toggle brighten when you hover over a disabled slider? Along with dimming the original slider would probably be fairly intuitive to figure out it is disabled _and_ how to enable it, I think.

**Comment by RyuviTheViali** [comment]
I've made the sliders no longer change length, and instead I have it so the sliders turn a dim red (handle included) when they are disabled.

![20240415165729_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/4b9a9901-5874-4bc0-ab5b-fe41241cffde)

**Comment by RyuviTheViali** [comment]
Adding onto your iOS reference, that is a setting available for accessibility which is disabled by default. It would be nice if we had a similar setting, though.

That would be relatively simple to add, and it was discussed prior a few times, but it was decided against due to adding visual noise. I can however still add this.

**Comment by RyuviTheViali** [comment]
Here are toggles with I/O symbols: 

![20240415171451_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/4c2d25d4-eba4-4781-b385-232afd451437)

**Comment by shiftyscales** [comment]
With the above change, I feel this issue is sufficiently resolved, thanks.
