### ISSUE TITLE
using lists as simple array's?

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#1693]
### Is your feature request related to a problem? Please describe.

so, i just watched frooxius play around with the settings ui rework and i came across the list ordering

### Describe the solution you'd like

have some nodes that could at least try to tie into this or give us a json equivilent.

### Describe alternatives you've considered

prroject obsidian's plugin though i want to play with friends and use these.

### Requesters

charlie-san

**Comment by Frooxius** [comment]
Duplicate: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/572
