### ISSUE TITLE
Input number settings are not saved and only take single digit inputs

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#1695]
### Describe the bug?

When trying to input a value into the Asset transfer settings, you will only be able to write a single digit at the time and the values will be reset upon going to another tab and going back.

### To Reproduce

1. Launch game
2. Go to settings -> networking
3. Try to enter a number in either "Maximum number of concurrent assets transfers" or "Maximum number of concurrent assets downloads"
4. Go to another settings tab
5. Come back
6. Values are gone

### Expected behavior

Those two settings should have a proper entry method and be saved.

### Screenshots

![Resonite_PS6moVMg8h](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/4a3126d7-a6be-4939-b9e9-9030deb87e69)

![Resonite_bODxbS74Bw](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/ad6f0687-1107-4bb1-867b-b53648388adf)

![Resonite_N5I1t68Y0z](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/f0d2f6a4-13ce-4252-8a4c-f0f9cfc718d4)

### Resonite Version Number

2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index; Desktop

### Log Files

[TETHYS - 2024.4.15.1407 - 2024-04-16 03_00_00.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14985203/TETHYS.-.2024.4.15.1407.-.2024-04-16.03_00_00.log)

### Reporters

U-j4 | j4.lc (Discord)

**Comment by jae1911** [comment]
While digging around, the same can also be reproduced on the resolution settings for the Photo Capture in "User Interface".

![Resonite_qtmzCMTCDl](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/44f9134e-c5d3-4f7c-b241-6c35f0ccf1f7)

**Comment by Frooxius** [comment]
Fixed this in 2024.4.16.520, thanks!
