### ISSUE TITLE
When you type numbers into settings in the settings menu, you can only type one character because it defocuses you or something.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#1696]
### Describe the bug?

When you type a number, or any value into a setting, you can only type one character before it defocuses you. In order to type more characters you need to go to another screen in your dash and go back to it, and type another one.

### To Reproduce

Try to type into a setting like Photo Resolution or something, you'll notice you can only type one character.

### Expected behavior

For it to work like the pre-release.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/b8afce18-e96b-4e9d-a965-bf2837a7257e

### Resonite Version Number

Beta 2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-QBGCSAQ - 2024.4.15.1407 - 2024-04-15 17_05_11.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14985215/DESKTOP-QBGCSAQ.-.2024.4.15.1407.-.2024-04-15.17_05_11.log)

### Reporters

ModernBalloonie

**Comment by jae1911** [comment]
Reported in #1695

**Comment by Frooxius** [comment]
Closing as duplicate
