### ISSUE TITLE
Registration DoB entry broken, registration impossible

### ISSUE THREAD

**Issue by DanteTucker** [Yellow-Dog-Man/Resonite-Issues#1698]
### Describe the bug?

Since the settings update the DoB field is not working.

Registration always fails with an invalid date.
It's not possible to type more then one character at a time, needing to click away and back to continue.

### To Reproduce

Attempt to register an account.

### Expected behavior

DoB entry should work and registration shouldn't fail.

### Resonite Version Number

Beta 2024.4.15.1407

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-TBLIEGS - 2024.4.15.1407 - 2024-04-15 20_53_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14985464/DESKTOP-TBLIEGS.-.2024.4.15.1407.-.2024-04-15.20_53_14.log)

### Reporters

Dante

**Comment by DanteTucker** [comment]
Woops. I just realized I had some mods.
Won’t be able to test again today so no idea if this is valid or not.

**Comment by Miniddawn** [comment]
same problem

**Comment by Miniddawn** [comment]
latest version

**Comment by shiftyscales** [comment]
Can you please provide log files, @Miniddawn?
