### ISSUE TITLE
Dash open / close speed is not clamped

### ISSUE THREAD

**Issue by RueShejn** [Yellow-Dog-Man/Resonite-Issues#1699]
### Describe the bug?

my dash open/close speed is set to -10, i cannot use my dash at all in that state and the -ResetDash command dose not reset setting values

currently i cant play Resonite at all until this is fixed either on my account or the command is updated

### To Reproduce

unsure as this should no longer be possible 

### Expected behavior

the command should reset values to default

### Resonite Version Number

2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

vr, and desktop

### Log Files

[DESKTOP-L6KVB13 - 2024.4.15.1407 - 2024-04-15 19_43_56.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14985477/DESKTOP-L6KVB13.-.2024.4.15.1407.-.2024-04-15.19_43_56.log)

### Additional Context

i had set this value on the pre release and didnt know it would use that value rather than the one i had set on the normal build when updating

**Comment by JackTheFoxOtter** [comment]
I don't think ResetDash should reset settings, but perhaps there could be a separate launch argument for it. Having ResetDash also reset settings to default would make it impossible to only recover userspace from a corrupted state without also resetting your settings.

**Comment by Frooxius** [comment]
This is normal. -ResetDash just resets the dash. This does not involve the settings.

**Comment by epicEaston197** [comment]
> then how would i go about reseting it?, because as mentioned i cant use resonite at all currently

if you click F6 and repeatedly click escape you might be able to click on the user interface category and navigate to the slider to where you can move it to a positive value that's what I did to fix mine

**Comment by Frooxius** [comment]
I'll add a clamp to this in the next build.

**Comment by Frooxius** [comment]
I've added a clamp in 2024.4.16.1147 even in case the setting is mis-configured. Let me know if this helps!
