### ISSUE TITLE
Broken components since update

### ISSUE THREAD

**Issue by SaraLouisa** [Yellow-Dog-Man/Resonite-Issues#1700]
### Describe the bug?

missing fields in some components and flux  nodes 

### To Reproduce

No Idea

### Expected behavior

more data fields should be present 

### Screenshots

![Photo in SaraLou Cloud Home 2024](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/154685179/80a050db-c902-4f5c-a236-0fb6b73dfff3)
![Photo in SaraLou Cloud Home 2024a](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/154685179/5349b876-5ed7-44bf-a7fd-fe1eda2a6328)

### Resonite Version Number

Latest update

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index , Quest 2

### Log Files

Not required as its on several users maxchines

### Reporters

SaraLou / SaraLouisa
SammyJo
Mevik11

**Comment by ohzee00** [comment]
Please do make sure to add log files, these could have very useful exceptions and may not require a dev to boot up the game to get said logs on their own.

**Comment by lxw404** [comment]
Make sure you are not using mods when testing these as well.  I was unable to reproduce this so it could be a mod you're using that broke...

**Comment by SaraLouisa** [comment]
found it was a mod , very sorry for inconvenience  i thought i had switched off the mods but alas i have two shortcuts and selected wrong one
