### ISSUE TITLE
Locale Setting UI Should Highlight/Indicate Current Locale

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#1701]
### Describe the bug?

Currently the Locale settings do not show the currently selected locale, making it confusing which one is selected.

### To Reproduce

Switch to the `User Interface > Locales` settings view, and choose a locale, or view the default set one. 

### Expected behavior

The currently selected locale should highlight or give some other visual indicator that it is set.

### Screenshots

![Resonite_KhkrG60UkD](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/87400bb2-067a-44ee-ac74-fd9c54e4eb3f)

### Reporters

LuxKitty

**Comment by RyuviTheViali** [comment]
I've added button highlighting to the action buttons, and updated the settings UI. Thanks!

**Comment by lxw404** [comment]
Awesome thanks~!
