### ISSUE TITLE
UserNetworkStatistic ProtoFlux node crashes world with KeyNotFoundException

### ISSUE THREAD

**Issue by tabithamoon** [Yellow-Dog-Man/Resonite-Issues#1705]
### Describe the bug?

Hosting a world and trying to get the AveragePacketSize network statistic of the host user crashes the world.

### To Reproduce

1. Create new gridworld
2. Spawn tools
3. Get user
4. Try to get AveragePacketSize statistic using the UserNetworkStatistic node

### Expected behavior

The world does not crash, and the node would probably return a 0 for the host user.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/123581598/a388ba23-068b-42f8-9790-805480b28943

### Resonite Version Number

Beta 2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Meta Quest 2

### Log Files

[CHEETAH - 2024.4.15.1407 - 2024-04-16 00_24_45.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14986520/CHEETAH.-.2024.4.15.1407.-.2024-04-16.00_24_45.log)

### Reporters

@tabithamoon

**Comment by Frooxius** [comment]
Fixed in 2024.4.16.520, thanks for report!
