### ISSUE TITLE
Settings:>Network>Asset Gathering, Cant be changed

### ISSUE THREAD

**Issue by Sharkmare** [Yellow-Dog-Man/Resonite-Issues#1709]
### Describe the bug?

Both the int entry fields on Asset Gathering cant be changed.

### To Reproduce

Try to change either settings on Settings:>Network>Asset Gathering, the setting goes blank, reselecting the tab shows unmodified values

### Expected behavior

Adjustable settings

### Resonite Version Number

2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

.

### Reporters

Eldritchkaiju , Aegis Wolf

**Comment by Sharkmare** [comment]
found #1695 after the fact, seems to apply to all int fiels

**Comment by Frooxius** [comment]
Oh this is duplicate. Fixed by 2024.4.16.520, thanks!
