### ISSUE TITLE
Unable to join Headless after update - Unhandled Exception in updating world. 

### ISSUE THREAD

**Issue by sveken** [Yellow-Dog-Man/Resonite-Issues#1710]
### Describe the bug?

Hello.
After todays update no one is able to join the headless server when hosting a particular world (Serenity). The message that shows up is 

"World Crashed" "Unhandled exception in updating the world" 

This message shows up when trying to join the world. However on the server console end, everything appears fine, typing status still shows the world as available. 

I have recreated the container from scratch, tried loading a default gridspace world (This works) 
The world opens fine when a normal user client hosts the world, like myself opening it. The world itself has not had any changes/saves in over a week

### To Reproduce

Attempt to join the headless while hosting the world. I can spin the headless back up if testing is required. 

### Expected behavior

Join works as expected.

### Resonite Version Number

2024.4.15.1407

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop

### Log Files

[1bd510f9ea5a - 2024.4.15.1407 - 2024-04-16 16_22_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14987829/1bd510f9ea5a.-.2024.4.15.1407.-.2024-04-16.16_22_14.log)

### Reporters

Faeith

**Comment by Frooxius** [comment]
I cannot find "World Crashed" "Unhandled exception in updating the world" in the log. Is it correct one?

**Comment by sveken** [comment]
That is the correct log from the headless. On the headless end it appears the world never crashes. Maybe its on the client end. 
I have removed my mods and tried to connect to the headless with this log file. This is my client 
[THICC5000 - 2024.4.15.1407 - 2024-04-16 18_32_50.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14994111/THICC5000.-.2024.4.15.1407.-.2024-04-16.18_32_50.log)

**Comment by Frooxius** [comment]
Ok I see the exception in that one, I'll have a look, thanks!

**Comment by Frooxius** [comment]
Should be fixed in 2024.4.16.1147, thanks for report! Let us know if you still run into the issue and we'll reopen.
