### ISSUE TITLE
Settings: Generated Lists generate from Host when used in world

### ISSUE THREAD

**Issue by Sharkmare** [Yellow-Dog-Man/Resonite-Issues#1711]
### Describe the bug?

Generated Lists generate from Host when facet is spawned in world
List values are unknown but names are populated

### To Reproduce

Save the settings facet.
Spawn it in a world
Open Host Access Menu
It loads the Hosts data
Open Audio Input
It shows hosts devices

### Expected behavior

For loading to fail

### Resonite Version Number

2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

.

### Reporters

Eldritchkaiju

**Comment by Frooxius** [comment]
This is expected behavior. Settings normally only generate in the userspace. If it's in the worldspace, it just defaults to the host.

**Comment by Sharkmare** [comment]
> This is expected behavior. Settings normally only generate in the userspace. If it's in the worldspace, it just defaults to the host.

Makes sense, i exected it to not generate at all in worldspace since this means all connected audio device types as well as what webhooks and webrequest the host interacted with is accesible by anyone in the session

**Comment by Chundelac** [comment]
Yeah I don't think this should be publicly visible. It could be a privacy risk.
I don't expect the game to share all my audio device names with everyone in my sessions.

**Comment by Frooxius** [comment]
I forgot to close this one. This has been resolved a few builds back.
