### ISSUE TITLE
Host access defaults are reset every time the game is restarted

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#1712]
### Describe the bug?

The host access setting has some defaults containing amongst others facebook and twitter.
When removing those and restarting the game, they come back.

### To Reproduce

1. Go in host access settings
2. Scroll until you find a default
3. Remove it
4. Relaunch the game
5. Observe that the host access is back

### Expected behavior

The host access should be removed.

### Screenshots

Removing the hosts
![Resonite_RronmFahXn](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/9ab45e33-7acc-4a44-bb88-4ac0df8ec981)

After restart:
![Resonite_tUzjwyuhI2](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/6bbba111-28f1-4137-87f1-5d6cd23f95d8)

### Resonite Version Number

Beta 2024.4.16.520

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index; Desktop

### Log Files

First start and removal:
[TETHYS - 2024.4.16.520 - 2024-04-16 12_02_43.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14994457/TETHYS.-.2024.4.16.520.-.2024-04-16.12_02_43.log)

Restart:
[TETHYS - 2024.4.16.520 - 2024-04-16 12_08_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14994493/TETHYS.-.2024.4.16.520.-.2024-04-16.12_08_34.log)

### Reporters

U-j4 | j4.lc (Discord)

**Comment by Frooxius** [comment]
Fixed in 2024.4.16.1147, thanks!
