### ISSUE TITLE
Settings options with X and Y values are broken and cannot be edited properly

### ISSUE THREAD

**Issue by paradoxical-autumn** [Yellow-Dog-Man/Resonite-Issues#1714]
### Describe the bug?

Currently, settings with an X and Y value cannot have numbers easily typed into them. Any other field works fine.

### To Reproduce

1. Open the settings menu
2. Go to an option with an X and Y input, such as `User Interface -> Photo Capture -> Timed photo resolution`
3. Try to input any value

### Expected behavior

These fields can take a value input

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/110392755/9d768324-3700-43f5-8064-a0fca23b31e3

### Resonite Version Number

Beta 2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-TGC19W - 2024.4.15.1407 - 2024-04-16 10_45_31.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14995116/DESKTOP-TGC19W.-.2024.4.15.1407.-.2024-04-16.10_45_31.log)

### Reporters

paradox19 (Resonite username) // paradoxical_autumn (Discord username)

**Comment by jae1911** [comment]
Was fixed in 2024.4.16.520, you need to update.

**Comment by paradoxical-autumn** [comment]
ah, i love steam.
