### ISSUE TITLE
Parse Color and Parse ColorX nodes do not work

### ISSUE THREAD

**Issue by JayKubJK** [Yellow-Dog-Man/Resonite-Issues#1715]
### Describe the bug?

Plugging in correctly-formatted string representations of color and colorX values into a Parse Color or Parse ColorX node fails to parse the color

### To Reproduce

1. Plug in a string such as [1; 0; 0; 1] into a Parse Color or [1; 0; 0; 1; Linear] into a Parse ColorX node
2. Pull out a display node for either the Value or IsParsed outputs

### Expected behavior

Expected behavior is that the color/colorX value is parsed when an appropriate string representation is hooked up to the node

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82873987/187d4109-3ffe-4134-91ef-2af74559a7e5)

### Resonite Version Number

Beta 2024.4.16.520

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

Quest 2

### Log Files

N/A

### Reporters

Pyroboy5000 (pyroboy on Discord) and I (jaykubjk on Discord) discovered the bug
coolymike (whippersnatchpumpkinpatch on Discord) was able to replicate it

**Comment by Frooxius** [comment]
Fixed this in 2024.4.17.208! Thanks for report!
