### ISSUE TITLE
Headless branch on Steam is offering an outdated build

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1716]
### Describe the bug?

Headless branch on Steam is offering Beta 2024.4.15.1407 when Beta 2024.4.16.520 is the latest.

This also affects the graphical client from this branch.

You can see this on SteamDB https://steamdb.info/app/2519830/history/

Headless branch was updated 13 hours ago and public/release was 4 hours ago (from the time of posting this).

### To Reproduce

Download Resonite from Headless branch and check version number

### Expected behavior

Headless branch has the latest version

### Screenshots

N/a

### Resonite Version Number

Beta 2024.4.15.1407 ?

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

N/a

### Additional Context

N/a

### Reporters

Nytra (discord: nytra)

**Comment by Nytra** [comment]
@shiftyscales the issue here is that the Headless branch on Steam comes with a graphical client which is now on an older version and therefore still has bugs that have already been fixed on more recent versions. While the builds may be compatible there are still those bugs which are affecting people (and may have led some people to make issues for those bugs believing that they have not been fixed).

**Comment by Frooxius** [comment]
There was something wrong with the publish script. I've pushed a new version, it should be okay now.

Generally any release should have a matching headless, even when compatible with current - we don't selectively push graphical client without headless.

**Comment by Nytra** [comment]
Thank you!
