### ISSUE TITLE
Audio input device selection is not working

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#1719]
### Describe the bug?

Even if I switch audio input devices on the UI, the actual audio input to Resonite always remains the default audio device.

The volume meter in the upper left corner of the screen appears to be working fine, as it appears to switch based on the selection of the microphone device, but the voice heard by others does not.

### To Reproduce

1. Display the list of audio input devices from the settings screen.
2. Switch the audio device while speaking something into the microphone.
3. Ask your friend if the sound has changed. They will tell you that there is no change.

### Expected behavior

My voice should switch depending on the device selection.

### Screenshots

To reproduce the problem alone, I set the Audio output component to play my voice.
You can see that when I switched audio input devices, the audio played did not change.
https://youtu.be/pYAhbDu0WrI

### Resonite Version Number

2024.4.16.520

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Beyond

### Log Files

[MENTAIKO - 2024.4.16.520 - 2024-04-17 01_23_43.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/14999964/MENTAIKO.-.2024.4.16.520.-.2024-04-17.01_23_43.log)

### Reporters

orange3134

**Comment by Frooxius** [comment]
Fixed in 2024.4.16.1147, thanks for report!
