### ISSUE TITLE
RefractMaterial not functioning correctly

### ISSUE THREAD

**Issue by SpaceAnon** [Yellow-Dog-Man/Resonite-Issues#172]
### Describe the bug?

The refraction filter material seems to behave as if the user's head isn't rotating and is always facing in the world z+ direction (a rotation of 0,0,0). This causes it to not distort your view at all if the surface's normal is perfectly aligned with the z axis but distorting it incorrectly if its angle is changed.

### To Reproduce

Below is the link to a simple quad that will align its normal with your view, and can be used to easily see the offset happening with its refraction material set to additive (setting the material to its normal opaque mode still has the offset, but makes it harder to visualize). Simply look through this quad facing the z+ direction of the world and start walking around it to see the distortion grow stronger the closer you are to looking in the y and/or x directions:
`resrec:///U-Joliair/R-72f9509d-b6c9-46d6-bcb1-a35cbdbfdd90`

Here is a more complex example of this with a UI and camera that lets you see the refraction effect from different and precise angles, making it pretty easy to see how the refraction effect is correct on the z-axis but has distortions when viewed from the y or x axis:
`resrec:///U-Joliair/R-1c3d4a7c-5046-4e77-8ad1-11c0632ad36c`

### Expected behavior

No view offset should be produced when looking through the refraction filter on a quad that is perfectly aligned to your view. And when the quad isn't aligned to your view, it should appropriately apply the offset depending on the angle that you're viewing the object, regardless of whether the face's normal is aligned with the z axis or not.

### Screenshots

(The following screenshot uses the normal refraction material on a quad that aligns itself with your view)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40308883/0f6f0e0b-192d-44d9-aeb0-771bae51de56)

(Note that in the images provided below the refraction material was set to be additive to make it easier to see the offset clearer)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40308883/ad6127a6-97c2-4c75-ad01-c0f919db6769)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40308883/50583217-db40-4234-90d8-e82ee3b483cf)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40308883/edf63b43-9abd-48be-9282-19692618c552)

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index & Desktop

### Log Files

[2023.10.13.743 - 2023-10-14 12_40_13.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12906846/2023.10.13.743.-.2023-10-14.12_40_13.log)

### Reporters

Joliair

**Comment by Geenz** [comment]
The offset is generally expected based upon the supplied refraction strength which defaults to 0.05.  Even for seemingly "flat" quads.  What usecase do you have for the quad to be completely non-refractive in a default state of 0.05?

**Comment by SpaceAnon** [comment]
This is a little tough to explain without showing it in-game (which I am willing to demonstrate in-game if it helps), but to my knowledge, if the quad surface is perfectly perpendicular to your view, there should not be a refractive effect.
Also, for my specific use-case I use it for a black hole/white hole gravity lensing effect.

This is the effect that it is supposed to have:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40308883/d90f3179-2250-4974-8712-2fbf4be2540d)

But this is what happens when you're not looking at it perfectly in the world's z-axis:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40308883/05e8a5b2-e4d5-4089-922b-43c51ddfdf76)

To me this seems like the refract effect isn't taking into account either the surface angle or player's view angle. (I will also note that this worked perfectly fine before in the old game)

**Comment by Geenz** [comment]
Oh! I see then. I’ll take a look at this for Shader Update 1 then.

**Comment by Geenz** [comment]
Bumping this out - using an earlier version of the shader it exhibits the same behavior (at least in my dev environment).  And by early, I mean _eeeeeeaaaaarly_.  This may be a good candidate to look at for either SU2 or consolidation.

**Comment by SpaceAnon** [comment]
As one thing that may or may not help as well, I will note that this worked perfectly fine before migration, but I'm not too sure how much that information will help.

**Comment by SpaceAnon** [comment]
Not too sure if this was intentional or not since it wasn't in the patch notes, but the latest update that was released earlier today seems to have ended up fixing this bug, allowing the refract shader to work properly once again! Thanks for all your hard work!
