### ISSUE TITLE
Massive crash

### ISSUE THREAD

**Issue by Drafy07** [Yellow-Dog-Man/Resonite-Issues#1722]
### Describe the bug?

resonite chugs hard , 2-5 minutes afteer launch it crashes since the new update.

### To Reproduce

run an oculus cv1 trought steamvr in vr, launch the latest version and join a session , games will chug to hard trying to load anything resulting in the oculus dash crashing , steamvr will follow and resonite too.

### Expected behavior

no crash plz .w. idk

### Resonite Version Number

2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus cv1 (the first one)

### Log Files

[DESKTOP-VUULJ39 - 2024.4.15.1407 - 2024-04-16 07_02_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15000801/DESKTOP-VUULJ39.-.2024.4.15.1407.-.2024-04-16.07_02_35.log)

**Comment by Drafy07** [comment]
huh wierd , i swore it was up to date , my bad and sure i can try getting more logs , where do i get the "normal logs" and "playerlogs" ?

**Comment by Drafy07** [comment]
here the Player log files 16/04/2024 , last time i launched resonite.

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15016139/Player.log)

and the crash report.

[crash.dmp](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15016150/crash.dmp)
[error.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15016151/error.log)
[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15016152/Player.log)

**Comment by Drafy07** [comment]
im not sure how to even launch the game without the cloudhome , after checkin the log it might just be an issue with the session i was trying to join , the video player mostly

**Comment by ultrawidegamer** [comment]
@Drafy07 you can skip loading your home by adding -DoNotAutoLoadHome to the launch options of your game

**Comment by Drafy07** [comment]
nope still happening after trying again today

**Comment by Drafy07** [comment]
legit , only resonite do this , get the vr compositor stuck to run at 99% and make my computer cought its lungs too  even after the game have crashed forever until i kill it

**Comment by Drafy07** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/50578765/161b423e-a4c0-48ab-99ea-0485df5535a6)
so here a screenshot of the oculus dash crashing 

this is a fresh install , completely clear cache and people where messing around with logics while a video player was playing music in the background
