### ISSUE TITLE
Unable to open large/heavy worlds after Setting UI Update (ArgumentNullException)

### ISSUE THREAD

**Issue by AmasterAmaster** [Yellow-Dog-Man/Resonite-Issues#1723]
### Describe the bug?

When trying to open my dev world, after a long time it fails to open. Normally it waits a long time and opens the world just fine. I am guessing it may be due to all the slots that it needs to prepare (as the world is quite heavy), but it also was a non-issue as it was working before the latest update. However it is possible something may have messed up in the process during the Settings UI update as now I am unable to open the world.

It was also brought up to me that something is either setting to null or is already null, which could also be preventing the world from being opened. Check lines 1665 to 1685 in the provided log file.

### To Reproduce

It may be impossible now to reproduce unless you have a time machine to make a world before the update and try to open one now. But here are the steps needed:
 - Make a world before the latest update, make a lot of slots to the point where the world is heavy enough to take a significant amount of time to load (5-8 min to load a world should be fine enough).
 - Update to the latest build of Resonite
 - Try to open the world (and wait that amount of time). If it fails, great, that is where I am stuck at.

### Expected behavior

I should just be able to create a new session of the world and wait for things to load in as it opens normally and successfully, just like before the update.

### Screenshots

Here is the world loading indicator when it freezes Resonite (letting me know that the world is opening and loading in the assets and other things)
![Dev World Crashed 01](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8411427/8e941218-2c18-41a4-bed7-c8e1fa8354c1)

Here is the world indicator when it lets me know of the world failing to open. (Giving me "World Crashed - Unhandled exception in updating the world")
![Dev World Crashed 02](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8411427/282af1d0-9ab1-4dc9-81c5-26215dfc86a8)

### Resonite Version Number

Beta 2024.4.15.1407

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index & Desktop

### Log Files

I will also attach a log to see if that can help as well, there is a possible null exception preventing the world from opening.
[ANDREW-SUPERPC - 2024.4.15.1407 - 2024-04-16 13_37_25.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15001325/ANDREW-SUPERPC.-.2024.4.15.1407.-.2024-04-16.13_37_25.log)

### Additional Context

The world in question that cannot be opened by me (maybe it can be opened by others, that I am unsure of)
resrec:///U-AmasterAmaster/R-f0e9a6c0-281b-4c94-9ad3-56a901454dce

I will also reference this other GitHub Issue as well as it may relate to this issue. Their issue relates more to the headless not being able to access worlds after the update, but they can easily move that to a separate container. As with my issue, I cant or un-knowledgeable enough to see if I can migrate or move or salvage anything in this world to another (if that is even a thing you can do here in Resonite).
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1710

### Reporters

AmasterAmaster
j4.lc

**Comment by Frooxius** [comment]
This is same issue as here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1710

Closing this one, I've got a fix incoming.
