### ISSUE TITLE
Separate  "Primary Hand" option into two settings: Primary Tool Hand and Primary Movement Hand

### ISSUE THREAD

**Issue by TisFoolish** [Yellow-Dog-Man/Resonite-Issues#1732]
### Is your feature request related to a problem? Please describe.

[I originally requested this in the discussion about the new settings menu in regards to new settings](https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/614#discussioncomment-7537077), but figure now that the new settings is out it'd be a good idea to create a formal feature request for this. I'll be copy-pasting my text

As a lefty it's endlessly frustrating to see tons of VR games conflate me wanting to set which hand I want to hold or equip things to as also the hand I want to primarily move with. Every other lefty I've talked with has felt the same.

People make tools that will auto equip to the primary hand, which as a left handed person who has limited mobility of my right side, is very annoying. Sure, I could just set my primary hand to left, but that also changes the way movement works and my right hand and thumb just doesn't have the dexterity for that. Right now when I make tools with myself in mind I have to hard code it for the left hand instead of using the node User Primary Hand to get a preferred side.

### Describe the solution you'd like

Split the Primary Hand setting into Primary Tool Hand and Primary Movement Hand

### Describe alternatives you've considered

Unequipping and then re equipping tools to my left side as well as hard coding tools I build for my left side.  

### Requesters

foolishsnowmew on Discord
hammywhamster on Discord

**Comment by Frooxius** [comment]
I don't understand what do you mean by this separation? How would this actually work? What would the hands do?

When you don't have anything equipped, both hands can be used for movement. 

If you have something equipped that hand can't be used for movement if it uses the inputs for its own.

**Comment by epicEaston197** [comment]
From what I could parse they want an option to make it so if a tool would have been equipped in the left hand (primary hand) it would instead be equipped to the right hand instead because their right hand doesn't have a lot of mobility

**Comment by JackTheFoxOtter** [comment]
> People make tools that will auto equip to the primary hand, which as a left handed person who has limited mobility of my right side, is very annoying. Sure, I could just set my primary hand to left, but that also changes the way movement works and my right hand and thumb just doesn't have the dexterity for that. Right now when I make tools with myself in mind I have to hard code it for the left hand instead of using the node User Primary Hand to get a preferred side.

When you equip a tool from ProtoFlux, you have to specify a chirality for which hand to use. Currently, the way most implementations do this is by querying `UserPrimaryHand`. This sounds like a request for a second node, something like `UserPrimaryToolHand`, which can be queried seperately by people creating tool systems.

That said, what is currently the issue with setting the primary hand to be your left hand? The actual underlying problem I see here is that controls are coupled to your primary hand choice. You should be able to set your primary hand to left, and have the ability to configure movement controls independantly from that. Tools shouldn't have to be considered here, they should just always use your primary hand.

**Comment by 5H4D0W-X** [comment]
The settings update added new configuration options for what each hands does when moving (strafe/turn/off per hand). What exactly is it that you can't do at the moment?

**Comment by 5H4D0W-X** [comment]
Since the settings update introduced per-hand movement options, I think there should be a `get hand movement mode` node that takes a user and chirality input and returns an enum value for turn/strafe/off. Tools could use this to tailor their interactions not only to different primary and movement hand options, but also to disabled movement on one hand etc.

**Comment by TisFoolish** [comment]
I had mods enabled and 1 or a combination of them had not been updated and somehow nuked the controls section for me, so I actually did not have the controller config options. Disabling my mods shows the options.  These options are actually more than enough for what I want.
