### ISSUE TITLE
Steam / Discord Rich Presence settings

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1738]
### Is your feature request related to a problem? Please describe.

Currently if Steam/Discord is present, Resonite will send rich presence status to these. There is no way to disable these.

### Describe the solution you'd like

Add privacy settings which allow disabling/controlling the rich presence integration. 

### Describe alternatives you've considered

N/A

**Comment by ProbablePrime** [comment]
Added in: 2024.5.7.505
