### ISSUE TITLE
Reflection Material broke when get any "Normal Map" texture

### ISSUE THREAD

**Issue by maksim789456** [Yellow-Dog-Man/Resonite-Issues#174]
### Describe the bug?

Reflection Material broke when get any NormalMap texture

### To Reproduce

- Spawn "Reflection" material
- Get some normal map picture ([example](https://docs.unity3d.com/uploads/Main/BumpMapTexturePreview.png))
- Place normal map picture in "NormalMap" at material

### Expected behavior

Like at Neos, setting "NormalMap" without texture don't broke the material
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8225008/63808d7d-e554-4950-bbc4-f2b29adf771e)

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8225008/6c612f7b-41ea-4e34-84e8-d58c9d8ba7f3)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### Reporters

U-maksim789456

**Comment by kulzae** [comment]
resrec:///U-Kulza/R-CC846284D49298BDB1F928B06F927146764A0AD1C8E53959BDA33B289E9EE69D can be found in this folder as the item with the issue number

**Comment by Geenz** [comment]
Likely related to #200 and #1117

**Comment by Geenz** [comment]
This is fixed for the next shader update.
