### ISSUE TITLE
Make Resonite logo hue slowly in loading screen

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1741]
### Is your feature request related to a problem? Please describe.

I feel like the logo is a little static

### Describe the solution you'd like

I would like the Resonite logo to slowly hue in the loading screen I feel like it would be a nice touch it would make it feel a bit more animated

### Describe alternatives you've considered

None maybe a mod

### Requesters

@epicEaston197

**Comment by JackTheFoxOtter** [comment]
I assume you mean hue shift?
Also just a reminder, you can also favorite a custom loading indicator if you want to change yours.

**Comment by epicEaston197** [comment]
> I assume you mean hue shift? Also just a reminder, you can also favorite a custom loading indicator if you want to change yours.
Yes
And No the one you see when you open the game

**Comment by JackTheFoxOtter** [comment]
Ah. You probably don't want to animate that one, that would make the loading stutter appear worse is my bet.

**Comment by epicEaston197** [comment]
Yeah I thought it would be a cute little edition but I suppose you're correct
