### ISSUE TITLE
Add support for the GigglePuck

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1751]
### Is your feature request related to a problem? Please describe.

This just arrived:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/105e4162-f096-4703-844a-a60b77bf2216)

### Describe the solution you'd like

Implement native support for GigglePuck in Resonite with the existing haptic feedback system. This will include a setting in the new settings UI to determine where to map the GigglePuck.

### Describe alternatives you've considered

Integrating it through WebSocket, but this would make it harder to take advantage of Resonite's system.

### Additional Context

The package came with two TimTams. I ate them and now I'm sad, because I have no more TimTams:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/f4ecc360-e543-4e23-a871-505048ac4d45)

### Requesters

Me

**Comment by Nytra** [comment]
important

**Comment by RyuviTheViali** [comment]
I figured I'd link this here, but GiggleTech has some repositories on GitHub which could serve as a basis on how to connect and use their devices: https://github.com/giggletech

**Comment by Frooxius** [comment]
This is now implemented in 2024.4.24.1426! Unfortunately this doesn't include more TimTams, but you can get headpats now.
