### ISSUE TITLE
Cuteness settings is shown

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#1756]
### Describe the bug?

When going into the settings, then "Profile", the `Settings.CutenessSettings` is shown.  

According to the wiki, [this setting is only supposed to show up for U-GlitchFur](https://wiki.resonite.com/Component:CutenessSettings).

### To Reproduce

1. Open game
2. Go to settings, then "Profile"
3. Observe that `Settings.CutenessSettings` is there

### Expected behavior

This setting should not be visible for me.

### Screenshots

![Resonite_9dLxSNTxd9](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/5e24ea7c-f1be-4abb-9043-27b796cc4abd)

### Resonite Version Number

Beta 2024.4.17.1420

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index; Desktop

### Log Files

[TETHYS - 2024.4.17.1420 - 2024-04-18 20_58_42.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15028702/TETHYS.-.2024.4.17.1420.-.2024-04-18.20_58_42.log)

### Additional Context

I am not cute.

If the setting is here by design, the detection should be improved.

### Reporters

U-j4 | j4.lc (Discord)

**Comment by jae1911** [comment]
> Did you at any point interact with/spawn out that linked component

I might have attached it to an empty object after seeing it being added to the wiki.

> Do you have any idea when or how the setting appeared for you?

I definitely noticed it yesterday night before going to bed (see in the [wiki channel of the Discord](https://discord.com/channels/1040316820650991766/1154514026177507438/1230317224976191569)).

**Comment by PointerOffset** [comment]
I'd like to add that I've experienced something similar myself when attempting to make my own facet using  `Settings.AudioStreamSettings`. I had discovered these settings existed and wanted to build a custom setting facet for myself. Half-way through trying to do so, I noticed these settings appeared in my User Interface settings tab. I asked others and nobody else seems to have these settings visible.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/61102129/58a23ac3-3e2f-4a37-9780-1a27c7e3bdbd)

I suspect the fact that I tried to access the settings caused them to be generated in the settings menu when they normally would not be. Unfortunately I don't have a log on-hand or for-sure way to replicate this. This is now a permanent part of my settings list.

However someone can attempt to replicate this by:
- Creating an EmptyObject
- Attach a `SettingValueSync<T,S>` component to it. T= `float`, S = `AudioStreamSettings`.
- Populate the `Setting` string field with `DefaultBitrate`
- Populate the `User` field with a reference to your own user.

Example:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/61102129/c90a591f-bca5-4731-9681-d1b6be1486e9)

This may not be all of the replication steps but I suspect this will get someone halfway there. Apologies I don't have something more concrete.

**Comment by Frooxius** [comment]
The new setting system is dynamic, so settings are only registered when something requests them. 

If you played with components and made ones that will request this setting - it will be added as a result - this isn't really a bug, the system is just doing what you requested it to do so.

I'll see if I can add a cleanup code for it.

**Comment by Frooxius** [comment]
Should be fixed in 2024.4.18.1398! I've added the cleanup for anyone how's not Glitch.
