### ISSUE TITLE
Add option for stereo separation on quick photo capture settings

### ISSUE THREAD

**Issue by paradoxical-autumn** [Yellow-Dog-Man/Resonite-Issues#1759]
### Is your feature request related to a problem? Please describe.

Currently, the `Quick Photo Capture` settings has an option to capture stereo photos but no option to set the stereo separation. I've found that the default separation set here hurts my eyes.
*(It also seems a bit random right now? Some times when I capture the photo, it's fine, other times it's a literal pain to look at.)*

### Describe the solution you'd like

A slider value allowing for a custom stereo separation to be set for quick photos. This could be added to the `PhotoCaptureSettings` component.

### Describe alternatives you've considered

- Manually changing this on the photo capture manager on the avatar
- ~~Reference hacking to the photo capture manager on the avatar and then to the stereo separation field~~

### Requesters

paradoxical_autumn (Discord username) // paradox19 (IGN)

**Comment by paradoxical-autumn** [comment]
I completely forgot to add an example of the "absurd" options.

I enabled "Capture stereo photo" and took a picture of a computer right in front of me in this example. Everyone with VR in the session complained that this is too much separation
![2024-04-18 22 13 42](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/110392755/ee5e069b-70ed-4b8d-ad13-d32ffb19e8e1)

**Comment by lxw404** [comment]
Stereo separation is just one factor to this.  The bigger problem with the stereo pictures taken by the default camera is that the focal point is at infinity (both cameras for the left and right eyes are not converging to a point).  This can, and has caused a lot of strain in viewing such photos, since in real life your eyes are always trying to focus on individual objects, not everything at once.

When you view objects in 3D, your eyes actually rotate and converge towards a single focal point which corresponds to rotating the individual 2 stereo cameras in the same way.  There really should be an additional option for a convergence point with toggle which can be set by either a laser projecting into the scene and hitting an object, or by specifying an actual position/slot.

**Comment by Frooxius** [comment]
We can add setting for this.

I'd just like to note that currently the separation is 65 mm, which is around the average distance between people's eyes.

**Comment by paradoxical-autumn** [comment]
Thank you!

Are you also going to try and fix how the distance is currently used in local space rather than global space, causing it to be affected by avatar scale?

**Comment by Frooxius** [comment]
Added in 2024.4.24.33, thanks!

**Comment by shadowpanther** [comment]
@Frooxius the default value in the Settings is 6.50mm, is this correct?

The average IPD is about 6.5cm (65mm), ten times as much.

**Comment by paradoxical-autumn** [comment]
> @/Frooxius the default value in the Settings is 6.50mm, is this correct?
> 
> The average IPD is about 6.5cm (65mm), ten times as much.

@shadowpanther
froox misspoke, the in game value is 65mm iirc

**Comment by Banane9** [comment]
Just loaded up the game to check, and the default is indeed `6.50 mm` - which as @shadowpanther points out is about a tenth of what it should be for the human average.

![Screenshot of the Quick Photo Captures settings, showing a default of 6.5mm IPD](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/4f40f2e2-155f-46c6-b9d6-d0ffd8320fbf)

Here's a quick overview on some averages: https://www.researchgate.net/figure/Mean-interpupillary-distance-mm-values-in-various-age-groups_tbl2_281069573

**Comment by shadowpanther** [comment]
> > @/Frooxius the default value in the Settings is 6.50mm, is this correct?
> > The average IPD is about 6.5cm (65mm), ten times as much.
> 
> @shadowpanther froox misspoke, the in game value is 65mm iirc

I never changed the value in my settings, and it's 6.5mm for me.

I can't take finger photos (quest controllers via steam link and steamvr), so can't confirm if that's the settings display issue or the setting value issue.

**Comment by Frooxius** [comment]
Ooop, yeah, that's supposed to be 65 mm

**Comment by Frooxius** [comment]
Ok it's fixed. If you already saved your settings you'll need to update this manually though.
