### ISSUE TITLE
Text Indicators in the Settings don't scale to fit larger text

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Resonite-Issues#1763]
### Describe the bug?

See title. When there's long texts, the (String) indicators don't increase in height to fit all of the text, making it overlap with other items.

### To Reproduce

The easiest would likely be creating a Protoflux setup that requests host access with a very long string, as it's currently the only UGC in the settings that I know of.

### Expected behavior

The indicator should scale to accomodate the text without clipping.

### Screenshots

Screenshot from my mod loader settings, but you get the point (and it may still be relevant for other cases, such as host access or future options)

![Overlapping description texts on the text indicators](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/556c80d6-d046-473d-bbf8-c618960b2d43)

### Additional Context

I get if this is likely going to be low priority, but it would still be nice to have 👍 

### Reporters

Banane9

**Comment by RyuviTheViali** [comment]
I've set the indicators to allow larger bodies of text to be shown properly - this is something that'd need to be done anyways since i.e. for some host access reasons, the text for that reason could be long. Closing this, thanks!

**Comment by Banane9** [comment]
Thanks! 💙
