### ISSUE TITLE
Remember settings of muting voice mode, and default mute option

### ISSUE THREAD

**Issue by akiRAM2** [Yellow-Dog-Man/Resonite-Issues#1767]
### Is your feature request related to a problem? Please describe.

Currently, Resonite starts up with the voice mode On (Normal voice mode).
For those who prefer to always be on mute, this requires them to change the settings every time, which can occasionally lead to unintended of sound transmission.

### Describe the solution you'd like

Make the application remember the voice mode setting upon exit.
And add an option 'Start with mute mode' in the settings menu.

### Describe alternatives you've considered

Change voice mode manually everytime on startup.
Or, adding a mod below:
https://github.com/FalsePattern/DefaultVoiceMode/releases/tag/2.0.0

### Requesters

akiram_

**Comment by Frooxius** [comment]
Added this in 2024.4.22.1366, thanks!
