### ISSUE TITLE
Configurable deadzone for exclusive joystick mode

### ISSUE THREAD

**Issue by Trotim** [Yellow-Dog-Man/Resonite-Issues#1769]
### Is your feature request related to a problem? Please describe.

I am used to VR movement using the left joystick for only strafing, and the right joystick for only turning. This is afaik a common control scheme.
As of Resonite 2024.4.18.1398, I am unable to set this up via the built-in Controls settings.
Enabling exclusive turn mode doesn't help: trying to press left/right can easily register as up/down and thus move instead of turning. (I couldn't find a way to change the deadzone of that.)
I understand some equipment overrides movement, and it can be useful to have Strafe and Turn on one joystick, but I'd still prefer this for my regular walk mode without equipment

### Describe the solution you'd like

Add an option to disable strafing on a joystick?

### Describe alternatives you've considered

Make the differentiation between "I want to turn" and "I want to strafe" more generous in exclusive turn mode?

### Additional Context

Right is set as my dominant hand and I primarily use the Walk and Fly modes

### Requesters

[Trotim](https://github.com/Trotim)

**Comment by Frooxius** [comment]
I'm actually not sure if I fully understand this issue. 

You're asking that one joystick is used for strafing (sideways motion), while other is used for turning. This should already be possible with the current settings:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/260801af-9eed-4c89-8aff-c0a8fadd3d02)

You can also set the joysticks to "Off" which means that it will only be used for forward/backward movement.

What about this is missing in particular? Or something I'm not understanding right?

**Comment by Trotim** [comment]
To be clear what I want is what I'm used to from other VR games:
Left stick moves position only (forward and backward and strafing sideways and everything inbetween). Never turns
Right stick turns only. Never moves position (no strafing, not forward or backward either)

What I can't find is an option to set a joystick to only turn. Setting a joystick to only move is easy, yes.

Exclusive mode sounded like a fine compromise: "I'll just use right stick to turn and ignore that it can move me forward and backward."
But that doesn't work out in gameplay since many times when I try to use the right stick to turn, I must be pushing it just slightly up or down, and start moving instead. (And even on successful turns, I noticed a tiny jolt of movement on completion)

**Comment by Frooxius** [comment]
Should be addressed in 2024.5.30.68 now! Thanks!
