### ISSUE TITLE
Implement Setting UI template for Int sliders

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1775]
### Describe the bug?

In recent update I've added Per Pixel Lights setting, which is represented by an integer with a range, which normally generates a slider.

Currently we only have template for float sliders, so this falls back to generic input template.

### To Reproduce

Go to Settings -> Graphics -> Rendering Quality

### Expected behavior

Create a template for slider with `int` type.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/8a15b589-4e5e-49ee-afaa-e50774b25453)

**Comment by RyuviTheViali** [comment]
I've created the int slider template and updated the settings facet template. Thanks! 

![20240419151231_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/93283122-ec93-419e-84f0-7c41fc5a7cf2)
