### ISSUE TITLE
Resonite API Hidden Session 404

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#1780]
### Describe the bug?

When trying to call the session part of the Resonite API you will get a 404 if a public session is listed as hidden

### To Reproduce

open a public session
get session id
make a call to the sessions resonite API https://api.resonite.com/sessions/{sessionId}
see that you will get a 200 response
switch to the public session to hidden
make the same call to the session API
see that you will get a 404

### Expected behavior

public session API calls that are hidden should return a 200 with value of hideFromListing displaying as true

### Screenshots

![2024-04-13 04 04 21](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/cd0b229d-21ae-470a-8f94-c3a432a5adc6)
![2024-04-13 04 04 51](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/423a5198-4f82-48c9-8945-2b802c28a828)

### Resonite Version Number

N/A

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

N/A

### Reporters

ultrawidegamer

**Comment by ohzee00** [comment]
I'm confused, is this not expected behavior? Hidden means it doesn't report its status to the API at all, hence it being hidden.

**Comment by ultrawidegamer** [comment]
the difference is that it is also a public session, if this is expected behavior it should at least not have a value in the data showing hideFromListing because you would never be able to use it in a true scenario

**Comment by Frooxius** [comment]
This is expected behavior. Hiding a session stops sending data to the public API.

**Comment by ultrawidegamer** [comment]
@shiftyscales yes this is a session that i am able to join if i have the session url and join via protoflux

**Comment by ultrawidegamer** [comment]
so then the hideFromListing value is not usable because it will only be there in false scenarios

**Comment by ultrawidegamer** [comment]
i am trying to create a custom session opener that needs to ping the API periodically to see if the session is still opened

**Comment by badhaloninja** [comment]
> i am trying to create a custom session opener that needs to ping the API periodically to see if the session is still opened and some of the world orbs that im using open as hidden by default

You should be able to use the FocusedWorldStatus and/or SessionInfoSource components

FocusedWorldStatus only shows info on the current focused world and it only works if it is in the userspace (ie on a facet)

SessionInfoSource lets you check a session id, and if you should be able to see info on that session, it should show it


Also the World List facet is surprisingly customizable

**Comment by ultrawidegamer** [comment]
@badhaloninja I just tested it and SessionInfoSource also does not show information when the world in public but hidden

**Comment by badhaloninja** [comment]
> @badhaloninja I just tested it and SessionInfoSource also does not show information when the world in public but hidden

Are you hosting or are you in the session (in the background) that you are checking?

Because I think that's the only time your account would be allowed to read the status.

If you are and it's still not working then something is wrong somewhere 



If you want to read session info for hidden worlds you are not in then I'm pretty sure it's just not allowed and I misunderstood what your end goal was

**Comment by ultrawidegamer** [comment]
@badhaloninja 

My goal is to determine if the world session URL is still active for a public hidden session, even if I'm not the host and not currently in the session. (In my previous scenario where it didn't work, I was the host but not focused on the world)

In this scenario, I think I'll have to request it as a feature in another ticket, as it seems it's currently not possible

**Comment by Frooxius** [comment]
Hidden session means that the session is hidden from any public data listing. That means its status is hidden to you, unless you're within the session or explicitly provided the data by the host. 

As a result, you cannot determine if the session is active or not, because that data is hidden from you - that is the purpose of hidden sessions.

It's not something we'd allow, since it would effectively make the session not be hidden.
