### ISSUE TITLE
Pause Protoflux State

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#1783]
### Is your feature request related to a problem? Please describe.

currently if debugging large or complex code it is sometimes very difficult to determine the solution to some coding bugs

### Describe the solution you'd like

I would like to have a node that can be used similar to the C#/JS debugger keyword where the code execution is paused and you can look at the active state of the code and then resume the code

### Describe alternatives you've considered

continue to attempt debugging very complex bugs without much insight

### Requesters

ultrawidegamer

**Comment by Nytra** [comment]
Might be covered by https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1122

**Comment by ultrawidegamer** [comment]
@Nytra Oh i didnt find this issue when searching before creating. Yes, I think you would be correct that this would be covered in #1122
