### ISSUE TITLE
Background Frame Rate Limit Setting

### ISSUE THREAD

**Issue by kulzae** [Yellow-Dog-Man/Resonite-Issues#1784]
### Is your feature request related to a problem? Please describe.

Currently when creating content i typically run the game in desktop mode in the background as I create assets then swap to the game to upload them. Currently the game will attempt to run at its max frame rate when backgrounded using additional computer resources and creating heat.

### Describe the solution you'd like

I would like a setting to set the frame rate when the game is in desktop mode and the window is unfocused. This could be in set intervals or as a custom number

### Describe alternatives you've considered

Limiting the background framerate using NVIDA control panel. but this has the side effect of affecting vr mode as well causing my vr framerate to be limited if im not specifically clicked on the window. It also does not work unless the window is pulled away from the edges of the screen for whatever reason

### Additional Context

related to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1052

**Comment by Frooxius** [comment]
I've looked at the both issues and I'm actually not sure how does this differ from https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1052 ? 

It seems both are asking for ability to limit the framerate when Resonite is not focused (e.g. minimized). 

I can just add that, but I don't understand what the difference between these two issues is.

**Comment by ohzee00** [comment]
I'm not the creator of either of these issues but #1052 seems to be a general frame limiting setting, that confusingly refers to framelimiting when not in focus as a usecase for the feature, while this one directly asks for a framelimiter _when_ it is unfocused. 

So I imagine adding a setting that allows you to override the framerate when it isn't focused (in desktop mode) would partly solve the underlying problems these issues want to solve. However #1052 wants a way to generally limit the game's framerate even when focused.

(I reread the issue like three times and got myself confused too honestly)

**Comment by ultrawidegamer** [comment]
@Frooxius these 2 issues seem to be more of a foreground and background frame limiter with separate settings. With these settings for example you can play an idle game on the side while you have Resonite focused or you could have Resonite on the side while you are focused and working in blender. 

Another use case for focused frame limiter would be using the steam application "VirtualHandheld" which allows you in VR to have a virtual steam deck like device so you can play other games while socializing in VR

**Comment by Frooxius** [comment]
@ohzee00 That's what I thought too, but the other issue mentions limiting while Resonite is not active window either, which is why I'm really confused.

@ultrawidegamer That's what this is both about though. So the framerate lowers while you're using another app.

This has nothing to do with VR. We cannot limit framerate while you're in VR.

**Comment by Frooxius** [comment]
Added in 2024.5.3.467, thanks!
