### ISSUE TITLE
Swizzle Drivers not working as intended.

### ISSUE THREAD

**Issue by Dartkitten** [Yellow-Dog-Man/Resonite-Issues#179]
### Describe the bug?

When utilizing Swizzle drivers (In this case, Float4ToColorXSwizzleDriver) the X Y Z and W values are all Ints instead of floats

### To Reproduce

Attempt to drive the X value of the Relations>Swizzle Drivers>Float4ToColorXSwizzleDriver 

### Expected behavior

the X Y Z and W values would be expected to be floats instead of integers.

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

**Comment by ProbablePrime** [comment]
@Dartkitten Is this ALL swizzle or just the reported ones? Please update your issue to reference a list of problematic swizzles.
