### ISSUE TITLE
Youtube Videos Do not play

### ISSUE THREAD

**Issue by Electronus** [Yellow-Dog-Man/Resonite-Issues#1791]
### Describe the bug?

You tube videos seem to have stopped working for me, even through Resonite up dates and updating YoutubeDL itself. 

 

### To Reproduce

Import a youtube video.

It never loads the Video

### Expected behavior

The youtube video should load and be playable. 

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/64871170/9d957254-39dd-4c9a-80ee-f22e20f33fbc)

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/64871170/78130aac-62a3-4a3e-92d9-c8f2cf1eba47)

### Resonite Version Number

Beta 2024.4.18.1398

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index, Desktop

### Log Files

[ELECTRONUS-PC - 2024.4.18.1398 - 2024-04-20 11_07_50.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15049147/ELECTRONUS-PC.-.2024.4.18.1398.-.2024-04-20.11_07_50.log)

### Additional Context

I have not seen anyone else with this issue.

### Reporters

Electronus

**Comment by Electronus** [comment]
So there is a discord thread where a few of us tried to figure this out. 

verifying game files didn't work.
Updating Youtube DL didn't work. 
reinstalling didn't work. 
A new database and cache didn't work. 
A different video player didn't work. 
A different link format didn't work. 
As far as we can tell my copy of youtube DL is fine and works, I can even use the command line to download videos.

**Comment by Nytra** [comment]
Could you check if your PATH environment variable contains any illegal path characters?

**Comment by Electronus** [comment]
I would not know how to do that.

**Comment by paradoxical-autumn** [comment]
Could you please verify that your yt-dlp works fine from the command line, so we can verify it is actually a resonite issue?

_(Basically, locate the file in your game's directory and then run `yt-dlp link` where `link` is a YouTube link)_

**Comment by Electronus** [comment]
As far as we can tell there is nothing wrong with my PATH variables.

**Comment by Electronus** [comment]
As i noted in the "Additional Context" section, I don't know of anyone else having this issue. 

But everything points to either Resonite or there being something wrong with my system Resonite doesn't like for some reason, Resonite is the only program to have issues, even yt-dlp itself works.

**Comment by Electronus** [comment]
So Sveken helped test and it seems that videos (.mp4s at least) on other websites work fine, so it still seems to be something with reso and yt-dlp.

**Comment by Banane9** [comment]
Interesting - I've had the same symptoms with .mp4 videos from a German image board website when @phil-flip posted them - whether as links or as directly imported files. YouTube videos play fine though.

**Comment by Chundelac** [comment]
I have worked with [Electronus](https://github.com/Electronus) to resolve this.
The problem was with a newline character as an entry in the environment variable path, removing it fixed the issue.

**Comment by Chundelac** [comment]
I have create issues #2496 and #2497 that better describe the underlying issues and Electronus no longer has this issue.
As such feel free to mark this as closed/resolved.

**Comment by Electronus** [comment]
Thanks again for the fix @Chundelac!
