### ISSUE TITLE
[settings] add legacy inventory gesture setting

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#1796]
### Is your feature request related to a problem? Please describe.

There is a gesture where if you hold the left grab and press any dash menu button it will open the legacy inventory. I find this gesture gets in my way more than it is useful, because for example when I'm climbing on a world or holding an item and want to open my dash menu, I cannot because it will only open the legacy inventory.

### Describe the solution you'd like

A setting that disables this gesture.

### Describe alternatives you've considered

using a mod https://github.com/art0007i/disablelegacyinventory

### Additional Context

There is another way to open the legacy inventory: pressing ctrl+i which means that even without the gesture it's possible to open the inventory using a facet with a VirtualMultiKey set to ctrl+i. I find this solution to be way nicer than a gesture that I click accidentally all the time.

**Comment by Frooxius** [comment]
Added this in 2024.5.28.94, since I was touching a bunch of the code with the facet anchors and this was easy enough. Thanks!
