### ISSUE TITLE
RenderValueOverride

### ISSUE THREAD

**Issue by ImErinTheBunny** [Yellow-Dog-Man/Resonite-Issues#1798]
### Is your feature request related to a problem? Please describe.

I have a UIX canvas with one element that needs to be shown to a user but not to the camera if they happen to be streaming.

### Describe the solution you'd like

I would like a component with a datatype that works the same way as RenderTransformOverride and RenderMaterialOverride where it will override the data value of the target you specify. 

I would use this to disable the slot active bool on the UIX component for the camera.

### Describe alternatives you've considered

RenderTransformOverride and RenderMaterialOverride.

RenderTransformOverride will not effect UIX and I can't use another material on that element for RenderMaterialOverride.

### Additional Context

This would also be great for changing string values for stream cameras to hide information :)

### Requesters

imerin.

**Comment by Frooxius** [comment]
Unfortunately this is not really possible to implement. 

Render overrides can only override "simple" states that are more or less the late state of what's being rendered. 

Overriding arbitrary values can have very complex state changes - e.g. this would require whole UIX canvas computation and recalculation, which is a complex multi-threaded process. Such complex updates cannot be performed in the rendering phase.

Your option is to have two canvases - one that is stream safe and one that isn't and then use the RenderTransformOverride to hide them appropriately - this is really the simplest way to achieve something like this.
