### ISSUE TITLE
Writing Haptic Sampler output to dynamic variable crashes world

### ISSUE THREAD

**Issue by marsmaantje** [Yellow-Dog-Man/Resonite-Issues#18]
### Describe the bug?

When you try to write the output from an OnCollisionStart node hooked onto a HapticSampler collider to a dynamic variable it crashes the user when it collides with another user. This only happens when the user is in VR.

### To Reproduce

1. Be in a world in VR with at least one other person
2. Spawn reproduction item
3. Have the user in VR grab the item and touch the other person with it
4. Observe

Reproduction item link:
resrec:///U-marsmaantje/R-bdba5462-735b-4e37-bbf9-d4e15d9605ea

### Expected behavior

The dynamic variable gets written correctly and no one crashes.

### Screenshots

![Resonite physics crash ticket](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/60362806/7d4723b7-908d-41fe-9454-eeeca5432ade)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[DESKTOP-K2H0L1O - 2023.10.6.1038 - 2023-10-07 18_05_04.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12899670/DESKTOP-K2H0L1O.-.2023.10.6.1038.-.2023-10-07.18_05_04.log)

### Additional Context

The Black Mesa tram ride and Deep Dreams suffer from this issue.
Though, we have recently pushed a workaround to the tram ride, temporarily circumventing the issue

(the log is from an older version, but it still happens on the latest release (2023.10.13.743))

### Reporters

marsmaantje
Elektrospy
Zyzyl

**Comment by Ruikio** [comment]
It sounds simple and like a specific use case, however this interrupts us using things for the bHaptic suit integration and it's performance gain for systems for some nice immersive systems.

This thing can literally be made into a gun that crashes the world session. It's just a sphere that kills people on touch. You're only safe if you started fully in desktop.

**Comment by Frooxius** [comment]
Should be good in 2023.11.8.335, thanks!
