### ISSUE TITLE
Screen360 Command Line Argument Doesnt work.

### ISSUE THREAD

**Issue by zahndy** [Yellow-Dog-Man/Resonite-Issues#1810]
### Describe the bug?

I wanted to record some 360 video but I cant get it to launch in this mode at all.

### To Reproduce

Add "-Screen360 " to the steam launch options or create a windows shortcut with the argument added.
Launch Resonite trough steam or the shortcut.

### Expected behavior

To start in 360 screen mode.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/b14912fb-24a7-4556-8686-dc55aafd4095)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/ad31d83c-f6dc-4c27-a8f5-f36cd68078b0)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/58b00a92-10a3-436f-b9ce-1f6d342185e0)

### Resonite Version Number

2024.4.18.1398

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-6NHJFPC - 2024.4.18.1398 - 2024-04-22 15_44_53.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15063832/DESKTOP-6NHJFPC.-.2024.4.18.1398.-.2024-04-22.15_44_53.log)

**Comment by Frooxius** [comment]
We don't support this command-line argument. You need to use `-Device Screen360`

**Comment by zahndy** [comment]
Thanks for info. 
I was just following what's currently on the wiki https://wiki.resonite.com/Command_Line_Arguments
