### ISSUE TITLE
Request for a Resonite translator badge

### ISSUE THREAD

**Issue by modimobeikete** [Yellow-Dog-Man/Resonite-Issues#1814]
### Is your feature request related to a problem? Please describe.

There's no issues relate to this request.

### Describe the solution you'd like

Translation is not always easy. I want to know if is possible to add it.

### Describe alternatives you've considered

For those contribute to the Resonite locales. they can earn one.

### Requesters

Resonite username:modimobeikete

**Comment by Frooxius** [comment]
I'm assigning @ChromaShiba to this.

Would you be able to make a translator badge that's in line with the moderation, mentor & QC? 

I'd like to assign these to all our translators, since they've been helping translate Resonite into lots of different languages a lot and they deserve some recognition for that.

**Comment by ChromaShiba** [comment]
> I'm assigning @ChromaShiba to this.
> 
> Would you be able to make a translator badge that's in line with the moderation, mentor & QC?
> 
> I'd like to assign these to all our translators, since they've been helping translate Resonite into lots of different languages a lot and they deserve some recognition for that.

Yeah I can do that.

**Comment by ChromaShiba** [comment]
@Frooxius How do you feel about this? 
<img width="311" alt="Screenshot 2024-05-30 143640" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/749eb048-b52a-49d9-81d5-d69394604aae">

**Comment by Frooxius** [comment]
@ChromaShiba There's a two main issues with that:

1) It's not universal enough. It's a bit odd for translators for languages other than Japanese to have Japanese symbol on the badge. I wouldn't use any specific languages/symbols on it, but make it something that's more universal
2) The text isn't going to be readable at the sizes the badges are usually at, so I'd avoid it and use some more general symbolism

**Comment by ChromaShiba** [comment]
> @ChromaShiba There's a two main issues with that:
> 
> 1. It's not universal enough. It's a bit odd for translators for languages other than Japanese to have Japanese symbol on the badge. I wouldn't use any specific languages/symbols on it, but make it something that's more universal
> 2. The text isn't going to be readable at the sizes the badges are usually at, so I'd avoid it and use some more general symbolism
<img width="301" alt="Screenshot 2024-05-30 143702" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/6b990031-2c32-4754-875e-20b4f65f726c">
<img width="427" alt="Screenshot 2024-05-30 144251" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/56318656-3203-405a-853b-d3d780e8eb06">

Alright, alternatively we I have these options.

**Comment by shiftyscales** [comment]
I think if you took the bottom right option there, and added the indicator arrows to the bottom right and top left corners to indicate 'translation' that could be perfect, @ChromaShiba.

Here's my 30 second MS paint approximation of what I mean.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/6a380cc9-cc44-4041-bee3-0ea4b1e28139)

**Comment by ChromaShiba** [comment]
> I think if you took the bottom right option there, and added the indicator arrows to the bottom right and top left corners to indicate 'translation' that could be perfect, @ChromaShiba.
> 
> Here's my 30 second MS paint approximation of what I mean.
> 
> ![image](https://private-user-images.githubusercontent.com/54213390/335384770-6a380cc9-cc44-4041-bee3-0ea4b1e28139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDU5MTgsIm5iZiI6MTcxNzEwNTYxOCwicGF0aCI6Ii81NDIxMzM5MC8zMzUzODQ3NzAtNmEzODBjYzktY2M0NC00MDQxLWJlZTMtMGVhNGIxZTI4MTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDIxNDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxY2VjZGE3Yjg1YWM5OGIzNDc1YTE1OGZmODg2NTUwOWQwMmY4MTA4NjNhN2Q3NzNiNjQ4NWI5MDRmYzNlNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f69WMZWLyjVGkbakXfqXIPEaaxA5FsegP3zJZ5GO_N4)

The arrows in this will have a similar issue to what Froox described with the characters with legibility in VR headsets

**Comment by ChromaShiba** [comment]
Alternatively this is also an option 
<img width="298" alt="Screenshot 2024-05-30 145118" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/daa72f9f-d325-4a0a-a79b-5096c7b09de5">

**Comment by shiftyscales** [comment]
One-sided and larger arrow variants.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/07dd45c4-c7e5-43d2-a5af-2bf14384d35f)

Single larger double-headed arrow.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/6850948c-705a-403c-9a20-94481701a5cb)

Thoughts on either of these, @ChromaShiba @Frooxius?

**Comment by ChromaShiba** [comment]
@shiftyscales I can possibly clean up something to work more like this but I'll wait to here @Frooxius thoughts before i make any more. 
![335385538-6850948c-705a-403c-9a20-94481701a5cb (1)](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/f9c9b990-0285-4b39-a5d9-208e9cb92b19)

**Comment by Frooxius** [comment]
I feel a lot of these are getting a bit too busy with too many elements in them. 

What about a single filled speech bubble, with the arrow being in the negative space? Could you make the arrow perhaps be more circular? I think that can look more elegant, kinda along these lines:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/9927fb1a-a391-46e3-915c-1e6d9520b45b)

Though better yet, would it be possible to do the "globe wireframe" in the negative space of the speech bubble, like this:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/3cb4ceca-f7e3-422f-bcbc-ce6b8349afed)

I think that is most recognizable symbol for globalization, so that would be my most preferable solution.

**Comment by shiftyscales** [comment]
I like both of those a lot. :)

**Comment by Banane9** [comment]
Alternatively, why not something like the icon wikipedia uses on their mobile site to indicate the menu for different language options for an article. It should already be pretty recognizable.

![Wikipedia Change Language Button](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/3d671c98-86e4-430d-bac4-9d54ce7abb68)

The Icon itself is SVG under MIT too: https://de.m.wikipedia.org/wiki/Datei:OOjs_UI_icon_language-ltr-progressive.svg

**Comment by ChromaShiba** [comment]
> I feel a lot of these are getting a bit too busy with too many elements in them.
> 
> What about a single filled speech bubble, with the arrow being in the negative space? Could you make the arrow perhaps be more circular? I think that can look more elegant, kinda along these lines:
> 
> ![image](https://private-user-images.githubusercontent.com/8838625/335387871-9927fb1a-a391-46e3-915c-1e6d9520b45b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDc0MzYsIm5iZiI6MTcxNzEwNzEzNiwicGF0aCI6Ii84ODM4NjI1LzMzNTM4Nzg3MS05OTI3ZmIxYS1hMzkxLTQ2ZTMtOTE1Yy0xZTZkOTUyMGI0NWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMjIxMjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzgxNTYyMGUzOTE3ZDY0YjQ4MTNiOTkzMjVkYWMzM2NjNTViNGI3ZWVmMGUwYzA1OWMzODZhMjg5YzFlMGRlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.uD1F61Xd12poScEZxRlcy0tfj_JSiO2yIK-YFJomGhQ)
> 
> Though better yet, would it be possible to do the "globe wireframe" in the negative space of the speech bubble, like this:
> 
> ![image](https://private-user-images.githubusercontent.com/8838625/335387955-3cb4ceca-f7e3-422f-bcbc-ce6b8349afed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDc0MzYsIm5iZiI6MTcxNzEwNzEzNiwicGF0aCI6Ii84ODM4NjI1LzMzNTM4Nzk1NS0zY2I0Y2VjYS1mN2UzLTQyMmYtYmNiYy1jZTZiODM0OWFmZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzBUMjIxMjE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjVjMDY1ZjRkZWI2MTliOWY1ODZjYTUzZjExNjBlNWIzNmNkMGY1ZjgwM2UzMWE1OGRjNDAwOTBmNzNiYzJjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lNZYyNFvx1Zh4hakCNjfsLikNuO-_5QSZKg70SPtUk4)
> 
> I think that is most recognizable symbol for globalization, so that would be my most preferable solution.

Unfortunately I can not get the fidelity of that style of globe (not to mention a bordering bubble or arrows) within our current style of badges, this proposed solution also suffers from thin line syndrome similar to why we didn't want to use the characters in the first option. I might propose in the meantime we stick to a simpler solution until I can fully commit to updating the style of the entire set later in the year. I'd prefer not to make too many outliers until I can get to that. The badges in particular are the product of being made early on in the set and were not thought out enough to account for fidelity beyond thick blobs.

**Comment by Frooxius** [comment]
It doesn't need to have that many lines, just a hint would be enough. 

But if the globe doesn't work, how about the arrow version then?

**Comment by Frooxius** [comment]
@ChromaShiba Is there any update on this?

**Comment by ChromaShiba** [comment]
<img width="167" alt="Screenshot 2024-06-13 151204" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/e5c524dc-e972-4c54-a27f-706302e4d4b5">
@Frooxius here a couple more options, I'm happy to go with any direction here for now but I expect to refresh these later in the year.

**Comment by Banane9** [comment]
I like the first and the last one especially. Last one would fulfill froox's request for no language specific symbols, I suppose.

**Comment by JackTheFoxOtter** [comment]
I really like the one with the globe. It's pretty.

**Comment by Frooxius** [comment]
@ChromaShiba Thank you!

I think the last one would work best here and be recognizable as translator icon. 

Would you be able to do that one with just a single speech bubble (without the second one in the background)?

I feel that will make it visually simpler and also bigger, so it's easier to read. Essentially this:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/f58b2841-1bf4-4d56-9e64-2d81d64c2393)

**Comment by ChromaShiba** [comment]
@Frooxius Sweet, here you go then! I'll drop it on our cloud server as well (should be up by the time this message comes up).
![Color_128_Translator](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/79342865/edf45546-016c-4f8e-a8e6-237b3da6ddfc)

I'll also update the presskit with the badge assets.

**Comment by Frooxius** [comment]
Thank you! This has been added in 2024.6.24.1317!

For any translators - if you don't have the badge by tomorrow, make an issue at the Locale repo so we can assign it to you!
