### ISSUE TITLE
Default Grab style setting

### ISSUE THREAD

**Issue by Electronus** [Yellow-Dog-Man/Resonite-Issues#1815]
### Is your feature request related to a problem? Please describe.

I prefer Auto grab mode. I would like to be able to set it as the default. 

### Describe the solution you'd like

A setting to define your default grab mode. (Palm, precision, auto). 

### Describe alternatives you've considered

Could change it every time I spawn. 

### Requesters

Electronus

**Comment by Frooxius** [comment]
This is now included in 2024.5.3.467, thanks!
