### ISSUE TITLE
"Capture private UI" for quick photo doesn't show private UI in preview render 

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1823]
### Describe the bug?

When using the quick photo gesture and having the "Capture private UI" setting for it enabled, the live preview of the camera won't show private UI, but it will be visible in a picture taken.

### To Reproduce

Enable "Capture private UI" in quick photo settings, and take a picture of your dash. You'll notice that you can't see the dash in the preview, but it shows up on the picture taken.

### Expected behavior

The private UI should be visible in the preview as well, the same way as it's shown if you do the same thing with the streaming camera.

### Resonite Version Number

Beta 2024.4.22.1366

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

N/A

**Comment by Frooxius** [comment]
It's not by design, it just requires a tweak.

**Comment by troyBORG** [comment]
I noticed this also.  I know the capture private UI mod showed it in the finger photo camera just fine.

**Comment by Frooxius** [comment]
Made this change in 2024.4.24.33, thanks!
