### ISSUE TITLE
Option to Hide Own and Others' Nameplates from Being Visible on Camera

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [Yellow-Dog-Man/Resonite-Issues#1829]
### Is your feature request related to a problem? Please describe.

When my own or others' nameplates appear in photos, it ruins the aesthetics of the images. However, the current option to hide nameplates makes it difficult to know where others are or recognize them when they are wearing new avatars. Switching nameplate visibility on and off is cumbersome, and not feasible when you want to take photos spontaneously.

### Describe the solution you'd like

Implement an option to keep others' nameplates from appearing in photos, such that when it's turned on, all users’ nameplates are hidden in pictures.

### Describe alternatives you've considered

None of these are practical:
- Use a local camera with the option to hide nameplates. This does not affect global cameras.
- Turning off nameplate visibility just before taking a photo, which doesn’t suit spontaneous photography.
- Setting all nameplates to be excluded by the camera's renderer, which is cumbersome when there are many users.
- Not generating nameplates in that world, which makes it impossible to recognize users by their nameplates.

### Additional Context

The desire to not capture others' nameplates in photos could also be considered from a privacy perspective. Sharing photos on social media with visible nameplates makes it clear who was interacting with whom, which can be avoided if nameplates are not displayed. This is not a complete solution but reduces the problem. There is also a relation to issue #1824 regarding privacy concerns.

### Requesters

Resonite: yoshi1123_
Discord: yoshi1123_

**Comment by Frooxius** [comment]
Added in 2024.4.30.495, thanks!

**Comment by blhsrwznrghfzpr** [comment]
I've checked out the new feature. Thanks for the update!
However, it seems that the settings for the new feature only work with Finger Photo. The local camera can hide the nameplate through settings in Camera Control, but the global camera (taken from the inventory) does not respond to either setting, and the nameplate still appears in photos.
Can you make it work with the global camera as well?

**Comment by JackTheFoxOtter** [comment]
I'm pretty sure that is unrelated to the settings, this just has to be exposed on the InteractiveCamera component itself so that non-streaming cameras can make use of this as well.

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius - from the description of the setting, it sounds like it should be a global setting that applies to all cameras, but it is in the "Quick Photo Capture" section, and only appears to apply to the quick capture photos at present.

Is this by design? I understood the initial request to have been for all cameras/screenshots/photos.

**Comment by Frooxius** [comment]
@shiftyscales It only applies to the quick photo capture.

The InteractiveCamera already has its own control for badges. We could perhaps expose that on the individual cameras, so it can be made into something you configure on those.

**Comment by shiftyscales** [comment]
I see. I'll stand up a separate request for that then. I think it could be a useful function of the content team's official camera found in the Resonite essentials/in cameras in general when used outside of the interactive camera context.

**Comment by shiftyscales** [comment]
Opened #1895 as a follow-up to this issue requesting a mechanism to expose nameplate/badge visibility control to individual cameras.
