### ISSUE TITLE
Sun Gun can't be deleted when spawned from Resonite Essentials.

### ISSUE THREAD

**Issue by ItsFawn** [Yellow-Dog-Man/Resonite-Issues#1832]
### Is your feature request related to a problem? Please describe.

When you spawn the Sun Gun from the Resonite essentials folder, it can not be deleted through normal means. 

### Describe the solution you'd like

Allow users delete it with the context menu. 

### Describe alternatives you've considered

Allow users to delete it through dev tools or other means.

### Requesters

its_fawn

**Comment by epicEaston197** [comment]
@AegisTheWolf you might want to look into this

**Comment by RyuviTheViali** [comment]
I've removed the Duplicate and Destroy blocks on the Sun Gun, so it should be able to be duplicated and destroyed now. Closing, thanks!
