### ISSUE TITLE
Unable to set UserNetworkStatistic<T> protoflux node to type "string"

### ISSUE THREAD

**Issue by Lexevolution** [Yellow-Dog-Man/Resonite-Issues#1833]
### Describe the bug?

I am trying to access the "Protocol" statistic, which is type string, using the UserNetworkStatistic node. Unfortunately, I can't set the node type to string to be able to access it.

### To Reproduce

- Launch Resonite
- Equip Protoflux tool
- Open context menu
- Click 'Browse Nodes'
- Click 'Users > Info > UserNetworkStatistic<T>'
- Type "string" in to type field

### Expected behavior

The button to change from "_invalid type_" to the appropriate button to spawn the node with a string output.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/31176843/edb86d03-7f66-4baa-a806-6a7772a0b602)

### Resonite Version Number

2024.4.24.33

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

[LEXDESKTOP - 2024.4.24.33 - 2024-04-24 20_18_11.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15092682/LEXDESKTOP.-.2024.4.24.33.-.2024-04-24.20_18_11.log)

### Additional Context

[Discord message from ProbablePrime showing implemented network statistics](https://discord.com/channels/1040316820650991766/1232455636978110596/1232468748909412414)

### Reporters

Lexevo

**Comment by Frooxius** [comment]
I've made a change in 2024.5.3.467

Added UserObjectNetworkStatistic to allow accessing statistics of type string (based on report by @Lexevo, issue #1833)
-- The previous node has been renamed to UserNumericNetworkStatistic

Thanks! Hope this helps!
