### ISSUE TITLE
[Settings] Enums are undoable in user space

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1836]
### Describe the bug?

Enums are undoable in user space

### To Reproduce

Go to controls and edit your preferred hand then click control Z

### Expected behavior

Enums should not be undoable in user space

### Resonite Version Number

Beta 2024.4.24.33

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A

### Additional Context

Someone made a Minecraft system I mined some cobblestone with a pickaxe and it went into my left hand so I switched my preferred hand so I could place down the cobblestone then switched it back later on I noticed that my preferred hand went back to being my left hand then i realized pressing control Z was undoable and switched my preferred hand back to left

### Reporters

@epicEaston197

**Comment by JackTheFoxOtter** [comment]
Duplicate of #513 I think

**Comment by epicEaston197** [comment]
> Duplicate of #513 I think

pressing control Z does not undo any other setting in user space except enums

**Comment by TisFoolish** [comment]
It's still a duplicate. They are both about the same problem, yours is just more specific in it's details.

**Comment by epicEaston197** [comment]
It would be nice if this is specifically fixed for enums because it is really annoying

**Comment by epicEaston197** [comment]
This does not happen to any other setting so there is something different about enums than the float sliders for any other setting for that matter

**Comment by art0007i** [comment]
it's because other ones don't create undo steps. also this is a duplicate of #1661 which was closed in favor of #513

**Comment by epicEaston197** [comment]
okay I'll be closing this issue really hope this gets fixed soon
