### ISSUE TITLE
First Launch setup has locale string errors

### ISSUE THREAD

**Issue by realdoomsboygaming** [Yellow-Dog-Man/Resonite-Issues#1837]
### Describe the bug?

Many text elements in First Launch have issues calling specific functions 

### To Reproduce

Launch a fresh out of the box version of Resonite on latest update as of this post.

### Expected behavior

Not have these errors in the header and namespaces.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/105606471/542973fe-bff1-4b0e-a4e3-682ca1781361)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/105606471/4038783e-5598-43ed-bcb6-7d7de932f8ad)

### Resonite Version Number

2024.4.24.33

### What Platforms does this occur on?

Windows

### Log Files

[DOOMSDESKTOP - 2024.4.24.33 - 2024-04-24 15_44_48.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15100209/DOOMSDESKTOP.-.2024.4.24.33.-.2024-04-24.15_44_48.log)

**Comment by Electronus** [comment]
Oh these are locale strings. Basically Because there isn't text in your language for that yet your seeing the raw string.

**Comment by ProbablePrime** [comment]
It should default to English if it cant find the selected language's string.

**Comment by realdoomsboygaming** [comment]
> It should default to English if it cant find the selected language's string.
> 
> I cant seem to find it in the log, but @realdoomsboygaming what language is your system set to?

English by default

**Comment by ProbablePrime** [comment]
@realdoomsboygaming Can you verify the integrity of your steam files? 

https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB

Based on what I'm seeing you have out-dated locale files on your machine, which shouldn't happen, the validation might pick them up.

**Comment by XDelta** [comment]
It looks like the locale keys that are missing there were removed from the locale files while still being used. Here is the issue on the locale repo on it https://github.com/Yellow-Dog-Man/Locale/issues/241 and the commit that removed them https://github.com/Yellow-Dog-Man/Locale/commit/20d8ca7623b6e322d1bad350c0c52727f8f27105

**Comment by realdoomsboygaming** [comment]
> @realdoomsboygaming Can you verify the integrity of your steam files?
> 
> https://help.steampowered.com/en/faqs/view/0C48-FCBD-DA71-93EB
> 
> Based on what I'm seeing you have out-dated locale files on your machine, which shouldn't happen, the validation might pick them up.

All verification checks passed.

**Comment by coolymike** [comment]
@Frooxius This issue still exists. I cleared my database due to an unrelated (Linux) issue and was greeted with the welcome screen with missing Locale strings. I checked the Locale repository and found that these strings are missing from there, not just my game. This is one of the first things a new user sees.

**Comment by Frooxius** [comment]
Fixed in 2024.7.25.1115, thank!
