### ISSUE TITLE
Notification settings

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#1838]
### Is your feature request related to a problem? Please describe.

Having a large list of contacts is great, but not great for your notifications. Everyday, I'll get those "____ is online" nearly every minute and I don't want to always set my status to Busy to avoid notifications as I still would like to be social.

### Describe the solution you'd like

I would like to see a settings toggle under "User Interface" or "Profile" that simply lets you disable Online notifications. So only your important notifications like Invites, Messages, Etc.. can be quickly accessed without the bother. 

### Describe alternatives you've considered

When Resonite first launched, I made a facet called "Silence Notifications". Unlike the name, all it did was search for the Notification visual in the Userspace and disable it. So auditory Notifications could still be heard but remain disabled visually. It's not a good way to handle this, and can break with any update to the way notifications are displayed. But it's been my fix for this problem for several months. 

There could be an option that uses this exact method (disabling all notifications except for auditory) in the settings menu, but I feel that it would be much less advised then just disabling the primary annoyance of online notifications. 

### Requesters

@zyro1331

**Comment by Frooxius** [comment]
Added this in 2024.4.30.495, thanks!
