### ISSUE TITLE
Generic OSC support

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#1841]
### Is your feature request related to a problem? Please describe.

Currently building applications with OSC protocol requires making an adapter that converts the signals to/from websocket. This makes developing certain applications more complicated.

### Describe the solution you'd like

Implement native OSC support for both client and server. This would include:

**OSC Client/Server component**
- This specifies the port/IP that it connects to and sends data
- This will require user to approve this connection, similar to the WebsocketClient
- Client/Server approvals are separate

Components to drive/sync values with OSC path, such as:
- OSCValue<T>
- OSCField<T>
- OSCChange (this will indicate when was the value last changed, even if the actual value remained the same)

These would allow specifying a path and client/server they are bound to. They would then either update that value from received OSC values or send updates as OSC to the target.

The server (sending data) can specify if they should be sent as independent messages or in an OSC Bundle

### Describe alternatives you've considered

N/A

### Additional Context

With the GigglePuck integration, we now use an OSC library, which makes it very quick and easy to add this.

This would make it very easy to implement and prototype with OSC applications and sync them up with the data model quickly.

**Comment by FlameSoulis** [comment]
Not sure how much more this will complicate things, but one issue that many OSC services written by others seem to lack are THRU ports. I get that is less of the core system's responsibility and more of people needing to actually follow a proper standard, but if there was some way to allow multiple OSC services to access the client, then the whole shuffle of OSC service stacking would be avoided.

I say this because of SteamLink only using 9001 and some other port, while most other services pretend they'll be the only service a person uses.

**Comment by ModernBalloonie** [comment]
Question, would this make it easy to make it just work with SteamLink's face tracking?

**Comment by FlameSoulis** [comment]
> Question, would this make it easy to make it just work with SteamLink's face tracking?

Kind of. This would be mostly discussed in #975, which in turn was mentioned in #1843. I'm not sure if this feature is a pre-requisite for those tickets since this appears to gear more towards ProtoFlux-related functions.

**Comment by Geenz** [comment]
It would be a prerequisite to those.

**Comment by Frooxius** [comment]
It's not really a prerequisite, they are independent enough.

It will make it easier to implement your own mapping/integration in-game, but it doesn't really help other than that.

**Comment by Frooxius** [comment]
Oh I forgot to close this, it's been implemented!
