### ISSUE TITLE
Rect type is not "linked" to Elements.Core.Rect

### ISSUE THREAD

**Issue by 5H4D0W-X** [Yellow-Dog-Man/Resonite-Issues#1847]
### Describe the bug?

When someone wants to attach a ValueGradientDriver<Rect> or any other generic component that supports Rects (or create flux nodes), they find that the component attacher doesn't accept `Rect` as a valid type. The user has to type in the specific name of the type, `Elements.Core.Rect`, to be able to attach the component.

### To Reproduce

Create an empty object, pick a component that supports generic types such as BooleanValueDriver or ValueGradientDriver and try to attach one after typing "Rect" into the generic type input field. This will not work. Then change it to "Elements.Core.Rect". It will allow you to attach the component.

### Expected behavior

Typing "Rect" into a generic type field should automatically select `Elements.Core.Rect`, similarly to how typing in "float" does the same thing as "System.single".

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/99607717/528bcfbc-9fd7-42ab-8585-598cb7d22901)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/99607717/71992877-dfc1-4baf-ab36-14480941a5e0)

### Resonite Version Number

2024.4.24.1426

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

N/A

### Reporters

EpicEaston197
ShadowX

**Comment by Frooxius** [comment]
It's not a bug, we just haven't added an alias for this yet. This is easy to add though.

**Comment by Frooxius** [comment]
Added in 2024.4.25.1389 thank!
