### ISSUE TITLE
The ability to forget/delete trackers from tracker settings

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#1848]
### Is your feature request related to a problem? Please describe.

There is some cases where you want to remove trackers from your settings, in my case I have a quest pro controller that steamvr sees as a tracker that I can't remove from tracker settings.

I also noticed this when using the debug ViveTracker, it added a tracker that I can't get rid off and could technically add a unlimited amount of trackers using this method.

### Describe the solution you'd like

The ability to remove/forget certain trackers in tracker settings by some button press or otherwise.

### Describe alternatives you've considered

If I really needed to I can probably go into the settings in userspace and delete it myself but that does seem really roundabout unless its for a emergencies.

### Additional Context

I imagine this problem will get pretty bad with users that have virtual trackers, they would just stay in their settings almost permanently.

Plus, I just like that section being clean for my own sake honestly.

### Requesters

Ohzee

**Comment by Frooxius** [comment]
Oh I forgot to close this, it's been implemented now!
