### ISSUE TITLE
Unable to input values into decimal fields.

### ISSUE THREAD

**Issue by Hennnatori** [Yellow-Dog-Man/Resonite-Issues#1853]
### Describe the bug?

Cannot input any value into ValueField<decimal>

### To Reproduce

Attaching ValueField<decimal> and attempting to input a value into "Value:".

### Expected behavior

You can input numerical values into the decimal field.

### Resonite Version Number

Beta 2024.4.26.10

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-G1GGVV6 - 2024.4.26.10 - 2024-04-26 16_00_26.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15126520/DESKTOP-G1GGVV6.-.2024.4.26.10.-.2024-04-26.16_00_26.log)

### Reporters

U-Hennnatori

**Comment by Frooxius** [comment]
Fixed this in, 2024.5.3.467, thanks for report!
