### ISSUE TITLE
Notification for Update Rollout Prior To Actual Updates

### ISSUE THREAD

**Issue by FlameSoulis** [Yellow-Dog-Man/Resonite-Issues#1862]
### Is your feature request related to a problem? Please describe.

While the wave of updates has been great, they are also sent at what feels almost random times and with no warnings. As a result, events running in-world are then put in a strange position where people cannot join because of the lack of warning, and any headless worlds are left without updates until the operators finally take note of the sudden updates.

### Describe the solution you'd like

A suggested solution, with hotfixes excluded, is to give a heads-up notice about an update and give a few hours so that people can prepare accordingly for said changes.

### Describe alternatives you've considered

There aren't any other solutions; this is purely dependent on deployment.

### Additional Context

The general idea is to give people time to prepare for an update that is not backward compatible. However, if a hotfix is needed, it should be mentioned and deployed as needed.

### Requesters

Flame Soulis (flamesoulis); Glavin (glavingkya)

**Comment by ProbablePrime** [comment]
I'd like to link: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1139 as releated.

We don't often know when we're going to release at the moment as it is very informal(I like this). But 20-30 mins should be doable.

My advice is to just not update if you're in the middle of something.

**Comment by FlameSoulis** [comment]
> I'd like to link: #1139 as related.

Woops! I figured someone must have encountered this kind of situation. I must have missed it while perusing the tickets.

> We don't often know when we're going to release at the moment as it is very informal(I like this). But 20-30 mins should be doable.

Honestly, even that delay would be very beneficial. It would ultimately resolve the issue and perhaps lead to a stronger resolution for #1139.

Thank you for listening. If it's been deemed okay, feel free to close this ticket.

**Comment by Banane9** [comment]
> My advice is to just not update if you're in the middle of something.

The issue stems from Steam enforcing the update when launching through the client, which most people probably do - I'd say.

**Comment by FlameSoulis** [comment]
> > My advice is to just not update if you're in the middle of something.
> 
> The issue stems from Steam enforcing the update when launching through the client, which most people probably do - I'd say.

Ah right... yeah, Steam has been very picky about not letting you run out-of-date versions. Given we don't have the luxury of the launcher system, once an update is pushed to Steam, you have to assume that ALL users who aren't already online will be forced to the newer one. This means event attending is limited to the window of the delayed push.

The only systems with this luxury are the headless servers.

**Comment by Frooxius** [comment]
I don't think this is very doable given our current state. We often don't have that level of heads up ourselves, so this would put a lot more burden on development at the moment and we don't have the capacity for that.

We'd need better tooling around updates to reduce the amount of manual work that's associated with updates, that will help relieve some of the pressure. If you'd like that, I'd suggest to vote for this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1212

**Comment by FlameSoulis** [comment]
I'm going to be honest: I'm not buying that.

Yes, better tools would help out, but the issue isn't the updates themselves but rather that we, the users, are getting zero heads-up about major updates that require updates to continue use. Within the past 24 hours, two major updates were released, each without any backward compatibility.

It is very frustrating to have to dance around this issue when even a notice of 20 minutes or so could at least give more of a notion to clean things up, prepare for the update, and ensure the headless servers are ready for the new version (assuming one is an operator). This was a complaint on the previous project, and the opinion of my own group remains the same.

**Comment by BlueCyro** [comment]
> I'm going to be honest: I'm not buying that.
> 
> Yes, better tools would help out, but the issue isn't the updates themselves but rather that we, the users, are getting zero heads-up about major updates that require updates to continue use. Within the past 24 hours, two major updates were released, each without any backward compatibility.
> 
> It is very frustrating to have to dance around this issue when even a notice of 20 minutes or so could at least give more of a notion to clean things up, prepare for the update, and ensure the headless servers are ready for the new version (assuming one is an operator). This was a complaint on the previous project, and the opinion of my own group remains the same.

I don't think an accusatory tone is productive in conveying this point - I would even suggest that being demanding will only hinder your issue. I can only reiterate that you have the answer in that #1212 would add more granular mechanisms to handle updating the client.

**Comment by Frooxius** [comment]
I understand that it can be frustrating, but problem here is that we often don't know that far in advance that update will be out by that time.

Usually I'm busy finalizing things, checking everything up, fixing up more issues and so on. This can take variable amount of time, as issues crop up during this process. 

Once I know that the update is ready and I hit the buttons to release it, it'll be out within a few minutes from that. 

If you wanted the 30 minute heads up, I'd have to sit and wait ~30 minutes twiddling my thumbs before hitting the release buttons - and I've got other things I want to do. 

With better tooling, I could just hit the buttons to schedule the release and have it handle those tedious processes for me. This would help overall, because there's a lot of manual steps that I need to take with every release right now.

You can either take my word for this or you decide to not believe me and think I'm lying (and to what end?) - but I don't see how we can have a any sort of constructive discussion at that point.

**Comment by EmergencyTemporalShift** [comment]
I would honestly prefer having a twenty to thirty minute heads up, even if it meant delaying that update for that long. I had a crash very nearly after the Resonite bot mentioned the update and was unable to rejoin the world I was playing, Fortunately I had saved my work, but if I hadn't yet done so, I would have been unable to rejoin. If my work had had avatar protections, then someone would be unable to save for me. I believe that feels reasonable.

**Comment by Frooxius** [comment]
Like I said above, that would require taking more time out of my day to handle things that way and I'm not okay with taking that additional burden right now.

If you want better handling for this then upvote the issues mentioned above, so we can focus on better tooling for things that will make stuff easier.

**Comment by shiftyscales** [comment]
As Frooxius had noted above- the underlying needs of this issue are best met by #1212, as such I will be closing and merging this issue into it. Thank you for your feedback.
