### ISSUE TITLE
Resonite Exit Message not rotating

### ISSUE THREAD

**Issue by Lucaedr** [Yellow-Dog-Man/Resonite-Issues#1864]
### Describe the bug?

The bottom exit message is no longer rotating. It has been stuck on "Thank you for using Resonite!" for as long as I can remember at this point. Sounded like a few others are seeing this same behavior.

This is only the very bottom section, the quotes that are submitted by users that is not functioning.

### To Reproduce

Open Resonite, Go to the exit page, and view the bottom. It will say "Thank you for using Resonite!" every time. Tonight I opened/closed about 30 times just to verify and it was the same every time.

### Expected behavior

This should be rotating randomly through the different submitted quotes by different people. Such as: 

"Glitch is cute"
submitted by: Frooxius

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47595482/121a330a-a18b-4b24-9eea-7de0789facc3)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47595482/dd8046de-56b9-41ec-bb0a-1b28b2df4cb8)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47595482/d2571b49-1c18-428b-b018-26a412b6b9c3)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47595482/5578554e-bb75-4de7-9549-1a9264b3b9e5)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47595482/60802dcb-5f25-4bba-9236-b34e982aca88)

### Resonite Version Number

2024.4.26.1258

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index / Desktop

### Log Files

[LUCAEDRPC - 2024.4.26.1258 - 2024-04-27 03_27_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15137465/LUCAEDRPC.-.2024.4.26.1258.-.2024-04-27.03_27_14.log)
[LUCAEDRPC - 2024.4.26.1258 - 2024-04-27 03_29_38.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15137466/LUCAEDRPC.-.2024.4.26.1258.-.2024-04-27.03_29_38.log)

**Comment by shadowpanther** [comment]
I saw some quotes down there, so it does rotate. Maybe the default message has much bigger probability weight than the quotes or your luck is just terrible.

**Comment by art0007i** [comment]
The chance that you get a quote on your exit screen is 20% each time you restart your game. Additionally the exit quote will only appear after you had your game open for 30 seconds, so if you were very quickly restarting to check, that might explain it.

A better way to check would be to spawn a bunch of ExitScreens in a world, and wait to see how many have exit quotes after 30 seconds. here's a link to a setup fake exit screen which you can spawn a bunch of times in a world and after about 30 seconds some of them should have a exit quote `resdb:///dcfe568c029a82ced4b6da04a04b01364802ffa6050661c55488d11c7a28c050.brson`

**Comment by Lucaedr** [comment]
I did wait for like 2-3 minutes each time. I would walk away from the computer because it takes a while for it to start up... That shouldn't be a problem with it but you know what. After getting on today I did finally have one so perhaps I had the absolute worst luck.

**Comment by art0007i** [comment]
probably safe to close this issue then. I think it is just bad luck.

**Comment by Lucaedr** [comment]
Yup. I'll go ahead and close. Thanks bad luck for making me wondering if it's even available.
