### ISSUE TITLE
US West LNL Relay: Poor performance

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#1868]
### Describe the bug?

When using the US west LNL relay, performance is poor, with voices breaking up & latency fluctuating.

Issue seems like it may be due to the relay host itself - I've been monitoring it over the past 12 hours and have noticed significantly worse ping times & packet loss to the host vs other hosts from the same provider in the same data center (Hetzner Oregon)

### To Reproduce

Under network settings, turn on "Always use relay to connect", turn off "Use closest available relay" and configure the relay server priorities to prefer resonite-relay-usw-1.

Join a session and note poor performance

### Expected behavior

Latency to not fluctuate, voices to be clear.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/d533dc41-be6d-4515-b9f2-4466666ddb9e)

Latency / packet loss to relay host (timestamps UTC+12):
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/e486959c-6622-4a53-b748-b3beda36d74b)

Comparable server from same provider (hil-speed.hetzner.com):
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/6be3fcdf-4f67-4a8f-abd9-464dae1dae68)

### Resonite Version Number

2024.4.26.1258

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ERIS - 2024.4.26.1258 - 2024-04-28 11_03_58.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15140250/ERIS.-.2024.4.26.1258.-.2024-04-28.11_03_58.log)

### Reporters

bredo

**Comment by Frooxius** [comment]
1) Do you know how many users were on that Relay at the time?
2) Does hit occur always or at particular times of the day?

**Comment by bredo228** [comment]
> 1. Do you know how many users were on that Relay at the time?

When I was testing, it appears there were less than 5 users on that particular relay.

>     2. Does hit occur always or at particular times of the day?

This has been occurring consistently for the past 12 hours at least (which is about as far back as I have monitoring), but has been noticed at least 36 hours ago - there's a message from Lexevo in the Resonite Discord showing this - https://discord.com/channels/1040316820650991766/1154514007479287942/1233367465132560394

Here's the screenshot from that message, showing high latency:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/3cce5038-9220-4501-9a5b-57b7d1190576)

**Comment by ProbablePrime** [comment]
I logged onto the machine and it looks healthy.

**Comment by shiftyscales** [comment]
Is this still an issue, @bredo228?

**Comment by bredo228** [comment]
> Is this still an issue, @bredo228?

Looks like it's still happening, albeit intermittent.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/94431aa3-8e3d-419a-9519-1532d41a7e7e)

**Comment by ProbablePrime** [comment]
The USWest1 machine is a little overloaded, I'm going to shutdown the Bridge on it at some point this week as the Relay is more important. We're also working on updating the bridge and relay to .net 8

**Comment by ProbablePrime** [comment]
With the new NetworkNode service, we have a performance improvement of several orders of magnitude, this should be resolved See #2767
