### ISSUE TITLE
Relatively frequent engine freezing happening since several days ago (VR and non-VR)

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#1875]
### Describe the bug?

Since several days ago I have been getting relatively frequent application hangs (not Unity crashes) where the Resonite window will just stop responding and will need to be force closed. During these hangs, the FrooxEngine log file is still being written to but it will say that the engine has not responded for X amount of seconds.

I know this has been happening to at least one other person and that person does not use mods at all.

Maybe this was caused by a recent update?

### To Reproduce

I don't know exactly how to reproduce it, but it seems like just leaving the Resonite window unfocused in the background or taking off the headset, leaving it for a while, and then coming back to it can trigger the crash. One time I had it trigger by going AFK then coming back and pressing the M key a few times to toggle mute which normally plays a sound, so it could be audio related (speculation). I have also seen it happen at the same time as an audio device being switched (I think Virtual Desktop does this after a while) however it is not VR exclusive. It happens even when not launching with SteamVR.

I have had this happen in a few different worlds, including my local home, which is very close to the default with very minor changes/additions. I do not think this is caused by a particular world.

### Expected behavior

Engine does not frequently stop responding.

### Screenshots

N/a

### Resonite Version Number

Beta 2024.4.26.1258

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[DESKTOP-H976HO2 - 2024.4.26.1258 - 2024-04-29 08_08_24.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15146442/DESKTOP-H976HO2.-.2024.4.26.1258.-.2024-04-29.08_08_24.log)

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15146444/Player.log)

### Reporters

Nytra (discord: nytra)

**Comment by shiftyscales** [comment]
If you don't know how to reproduce an issue- that's okay, but please don't provide speculation on what you think the issue might be if you don't know for sure that it is the issue, @Nytra.

It is better to focus on the objective facts. You can state what happened/what you were doing at the time of the issue- but it's best not to guess which part of that might or might not have caused it if you don't know.

Saying otherwise can lead us down rabbit holes and chains of thought that have us investigating the wrong systems.

**Comment by Geenz** [comment]
There may be a partial fix for this in Shader Update 1.  It appears that there's a fallback that's attempting to be used that does not exist in some of the shaders.  Not pointing at that as a smoking gun, but it's an issue in and of itself that a fix has been submitted for.  I'll leave this issue open post Shader Update 1.

**Comment by shadowpanther** [comment]
[VIXEN - 2024.4.30.495 - 2024-04-30 21_41_08.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15170341/VIXEN.-.2024.4.30.495.-.2024-04-30.21_41_08.log)
Just happened to me while loading assets for the session I just joined.
Says engine unresponsive for X seconds in the log.

**Comment by EmergencyTemporalShift** [comment]
I have had some limited success minimizing the game in windowed mode, but it hasn't worked the past couple updates (not sure which one exactly) It also seems to trigger for me when virtual desktop disconnects for 30ish seconds due to Wi-Fi issues.

**Comment by kulzae** [comment]
Might be related to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1739

I ended up crashing yesterday after a headset disconnect and have crashed due to Bluetooth headphones being connected but I have yet to get it to happen consistently with an unmodified client so I haven't nailed down exactly what causes it yet.

So far it seems like adding or removing sound devices causes it but like I said it's not consistent

**Comment by Nytra** [comment]
Just from some testing I've done this seems to happen if I'm using Virtual Desktop to stream to the Quest 3. When I use ALVR it doesn't happen. Not sure how that impacts the non-VR mode though.

**Comment by shadowpanther** [comment]
In my case, it was with Quest 3 via Steam Link.

**Comment by FlameSoulis** [comment]
I've noticed stutters occurring in a frequency of roughly once every 2 seconds. This has occurred with both the Quest Pro and the Index. I'll have to test it in a grid world to ensure it isn't world dependent and share the logs once I can validate the results.

**Comment by Nytra** [comment]
My current thinking is that these particular crashes I have been experiencing are most likely caused by audio device switching, so this issue is probably related to #1739. The shader thing might be unrelated but still worth fixing probably.

**Comment by lxw404** [comment]
I'll first state that I believe the original issue was *not* referring to stuttering or a full crash, but a complete hang with no recovery (process unresponsive).

I've experienced this particular symptom in desktop mode just sitting in a default grid world with the Resonite window unfocused for around an hour, so I don't think it is something device or runtime specific.  My headset was not even plugged in and I don't believe my audio setup has changed either, but I also don't know for sure if anything disconnected while I wasn't paying attention.

Here's a log:
[Freeze Unfocused Desktop - 2024.5.4.678 - 2024-05-06 01_05_51.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15217558/Freeze.Unfocused.Desktop.-.2024.5.4.678.-.2024-05-06.01_05_51.log)

**Comment by Nytra** [comment]
I think there may be a number of different causes for the freezes/crashes people have been getting, and this issue is vague enough to really encapsulate a lot of them

**Comment by shiftyscales** [comment]
I'm thinking the same, @Nytra. The most prominent crash sources I've seen reports of lately are #1704, and #1739.

@lxw404 - Did any of your monitors go to sleep? If so, depending on how the monitor is configured, it may have disconnected itself and caused either of #1739 or #727.

**Comment by Geenz** [comment]
I'm bumping this out of Shader Update 1- it appears that it may not be related to one of the issues I found in the shaders.

**Comment by lxw404** [comment]
@shiftyscales Not sure in that particular case if I remember it going to sleep, however I've had this happen definitively with just leaving the window unfocused in the background, just working on other things and then refocusing and Resonite is frozen.

**Comment by Nytra** [comment]
I haven't noticed any of these crashes for a while so I think I will close this issue
