### ISSUE TITLE
bug report (first time playing)

### ISSUE THREAD

**Issue by mishapmono** [Yellow-Dog-Man/Resonite-Issues#1881]
### Describe the bug?

it wont let me make an account, the screenshot taken and provided is not my real date of birth, it was a test

### To Reproduce

best i can tell you is that you cant put 01 01 2001 without it turning into 1 1 2001

### Expected behavior

i expected to be able to make an account to play with my friend

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/168486399/a74e98b8-9a93-4e5f-85de-39cc160c3e3d)

### Resonite Version Number

i dont know-

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, alienware.

### Log Files

sorry, idk what this is asking

### Additional Context

none

### Reporters

none

**Comment by ShrikeAlvaron** [comment]
You have 2010 entered as the birth year, which would mean you are 14, however the minimum age to play Resonite is 16 years old.

**Comment by Frooxius** [comment]
This is expected behavior. You cannot make an account if you're under 16.
