### ISSUE TITLE
Doppler effect intensity slider

### ISSUE THREAD

**Issue by Nwhis** [Yellow-Dog-Man/Resonite-Issues#1884]
### Is your feature request related to a problem? Please describe.

The doppler effect can be funny, but with how unrealistically intense it is it can definitely make some experiences awkward. Simply walking towards or away from an object is enough to noticeably change the pitch, which is horribly unrealistic.

### Describe the solution you'd like

Add a slider in the options menu to change the intensity of the doppler effect (including disabling it)
Ideally include a marker for "realistic" intensity

### Describe alternatives you've considered

It may also be useful to have some way to modify this with in-world audio emitters (if it isn't already), although this wouldn't fix the underlying issue (you would have to change it for every single audio emitter in every world)

**Comment by VirgilCore** [comment]
This already exists on the AudioOutput component.

**Comment by Nwhis** [comment]
> This already exists on the AudioOutput component.

Is this a global override you can permanently set up on the user client?

**Comment by VirgilCore** [comment]
> > This already exists on the AudioOutput component.
> 
> Is this a global override you can permanently set up on the user client?

No, but I can see how that would be useful. I was just making sure you knew about the override on the AudioOutput component.

**Comment by shadowpanther** [comment]
Though overriding this effect globally might make some objects and experiences not work as intended.

**Comment by Frooxius** [comment]
This is not really the type of effect that can be overridable by global setting - it's something that content creators are expected to adjust on the content they make. 

We have no way of knowing whether doppler on given audio source is important or not - maybe the way it's setup is important to the experience for some reason (e.g. it's part of some synth or narrative experience) and global override would break it.

Generally we won't add settings like that where it's not clear if it's safe to override the way content is setup or not.

**Comment by Frooxius** [comment]
How are you measuring that this is 10-100 times a realistic level?

The doppler should be based on a realistic speed of sound, so 1.0 should technically be the realistic amount of doppler you'd get for a given speed.

**Comment by Nwhis** [comment]
> How are you measuring that this is 10-100 times a realistic level?
> 
> The doppler should be based on a realistic speed of sound, so 1.0 should technically be the realistic amount of doppler you'd get for a given speed.

Simply walking towards an audio source should not change its pitch by any noticeable amount. 10-100 is a very rough guesstimate but it's at least part of the way there.
I wish I knew what the calculation was actually based on, but there doesn't seem to be any exposed way to change the speed of sound (which would theoretically fix it being way too strong if it were set to a correct value)
