### ISSUE TITLE
Assign users profile picture URL as Icon for WorldUsersFeed

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1887]
### Is your feature request related to a problem? Please describe.

Currently, a FeedEntityInterface<User> used together with WorldUsersFeed will not provide an asset URL for the Icon / HasIcon properties when instantiating an interface for a user.

### Describe the solution you'd like

I'd like the user's profile picture URL to be provided as the FeedInterface's icon property.

### Describe alternatives you've considered

Fetching the icon from the cloud for every user.

### Requesters

Nordwick & Myself

**Comment by Frooxius** [comment]
The user's icon is not known as part of the source data that WorldUsersFeed generates, therefore it cannot be provided with the feed.

If you'd like to get their icon, use the CloudUserInfo on the items to dynamically fetch the icon of the user.
