### ISSUE TITLE
Allow searching users by username in WorldUsersFeed

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1889]
### Is your feature request related to a problem? Please describe.

Currently, when entering a search phrase in a data feed view for WorldUserFeed, nothing happens.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/48771589-4aa9-4c7a-8300-4b46819596cc)

### Describe the solution you'd like

I would like to be able to make a searchable user list, where providing a search phrase would limit the results to only users who's usernames contain the phrase, case insensitive.

### Describe alternatives you've considered

Writing the user's username into the slot name and then using FindChildByName.

### Requesters

Nordwick & Myself

**Comment by Frooxius** [comment]
Implemented in 2024.5.3.467, thanks!
