### ISSUE TITLE
Editing the OSC Port can spam the user with Host Access Dialogs

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#1891]
### Describe the bug?

When editing the OSC Port on the OSC_Reciever component, you can get into a state where you are spammed by Host Access Dialogs

### To Reproduce

1. Create an OSC_Receiver
2. Set the Handling user to yourself
3. Edit the port
4. Observe the access dialog each time you type a character into the port field

### Expected behavior

Port field should wait till text is finished editing before popping the host dialog box

### Resonite Version Number

Beta 2024.4.30.495

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[ALFRED - 2024.4.30.495 - 2024-04-30 12_40_39.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15170667/ALFRED.-.2024.4.30.495.-.2024-04-30.12_40_39.log)

**Comment by Frooxius** [comment]
Are you okay if I take this one? I wanted to add a general mechanism to indicate if field should use continuous editing more or not, since it'll be useful for some settings too.

**Comment by ProbablePrime** [comment]
Of course, go for it!

**Comment by Frooxius** [comment]
Added in 2024.5.3.467! It will now only parse after editing is done.

I've added a whole new mechanism to do this for any field!
