### ISSUE TITLE
Copying a image via context menu or material inspector into your clipboard no longer works

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#1901]
### Describe the bug?

When using a context menu or material inspector button to copy a texture into your clipboard, it does not actually get put into your clipboard.

### To Reproduce

1. Start up Resonite
2. Take a picture
3. Hit Copy Image in your context menu
4. Paste by Ctrl V
5. Notice that nothing imports, or your previous clipboard imports instead

### Expected behavior

Images should be able to be copied into your clipboard.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/317d9615-8393-4d5e-85ab-0735cbca017e

### Resonite Version Number

Beta 2024.5.1.68

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-V75BHJO - 2024.5.1.68 - 2024-05-01 01_53_45.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15174238/DESKTOP-V75BHJO.-.2024.5.1.68.-.2024-05-01.01_53_45.log)

Note this is the same session that the above video was taken too.

### Additional Context

I do have a clipboard importer in my world just incase that gets asked.

### Reporters

Ohzee
its_fawn

**Comment by Frooxius** [comment]
Can you still replicate this? 

If so, can you please post your `SystemHelper.log` file from replication? It's in the same location where Resonite.exe is.

**Comment by ohzee00** [comment]
[SystemHelper.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15194824/SystemHelper.log)
Did same replication as above, still same behavior as reported.

**Comment by ohzee00** [comment]
Closing this issue due to being able to successfully copy images the past few weeks now, with the friend that originally shown me this also able to do so.
I am more blaming a weird Windows Moment than anything but it doesn't seem fair to keep this open when it works, if I have more information on a consistent way to break it I'll reopen it.
