### ISSUE TITLE
Notification for User Joining and leaving

### ISSUE THREAD

**Issue by Readun** [Yellow-Dog-Man/Resonite-Issues#1902]
### Is your feature request related to a problem? Please describe.

It would be nice to also have a notification + Option for Users who join the current session you are in and leaving.
With maybe even an optional one to see that for every session you are present.

### Describe the solution you'd like

Notification popups with current joining or leaving users

### Describe alternatives you've considered

Currently this is done by either mods or even in World made Systems.

### Additional Context

Toggles for each would be nice. For some people only joining users in the active world might be interested, others might also want that for people who leave or even for every session you are currently in.

(To see if someone may have joined your home world while being in someone elses Public world.

### Requesters

Readun

**Comment by TisFoolish** [comment]
Since they'll be a data feed, will that mean after the rework that we might be able to browse the notification history?

**Comment by Frooxius** [comment]
Added in 2024.5.3.467! Thanks!
