### ISSUE TITLE
JoinRejected and other join failures don't show in the UI

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#1906]
### Describe the bug?

Trying to join a session with a custom join verifier, the connection status panel just disappears, which doesn't clearly tell you that you were denied.

### To Reproduce

Join a session with a custom join verifier which denies you.

### Expected behavior

A message is shown that tells you that you can't join and shows the custom message returned by the system.

### Resonite Version Number

2024.5.1.68

### What Platforms does this occur on?

Windows

### Log Files

[VIXEN - 2024.5.1.68 - 2024-05-01 21_57_24.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15180901/VIXEN.-.2024.5.1.68.-.2024-05-01.21_57_24.log)

The log states the reason:
```
21:59:54.450 (120 FPS)	Waiting for join grant
21:59:55.560 (120 FPS)	JoinRejected: ...
```

### Additional Context

I don't think any message is shown in any case of network error or such that prevents from joining. Session full message would also be useful.
At first I thought I caught the LNL Relay issue that I had before (#44), but checking the log found this instead.

**Comment by shiftyscales** [comment]
I believe this may be related to the same underlying issue as #1529.

**Comment by shadowpanther** [comment]
> I believe this may be related to the same underlying issue as #1529.

It might be, but the name and description of that issue is quite different. From what I understand, that one is about the asset loading indication missing after you've connected and switched to the new session.

This one is about the error message missing when you couldn't finish the connection to said session for any reason. The connecting/loading panel just disappears immediately.

In the _legacy_ client, there was a message popping up locally in red font about the reason you can't join the session. That's what is missing here.

On the side note, I might be using a non-default loading indicator, I need to check whether that is the cause or if the default one also doesn't show the error message. Though even if the non-default indicator didn't have a place to put the error into, I would expect it to still stay for a while after the disconnect to _try_ to show the message.

**Comment by shadowpanther** [comment]
Closing this one as it was resolved by using a default panel and fixing the non-default one to actually show the message.
