### ISSUE TITLE
Headless world crashes on user joining

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#1925]
### Describe the bug?

When trying to join a session hosted by a headless, the world crashes

### To Reproduce

Host a headless, try and join the world

### Expected behavior

For it not to crash

### Resonite Version Number

2024.5.3.526

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[87ac1acc-c321-4988-8185-9afe17b638b5 - 2024.5.3.526 - 2024-05-03 09_05_19.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15198063/87ac1acc-c321-4988-8185-9afe17b638b5.-.2024.5.3.526.-.2024-05-03.09_05_19.log)

[ERIS - 2024.5.3.526 - 2024-05-03 21_04_53.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15198077/ERIS.-.2024.5.3.526.-.2024-05-03.21_04_53.log)

### Reporters

bredo, t.o.a.s.t.e.r. (discord), ohzee

**Comment by LpSuchtie** [comment]
Weirdly enough, my sessions don't crash when I try and join.
[redlanterninn-7854f6b95b-z7fpv_logs.txt](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15198176/redlanterninn-7854f6b95b-z7fpv_logs.txt)

**Comment by Frooxius** [comment]
Fixed in 2024.5.3.561, thanks! Sorry for the trouble!
