### ISSUE TITLE
User/join leave notifications notifies you of people leaving in any world you're in not only the current one

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1933]
### Describe the bug?

I am receiving notifications for users leaving in worlds I'm not currently focused to

### To Reproduce

Join a few worlds and have them in the background you will notice that users will eventually leave those worlds are in and you will still receive a notification for that

### Expected behavior

The user join/leave notification should be scoped to only my focused session

### Resonite Version Number

Beta 2024.5.3.561

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A but could obtain them if needed

### Reporters

@epicEaston197

**Comment by Frooxius** [comment]
This has been fixed in 2024.5.3.1229, thanks!
