### ISSUE TITLE
Add The Resonite Press kit items into the Resonite Essentials

### ISSUE THREAD

**Issue by ImErinTheBunny** [Yellow-Dog-Man/Resonite-Issues#1935]
### Describe the bug?

Feature request - not a bug.
I would love to have the Resonite icons and logos and any other items that would be found in the press kit be also uploaded somewhere in the Resonite Essentials folder. 

I love to use these icons a lot in things that I make in Resonite and it would be nice to have an updating list within Resonite to pull from.

### To Reproduce

Feature request - not a bug.

### Expected behavior

A new folder in Resonite Essentials > Assets to store the press kit assets

### Screenshots

I currently have the icons from the press kit saved into a grid so that I can grab them for use but as right now the list is outdated so I would love to have an always up to date list.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/148178510/353697a8-c2c9-43fa-b116-ecff7c4eb86b)

### Reporters

imerin.

**Comment by shiftyscales** [comment]
Seeking input from @ChromaShiba.
