### ISSUE TITLE
writing info to local file like blendshape toggles or boolean values for avatar parameters

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#1938]
### Is your feature request related to a problem? Please describe.

so i wanted a thing that i can use to write values like when selecting a clothes or blenshapes setting via a custom radial menu that i made and have it be persistent without having to save that avatar in that state

### Describe the solution you'd like

some sort of way to save values to a local file which is referenced to the avatar

### Describe alternatives you've considered

i dont know really 

### Additional Context

persistent avatar toggles

**Comment by Frooxius** [comment]
This is already supported through cloud variables.

**Comment by alexderpyfox** [comment]
how many cloud variables can be made? is there a limit per person?

**Comment by alexderpyfox** [comment]
maybe local cloud variables

**Comment by alexderpyfox** [comment]
should i make a new github issues for local cloud variables?

**Comment by shiftyscales** [comment]
Can you please provide more context on what you are trying to do? What are you trying to set, and why is it important that the values are different per machine?

**Comment by alexderpyfox** [comment]
i made a new github issue for the specific thing
