### ISSUE TITLE
MultiplyString Node Displays As '+'

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#194]
### Describe the bug?

The `MultiplyString` node's visual shows a `+` instead of an expected `*`.

### To Reproduce

* Equip a protoflux tip
* Spawn a `MultiplyString` node

### Expected behavior

The node should display as `*`.

### Screenshots

![Resonite_mKntN1aX0a](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/1ad0439b-de36-4790-bf69-dea4ccefaeab)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Valve Index

### Reporters

LuxKitty

**Comment by Frooxius** [comment]
It's out in 2024.6.24.1317, thanks!
