### ISSUE TITLE
Earmuff directionality setting inverted?

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1940]
### Describe the bug?

The directionality setting is inverted if you turn it to `0` it has the audio cone behavior at `1` it is the spherical radius

### To Reproduce

Turn on earmuff mode look away from someone they will be at the exact same volume as if directionality was set to `0`

### Expected behavior

directionality shouldn't be inverted

### Resonite Version Number

Beta 2024.5.3.561

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A but will collect them and provide them here if I need to

### Additional Context

I'm not sure if directionality is inverted or not but the behavior has definitely changed and in a bad way

### Reporters

@epicEaston197, Koneko, Defhammer, alex derpy fox

**Comment by alexderpyfox** [comment]
yeah i noticed it too yesterday and today it doesnt go off anymore

**Comment by epicEaston197** [comment]
Never mind it's just exhibiting some weird behavior I'll give you issue open just in case

**Comment by epicEaston197** [comment]
The behavior seems to be functioning but in a strange and odd way that it wasn't behaving like before

**Comment by epicEaston197** [comment]
It seems like the angle setting has no effect when I'm not looking at someone there's no dip in audio volume

**Comment by alexderpyfox** [comment]
directionality 100 default is like the earmuff mode isnt on

**Comment by epicEaston197** [comment]
> directionality 100 default is like the earmuff mode isnt on 30% should be default

no Alex this is a bug 100% should be fully directional

**Comment by Frooxius** [comment]
Fixed this in 2024.5.3.1229, thanks!
