### ISSUE TITLE
Emergency desktop leave world gesture no longer working

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1942]
### Describe the bug?

If I hold down shift and double tap escape nothing happens

### To Reproduce

Go into a world hold on shift and double tap escape you will observe that nothing will happen

### Expected behavior

Holding on shift and double tapping escape should force me to leave the world I'm currently in

### Resonite Version Number

Beta 2024.5.3.1229

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A but we'll collect them and share them here if I need to

### Reporters

@epicEaston197

**Comment by shiftyscales** [comment]
Hmm- that's odd. The gesture is still working in VR it seems. Are others having this issue too, @epicEaston197?

**Comment by epicEaston197** [comment]
> Hmm- that's odd. The gesture is still working in VR it seems. Are others having this issue too, @epicEaston197?

Weird it seems to be only me having this issue

**Comment by badhaloninja** [comment]
Have you tested this without mods?

**Comment by epicEaston197** [comment]
No I'll try that later when I get a chance

**Comment by Nytra** [comment]
Don't make bug reports unless you are sure it happens without mods

**Comment by epicEaston197** [comment]
> Don't make bug reports unless you are sure it happens without mods

The thing is I wanna make a GitHub issue before I forget about my issue so when I have a issue I just make it immediately worst case scenario is it gets closed and we move on

**Comment by RyeTheGooSnep** [comment]
Without mods, I've not been able to get emergency controls to work as a whole in vr. Not sure why, but it's been a problem since launch.

**Comment by epicEaston197** [comment]
Alright sorry ran about muds and it works fine 
closing this issue

**Comment by shiftyscales** [comment]
What headset/controllers are you using, @RyeTheGooSnep? The gestures require you place the controllers near the sides of your head.

**Comment by epicEaston197** [comment]
Although it was running in mods at the time of this issue i made an issue on the respective mods repo and sorrow had something really interesting to say

@BlueCyro
>Just as an FYI, the CTRL+Tab keybind breaking (without the exception) happens without any mods installed for me.

https://github.com/badhaloninja/Optizoom/issues/6#issuecomment-2095083994

**Comment by RyeTheGooSnep** [comment]
> What headset/controllers are you using, @RyeTheGooSnep? The gestures require you place the controllers near the sides of your head.

Index headset and controllers.

**Comment by RyeTheGooSnep** [comment]
> Do any other gestures work, e.g. opening up the dash by holding the controller near your head and pressing the context menu button? Or do gestures just universally not work for you, @RyeTheGooSnep?
> 
> * Open/Close Dash - Put left controller near your head and press the Context Menu button
> * Open/Close World Switcher - Put the right controller near your head and press the Context Menu button
> * Open/Close Inventory - Put the left controller near your head, hold grip and press the Context Menu button
> * Open/Close Session Control - Put the right controller near your head, hold grip and press the Context Menu button
> * Emergency Disconnect - Put both controllers near your head and hold Context Menu buttons on both for a few seconds
> * Emergency Respawn - Put both controllers near your head, hold grip on either of them and hold Context Menu buttons on both for a few seconds

The ones that work are the dash and inventory and i know that for a fact because whenever i try to open my context menu while grabbing something even if my hands are not by my head at all the dashboard opens up, but it does that with both hands not just the left, so is that unusual? The inventory one does only work with my hands near my head though.

**Comment by shiftyscales** [comment]
> but it does that with both hands not just the left, so is that unusual?

That is expected behaviour if you have the legacy world switcher disabled in the settings (it is disabled by default).

If you're able to do some gestures- it seems strange you wouldn't be able to do others though, @RyeTheGooSnep. So you absolutely can not make use of the emergency disconnect or respawn gestures?

**Comment by RyeTheGooSnep** [comment]
> > but it does that with both hands not just the left, so is that unusual?
> 
> That is expected behaviour if you have the legacy world switcher disabled in the settings (it is disabled by default).
> 
> If you're able to do some gestures- it seems strange you wouldn't be able to do others though, @RyeTheGooSnep. So you absolutely can not make use of the emergency disconnect or respawn gestures?

No, and its been a problem when there were users coming on to be a nuissance and cut limbs off my body so I couldnt do anything. Something to add, when holding the context menu buttons and holding both hands near my head, nothing happens, and upon releasing the buttons, the dashboard opens, and when holding grip and context menu, nothing happens but releasing spawns the legacy inventory panel.

**Comment by shiftyscales** [comment]
Would you be able to open a userspace inspector facet, and check if your Userspace component is disabled, @RyeTheGooSnep?

In https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1982#issuecomment-2095648376 XDelta had found that the Userspace component being disabled would cause some issues such as world focus changing with Control + Tab to stop updating, so I suspect that issue could be related.

**Comment by RyeTheGooSnep** [comment]
> Would you be able to open a userspace inspector facet, and check if your Userspace component is disabled, @RyeTheGooSnep?
> 
> In [#1982 (comment)](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1982#issuecomment-2095648376) XDelta had found that the Userspace component being disabled would cause some issues such as world focus changing with Control + Tab to stop updating, so I suspect that issue could be related.

What is the userspace inspector?

**Comment by shiftyscales** [comment]
Basically- by attaching a `Facet` component at the root of an inspector, and selecting the inspector's own slot with itself, after saving it to your inventory, it is possible to save, and spawn out this modified facet with an inspector on it which allows you to browse through "Userspace"- which is the overlayed world that contains private components like your dash.

It is not generally recommended to modify Userspace, however, this functionality can be useful for debugging issues like this.

If you are not comfortable with doing so, my recommendation would be to try resetting your dash with the `-ResetDash` [command line argument](https://wiki.resonite.com/Command_Line_Arguments) and see if that helps at all. But you will lose any customizations you have made to your dashboard including custom facets, and layouts.
