### ISSUE TITLE
Earmuff mode should use a spherical sector, not a cone

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#1944]
### Is your feature request related to a problem? Please describe.

Currently the cone earmuff uses  has a flat "bottom" (the front-faced part), so that users who are the same linear distance from you can be inside the cone when you are not looking at them, but fall out of it when you turn to look at them, voice attenuating.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/dec980d9-9a8b-4e40-b0ad-56078bd3326f)

### Describe the solution you'd like

For the earmuff to use a [spherical sector](https://en.wikipedia.org/wiki/Spherical_sector) instead of a cone so that users stay in range when you are turning your head towards them.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/09fd7e43-a061-443b-b0a3-c987c3bfcf54)

### Describe alternatives you've considered

Using a non-directional (spherical) earmuff mode.

**Comment by shiftyscales** [comment]
Can you please post your current settings, @shadowpanther?

What you are describing is what the "transition start" value accounts for.

**Comment by shadowpanther** [comment]
> Can you please post your current settings, @shadowpanther?
> 
> What you are describing is what the "transition start" value accounts for.

My settings are the default ones, I didn't change them. And I'm aware of the transition distance, but it is uniform with the distance from the surface of the cone, so it wouldn't affect this issue, because the corner (the circle) of the cone is farther away from its point (my head) than the middle of its base.

Here you go, with the falloff/transition distance it would look like this. Notice that the red user falls in the transition zone when I'm not looking at them and onto the fringe of the falloff when I'm looking directly at them:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/3b25de3a-78c3-4954-8f7e-5cdbf8d00de6)

With certain distances, there is this effect when you turn your head to look directly at the speaking user that you are hearing at normal volume, and their volume goes down as your head turns. The distance from myself to the user did not change, but the distance from the cone to the user did. That's why a spherical sector is needed instead, as it has the same distance from the top point to all the surface at the bottom.

**Comment by shadowpanther** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/a9cea6f8-9167-4783-9192-5db31178b63b)

@shiftyscales here are the settings you requested. They are the default values, I've never touched them.

**Comment by Frooxius** [comment]
I've reworked this in 2024.6.5.198, thanks for feedback! I hope this works better!
