### ISSUE TITLE
Nullable enums require "System.Nullable<T>", unlike generic types such as "int?"

### ISSUE THREAD

**Issue by Raidriar796** [Yellow-Dog-Man/Resonite-Issues#1945]
### Describe the bug?

Nullable enum types require that you enter `System.Nullable<T>`, which is inconsistent with more generic nullable types like `int?`. This is exemplified by the recent change to the Filter Mode setting on StaticTexture2D, where all components using `TextureFilterMode` as the type have drives/references broken, and can only be fixed by using the Pack Nullable Protoflux node or by replacing components with equivalents using `System.Nullable<TextureFilterMode>`.

### To Reproduce

1. Create any component that can take `TextureFilterMode`, such as `ValueField<TextureFilterMode>`
2. Try to create another of the same component but with type `TextureFilterMode?` (It will say invalid type)
3. Try to drive the filter mode setting with a component, such as `ValueMultiDriver<TextureFilterMode>` (it doesn't work)

### Expected behavior

You should be able to get nullable enums by appending "?" to the type name like more generic types, and potentially migrate existing components of type `TextureFilterMode` to instead use `TextureFilterMode?` to keep content from breaking.

### Screenshots

This is showing that `TextureFilterMode?` isn't valid
![ValueField TextureFilterMode](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/145519075/72191a4e-5665-4990-8e18-b1b98ca67d9f)
![ValueField TextureFilterMode?](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/145519075/e0b9f9be-87fb-4199-8423-f7703daa9066)
This is showing that it is valid for other types such as `int?`
![ValueField int?](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/145519075/dc2e1b04-4dad-473d-85a3-c361cdc0d597)
This is what happens when you drive the Filter Mode on a StaticTexture2D component
![Nullable TextureFilterMode](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/145519075/a9580528-0506-4ff0-8a21-84291de62bd1)
This is showing that is can still be worked with by using Pack Nullable
![PackNullableTextureFilterMode](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/145519075/b3bb441e-5e63-465d-aaeb-901ed92890d4)

### Resonite Version Number

Beta 2024.5.3.1229

### What Platforms does this occur on?

Windows, Linux

### Log Files

[2024.5.3.1229 - 2024-05-03 15_23_21.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15205524/2024.5.3.1229.-.2024-05-03.15_23_21.log)

### Additional Context

I recently made an update to a world that included a lower quality mode that changed the textures to use Trilinear instead of Anisotropic with level 16, and this recent update every drive of type `TextureFilterMode` related to this feature was broken. I have since removed it because I actually prefer the texture filtering of said world to be controlled by user settings instead of in world settings.

### Reporters

@Raidriar796 / raidriar796

**Comment by stiefeljackal** [comment]
It should be `System.Nullable<TextureFilterMode>` to get the nullable form. However, `TextureFilterMode?` should have been accepted as well.

<img width="693" alt="image" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/20023996/edc00944-7285-40ee-96eb-2503937bccf4">

**Comment by Raidriar796** [comment]
Ah, I didn't know it was specifically `System.Nullable`. I tried different variations and got close to `System.Nullable` but never thought to try it that specifically, but in hindsight it was pretty obvious given stuff like `System.Single` for Floats. Thanks.

**Comment by Banane9** [comment]
For anyone wondering, `int?` is just syntactic sugar for `System.Nullable<int>` - but the behavior is certainly inconsistent

**Comment by shadowpanther** [comment]
I feel that #427 should've covered easier typing for Nullable types too.

**Comment by Banane9** [comment]
> I feel that #427 should've covered easier typing for Nullable types too.

Seems to be inconsistent at the moment, `int?` at the top works, but the enum here doesn't.

**Comment by stiefeljackal** [comment]
All enum types are currently exhibiting this behavior.

---

__**Non-syntactic Sugar**__
`System.Nullable<ExceptionAction>`

<img width="508" alt="image" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/20023996/ddc079e6-8afa-4ae3-8bf6-d1392716e941">

---

__**Syntatic Sugar**__
`ExceptionAction?`

<img width="518" alt="image" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/20023996/c7cd11ec-cd87-453b-a05a-d4ba51f28880">

---

@Raidriar796 It might be worth updating this issue since this is impacting `enum` types in general and not specifically the `TextureFilterMode` one.

**Comment by Raidriar796** [comment]
Updated the title and original comment to focus more on enums in general, but still focused on TextureFilterMode as the lead example due to potential content breakage.

**Comment by JackTheFoxOtter** [comment]
![Image](https://github.com/user-attachments/assets/1eb1ddde-cb9a-4c04-a3a9-1c8def294ea2)
This was actually solved back when the new nice type parser was added with the type update a while ago!

**Comment by Banane9** [comment]
_Nice_

**Comment by Frooxius** [comment]
Thanks for update, closing this!
