### ISSUE TITLE
GrabbingSettings locale keys differs from that in the game.

### ISSUE THREAD

**Issue by Aesc3625** [Yellow-Dog-Man/Resonite-Issues#1946]
### Describe the bug?

GrabbingSettings locale keys differs from that in the game.

### To Reproduce

Check the grabbing settings from Controls in Settings.

### Expected behavior

Displayed in appropriate strings.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49610790/12276283-6528-4fe1-b785-872817970db5)

### Resonite Version Number

2024.5.3.1229

### What Platforms does this occur on?

Windows

### Log Files

not required

### Additional Context

It would be smoother to change strings in game as they are already translated into several languages.

**Comment by shadowpanther** [comment]
The locale files have `Settings.GrabbingSettings.DefaultHandGrabType`  key instead.

**Comment by Frooxius** [comment]
Fixed in 2024.5.4.678, the member was supposed to be renamed, but it slipped. Thanks!
