### ISSUE TITLE
Add exclude session thumbnails to texture quality settings

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1949]
### Is your feature request related to a problem? Please describe.

If you lower your texture quality settings too much session thumbnails become unlegible

### Describe the solution you'd like

Add a toggle to exclude session thumbnails from the texture quality settings

### Describe alternatives you've considered

Temporarily raising your texture quality settings

### Requesters

@epicEaston197

**Comment by Frooxius** [comment]
What you are asking for is not possible, there's nothing about session thumbnail textures that would make them be "session thumbnail texture".

From the perspective of the system, it's just a texture - there's no link in how it could be used.
