### ISSUE TITLE
Add exclude option for imported images to texture quality settings

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1950]
### Is your feature request related to a problem? Please describe.

When your texture quality settings are low imported images are really blurry and you can't really tell what's going on unless it's temporarily raise your texture resolution settings to see what the user is trying to convey with their image they imported

### Describe the solution you'd like

An exclude option for imported images the texture settings would not apply to imported images if this option were to be added

### Describe alternatives you've considered

Temporarily increasing our graphic settings to see the image in higher quality but this does increase the quality settings of everything else

### Requesters

@epicEaston197

**Comment by Frooxius** [comment]
This is also not possible, same as here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1949

There's nothing about a texture that makes it "different" from other textures - technically every single image that is an imported image.

**Comment by epicEaston197** [comment]
That is unfortunately what I was expecting
