### ISSUE TITLE
Audio orientation is sometimes delayed on startup 

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1952]
### Describe the bug?

When someone's talking to me and i look in another direction it still sounds like their voice is coming from in front of me for half a second or so

### To Reproduce

I don't know it just happens sometimes

### Expected behavior

Voice sound orientation shouldn't be delayed as to not cause disorientation

### Resonite Version Number

Beta 2024.5.3.1229

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.5.7.505 - 2024-05-16 07_17_20.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15334685/DESKTOP-DAN95E7.-.2024.5.7.505.-.2024-05-16.07_17_20.log)

### Additional Context

I had earmuff mode on while I was experiencing this issue but I experienced this issue even before that was implemented so I'm suspecting it's unrelated

### Reporters

@epicEaston197

**Comment by Frooxius** [comment]
This seems very odd to me, I can't think of a plausible mechanism how this would normally happen.

Do you have any avatar ears overrides? Or anything like that?

We'd need a way to reproduce this or at least capture a video of this appearing.

**Comment by JackTheFoxOtter** [comment]
I've noticed this a bit in the past, it's especially noticable when you have low FPS. When someone is stading right in front of you and speaking, it can almost sound as if their voice origin is "stuck" to your face when you turn quickly, and will lag behind a bit before eventually being at the correct position relative to your view.

**Comment by Frooxius** [comment]
In that case that's just because of the lag. I don't think there's much we can do about that, as it's slow to update the position of their voice.

**Comment by epicEaston197** [comment]
>Do you have any avatar ears overrides? Or anything like that?

no I do not I do have a view override but that shouldn't affect my ears

**Comment by epicEaston197** [comment]
> In that case that's just because of the lag. I don't think there's much we can do about that, as it's slow to update the position of their voice.

I hope that there is "a" solution to this because this is very disorienting and when I was in the world I wasn't even at that low of FPS

**Comment by epicEaston197** [comment]
I haven't experienced the problem recently even at low frame rates it just seems to happen randomly on launch

**Comment by shiftyscales** [comment]
So for the times it does occur, @epicEaston197 - does it occur right from the start of Resonite being launched, as a persistent issue no matter the framerate, etc? Or does the issue present itself at some point after Resonite has been running for some amount of time?

**Comment by epicEaston197** [comment]
> So for the times it does occur, @epicEaston197 - does it occur right from the start of Resonite being launched, as a persistent issue no matter the framerate, etc?

Yes

**Comment by epicEaston197** [comment]
okay small update it seems to happen at random on startup restarting the game fixes the issue also frame rate does not matter you can be at 60 FPS and it will still be delayed I also figured out that this goes for all audio including audio streams and video players etcetera

**Comment by epicEaston197** [comment]
@Frooxius I've added log files to the issue
I haven't been playing with mods for a bit so I was able to get this log

**Comment by shiftyscales** [comment]
Did you capture the Player.log at the time of that happening as well, @epicEaston197?

Without a replication case, we are unlikely to prioritize this in any case, and whenever we eventually integrate our new renderer #1401 and chuck Unity, this issue might not even be relevant anymore.

**Comment by epicEaston197** [comment]
So coming back to this issue from office hours `Prime Time Questions for 2024-12-3` I have not had this issue for very very long time now I think this issue is safe to be closed
