### ISSUE TITLE
Bad collision in tutorial and home.

### ISSUE THREAD

**Issue by vemas23** [Yellow-Dog-Man/Resonite-Issues#1958]
### Describe the bug?

In the tutorial and the cloud home collision arenworking properly.

### To Reproduce

Going into the cloud home or into the tutorial.

### Expected behavior

The collision shouldnt be off

### Screenshots

![20240504175727_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/128408040/c3024d9f-342b-41d4-a45c-5e81f4ee9e57)
![20240504175737_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/128408040/9650effc-a837-48f5-81f1-b0c575342064)

### Resonite Version Number

Beta 2024.5.4.678

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-9CNNE91 - 2024.5.4.678 - 2024-05-04 17_51_11.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15210245/DESKTOP-9CNNE91.-.2024.5.4.678.-.2024-05-04.17_51_11.log)

### Additional Context

i didnt try any other maps.

### Reporters

Me: @therealvemas

**Comment by shiftyscales** [comment]
@vemas23 - Could you do me a favour and check what your height is set to in the profile tab of the settings?

**Comment by vemas23** [comment]
I currently cant get onto my PC, but i never changed it from the deafultAm 04.05.2024 18:49 schrieb Shifty ***@***.***>:
@vemas23 - Could you do me a favour and check what your height is set to in the profile tab of the settings?

**Comment by shiftyscales** [comment]
Whenever you can, please check it and report back. I suspect it may be the same issue as #1794, @vemas23.

**Comment by vemas23** [comment]
yes, that was the issue
