### ISSUE TITLE
Unknown Crashing Within Last 24 Hours

### ISSUE THREAD

**Issue by Polly-Geist** [Yellow-Dog-Man/Resonite-Issues#1962]
### Describe the bug?

Getting random sudden crashes which far as I can tell make no sense. Uploading the logs in hopes someone can spot something I'm missing.

### To Reproduce

Unable to reproduce.

### Expected behavior

Not randomly crash in worlds.

### Resonite Version Number

2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[DESKTOP-3U8M7V3 - 2024.5.4.678 - 2024-05-04 11_26_13.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211202/DESKTOP-3U8M7V3.-.2024.5.4.678.-.2024-05-04.11_26_13.log)
[DESKTOP-3U8M7V3 - 2024.5.4.678 - 2024-05-04 14_59_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211203/DESKTOP-3U8M7V3.-.2024.5.4.678.-.2024-05-04.14_59_34.log)
[DESKTOP-3U8M7V3 - 2024.5.4.678 - 2024-05-04 15_22_00.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211204/DESKTOP-3U8M7V3.-.2024.5.4.678.-.2024-05-04.15_22_00.log)
[Crash_2024-05-04_215846080.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211207/Crash_2024-05-04_215846080.zip)
[Crash_2024-05-04_225057457.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211208/Crash_2024-05-04_225057457.zip)

### Additional Context

The first crash was in a world that I've never had issues in (a baked incomplete build using the Dawn Modular Set), while the next two were inside my home which is just a giant plane with grass material.

### Reporters

Polly-Geist

**Comment by Polly-Geist** [comment]
[DESKTOP-3U8M7V3 - 2024.5.4.678 - 2024-05-04 15_52_12.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211226/DESKTOP-3U8M7V3.-.2024.5.4.678.-.2024-05-04.15_52_12.log)
[Crash_2024-05-04_231730789.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211229/Crash_2024-05-04_231730789.zip)

another already lmao

**Comment by ohzee00** [comment]
The only thing I can find in those logs is `Shader 'PBSDisplaceTransparent_00000105': fallback shader 'Neos/PBSDisplaceShadow' not found` right before the crash in two of the player.log but that isn't consistent with every crash log. Reading Unity logs for this is really difficult sadly.

**Comment by Polly-Geist** [comment]
> Shot in the dark, could you perform a database repair? Maybe a shader downloaded incorrectly

I can try that and add more logs if I crash again. It's kind of a pain since things were fine until today.

**Comment by Polly-Geist** [comment]
[DESKTOP-3U8M7V3 - 2024.5.4.678 - 2024-05-04 16_25_07.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211243/DESKTOP-3U8M7V3.-.2024.5.4.678.-.2024-05-04.16_25_07.log)
crashed even sooner this time.

**Comment by Polly-Geist** [comment]
I'm gonna chalk this up to corrupt cache/data stored locally just going off the rails. After nuking those folders and just starting fresh.. I have not crashed for an extended amount of time.

**Comment by shiftyscales** [comment]
Based on @ohzee00's finding, I believe this may be the same issue as #1875.
