### ISSUE TITLE
thumbnails of private worlds and contacts plus worlds are getable 

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#1965]
### Describe the bug?

someone made a tool that gets thumbnails of any world even private ones and hidden contacts plus ones

### To Reproduce

change a setting in the world browser im not sure myself how but the creator said that was how he did it

### Expected behavior

it to not get thumbnaila from private or hidden contacts worlds

### Resonite Version Number

2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

vr

### Log Files

[DESKTOP-OTQN0RR - 2024.5.4.678 - 2024-05-05 02_53_30.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15211505/DESKTOP-OTQN0RR.-.2024.5.4.678.-.2024-05-05.02_53_30.log)
it got mods in the log because this is not related to mods

**Comment by shiftyscales** [comment]
We need more information / details on what is being done- ideally from the person you heard that from, and a link to the tool so we can dissect it, @alexderpyfox. Please follow up in a security ticket here: https://support.resonite.com/

Use the "Support - Report a Security Issue" help topic.
