### ISSUE TITLE
"Contacts Only" new session notifications

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1966]
### Is your feature request related to a problem? Please describe.

Right now if you turn on new session notifications you get notified of every single new session

### Describe the solution you'd like

I would like the new session notification to be scoped to my contacts list

### Describe alternatives you've considered

None

### Additional Context

I know some users might like this functionality so additionally there could be a toggle between contacts only and everyone
also I wouldn't mind using this setting if it only scoped to my contacts list but currently it isn't so I don't see much utility in it

### Requesters

@epicEaston197

**Comment by shiftyscales** [comment]
Having a 'contacts only' form of this notification type would make it considerably more useful to me, and I think is worth consideration.

**Comment by JackTheFoxOtter** [comment]
I think it should be an option to choose what scope of session notifications you want to receive. Some useful ones I can think of are "disabled", "all", "only contacts", "only LAN". Perhaps a separate option to exclude headlesses could also be good, that's the big one that has annoyed me a couple of times so far.

**Comment by Frooxius** [comment]
Added this in 2024.5.7.505! Thanks!
