### ISSUE TITLE
Some facets don't populate after using -ResetDash if their Dash pages aren't opened immediately

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#1970]
### Describe the bug?

When using `-ResetDash`, the World, Settings and Migration tabs don't seem to populate until they are opened for the first time. When restarting without `-ResetDash` afterwards, those can be left empty.

### To Reproduce

Start the game with -ResetDash, then Exit & Save, remove -ResetDash, and start the game up again

### Expected behavior

All Dash pages should immediately be populated with their corresponding facets after using `-ResetDash`.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/df0ca04c-11d8-45d7-8ce8-e8092e7d6c21)

### Resonite Version Number

Beta 2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

1. Started with -ResetDash, then exited [J4-C - 2024.5.4.678 - 2024-05-05 11_35_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15212408/J4-C.-.2024.5.4.678.-.2024-05-05.11_35_14.log)
2. Sarted afterwards without -ResetDash [J4-C - 2024.5.4.678 - 2024-05-05 11_37_22.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15212412/J4-C.-.2024.5.4.678.-.2024-05-05.11_37_22.log)

### Additional Context

When initially visiting every dash in the session where `-ResetDash` was used and then Exit & Save, the dash pages are correctly populated and available the next time you start the game.

**Comment by Nytra** [comment]
Same as this? https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/466

**Comment by epicEaston197** [comment]
> Same as this? #466

Yep I think this may be a duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/466

**Comment by JackTheFoxOtter** [comment]
Ah, I searched for it but didn't find it! Closing.
