### ISSUE TITLE
crash on add/removing sound device 

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#1974]
### Describe the bug?

it crashes the game when adding or removing an audio input

### To Reproduce

toggle use virtual audio driver in virtualdesktop streamer

### Expected behavior

it to not crash

### Resonite Version Number

2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

virtual desktop

### Log Files

[DESKTOP-OTQN0RR - 2024.5.4.678 - 2024-05-05 20_53_30.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15214184/DESKTOP-OTQN0RR.-.2024.5.4.678.-.2024-05-05.20_53_30.log)

**Comment by shiftyscales** [comment]
This is almost certainly the same issue as #1739.
