### ISSUE TITLE
Allow users without an account to add people as contacts

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1976]
### Is your feature request related to a problem? Please describe.

When you don't have an account created you can't add people as contacts or send messages to anyone the limited functionality for a steam account is very restrictive

### Describe the solution you'd like

The ability for logged out users to add others as contacts and store their data locally on the machine

### Describe alternatives you've considered

Creating an account

### Additional Context

With the existing migration functionality you could migrate your steam account to a Resonite account this might help draw new users in as they don't need to make a third party account and they can make one of their own leisure as it's not required to add people as friends and for messaging

if what I've proposed here doesn't work then I hope there is another solution that solves what I want

### Requesters

@epicEaston197

**Comment by shadowpanther** [comment]
What would the other person see? An anonymous user requesting a contact? That wouldn't work well or at all.

And migrating a Steam account into Resonite? Is that a thing? These two are entirely different classes, not mutually interchangeable.

You might be talking about using a Steam account to log in to Resonite, similar to how VRChat does that. But that still requires a native account to log in to, Steam account just acts as an alternative login method.
Maybe allow using a Steam account to create a Resonite account - using Steam's username, profile picture, etc. to fast-track through the registration. Similar to how some websites allow logging in with your Google account, while also creating a website account linked to that Google account under the hood.

**Comment by epicEaston197** [comment]
> similar to how VRChat does that. But that still requires a native account to log in to, Steam account 

VRChat allows you to add friends with your steam account and there is an interface that allows you to migrate your steam account to a VRChat account that you created then from there you can optionally log in with your steam account

**Comment by shadowpanther** [comment]
> > similar to how VRChat does that. But that still requires a native account to log in to
> 
> VRChat allows you to add friends with your steam account and there is an interface that allows you to migrate your steam account to a VRChat account that you created then from there you can optionally log in with your steam account

Yeah, but when you log in with just a Steam account to VRChat, a VRChat account is created for you, which actually stores your friends, avatars, etc. And then when you say "migrate" - you actually add a VRChat native login to that same account or merge "native" VRChat account with "Steam" VRChat account.

Without creating some kind of an account on the platform (Resonite or VRChat), there's no way to store personal data related to that platform. So something needs to be created in any case.

**Comment by Frooxius** [comment]
This is not possible. Adding contacts fundamentally requires an account to exist. Like @shadowpanther mentions, there would be nothing for the other user to work with - you can't have contact that's something that's just on other user computer.

Best way here would be to allow logging in with Steam and implicitly creating the account. It's something we considered implementing this at some point, you can make an issue for that, but I'm going to close this one.
