### ISSUE TITLE
[meta] bug report template cuts off on  resonite version number

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#1981]
### Describe the bug?

Recently there was  a change that says to not type things like "latest" but that message is cut off so it's not exactly clear what it means.

### To Reproduce

1. create a new bug report
2. look at the "Resonite Version Number" field

### Expected behavior

The placeholder message is fully visible.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/5db7723c-8e6f-4f92-8334-9f1fb60feea5)

### Resonite Version Number

n/a

### What Platforms does this occur on?

Windows

### Log Files

n/a

**Comment by shadowpanther** [comment]
The relevant commit where this was changed is https://github.com/Yellow-Dog-Man/Resonite-Issues/commit/e213ace6ce1420eedf3a3661e19a7ab50078c385

**Comment by shiftyscales** [comment]
This has since been resolved by ProbablePrime in this commit. https://github.com/Yellow-Dog-Man/Resonite-Issues/commit/30c4dc85516fddb5d25ac2c73b735bec49e1d121

**Comment by shiftyscales** [comment]
I noticed the pre-release template was lacking this updated text, and have copied it over to that template as well.
