### ISSUE TITLE
Setting to not load cloud home on startup

### ISSUE THREAD

**Issue by ShrikeAlvaron** [Yellow-Dog-Man/Resonite-Issues#1986]
### Is your feature request related to a problem? Please describe.

The command line flag to do this is pretty commonly used and new users frequently ask about it, turning it into a setting would ease this making it easier to use and for people to find on their own.

### Describe the solution you'd like

Just a simple toggle option in the settings menu.  Unsure on category, it might have to go under misc?

### Describe alternatives you've considered

Using the -DoNotAutoLoadHome launch argument

**Comment by Frooxius** [comment]
Added this in 2024.5.7.505
