### ISSUE TITLE
Add issue template for content enhancements

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#1990]
### Describe the bug?

We currently only have an issue template for bugs with official content

### To Reproduce

N/A

### Expected behavior

N/A

### Additional Context

I wanna make content issues for enhancements or tweaks but there's only a bug template for official content

### Reporters

@epicEaston197

**Comment by shadowpanther** [comment]
Agreed. Currently, you have to choose between the content-bug template and the generic feature request template.

We should at least have four categories - engine bug, engine feature, content bug, content feature.

**Comment by Nytra** [comment]
The content template is for bugs and feature requests:

`For issues/feature requests relating to tutorial/home worlds, default facets, keyboards, video and audio players, and other content produced by our content team. `

**Comment by shadowpanther** [comment]
> The content template is for bugs and feature requests:

The issue with that is that the _required_ fields in the template are about a content bug, not a content feature request.

**Comment by shiftyscales** [comment]
I've clarified/rewritten some of the language in the template to make it more encompassing for all types of content issues, @epicEaston197 @Nytra @shadowpanther.
