### ISSUE TITLE
Hide Badges on Camera Control Does Not Hide Badges

### ISSUE THREAD

**Issue by TahvoDev** [Yellow-Dog-Man/Resonite-Issues#1992]
### Describe the bug?

The "Hide Badges" option on the Camera Control does not hide player badges.

### To Reproduce

1. Open Menu on Home Tab in Home World
2. Select Camera/Streaming
3. Check "Hide Badges"
4. Click third person to view self

### Expected behavior

I expects badges (like the star above my head) to disappear. 

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/100007692/75d4ff1e-33d9-4323-9cb0-9af8708d88a9)

### Resonite Version Number

2024.5.4.678

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[FLOW - 2024.5.4.678 - 2024-05-06 17_51_04.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15227410/FLOW.-.2024.5.4.678.-.2024-05-06.17_51_04.log)

### Additional Context

This setting may also hide nameplates, but given the naming this could be considered separately. The workaround is to disable nameplates entirely. 

Possibility related? I am using the default camera. https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1829

**Comment by GrayBoltWolf** [comment]
You have a custom nameplate and badge manager. This works with the default nameplate / badge manager generated at avatar equip in user root (not a custom set of badges on avatar root).

**Comment by shadowpanther** [comment]
> You have a custom nameplate and badge manager. This works with the default nameplate / badge manager generated at avatar equip in user root (not a custom set of badges on avatar root).

A custom badge manager and nameplate should also work properly as long as the corresponding visibility components are set as on the default ones.

**Comment by TahvoDev** [comment]
Confirmed that it does correctly hide non-custom nametags. Custom nametags still show. 
I'm not exactly sure what I am looking for beyond the visibility components here, the two Avatar Name Tag Visibility components look identical on first glance. 

Custom Name Badge
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/100007692/a9a78d8d-731e-4dc3-9cdd-b8e8f088ae08)
Default Name Badge Component 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/100007692/f0db945c-347f-4db2-b651-64c66caaf3ba)

Feel free to close if the custom name tag is simply not set up correctly. 
For what it's worth, other users in-game with custom name badges have their badges showing up on my camera.
