### ISSUE TITLE
Fixing the twisting of the TubeWireMesh

### ISSUE THREAD

**Issue by AegisTheWolf** [Yellow-Dog-Man/Resonite-Issues#1993]
### Describe the bug?

The TubeWireMesh has troubles when bending the tube wire mesh in certain angles as well as the mesh creates black triangles at the ends of the mesh at certain sizes or angles. 

### To Reproduce

Simply use the premade TubeWireMesh under Resonite Essentials>Assets>3D Models>Procedural Meshes>Stripe, Segment, and Wire Meshes folder.

### Expected behavior

This procedural mesh needs to have the same touch-up pass the StripeWireMesh had when ProtoFlux wires were tweaked.

### Screenshots

![2024-05-07 00 11 27](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/65252793/af8a6dd7-3882-4160-97fb-21957138ca5a)
![2024-05-07 00 37 12](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/65252793/12a1a68c-439f-45cb-b3f3-8b4d1977a60d)

### Resonite Version Number

Beta 2024.5.4.678

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Vive Pro Eye

### Log Files

Let me know if a log file is required for this Issue.

### Additional Context

Been needing to add this GH issue for a while since using the dawn set some of the meshes used.

### Reporters

Aegis_Wolf

**Comment by PointerOffset** [comment]
This may be a dupe or otherwise related to: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1423
