### ISSUE TITLE
Matcap Material Breaks With Normal Map

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#200]
### Describe the bug?

Whenever a Matcap material has a normal map applied, the material breaks.  The `Waiting for apply` flag is False as well seemingly indicating that this variant just does not exist.

### To Reproduce

* Create a Matcap material
* Drag a normal map into the `NormalMap` field

### Expected behavior

The matcap should have a normal map applied and not be broken.

### Screenshots

![Resonite_D7g9hT0U9N](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/4d75bc65-8970-4d92-98b7-a50f165877ba)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Valve Index

### Reporters

LuxKitty

**Comment by lxw404** [comment]
Related to: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/174

**Comment by kulzae** [comment]
resrec:///U-Kulza/R-CC846284D49298BDB1F928B06F927146764A0AD1C8E53959BDA33B289E9EE69D can be found in this folder as the item with the issue number
[RENEGADE - 2023.10.13.743 - 2023-10-16 17_55_17.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12922313/RENEGADE.-.2023.10.13.743.-.2023-10-16.17_55_17.log)

**Comment by Geenz** [comment]
At first glance, the specific variant we need is not getting properly built.  Looking into this.

**Comment by Geenz** [comment]
I'm doing a build to test this with all variant stripping disabled in Unity.  I suspect that's what's causing this.

**Comment by Geenz** [comment]
This is fixed with the next shader update.
