### ISSUE TITLE
Add privacy setting to strip EXIF image data on import

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#2015]
### Is your feature request related to a problem? Please describe.

1. Most cameras these days are smart devices, that record information such as the GPS coordinates of a photo. These are saved to an area of the photo file called "EXIF" data(https://en.wikipedia.org/wiki/Exif).
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/31ed7a79-ab3b-44d9-9ef1-ca1a5ab2219c)
2. Privacy minded users would like this information not to be included when an image is imported in Resonite.]

### Describe the solution you'd like

1. A setting that when enabled, will automatically strip any EXIF information from an image on import.

### Describe alternatives you've considered

Requiring users to strip EXIF before they import.

### Additional Context

1. I took a look and FreeImage actually... mostly supported this. (see: https://github.com/Yellow-Dog-Man/FreeImage/pull/14)
2. Therefore its easy to flow into our existing image importing/exporting flows.

This report came via the ticket desk as a security issue, but I see it as more of a privacy feature, additionally as the FreeImage changes need to be public due to the nature of FreeImage, it makes sense to open a public issue.

**Comment by EmergencyTemporalShift** [comment]
Glad it got implemented, thanks for the work.

**Comment by ProbablePrime** [comment]
Not yet, we're on the way to though!

**Comment by ProbablePrime** [comment]
WIP: https://www.youtube.com/watch?v=2H9LBQ1LywA

**Comment by TisFoolish** [comment]
Can you please include info in the description that the data can include location? I know that the description mentions GEOTIFF metadata, I just fear that is far too technical for most users and won't understand what that means.

**Comment by ProbablePrime** [comment]
Sure!

**Comment by ProbablePrime** [comment]
Updated: https://github.com/Yellow-Dog-Man/Locale/commit/3e24f71b6d23adcaf1454c321d359c2ecc475b96

**Comment by TisFoolish** [comment]
I think that works!
