### ISSUE TITLE
RenderTime is reported as -1000.00 ms if Resonite is started in Desktop mode

### ISSUE THREAD

**Issue by Zyzyl** [Yellow-Dog-Man/Resonite-Issues#2016]
### Describe the bug?

The RenderTime statistic shown in the Worlds tab of the Dash Debug panel is erroneously reported as -1000.00 ms if the Resonite client is started in Desktop mode.

This makes performance profiling more difficult, particularly for users without access to VR.

### To Reproduce

Start Resonite in Desktop mode, open the Dash and check the Worlds tab of the Debug panel.

### Expected behavior

Render time would be correctly reported as it seems to be if Resonite is started in VR.

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[RenderTime bug log - 2024.5.7.505 - 2024-05-09 11_46_19.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15260623/RenderTime.bug.log.-.2024.5.7.505.-.2024-05-09.11_46_19.log)

### Reporters

Zyzyl (zyzylian on Discord)

**Comment by Frooxius** [comment]
This is not a bug.

This statistic is measured only when the VR SDK is active, it does not exist in desktop as such. 

The negative value means the statistic is not available.
