### ISSUE TITLE
Option to hide contact+ worlds your banned from from session list and contact list

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#2023]
### Is your feature request related to a problem? Please describe.

Option to hide contact+ worlds your banned from from session list and contact list

### Describe the solution you'd like

Option to hide contact+ worlds your banned from from session list and contact list

### Describe alternatives you've considered

Option to hide contact+ worlds your banned from from session list and contact list

### Requesters

SlyTheFloof

**Comment by Frooxius** [comment]
This is unfortunately not possible to do.

We do not broadcast list of banned users on worlds for privacy reasons, so you don't know that you're banned until you actually try to connect.
