### ISSUE TITLE
User inspector will not generate when in another session that you're not hosting

### ISSUE THREAD

**Issue by ScarsTRF** [Yellow-Dog-Man/Resonite-Issues#2026]
### Describe the bug?

When joining a session where both sides do NOT have any modifications, when attempting to spawn a user inspector, the entire inspector including the list of users will not generate.

### To Reproduce

- Join another user/headless.
- Open your context menu with the dev tip and create new.
- Navigate to Editor and spawn the user inspector.
- You will see that he inspector will not generate any users.

### Expected behavior

When spawning the user inspector, you should be able to see all the users in the session and click on them.

### Screenshots

![Screenshot 2024-05-11 161844](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/23484495/05c29076-e6e2-42b6-9630-d47e0a8b9373)

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[SCARS-DESKTOP - 2024.5.7.505 - 2024-05-11 16_11_07.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15284321/SCARS-DESKTOP.-.2024.5.7.505.-.2024-05-11.16_11_07.log)

### Reporters

Discord: scarstrf
Resonite: ScarsTRF

**Comment by shadowpanther** [comment]
Dupe of #1964?

**Comment by ScarsTRF** [comment]
Guess so, my bad, I did try and search but got nothing while searching "User inspector". I'll close this one so I'm not duplicating.
