### ISSUE TITLE
MultiplyString does not multiply by zero

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#2027]
### Describe the bug?

The multiply string node when given any string multiplied by zero will just output the string as if it was multiplied by 1

### To Reproduce

put multiply string with any string and integer 0
it will output the string but it should output nothing

### Expected behavior

It outputs an empty string

### Screenshots

![2024-05-11 22 57 44](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/c60ad93b-2ac4-4e90-a7ba-684a19b8fbb0)

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Windows

### Log Files

n/a

### Additional Context

this was not a problem on old platform

**Comment by Frooxius** [comment]
Made this change in 2024.6.5.198, thanks!
