### ISSUE TITLE
People that you sent contact requests to respect the contact session notification despite not accepting it

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2031]
### Describe the bug?

If you send a user a contact request you will receive notifications whenever they start a session if you have that enabled

### To Reproduce

1. Turn on the new contact session notification
2. Add somebody as a contact but not have them accept it
3. Have that person start a new session
4. You will receive the notification from them starting the session despite them not adding you as a contact

### Expected behavior

This notification should only be respected when both parties have one another added as a contact

### Resonite Version Number

Beta 2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A

### Additional Context

this could potentially be used for stocking reasons that's why this should be a mutual thing in order for this notification to function

### Reporters

@epicEaston197

**Comment by Banane9** [comment]
> 3\. Have that person start a new session

It'd be important to know which type of session this applies to. If it's just for fully public sessions, that's to be expected I would say.

**Comment by epicEaston197** [comment]
> > 3. Have that person start a new session
> 
> It'd be important to know which type of session this applies to. If it's just for fully public sessions, that's to be expected I would say.

Even then it shouldn't send the notification because you're not contacts with that person

**Comment by Banane9** [comment]
> Even then it shouldn't send the notification because you're not contacts with that person

They're your contact, essentially marking them as of interest to you, and I'd presume the notifications just check whether the host is your contact when a new session appears. Conversely, they can send you messages, while you can't send them any, because you can send messages to people that have you as a contact.

**Comment by epicEaston197** [comment]
> > Even then it shouldn't send the notification because you're not contacts with that person
> 
> They're your contact, essentially marking them as of interest to you, and I'd presume the notifications just check whether the host is your contact when a new session appears. Conversely, they can send you messages, while you can't send them any, because you can send messages to people that have you as a contact.

Well this is inconsistent with the contact online notification you only get that notification when your mutual contacts with someone

**Comment by epicEaston197** [comment]
Well this is inconsistent with the contact online notification you only get that notification when your mutual contacts with someone

**Comment by Banane9** [comment]
> Well this is inconsistent with the contact online notification you only get that notification when your mutual contacts with someone

Well, unlike a public session being hosted by someone, online status isn't public data.

**Comment by shiftyscales** [comment]
> that's to be expected I would say.

This is not expected/desirable, @Banane9. It occurs in reverse too, e.g. if a user has sent you a contact request, but you have not accepted it, they will appear in your list of 'contacts sessions' in Resonite despite them not being a contact- making that filter significantly less usable as well.

**Comment by Frooxius** [comment]
This should be fixed in 2024.5.29.27! Thanks!
