### ISSUE TITLE
Generalized movement input node

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#2032]
### Is your feature request related to a problem? Please describe.

There exist many "vehicle" systems that implement custom controls for anchored users. Currently, creators are required to write code to directly parse the raw device input to implement controls, which adds additional engineering complexity, as creators need to implement custom handling for different input devices like index controllers, touch controllers or keyboard controls manually.

### Describe the solution you'd like

I would like a single generalized node that outputs the movement input for an anchored user, which would otherwise control the user's avatar, regardless of the used input device. This would make it significantly easier for creators to engineer vehicle-like systems. At a bare minumum this would need a float2 for the movement input, but it would also be nice to see "primary", "secondary" and "jump", since I'm pretty sure those are the smallest common denominator across all input devices.

### Describe alternatives you've considered

Manually writing code to process raw device input for those kinds of systems.

**Comment by badhaloninja** [comment]
Does [Anchor Locomotion Data](https://wiki.resonite.com/ProtoFlux:Anchor_Locomotion_Data) not work for this?

It doesn't have jump, but it has input vectors and primary/secondary action
