### ISSUE TITLE
string parsing features for protoflux

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2042]
### Is your feature request related to a problem? Please describe.

so i'm making projects which require alot of parsing strings with homemade lexers and parsers. 
with protoflux i have to reverse the string, do some complex tricks then reverse it again and redo that about 10 times to get what i want.

### Describe the solution you'd like

a set of around 3/10 nodes that provide the user to be able to extract the specific parts of a string for formatting or parsing.
regex support would greatly be appreciated.

### Describe alternatives you've considered

creating a mod that provides a method class so i can use that instead of having 500+ protoflux nodes on my redprint.

### Requesters

charlie_san

**Comment by Zyzyl** [comment]
What specific functions would you like the requested set of 3 to 10 nodes to have? Are there existing C# methods you'd like ProtoFlux nodes for?

Note, regex support already has an issue https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/403

**Comment by Banane9** [comment]
Yea, you're gonna have to be more specific on what you actually want

**Comment by charlie-sans** [comment]
ah sorry.

so i hope we can get some functions that allow us to do proper string.split, and things to allow parsing of strings that actualy don't suck

**Comment by charlie-sans** [comment]
it's nearly 11pm so i'm having a hard time thinking of things lol

**Comment by Nytra** [comment]
This would require collections in protoflux https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/572

**Comment by Frooxius** [comment]
This is a bit too vague for us to really do anything. I don't know what kinds of parsing nodes would you need that would help your situation.

Like @Zyzyl mentioned, Regex already has its own issue. 

Unless you can provide specific types of nodes you'd want, we'll have to close the issue.

**Comment by charlie-sans** [comment]
ah no worries.

so, with the string features, of course regex has it's own,  but i think things like 

    `s = s.Substring(0, separatorIndex + 1);`
string.substring, or things that allow us to do switch statements with strings would be great.

**Comment by charlie-sans** [comment]
i know of others but i can't remember them.

**Comment by ProbablePrime** [comment]
ProtoFlux has a bunch of string nodes that seem to include what you're after such as substring.

If the string functions you are after output collections(arrays, lists), then those will have to wait for #572 

With those items out of the way:
- Regex(https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/403)
- Collections(#572 ) 
- We already have substring.

Unless you're able to provide a list of functions that are missing from Resonite that you'd like. We'll have to close this one as a duplicate/already implemented.

In the future, try to create GitHub issues that don't leave any unanswered questions for us, for example in this issue:
- What do you want?

Was not answered sufficiently.
