### ISSUE TITLE
dynamic varible types for itself

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2043]
### Is your feature request related to a problem? Please describe.

so i need to store a reference or a variable to a dynamic variable component so that i can reference it dynamicly.

### Describe the solution you'd like

a dynamicreference<dynamicvaluevarible> type or set of types

### Describe alternatives you've considered

trying to refhack the component location instead.

### Requesters

charlie_san

**Comment by Nytra** [comment]
did you try making a `ReferenceField<component>` ?

**Comment by charlie-sans** [comment]
i've tried to do that but it doesn't quite work the way i want it to.
ill try to experiment with the use of it but i doubt that i will get somewhere with it.

**Comment by 5H4D0W-X** [comment]
You can use the Get Slot node to obtain the slot that the component is on, or a DynamicReferenceVariable<IField<T>> to point to the actual value, for example a float, of the original variable

Ultimately I think you should explain your use case, that would make it much easier to find an appropriate existing solution or justify a new component

**Comment by charlie-sans** [comment]
so i'm trying to get a reference to a dynamic varible component so i can store it for a later use down the protoflux chain. when it comes time to use it, i want to be able to read the component and write to it with dynamic varibles.

**Comment by 5H4D0W-X** [comment]
In that case you should make a ref to the specific field you   want to write to, if you want to write to the name that would be either a string DynamicField or a DynamicReferenceVariable<IField<string>>

**Comment by Frooxius** [comment]
I don't understand what are you asking for here.

You can create dynamic variables for any type, you just need to specify that type in. It seems like your issue is resolved by the above comments?

**Comment by charlie-sans** [comment]
yeah, was looking for a way to store a say.


DynamicValueVarible<DynamicValueVarible<string>> or something like it.
 nested dynvars in the inspector

**Comment by ProbablePrime** [comment]
You can do the above, using the methods described by the users.

Closing
