### ISSUE TITLE
A way to "name" ValueMultiDrivers, or ValueGradientDrivers. (Maybe components in general?)

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2049]
### Is your feature request related to a problem? Please describe.

I often find problems when working with ValueMultiDrivers and ValueGradientDrivers where I lose track of what does what due to my disability.

This can be a problem when making animations and stuff, and sometimes I don't want to make separate slots for certain drivers because that can become a little messy, and sometimes even harder for me to work with.

### Describe the solution you'd like

I'd like a way to sort of "name" the drivers, kind of like Unity blend trees. My proposal would be a string at the top of the gradient driver or multi driver that allows you to just name it so you can keep track of it and what it does.

### Describe alternatives you've considered

Making a slot for every single driver, but if I have a bunch of them, then it's even harder to keep track because I can't see all of them in the component list, and sometimes they serve a generalized function for the avatar/item in question, so I want to have them under the same slot, but sometimes I have gradient drivers within gradient drivers, which makes it even harder to keep track because it just says stuff like [0] on ValueGradientDriver on slot, which if I have a lot of them, can make no sense if I decide to work on it later.

### Additional Context

This makes me think that something like "Component Comments" could be cool.

### Requesters

ModernBalloonie

**Comment by Dusty-Sprinkles** [comment]
It'd be nice if the names were reflected when they are referenced in protoflux too cause I've definitely ran into situations where I wish my components were more clear with what they do

**Comment by Frooxius** [comment]
Why not just put them on a slot with appropriate name? That's technically the intended way to name and organize your things - Slots support names - it's their inherent property to allow for organization.

I'm hesitant to introduce yet another mechanism to provide functionality that's already possible - especially since doing this per-component would add more overhead and would need each component have things on it that it doesn't necessarily care about or that are its responsibility.

**Comment by epicEaston197** [comment]
This might have to wait until the inspector rework and infinite scrolling #1363
once that's done adding text to components wouldn't add that much overhead unless I'm wrong

**Comment by ModernBalloonie** [comment]
> Why not just put them on a slot with appropriate name? That's technically the intended way to name and organize your things - Slots support names - it's their inherent property to allow for organization.
> 
> I'm hesitant to introduce yet another mechanism to provide functionality that's already possible - especially since doing this per-component would add more overhead and would need each component have things on it that it doesn't necessarily care about or that are its responsibility.

Yeah, fair enough. you do have a point there.

**Comment by ProbablePrime** [comment]
This periodically comes up, even I made the request back in 2019.

Generally, if you are struggling to understand what components do on a slot then one of the following is happening.
1. You have too much happening on one slot
2. Your design might need a review for simplification
3. You need to use ProtoFlux instead.

As you've indicated a favourable response, closing.
