### ISSUE TITLE
Redrive the grip and trigger impulses

### ISSUE THREAD

**Issue by Mr-CostlessClaw** [Yellow-Dog-Man/Resonite-Issues#2050]
### Is your feature request related to a problem? Please describe.

The components that are used to expose the controller imputs for activating grip and trigger are not exposed to be in a sense. Remapped

### Describe the solution you'd like

I would like to be able to have other impulses to drive trigger and grip.
This could be through components or Flux code.
 The usefulness of this would be the implications of useful hand tracking with interactions.

### Describe alternatives you've considered

This could be added as a game feature for useful hand tracking. 

### Requesters

Mr. Claw

**Comment by ProbablePrime** [comment]
In most cases, you shouldn't need this.

For example in Hand Tracking with the Leap Motion or similar, you can grab things with a pinch and they'll be grabbed.

The way this is achieved is by mapping "data" that a device has, to inputs within Resonite that trigger certain actions. We want to open things up in the future to allow for:
1. Custom Mappings - For things like rebinding keys
2. Custom Device Drivers - Allowing developers to write their own device drivers for Resonite in a similar(yet compatible with other users) manner to Plugins.

You can read somewhat about this here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1247#issuecomment-1911640819

But I don't think we have an open issue for it. I will double check and then cross-link here when done. But for now, I'll close as not planned.

**Comment by Mr-CostlessClaw** [comment]
I am on quest pro and ALVR is supposed to have these functions. I have yet to be able to interact with things in-game. External solutions are iffy at best. I cant use leap motion with this headset. This wouldn't depend on external software. Just having finger tracking. Though this would go under alternative tracking. 
This solution I was thinking would be a quick way people in game could solve finger tracking.

**Comment by ProbablePrime** [comment]
Unfortunately, the "right way" is for us to implement ALVR directly on our side, and not for us to make "quick" solutions which are hacky. You can read #4 and #5 for more information.

**Comment by Mr-CostlessClaw** [comment]
Thank you Prime for reviewing my request and replying back to it. Sorry that I haven't said anything or thanked you sooner. Since this is something I am passionate about.
I would like to respectively oppose that. I wasn't mentioning this for ALVR directly. I was looking at this like how people make their own custom IKs and custom Locomotions. 
I wasn't going to mention Quest or ALVR for there are other forms of hand tracking and people can build their own. Like they do with eye and mouth tracking. 
I saw this as a feature that could be used with any finger tracking input regardless of headset or connection software. I do hope it does get seen this way.
Though thanks again for reviewing this.

**Comment by ko-tengu** [comment]
Yeah, I think this is a useful feature to have exposed for most than just finger tracking, allowing people to wire up their own custom interaction layers with websocket/osc or through their own scripting is a nice feature to have so people can create their own hardware with it's own functions and require Resonite to update to support it natively.

**Comment by ProbablePrime** [comment]
> allowing people to wire up their own custom interaction layers with websockets
Yes that's planned with the "Custom Device Drivers" i mentioned above.

> I saw this as a feature that could be used with any finger tracking input regardless of headset or connection software. I do hope it does get seen this way.

Yes that's planned with the "Custom Device Drivers" i mentioned above.
