### ISSUE TITLE
Rotation Offset field for CopyGlobalTransform

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#2056]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to add my CopyGlobalTransform to a new parent slot of the slot I actually want to transform because I would like to have an offset rotation.

### Describe the solution you'd like

The CopyGlobalTransform should have an extra floatQ that determines how much the target slot's rotation should deviate from the source slot.

### Describe alternatives you've considered

1. Not doing this. (leads to more annoying workarounds with unnecessary slots in the hierarchy)
2. The aforementioned fake parent slot. (annoying)
3. Using ProtoFlux to do this. (making the component more versatile seems like the more straight-forward option)

### Additional Context

My current use-case for this is 4 legged avatars where the back legs copy their rotations from the front legs but might not have the same rest rotation, necessitating this offset.
I get that this makes this an instance of the XY Problem since the proper solution here is a new IK system but I think a copy with offset is fairly versatile and probably useful in other situations as well.

I am not requesting a position offset since I am not sure if it should be applied in global or local space.
If there is use cases for these, maybe two position offsets might even make sense, a global an a local one.

### Requesters

Discord: cameron5
Resonite: Psychpsyo

**Comment by Frooxius** [comment]
What is your issue with adding additional child with the offset? That's the "canonical" way to do this.

CopyGlobalTransform has one responsibility - copying global transform. You're asking to change its responsibilities here, to something that's already provided by existing systems.

Particularly I have an issue that you want just the rotation offset - it might also need to have position & scale offset for completeness, but question is how to handle these? 

This makes me concerned that this would change the component to be less generic and bend it more towards this particular use-case, which is something we normally avoid.

**Comment by Psychpsyo** [comment]
> What is your issue with adding additional child with the offset? That's the "canonical" way to do this.

My issue with the current one was that it seemed convoluted compared to this and that, in my case, I need to add additional slots in the middle of bone chains which felt not great to me.
But if this is the canonical way to do this, then the only remaining issue is that it's more annoying to set up this way which isn't really a good reason to add this.

> Particularly I have an issue that you want just the rotation offset - it might also need to have position & scale offset for completeness, but question is how to handle these?

I didn't ask for a scale offset because CopyGlobalTransform currently doesn't touch scale at all and I didn't want to ask for a position offset since there's two ways it could work (being in global or local space) and I am not sure which of the two would make more sense.

> This makes me concerned that this would change the component to be less generic and bend it more towards this particular use-case, which is something we normally avoid.

Fair point, this can probably be closed then.

**Comment by Azavit** [comment]
Does [VirtualParent](https://wiki.resonite.com/Component:VirtualParent) not work instead for your usecase?

**Comment by Banane9** [comment]
> Does [VirtualParent](https://wiki.resonite.com/Component:VirtualParent) not work instead for your usecase?

Yea, Virtual Parent is exactly what would solve this. It's basically CopyGlobalTransform + Local Transform.

**Comment by Psychpsyo** [comment]
Turns out yes, VirtualParent does exactly this.
Didn't know that.
