### ISSUE TITLE
resonite suddenly not launching fully

### ISSUE THREAD

**Issue by Draconas** [Yellow-Dog-Man/Resonite-Issues#2060]
### Describe the bug?

initial loading bar only reaches about 80% before hanging, with or without mods, clean reinstall of resonite, all launch params wiped

### To Reproduce

N/A

### Expected behavior

to actually load

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2776564/f037b8af-c764-4084-b1b8-0ced05dd77c1)

### Resonite Version Number

2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

quest 2, desktop.

### Log Files

[TITAN - 2024.5.7.505 - 2024-05-18 22_59_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15367522/TITAN.-.2024.5.7.505.-.2024-05-18.22_59_36.log)
[TITAN - 2024.5.7.505 - 2024-05-18 23_03_29.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15367523/TITAN.-.2024.5.7.505.-.2024-05-18.23_03_29.log)

### Additional Context

providing 2 logs, commonly hangs at the DB file (which I've deleted) the other it's rarely getting to

**Comment by Draconas** [comment]
seems if I let it sit for a long time (like 3+ minutes) it'll then work sometimes. attaching another log
[TITAN - 2024.5.7.505 - 2024-05-18 23_27_50.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15367594/TITAN.-.2024.5.7.505.-.2024-05-18.23_27_50.log)

**Comment by Frooxius** [comment]
From the logs attached, you have a ResoniteModLoader installed. 

We request that you remove all mods before submitting a bug report, because we don't have a way to distinguish if the bug is caused by a mod or not.

**Comment by Draconas** [comment]
One of the logs didn't have mods and the issue persisted. Something is up
with my windows install as launching resonite in a VM had it load instantly

**Comment by Frooxius** [comment]
> One of the logs didn't have mods and the issue persisted.

Which one?

Can you also provide the Player.log log file as well?

**Comment by Draconas** [comment]
will generate a new log but i believe it was the second one in my initial post. where would one find player.log?

**Comment by AmasterAmaster** [comment]
@Draconas To get the logs you need, here is a wiki page for it: https://wiki.resonite.com/Log_Files#Player.log_Files

**Comment by Draconas** [comment]
[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15380139/Player.log)
[TITAN - 2024.5.7.505 - 2024-05-20 12_23_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15380146/TITAN.-.2024.5.7.505.-.2024-05-20.12_23_14.log)
fresh modless run
also thank you @AmasterAmaster

**Comment by Draconas** [comment]
things ive tried:
-resonite reinstall
-wiped DB and cache
-reset windows networking
-tried different network interfaces and a VPN
-tried tethered to my phone
-windows VM
-chkdsk with no issues
-system file checker with issues that were fixed

only improvement i got was the windows VM when i changed the networking to bridged, i can only think something's borked in windows but resonite is the only thing affected

**Comment by TisFoolish** [comment]
I've had this happen to me as well, but I was using mods at the time and for me it's incredibly inconsistent.  I know there isn't much in this comment to help, but it shows the issue isn't limited to just their setup.

**Comment by Draconas** [comment]
ive reinstalled windows and resonite just starts instantly now

**Comment by shiftyscales** [comment]
So you are no longer experiencing this issue, @Draconas?

Are you aware if anything had changed about your Windows configuration prior to you having this issue? E.g. were there any recent updates, hardware/driver changes or other variables you are aware of?

Otherwise, this issue could probably be closed out.
