### ISSUE TITLE
Sync Error While Saving Avatars

### ISSUE THREAD

**Issue by Skielsthear** [Yellow-Dog-Man/Resonite-Issues#2063]
### Describe the bug?

I don't know what is going on. I cannot save avatars anymore.
[DESKTOP-REV78J8 - 2024.5.7.505 - 2024-05-19 16_42_48.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15371009/DESKTOP-REV78J8.-.2024.5.7.505.-.2024-05-19.16_42_48.log)
[DESKTOP-REV78J8 - 2024.5.7.505 - 2024-05-19 17_09_22.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15371011/DESKTOP-REV78J8.-.2024.5.7.505.-.2024-05-19.17_09_22.log)

### To Reproduce

I don't know.

### Expected behavior

I wanted to save an avatar.

### Resonite Version Number

2024.5.7.505

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[DESKTOP-REV78J8 - 2024.5.7.505 - 2024-05-19 16_42_48.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15371009/DESKTOP-REV78J8.-.2024.5.7.505.-.2024-05-19.16_42_48.log)
[DESKTOP-REV78J8 - 2024.5.7.505 - 2024-05-19 17_09_22.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15371011/DESKTOP-REV78J8.-.2024.5.7.505.-.2024-05-19.17_09_22.log)

### Reporters

Skielsthear

**Comment by Skielsthear** [comment]
Tried to set to Cloudflare DNS at 8.8.8.8
New log file, still same issue. 6:06:59 PM.175 (162 FPS)    Exception running PUT request to https://skyfrost-archive.resonite.com/assets/858036:858036:07011a9ae6a94e5297f05c7880095f2e:U-Skielsthear:0f74a42be0e662a7faf25aafd3d6b9c82ce0481f97c438c31b06b730f4018aa2. Remaining retries: 1. Elapsed: 63.05s
System.ObjectDisposedException: Cannot access a disposed object.
[DESKTOP-REV78J8 - 2024.5.7.505 - 2024-05-19 18_05_11.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15371071/DESKTOP-REV78J8.-.2024.5.7.505.-.2024-05-19.18_05_11.log)

**Comment by Skielsthear** [comment]
Any avatar being saved.
1GB download, 40mb upload. It happens when sending voice messages sometimes, too.

**Comment by Frooxius** [comment]
What's your internet stability like? From the logs it seems like it might be timing out or something is interrupting the upload connection.

**Comment by Skielsthear** [comment]
My Internet is quite stable. It only seems like it hangs up on Resonite. I had no issues with Steam, guild wars, Final Fantasy, Or any Streaming sites.

**Comment by Skielsthear** [comment]
For reference, I have disabled my firewalls, antiviruses, and rebooted/restarted my router. My ISP has done some maintenance just last night in the overnight hours, so will be attempting to save an avatar once more and provide the log should it fail. I turned off Discord, just in case. It gets past 10% and then hangs up at 11.3%. It will eventually say "Sync Error, check log for details." When I restart Resonite, the avatar is saved and in the inventory, however during the sync error I can no longer send voice messages. In the previous weeks I had noticed a severe lack of being able to sync with worlds I visit after only 5 minutes, and get in excess of 15,000 packets queued with the total only getting higher as time progresses.

[DESKTOP-REV78J8 - 2024.5.7.505 - 2024-05-20 16_46_38.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15382034/DESKTOP-REV78J8.-.2024.5.7.505.-.2024-05-20.16_46_38.log)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/170277034/cd8708c3-6fc1-439b-8237-34849b21dcca)

**Comment by Skielsthear** [comment]
According to H3BO3, there is a bug that can happen if something in the inventory is deleted while syncing. The error in the logs say "Cannot access disposed object." I was working with Electronus and he saw that if we rename the data folder, create a new folder, and verify integrity, I could save avatars. The moment I tried to copy the old folder to the new one, it broke again. Our solution was that I had to delete my data folder.

**Comment by Electronus** [comment]
Ill note that they had moved their data folder to Resonite_data in the install folder, I don't know how relevant that is, but I still wouldn't recommend it.

**Comment by shiftyscales** [comment]
Can you please open a new GitHub issue if you are able to replicate that condition, @Skielsthear?

If it's as easy as you say- it should be pretty quick to verify and report, because my understanding of it based on what you said:

- Save something to your inventory
- As it starts to sync, delete it from your inventory

Is that right?
