### ISSUE TITLE
Flux node to DECODE a Base64 String into the respective data such as images

### ISSUE THREAD

**Issue by ScarsTRF** [Yellow-Dog-Man/Resonite-Issues#2064]
### Is your feature request related to a problem? Please describe.

Recently I have been wanting to push images into Resonite using a variety of methods including making an API endpoint just to return a image via a URL but all this all requires some users to be OK with the fact that they are downloading something from a server that they don't recognize which can spark some concern in some.

On top of this I use XSOverlay that recently got some new API's added that have some Base64 images for like album art and other things like window information, but none of that is usable directly from the websockets between Resonite and XSOverlay

### Describe the solution you'd like

It would be really nice to have a single node that will take the Base64 encoded string and attempt to decode it into a proper image asset. Even if the node requires a impulse to execute a decode and push the image data to a imagetexture2D component like what the RenderToTextureAsset node does still would be good.

### Describe alternatives you've considered

As mentioned above the other things I have thought about doing was using URL Post requests and a ton of backend flux to handle a external API that would return a URL for that Base64 encoded string. But this will only work if the URL is not blocked or untrusted by some users.

### Additional Context

This is not exactly related to the issue #673 as I'm not wanting to Encode a image, I just want to decode a image from external sources like websockets or other forms of inputs.

### Requesters

Discord: scarstrf
Resonite: scarstrf

**Comment by Psychpsyo** [comment]
Very related to #673 which means it'll likely require #572

**Comment by Frooxius** [comment]
We wouldn't likely add node that decodes Base64 specifically to images, because Base64 can encode all kinds of data.

This operation could just get composed from two nodes: Base64 to raw bytes conversion node and then node that takes raw bytes and decodes image from it. 

In either case, that requires collection support, since the decoded/encoded data will be a byte array.

**Comment by shiftyscales** [comment]
Closing this in favour of #2078 which requests more general nodes for handling encoding/decoding Base64, and since the proposed solution of the initial issue was considered unsuitable.
