### ISSUE TITLE
World Stutters When Opening Inspector To Large Slot

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#2070]
### Is your feature request related to a problem? Please describe.

Whenever an inspector is opened to a large slot such as the avatar root slot, or even Root, the world stutters and freezes for an indeterminate amount of time for everyone.

### Describe the solution you'd like

Opening a slot should not lag the entire world.

### Describe alternatives you've considered

There really is no alternative.  At some point, you will have to inspect your avatar root which is fairly common, and lagging a session this way can be unbearable for some users.

### Additional Context

I'm making this issue to document it in light of the recent announcement of potential performance improvements and also since I haven't seen it brought up at all, even though it is a very common pain point that regular users have gotten used to.

### Requesters

Probably everyone at this point

**Comment by JackTheFoxOtter** [comment]
I believe this is due to the UI generating. The same can be observed when switching between pages on the new settings tab, even if significantly less noticable, but loading a new settings page does cause a small lag spike. I suspect that if this can be improved it would improve a lot of things, all generated UIs, but also ProtoFlux nodes being unpacked.

**Comment by shadowpanther** [comment]
I suspect the more general issue is the creation of a big chunk of slots and components. The same hitch is observed when loading a complex avatar or object into a session or when joining a session (in the last case, the whole session's worth of stuff is being unpacked on your side).

**Comment by Banane9** [comment]
Yea, same reason the contacts UI lags when first opening it - lots of slots and UI being generated at once. Staggering it out over multiple updates might help.

**Comment by JackTheFoxOtter** [comment]
> Yea, same reason the contacts UI lags when first opening it - lots of slots and UI being generated at once. Staggering it out over multiple updates might help.

Yeah, but before that I think it would be worth investigating if the slot / component creation process itself can be optimized more fundamentally. I've heard RefID allocation for example is a bit on the expensive side and might be slowing stuff down, I'm just not sure how much of an impact that itself has. I think #702 could help out in those regards for example:
> "RefID allocations will be structured to be done in blocks, with "block owners" - this will handle scenarios like components more efficiently, since those are known to have a number of fields, that are always known and fixed"

There's maybe more optimization potential elsewhere as well. Asynchronous loading might mask underlying performance issues if it's done as the first step.

**Comment by shiftyscales** [comment]
As others have highlighted- this issue itself is more of a symptom of other optimizations that can be made, e.g. #702 as highlighted above.

While this is a useful test-case to consider and potentially target during performance optimization work, there is not a specific work item that can be attributed to this issue, so for that I will be closing it. Thank you.

**Comment by JackTheFoxOtter** [comment]
> As others have highlighted- this issue itself is more of a symptom of other optimizations that can be made, e.g. #702 as highlighted above.
> 
> While this is a useful test-case to consider and potentially target during performance optimization work, there is not a specific work item that can be attributed to this issue, so for that I will be closing it. Thank you.

I wouldn't call it a duplicate. The issues linked might be potential solutions, but the underlying issue players experience is "opening inspector on large slot causes lag". Considering the reporting guidelines ask for reporting the underlying issues, I'd say this is a good one to keep open.

**Comment by shiftyscales** [comment]
@lxw404 @JackTheFoxOtter @shadowpanther @Banane9 - Discussed this issue briefly with Frooxius- he noted that #1363 and data feeds will also implicitly fix this issue because everything won't need to be generated all at once.

So there isn't really a single problem that this issue represents, as it can be fixed/improved by other existing issues as previously highlighted.

While we ask users to focus on underlying issues when reporting things- the fixes to the underlying issue highlighted here already have their own issues already.
