### ISSUE TITLE
listbans on Headless only displays ID and not usernames

### ISSUE THREAD

**Issue by sveken** [Yellow-Dog-Man/Resonite-Issues#2075]
### Describe the bug?

When using the console for the headless and using the command listbans, the list produced does not contain the usernames even though the column is there. 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19641755/0d31f492-d1d8-4dfa-9d04-38dcf88036eb)

Now that user IDs are snowflakes it makes it a little harder to at a glance find a user who is banned or not.

### To Reproduce

use the console for a headless and type listbans

### Expected behavior

The usernames are listed alongside the userIDs to make it easier to locate users. 

### Screenshots

Hamster was requested by Prime
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19641755/c8d538e8-e85b-4db9-a5c1-7b5fc2cf5e88)

### Resonite Version Number

2024.5.22.1274

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

[014535c3dace - 2024.5.22.1274 - 2024-05-23 15_29_47.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15411984/014535c3dace.-.2024.5.22.1274.-.2024-05-23.15_29_47.log)

### Reporters

lecloutpanda
Sveken

**Comment by LeCloutPanda** [comment]
From a quick glance the string is formatted correctly allowing it to accept the user name along side the other information but something clearly fails, by the looks of it when creating the entries it fails to assign ``b.Username.Value``.

Correctly formatted code from the game
```cs
foreach (UserRestrictionsSettings.Entry b in s.Entries)
{
    if (b.IsFullyBanned.Value)
    {
        Console.WriteLine(string.Format("[{0}]\tUsername: {1}\tUserID: {2}\t", index2++, b.Username.Value, b.UserId.Value) + "MachineIds: " + string.Join(", ", b.MachineIDs));
    }
}
```

**Comment by ProbablePrime** [comment]
This might be something to do with the old-> new settings migration.

Could someone verify by issuing a new ban and seeing?

**Comment by bredo228** [comment]
```
oops only grid>listbans
oops only grid>banByName notbredo
Searching for user...
User banned
oops only grid>listbans
[0]     Username: notbredo      UserID: U-notbredo      MachineIds:
oops only grid>
```

looks like it shows up, this account didn't have any existing bans though

**Comment by ProbablePrime** [comment]
Yeah I looked at our migration code and discussion(https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1554)

Migrated(from old settings system) bans will not have the username as we did not record it in a compatible way etc. We could alter the migration to find the username but as you've already migrated the settings that won't work again.

New bans do work as shown by Bredo though.

**Comment by sveken** [comment]
That makes sense. Thanks prime

**Comment by Frooxius** [comment]
Bans aren't guaranteed to have Usernames associated with them, depending on how they were added to the system.
