### ISSUE TITLE
Create a Linux Discord-channel

### ISSUE THREAD

**Issue by FlipperLP** [Yellow-Dog-Man/Resonite-Issues#208]
### Is your feature request related to a problem? Please describe.

The current solution is fine, but hard to reach/find inside Discord. If someone with no prior experience with Discord joins the server to get help, they might have a hard time finding the thread and start posting Linux related questions in channels not meant for them. It might cause mixups if they are not clear of their operating system and potential helpers have a hard time to find the questions related to Linux.

### Describe the solution you'd like

I would like to have a dedicated Linux Discord-channel for ease of access in case there are any issues with the game and the community can help each other out and hang out in general.

### Describe alternatives you've considered

There is currently a forum thread dedicated for Linux.

**Comment by ProbablePrime** [comment]
Created: https://discord.com/channels/1040316820650991766/1183927772700213299
