### ISSUE TITLE
Add rounding option to CircleSegmentShaderMesh.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2080]
### Is your feature request related to a problem? Please describe.

Currently, you can't change the rounding on the CircleSegmentShaderMesh like you can for the context menu items, However, if I bring the CircleSegmentShaderMesh into blender, I can change the rounding by changing the UV coords manually.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/ba215e98-b76e-44e0-886e-0e017b0600a3)

As you can see, there is no rounding option to round the corners like you can in the context menu.

### Describe the solution you'd like

Add a rounding option in the CircleSegmentShaderMesh properties.

### Describe alternatives you've considered

Bringing the mesh into blender and changing the UV coords manually, but you can't exactly animate that.

### Additional Context

This is affecting something i'm trying to make.

### Requesters

ModernBalloonie

**Comment by Frooxius** [comment]
Added in 2024.5.23.1416 thanks!
