### ISSUE TITLE
Session menu canvas freezes when User tab is selected.

### ISSUE THREAD

**Issue by shininghero** [Yellow-Dog-Man/Resonite-Issues#2081]
### Describe the bug?

Opening the user tab on the session menu causes the UI canvas for that portion of the dash menu to freeze.
Timing the mouse click to a known clock time, I get a log message saying `Exception in Preprocess for text. String: <b><noparse>ShiningHero <sprite name="host"></noparse></b>`

### To Reproduce

- Open Dash menu
- Click Sessions
- Click the Users tab
Dash menu freezes

### Expected behavior

Dash menu shouldn't freeze

### Resonite Version Number

Beta 2024.5.23.1416

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Pimax 5K

### Log Files

[DESKTOP-J0VP0S2 - 2024.5.23.1416 - 2024-05-23 20_16_41.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15425450/DESKTOP-J0VP0S2.-.2024.5.23.1416.-.2024-05-23.20_16_41.log)

**Comment by Frooxius** [comment]
This should be fixed in 2024.5.24.202! Thanks for report!
