### ISSUE TITLE
A Rollback or Backup Build of Resonite

### ISSUE THREAD

**Issue by AmasterAmaster** [Yellow-Dog-Man/Resonite-Issues#2083]
### Is your feature request related to a problem? Please describe.

Recently people are having problems with Resonite breaking in ways after an update, and I feel it would be beneficial to have at least one (1) rollback version that people can go back to that is more stable, or at least have a backup version that is stable until a patch, hot fix, or future update that can allow users to safely jump back into the latest version.

### Describe the solution you'd like

A button somewhere that gives the option to go back at least one (1) version of Resonite. (Probably similar to using the beta versions via a dropdown on Steam. Library page -> Resonite -> Gear button (settings) -> Betas -> Beta Participation -> having a drop down option for a rollback/backup version of Resonite).

### Describe alternatives you've considered

An in-game option of a button that could force close Resonite and load the older version, but I feel that would need a warning for users that see the button and also you would need to have two Resonites on the system, that would not be efficient...

### Additional Context

Having a system like this (even if this feature request became topical at the moment), I feel this would be an evergreen thing that could be useful to the dev team in the future, especially if you keep different versions on your (the dev team) systems that you can hotswap at anytime when needed for the rollback/backup option.

Also, since the Data Model does not change much between updates (basically we are currently able to still see each other, talk to each other, and see items/slots in the world, including still being able to communicate between versions using the contacts menu), i feel it wont be too much workload (especially since Resonite has code versioning) for having a way to support this.

### Requesters

AmasterAmaster

**Comment by charlie-sans** [comment]
that sounds actualky pretty cool. 👍

**Comment by SlyTheFloof** [comment]
sounds cool but we are in a active editor that always runs in dev mode

**Comment by Frooxius** [comment]
This would be handled by this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1212
