### ISSUE TITLE
The Encapsulate Bounds node outputs an infinite-sized bounding box when the OtherBounds input is an empty bounding box

### ISSUE THREAD

**Issue by Zyzyl** [Yellow-Dog-Man/Resonite-Issues#2090]
### Describe the bug?

With the Encapsulate Bounds ProtoFlux node, the output will be an infinite-sized bounding box with center [0;0;0] if the OtherBounds input is an empty bounding box.

### To Reproduce

Open a new world and generate the ProtoFlux setup shown in the screenshot below. This world already has it set up:  `resrec:///U-Zyzyl/R-857397a3-33a3-4398-b751-76ab6faf8dff`

### Expected behavior

I'm not sure exactly what the output should be in this case, but I don't think the output should be an infinitely large bounding box. I think what would make sense would be to return the input Bounds since it doesn't need to be transformed to encapsulate an empty bounds. 

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/66165438/04bd46d2-7a76-4576-b8a6-f1cc717ded43)

### Resonite Version Number

Beta 2024.5.24.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Tested in Desktop mode

### Log Files

[EncapsulateBounds log - 2024.5.24.202 - 2024-05-25 07_21_47.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15442134/EncapsulateBounds.log.-.2024.5.24.202.-.2024-05-25.07_21_47.log)

### Reporters

Zyzyl (zyzylian on Discord)

**Comment by Zyzyl** [comment]
On further investigation, this looks like this is probably related to an Empty bounding box having min and max values at min float and max float. I'll leave this up for now, but I'm happy to make a new one if this is considered more of a symptom than the real underlying problem.

**Comment by Frooxius** [comment]
The min max being swapped is how Empty bounding box is signaled without needing additional boolean stored with the data.

We just need to add a check that prevents the Encapsulation when the bounds are empty, rather than just plainly running the math.

**Comment by Frooxius** [comment]
Fixed in 2024.6.5.198, thanks!
