### ISSUE TITLE
Video URLs from X.com get pasted as audio

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#2093]
### Describe the bug?

When pasting a link to a video on x.com, it comes in as audio only.
For twitter.com, it comes in as a video.

### To Reproduce

Paste an x.com video link into Resonite, such as this one: ``https://x.com/psychpsyo/status/1794354039725215885``

### Expected behavior

It should come in as a video.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/60073468/74ec8ab8-929a-4a87-8440-56a695676b57)

### Resonite Version Number

Beta 2024.5.24.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

I don't feel comfortable sharing log files, especially for issues this easily replicated

### Reporters

cameron5 on Discord, Psychpsyo on Resonite

**Comment by epicEaston197** [comment]
This is probably a problem with YouTubeDL as the domain change is relatively recent I think if you just run the update command this would probably solve your issue

**Comment by epicEaston197** [comment]
okay I updated YouTubeDL manually and the issue still persists this is probably a third party fix that we'll need to wait on

**Comment by JackTheFoxOtter** [comment]
Last time I tried this worked for me, does this issue still happen?
