### ISSUE TITLE
Enhance the renderer to remove the fake ambient occlusion effect

### ISSUE THREAD

**Issue by InconsolableCellist** [Yellow-Dog-Man/Resonite-Issues#21]
### Is your feature request related to a problem? Please describe.

It seems that when the renderer currently in use produces a fake ambient occlusion effect, easily visible as a shadow around objects. If you bring your hand in front of your face and wave it around you often see a vague shadow projected onto objects. 

### Describe the solution you'd like

I'd like a better renderer that looks more like other Unity games, and doesn't include that shadowy effect. I can't say for sure that it's fake ambient occlusion, but I believe it's a really clear effect. If my description doesn't give you an idea of what I'm talking about I can try to capture a video.

The effect also seems more unpleasant, for whatever reason, when my FPS is low. But perhaps that's just a red herring sort of thing.

### Describe alternatives you've considered

The effect is less annoying when I stay in places that have higher FPS.

**Comment by Sarniwoop** [comment]
+1 on this. The ambient occlusion postprocessing filter is both ugly and extremely off-putting for me and my friends. It renders differently in each eye and throws void-shapes where they really don't belong.

Adding a toggle to disable ambient occlusion (Or postprocessing all together! Bloom and Motion Blur doesn't look great, but they're not nearly as awful as the AO effect) is not a technical challenge - it's literally a component checkbox option on the camera.

I know the long term plan is to move to a new renderer, but surely some devtime could be allocated to create that button so I can tell newcomers they can easily disable it without having to install mods when they ask why the shadows look like absolute crap in here.

**Comment by Nammi-namm** [comment]
I don't know if the ambient occlusion effect is technically "fake" but it is jarring in VR especially. The fact it looks different in each eye can be headache inducing for some users. I would gladly like to be able to turn it off if the current implementation is not improved.

**Comment by Gawdl3y** [comment]
I don't think it's "fake", it's just a standard-ish SSAO pass AFAIK, though I could be wrong. That being said, if I were to hazard a guess, this won't be addressed until the new renderer (Sauce) that Geenz and others are working on is stable and implemented into Resonite to replace Unity. If you're interested in learning more about Sauce, see the [Void Anchor Discord](https://discord.gg/K5gsnK4WQY) and [their Patreon](https://www.patreon.com/voidanchor) (all Sauce-related posts are public).

**Comment by The-furf-of-July** [comment]
I don't think it should wait until then if the methods to fix/remove/toggle it have already been solved in cameras and via plugins. If it wouldn't take much dev time and would help the new user experience I think it'd be worth doing it now.

Namely, toggles for bloom, motion blur, and AO. They are likely to be common beginner complaints, and the fix seems straightfforward.

**Comment by Sarniwoop** [comment]
This is a very low hanging fruit that would make a lot of people happy and would probably take less than an hour or two to fully implement.

I'm handwaving numbers now, but having to wait several years until Sauce is out is crazy when disabling post processing, parts of it or entirely, is a literal matter of a checkbox being ticked or not. Most of the coding effort would be adding a new button in the settings page and hooking it up to disable/enable the component.

**Comment by kazu0617** [comment]
+1, but add notes. This option works only under the Unity rendering engine, and I think it's fine if you assume it won't work eventually. It only need to write it down as an assumption that it won't work for a new rendering engine.

I'm only worried that the addition of this check box will make it difficult to add a check box to a new rendering engine that can't be updated ...

**Comment by kazu0617** [comment]
That's the big disconnect between being able to do it with a Mod and being able to implement it officially. You have to have some commitment to work in the future. Mod doesn't, so it has no problem breaking with every update.

Modで出来る、というのと公式で実装する、というところの大きな乖離はそこだからね。将来にわたって動作することをある程度約束しないといけない。Modはそうではないので、更新のたびに壊れることについて問題ない。

**Comment by Nammi-namm** [comment]
From [Unity Documentation](https://docs.unity3d.com/540/Documentation/Manual/script-ScreenSpaceAmbientOcclusion.html):
>Note that SSAO is quite expensive in terms of processing time and generally should only be used on high-end graphics cards. Using SSAO will cause Unity to render the depth+normals texture of the camera which increases the number of draw calls and has a CPU processing overhead. However, the depth+normals texture then can be used for other effects as well (eg, Depth of Field). Once the texture is generated, the remainder of the SSAO effect is performed on the graphics card.

Granted this might not apply to Resonite depending on what Resonite does. But at the very least we know rendering in Resonite is done via Unity. So I thought it would be worth mentioning here.

I decided to do my own test via modding: [video](https://www.youtube.com/watch?v=PhGoQ7LoxyA) comparing framerate/frametime between having SSAO on and SSAO off in VR. World used: resrec:///U-Enverex/R-973a3778-1d15-45c5-a157-5b447af01a91 . There is quite a noticeable difference in framerate/frametime between it being on and being off.

**Comment by InconsolableCellist** [comment]
That looks like quite a useful mod. ~50% better FPS (from 40 to 60) by disabling something I don't even want to see? Will you distribute it?

**Comment by Nammi-namm** [comment]
> That looks like quite a useful mod. ~50% better FPS (from 40 to 60) by disabling something I don't even want to see? Will you distribute it?

Cyro @RileyGuy made it, hasn't made it public on github yet. But intends to. I'll link it here when public if nobody else beats me to it.

**Comment by The-furf-of-July** [comment]
> +1, but add notes. This option works only under the Unity rendering engine, and I think it's fine if you assume it won't work eventually. It only need to write it down as an assumption that it won't work for a new rendering engine.
> 
> I'm only worried that the addition of this check box will make it difficult to add a check box to a new rendering engine that can't be updated ...

Once there is a new rendering engine I think it'd be safe to remove an option that specifically disables Unity post-processing effects. Sauce would probably have its own implementations of these things anyway.

**Comment by Frooxius** [comment]
You can now configure AO in 2024.4.17.1420, thanks for the issue!
