### ISSUE TITLE
SteamLink Face Tracking OSC address typo

### ISSUE THREAD

**Issue by hazre** [Yellow-Dog-Man/Resonite-Issues#2100]
### Describe the bug?

So I was going through Froox's new SteamLink face tracking code and I think there seems to be a typo for the address `/sl/xrfb/facew/TongueOut`, so the tongueout expression might not be even working? (I can't test, I don't own a Quest Pro anymore)

It should be `/sl/xrfb/facew/TongueOut` instead of `/sl/xrfb/facew/ToungeOut`.

### To Reproduce

See if Tongue out expression works?

### Expected behavior

To Tongue come in and out.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/37149950/d79cebb9-4a1a-4d49-8a1b-335740a43c9e)

### Resonite Version Number

2024.5.24.202

### What Platforms does this occur on?

Windows

### Log Files

N/A

### Reporters

@hazre

**Comment by hazre** [comment]
It's possible Valve has added a fallback for that address, so the misspelled version still works. Again I can't test, so I don't know.

**Comment by troyBORG** [comment]
I had my tongue already setup previously, and it still working after the new update.  

Originally with the Vive Face Tracker, then using Cyro's Mod that let Steam Link OSC work, and now with the official support.   Tongue still triggers.

**Comment by Frooxius** [comment]
Oh that's a good catch! I didn't even notice this. I just dumped the OSC data and copied the strings from it for the mapping.

I've had a closer look at the data SteamLink sends and apparently they send both versions - with and without typo. I must've copied the typoed version when I was making the mappings:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/1ecea69d-09e1-41a9-b342-e989ee4dafe1)

From what I can tell, it's sending the exact same data.

I'll switch it to the non-typo one just to be sure.

**Comment by hazre** [comment]
Yeah that's what I assumed as well, since I saw other facetracking software also using the mistyped version originally and then switching to the correct one. Seems like a whoopsie on valve's end.

**Comment by ModernBalloonie** [comment]
> Oh that's a good catch! I didn't even notice this. I just dumped the OSC data and copied the strings from it for the mapping.
> 
> I've had a closer look at the data SteamLink sends and apparently they send both versions - with and without typo. I must've copied the typoed version when I was making the mappings:
> 
> ![image](https://private-user-images.githubusercontent.com/8838625/333901494-1ecea69d-09e1-41a9-b342-e989ee4dafe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTAyNjUsIm5iZiI6MTcxNjk0OTk2NSwicGF0aCI6Ii84ODM4NjI1LzMzMzkwMTQ5NC0xZWNlYTY5ZC0wOWUxLTQxYTktYjM0Mi1lOTg5ZWU0ZGFmZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDIzMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc5MTc1NTE5MzNiM2FiNjM4ZDlkZmQyYTJjMTQ3MjA1NDc3MWQ4NzY0MmNkMjJlZWIxMGE5NTM0YWE3YjEyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1KDyKbXHv4vewEOisY-KtDk9Esy48xOO101ShG4if1Q)
> 
> From what I can tell, it's sending the exact same data.
> 
> I'll switch it to the non-typo one just to be sure.

Unrelated but I find it funny that valve would make a typoed one just in case you spelt it wrong.

**Comment by hazre** [comment]
> > Oh that's a good catch! I didn't even notice this. I just dumped the OSC data and copied the strings from it for the mapping.
> > I've had a closer look at the data SteamLink sends and apparently they send both versions - with and without typo. I must've copied the typoed version when I was making the mappings:
> > ![image](https://private-user-images.githubusercontent.com/8838625/333901494-1ecea69d-09e1-41a9-b342-e989ee4dafe1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTAyNjUsIm5iZiI6MTcxNjk0OTk2NSwicGF0aCI6Ii84ODM4NjI1LzMzMzkwMTQ5NC0xZWNlYTY5ZC0wOWUxLTQxYTktYjM0Mi1lOTg5ZWU0ZGFmZTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDIzMjQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc5MTc1NTE5MzNiM2FiNjM4ZDlkZmQyYTJjMTQ3MjA1NDc3MWQ4NzY0MmNkMjJlZWIxMGE5NTM0YWE3YjEyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1KDyKbXHv4vewEOisY-KtDk9Esy48xOO101ShG4if1Q)
> > From what I can tell, it's sending the exact same data.
> > I'll switch it to the non-typo one just to be sure.
> 
> Unrelated but I find it funny that valve would make a typoed one just in case you spelt it wrong.

Again it seems like Valve made the typo first and then fixed it but they kept the misspelled version in for compatibility.

**Comment by Frooxius** [comment]
Switched the path in 2024.5.30.68, thanks!
