### ISSUE TITLE
SkinnedMeshs following the same bone appears out of alignment in screenshot

### ISSUE THREAD

**Issue by hantabaru1014** [Yellow-Dog-Man/Resonite-Issues#2102]
### Describe the bug?

When screenshot an avatar with separated SkinnedMesh for each clothing part, the parts of the avatar that should follow the same bone will appear misaligned, resulting in an unintended appearance.  
It is usually not visible out of alignment, either to me or to other players, but it often appears out of alignment in screenshots. (Sometimes they do not.)
Also, this phenomenon occurs not only with my particular avatar, but also with other avatars and other people's avatars.

### To Reproduce

Take a screenshot while wearing an avatar that follows the same bones but is composed of another multiple SkinnedMesh, such as clothing.
It seems to happen more often in screenshots taken by other people than by the person wearing the avatar. Also, the probability of this happening is higher when the fps of the person who took the screenshot is low.

### Expected behavior

SkinnedMesh misalignment does not occur and screenshots can be taken as they normally look.

### Screenshots

Unproblematic screenshots
![correct_visual](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/16133291/09eb2c2c-ffba-4f64-863a-63b9176304f6)

Screenshot of the problem. The socks have shifted and skin is visible.
![unintended_visual](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/16133291/18d571d7-34a4-442f-ab6b-3ae4d7269dd6)

Bone settings for the sock and skin mesh that are causing the problem in the screenshot above. (LowerLeg.L, Foot.L, LowerLeg.R, Foot.R are Slots with the same ID)
![2024-05-27 02 44 04](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/16133291/afa9f8bb-cb5d-4e5a-a980-d85c56cb0f4c)
![2024-05-27 02 44 30](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/16133291/b9bbee82-cc18-46a2-a965-a07f7382d006)

### Resonite Version Number

2024.5.24.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive ProEye, Quest Pro, Desktop

### Log Files

No useful logs, no mods used.

### Reporters

Resonite: baru3  
discord: baru14

**Comment by Electronus** [comment]
This looks like a duplicate of : https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/151 ?

**Comment by hantabaru1014** [comment]
oh, yes. I did not notice. Thanks!
