### ISSUE TITLE
Clicking the version number facet should copy it to the clipboard

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#211]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need to type out my Resonite version for bug reports manually.

### Describe the solution you'd like

Clicking the facet that tells you what version you have should copy said version to your clipboard.

### Describe alternatives you've considered

1. Not doing this. (I don't really see a reason for that though.)
2. Some fancy 'Report a Bug' button that'll bring up the Github bug submission page with stuff like the version number already filled in.

**Comment by shadowpanther** [comment]
I just open the latest log and get the version from it, as I'm going to look at the log anyways. Copying the current version from the facet would be helpful though.

**Comment by Gawdl3y** [comment]
The current version number is also available in the `Build.version` file in the game's installation directory, FWIW.

**Comment by The-furf-of-July** [comment]
Would be simple and helpful

**Comment by RyuviTheViali** [comment]
I've updated the version number facet to allow users to copy the version number to their clipboard, and requested a version bump for the facet so it will update for all users.

**Comment by Psychpsyo** [comment]
This has already rolled out for me:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/60073468/46b06ba4-d445-421d-8c13-1e7f68495635)

**Comment by Frooxius** [comment]
Facets have been updated in 2023.11.24.1379 for everyone. Closing this. Thank you!
