### ISSUE TITLE
Add ability to equip avatars by grabbing them through the context menu

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2111]
### Is your feature request related to a problem? Please describe.

when I'm showing new users avatars a common pattern I see is that they try to grab the avatar and equip it like a tool

### Describe the solution you'd like

Just like equipping a tool I would like to have the ability to grab an avatar and equip it through the context menu

### Describe alternatives you've considered

None besides equipping it with the laser but this still has the problem of new users trying to equip avatars like tools because it's a common pattern in Resonite

### Additional Context

if users are already familiar with the laser method a setting could be implemented to turn grab equipping off

### Requesters

@epicEaston197

**Comment by shiftyscales** [comment]
This could be a relatively harmless/easy tweak to make for UI/UX consistency across these systems.

Grabbing the tool is technically a redundant step however, as tools can also be directly equipped by clicking on them in the same way as the avatar can be.

So perhaps this could also be something that is better explained as part of the tutorial content as well?

Thoughts, @Frooxius @ProbablePrime?

**Comment by Frooxius** [comment]
I think we can just make this change, it's simple enough. That way you'll be able to do it both ways. 

I've actually seen this happen a few times too.

**Comment by epicEaston197** [comment]
> I think we can just make this change, it's simple enough. That way you'll be able to do it both ways.

also please make sure you do the avatar protection check

**Comment by Frooxius** [comment]
That's done automatically during the equip process - it doesn't matter how the equip is triggered.

**Comment by Frooxius** [comment]
Added this in 2024.5.28.94, thanks!

**Comment by shiftyscales** [comment]
An issue related to this means of equipping an avatar was discovered in #2533.
