### ISSUE TITLE
Enable "Use smooth turn exclusive mode" by default

### ISSUE THREAD

**Issue by Gawdl3y** [Yellow-Dog-Man/Resonite-Issues#2114]
### Is your feature request related to a problem? Please describe.

One of the consistent questions I hear new players ask is how to prevent themself from accidentally moving/turning while trying to move/turn with their right analog stick, or how to completely stop themself from being able to move with it. It can be very disorienting to turn or move when you're not expecting to, especially both simultaneously.

### Describe the solution you'd like

A simple mitigation for this is to enable the "Use smooth turn exclusive mode" setting by default. I believe that this is the more desirable default behavior for _most_ people since it mostly solves the issue of accidental turns/movements while still allowing the right stick to move you when you actually want it to. Given Resonite is fairly unique in the ability to use both sticks to move, attaching these training wheels (enabling this setting) out of the box should make getting used to this a much less jarring experience and prevent some additional up-front confusion and configuration for new players.

### Describe alternatives you've considered

The ability to completely disable movement on the right stick would possibly be desired by some, but that would likely require implementing a new way to "sprint" and possibly (?) break some existing content when disabled. Smooth turn exclusive mode solves most of the comfort issues people have while still maintaining the established behaviour.

### Additional Context

Vaguely related: #1769

### Requesters

@gawdl3y

**Comment by Frooxius** [comment]
Is this the movement behavior that a lot of new users would expect?

Given my experience with the VR stuff I play, this feels a bit counterintuitive to me to have this be the default behavior, but I'm not sure how common this really is for new players coming in and if just increasing the default deadzones would perhaps help more.

**Comment by Gawdl3y** [comment]
Judging by my own experience and what I hear from new players, yeah, I'd say it's most expected for the right (primary) stick to only turn and not move. As a quick check, I hopped into several of my VR games to confirm their default control scheme for smooth locomotion + smooth turning:

- **VRChat:** Left stick moves, right stick turns
- **Pavlov VR:** Left stick moves, right stick turns
- **Hot Dogs, Horseshoes & Hand Grenades:** Left stick moves, right stick turns, pulling back on right stick jumps (this is on the "classic twin stick" locomotion profile)
- **No Man's Sky:** Left stick moves, right stick turns
- **Half-Life: Alyx:** Left stick moves, right stick turns, pulling back on right stick teleports
- **Boneworks:** Left stick moves, right stick turns, pushing/pulling forwards/back on right stick stands higher/crouches
- **Phasmophobia:** Left stick moves, right stick turns

Anecdotally, out of all of the games I tried, none of them allow movement with the right stick by default, leaving Resonite as the only one that does. I don't think this is a bad thing at all, but it is probably unexpected by most new users. I wanted to check Rec Room as well since that's fairly popular, but I couldn't remember my account's password and didn't want to deal with the recovery/reset process, haha.

For a new user, this probably results in unexpected movement fairly quickly. That being said, even once a new user learns of the feature (most likely from someone telling them "hey, move both sticks together to move faster!"), the lack of exact muscle memory for that most likely *also* leads to unexpected turning while moving in this way. Smooth turn exclusive mode mostly resolves both of these issues.

**Comment by TisFoolish** [comment]
What you're describing is a workaround for people not being used to used to Res's odd movement configuration.  In my experience, most games default to snap turn and a lot of new VR users would get motion sick if smooth turn was the default.

**Comment by Frooxius** [comment]
@Gawdl3y Oh I see, thanks for the additional context! This helps quite a bit.

I wonder if it might be better to just allow option to disable the movement completely on the stick and have that be the default? That might make things more familiar to users.

@TisFoolish This is different, we are not going to have Smooth turn by default - that's actually something a new user picks during the intro tutorial. Default is Snap turn.

**Comment by FlameSoulis** [comment]
> @Gawdl3y Oh I see, thanks for the additional context! This helps quite a bit.
> 
> I wonder if it might be better to just allow option to disable the movement completely on the stick and have that be the default? That might make things more familiar to users.

Just... make sure to figure out what to do with the dev tools when they are equipped. The sudden change from normal to the forced tank on my non-dominant while using the Quest Pro is very infuriating.

**Comment by Frooxius** [comment]
> > @Gawdl3y Oh I see, thanks for the additional context! This helps quite a bit.
> > I wonder if it might be better to just allow option to disable the movement completely on the stick and have that be the default? That might make things more familiar to users.
> 
> Just... make sure to figure out what to do with the dev tools when they are equipped. The sudden change from normal to the forced tank on my non-dominant while using the Quest Pro is very infuriating.

If they are equipped, it'll get consolidated to a single controller - there's no other option available if something else ends up using the secondary. 

It could be potentially solved by reworking that so it doesn't need to use secondary, but that's a separate thing.

**Comment by FlameSoulis** [comment]
Ooh... actually, this just dawned on me... Resonite uses the second stick's forward for running... While other games generally use push down to run or push down to toggle run.

I'm not sure on what the best solution for that is, especially considering the Quest's limited inputs.

**Comment by Frooxius** [comment]
I've made changes in 2024.5.30.68 that should address this!

There's the separate daedzone and new "turn only" mode, which is default for new users. I think this should help the new users make things more familiar.
