### ISSUE TITLE
Swappable UI Anchor Toggle Hand

### ISSUE THREAD

**Issue by ImErinTheBunny** [Yellow-Dog-Man/Resonite-Issues#2118]
### Is your feature request related to a problem? Please describe.

Myself and a massive portion of Resonite use the right hand to open the dash and are now forced to swap hands if we want to use UI anchors.

### Describe the solution you'd like

1. Make the toggle control be primary hand based and use the opposite hand.
2. Selectable hand setting.
3. Throw it in with the editable keybinds update

### Describe alternatives you've considered

Deal with it I guess lol I don't think there is an alternative for this.

### Requesters

imerin.

**Comment by WayaShinzui** [comment]
Please! I mainly use my right hand for the dash so left would be perfect for toggling the new facets! 💙

**Comment by JackTheFoxOtter** [comment]
I just tried the facet anchors, I *really* like them, but this is definitely necessary for me.

**Comment by Frooxius** [comment]
Added in 2024.5.29.27! Thanks!
