### ISSUE TITLE
Make the reload all textures settings option grabbable

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2120]
### Is your feature request related to a problem? Please describe.

I want to have quick access to reloading all textures, but I can't grab it.

### Describe the solution you'd like

Making this button grabbable.
![2024-05-28 03 05 46](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/cf253060-08c4-4163-9a75-315ef6c14cdf)

### Describe alternatives you've considered

Making my own button (possibly)

### Requesters

ModernBalloonie

**Comment by Frooxius** [comment]
We cannot make this option grabbable specifically, because they all share the same template, but we can make all button action options grabbable.

This would need to be handled by the content team.

**Comment by RyuviTheViali** [comment]
I've added the ability for action buttons to be grabbable in the UI. Closing this, thanks!

![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/4b4ce48e-8056-4969-80d7-4512dd74a0ef)
