### ISSUE TITLE
Toggle display/disable individual facet anchors

### ISSUE THREAD

**Issue by amplified1** [Yellow-Dog-Man/Resonite-Issues#2125]
### Is your feature request related to a problem? Please describe.

Facet anchors could be integrated with avatars in way more interesting manners if the avatar could individually toggle the 10 anchors, and if the user had the option to have their facet anchors permanently on, not overriding the right dash button and allowing the state of the anchors to be managed entirely by the avatar.

### Describe the solution you'd like

Boolean on the facet anchor component that hides the associated panel.
Setting to force facet anchors to always be enabled and not utilize the controller bind.

### Describe alternatives you've considered

The anchors could be 0 scaled so that they become negligible. Which would work fine enough, but is jank. And you could rebind your dash buttons so that both route to the left dash, but then checking for controller inputs will be incorrect.

**Comment by JackTheFoxOtter** [comment]
I'm not sure I like the idea of having a setting to always keep them on, I'd rather be able to create an override for that per facet anchor.
I'm imagine a nullable boolean "override active" that when not null overrides wether or not the anchor should currently be active, while at null it sticks to the current state of the facet anchor toggle. This way you can both show them when anchor are hidden, but also hide them when anchors are shown, which should provide maximum flexibility. I definitely would like to make some of them appear automatically depending on how my wrist is positioned.

**Comment by shiftyscales** [comment]
Being able to selectively disable unwanted individual facet anchors would be a very nice QOL tweak for this feature. I like the view and hand-mounted facet anchors, but would prefer to hide the arm and palm ones by default.

I'd recommend these be exposed as settings so you can toggle on-off individual anchors from use.

**Comment by lxw404** [comment]
A global setting would be nice, however if the `AvatarFacetAnchor` component itself reacted to some active state, it would give a lot more customization allowing you to define per-avatar which are shown.  For example, some avatars you might have smaller/larger arms and prefer that the arm anchors are on/off, or like Jack mentions above, having the ability to show them only when looking at them or depending on orientation using ProtoFlux.

**Comment by Frooxius** [comment]
Added in 2024.5.29.27! Thanks!
