### ISSUE TITLE
Hide facet anchor boundaries outside of edit mode

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#2128]
### Is your feature request related to a problem? Please describe.

Unused anchors by default have a canvas visual that is always active while the anchors are active, even if the anchors contain no facets.

This adds extra visual clutter if you wish to keep the facet anchors open for prolonged periods of time.

### Describe the solution you'd like

I'd prefer the underlying canvas visual to only be visible in UI edit mode so that empty anchors, and the empty space not currently being used by facets is invisible, showing only the facets themselves, and not the anchors they are attached to.

Perhaps a setting could be introduced which allows the canvas visuals to always be visible, and otherwise they can fade out/be invisible while not in edit mode.

### Describe alternatives you've considered

In userspace, I've manually configured the material on my hand facet to be invisible- but this solution is hacky and I'd prefer a native option.

### Additional Context

Some feedback following up from my initial impressions while using facet anchors last night.

Video depicting my modified anchor configuration:

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/391c3fa8-3859-4ac4-9cf4-6aaf78b28f05

### Requesters

@shiftyscales

**Comment by Frooxius** [comment]
I don't think this is a good global or default change. The boundaries add extra visual structure, which can help (and personally I prefer it) and help discoverability.

I think it would be better to instead provide settings or other means to customize the visuals, so each user can adjust them to their liking.

**Comment by shiftyscales** [comment]
A setting sounds great for now to cover my needs. Allowing the visuals themselves to be customized could also be nice- but I see it more as a stretch goal.

**Comment by JackTheFoxOtter** [comment]
Hasn't this already been implemented at some point with the "Show Background" option, so this ticket can probably be closed? Unless I misunderstand it, in that case apologies!
![image](https://github.com/user-attachments/assets/3e0964bc-5a58-45b6-9bd9-5317ed31a381)

**Comment by shiftyscales** [comment]
Oop- yeah, this has been resolved for a bit. Thank you, @JackTheFoxOtter.
