### ISSUE TITLE
View facet anchors take laser priority over in-world inspectors

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#2129]
### Describe the bug?

View facet anchors take laser priority over in-world inspectors and make them considerably harder to use.

### To Reproduce

Attach facets to the view anchors and attempt to make use of an inspector- your laser will pass through the inspector in favour of the view facets, even while they are physically behind/rendered behind the inspector.

### Expected behavior

Inspectors should take priority over the view facet anchors as they are colliders that exist outside of the hierarchy of the avatar.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/cbc7e9cf-96d3-4777-803e-f38a76e242ce

### Resonite Version Number

Beta 2024.5.28.94

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 1

### Log Files

[SHIFTY-LAPTOP - 2024.5.28.94 - 2024-05-28 11_03_08.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15474495/SHIFTY-LAPTOP.-.2024.5.28.94.-.2024-05-28.11_03_08.log)

### Additional Context

Discovered this issue last night while testing facet anchors for the first time.

### Reporters

@shiftyscales

**Comment by Frooxius** [comment]
This isn't really a bug - the facet anchors intentionally take priority over worldspace things to avoid avatar interfering.

However I think we can change the behavior, since it's not as important for the view facet anchors to take priority, as the ones on the avatar where the avatar colliders can interfere.

**Comment by shiftyscales** [comment]
I see- I must have misunderstood your update notes, @Frooxius.

You had indicated:
> - Facet anchors are always a laser priority
> -- This prevents them from being occluded by the avatar colliders

Which suggested to me that it was only colliders under the avatar which were given a lesser priority- but upon re-reading it I can see where I was mistaken now.

**Comment by Frooxius** [comment]
> I see- I must have misunderstood your update notes, @Frooxius.
> 
> You had indicated:
> 
> > * Facet anchors are always a laser priority
> >   -- This prevents them from being occluded by the avatar colliders
> 
> Which suggested to me that it was only colliders under the avatar which were given a lesser priority- but upon re-reading it I can see where I was mistaken now.

The additional notes in release notes are always clarifications & examples. You can see that the first line says: 

> Facet anchors are **always** a laser priority

That's the key piece of info.

**Comment by Frooxius** [comment]
I've made the tweak 2024.5.29.27! Thanks!
