### ISSUE TITLE
Lasers stuck to the edge of view facet causes rapid strobing

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#2130]
### Describe the bug?

If you move your cursor towards the edge of the view facet in edit mode while trying to place a facet, it can cause the anchor/facet to rapidly strobe.

I suspect that the issue is that the laser is being momentarily moved off of the canvas and back onto it over and over causing the strobing.

### To Reproduce

With the laser stuck to the edge of the canvas- it will cause the facet placement visual, and sometimes the anchor itself to rapidly strobe green/white.

### Expected behavior

Facet placement indicators should remain stable while the laser is at the edge of the canvas.

### Screenshots

**PHOTOSENSITIVITY WARNING - RAPIDLY STROBING VISUALS**

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/c8a364ae-4f30-4d15-b59f-0b73858fa752

### Resonite Version Number

Beta 2024.5.28.94

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 1

### Log Files

[SHIFTY-LAPTOP - 2024.5.28.94 - 2024-05-28 11_42_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15474674/SHIFTY-LAPTOP.-.2024.5.28.94.-.2024-05-28.11_42_34.log)

### Additional Context

Discovered this last night while using the new facet anchors and had to warn my partner who is light sensitive.

### Reporters

@shiftyscales

**Comment by Frooxius** [comment]
Does this affect facets that are on hands as well? Or is it specifically the view one?

**Comment by shiftyscales** [comment]
I can test it shortly, but the view one was primarily the concern because it takes up so much of the user's screen.

**Comment by Frooxius** [comment]
It would be useful to know from technical perspective, because there's some differences in the view and & hand layout and how they're setup.

**Comment by shiftyscales** [comment]
Okay- did a quick test on all available containers including the dash itself for completeness, @Frooxius.

Dash top bar: Facet placement indicator stays solidly green suggesting the cursor never leaves the bounds of the canvas.
Dash main screen: Same as above
Hand container: Facet placement indicator disappears entirely- suggesting the cursor is entirely off of the canvas
Arm container: Same as above, can occasionally flash white when moving the facet between the outer edge and the usable facet space.
View container top and bottom: Laser sticks to edge and flickers on and off as reported above.

So the view templates are the only ones that severely cause the issue, but the hand/arm containers have their own issue since it makes placing facets at the edges more difficult because the cursor can drift off the canvas and prevent placement, causing the user to drop the facet rather than place it.

The dash itself represents the expected behaviour- as long as the cursor is stuck to the dash, the placement indicator remains active and doesn't disappear or strobe.

A quick recording of these results can be seen in the below video as with the prior video **PHOTOSENSITIVITY WARNING**:

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/d6f89e9a-a40c-4e6e-b51d-9f9a8ded68f6

**Comment by Frooxius** [comment]
This should be fixed in 2024.6.5.198, thanks! If this still occurs, let me know.
