### ISSUE TITLE
Re enable desktop view anchors

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2137]
### Is your feature request related to a problem? Please describe.

I was using desktop view anchors previously to make a HUD system and now it's gone

### Describe the solution you'd like

I would like the view facet anchors to be on in desktop mode

### Describe alternatives you've considered

None 

### Additional Context

The way I was doing it before was a little hacky but you could still do it through things like the user space inspector but the feature worked and advanced users could do it but they will be doing so risking their safety of their user space and that's up to them

also if you set up a view anchor setup in VR mode that would be entirely gone in desktop mode some users would still want to see their view anchors in desktop mode maybe a setting could be added to enable or disable this

### Requesters

@epicEaston197

**Comment by Frooxius** [comment]
Like I mentioned in the other issue, these are not designed for desktop and we have no plans in supporting them in desktop, they're a VR feature.

We do plan to add desktop facet overlay as well, that will be specifically designed for desktop, but we won't just re-enable feature that we can't support.

**Comment by epicEaston197** [comment]
> We do plan to add desktop facet overlay as well, that will be specifically designed for desktop, but we won't just re-enable feature that we can't support.

That's understandable I just hope it comes sooner than later as I was utilizing this feature
