### ISSUE TITLE
Buttons can no longer be clicked in inspector lists.

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#2139]
### Describe the bug?

The newest update seems to have extended the collider on the text next to inspector lists, making the two buttons inaccessible.

The text also has extra white space which may or may not be related.

### To Reproduce

Open an inspector and click at the list.

### Expected behavior

The button to work.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/6ae89203-f731-4953-9b4d-c547a5c8fbc8)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/f8ca6267-45e7-4685-82b5-d41405d1f672)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/89536622/70ad1a89-1900-4fca-a72a-c2e37fab1c96)

### Resonite Version Number

Beta 2024.5.29.27

### What Platforms does this occur on?

Windows

### Log Files

[BUFU - 2024.5.29.27 - 2024-05-28 21_48_32.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15477641/BUFU.-.2024.5.29.27.-.2024-05-28.21_48_32.log)

### Reporters

@RyuviTheViali

**Comment by Frooxius** [comment]
Fixed in 2024.5.29.130, thanks!
