### ISSUE TITLE
Inspector List Item Value Text Overlaps Buttons

### ISSUE THREAD

**Issue by RyuviTheViali** [Yellow-Dog-Man/Resonite-Issues#2140]
### Describe the bug?

With the recent update to allow list items in inspectors to have their little interaction button, the text area for the name of the list item is too wide and overlaps the buttons to open the (reference) field in a worker inspector, or full scene inspector.

### To Reproduce

Open an inspector, find a list with reference items, try to click on the left two buttons to open the reference in an inspector.

### Expected behavior

The buttons should function normally.

### Screenshots

Shown here is the Rect of the text field for a list item's name replaced with an image, showing it's area of influence.

![20240528204436_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/f65504c0-4443-4ce8-92b9-f38f78190e80)

### Resonite Version Number

Beta 2024.5.29.27

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[RYUVI-TOWER - 2024.5.29.27 - 2024-05-28 20_52_13.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15477675/RYUVI-TOWER.-.2024.5.29.27.-.2024-05-28.20_52_13.log)

### Reporters

Ryuvi (Discord: ryuvi)

**Comment by Frooxius** [comment]
Fixed in 2024.5.29.130, thanks!
