### ISSUE TITLE
Wiki: Missing licensing information & guidelines

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2148]
### Describe the bug?

When editing the wiki, there is a link under the edition box that links to copyright/licensing information which is empty at the moment.

Since I doubt any volunteer editors has the authority of deciding this, and that licensing guidelines on a wiki is a very important part, I'm opening this issue.

It would be the place to set what can and cannot be used on the wiki content-wise (thinking about some images or logos that might be under restrictive licenses).

### To Reproduce

Visit https://wiki.resonite.com/Resonite_Wiki:Copyrights

### Expected behavior

Wiki should have valid licensing guidelines.

### Screenshots

![firefox_qbyasmsMg6](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/dbed2408-fba7-45e9-9971-768e31cd4be6)

### Resonite Version Number

N/A

### What Platforms does this occur on?

Windows

### Log Files

N/A

### Additional Context

Footer of the wiki states:

> Content is available under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/deed.en), unless otherwise specified.

But it would be nice to have it on a proper page.

### Reporters

U-j4 | j4.lc (Discord) | User:J4 (Wiki)

**Comment by shiftyscales** [comment]
Seeking input from @ProbablePrime.
