### ISSUE TITLE
New User Badge

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#2149]
### Is your feature request related to a problem? Please describe.

``I'm always frustrated when`` I don't know if someone is a new user cause I don't know how much I might need to explain to them to help out with a question they're having.
But mainly I just think this would be neat.

### Describe the solution you'd like

New users should have a badge to indicate that they are new for the first few days of their account existing.

### Describe alternatives you've considered

1. Not doing this. (why?)
2. Making a tool or mod that shows someone's account age.

### Additional Context

Discord does a similar thing where it puts a little "I'm new here, say hi!" badge next to someone's name if they've recently joined the server:
![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/60073468/b6b6dfee-52ec-4c2d-8793-18a6a9071680)
(taken from the Resonite discord)

### Requesters

cameron5 on Discord, Psychpsyo on Resonite

**Comment by jae1911** [comment]
Already talked about in #1042

**Comment by epicEaston197** [comment]
<New users should have a badge to indicate that they are new for the first few days of their account existing.

I would probably not say there account existing it should be based off of how many days that they played and how long they've been absent let's say a new player logged in to their account played for a day and left for a few months I think in this case the user should regain the new user badge after that long of inactivity

**Comment by JackTheFoxOtter** [comment]
The other one was closed, so I assume this one will be as well. In general a new user badge is kind of pointing fingers at someone for being new. I'm not sure that's very beneficial. If a user wants help, they can seek it out. But they shouldn't be the one seeked out / put into spotlight by default.

> [...] cause I don't know how much I might need to explain to them to help out with a question they're having.

My response to this is: ask them.
"How much do you already know?" is usually a good beginning of any tutoring session.

**Comment by shiftyscales** [comment]
My stance as indicated on the previous issue:
> I don't think it is socially beneficial to single out new users to the platform

In addition to that, as highlighted- account age being new is not a good indicator of a person's experience level in general, their capacity to learn quicker/slower than others, etc.

A user could also take a break/hiatus from the platform and forgot things and be 'new' again.

There are a lot of reasons why the solution raised is not an adequate solution to the problem posed. It is better to instead talk to the user and ask questions about their experience level with whatever you are trying to help them with.
