### ISSUE TITLE
LNL-NAT Punchthrough Issues

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#2150]
### Describe the bug?

Currently we have a headless server running in Kansas USA but all out sessions are pulling a LNL-Relay ID from a relay that's the japan relay **_d4400e66fd5746f1bb249d60ef688495_** to be exact but it should be pulling from the closest relay

### To Reproduce

not a clue

### Expected behavior

connect to the closet relay or have the ability to select the relay to be used in resonite headless config as a static connection

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/85da45d4-2258-4bb2-ac2c-d89f0d582ae3)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/05dbb50d-94dc-4928-967e-5cae1d768d3c)

### Resonite Version Number

Beta 2024.5.29.27

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Desktop, Steam VR, Oculus

### Log Files

it's on a headless server that i have no clue how to pull the logs cus Kubernetes

### Reporters

t.o.s.t.e.r., SlyTheFloof, SkywindKitsune, USFN Team

**Comment by SlyTheFloof** [comment]
@skywindkitsune
just so your aware this is in github

**Comment by Frooxius** [comment]
Can you ping those servers from the location?

The system already tries to pick the closest bridge by pinging them and picking the one that's the lowest. Without logs we can't really do much here.

**Comment by SlyTheFloof** [comment]
> Can you ping those servers from the location?
> 
> The system already tries to pick the closest bridge by pinging them and picking the one that's the lowest. Without logs we can't really do much here.

Pinging with the ip of 173.208.148.66

Ping from server to **_resonite-bridge-eu-1_** (2748d8c5c6534475b68775cd510126c4)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/8a5bb797-a2f8-4e9b-bb34-e42ed56614d5)

Ping from server to **_resonite-bridge-jp-1_** (d4400e66fd5746f1bb249d60ef688495)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/2a03cf2b-1f3b-49b0-af63-d8b618a19791)

Ping from server to **_resonite-bridge-usw-1_** (f6774240aa2b426c8e70c2f3f8e19e39)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/47129711-928e-4045-8c1d-08b6f4930091)

Ping from server to **_resonite-relay-eu-1_** (b3ec331855d84ba7a6b6394a098bca43)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/20a66857-4580-4f77-ac7e-57dfcd6b2ac4)

Ping from server to **_resonite-relay-usw-1_** (f285cbef9eb441fbb990f355aac50496)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/32169985-30ef-4d8a-af75-3673e79f0441)

Ping from server to **_resonite-relay-jp-1_** (45ec7a50c85d4858b6a406867e8ca7c3)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/a1a8f2e7-d80c-48a6-a3e8-a9840148d786)

Ping from server to **_resonite-bridge-aus-1_** (f4145623eceb433d90dd08e947cc0fc9)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/38927dcd-0623-4bb4-8d66-1256a2fd4b03)

Ping from server to **_resonite-relay-aus-1_** (597f6220337d4300b068546c86cbeec1)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/a47f7247-0b06-4c88-9416-809ea8120095)

**Comment by SlyTheFloof** [comment]
still trying to find out how to pill the logs out for each of the pods unsure if i'll be able to

**Comment by bredo228** [comment]
It looks like there's some sort of source port randomisation in play in this case causing LNL to fail - this is the same way I've been causing punchthrough to fail in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2005

I'm the IP beginning in 103 - note the headless using source port 18911 while I'm connecting to it on 46153.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/7f751e35-3376-4602-9546-2195753f76f4)

This is in comparison to a session where LNL punchthrough was successful, where the ports on both sides of the connection remain the same.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/38fd6ad9-f4a7-4d5a-b9e9-32a0738df394)

In the case of this headless, it appears to be default Kubernetes behaviour.
