### ISSUE TITLE
Controllers not tracking after headset was in standby

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#2152]
### Describe the bug?

Using Quest 3 via Steam Link and SteamVR, after the headset went into standby and was brought back on, the controllers respond to buttons, but do not track at all and stay at 0,0,0.

In the SteamVR overlay, the controllers were tracking normally. Only Resonite itself lost controller tracking.

### To Reproduce

Use Steam Link
Take off the headset and let it go into standby
Put the headset back on
Realise that the controllers went into the floor, but still respond to button/trigger/grip input

### Expected behavior

Controllers to continue tracking normally

### Resonite Version Number

2024.5.29.130

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3 via Steam Link

### Log Files

[VIXEN - 2024.5.29.130 - 2024-05-29 22_48_37.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15491269/VIXEN.-.2024.5.29.130.-.2024-05-29.22_48_37.log)

**Comment by Nytra** [comment]
Dupe of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/927 I think

**Comment by shadowpanther** [comment]
> Dupe of #927 I think

Yeah, seems so. Thanks.
