### ISSUE TITLE
Head facet surface causes lingering collisions after the laser hits any facet on it

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#2153]
### Describe the bug?

Using the head/view facet anchor, after the laser hits any facet (becomes violet), moving it out of the facet causes the laser to hit some invisible points on the facet surface.

### To Reproduce

Place any facet on the head/view facet anchor
Point your laser at said facet
Move the laser away from the facet into the area of the facet anchor where there are no facets
Observe the laser staying userspace-violet and gluing to some random points

### Expected behavior

After leaving the facet, the laser should go back to the worldspace laser

### Screenshots

https://youtu.be/oEv2gxvoQYE
The facets are above the recording view, but the bug is visible.

### Resonite Version Number

2024.5.29.130

### What Platforms does this occur on?

Windows

### Log Files

[VIXEN - 2024.5.29.130 - 2024-05-29 22_48_37.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/15491288/VIXEN.-.2024.5.29.130.-.2024-05-29.22_48_37.log)

**Comment by Frooxius** [comment]
Fixed this in 2024.5.31.37, it should feel better now! Thanks!
