### ISSUE TITLE
Allow manual Inbound Port Forwarding

### ISSUE THREAD

**Issue by Dessix** [Yellow-Dog-Man/Resonite-Issues#2156]
### Is your feature request related to a problem? Please describe.

Right now, UPNP is, as far as I can find, unsupported for clients. Manual specification of inbound ports also appears to be unsupported. This causes many connections to be throttled through relays that could otherwise be routed directly and at lower latency.

### Describe the solution you'd like

As someone with plenty of experience forwarding ports for game connectivity, being able to do so and specify a port (or range of ports) for use by the game would be a way out of use of tunneling. It could be a matter of a simple options-menu entry asking for which port (or ports) to suggest for inbound connections.

As an added bonus, falling back to relays when inbound ports are exhausted can be not only a beneficial behaviour if the game requires multiple such concurrent connections, but a sensible way to build the default code path- an empty set of inbound ports immediately leads to attempting punchthrough and, failing that, usage of a relay.

### Describe alternatives you've considered

UPNP support would be a fantastic alternative. Several users have expressed concerns about the security of UPNP, but that's what firewalls are for, and this solution would not be for them. For everyone else, this would be an easy way to get less-technically-savvy users connected without relaying.

I've also attempted to support restricted-cone mapping ("Moderate NAT") (See [RFC 3489](https://datatracker.ietf.org/doc/html/rfc3489#section-5) for terminology definitions) on my networking gear, but Mikrotik's commercial devices do not support anything but symmetric or known-port exceptions. This is true of many other vendors' hardware as well.

### Additional Context
This issue simply requests port forwarding alone, which may be simpler to implement as a matter of preferred port selections when creating a socket. To open a new socket, try each one in the marked inbound range, catching any failures and incrementing; if the range is exhausted, fall back to the current code path. Report the selected port via the usual means.

Punchthrough was cool while it lasted, but is pretty much dead due to modern stateful NATs, with the only signs of a comeback being primarily the result of consoles lacking UPNP support.

Either solution to this problem may also save significantly on bandwidth costs (More frequent users will care more about optimizing their connection setup), while offering varying degrees of improved user experience through lower latency.

### Requesters

- Zoey `sourceress`
- Multiple help threads and new-user questions in the Resonite Discord server

**Comment by ProbablePrime** [comment]
We added this to a corporate branch of Resonite a few months ago, Im trying to get it back into the mainline Resonite branch but that might take some time.

As a reminder, mentioning past projects is against our guidelines for posting. I will edit your response to remove those references.

**Comment by Dessix** [comment]
> Past projects
My apologies, I must've missed that bit. As long as the intention is preserved, edits for compliance are appreciated ^^

As for the merges, if there's anything we at the community or individual levels can do, I'd be happy to contribute toward this functionality. Admittedly, that possibility is somewhat limited while Resonite remains closed-source, but maybe you need work done on LNL or similar dependencies?

**Comment by ProbablePrime** [comment]
We can double check requirements for sure.

The branch has port restrictions on incoming and outgoing connections, these restrictions can be:
1. Single: A single port (useful for some settings that only need a single port such as LAN Session announcement)
2. Range: A range of ports (useful for the underlying connection items on LNL, which uses 1 port per session)
3. Any: Any (Useful if you dont care and also the default, leaves it up to the Operating system)

Would that solve your issue?

**Comment by Dessix** [comment]
I think the range of ports one is going to be the most useful here, given the constraints. As for outgoing connection restriction, I'm not sure that needs to be exposed in the settings at the UI level, at least in an initial revision, so the MVP probably leaves outgoing control as a nice-to-have with only command-line options exposed for that bit of control? Requiring a game restart to register the change is also trivially acceptable, if that simplifies implementation significantly.

The only concerns I have about viability of simple port-restriction are due to #2005, as it may skip even attempting to use the port to connect. It may be worthwhile to warn if a relay is used while one of these options is selected, notifying either that the given range was insufficient to connect to the target due to too many sessions compared to port count, or (worse) because the port itself appears to not actually connect, leading to the relay fallback?

**Comment by ProbablePrime** [comment]
We now have port restrictions, they're a little simpler than when I originally described them. They were added in: 2024.7.10.1399.

The restrictions apply to both hosting and joining a session, each which take/consume one port.

You can read about the feature here: https://wiki.resonite.com/Startup_Config_File#Ports

I will close this issue and we can focus on #2005 where the rest of your concerns are. If there are gaps feel free to re-comment and i'll take a look.
