### ISSUE TITLE
"Save To Inventory" always says "You must be logged in to save items."

### ISSUE THREAD

**Issue by AlanMoonbase** [Yellow-Dog-Man/Resonite-Issues#2160]
### Describe the bug?

The "Save To Inventory" context menu button always says "You must be logged in to save items." and never changes like it should.

### To Reproduce

Try to save an item through context menu.

### Expected behavior

For it to say "Save To Inventory" when your in folders you can save to, and "You can't save items here." in folders you can't save to.

### Screenshots

![2024-05-30 01 43 29](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/110652548/1fdd458f-0f2f-464d-9411-830334a487c7)

### Resonite Version Number

2024.5.30.68

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

No unmodified logs can be provided at this time.

### Reporters

Moonbase (moonbase__)

**Comment by ProbablePrime** [comment]
Hey Luckily it still works, so this is just a visual thing for now 😆

**Comment by ProbablePrime** [comment]
Fix: https://github.com/Yellow-Dog-Man/FrooxEngine/pull/660

**Comment by ProbablePrime** [comment]
#2071 Hit me while I was testing this and so while I thought i was logged out, I was actually logged in :'(

**Comment by AlanMoonbase** [comment]
oooof yeah that sounds annoying

**Comment by LeCloutPanda** [comment]
Glad someone beat me to it. I didn't wanna have to right up a bug report but yeah my self and another user was experiencing the same issue.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/53411604/271bb9ef-ea6c-4c9a-a87d-82810a164e32)

**Comment by Frooxius** [comment]
Merged the fix in 2024.5.31.37, thanks!
