### ISSUE TITLE
Readd Controller Diagram Facet to the default home dash.

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#2166]
### Is your feature request related to a problem? Please describe.

Resonite's controls are rather unique and with the recent influx of users there's been a lot of questions about how to do even very basic functions like closing the dash. There is a facet in the Resonite Essentials folder that automatically displays the basic controls diagram for your detected platform, but it was removed from the dash during the transition from Neos to Resonite.

### Describe the solution you'd like

Re-add the facet to the default dashboard.

### Describe alternatives you've considered

Telling people in discord or in game still.

**Comment by Frooxius** [comment]
We don't plan to add this, because it actually has counterintuitive effect - it's a lot of information at once and new users tend to get confused by it more often than not - even when actively trying to figure out controls.

Our goal is to keep the dash Home screen as clean as possible.
