### ISSUE TITLE
Parts of Avatar Creator snap in wierd places when let go from being grabbed.

### ISSUE THREAD

**Issue by AegisTheWolf** [Yellow-Dog-Man/Resonite-Issues#2167]
### Describe the bug?

When grabbing the slider objects of the Avatar Creator in a world the objects snap in weird orientations, this mainly happens when you are not the host.

This affects the headset, hands, tooltips, grabspheres, and toolshelves.

This may be caused by the feature of the slider component "dont drive" is set to false.

### To Reproduce

Simply spawn an Avatar Creator and grab and move the objects that are not the menu around and release them to see if they snap in weird orientations.

Do this in these circumstances to compare its behavior:
- your own hosted session
- A world where you are not the host and the host IS focused in the world you are in
- A world where you are not the host and the host is NOT focused in the world you are in

### Expected behavior

The slider objects shouldn't snap in undesired orientations to reduce the frustration of new and current users of the platform when making their avatars.

### Screenshots

(I will update this issue with screenshots next time I'm in platform)

### Resonite Version Number

2024.5.30.68

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Vive Pro Eye

### Log Files

(Will provide logs if necessary for this issue when asked)

### Reporters

Other than myself I cannot recall specific users as this is just a common quirk most users of the platform experience when creating avatars.

**Comment by shadowpanther** [comment]
This is probably related to or caused by #399
