### ISSUE TITLE
Create split version of voice facet: One that's just for switching mode and another that's voice level indicator

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#2171]
### Describe the Underlying Issue

Right now, the voice facet preset is a single long bar, that includes both the voice switch and voice level indicator in one. This makes it difficult to place on the hand anchors.

### Expected Behavior

Create 2 new versions of the voice facet that's essentially a split. One that's just the voice buttons and another that's the voice level indicator.

Keep the original for now as well, but we can potentially switch to these two going forward as well.

**Comment by shiftyscales** [comment]
This would be nice to have. I had tried to place my voice facet on my left hand- but found the facet was too long/couldn't scale to fit onto the hand facet anchor.

**Comment by Frooxius** [comment]
Yeah, that's actually the main reason that led me to make this issue!

**Comment by gameboycjp** [comment]
I'd also like to see vertical variants too. I tried making one myself but I couldn't get things to work.

**Comment by epicEaston197** [comment]
I fixed this issue by just getting help to make a miniature version of the voice mode facet.
maybe something like this could work for a different version of the voice mode facet?
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/f73b1a7a-0dfc-4cca-bb2a-9fdae1e3b796)

**Comment by RyuviTheViali** [comment]
Okay, I have split the VoiceMode facet into two unique facets - `VoiceModeSelection` and `VoiceLevelIndicator`. These facets will auto-align horizontally or vertically based on if the facet is wide or tall (and it defaults to horizontal if square).

These have been added to the Facets folder in `Resonite Essentials/Facets/Templates` with the above names, alongside the combined `VoiceMode` facet.

![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/e432de84-677a-4654-96a3-30660835dd7d)
