### ISSUE TITLE
Make setting facets more adaptable to small size

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#2172]
### Describe the Underlying Issue

Right now, when placing Setting Facet Anchors and making them too small, they do not work too well - the text overflows and sometimes overlaps the UI elements (like the slider).

### Expected Behavior

Improve the facet templates for setting facets so they better adapt to different size - particularly making them smaller. 

Ideally once you get it small enough, the text itself should disappear.

The icon (if visible) should stay - we should look into adding icons to common settings to make them easy to identify, but that's a separate issue.

**Comment by RyuviTheViali** [comment]
I have adjusted all setting templates to dynamically hide elements when they're on a smaller-sized facets, so they look better at smaller scales.

![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/d2ef9644-4f10-42ac-8cb5-651f00649a25)

Closing this, thanks!
