### ISSUE TITLE
Make sociable notification sound

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2177]
### Is your feature request related to a problem? Please describe.

Right now it's using the same sound as the contact request notification which could be really confusing

### Describe the solution you'd like

I want a new sound created for the sociable notification

### Describe alternatives you've considered

None

### Requesters

@epicEaston197

**Comment by shiftyscales** [comment]
Assigning @LacyDoes - I have a concept in mind for what would work well here.

My phone has a "Hello" notification sound which is two short tones. I think it'd be a good starting place, and fits in well with the theme of "sociable" as a status/notification.

https://youtu.be/RJ-fEfyx9PM

**Comment by epicEaston197** [comment]
> Assigning @LacyDoes - I have a concept in mind for what would work well here.
> 
> My phone has a "Hello" notification sound which is two short tones. I think it'd be a good starting place, and fits in well with the theme of "sociable" as a status/notification.

I am surprised you're keeping this issue open and others even though that this feature is planned to be removed as a whole

**Comment by shiftyscales** [comment]
@epicEaston197 - Based on the feedback, I think with a few relatively minor tweaks, this feature can continue to exist. It does a lot of good for the community as an accessibility tool, even in its current form, and I personally think it should still exist.

I am collating feedback (both positive and negative) into an action plan of steps that can be taken to resolve a majority of the issues people have raised with the feature- there isn't too much that need be done.

**Comment by Frooxius** [comment]
This is now out in 2024.8.5.1341!
