### ISSUE TITLE
Contacts with notifications mistakenly appear below sociable status users

### ISSUE THREAD

**Issue by LeCloutPanda** [Yellow-Dog-Man/Resonite-Issues#2182]
### Describe the bug?

Users set to sociable appear at the top of the contacts list, if someone who isn't set to sociable sends a message to you they will still appear below the people marked as sociable(when receiving a message from someone who is set to offline their contact appears above people set to sociable)

### To Reproduce

Look at the contacts tab and see people set as Sociable sort higher then everyone else

### Expected behavior

Sociable and Online people mixed together with no priorities unless they send a message.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/53411604/c0164a70-6576-4461-ba9a-ed66aaf3a868)

### Resonite Version Number

2024.5.31.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

[GEOFF - 2024.5.31.202 - 2024-05-31 15_57_56.log](https://github.com/user-attachments/files/15508958/GEOFF.-.2024.5.31.202.-.2024-05-31.15_57_56.log)

### Additional Context

Even just having a toggle to that lets me have people marked as Sociable to be mixed in with those who are marked as Online would suffice to fix

### Reporters

[LeCloutPanda](https://github.com/LeCloutPanda) (Discord)
@knackrack615

**Comment by epicEaston197** [comment]
Hmmm
I actually prefer that from what I can tell people who are joinable use the sociable status more often so having joinable players at the top is preferable

**Comment by stawze** [comment]
> Hmmm I actually prefer that from what I can tell people who are joinable use the sociable status more often so having joinable players at the top is preferable

Contacts with new messages should be prioritised above Contacts with the Sociable status though, right?

**Comment by LeCloutPanda** [comment]
> Hmmm I actually prefer that from what I can tell people who are joinable use the sociable status more often so having joinable players at the top is preferable

Don't get me wrong yes it would be nice but I suggested having an option that let's us determine if they have priority or not and if they don't they just get mixed in with the online people.

**Comment by kulzae** [comment]
Imo it should be new messages first then socialabe then online

**Comment by shiftyscales** [comment]
Messages are/should be first already, @stawze @LeCloutPanda @kulzae. If they aren't being sorted at the top, that is a bug. I've editited this issue title slightly to make that a bit more apparent.

**Comment by shiftyscales** [comment]
This issue seems to have all that it needs to be looked into, @Frooxius.

**Comment by Frooxius** [comment]
Should be fixed in 2024.6.5.198! Let me know if it still occurs.
