### ISSUE TITLE
Cannot import .blend files on Linux Proton

### ISSUE THREAD

**Issue by Elaquen7** [Yellow-Dog-Man/Resonite-Issues#2188]
### Describe the bug?

When importing a .blend file on Linux using the Windows client through Proton, the import will fail.
Log file reports:
```Error importing file: BLEND: BLENDER magic bytes are missing, couldn't find GZIP header either```

The file can be opened just fine in Blender. It is not corrupted.
Happens both if the blend scene is gzip compressed or uncompressed.

The file command reports:
When compressed: ```GummigooBlend.blend: Zstandard compressed data (v0.8+), Dictionary ID: None```
Uncompressed: ```GummigooBlend.blend: Blender3D, saved as 64-bits little endian with version 4.01```

This happens with any .blend file.
FBX, STL, PNG or other file types work fine.
Only .blend files do not work.

### To Reproduce

Open the Windows version of Resonite on a Linux system with Proton and try to import a .blend file through the file browser.
After clicking "Run Import!" an error message will pop up immediately reporting an error while attemting to decode the file.

### Expected behavior

The file should import correctly and be placed in the world.

### Resonite Version Number

Beta 2024.5.31.202

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Valve Index

### Log Files

[SUPERSUSE - 2024.5.31.202 - 2024-05-31 19_23_27.log](https://github.com/user-attachments/files/15517123/SUPERSUSE.-.2024.5.31.202.-.2024-05-31.19_23_27.log)

### Additional Context

Error in log file occurs in line 606.

Proton misidentifies the system as Windows 10.
In reality the system is:
Linux 6.9.1-1-default 64bit
openSUSE Tumbleweed

### Reporters

Elaq

**Comment by Elaquen7** [comment]
If someone asks why I am not using the Linux native version, see #47, #69, #87, some textures have z-fighting (mirror button in default home world), and showing the desktop doesn't work anyway because Resonite does not interface with xdg-desktop-portals to acquire permission for pipewire screen capture.

**Comment by shiftyscales** [comment]
There are a few paths in which Resonite will search for a Blender installation by default. If you are running Resonite through Proton, you would likely need to include the relevant Windows binary/files for Blender in a path Resonite would be able to find it, @Elaquen7.

You can read documentation on how .blend imports work in the "Blender" section of this wiki page: https://wiki.resonite.com/3D_Model_Import

**Comment by Elaquen7** [comment]
Confirmed that Resonite needed a blender installation to process the blender scene file.
As the blender scene file format is open, I expected Resonite to be able to handle this format internally as is the case with other formats.

For reference, install the current Blender version with a tool like Bottles, then copy the ```Blender Foundation``` folder from ```drive_c/Program Files/``` to ```steamapps/compatdata/2519830/pfx/drive_c/Program Files/```.
This should allow Resonite to use Blender libraries for processing the .blend scene file.

**Comment by Elaquen7** [comment]
Feature request:
If decoding the .blend scene file fails, check if a drive is attached at Z: and see if a basic Linux file structure is present (e.g. /etc, /sys and /home). If these checks pass, it is likely that Resonite is running under WINE.
When the import fails, display a helpful message, telling the user to please install Blender in the current WINE prefix (and potentially directing them to this GitHub issue.)

**Comment by stiefeljackal** [comment]
> **Feature request**: If decoding the .blend scene file fails, check if a drive is attached at Z: and see if a basic Linux file structure is present (e.g. /etc, /sys and /home). If these checks pass, it is likely that Resonite is running under WINE. When the import fails, display a helpful message, telling the user to please install Blender in the current WINE prefix (and potentially directing them to this GitHub issue.)

You may want to submit that as a separate GitHub issue under the **_Feature Request_** type so that your request does not get lost and the conversation of that request can be had there.

**Comment by Elaquen7** [comment]
Feature request spun off into own issue at #2211. That completes this issue.
