### ISSUE TITLE
Allow sociable status notice toast/sound to be separately toggleable like other notifications

### ISSUE THREAD

**Issue by Azavit** [Yellow-Dog-Man/Resonite-Issues#2189]
### Is your feature request related to a problem? Please describe.

The sound seems to be one of the major issues people have with the new Sociable audio.
Having an option similar to the other notifications where you can get just the toast would be best.

### Describe the solution you'd like

An enum like some of the other notification systems that is set to only the visual notification by default

### Describe alternatives you've considered

Removing the feature (Please don't, this is a major accessibility feature)
Disabling notifications as a whole by default.

### Additional Context

Lots of discussion on this issue https://discord.com/channels/1040316820650991766/1246024940256366632

### Requesters

Azavit, lecloutpanda, whippersnatchpumpkinpatch, thebasementnerd, karasutengu, [hazre](https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/2186#discussioncomment-9618608), shrikealvaron

**Comment by ModernBalloonie** [comment]
Yes agreed. I love the socialable feature myself.

It's just if the notification was off by default, that would fix the issues currently with it.

**Comment by win189** [comment]
i think it should be Left the way it is change is change u can disable it every one always complains when something new comes in and they have to press a button to not have it the way there not used to

**Comment by shiftyscales** [comment]
> An enum like some of the other notification systems that is set to only the visual notification by default

I think it would be better to highlight/focus on this aspect of the request, so I am renaming this issue accordingly.

After reading through a bunch of feedback regarding the implementation of this feature, I have seen a lot of desire for users to be able to set it to toast only/audio only/neither/both similar to other notification settings.

If a user does not want the notification sound- they would then be able to turn it off as desired.

> The sound seems to be one of the major issues people have with the new Sociable audio.

If users dislike the current sound effect, there is a separate request to add a discrete notification sound for sociable here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2177

Likewise- if they wish to provide feedback on the sound itself as it is used in other notifications- they should open a separate issues highlighting their issues with it, e.g. if it has particularly harsh tones, etc.

**Comment by TrebleSketch** [comment]
I'm not sure how the current online users are organised but are those who are set as Sociable prioritised at all on the list?

If there would be messages sent, they would be just right below unread messages. Not sure if this should be in here or a separate GitHub issue.

**Comment by Frooxius** [comment]
Made this change in 2024.6.5.198, you can now configure it fully like other settings!
