### ISSUE TITLE
Allow the ability to force ourselves via the relay without restarting Resonite

### ISSUE THREAD

**Issue by sveken** [Yellow-Dog-Man/Resonite-Issues#219]
### Is your feature request related to a problem? Please describe.

Being Australian, alot of the times the peering that our internet provider provides to international hosts can actually be worse than what is available via the relay. 
Example directly connecting to the Resync lounge headless located in LA causes desync above 8-12 people normally in my case. 
However using a VPN to block the IP address of the headless, making LNL punchthrough/direct error and fail over to the relay i can stay perfectly synced with over 18 people.  This gap can widen further when the host is further away.

### Describe the solution you'd like

Either an option in the settings or some form of easy in game way to toggle or force the player via the relay for a given host/session instead of attempting a direct connection. 

### Describe alternatives you've considered

Currently the method i use is to block the IP address with a faulty wireguard config or firewall rule. Making my game unable to connect to the IP directly. However this involves finding out what the IP address of the host is, which is fine for static headless's but becomes a headache for sessions hosted by users with changing IPs. 

### Additional Context

Would just like to thank you for adding the extra Relays in the first place. This has made the game actually playable and interactable with larger international sessions and is an actual game changer.

**Comment by bredo228** [comment]
An improvement for this would also be the ability to select a specific relay - there are cases where using the closest relay to you isn't always the best option.

As an example of this:

Running a ping from Wellington, New Zealand - where I am - and Sydney, Australia - where my nearest LNL relay is located - to a server located in Los Angeles results in a similar round trip time - 135ms for the Spark connection, 138ms for the OVH connection.

The ping time between Wellington and Sydney is ~35ms on average in a best case scenario (fibre broadband on both ends, good peering) - for connecting to US hosts, I'd end up with that extra 35ms of latency vs going via the West Coast US relay.

Testing this last night by blocking both the Australian and Japanese relays through my router, I had about 1000 queued packets while using the Australian relay to connect to a populated headless located on US West vs none using the US West relay and upwards of 5000 while connected directly to the headless.

**Comment by knackrack615** [comment]
It's worth mentioning that the launch argument ``-ForceRelay`` does exist, but it would be very nice to have a UI option for it (including relay server selection).

Also, the relay doesn't pass-down queued messages. The queued messages you see in the session are Relay->Host

**Comment by sveken** [comment]
> It's worth mentioning that the launch argument `-ForceRelay` does exist, but it would be very nice to have a UI option for it (including relay server selection).
> 
> Also, the relay doesn't pass-down queued messages. The queued messages you see in the session are Relay->Host

Yup, which highlights the crazy difference in peering when the Sydney Relay still says perfectly synced vs my Sydney based ISP exit node or "POP". 

To comfirm the desync, My avatar grabbable system will refuse to work correctly, plus stuff like pictures etc don't show up for ages. or objects don't move. Going through the relay this is all still usable and pretty much realtime to what others are seeing. So i can comfirm the relay is helping.

**Comment by Crusher50** [comment]
Could improve #120

**Comment by ProbablePrime** [comment]
As we have the -ForceRelay option, is this now more asking for a better way to control when/how this applies?

**Comment by bredo228** [comment]
> As we have the -ForceRelay option, is this now more asking for a better way to control when/how this applies?

Pretty much

**Comment by sveken** [comment]
Yup. Wasn't aware of the -ForceRelay option which so far with the new Sydney relay i have bene able to just leave on and it has fixed alot of sessions for me. Its great. 

However turning it off/on requires a full game restart. Would be neat to have it in the settings panel like "Prefer Steam Sockets" is. Bonus if we can even select a preferred relay like Bredo mentioned.

**Comment by ProbablePrime** [comment]
Ok, I'm gonna update the title to make that a little clearer

**Comment by Frooxius** [comment]
This has been added in 2024.4.17.208 now! Thanks!
