### ISSUE TITLE
Add a way of emptying override entries in ValueUserOverride

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2192]
### Is your feature request related to a problem? Please describe.

There are situations to where I want to remove everyone's overrides currently you cannot do this without writing everyone's value but this means they can't see the default value without some trickery

### Describe the solution you'd like

I would like a method at the bottom of the component something like `RemoveAllEntries`
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/77e01733-1af8-44b1-aa93-8415357a1f93)

### Describe alternatives you've considered

Writing everyone's value to the default but this still doesn't fix my issue because if the default value is changed it won't update for anyone

### Requesters

@epicEaston197

**Comment by shiftyscales** [comment]
> I would like a method at the bottom of the component something like RemoveAllEntries

This was already requested in #974.

There is also #1013 which requests a mechanism to remove an override when the user leaves the session.

Thanks for the suggestion.
