### ISSUE TITLE
Resogrid Discord link redirects to Guidelines

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2202]
### Describe the Underlying Issue

The Discord Link in the Resogrid world redirects to the Guidelines

### Expected Behavior

Should redirect to Discord.

### Screenshots / Video

![Resonite_9uD7XokfPV](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76598503/4b169a57-a531-4cb4-a931-8a6d0a20bef6)

![](https://i.j4.lc/ShareX/2024/06/Resonite_pyp7E7zPHG.gif)

### Reporters

U-j4 | j4.lc (Discord)

**Comment by shiftyscales** [comment]
A minor oversight it appears- should be a trivial tweak, @AegisTheWolf @RyuviTheViali @RueShejn.

**Comment by RyuviTheViali** [comment]
This has been fixed - the link now references the correct link. This will take effect the next time the Resogrid worlds being hosted restart. Closing, thanks!
