### ISSUE TITLE
local home doesn't load/crashes

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2205]
### Describe the bug?

when i open Resonite my local home either doesn't open or crashes

### To Reproduce

1. Delete your cache
2. Delete local dot bin from the runtime data folder
3. Go to steam and verify game file integrity
4. Open Resonite
5. You'll notice that you're in a black void your local home will never load

### Expected behavior

my local home should load without any issues

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/2f125a9e-6e1b-48ab-b67d-10aeb17b1722)

### Resonite Version Number

Beta 2024.5.31.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.5.31.202 - 2024-06-01 19_31_27.log](https://github.com/user-attachments/files/15523657/DESKTOP-DAN95E7.-.2024.5.31.202.-.2024-06-01.19_31_27.log)

### Additional Context

before i cleared my cache it was working perfectly fine but when I wanted to delete it all of a sudden my local home would not load anymore I've tried reinstalling the game and everything and it just won't load I even tried unfavoriting my avatar to see if that was the issue but it still occurs

but this could have also been caused by me only deleting the cache folder and not both cash and data path
I'm also using this launch argument to move my data
`-CachePath "D:\Resonite Data Folder\CachePath" -datapath "D:\Resonite Data Folder\datapath"`
with this configuration if I delete only the cash path for some reason my local home doesn't load

### Reporters

@epicEaston197

**Comment by epicEaston197** [comment]
okay so I deleted both cache and data path and now it's working fine but I feel like I should be able to delete my cache without losing my login

**Comment by shadowpanther** [comment]
Sounds like you've cleared your Assets folder alongside with your Cache: #1414

**Comment by epicEaston197** [comment]
> Sounds like you've cleared your Assets folder alongside with your Cache: #1414

ohh yeah sorry I forgot to mention that I also deleted the assets folder inside the data folder as that also holds some section thumbnails for some reason4

**Comment by shadowpanther** [comment]
Well, yeah, you've deleted your local home world itself then. It wouldn't be recreated automatically unless you remove your database - then the Assets folder would be re-initialised.

**Comment by epicEaston197** [comment]
> Well, yeah, you've deleted your local home world itself then. It wouldn't be recreated automatically unless you remove your database - then the Assets folder would be re-initialised.

Wait the local home assets are stored in the data assets folder?

**Comment by shadowpanther** [comment]
It seems so, yeah. Not in the Cache - downloaded data from external sources goes there.
