### ISSUE TITLE
Audio Source Fequency Full Spectrum Equalizer Data Access 

### ISSUE THREAD

**Issue by ItsAlphaNeon** [Yellow-Dog-Man/Resonite-Issues#2210]
### Is your feature request related to a problem? Please describe.

Other social VR platforms allow access to audio source spectrum equalizer data, allowing for the utilization in audio reactive shaders (an example of such is AudioLink).

### Describe the solution you'd like

It would be nice to have access to equalizer audio data, even if it was minimal (Low, Mids, High, Intensity) so that these kinds of reactive effects could be replicated in Resonite. Whether these are exposed as float values to represent intensity, or if somehow the entire spectrum could be accessed and represented somehow, it would be useful.

### Describe alternatives you've considered

Currently, the only thing close to this that exists is the volume intensity of the audio sources volume. This leaves audio reactivity looking very simple, and very complex code has to be written for any kind of variety. Another "hack" solution to this problem is using a viseme analyzer to try to seperate certain kinds of noise for more variety.

### Additional Context

Discussion on the specifics would be helpful, and anyone who knows more about audio data feeds could comment on this, and see how it can be more properly implemented.

### Requesters

@alphaneon (Discord)

**Comment by shadowpanther** [comment]
This is the same as #48 which is covered by #567
