### ISSUE TITLE
Password change emails contan "/n/n" as a string==

### ISSUE THREAD

**Issue by EIA485** [Yellow-Dog-Man/Resonite-Issues#222]
### Describe the bug?

password change emails display show escape strings as text

### To Reproduce

change your password and look at your email in box

### Expected behavior

new lines are created instead of a "/n/n" string as text

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/17285570/5d7975a4-e46e-486e-b395-845e21a27b7c)

### Resonite Version Number

n/a

### What Platforms does this occur on?

Windows, Linux, Android / Quest

**Comment by Frooxius** [comment]
Thank you, fixed this in 2023.10.17.464!
