### ISSUE TITLE
Materials set to Alpha and Transparent do not render shadows

### ISSUE THREAD

**Issue by Epimonster** [Yellow-Dog-Man/Resonite-Issues#2220]
### Describe the bug?

Materials set to "Alpha" or "Transparent" do not render shadows cast on them.

### To Reproduce

Create any material and set its blendmode to "Alpha" or "Transparent", then cast a shadow on it. The shadow will not render on it.

### Expected behavior

Shadows should render on top of transparent surfaces as well as opaque ones.

### Screenshots

Demonstrations of this effect:

![2024-06-02 23 59 39](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/33250351-8882-4764-8a6c-99e86be6ecc6)
![2024-06-02 23 59 55](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/f72c9990-f5e3-4635-a649-4e30163dcae5)

### Resonite Version Number

2024.5.31.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[BEASTMANS-BOON - 2024.4.3.1170 - 2024-04-09 19_26_35.log](https://github.com/user-attachments/files/15527348/BEASTMANS-BOON.-.2024.4.3.1170.-.2024-04-09.19_26_35.log)

### Reporters

Gareth48

**Comment by Geenz** [comment]
This is a Unity limitation unfortunately.  This will not be fixed until after Sauce.
