### ISSUE TITLE
[Migration Issue] Some data textures are assigned srgbAlpha which leads to unexpected behavior

### ISSUE THREAD

**Issue by Epimonster** [Yellow-Dog-Man/Resonite-Issues#2222]
### Describe the bug?

Some data textures (namely the ColorMap of PBS_ColorSplat_Specular and Metallic) are assigned srgbAlpha on migration which leads to unexpected behaviors. This is the only map that I've observed migrating incorrectly but it may not be the only one.

### To Reproduce

Create a material like so on the old platform, using a colormap with all 4 channels:
![2024-06-03 00 24 46](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/35850937-7108-4465-9008-37ea05aece67)

Migrate it and get the following result:
![2024-06-03 00 24 37](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/e7a784dd-5600-4bb1-96c6-015947be8059)

### Expected behavior

This is the original old platform look:
![2024-06-03 00 16 46](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/e541d729-9aea-4ce5-bab8-ad8cdddcaea2)

This is the migrated look (notice the holes in the dirt):
![2024-06-03 00 16 21](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/0d18eb82-ee62-4c41-aeac-ac00d2df4b2d)

This is the expected look, achieved by setting it to linear:
![2024-06-03 00 28 24](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/98382c99-a436-4236-a0f0-cd17da7d47d7)

### Resonite Version Number

2024.5.31.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[BEASTMANS-BOON - 2024.5.31.202 - 2024-06-02 20_18_55.log](https://github.com/user-attachments/files/15527481/BEASTMANS-BOON.-.2024.5.31.202.-.2024-06-02.20_18_55.log)

### Additional Context

The texture maps are too large in size to provide over github, I will provide the migrated material in a public folder where all textures can be extracted and used:

resrec:///U-Gareth48/R-36E3A145301B4A54E003624321EECCB18EC68C82538B928544F5CE407AD6377A

### Reporters

Gareth48

**Comment by shiftyscales** [comment]
Seeking input from @Geenz - but I suspect this may be a similar case to your other issue #2223.

**Comment by Geenz** [comment]
This is why you have the ability to change texture color spaces after the fact.  We make a best guess first, and leave it to you to make adjustments when that guess is wrong.
