### ISSUE TITLE
[Migration Issue] Textures used as data textures and color textures are assigned linear which leads to unexpected behavior

### ISSUE THREAD

**Issue by Epimonster** [Yellow-Dog-Man/Resonite-Issues#2223]
### Describe the bug?

Textures used as both data maps and as color texture are assigned linear on migration leading to unexpected results.

### To Reproduce

Create a material (I chose unlit) and assign the same texture to the "Texture" and "Offset Texture" slot. Migrate the content and then observe that it is not rendering correctly.

### Expected behavior

In this very specific instance, textures would be duplicated and assigned relevant color profiles.

Below is the initial correct render:
![2024-06-03 00 45 34](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/3bfaf7a5-8a29-4dd9-a269-cee049bac429)

Below is the incorrect migrated render (notice that both are linear):
![2024-06-03 00 44 15](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/caa4c7e0-f979-4575-aeeb-9655f9202bb9)

Below is the modification to make it correct (achieved by duplicating the texture and assigning one to srgbalpha):
![2024-06-03 00 45 26](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/db4efca4-69bb-407d-8ced-fea575ac3c1f)

### Resonite Version Number

2024.5.31.202

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[BEASTMANS-BOON - 2024.5.31.202 - 2024-06-02 20_18_55.log](https://github.com/user-attachments/files/15527650/BEASTMANS-BOON.-.2024.5.31.202.-.2024-06-02.20_18_55.log)

### Reporters

Gareth48

**Comment by Geenz** [comment]
This is why we give you the ability to change the texture color space after the fact.  Some situations will call for linear, others will call for sRGB.  There are situations where you must do as you have described due to how color spaces work, and it's difficult to detect what the correct color space is supposed to be for both.
