### ISSUE TITLE
Make Online Status Icons Less Ambiguous

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#2224]
### Describe the Underlying Issue

Currently the icons in the default online status facet are somewhat ambiguous as to which one is active and this becomes especially apparent when minimized to just the icons only.

### To Reproduce

Resize the default online status facet to its minimal state showing only icons as below:
![Resonite_T2Wdc19sKV](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/52231149/075a7fee-aef4-40dd-b20b-7e1a40d5146b)

Observe that it is extremely difficult to discern which one of these statuses is active.  (Take a guess at which one is active in this screenshot then click below to reveal which one it is).

<details> <summary>Spoiler</summary>
<i>It was the Online (green) one</i>
</details>

### Expected Behavior

The icons should exhibit consistent behavior, either an outline appears to indicate it is selected when selected and all others do not have such outline, or some other indicator which is very clear upon comparison with other icons that it is the only possible one that is active at the moment.  Possibly even giving each icon a completely unique interior shape would help distinguish them and allow a separate active indicator to clearly indicate status rather than have multiple icons which look the same under different states.

### Reporters

LuxKitty

**Comment by Frooxius** [comment]
This is already being handled through this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2173
