### ISSUE TITLE
Generate a new Session Preview when switching to Publicly visible states

### ISSUE THREAD

**Issue by FroppyVR** [Yellow-Dog-Man/Resonite-Issues#2227]
### Is your feature request related to a problem? Please describe.

Users can accidentally violate the guidelines on Adult Content if after deleting the content they switch the session state too fast. The session preview will still show the world containing the content for awhile afterwards.

### Describe the solution you'd like

When the session is set to any state that can be publicly visible such as Anyone or Contacts, the session preview should immediately be thrown out and regenerated.

### Describe alternatives you've considered

It might be possible to just hide the preview until the next refresh? But that's not ideal.

### Requesters

Froppy, Rabbuttz and the moderation team

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius or @ProbablePrime - this recently came up as a moderation concern.

**Comment by Frooxius** [comment]
Made the change in 2024.6.5.198, thanks for report!
