### ISSUE TITLE
Inventory Shortcut Component/Facet

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#2232]
### Is your feature request related to a problem? Please describe.

With the new facet anchors, it'd be extremely convenient to have buttons that either spawn items or open my inventory to a folder through these anchors

### Describe the solution you'd like

Introduction of facets for inventory shortcuts, items will spawn the linked item, folders will open the corresponding folder.  This will require introduction of appropriate component(s) as well.  I am currently of the opinion that these should be strictly user space/facet features, and seen more as an extension of the current inventory, rather than as an introduction of sanctioned cloud spawning

### Describe alternatives you've considered

Could be re-created with cloud spawnning or mods, but these are not ideal solutions, especially since neither are official at the time

### Requesters

zangooseoo

**Comment by Frooxius** [comment]
This is actually going to be handled by the Inventory UI rework, which will rework the UI as as a set of modular components, data feeds and facets: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1119

More generally, the goal is to rework all major UIs to these new systems, which will make it possible to place them and versions of them as facets for quick access like this.
