### ISSUE TITLE
multiply string node has incorrect "+" label

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#2240]
### Describe the bug?

the multiply string node says "+" on it's label. it should probably have "*" or just "Multiply"

### To Reproduce

spawn multiply string node

### Expected behavior

it has  "*" or "Multiply" label.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/a44b2ca6-34db-4318-862e-58163f969fac)

### Resonite Version Number

Beta 2024.6.5.198

### What Platforms does this occur on?

Windows

### Log Files

n/a

**Comment by Nytra** [comment]
Duplicate https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/194

**Comment by art0007i** [comment]
I searched for "multiply" when looking for duplicates but that issue did not show up, thanks github
