### ISSUE TITLE
Users with Quotation marks in name unable to change username

### ISSUE THREAD

**Issue by DanteTucker** [Yellow-Dog-Man/Resonite-Issues#2249]
### Describe the bug?

While it's possible change to a username with a quotation mark, Users with quotation marks (") are unable to change their name due to parsing of the /changeUsername command determining the command has the wrong number of parameters.

This issue can occur accidentally as it's easy to mistakenly add a leading or trailing quote when changing username. 

### To Reproduce

Change your username to have a leading or trailing quotation mark.
Attempt to change your name to anything else.

### Expected behavior

Command should be successful. Either by parsing the current name correctly or allowing alternate formats like UserID in place of current name.

### Resonite Version Number

Beta 2024.6.5.1084

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Log Files

N/A

**Comment by Banane9** [comment]
Have you tried escaping the quote with a backslash? Like: `username\"`

**Comment by DanteTucker** [comment]
@Banane9 
I can't test if that will work as expected due to the week delay. Which we have no ability to override at this time.

**Comment by Banane9** [comment]
> I can't test if that will work as expected due to the week delay. Which we have no ability to override at this time.

Oh? I thought the command was failing trying to change it - could you ellaborate on the timeline?

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius or @ProbablePrime.

**Comment by ProbablePrime** [comment]
Will take a look

**Comment by DanteTucker** [comment]
@ProbablePrime Sorry, this isn’t actually valid. I was too laser focused on the quotation and something unrelated but obvious slipped by me. Sorry if you spent any time on this.
