### ISSUE TITLE
Undo Manager List is easily manipulated. 

### ISSUE THREAD

**Issue by VirgilCore** [Yellow-Dog-Man/Resonite-Issues#2252]
### Is your feature request related to a problem? Please describe.

The Undo Manager List in Resonite stores a list of all actions a user in a session has made. The list is stored on a hierarchy of slots on the world root. A consequence of this is that the Undo List is easily modifiable and easy to falsify. See attached images for examples. If a bad actor was to, for example, make the list display that a user had spawned a dangerous item, and sent that to moderation, it could be mistook for being real, and the user could be unfairly punished. In the example image, fake slots can be added to the Undo Manager list, showing a user performing an action, even if they were never in the session to begin with.
![20240606075107_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76923632/89576af5-525c-4215-8961-b6e40da3f9da)

I tried to submit this as a Security Report but was told to make a Github Issue instead.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76923632/34bae245-959e-4bc7-8648-eaa3eb39aab3)

### Describe the solution you'd like

the Undo Manager should not be editable like this. It is easy for a bad actor to make a false listing in the Undo Manager to frame a user for an action they never took.

### Describe alternatives you've considered

Moderation should not trust a screenshot of the Undo Manager as proof of someone doing something wrong, given how easily someone can make a false report.

**Comment by Draconas** [comment]
this should never be considered proof for moderation issues when one can literally drag and drop a single thing into your undo manager like that

**Comment by ProbablePrime** [comment]
While I am aware of the moderation concerns here, I can't speak for them.

However, the reason this was de-prioritized as a security issue was because once you're a builder and able to modify items in here that's an intended application of the platform as its design currently stands.

As you've correctly attributed, this then becomes a feature request to change the design of the undo system and as a feature request I agree with your concerns and feel #1103 would probably help here.

**Comment by Frooxius** [comment]
I've talked with moderation about this.

The main thing here is that Undo Manager is not intended or designed as a moderation feature. However the moderation team will make use of all available sources of evidence to corroborate a story. It is understood that evidence provided by the undo list is not immutable, and for the purposes of investigation may be considered analogous to additional testimony or attaching a log file - which can be similarly falsified. 

The Undo list is working as intended here and we do not have plans to make any modifications to it - it's designed to be a builder & helper tool and for that its mutability is important factor. If we wanted to make it into moderation tool, it would interfere with its functionality.

If there's a need for stronger evidence for moderation, we can consider those as dedicated features designed for that. but for the Undo manager I'm going to close this issue.

Thank you for your report!
