### ISSUE TITLE
Random Unity Crash

### ISSUE THREAD

**Issue by GearBell** [Yellow-Dog-Man/Resonite-Issues#2254]
### Describe the bug?

I was standing still just reading something alone in my session when I got a unity crash. I do not know the cause.

### To Reproduce

Unfortunatly because of its randomness I cannot reproduce it - however this did take place in the same map I submitted my last random crash in. The map is unpublished and a work related map so I cannot publish it. The crashing became consistance since 2 weeks ago, beforehand no one ever crashed there.

### Expected behavior

Not crashing - unknown cause so unable to identify what item should be doing what.

### Resonite Version Number

2024.6.5.1084

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[DESKTOP-SH9HHOE - 2024.6.5.1084 - 2024-06-07 11_08_22.log](https://github.com/user-attachments/files/15744471/DESKTOP-SH9HHOE.-.2024.6.5.1084.-.2024-06-07.11_08_22.log)
[error.log](https://github.com/user-attachments/files/15744487/error.log)
[Player.log](https://github.com/user-attachments/files/15744488/Player.log)

### Additional Context

The map consists of 3 nonfunctioning prop cars on Spinner components, a world radial menu option to turn off the lights, 2 UserDistance based culling mirrors, and a vehicle-hoverboard. There are 9 studio buildings all empty aside from a single pointlight culled by being inside/outside the building. No new adjustments to the map have been made since 3 months ago.

### Reporters

GearBell

**Comment by shiftyscales** [comment]
At a quick glance, I suspect that this might be the same issue as #2134. From what I can gather from it, it seems like a fairly generic Unity error- I don't really see anything specific of note in any of the provided log files that points me in a particular direction as to what may be causing it.

> this did take place in the same map I submitted my last random crash in

All the more reason that I suspect that this is probably the same issue. I'm going to close this as a duplicate- we can continue to look into this as possible on your prior issue.

If possible- it would be helpful if you stripped down a copy of the world as much as possible to the bare minimum setup required to still cause the crash. But without replication steps it's not likely we'll be able to do much with this one at this time.
