### ISSUE TITLE
(Resonite Package) An option to add Avatar Protection to an avatar that's specific to the user that imports the Resonite Package.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2255]
### Is your feature request related to a problem? Please describe.

I have been thinking about the resonite package as of recent because I have been wanting to use them to distribute avatars, because I sell them on gumroad, and I was thinking of an easy and less jank way besides taking apart a component selector and having you push that button before you save it.

### Describe the solution you'd like

An option so you can export a resonite package with automatic simple avatar protection applied to it on import. Mostly why I want this is because of new users that may have bought said avatar, and they don't know how to use an inspector.

### Describe alternatives you've considered

Taking apart an inspector/component selector and only showing the "SimpleAvatarProtection" button when you import the resonite package so you can just click that button to add the protections.

### Additional Context

This github issue is related to a future feature but I wanted to suggest it xP

### Requesters

ModernBalloonie

**Comment by XDelta** [comment]
Some of this has been mentioned on the issue for .ResonitePackage already for what to do with avatar protections and how they are setup https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/950#issuecomment-2155183605

**Comment by shiftyscales** [comment]
If you have feedback regarding #950 I would recommend either commenting on that issue, or if it is a broader discussion (e.g. thoughts about potential issues with it) - you could open a discussion instead.

As has been highlighted above- that use-case has already been considered, @ModernBalloonie. As such I will be closing this as a duplicate.
