### ISSUE TITLE
Unity to Resonite Avatar Conversion Tool

### ISSUE THREAD

**Issue by rabbuttz** [Yellow-Dog-Man/Resonite-Issues#2258]
### Is your feature request related to a problem? Please describe.

Currently, converting avatars set up in Unity for VRChat to Resonite is a highly complex and frustrating process. Users who have already configured their avatars for other platforms face significant challenges when reconfiguring them for Resonite. This involves learning new setup methods, which can be a major burden. Specific problems include:

- Broken Exports: When exporting avatars using Unity’s FBX Exporter, the contents often become corrupted.
- Limitations of VRM Format: While VRM performs better than FBX, it still requires manual conversion to .glb for Resonite, and textures often don’t carry over.
- Manual Re-setup: Even after using these methods, users still need to manually set up the avatar in Resonite. While Resonite’s setup is intuitive, the ease of use is not apparent to external users, which is a significant disadvantage.

Additionally, many users customize their avatars in Unity, including clothing changes and other modifications, using tools like Modular Avatar. Properly exporting these customized avatars is currently very difficult, and users often have to resort to editing in Blender. This adds to the complexity and discourages users from adopting Resonite.

### Describe the solution you'd like

I strongly propose a feature in Unity that allows users to easily convert VRChat-ready avatars to Resonite avatars and export them as ResonitePackages. This feature should include:

- Preservation of Existing Settings: Maintain Humanoid settings, Material settings, height, and eye position while converting avatars to Resonite.
- Simple Drag and Drop: Allow users to export the avatar as a ResonitePackage that can be used by simply dragging and dropping into Resonite.
- Intuitive Operation: Maintain the intuitive avatar setup process of Resonite while enabling easy conversion of pre-configured avatars.

This feature would make Resonite much more accessible and appealing to both new and existing users.

### Describe alternatives you've considered

Several alternatives have been considered, but each has its issues:

1. FBX Exporter: Often results in corrupted avatar content and is unreliable.
2. VRM Format: Requires manual conversion to .glb, and textures are often lost in the process.
3. Manual Setup in Resonite: Requires users to learn and redo the setup process, which is a significant barrier for new users.

### Additional Context

This feature is especially beneficial for users who customize their avatars in Unity. Many users frequently change clothing and other features using tools like Modular Avatar. Currently, exporting these customized avatars correctly is very challenging, forcing users to resort to Blender for manual edits. If Unity customizations could be directly applied to Resonite, it would greatly increase user convenience and attract more users to Resonite.

Moreover, developing this feature would lay the groundwork for future development of tools that allow content export from Unity to Resonite, enhancing long-term usability and convenience.

### Requesters

Rabbuttz

**Comment by kazu0617** [comment]
Considering the cost of maintaining the tools, I think it would be better to have a community tool that converts the ResonitePackage to that format after it is provided. It may be usable when Resonite provides the tool, but I recognize that it will be difficult to update it according to both VRChat updates and Resonite updates.

**Comment by kulzae** [comment]
It would probably be okay if it cut off at baseline features rather than attempting to stay updated with whatever vrc adds. Meaning it brings in rigging, meshes, and textures and maybe a few other things. You can't really convert stuff like physbones 1 to 1 anyways

**Comment by Frooxius** [comment]
We already have issue for this here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/6

The Unity SDK would allow converting not only avatars, but any other objects and worlds into Resonite easily and be extensible. If you're interested in that functionality, I recommend upvoting that issue.

I am closing this one as duplicate, since it would be covered by the more generic Unity SDK.
