### ISSUE TITLE
Redesign & rework type serialization & negotiation

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#2264]
### Is your feature request related to a problem? Please describe.

Currently the type serialization in FrooxEngine, both for realtime synchronization and persistence is built on top of .NET's own typesystem. However this presents a number of problems:
- Compatibility issues between .NET Framework/Mono and modern .NET - some core types (e.g. int, string...) have been moved
- Clients can try to introduce types that aren't compatible/allowed within a session, resulting in crash
- Moving/renaming certain datatypes can be difficult, requiring hacky methods to preserve compatibility of old content

### Describe the solution you'd like

Implement more custom system for handling datatype encoding & add explicit type negotiation & validation to session communication.

This system will recursively handle any generic types - validating and processing each type within with the custom system.

Primitive datatypes will be encoded much more efficiently with custom handling, to ensure that they are compatible between different runtimes and don't change over time.

Other datatypes will be processed & validated in a similar manner, with full support for compatibility attributes to adjust any types that were moved or renamed.

### Describe alternatives you've considered

N/A

### Additional Context

This is a pre-requisite for moving to .NET runtime. With the initial step being switching the headless: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2265

Additionally this will heavily improve support for plugins and mods, as it will lay part of groundwork for ensuring that clients with mods and plugins can remain compatible with ones without them - they will simply be forbidden bringing datatypes that aren't supported by all clients within the session.

**Comment by Banane9** [comment]
> Additionally this will heavily improve support for plugins and mods, as it will lay part of groundwork for ensuring that clients with mods and plugins can remain compatible with ones without them - they will simply be forbidden bringing datatypes that aren't supported by all clients within the session.

Sounds great! Fully approve :>

**Comment by gameboycjp** [comment]
For clarification, will this implicitly improve plugin compatibility on its own, or will type negotiation still have to be worked on further before that improves?

**Comment by Frooxius** [comment]
@gameboycjp Depends how exactly it's implemented. It'll help at very least to prevent issues when you try to introduce types into the data model that aren't supported by the session - you'll not be allowed to and if you try to force it, it'll disconnect you.

The other part will be adding a mechanism that communicates which assemblies (and thus which types) are allowed in the session, instead of using a single compatibility hash.

That will make it easier so you can just load additional plugins and not break the compatibility with the other branches, but I'm not 100 % sure if that will get implemented as part of this yet.

**Comment by Frooxius** [comment]
This is now out in 2024.7.11.1293! This marks the first step done towards performance optimizations, moving headless to .NET is next! :D
