### ISSUE TITLE
Component: Driving a number of active states to be active

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#2269]
### Is your feature request related to a problem? Please describe.

Sometimes you want to reveal your content one part at a time until everything is shown.
Common examples include:
- forms that reveal the next question after the last one has been answered
- animating multi-step processes, i.e. dramatically switching on large-scale flourescent lighting

### Describe the solution you'd like

I can imagine an extension of `BooleanSwitcher` to not just enable the indexed target but also all previous or following elements.

If both previous and following elements can be enabled it may be helpful to add an option for the indexed target itself.
This will allow behaviours such as "up to (exluding)" and "all but".

This extension would work well in combination with a `ValueGradientDriver` driving the `ActiveIndex` property.

### Describe alternatives you've considered

An alternative would be a new component that is similar to the `BooleanSwitcher` but has two indices "from" and "to".

**Comment by Zyzyl** [comment]
Wouldn't using an Animator be the most generic solution here? I appreciate those are hard to make in Resonite right now though, but AnimJ is an option

**Comment by shiftyscales** [comment]
A pretty common pattern I see is users that make use of the ValueGradientDriver to activate/deactivate/change the value of various things based on the "progress" as well- similar to AnimJ in concept- but set-up entirely in-game instead.

**Comment by art0007i** [comment]
the idea of this request is ease of use. the request mentions that ideally it should be similar to BooleanSwitcher. that component has an auto add children option making it super easy and convenient to use. things like ValueGradientDrivers and Animators are quite tedious when you have to manually add them on each element.

I've needed this before and I ended up using a protoflux solution but it is not ideal at all, if I could replace all that with a single component would be really nice

**Comment by shiftyscales** [comment]
I'm aware- Frooxius has already assigned himself to it- I was just giving additional context for workflows a component like this could potentially improve, @art0007i.

**Comment by Frooxius** [comment]
I think this is simple enough change that's also very generic, so I've just added it to my list.

**Comment by Nytra** [comment]
art0007i and I figured out a way to do something like this before. This is how to enable a number of booleans up to (but not including) a given index in ProtoFlux.

![2024-06-10 22 02 13](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/fbf28639-6224-4b48-b8ff-817345c35ecb)

**Comment by Frooxius** [comment]
I've added this in 2024.6.24.1317! I've expanded on it a bit to make it more flexible:

Added a number of activation modes to BooleanSwitcher to provide more flexibility (based on request by @mpmxyz, issue #2269)
-- AtIndexOnly (this is the original mode, activates item only at the index)
-- AllButIndex (the item at index is deactivated)
-- IndexAndBefore (all items all the way to the index are activated)
-- IndexAndAfter (all items at index and after it are activated)

Thanks for the request!
