### ISSUE TITLE
External/ Assets Storage/Retrieval

### ISSUE THREAD

**Issue by AdmiralGhoster** [Yellow-Dog-Man/Resonite-Issues#227]
### Is your feature request related to a problem? Please describe.

The feature i bring forward if for External storage and retrieval of prepacked assets files (such a world, avatar, or object) from a url based location rather then from the built in storage system. This feature can be use to allow players to preview avatars before getting the final model (for avatar commissions) without actually having the raw files before transaction is complete. In addition, this feature could be used with an hosted webserver to allow only certain players to load the avatar (by using the player  uid passed in the uri to the server to block/send said file), which will help with players having custom private avatars that are available only to them/specific friend groups. As well as having private avatars, this feature would allow players to have many more avatars, or make a free account and have 20+ avatars saved without running into a storage bottleneck (increasing interest and possibly convincing said player to support the application and team behind it)

For worlds, this feature can be used to update specific part of the world without having to join the world and resave it to the cloud, and with a checking system, all active worlds that use this external asset can be updated live without having to relaunch the world.

### Describe the solution you'd like

**For exporting to external hosting site:** Add a node into the system that takes in a name(string)[file name], playeruid[for registering package to player] and the root item you want to pack. when impulsed a dialog box will pop up prompting the player with useruid given if the file is a world, object, or avatar (or ect). If world, a new dialog will ask what should happen if the file isn't available (Show default home, show blank world, close instance, ect)_[this info gets saved to the cloud inventory within the item  and is used when calling up the assets]_ for an avatar file , show a dialog for if the assets is not retrievable what should happen ( use default player avatar or  use fallback Resonite avatar) _[this info gets saved to the cloud inventory within the item and is used when calling up the assets]_ ( should an object fail to load, just show an error).
once this step is done, show a packed item to user for them to export from Resonite, have them upload it, then provide a url to access said files _[this info gets saved to the cloud inventory within the item and is used when calling up the assets]_. the dialog then checks the url to see if the file in Resonite and at the url are the same then saves a node and item card to the player inventory( Resonite folder/external assets/..) which refences that external object and can be given out to other players.

** for importing from external site:** add a node that takes in a player uid, a external node file uid( a obfuscated url reference), and an impulse. The player then gets prompted to allow this domain to open urls/files (similar to url domain node, but with an anonymous option) and if the file is there, a builder will import the file into the world, unpacking it and assembling it as it was. (the passed url contains the player uid_{unless player request anonymous}_ for whitelisting/blacklisting use**{example.com/avatar1.frooxpack?uid=xxxxxxxx}**)

### Describe alternatives you've considered

stop crying about it and just support the app/game via patreon to get more storage. (for $12 a year you get 5gb rather then 1gb)

or add a whitelist/blacklist node of some kind.

### Additional Context

this may cause a issue if an avatar creator sells avatars and hand the client a external reference file/node. then they can delete said file from external host, also there is no way to protect the assets from being saved to the clients account. there's problems, but i figured i would throw it out there and see what sticks.

**Comment by kazu0617** [comment]
@AdmiralGhoster 
I think it is interesting as an idea.
However, this feature is a so-called "mega" Issue, and it needs to go through several steps if it is actually to be achieved to some extent or completely.

Can you break down those elements first?
For example, let's break down the first one, "cloud storage" only:

- [ ] Allow local saving: this can actually already be done, either by saving to the Local world or by saving the world orb locally so the item/world is saved locally. You can also add a local directory to your inventory and save there by using the ["LocalStorage" mod](https://github.com/art0007i/LocalStorage).

- [ ] Access to external resources such as Dropbox: this certainly does not exist at this time.
       LocalStorage can only be specified in one location, and it is not possible to directly access the cloud, so there is a performance loss.

By breaking it down like this and tying the Issues together, we might be able to set this MegaIssuga as a somewhat achievable goal without being left out (I say "might" because I'm not a developer myself).

**Comment by AdmiralGhoster** [comment]
@kazu0617 i completely agree with you about this accidentally being a mega issues (aka multiple issues wrapped into one request) i just was thinking about it and ran out of time to clean it up before heading to work.
As such, i've updated the request to be solely about the packing and retrieval of assets on external sources along with better and more concise application of the feature. 
`< Access to external resources such as Dropbox: this certainly does not exist at this time.
LocalStorage can only be specified in one location, and it is not possible to directly access the cloud, so there is a performance loss.> `
this is the main topic of the feature, if its possible it will not be added soon but as a future feature, i believe it could be a interesting addition considering the community that Resonite has
