### ISSUE TITLE
Exit headless when users are no longer able to join, enabling auto-updating

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#2274]
### Is your feature request related to a problem? Please describe.

Currently, I have to manually stop and restart my headless to get it to update, I would rather this be automated

### Describe the solution you'd like

When all hosted sessions are empty, and the headless detects it is no longer the most recent version, it should exit with code 0.  In this state, users likely won't be able to join anyways (other than a few who've delayed updating), and exiting will allow services such as docker (my use case) to then restart the headless.  My personal docker image runs an update via steam on launch before starting the headless, and I imagine others do something similar, so this behavior would ensure that headless servers can receive updates.  This behavior likely may not be desirable for everyone, so it may be wise to add a config which disables it, such as `no_exit="true"`

### Describe alternatives you've considered

Another option may be adding an internal self-updating mechanism to the headless, however I forsee conflicting cases, ex: where users headless is running off the same machine (and thus files) as their interactive sessions, and I'm unsure of how this might conflict with steam's updating mechanisms

### Requesters

zangooseoo

**Comment by Frooxius** [comment]
This would be handled by this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1212

Right now we don't have any mechanism to detect what the recent version is - or what version you want. E.g. if you want to host headless for other branches (e.g. for testing or compatibility purposes).
