### ISSUE TITLE
Make resonite be able to use giggle tech OSC router for multiple giggle pucks to work

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#2277]
### Is your feature request related to a problem? Please describe.

currently how resonite finds giggle pucks is it looks for the ip under [giggle](http://giggletech.local/) but that only lists one puck at a time and doesn't work if you have meny pucks that you wanna use for like (head and belly)

### Describe the solution you'd like

have a way to use meny pucks seamlessly 

### Describe alternatives you've considered

none

**Comment by Frooxius** [comment]
This is something that's already supported. The giggle.local should resolve to multiple IP's if there are multiple present on your network.

Is only single one detected for you? How are they configured? Can you share logs?

**Comment by SlyTheFloof** [comment]
> This is something that's already supported. The giggle.local should resolve to multiple IP's if there are multiple present on your network.
> 
> Is only single one detected for you? How are they configured? Can you share logs?

both are connected via static ip config but only shows one ip [giggletech.local](http://giggletech.local/)

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/a2ae8c86-4f6a-4aec-89c7-028451e75210)

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/88360ca2-3619-464a-ae67-32c3d93895d1)

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/86118564-5702-440c-8fd4-83f4dd09f947)

Resonite log 
[SLYS-DESKTOP-PC - 2024.6.11.74 - 2024-06-11 00_28_16.log](https://github.com/user-attachments/files/15782306/SLYS-DESKTOP-PC.-.2024.6.11.74.-.2024-06-11.00_28_16.log)

**Comment by SlyTheFloof** [comment]
both are connected via static ip config but only shows one ip [giggletech.local](http://giggletech.local/)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/a5b003cf-2a39-4684-abfc-6cad33581d84)

![Resonite_4lRa8QPyh7](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/3fd9d8d1-b682-4da7-adb3-1dee5d6e234f)

resonite log attached
[SLYS-DESKTOP-PC - 2024.6.11.74 - 2024-06-11 00_45_04.log](https://github.com/user-attachments/files/15782449/SLYS-DESKTOP-PC.-.2024.6.11.74.-.2024-06-11.00_45_04.log)

**Comment by Frooxius** [comment]
@SlyTheFloof From your look and video, it looks like both got initially detected, but it's unreliable and they seem to be disconnecting.

You might need to check "Always treat as connected" on both of them and see if that works. 

Resonite doesn't use the OSC Router by the way.

**Comment by SlyTheFloof** [comment]
ok yea that fixed it so it just doesn't list on giggletech for me but useing the always treat as connected works

**Comment by shiftyscales** [comment]
Can this issue be closed then, @SlyTheFloof?
