### ISSUE TITLE
Height Locale Strings Removed, But Still Used for `Full Body / Avatar Calibration`

### ISSUE THREAD

**Issue by stiefeljackal** [Yellow-Dog-Man/Resonite-Issues#2279]
### Describe the bug?

The `Settings.Height`, `Settings.Metric`, and `Settings.Imperial` locale keys were removed due to the transition from the old to the new settings Screen. However, these keys are still used for Full Body / Avatar Calibration.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/20023996/f8a8232f-4161-4db4-be0a-b388c7a1d997)

### To Reproduce

1. Open the Dash.
2. Click or press **Full Body / Avatar Calibration**.
3. The dialog should appear with the missing Locale keys

### Expected behavior

The Locale keys should populate with the correct values for the set Language.

### Resonite Version Number

2024.6.5.1084

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[JACKAL_MK2 - 2024.6.5.1084 - 2024-06-10 12_09_29.log](https://github.com/user-attachments/files/15776396/JACKAL_MK2.-.2024.6.5.1084.-.2024-06-10.12_09_29.log)

### Additional Context

I previously reported this in the Locale repository (https://github.com/Yellow-Dog-Man/Locale/issues/270). I'm adding it here since it will have higher visibility. A PR for the missing Locale keys was also created (https://github.com/Yellow-Dog-Man/Locale/pull/391) that should resolve the issue for the `en` locale. Of course, if the team is looking to change the key names, then I will update the PR accordingly. 

### Reporters

Stiefel (@stiefeljackal)

**Comment by shiftyscales** [comment]
Seems like something that was just overlooked should be a simple tweak @ProbablePrime.

`Setting.Height` can be replaced with `Settings.UserMetricsSettings.UserHeight`
`Settings.Metric` with `General.Units.Metric`
`Settings.Imperial` with `General.Units.Imperial`

**Comment by stiefeljackal** [comment]
> `Setting.Height` can be replaced with `Settings.UserMetricsSettings.UserHeight`
`Settings.Metric` with `General.Units.Metric`
`Settings.Imperial` with `General.Units.Imperial`

If the locale keys in the `FrooxEngine` code will be updated to the mentioned mappings above, then I will update my locale PR with the following:
* Add missing values for `General.Units.Metric` and `General.Units.Imperial` with the same values from `Settings.Metric` and `Settings.Imperial` (minus the unit mentioned) in those locale files. 
* Discard `Settings.Height` since it is slightly different from `Settings.UserMetricsSettings.UserHeight` due to the possessive noun.

**Comment by shiftyscales** [comment]
Those values already exist in the locale- at least in the en.json locale file, @stiefeljackal - that was where I got them from.

**Comment by stiefeljackal** [comment]
@shiftyscales I'm aware they exist in en.json file. `General.Units.Metric` and `General.Units.Imperial` are missing in the following locales where they formerly had these values under the legacy key name:

* cs.json
* eo.json
* es.json
* et.json
* fi.json
* is.json
* nl.json
* no.json
* pl.json
* pt-br.json
* tr.json
* zh-tw.json

I will update my locale PR to include those missing keys and their values as mentioned above once @ProbablePrime confirms to the mappings mentioned in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2279#issuecomment-2159139467.

**Comment by shiftyscales** [comment]
I see. Thanks. :)

**Comment by Frooxius** [comment]
@ProbablePrime Do you mind if I take this?

**Comment by ProbablePrime** [comment]
Of course

**Comment by Frooxius** [comment]
Fixed this up in 2024.7.25.1115, tahnks!
