### ISSUE TITLE
Active sessions aren't visible

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2283]
### Describe the bug?

If you go to the active sessions tab or headless' tab there are 0 sessions

### To Reproduce

Open the world's menu and go to active sessions or the headless' tab

### Expected behavior

They should function properly and display sessions properly

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/4ed6221c-7cef-4c94-97fc-b284038549a6)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/63bbbbf1-ce9e-4142-972d-ea6f9e6b7960)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/b3cc2ab6-aa01-4ea3-beb6-af56187d4981)

### Resonite Version Number

Beta 2024.6.10.1405

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2024.6.10.1405 - 2024-06-10 19_44_52.log](https://github.com/user-attachments/files/15780409/DESKTOP-DAN95E7.-.2024.6.10.1405.-.2024-06-10.19_44_52.log)

### Reporters

@epicEaston197

**Comment by ProbablePrime** [comment]
The new update we just launched is incompatible with other updates.

Can we wait about an hour and see if this persists?

**Comment by epicEaston197** [comment]
> The new update we just launched is incompatible with other updates.
> 
> Can we wait about an hour and see if this persists?

okay maybe I jumped the gun a tiny bit turning on "fetch incompatible sessions" fixes my issue but it might be a issue with the new build so I'll just wait

**Comment by epicEaston197** [comment]
The basement nerd is hosting a session right now but I cannot see this through the world browser at all
( keep in mind I turned off that you compatible sessions my world's tab it just hasn't updated yet basement is also on the new build)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/a8f85c9d-dbfb-4805-96a5-0e5670f48e11)

**Comment by Zyro1331** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/3f20308c-a19f-4574-89f2-5e1afd6624a4)
Unable to recreate the issue on a clean Resonite client. Show incompatible sessions is disabled.
I am also able to see Headless and Contacts sessions just fine. 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/eddb8cc7-8df0-4645-b0ac-16a5a88dd24a)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/00677f2e-7009-4434-a8f0-e0f21edb2f93)

**Comment by epicEaston197** [comment]
Huh maybe my games just being weird xD

**Comment by ProbablePrime** [comment]
Make sure your clock is synced too!

**Comment by ProbablePrime** [comment]
I see you in other sessions currently @epicEaston197 is this resolved?

**Comment by epicEaston197** [comment]
> I see you in other sessions currently @epicEaston197 is this resolved?

I believe so sorry for jumping the gun so quickly on this issue
