### ISSUE TITLE
Duplicate User Profile Tabs In Contacts (VR MODE)

### ISSUE THREAD

**Issue by TheNovaBeast** [Yellow-Dog-Man/Resonite-Issues#2294]
### Describe the bug?

Selecting a person who is not your friend with their name badge multiple times will cause them to appear in your contacts as search results many times

I have only been able to have replicated this twice, I can't get it again.

### To Reproduce

1. Select a user that isn't your friend more than once via the name badge (leaving the menu each time)
2. Go to your contacts list and scroll down

### Expected behavior

Clicking on a user profile should not add additional entries to the contacts list or as a search.

### Screenshots

I will post if I can replicate it, or if someone else can.

### Resonite Version Number

2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2 (currently)

### Log Files

N/A

### Reporters

Resonite Server Username:  The Nova Beast
My discord account name is: FireFlyFlying

**Comment by JackTheFoxOtter** [comment]
Do these duplicate entries persist if you restart the game.

**Comment by TheNovaBeast** [comment]
> Do these duplicate entries persist if you restart the game?

No they do not

**Comment by Frooxius** [comment]
Since this isn't game breaking and it seems to be rare and the whole Contacts UI will be scrapped and reworked, I don't think we'll investigate this one for the old UI.

It should be implicitly fixed once we rework the Contacts UI, because that one will be based on the generic data feeds.

**Comment by TheNovaBeast** [comment]
> Since this isn't game breaking and it seems to be rare and the whole Contacts UI will be scrapped and reworked, I don't think we'll investigate this one for the old UI.
> 
> 
> 
> It should be implicitly fixed once we rework the Contacts UI, because that one will be based on the generic data feeds.

I understand, and that is fair if you are close to having the overhaul ready anyways! As a new user it's nice to know these things, thanks Frooxengine!
