### ISSUE TITLE
GridTexture gets permanently broken by invalid parameters

### ISSUE THREAD

**Issue by 5H4D0W-X** [Yellow-Dog-Man/Resonite-Issues#2299]
### Describe the bug?

When a GridTexture tries to recalculate with invalid parameters for any one of the layers, it stops and does not retry when the values change in the future, even when they become valid

### To Reproduce

Make an EmptyObject and attach a grid texture. Drag out a preview for it. Add a new grid layer to the texture (the default values are invalid). Try changing parameters like the color of the original grid and observe that the texture is stuck.

### Expected behavior

The texture identifies invalid values and doesn't regenerate until all inputs are valid, instead of permanently getting stuck

### Resonite Version Number

Beta 2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

Will add later

### Reporters

scrapSavage
ShadowX

**Comment by lxw404** [comment]
When changing any of the grid parameters to anything less than or equal to zero this happens immediately.  Changing the parameters back does not prevent the texture from regenerating, however duplicating this component fixes it on the new component.

**Comment by shiftyscales** [comment]
Can you provide logs from that replication case @lxw404 since @5H4D0W-X hasn't yet included logs from it?

**Comment by Frooxius** [comment]
Merged fix in 2024.6.25.1149! Thank you!
