### ISSUE TITLE
Improve automatic hand placement of the avatar creator

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#230]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when clicking all the Align buttons of the avatar creator aligns the ghost-head in a useable position (centered, looking straight, etc.), but the ghost-hands are placed at the model's wrists with random rotation (pointing straight down, for example).

### Describe the solution you'd like

Align the ghost-hands at the wrists as before, but rotate them so that the fingers point straight out (left and right of the model) and the palms point straight down (down of the model). That would give a useable position as fingers are anyways being taken from the bones, not the ghost-fingers.

### Describe alternatives you've considered

Rotating the ghost-hands by hand or gizmos each time.

**Comment by shadowpanther** [comment]
Actually, to allow for A-pose cases, point fingers along the shoulder-elbow-wrist line and palms down.

**Comment by Enverex** [comment]
Adding for tracking purposes (https://github.com/Neos-Metaverse/NeosPublic/issues/1383).

**Comment by shadowpanther** [comment]
Could you reopen this issue as a catch-all about the hands aligning or make a new "official" one, @shiftyscales ?
I feel that people would eventually create more duplicates.
