### ISSUE TITLE
Worlds Data Feed

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#2300]
### Is your feature request related to a problem? Please describe.

Currently there's WorldListManager component for listing worlds and sessions. This component is sort of "proto-datafeed", where it has some concepts of data feeds, but is still somewhat monolithic and doesn't fit with the rest of the data feed system.

### Describe the solution you'd like

Introduce WorldsDataFeed, which will provide list of opened worlds, sessions and published/saved worlds as a data feed. A new world browser UI will be built on top of this feature, replacing the WorldListManager

### Describe alternatives you've considered

N/A

### Additional Context

WorldListManager will be deprecated once this is released and some time after removed.

### Requesters

Myself & content team who needs this for some functionality for the cloud home.

**Comment by epicEaston197** [comment]
I'm just wondering how this is going to interact/work with the existing facets eg
would these have to be reworked to work with the new system?
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/9c747dab-ac64-4103-b7ec-7f60a895f0b3)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/add287ea-1d64-4af3-b8ed-2c4f53ab2f72)

**Comment by shadowpanther** [comment]
> would these have to be reworked to work with the new system?

The answer is right there:

> A new world browser UI will be built on top of this feature, replacing the WorldListManager

And I guess we'd also be able to build custom interfaces using the sessions list more easily with this DataFeed approach.

**Comment by epicEaston197** [comment]
> > would these have to be reworked to work with the new system?
> 
> The answer is right there:

I took that as they're gonna redesign and make a new world's facet the one with the world's inside of it I'm not sure if they're gonna redesign the entire world menu

**Comment by shadowpanther** [comment]
> I took that as they're gonna redesign and make a new world's facet the one with the world's inside of it I'm not sure if they're gonna redesign the entire world menu

"World Browser UI" is the whole set of facets on this Dash tab, as far as I'm aware. It might change somewhat, but I suppose we'd still get filters and search, like in the current UI.

That said, the filters and search facets do not dynamically load anything, they just set a bunch of DynVars that the world list itself uses to compose the query to the API. So those don't _need_ to change for the new system.

**Comment by Frooxius** [comment]
These have been added in 2024.6.24.1317!
