### ISSUE TITLE
Ability to Change Inspector Aspect Ratio

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#2302]
### Is your feature request related to a problem? Please describe.

``I'm always frustrated when`` opening a deep hierarchy in an inspector because the left side really isn't wide enough for that sometimes.

### Describe the solution you'd like

The inspector should be resizeable (with changing its aspect ratio) by just dragging on a corner, just like windows very often are in other programs and on computers in general.

It'd also be neat if the dragging the center line could let you redistribute what percentage of the inspector is used for hierarchy / the components list.

It would also be neat if a user could set a default size or if Resonite remembered what size they last set an inspector to and then spawns new ones at that scale. Otherwise some people would probably feel the need to change the size every single time they open one.

### Describe alternatives you've considered

1. Not doing this. (why?)
2. Making a custom inspector to do this. (This is possible but at this point, you either need to make a mod or Resonite is actively working against you by making the dev tool's default behaviors hard to edit)
3. Making a mod that adds this. (mods are janky and people shouldn't need to install them for something as basic as this)

### Additional Context

People commonly make their custom inspectors be closer to a square aspect ratio to have more space on them so it seems like the demand is there. (and has been, for a long time)

This request could also be extended to other default UI, potentially making this a content issue but the inspector seems the most important and the only one I can think of where being able to change the aspect ratio makes a lot of sense.

### Requesters

cameron5 on Discord / Psychpsyo on Resonite

**Comment by Frooxius** [comment]
This would be implicitly handled by this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/563

The goal here is we rework inspectors to a more modular system. Part of this is that the "container panel", is going to be its own template, that we can build in-game nicely.

That way we can make a fancy container panel for all the UI's to share, which ensures consistency, but also that we can add a number of nice features like resizing, which is something that's been on my radar for it. 

I'll close this one as duplicate, but we definitely want to have this more generally as a feature for UI's.
