### ISSUE TITLE
Eyebrow parameters should be assignable in EyeLinearDriver

### ISSUE THREAD

**Issue by hazre** [Yellow-Dog-Man/Resonite-Issues#2303]
### Is your feature request related to a problem? Please describe.

After the recent SteamLink intergration update, some few eye and face tracking parameters were added to the eye manager and the avatar expressions component to fully take advantage of Quest Pro's eye and face tracking capabilities. One of these was eye brow expressions. To be exact, InnerBrowVertical & OuterBrowVertical.

But so far, I have not found a way to assign blendshapes to these parameters below, besides manually driving them.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/37149950/3fc3c2e2-fe39-4206-8462-0359d142c804)

### Describe the solution you'd like

I would like to be able to assign blendshapes for InnerBrowVertical & OuterBrowVertical inside EyeLinearDriver component, similar to other eye related parameters:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/37149950/f5bb6c2f-18fb-412a-b2c0-8c31ce647796)

### Describe alternatives you've considered

Manually driving avatar's blendshapes from Eye Manager's RawOutput parameters.

### Requesters

@hazre
@gourry
@natbard

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius.

**Comment by hazre** [comment]
I want to add something else to this. it looks like the parameters for `BROW_LOWERER_R` and `BROW_LOWERER_L` are missing too (they are called brow down sometimes)

I understand that Froox went for a more generic way of handling it by going for -1 to 1, to handle both lower and upper but in reality basically all face tracking avatars that have support for quest pro's brow tracking have it as a separate blendshape.

![image](https://github.com/user-attachments/assets/bd5758fc-039b-49e6-af7c-e30f26701a70)

Would be nice to have two helper fields for BrowLower for each eye under EyeLinearDriver component, so users don't have to add extra logic to their avatars to be able to map it correctly to their avatar's blendshapes.

**Comment by Frooxius** [comment]
This has been implemented in 2024.10.4.923 by @RyuviTheViali, thanks!
