### ISSUE TITLE
Cone Colliders can't specify top radius

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#2313]
### Is your feature request related to a problem? Please describe.

I want to use primitive colliders to optimize my worlds and some objects are conical in shape but have non-pointy tops so I would like to be able to define the top radius of the collider primitive

 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33443066/6e3959f9-845c-403d-a6f4-e6b39ea19fb7)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33443066/2604a8c4-92b8-4860-b332-c8b530d6fc77)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33443066/f18632b6-c0db-4089-8c80-98401e1022a0)

### Describe the solution you'd like

flat cone colliders

### Describe alternatives you've considered

mesh colliders with really small side counts

### Requesters

venport

**Comment by Frooxius** [comment]
Unfortunately this is not supported by the physics engine, so we can't offer this feature.

I don't think conical frustums (which is the name of the shape this would produce) are generally supported as primitive colliders in any physics engines, so I don't foresee this being supported in any foreseeable future at all.

You can emulate this using a procedural mesh and convex hull collider.
