### ISSUE TITLE
Unhandled Exceptions | System.IndexOutOfRangeException | System.InvalidOperationException

### ISSUE THREAD

**Issue by Krzeszny** [Yellow-Dog-Man/Resonite-Issues#2316]
### Describe the bug?

During day 3 of the Protoflux Classroom we started driving color (HSV) nodes with GlobalTime.
After a few seconds, I got kicked to my home (first log). I rejoined and seconds later I got kicked again (second log). The whole session crashed when I was about to rejoin without mods so I couldn't test it properly. One of my friends' game crashed, too.
I suspect not everyone was doing it in the same way because I couldn't repro the crash by repeating exactly what I did, even by creating several drives. 

### To Reproduce

Drive color values from time floats? 
(I started getting kicked while just watching the nodes)

### Expected behavior

No crashing

### Resonite Version Number

2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Reverb G2

### Log Files

[exception 1.log](https://github.com/user-attachments/files/15814993/exception.1.log)
[exception2.log](https://github.com/user-attachments/files/15814994/exception2.log)

### Additional Context

Both log snippets are from the same (24MB) log file but I haven't found any more relevant context.

### Reporters

Kresny

**Comment by Zyzyl** [comment]
Generally the team requests users to upload full log files, I'd recommend re-uploading the full logs or at least linking to them

**Comment by shiftyscales** [comment]
Yes, full log files would help- it would also be helpful to have precise replication steps that are known to cause the issue, and ideally also a replication object that replicates the issue, @Krzeszny.

**Comment by Krzeszny** [comment]
> Yes, full log files would help- it would also be helpful to have precise replication steps that are known to cause the issue, and ideally also a replication object that replicates the issue, @Krzeszny.
Sorry, I have no replication steps. If I had them, I'd have shared them. Here's the full log:
https://drive.google.com/file/d/18zviq2hvPzDdU26Y-L9qRuL14NC9ovRo/view?usp=sharing

**Comment by shiftyscales** [comment]
Can you upload it directly to GitHub please, @Krzeszny? You can do so by dragging and dropping it onto the comment field.

If it is too large to attach, you can zip it first which will significantly reduce its size.

**Comment by Krzeszny** [comment]
@shiftyscales It's not too large to attach, but it's still large nevertheless.
[DESKTOP-VHA2V7H - 2024.6.11.74 - 2024-06-11 14_26_55.log.zip](https://github.com/user-attachments/files/15887048/DESKTOP-VHA2V7H.-.2024.6.11.74.-.2024-06-11.14_26_55.log.zip)

**Comment by shiftyscales** [comment]
> 14:27:03.985 ( -1 FPS)	Loaded Extra Assembly: Libraries/ResoniteModLoader.dll

Your log file indicates the use of client modifications, @Krzeszny - please retest your issue with all modifications disabled / on a fresh / untouched copy of Resonite.

Per our [reporting requirements](https://github.com/Yellow-Dog-Man/Resonite-Issues#reporting-requirements):
> - **Provide a clean [log file](https://wiki.resonite.com/Log_Files)** from replicating the issue (do not use mods or plugins except for diagnostic ones (see below), launch the client, load the replication item/world, replicate the issue, and exit)

We also would still need reproduction steps and confirmation your issue occurs on an unmodified version of Resonite.

For now I will be closing this issue, if you find the above requested additional information- please provide it here and this issue can be re-opened- or make a new issue.
