### ISSUE TITLE
Pasting resrec uri's spawns the content at root

### ISSUE THREAD

**Issue by NezzKryptic** [Yellow-Dog-Man/Resonite-Issues#2317]
### Is your feature request related to a problem? Please describe.

When pasting content from a resrec uri, the content spawns at root rather than within the user's view.

### Describe the solution you'd like

Having the pasted content spawn within the user's view for ease of location and use.

### Describe alternatives you've considered

Having Flux on the content that places that object in the users view, though this adds unnecessary bloat to content.

### Requesters

NezzKryptic

**Comment by paradoxical-autumn** [comment]
In your title, you state "resrec" URIs, but in your comment you state "resdb"? Which do you mean?
I agree that `resrec`s should have their content spawn in the user's view but I can't agree with `resdb`s, as they are designed for internal use only and not for file sharing.

**Comment by epicEaston197** [comment]
This is an unfinished feature I believe because it also doesn't properly clean up the holder slot above it if it was saved with your laser/hand

**Comment by shiftyscales** [comment]
Thanks for the report, @NezzKryptic - this is a report of #430 however.
