### ISSUE TITLE
Provide workaround to desktop users for assigning profile picture

### ISSUE THREAD

**Issue by Elaquen7** [Yellow-Dog-Man/Resonite-Issues#2318]
### Is your feature request related to a problem? Please describe.

In desktop mode, editing the dash is not possible. Therefore, in addition to not being able to edit the dash (mostly), it is not possible to assign a profile picture as this involves importing a picture and moving it onto the dash.
As the dash fills the screen in desktop mode and objects cannot interact with it, a workaround might be needed.

### Describe the solution you'd like

When importing something with a file extension that is known to be an image format, in the "What are you importing?" dialogue, provide a new option to import as profile picture.
This option should automatically try to import the file as an image and set it as the user's profile picture.

### Describe alternatives you've considered

Alternatively this feature could stay unavailable until a method for moving objects and facets onto the dash in desktop mode is figured out.

### Requesters

Elaq

**Comment by Zyzyl** [comment]
This seems to have a common root problem with a bunch of other issues like https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/628 i.e. that the dash is hard to edit in Desktop mode

**Comment by Electronus** [comment]
If I'm not mistaken if you are already holding the image and open your dash it should work.

**Comment by ko-tengu** [comment]
I do think the entire workflow of this can be more obvious, but you can apply a user picture in desktop by just continuing to hold an item while the dash is up. This is also how desktop users can export files with the file browser or save held objects into the inventory without a context menu.

**Comment by ShrikeAlvaron** [comment]
Perhaps a solution to assigning a profile picture in general would be to give a "Set Icon" button when selecting a picture in your inventory (or even your file browser) as with other items like avatars.  Of course, that may be pending an inventory/file browser overhaul, but would bring it in line with the flow for setting other things.

**Comment by JackTheFoxOtter** [comment]
This does not need a workaround, as it already works, the same way you export files in desktop mode. Grab the object, open the dash while the object is held, and then just click on your profile picture. Example:

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/35171546/63158fb2-c210-4e1d-b94c-63d38bfed08e
