### ISSUE TITLE
Open file picker when clicking profile picture in dash

### ISSUE THREAD

**Issue by Elaquen7** [Yellow-Dog-Man/Resonite-Issues#2319]
### Is your feature request related to a problem? Please describe.

The process of setting a profile picture is convoluted and is explained nowhere in the game or online documentation. From my own experience, clicking the profile picture, one would assume a file picker to open. This is in no way a standardized interaction but almost all UI systems I have interacted with over the last decade work this way or have an edit button right next to the image.

### Describe the solution you'd like

As clicking the picture has currently no use and no effect, on click provide a short explanation on how to set a profile picture via import (also see #2318) or preferrably open a system file picker to automate these steps.

### Describe alternatives you've considered

Currently when you click on the image it flashes, indicating that something should have happened even though there was nothing there in the first place. **If this feature request is not implemented**, at least edit the corresponding facet to not react when a user clicks the image. Otherwise the user might assume they are doing something wrong or something is broken on their end when nothing happens.

### Requesters

Elaq

**Comment by JackTheFoxOtter** [comment]
To my knowledge there isn't really a file picker like that in Resonite, but I can imagine in the future this could work through the inventory. I can't find the issue but I remember there was talk about an easier way to favorite certain types of items, this would be likely addressed by #1119.

What I'm imagining is that you could for example click on "Change Camera", and it opens a filtered view of your inventory showing you all cameras you have. Similarly, a "Change Profile Picture" could open a filtered view if your inventory showing you all pictures you have saved.

A actual file picer from your host computer would probably be more complicated, as then that mechanism would have to import / upload the file itself, right now files are already imported / uploaded when you set them as your profile picture.

**Comment by Elaquen7** [comment]
@JackTheFoxOtter 
> An actual file picker from your host computer would probably be more complicated, as then that mechanism would have to import / upload the file itself, right now files are already imported / uploaded when you set them as your profile picture.

So do I understand this correctly:
When you import the image an object on the Resonite servers is created and setting the profile picture just creates a reference to this object?
That would explain why this is necessary.

As I pointed out in a comment on #2318, maybe guiding new users through this process in the tutorial world might be a good alternative.

**Comment by JackTheFoxOtter** [comment]
The profile picture is basically just referring to an uploaded image asset. (resdb link)

There's different approaches for this issue. But fundamentally I do believe that you should not need a tutorial to change your profile picture. Making it part of the account creation would have a similar need for some file select & import mechanism, and I don't think it should be part of the tutorial world, as that focuses on core interactions on the platform.

Making the profile picture clickable and opening some sort of picture selector would be neat, either that or just having that open in the inventory directly. I know with the planned inventory UI rework there will be individual facets for folder contents, so I wouldn't think it would be too far off to open a filtered view of your inventory in a modal to let you select an image file. I think the idea is good.

**Comment by Elaquen7** [comment]
> There's different approaches for this issue. But fundamentally I do believe that you should not need a tutorial to change your profile picture. Making it part of the account creation would have a similar need for some file select & import mechanism, and I don't think it should be part of the tutorial world, as that focuses on core interactions on the platform.

At it's core Resonite lives from user generated content. New users should be encouraged to learn the basics of dragging and dropping objects on UIs and attributes between UIs if you want them to be able to use the dev tool or the protoflux tool.
Putting a spot in the tutorial world where it teaches you to set your profile picture seems like a great example for this kind of interaction.
