### ISSUE TITLE
 ProtoFlux:Touch Controller - ThumbRestTouch - Permanently False

### ISSUE THREAD

**Issue by TumnusB** [Yellow-Dog-Man/Resonite-Issues#2328]
### Describe the bug?

The ProtoFlux:Touch Controller node, will display output for every touch button input but when ThumbRestTouch is touched the node doesn't update but you can see the thumb move in game so the input is detected but the Node isn't updating, I have confirmed this with several users, all added to the Reporters.

### To Reproduce

Find a Quest user, grab the node, plug in either hand and have them touch the thumb rest area on their controller.

### Expected behavior

When the thumb rest area is touched for the output ThumbRestTouch to flag True then on release to flag False

### Screenshots

[Video of The Issue](https://drive.google.com/file/d/1po7zff0-mk2Podu3_1BNRRJgh2RHG-hy/view?usp=sharing)

Due to Github file size requirement of 10MB I had to upload it to my GDrive, happy to upload elsewhere if that is a security concern

### Resonite Version Number

2024.6.11.74 

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[TOM-PC - 2024.6.11.74 - 2024-06-14 13_30_55.log](https://github.com/user-attachments/files/15838137/TOM-PC.-.2024.6.11.74.-.2024-06-14.13_30_55.log)

### Additional Context

Calamity Lime was using a pico but as Virtual Desktop emulates Touch Controllers same behavior

### Reporters

MrTumnus, stephblackcat, NovaFox21, Calamity Lime, thebettercat

**Comment by ko-tengu** [comment]
This is an error with the default SteamVR binding instead of the flux node, and has instructions on how to fix it yourself and an assurance of a default binding update in the future over here https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/449

**Comment by TumnusB** [comment]
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/449
