### ISSUE TITLE
LNL Bridge and Relay Updates

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#2336]
The LNL Relay and Bridge are currently running under the same .NET version as Resonite itself. On our nodes this also means they're running under mono.

We'll be updating the .NET version of both elements but also combining them together into one application. This makes it easier to deploy and run and means they can run natively on Linux.

This will also reduce some of the performance issues we are seeing on some of our smaller LNL Network Nodes.

**Comment by FlameSoulis** [comment]
So the newer .NET is just friendlier with Mono for Linux, or that the newer one actually produces binaries that can just run on Linux without the need of Mono?

If the latter sounds like that, it could also benefit the client's relation to Linux operations.

**Comment by ProbablePrime** [comment]
.NET can run native apps, Not sure what version enabled that but 8 certainly did, which means we can skip Mono for them.

For an example app, look i added linux support here: https://github.com/Yellow-Dog-Man/LNLBridgePoker/blob/main/LNLBridgePoker.csproj#L7

However, This isn't relevant to the client though as that's still gonna be stuck inside Unity which means Mono.

**Comment by ProbablePrime** [comment]
Uh this is old but also done yay
