### ISSUE TITLE
Reduce the usage of Secondary in default tools

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#2338]
### Is your feature request related to a problem? Please describe.

Currently all of the default tools (dev tool, protoflux tool etc) use secondary, this can cause issues with secondary axis locomotion lock as described in #125

As Frooxius commented in that issue, and other issues related to secondary axis locomotion lock, the only solution is to not use secondary in the default tools where possible.

Quoting Froox from the above issue:
 `I think the main thing here would be going over some of the basic principles of the tools and removing need to use the Secondary on a lot of them.`

### Describe the solution you'd like

Remove / reduce the usage of secondary in the default tools where possible. 

### Describe alternatives you've considered

leave it as is, and if users do not want secondary axis locomotion lock they will need to use mods to disable it. 

### Additional Context

I am making this as there was no feature request / tweak issue for the prior. And this can be used to direct people to when they have issues with secondary axis locomotion lock.

You can also direct users here if duplicate issues for decoupling secondary axis come up again, and other issues that will be closed due to removing secondary axis locomotion lock not being an option, as described in #125 #2310 #1817 #17 and others.

### Requesters

Stellanora

**Comment by epicEaston197** [comment]
When holding a tool the bottom face button could be used as the secondary action and if you wanna open your dash or activate facet anchors you would need to hold down the button to open either that would completely fix this issue

**Comment by gameboycjp** [comment]
I'd like the option for old behaviour if there are any changes, I really like how the tools currently work.

**Comment by Frooxius** [comment]
I don't know how we would really do this for some tools without making things complicated or too confusing. 

E.g. say the ProtoFlux tool has only a single input to work with - this means every single action now has to be done through context menus or some gestures.

Similar with DevTool - you need to do two actions - interact with gizmos and select. It could potentially be bound to a single action, but now that means if you miss the gizmo, you select something else.

While reducing the usage of secondary would help with the lock, it would come at the cost of making those tools a lot harder to use.

**Comment by Stellanora64** [comment]
I agree that secondary action is very useful for the functionality of the default tools, but since decoupling it from axis is not feasible, there is no other option that has at least some possibility of mitigating the issue.

All other suggestions have been rejected, so I'm not sure what other approach there could be.

Possibility some specific action / combo could be remapped to act as secondary action, like as Easton suggested above.

**Comment by Frooxius** [comment]
Decoupling from the axis is potentially feasible. It's a complicated problem.

We generally recommend to focus on the problem, rather than specific solutions and let us work out the solution, rather than pushing a specific one - it's something we explicitly mention in the guidelines for this reason (and it's probably one of the most common reasons issues get closed): https://github.com/Yellow-Dog-Man/Resonite-Issues

For things like this we need to step back and think about it and formulate what exactly is the problem first and then figure out how it will affect things and rethink stuff holistically - but that's hard to do when we are asked to make a very specific change.

In this case it seems that on some controllers, motion controls become harder to use due to the tool taking control of one of the elements.

**Comment by Stellanora64** [comment]
That's fair, would you like me re-name this issue / make a new one that is less specific for this solution and focuses more on generally improving motion controls for quest like controllers?

**Comment by epicEaston197** [comment]
Again rebinding secondary from the joystick to the bottom face button would fix this issue entirely and just have the dash open when you hold down the button and do secondary when you press it

**Comment by Stellanora64** [comment]
super seeding with #2339
