### ISSUE TITLE
Resonite Migration Completely Failing

### ISSUE THREAD

**Issue by RuiNtD** [Yellow-Dog-Man/Resonite-Issues#2347]
### Describe the bug?

Hello. When I attempt to migrate from another Resonite account, the migration completely fails, migrating over 0 items.

### To Reproduce

1. Go to the Migration menu
2. Click New Migration Task
3. Attempt to migrate from another Resonite account

### Expected behavior

The migration succeeds.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/1149870/c9241656-0b2b-4153-993d-c6142bb73123)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/1149870/d355fee4-51a6-469c-a126-b17b1665d8de)

### Resonite Version Number

Beta 2024.6.11.74

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ETHAN-PC - 2024.6.11.74 - 2024-06-15 23_03_01.log](https://github.com/user-attachments/files/15856262/ETHAN-PC.-.2024.6.11.74.-.2024-06-15.23_03_01.log)

### Reporters

RuiNtD

**Comment by DanteTucker** [comment]
Just a headsup that support has been redirecting these issues to github.  I know the message from the bot says to contact support but we don't have access to migration logs in support. So please handle this here. It would be best if the bot message was changed to not direct users to support.
Thank you.

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius or @ProbablePrime.

**Comment by ProbablePrime** [comment]
I cannot check Migration logs.

**Comment by FlameSoulis** [comment]
I've just checked the other system, and logins and inventory do appear to be online... albeit very slow.

**Comment by RuiNtD** [comment]
Hello? Any update on this? I just tried this again but now I can't even get past the login screen.
![Resonite_ZCFvLp6ZnV](https://github.com/user-attachments/assets/4a523111-727a-42d5-a8f2-0da23028943a)

**Comment by shiftyscales** [comment]
It appears that @Frooxius is taking a look into this issue as seen on #2646, @RuiNtD.

And yes, @FlameSoulis - the system is designed so that you can migrate from any compatible infrastructure with which Resonite to Resonite migrations will be compatible of course. It will also be useful in future for running separate testing infrastructure.

**Comment by Frooxius** [comment]
This looks like a different issue?

**Comment by shiftyscales** [comment]
@RuiNtD in the comment above mentioned the same symptom- being unable to progress past the login page, which was the same issue reported in #2646 that was what I was referring to in specific.

Otherwise for the issue as a whole, yes, it is a different issue- because this issue is otherwise pertaining to Resonite to Resonite migrations, @Frooxius.

**Comment by TumnusB** [comment]
I tried migrating stuff from my headless to my main account to test

![image](https://github.com/user-attachments/assets/ae251ac3-7c79-410e-ad5e-cafcdd37ffb5)

Another user Spacee1/spacerocket1
They migrated Neos Account over and wanted to migrate from their Reso Account to Neos Import
I was in session with them as they tried to migrate their stuff over
they attempted Full Account, Contacts, Contacts With Messages & Cloudvars, Items Plus Worlds
<b>All Failed</b>

**Comment by WattleFoxxo** [comment]
+1, I'm having the same issue.

**Comment by Marshall-vak** [comment]
+1, Also having the same issue.

**Comment by ProbablePrime** [comment]
Please don't reply with a +1

Instead react to the issue with 👍

**Comment by Frooxius** [comment]
If you're making a reply, please provide more detailed information - that way I we can use that to look and diagnose the problem.

**Comment by Frooxius** [comment]
This should be fixed in 2024.10.4.923! Thanks for report!
