### ISSUE TITLE
Strip invalid characters when exporting items

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2351]
### Is your feature request related to a problem? Please describe.

When you're exporting an item with a color tag for example the export will fail because those characters are not allowed to be in a file name in windows

### Describe the solution you'd like

i would like the export dialogue to strip all tags along with any invalid characters that would prevent it from exporting as a valid file

### Describe alternatives you've considered

Manually editing the slot name to remove all unsafe characters so the exporter can export the object successfully

### Requesters

@epicEaston197

**Comment by shiftyscales** [comment]
This is a dupllicate of #2286, @epicEaston197.
