### ISSUE TITLE
First character typed in a field after double clicking an empty field gets removed

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#2361]
### Describe the bug?

Typing in a field that is null or empty after double clicking the field to select all appears to delete the first typed character in the field. 

### To Reproduce

Create an empty slot or select any existing one,
Null the slot name
Double click on the name field
Type "Test"
See the resulting "est" text being left behind

### Expected behavior

The text you type after double clicking the field should be retained without being partly removed.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/43e55120-65eb-4274-89c7-7e387e43d951

### Resonite Version Number

Beta 2024.6.11.74

### What Platforms does this occur on?

All

### Reporters

_deltawolf
imerin.

**Comment by ImErinTheBunny** [comment]
Thank you for reporting this for me

**Comment by Frooxius** [comment]
Fixed this in 2024.7.25.1115, thanks for rerpot!
