### ISSUE TITLE
Subworld Creation

### ISSUE THREAD

**Issue by mrkbx** [Yellow-Dog-Man/Resonite-Issues#2376]
### Is your feature request related to a problem? Please describe.

Currently it's pretty annoying to create big worlds made out of seperate areas, mostly because of preformance and "littering the world browser with subareas" concerns.

### Describe the solution you'd like

Ability to create subworlds, worlds connected to one root world, not normally accessible from the world browser; only accessible via "teleporting" (leaving root world and instantly joining subworld via flux/components) in root worlds. 

### Describe alternatives you've considered

Creating seperate worlds, which creates an unnessesary mess on the world tab and makes it pretty tedious to manage it all in one place.

**Comment by Nytra** [comment]
You can already have worlds be accessible by URL without publishing them

**Comment by mrkbx** [comment]
> You can already have worlds be accessible by URL without publishing them

it's not treated as a part of the "world", therefore it's a mess with several things like permissions and so on

i don't know if hosts who aren't the world creators can open up these worlds via just the link, they are unpublished

**Comment by Electronus** [comment]
if you have it set in the metadata yeah they can.

**Comment by lxw404** [comment]
This is already addressed [here](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/702).  Specifically:
> -- It will also provide a way to create large worlds, by having world split into multiple domains, with each representing a single chunk of the world and other domains coordinating them

**Comment by ProbablePrime** [comment]
Closing as duplicate
