### ISSUE TITLE
PayPal Balance As A Subscription Payment Option

### ISSUE THREAD

**Issue by TheNovaBeast** [Yellow-Dog-Man/Resonite-Issues#2380]
### Is your feature request related to a problem? Please describe.

PayPal option on patreon but it forces me to use a card which defeats the purpose of what I would like. 

### Describe the solution you'd like

Ability to use PayPal balance through the PayPal option on Patreon because I want to support the resonate team and purchase the subscription through the method that I have been using for many years for everything in my life. I am the only one that has this request. This would make life much easier on me. Froox himself told me to put this up on the GitHub here.

### Describe alternatives you've considered

N/A

### Requesters

@FireFlyFlying

**Comment by shiftyscales** [comment]
We are not Patreon, or PayPal and we do not have control over their systems or how they operate- but from personal experience, I am pretty sure that PayPal itself does not support the use of account balance for recurring payments (subscriptions).

I would suggest reaching out to support at PayPal if you need help with PayPal's services, @TheNovaBeast.

https://www.paypal.com/ca/smarthelp/contact-us

Otherwise- for mechanisms / ways to support Resonite outside of the use of Patreon, there are other issues such as #497 which focus on that.

**Comment by TheNovaBeast** [comment]
> We are not Patreon, or PayPal and we do not have control over their systems or how they operate- but from personal experience, I am pretty sure that PayPal itself does not support the use of account balance for recurring payments (subscriptions).
> 
> 
> 
> I would suggest reaching out to support at PayPal if you need help with PayPal's services, @TheNovaBeast.
> 
> 
> 
> https://www.paypal.com/ca/smarthelp/contact-us
> 
> 
> 
> Otherwise- for mechanisms / ways to support Resonite outside of the use of Patreon, there are other issues such as #497 which focus on that.

I've been using PayPal balance for reoccurring payments all my life, such as Bills, rent and Wi-Fi, Tv and "subscriptions" as you proclaim they don't work, but they d, etc and some other sites. Just clearing that up.

But I just want another way to get more storage in Resonite and get the support role in Resonite to. I will however check your linked case.

**Comment by ProbablePrime** [comment]
We're exploring other payment methods. But as shifty says, this is most likely an issue with Patreon/PayPal and not us. There's nothing we can do in this issue to resolve the matter but a combination of Paypal/Patreon support can most likely help.

**Comment by TheNovaBeast** [comment]
> We're exploring other payment methods. But as shifty says, this is most likely an issue with Patreon/PayPal and not us. There's nothing we can do in this issue to resolve the matter but a combination of Paypal/Patreon support can most likely help.

"Hello, PayPal yes can you add balance to an option to this patreon" support isn't going to help with this, it's up to Patreon and I think others might of already brought this up before to Patreon.

But yes I understand you, I guess we just got to hope maybe Steam balance payments will get implemented or something.

Thanks for your time both of you c:

**Comment by shiftyscales** [comment]
I see- I remember this issue now, @TheNovaBeast - since your underlying concern is just about paying for a subscription via a PayPal balance, I'll re-open this issue with the title reworded to indicate such.

No guarantee we'd be able to prioritize it soon, but it's better to have this issue open in the meantime.

Seeking input from @Geenz.

As far as I've seen in first-hand experience PayPal doesn't like to use balance as a payment option for recurring billing- and prefers use of a card linked to the account, but that doesn't preclude the possibility we could still offer one-time transactions which could make use of account balance- e.g. 6-month to a year billed at once - users would need to remember to manually renew their plan by paying again whenever it is close to expiry though- and we'd need a mechanism for serving a reminder if services are about to expire.

I've noticed this while paying for games on Steam- if it is set to remember my credentials- then it only offers credit card billing, but if I don't save my credentials, then balance can be used.

**Comment by TheNovaBeast** [comment]
> I see- I remember this issue now, @TheNovaBeast - since your underlying concern is just about paying for a subscription via a PayPal balance, I'll re-open this issue with the title reworded to indicate such.
> 
> 
> 
> No guarantee we'd be able to prioritize it soon, but it's better to have this issue open in the meantime.
> 
> 
> 
> Seeking input from @Geenz.
> 
> 
> 
> As far as I've seen in first-hand experience PayPal doesn't like to use balance as a payment option for recurring billing- and prefers use of a card linked to the account, but that doesn't preclude the possibility we could still offer one-time transactions which could make use of account balance- e.g. 6-month to a year billed at once - users would need to remember to manually renew their plan by paying again whenever it is close to expiry though- and we'd need a mechanism for serving a reminder if services are about to expire.
> 
> 
> 
> I've noticed this while paying for games on Steam- if it is set to remember my credentials- then it only offers credit card billing, but if I don't save my credentials, then balance can be used.


I use PayPal Balance for Reoccurring steam and VRChat+ and twitch subscriptions often. This is why I have it as my main source. I know not all sites like to use it. 

Also thanks for hearing and letting me come back to this topic. I await further discussion

**Comment by Geenz** [comment]
@TheNovaBeast Stripe supports PayPal. See https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2819.

**Comment by TheNovaBeast** [comment]
> @TheNovaBeast Stripe supports PayPal. See https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2819.

Stripe doesn't show as an open for me when on the Patreon check out. I suggest this be further looked into

**Comment by Geenz** [comment]
@TheNovaBeast Per Stripe's documentation: https://docs.stripe.com/payments/paypal

This is dependent on the seller's preference within Stripe.  I see no reason why we wouldn't enable it as an option to users - beyond perhaps the increased payment processing rate.

**Comment by TheNovaBeast** [comment]
> @TheNovaBeast Per Stripe's documentation: https://docs.stripe.com/payments/paypal
> 
> 
> 
> This is dependent on the seller's preference within Stripe.  I see no reason why we wouldn't enable it as an option to users - beyond perhaps the increased payment processing rate.

I see it allows PayPal wallet as I like but I still don't see this as an available source within stripe currently. I insist to report back when it has either been allowed by your system.

This is something important that I need to be updated on. Thanks Geenz!

**Comment by Geenz** [comment]
Now if you do not wish to add a card to PayPal, say in the event of your balance not being able to cover your subscription with us, that's your problem.  We intend to offer multiple ways to pay via Stripe, and as needed add other options based upon demand (such as Steam).  Trying to support every payment processor under the sun isn't particularly feasible long term, so the fewer times we have to do this the better in terms of maintainability.

**Comment by Geenz** [comment]
Additionally, Stripe support isn't shipped yet.  You shouldn't even have access to anything Stripe related.

**Comment by TheNovaBeast** [comment]
> Additionally, Stripe support isn't shipped yet.  You shouldn't even have access to anything Stripe related.

I was looking into it on a site that has

**Comment by TheNovaBeast** [comment]
> Now if you do not wish to add a card to PayPal, say in the event of your balance not being able to cover your subscription with us, that's your problem.  We intend to offer multiple ways to pay via Stripe, and as needed add other options based upon demand (such as Steam).  Trying to support every payment processor under the sun isn't particularly feasible long term, so the fewer times we have to do this the better in terms of maintainability.

I always have balance so it will never be an issue in my case
