### ISSUE TITLE
Add wiki List of Public Folders to Resonite Essentials

### ISSUE THREAD

**Issue by archer007** [Yellow-Dog-Man/Resonite-Issues#2385]
### Is your feature request related to a problem? Please describe.

It is difficult to browse all public folders and get tools like RedX to index your public folder

### Describe the solution you'd like

I would like the list of public folders on the wiki ( https://wiki.resonite.com/List_of_Public_Folders ) to be added to the Resonite Essentials folder in-game. Maybe under a "List of Public Folders" subfolder. Whatever the specific method, it should allow you access to all of the folders listed on the public wiki in-game without having to manually copy paste shared folder URLs

### Describe alternatives you've considered

Simply using the wiki list of public folders (the current method) is diffcult for the average person. The average user would have to know the wiki page exists at all, know that copying Resonite URLs is possible, and successfully copy a URL while wearing a VR headset, all while having done none of these things before. 

### Additional Context

This would enhance ease of use and lower the barrier for new people to browse public folders and find interesting items

### Requesters

Archer42

**Comment by shadowpanther** [comment]
The issue with this is that some users might have the illusion that the content of these public folders is "official" because it came from the official folder everyone has. So if something broken or even malicious would surface in one of the linked folders of The Directory, for example, it would be blamed on the Resonite Team.

**Comment by ProbablePrime** [comment]
Pretty much exactly what Shadow said.

We want Essentials to be organized, licensed and useful this time around. Cramming a large collection of public folders doesn't follow this.

If you're looking for better discovery that's probably more likely going to be solved by #1473
