### ISSUE TITLE
World data feed causes exceptions when put into a feed view twice.

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#2399]
### Describe the bug?

Usually when working with data feeds I would clear out the "Feed" reference on my SingleFeedView and then put it back in to regenerate all the items after I edit the template. This does not work with the WorldDataFeed because it causes some exceptions 

### To Reproduce

1. spawn out reproductive item: `resrec:///U-art0007i/R-d6a5c299-2c04-44a0-8217-548198910613`
2. inspect it and select the list slot
3. clear out the "Feed" reference on SingleFeedView
4. put the WorldsDataFeed back in the SingleFeedView
5. no items will be created and there is an exception in the log

### Expected behavior

it works without problems

### Resonite Version Number

2024.6.24.1317

### What Platforms does this occur on?

Windows

### Log Files

[ROTHORN - 2024.6.24.1317 - 2024-06-25 12_39_22.log](https://github.com/user-attachments/files/15969729/ROTHORN.-.2024.6.24.1317.-.2024-06-25.12_39_22.log)

**Comment by Frooxius** [comment]
Good catch, this has been actually a big more general and the feeds wouldn't unregister events properly due to some parameters changing. 

Fixed this in 2024.6.25.1149, thanks!
