### ISSUE TITLE
Arm resting width setting in VRIK for desktop mode

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#240]
### Is your feature request related to a problem? Please describe.

In desktop mode, wider avatars will tend to have their hands clipping through their sides

### Describe the solution you'd like

Setting in VRIK for how "wide" the resting hand position should be (as an angle).  ex: Currently the default seems to be 90 degrees (down), maybe we want 80, or 60, where 0 would be a T pose.  This should only apply to the desktop mode resting position, not to other animations unless it seems reasonable

### Describe alternatives you've considered

not really sure what else could be done here

### Additional Context

zangooseoo

**Comment by shiftyscales** [comment]
This was covered implicitly as part of the avatar locomotion system. It is possible to specify body colliders with which avatar hands will not pass through as well as increasing the spread of the arms.
