### ISSUE TITLE
Wavelength Color node

### ISSUE THREAD

**Issue by 5H4D0W-X** [Yellow-Dog-Man/Resonite-Issues#2406]
### Is your feature request related to a problem? Please describe.

If one wants to obtain the hue of a specific wavelength of light, for example to color a laser, it has to be calculated manually.

### Describe the solution you'd like

A node that takes a wavelength in nanometers and returns a ColorX that would match a lightsource of that color.

### Describe alternatives you've considered

calculating the hue manually and using a Hue node

### Additional Context

This would essentially be a companion to the BlackBodyColorX node

**Comment by Frooxius** [comment]
Merged this in 2024.7.11.1293, thanks!
