### ISSUE TITLE
Index Of RootSlot crashes worlds

### ISSUE THREAD

**Issue by AntonBoch1244** [Yellow-Dog-Man/Resonite-Issues#2407]
### Describe the bug?

Because of the nature of C# Null no functions like IndexOf have existed.

Bug is about getting Index of Child of RootSlot where parent is Null.

### To Reproduce

Concatenate next
RootSlot -> Index Of Child -> Display 

Crashes session

### Expected behavior

RootSlot -> Index Of Child -> Display = 0

### Screenshots

No screenshots needed

### Resonite Version Number

Beta 2024.6.25.1149

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

It doesn't matter

### Log Files

[ANTONBOCH1244 - 2024.6.25.1149 - 2024-06-26 23_07_20.log](https://github.com/user-attachments/files/15995797/ANTONBOCH1244.-.2024.6.25.1149.-.2024-06-26.23_07_20.log)

Attached as file

### Additional Context

If Display is used, World crashes.
If Display about to be created, Person disconnects immediately

### Reporters

Reported: antonalekseevich 
Replicated: demonzla

**Comment by AntonBoch1244** [comment]
Ignore duplication. Probably dead issue.

Check parent is null => return 0

**Comment by art0007i** [comment]
it should probably return -1 but sure

**Comment by AntonBoch1244** [comment]
I not sure about the index starts from -1. It should be unsigned so from 0.

**Comment by Nytra** [comment]
Other nodes have a convention where if nothing is found it returns the index -1

**Comment by ProbablePrime** [comment]
this is a duplicate of #651
