### ISSUE TITLE
Resonite captures cursor even when not focused

### ISSUE THREAD

**Issue by ProtogenDelta** [Yellow-Dog-Man/Resonite-Issues#242]
### Describe the bug?

While launching resonite, I usually alt-tab over to another application in the meantime to perform other tasks.

Once resonite has fully loaded, though, e.g. into the local or home instance, it captures the mouse cursor, despite not being actively focused.

### To Reproduce

1. Launch Resonite
2. Alt-Tab to another application
3. Wait for resonite to load and capture the cursor

### Expected behavior

The cursor should not be captured, as resonite is not actively focused.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/47292121/c510fcfd-52c9-48d8-8f13-e838fd2a193e

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

Not provided, as the issue is trivial and unrelated to in-game actions or content.

### Additional Context

N/A

### Reporters

`leocatto` on Discord

**Comment by FlameSoulis** [comment]
This also triggers when switching from VR to Desktop-mode, and vice versa. It will also do it when minimized, which creates a problem when trying to unminimize the window but your controls are locked.

**Comment by Nytra** [comment]
Does anyone know a workaround for this? It is so annoying.

**Comment by Frooxius** [comment]
Fixed in 2024.5.3.467! Sorry it took a bit, I ran into this while making some other unrelated changes.

**Comment by FlameSoulis** [comment]
I'll try to poke #670 to see if this fix is a possible fix for that.
