### ISSUE TITLE
Add launch argument to disable FXAA (Fast approximate anti-aliasing)

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#244]
### Is your feature request related to a problem? Please describe.

Resonite gets kind-of blurry on lower-end screens due to the anti-aliasing always being enabled by default. 
_(ex; 2016 HTC Vive, or other HMDs within the range of 1080p)_
Being a rather text-heavy program, this can make text a lot harder to read in VR until super-sampling is turned up unreasonably high.

### Describe the solution you'd like

My solution to this minor problem would be an application launch-option to disable FXAA upon opening the program. For example, applying a launch argument "`-DisableFXAA`" would just simply initialize the rendering engine without anti-aliasing.

A more user-friendly approach would be a toggle built into the Settings menu that actively disables the anti-aliasing when you toggle it off. _(But personally, I'd rather leave the settings menu untouched until it's cleaned up later.)_

### Describe alternatives you've considered

Trying Temporal anti-aliasing (TAA) using the `-CTAA` launch command is pretty decent in Desktop mode, but in VR it becomes uncomfortably blurry and sometimes smears details around objects or creates a strange "ghosting" effect when something is moving behind solid UIX panels or other UI elements. _Some of these negative effects are noticeable in desktop mode, but not as often._ 

I feel that FXAA is preferred over the more experimental TAA implementation, but is also not the perfect solution for text-clarity.

### Additional Context

Here's some examples on how disabling FXAA can make text easier to read.
Below is two screenshots which shows a Box, Inspector, and some sample text. 

## Here's a full 1920 width screenshot of a sample scene with FXAA enabled as default.
![20231016213822_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/6eeb7581-bd1d-407e-8f4f-0ee7b5de89b3)

## Now, here's the same scene without FXAA.
![20231016213846_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/7ce0edf4-d235-4bb2-8943-9574fbd7d313)

## Here's both of those inspectors up close.
Pay extra attention to the clarity difference on the right sides of the panels, the text is much more clear without the anti-aliasing.
_*Fullscreen may be required to see the detail loss on images._
![FXAACompare](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/49619936/e85b76b9-7c28-477b-824c-62fc7430bb84)

_*These screenshots were taken using a specialized mod to disable FXAA, this issue was written with hopes of getting these options natively implemented. Other mods may also be visible in the sample screenshots._

**Comment by Frooxius** [comment]
You can now configure AA in 2024.4.17.1420, thanks!
