### ISSUE TITLE
Create text file from string

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#2448]
### Is your feature request related to a problem? Please describe.

If I heard correctly [Write Text To File](https://wiki.resonite.com/ProtoFlux:Write_Text_To_File) has been created to allow researchers to export data out of Resonite.
Unfortunately it is inherently unsafe which is why it is only available within unsafe sessions.
I personally also have a use-case where I want to export data of different text-based formats. (CSV, JSON, AnimJ)

### Describe the solution you'd like

I want to be able to create an importable/exportable file object within the world like this from ProtoFlux:
![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/fef48808-6e71-45b2-a098-82cf6a6f9b3f)
This would be much safer than `WriteTextToFile` because it needs user interaction to use this file.

### Describe alternatives you've considered

The extra steps needed to get the file object out of Resonite make it more likely to forget saving it, though. So other ways to export data like communicating with external tools are still an option.
I personally would still love to have a nice workflow if you could generate AnimJ or similar files and just reimport them in-world.

### Additional Context

My own use-case is related to my logging tool [Flight Data Recorder](https://discord.com/channels/1040316820650991766/1202422002611126292).
Adding this feature will enable a full MoCap data workflow from recording to final usage.

**Comment by Electronus** [comment]
You can do this by writing to a string field with a text exportable.

**Comment by Frooxius** [comment]
Yes, @Electronus is correct, you can already do this with the TextExportable.

If there's anything missing with that solution, feel free to open issue about it and we'll look at that, but I'm going to close this issue.
