### ISSUE TITLE
Add matcap mask field to Xiexetoon Shader

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#2454]
### Is your feature request related to a problem? Please describe.

The current version of the Xiexetoon shader in Resonite does not have the matcap mask field available, limiting the usefulness of matcaps and creating a layer of friction bringing in models designed around toon shaders and matcaps. 

### Describe the solution you'd like

Adding a field to add matcap masks, allowing you to define regions that the matcap will effect similar to emission masks.

### Describe alternatives you've considered

Splitting the model up to use an extra material slot for each intended matcap region.

### Additional Context

I think this is an included feature in the version of XSToon Resonite uses but I can't be certain since the really old versions have all been deleted from the internet.

**Comment by Geenz** [comment]
We will not be doing this with Xiexe as we will be deprecating this shader in the near future and replacing it with our own.  For any toon shader feature requests I encourage joining the conversation here: https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/1184
