### ISSUE TITLE
Glue Tool Context Menu text is broken

### ISSUE THREAD

**Issue by lill-la** [Yellow-Dog-Man/Resonite-Issues#246]
### Describe the bug?

The text displayed when the ContextMenu is opened with GlueTool equipped is broken.

### To Reproduce

Equip GlueTool.
It reproduces equally well with the default GlueTip or one created by attaching the GlueTool from the inspector.
It was reproduced even after changing the locale.

### Expected behavior

Strings set in the locale file are displayed.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44998659/957c93d2-1a11-42c5-ae6d-379d40978413)

### Resonite Version Number

Beta 2023.10.17.464

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[FEIRIL - 2023.10.17.464 - 2023-10-17 17_17_48.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12926255/FEIRIL.-.2023.10.17.464.-.2023-10-17.17_17_48.log)

### Additional Context

"Beta 2023.10.13.743" are showing up fine.

### Reporters

lill, zozokasu, Aetoriz

**Comment by ProbablePrime** [comment]
Taking a look here, thanks!
