### ISSUE TITLE
user leave does not respond with the user when the user leaves

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2460]
### Describe the bug?

when a user leaves the session with a user leave node plugged into a ObjectWrite<user>
the user doesn't get output from the user leave node but the pulse does.

### To Reproduce

grab 2 people, go into a world regardless if it's a headless or not. 
place down a user leave node, grab a ObjectWrite<user> and pull a output to view the output from a datamodelstore.
the output doesn't show when a user leaves.

### Expected behavior

the user shows in the datamodel store or for that matter any store/ouput.

### Resonite Version Number

Beta 2024.6.25.1149

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 1

### Log Files

i have none for this issue sorry. 
it shoudn't matter if it's a node that gets a user right?

### Reporters

@Charlie-sans @MrTumnus

**Comment by art0007i** [comment]
the user is there at the time of leaving but not after that because they left. try storing the username or userid instead of the user itself

**Comment by charlie-sans** [comment]
we can't get the user at all from it
don't know why

**Comment by Nytra** [comment]
@charlie-sans when the user leaves their user object becomes null, you can't store it if they are gone

**Comment by ProbablePrime** [comment]
This is working as intended. As others have said, when a user is completely done leaving the world they will not exist in the world's structure which means that variables referring to the actual user will be blanked out. User objects do not stay around once a user has left.

For the User Left node, you should do all operations you need to do with the outputs from that node in one go. For example you can write their username to another variable as others have said.

You cannot use display nodes or refer to the data after the call chain has completed. 

If you're still having issues, please provide a photo of your ProtoFlux nodes.

**Comment by ProbablePrime** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/cd065906-3067-4ac0-ae01-cf50f855bd48)
This setup should work as an example.
