### ISSUE TITLE
PBS_RimSpecular broken/missing shader variant

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#2463]
### Describe the bug?

Variant 11 of PBS_RimSpecular appears to have broken recently. This is just with a texture placed in `AlbedoTexture` and `SpecularMap`.

### To Reproduce

Create a new `PBS_RimSpecular` material
Apply it to an object
Add a texture to both `AlbedoTexture` and `SpecularMap`
For demonstration, I used a `SimplexTexture`
Observe Variant change to 11 and 'Waiting for apply: True' after a little bit the material changes to the error magenta color. or the placeholder checkerboard material.

### Expected behavior

The shader variant to be available instead of "NotFound"

### Screenshots

![9e52cc835f](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/625ad750-5386-4a69-a836-c41b2579f5bb)

### Resonite Version Number

Beta 2024.6.25.1149

### What Platforms does this occur on?

Windows

### Log Files

```
10:08:12 AM.764 (144 FPS)	Failed gather for resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, path: V:\Resonite\Cache\i7t129rwyiibw51z
GatherJob resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, State: Failed, StatusCode: , Progress: 0.00, Started: 1/1/0001 12:00:00 AM
10:08:18 AM.095 (144 FPS)	Failed gather for resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, path: V:\Resonite\Cache\s29m3lh38ccr6t5t
GatherJob resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, State: Failed, StatusCode: NotFound, Progress: 0.00, Started: 1/1/0001 12:00:00 AM
10:08:23 AM.437 (144 FPS)	Failed gather for resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, path: V:\Resonite\Cache\eowj9dvo2p1xi4w2
GatherJob resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, State: Failed, StatusCode: NotFound, Progress: 0.00, Started: 1/1/0001 12:00:00 AM
10:08:25 AM.826 (147 FPS)	Session updated, forcing status update
10:08:28 AM.725 (144 FPS)	Failed gather for resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, path: V:\Resonite\Cache\aasbq26e4c7q8i0i
GatherJob resdb:///1ef6752fc1971cd8ba92c9f0a129a3044a36dac1b66b65a13973700672f1e4ab.unityshader?variant=00000011&platform=WindowsDX11, State: Failed, StatusCode: NotFound, Progress: 0.00, Started: 1/1/0001 12:00:00 AM
```

### Additional Context
Replication item (in folder): `resrec:///U-Delta/R-BB1765AABE4EB74FE154229D3065EAE99E40773FBD990DD23B8179693CB47E66` 

### Reporters

_deltawolf

**Comment by Geenz** [comment]
Does `Waiting for apply: True` ever change to `False` after it's went pink or checkerboard?  This could be an indication that the shader is stuck somewhere in the variant queue.

**Comment by XDelta** [comment]
No it doesn't change to false. We noticed it a few days ago and once again yesterday in a session and it remained this way for the entire several hour session.

**Comment by shiftyscales** [comment]
Assigning @Geenz to follow-up / look into this when possible.

**Comment by XDelta** [comment]
Seems to be resolved now. Looked through images/recordings to narrow down the time frame and this appears to have been caused by the shader update on 6/24 and somewhere between 7/6 and 7/11 the variant was finally processed. Odd that it took ~2 weeks to do so.

**Comment by Geenz** [comment]
Yeah, that is a really weird one.  It's possible it got held up in the AVS somewhere - which does tend to happen from time to time.  I want to do a deeper investigation on our shader variant processing in the near future as we're gonna need to revisit it for Sauce soonish.
