### ISSUE TITLE
When launching in VR mode, with VR Hotswitching disabled, app loads in Desktop mode by default

### ISSUE THREAD

**Issue by ikanimew** [Yellow-Dog-Man/Resonite-Issues#247]
### Describe the bug?

If I launch Resonite in VR mode (Steam VR running, launch app from Steam library) it will load in VR mode, but then switch to Desktop mode until I press F8. This only happens when VR Hotswitching is disabled.

### To Reproduce

In app, disable VR Hotswitching
Close, and then launch the app with SteamVR running, specifically launching from the Steam library, not from SteamVR home.
Loading will occur in VR mode, then switch to Desktop mode once cloud home is loaded

### Expected behavior

Ideally when launching with SteamVR running, the app should stay in VR mode by default.

### Screenshots

![0e166ac077ea38a1844cfcd516b48f78](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2838766/bed57b0f-a5ea-40d7-8587-d3f3848aab46)
![47e9c98ab29f934283383b657eb40915](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2838766/954549ac-b599-4c18-a387-3f73dab32015)

### Resonite Version Number

2023.10.17.464

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[DISPLACER - 2023.10.17.464 - 2023-10-17 01_20_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12926294/DISPLACER.-.2023.10.17.464.-.2023-10-17.01_20_35.log)

### Reporters

Ikani

**Comment by Ardescar** [comment]
Yes same here - but i do have Valve Index as headset. 
I need to press F8 to be in VR always. I was wondering if something is broken on my index.
[DESKTOP-T7AIKEN - 2023.10.17.464 - 2023-10-17 10_46_03.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12926507/DESKTOP-T7AIKEN.-.2023.10.17.464.-.2023-10-17.10_46_03.log)

As we talk about this - when hotswitching is disabled then it would be good that it switches to VR instead to desktop per default.

**Comment by Frooxius** [comment]
This should be fixed in 2023.10.18.449! Thanks!
