### ISSUE TITLE
Update yt-dlp

### ISSUE THREAD

**Issue by Azavit** [Yellow-Dog-Man/Resonite-Issues#2471]
### Is your feature request related to a problem? Please describe.

Currently links from x.com do not work due to out of date yt-dlp though other issues may also be caused by this.

### Describe the solution you'd like

A newer version of yt-dlp
or
A system to automatically update yt-dlp when there is updates similar to [Raidriar796/yt-dlp-Updater](https://github.com/Raidriar796/yt-dlp-Updater)

### Describe alternatives you've considered

Having users manually update yt-dlp when there is changes.
Have users install the mod listed above.

### Additional Context

I tried loading in the following video https://x.com/Frooxius/status/1801837630906372592 which failed to load in.  Manually updating yt-dlp and trying the link again loaded it into the world perfectly, though others in the world with out of date yt-dlp could not see the video

### Requesters

Azavit, Gawdl3y

**Comment by Zyro1331** [comment]
YouTube videos do not load anymore after YouTube made minor updates to their service, so a version bump of yt-dlp would be very appreciated. 
I believe Resonite currently ships with yt-dlp 2024.03.10 currently, and the latest version as of writing is yt-dlp 2024.07.09. Two CVEs have been identified and patched out between these releases.

**Comment by Frooxius** [comment]
I'll include updated version in the next build.

**Comment by Frooxius** [comment]
Updated in 2024.7.10.1399, thanks!
