### ISSUE TITLE
Importing 360 HDR Skybox causes Severe Lockup and Crash

### ISSUE THREAD

**Issue by skywindkitsune** [Yellow-Dog-Man/Resonite-Issues#2472]
### Describe the bug?

When attempting to import an HDR 4K Skybox, Resonite begins using up my entire CPU and Ram to the point that it crashes itself, this was not a problem before the recent updates.

Additionally Baking a Reflection probe causes the same severe lockup, there must be something wrong with 360 photo processing.

CPU: AMD Ryzen 5 5600K
Ram: 16 GB of Ram
Graphics card: Nvidia GeForce RTX3070 Ti

### To Reproduce

Download and import the 4K HDR version of this skybox:
https://polyhaven.com/a/meadow_2

A few minutes later your PC will begin to lockup and eventually crash with a runaway memory leak.

### Expected behavior

Import the file successfully without Resonite going ballistic on the ram.

### Screenshots

![Screenshot 2024-07-05 020744](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/72045840/51b1518f-de91-4bf7-b961-faa116741d6b)

### Resonite Version Number

2024.7.4.1347

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus Quest 3

### Log Files

No Crash Log generated

### Reporters

Skywind Kitsune, Sctanf

**Comment by ko-tengu** [comment]
This is probably related to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1983, since a handful of comments connect that to general HDR image handling.
