### ISSUE TITLE
Add strip tags toggle to the ButtonClipboardCopyText

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2475]
### Is your feature request related to a problem? Please describe.

I really want to use the <b>ButtonClipboardCopyText</b> Component but currently it doesn't strip tags which results in formatting being copied to the clipboard which is not preferable

### Describe the solution you'd like

It shouldn't copy the formatting
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/ef2d9b38-c717-4ab6-9833-5a67262c3640)

It should preferably look like this when being copied
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/33c5de48-8235-4d3d-a6eb-e8d5fab5d8ea)

### Describe alternatives you've considered

Using flux to drive a value field That strips the tags but this seems like an unnecessary step but this seems like an unnecessary step

### Additional Context

I am the main maintainer of a Mastodon client completely in game And I give users an option to copy the text of the post with mentions, hashtags and Urls they need to be formatted like so But I don't want this to be copied to the users clipboard as that could be really annoying when using text to speech utilities

### Requesters

@epicEaston197

**Comment by 5H4D0W-X** [comment]
You can strip tags with flux (there's a dedicated node) and drive a ValueField<string> that the component can copy from

**Comment by epicEaston197** [comment]
> You can strip tags with flux (there's a dedicated node) and drive a ValueField that the component can copy from

Yeah but why should I do that?
It should just have a toggle for it

**Comment by Frooxius** [comment]
Stripping the tags is not really responsibility of the button.

Generally we try to enforce decomposition of responsibilities and this would be one of the reasons.

Say you need stripping of the tags. Someone else might need the text to get capitalized. Or reformatted in different way. Or truncated. Or perhaps replace some susbtrings in it. Or append extra things.

There's lots of transformations that could be needed to be done to the text and the copy button should not care about any of them - it's job is to copy the text verbatim, assuming you did all those transformations already.

If we were to bake all that functionality to the button component, it would become very bloated.

But with those being operations you can compose yourself, you can do whatever you want to the text and just give it the text yup wanted copied.

For that reason we wouldn't add this to the button component.
