### ISSUE TITLE
Class name for Continuous Relays spelled as 'Continously'

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#248]
### Describe the bug?

`ContinouslyChangingObjectRelay` and `ContinouslyChangingValueRelay` node classes are spelled incorrectly resulting in the generated component and slot name to also be named that way.

Additionally spotted:
`ContinouslyChangingAttribute`
The `Continous` option on `ButtonPlaybackSeeker`

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

All

### Reporters

_deltawolf

**Comment by Frooxius** [comment]
Fixed the naming in 2023.11.8.335, thanks!
