### ISSUE TITLE
Resonite gets stuck in preview resolution if steamVR dashboard is open while connected over Steamlink

### ISSUE THREAD

**Issue by RadioFoxProductions** [Yellow-Dog-Man/Resonite-Issues#2483]
### Describe the bug?

Hello! i use steam link with my Meta Quest Pro, but i've also had this bug occur with a Quest 2 and 3.

if the steamVR dashboard is open while loading into game or loading a world or session, Resonite appears to get stuck in the StemVR dashboard resoluion (I.e. The game is rendering at a lower resolution while steamVR dash is open, and gets stuck that way when closed)

### To Reproduce

1. connect to your PC with Steam Link on a Meta VR headset
2. Launch resonite
3. leave steamVR dashboard open while loading into the game or a world/session.

i haven't been able to get it to happen every single time reliably, but it happens frequently enough its a rather annoying bug

### Expected behavior

Resonite switching back to the proper rendered resolution when steamVR dashboard is closed

### Resonite Version Number

2024.7.4.1347

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[RADIA-DVS-DEVIC - 2024.7.4.1347 - 2024-07-06 01_42_47.log](https://github.com/user-attachments/files/16115101/RADIA-DVS-DEVIC.-.2024.7.4.1347.-.2024-07-06.01_42_47.log)

### Reporters

radiofoxproductions

**Comment by Geenz** [comment]
This is going to be either a Unity or SteamVR bug.  I'd say this will be more fixable after Sauce.

**Comment by ko-tengu** [comment]
This is a duplicate of my issue ( https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2337 ) but there's not even the possibility of just not reducing the resolution when you open the steamvr dash? it's not a mandatory feature and most VR games I play don't do that.
