### ISSUE TITLE
Common Generic Types list doesn't use correct label

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Resonite-Issues#2489]
### Describe the bug?

When creating an instance of a generic type with the component selector, the list of preset concrete versions is labeled "Custom Generic Arguments", rather than "Common Generic Types". This is the name of the input fields above that.

### To Reproduce

* Spawn a Component Selector
* Navigate to a generic component

### Expected behavior

The lower section should be labeled as "Common Generic Types" (locale key `ComponentSelector.CommonGenericTypes`).

This issue is in the method `ComponentSelector.BuildUI`.

### Screenshots

![Screenshot of component selector showing the wrong label](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/5af06cb7-7425-4bd3-a3de-dd7e10f1e83a)

### Resonite Version Number

Beta 2024.7.4.1347

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

N/A

### Log Files

N/A

### Additional Context

N/A

### Reporters

[Bb]anane9

**Comment by Nytra** [comment]
I encountered the same thing. Here's a log file:

[DESKTOP-H976HO2 - 2024.7.4.1347 - 2024-07-08 17_28_36.log](https://github.com/user-attachments/files/16132027/DESKTOP-H976HO2.-.2024.7.4.1347.-.2024-07-08.17_28_36.log)

**Comment by shiftyscales** [comment]
Assigning @BlueCyro - this should be a quick line to edit.

**Comment by BlueCyro** [comment]
Done & dusted

**Comment by Frooxius** [comment]
Merged fix in 2024.7.10.1399, thanks!
