### ISSUE TITLE
Allow headless to show a session that doesn't have a create world option for public worlds and is completely separate

### ISSUE THREAD

**Issue by Synkstar** [Yellow-Dog-Man/Resonite-Issues#249]
### Is your feature request related to a problem? Please describe.

When you create a headless session using a world template it will show the world name as the session name in the list and not allow people to create a session under the same category. The idea is to make this possible with public worlds.

### Describe the solution you'd like

Add a configuration option to change the behavior.

### Describe alternatives you've considered

The ability to make a world private and sharing it with specific accounts and changing the name of a copied world is an alternative.

**Comment by kulzae** [comment]
already possible with the  overrideCorrespondingWorldId field in the headless config

example of use

      "overrideCorrespondingWorldId" :
      {
        "recordId" : "R-RecordIDYourOverridingItWIth",
        "ownerId" : "U-OwnerOfRecord"
      },

**Comment by shiftyscales** [comment]
It sounds like the above functionality should meet your needs, @Synkstar - so I'll close this issue. If it doesn't for some reason- please feel free to comment so this issue can be re-opened, or make a new issue.
