### ISSUE TITLE
Multiple dash tabs do not load on Prerelease build

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2491]
### Describe the issue.

On Prerelease build 2024.7.7.1295, the Worlds, Settings and Migration tabs do not show up.

### To Reproduce

Launch Resonite on the prerelease build

Observe that the worlds / settings / migration tabs do not load

### Expected behavior

For all dash tabs to load

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/e26a2038-bdea-43fb-9844-3aef5b6b50c6)

### Resonite Version Number

Beta 2024.7.7.1295 (Prerelease)

### What Platforms does this occur on?

Windows

### Log Files

[DYSNOMIA - 2024.7.7.1295 - 2024-07-08 10_21_46.log](https://github.com/user-attachments/files/16120977/DYSNOMIA.-.2024.7.7.1295.-.2024-07-08.10_21_46.log)

### Reporters

bredo, epicEaston197, ModernBalloonie, coolymike

**Comment by epicEaston197** [comment]
It appears that the setting components are not a part of the data model they all appear as missing
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/2a6fd9fd-e08d-47e4-959a-76fa5fe672da)

**Comment by ModernBalloonie** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/9b057874-11de-41fc-9d28-5daab2d578f3)
Hmm, so the user data feed seems to be broken too. i'll have to get a log in a sec.

**Comment by ModernBalloonie** [comment]
![2024-07-07 23 25 39](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/75dfb8b5-6f5b-48cc-a587-bb45545244d8)
Seems that the datafeeditemmapper on the settings menu, the types are nulled!

**Comment by Zyro1331** [comment]
I didn't have an issue loading the Worlds Menu, everything appeared as normal, including my own custom facets were working fine too. I don't have a Migration screen so I couldn't test that, though I can though confirm my settings menu was completely blank however. 
[MANGOVRG - 2024.7.7.1295 - 2024-07-07 19_12_56.log](https://github.com/user-attachments/files/16122060/MANGOVRG.-.2024.7.7.1295.-.2024-07-07.19_12_56.log)

**Comment by bredo228** [comment]
> I didn't have an issue loading the Worlds Menu, everything was functional including my own custom world facet on my Home screen. I don't have a Migration tab so I couldn't test that, though I can though confirm my settings menu was completely blank as reported above.

Interestingly enough, when I signed in on my main Resonite account the Worlds and Migrations tab both loaded - I could only get them to not load on my `Portable bredo` account.

**Comment by Frooxius** [comment]
This should be fixed with 2024.7.8.1130, thanks!

**Comment by bredo228** [comment]
Yep, appears fixed. Thank you!
