### ISSUE TITLE
[prerelease] Cameras do not work in multiplayer

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2494]
### Describe the bug?

Whenever someone joins my session all cameras cease to function including my HUD camera 
Cameras used in my dash (User space) Work perfectly fine

### To Reproduce

Spawn a camera and have someone join your session you'll notice it will stop rendering

### Expected behavior

The camera should render no matter how many people are in the world

### Screenshots
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/b27572e6-af45-4f81-b520-1aa569844b75
### Resonite Version Number

Beta 2024.7.7.1295

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[EPICEASTON197 - 2024.7.7.1295 - 2024-07-07 19_35_38.log](https://github.com/user-attachments/files/16121314/EPICEASTON197.-.2024.7.7.1295.-.2024-07-07.19_35_38.log)

### Reporters

@epicEaston197 modernballoonie

**Comment by epicEaston197** [comment]
This is on the pre release build I accidentally reported it as a bug issue instead of the prerelease

**Comment by shiftyscales** [comment]
As a quick reminder @epicEaston197 @ModernBalloonie - it is helpful to press F3 before and after replication of an issue as it inserts markers into the log file that make any relevant exceptions easier to find.

**Comment by Frooxius** [comment]
I was not able to replicate this or find anything in the log. 

Can you retest on 2024.7.8.1130 please?

**Comment by epicEaston197** [comment]
> I was not able to replicate this or find anything in the log.
> 
> Can you retest on 2024.7.8.1130 please?

In order for me to do this I'll need someone else to be on the build (Which is really hard to do)

**Comment by epicEaston197** [comment]
@Frooxius This issue can be closed It has been resolved
