### ISSUE TITLE
Add a way of rejoining a session via a single button

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2500]
### Is your feature request related to a problem? Please describe.

Sometimes I need to rejoin a session and this involves me needing to leave the session look for the session again through my contacts or the world browser clicking on it and clicking join

### Describe the solution you'd like

I want a single button that I can double press that makes me leave the session then rejoin that session right after

### Describe alternatives you've considered

There are ways of doing this in flux but it's really scuffed

### Additional Context

I used a rejoin facet very often and it was really useful but it broke during migration

### Requesters

@epicEaston197

**Comment by JackTheFoxOtter** [comment]
When do you need to rejoin a session? Why is respawning not an option in those situations?

**Comment by epicEaston197** [comment]
> When do you need to rejoin a session? Why is respawning not an option in those situations?

Do you think most of the time....
But other social VR platforms have a button to rejoin the session

**Comment by JackTheFoxOtter** [comment]
From my understanding the rejoin option in other social VR platforms exists in case the local state gets too desynced from the expected state, so you re-connect to reset your local world state.

In Resonite, the data model always keep your local state in sync with the world state. The only situation I know when that's not the case is desync, but there I feel like a "rejoin" button would be a bit of a bandaid solution, and the underlying issue is you desyncing in the first place.

**Comment by JackTheFoxOtter** [comment]
In either case, if something like this would be implemented I wouldn't think it would be "rejoining", it would be more like discarding all queued messages and force re-syncing the world state. I wouldn't think you'd need to leave the world for that.

**Comment by ExoTheWicker** [comment]
I feel this shouldn't be implemented as desync is a networking issue (typically) on the user side of things.

This might be mitigated by the new window size setting and the soon-to-be-implemented dynamic window sizing.

I would suggest tinkering with the mentioned setting or finding ways to improve your networking setup.

**Comment by shiftyscales** [comment]
> desync mostly...

It seems your underlying concern is on packet queueing which is something the recent LNL window size pre-release build was looking to help improve: https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/2438

There will be continued work in that area in future to make the window size scale more dynamically based on network conditions.

If you are still experiencing issues, I would recommend trying out different values with that setting and seeing if it helps, @epicEaston197.

As such I will be closing this issue as there are better ways to resolve packet queueing than having a band-aid solution that requires the user to leave and rejoin the session.
