### ISSUE TITLE
Loading a StaticTexture2D in an Inspector causes a World Crash

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#2503]
### Describe the issue.

Upon opening an inspector to a Slot with a StaticTexture2D component, along with multiple users present, the world will immediately crash.

### To Reproduce

1. Invite a contact or have another user present in your session.
2. Spawn an image via a local import, or just make an empty object and attach a StaticTexture2D component to it.
3. Select the Slot with an Inspector.

### Expected behavior

The component should display in the inspector without a world crash.

### Resonite Version Number

Beta 2024.7.8.1130

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MANGOVRG - 2024.7.8.1130 - 2024-07-08 12_15_55.log](https://github.com/user-attachments/files/16133742/MANGOVRG.-.2024.7.8.1130.-.2024-07-08.12_15_55.log)
(Log file is a tiny bit messy as it was done amongst other tests.

### Additional Context

I am not sure if it's just the component being displayed in the Inspector that causes the crash, but something about the affected Slot with the component just causes a world crash upon the inspector selecting it.

### Reporters

@zyro1331
@epicEaston197

**Comment by epicEaston197** [comment]
I will also toss my login here as well
[EPICEASTON197 - 2024.7.8.1130 - 2024-07-08 15_15_59.log](https://github.com/user-attachments/files/16133740/EPICEASTON197.-.2024.7.8.1130.-.2024-07-08.15_15_59.log)
(Unfortunately not a completely clean one since Zyro got off

**Comment by Zyro1331** [comment]
Can confirm, single-user sessions don't crash upon loading. Only in a multi-user session does it cause world crashes.

**Comment by Zyro1331** [comment]
More further observations, which might be tangentially related to this. 
Clicking on a component with a generic type in the Component Browser, or ProtoFlux browser causes other users to World Crash except for the locally invoking user.

**Comment by Zyro1331** [comment]
Give me a moment, I'll attach logs for that too.

**Comment by Frooxius** [comment]
Should be fixed in 2024.7.8.1285, thanks!
