### ISSUE TITLE
Generating a component browser with Generic Types crashes other users.

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#2505]
### Describe the issue.

Opening a component browser and navigating to a generic type will cause other users present in your session to World crash. The component browser will generate fine locally, but other users will world crash.

### To Reproduce

1. Invite other users to your session.
2. Spawn a component browser, or ProtoFlux browser, and find a component or node with a generic type. <i>*(Anything that's green with a <T> on it)</i>
3. Watch other users connected suddenly disconnect.

### Expected behavior

The component browser should not crash the other users connected.

### Resonite Version Number

Beta 2024.7.8.1130

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MANGOVRG - 2024.7.8.1130 - 2024-07-08 12_31_44.log](https://github.com/user-attachments/files/16133989/MANGOVRG.-.2024.7.8.1130.-.2024-07-08.12_31_44.log)

### Additional Context

Very, very similar to Issue #2503 but found in a different way, with slightly different behavior. 

### Reporters

@zyro1331
@epicEaston197

**Comment by epicEaston197** [comment]
[EPICEASTON197 - 2024.7.8.1130 - 2024-07-08 15_53_03.log](https://github.com/user-attachments/files/16134036/EPICEASTON197.-.2024.7.8.1130.-.2024-07-08.15_53_03.log)

**Comment by epicEaston197** [comment]
[Uploading EPICEASTON197 - 2024.7.8.1130 - 2024-07-08 15_24_40.log…]()

**Comment by epicEaston197** [comment]
[EPICEASTON197 - 2024.7.8.1130 - 2024-07-08 15_24_40.log](https://github.com/user-attachments/files/16134067/EPICEASTON197.-.2024.7.8.1130.-.2024-07-08.15_24_40.log)

**Comment by epicEaston197** [comment]
[EPICEASTON197 - 2024.7.8.1130 - 2024-07-08 16_11_18.log](https://github.com/user-attachments/files/16134150/EPICEASTON197.-.2024.7.8.1130.-.2024-07-08.16_11_18.log)

**Comment by Zyro1331** [comment]
Here's a cleaner log of me entering Easton's world, them spawning a ProtoFlux browser, and then clicking on a generic type node.
[MANGOVRG - 2023.9.24.1365 - 2023-09-24 19_27_29.log](https://github.com/user-attachments/files/16134155/MANGOVRG.-.2023.9.24.1365.-.2023-09-24.19_27_29.log)

**Comment by Zyro1331** [comment]
Here's a cleaner log of me entering Easton's world, them spawning a ProtoFlux browser, and then clicking on a generic type node.
[MANGOVRG - 2024.7.8.1130 - 2024-07-08 13_10_59.log](https://github.com/user-attachments/files/16134166/MANGOVRG.-.2024.7.8.1130.-.2024-07-08.13_10_59.log)

**Comment by Frooxius** [comment]
This is fixed in 2024.7.8.1285, thanks for report!
