### ISSUE TITLE
Missing data model type FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.ContinouslyChangingObjectRelay`1

### ISSUE THREAD

**Issue by coolymike** [Yellow-Dog-Man/Resonite-Issues#2506]
### Describe the issue.

The type `FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.ContinouslyChangingObjectRelay`1` is not a data model type, but is used in the game.

### To Reproduce

Spawn ProtoFlux tool by pressing `3` on a keyboard. Observe the logs.

### Expected behavior

-

### Resonite Version Number

2024.7.8.1130

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Desktop

### Log Files

```
22:03:40.809 (639 FPS)	Assembly  is not a data model assembly for this world, cannot decode type: FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.ContinouslyChangingObjectRelay`1
22:03:40.810 (639 FPS)	Type not found: FrooxEngine.ProtoFlux.Runtimes.Execution.Nodes.ContinouslyChangingObjectRelay`1
```

### Reporters

whippersnatchpumpkinpatch on Discord

**Comment by Frooxius** [comment]
Fixed this in 2024.7.8.1285, thanks!
