### ISSUE TITLE
Text not showing up in worlds menu.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2509]
### Describe the issue.

The text showing the categories in the worlds menu has broken.

### To Reproduce

Open your worlds menu.

### Expected behavior

Well, for text to show up.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/2e499f18-1031-4439-9f91-632a5ccc6bec)

### Resonite Version Number

Beta 2024.7.8.1285

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Quest Pro

### Log Files

[DESKTOP-QBGCSAQ - 2024.7.8.1285 - 2024-07-08 14_40_24.log](https://github.com/user-attachments/files/16134695/DESKTOP-QBGCSAQ.-.2024.7.8.1285.-.2024-07-08.14_40_24.log)

### Reporters

ModernBalloonie

**Comment by Frooxius** [comment]
I just tested mine, but I can't replicate it.

1) Did this just happen on this build?
2) Does this happen on every launch? 
3) If you go to the normal build, is the text back?
4) Does this persist even if you do -ResetDash? (or just spawn out the facet preset from essentials)

**Comment by ModernBalloonie** [comment]
> I just tested mine, but I can't replicate it.
> 
> 1. Did this just happen on this build?
> 2. Does this happen on every launch?
> 3. If you go to the normal build, is the text back?
> 4. Does this persist even if you do -ResetDash? (or just spawn out the facet preset from essentials)

It just happened on this build, I launched Resonite twice and the text was gone both times.
I went to the normal build and the text is fine. I just decided to start the prerelease again, and the text is still gone.

I kind of want to try resetting the dash but I have a lot of things set up currently.

Interestingly, I tried logging out, and the text is fine there. Huh, must be a me problem.

**Comment by shiftyscales** [comment]
Things are working fine here too- this suggests it is likely your copy of the facets in particular that have that issue, @ModernBalloonie.

Can you check against the presets from the essentials folder as Frooxius suggested as well?

**Comment by ModernBalloonie** [comment]
> Things are working fine here too- this suggests it is likely your copy of the facets in particular that have that issue, @ModernBalloonie.
> 
> Can you check against the presets from the essentials folder as Frooxius suggested as well?

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/3d51dce7-0627-42cc-81e9-c999a3027587)
There doesn't appear to be a worlds facet in there.

**Comment by shiftyscales** [comment]
I see- in which case, create a new slot, and attach the `WorldFilterFacetPreset`, @ModernBalloonie. Attach Component > Radiant UI > Facets.

**Comment by ModernBalloonie** [comment]
> I see- in which case, create a new slot, and attach the `WorldFilterFacetPreset`, @ModernBalloonie. Attach Component > Radiant UI > Facets.

Hmm, so if I do that, it's fine. I think maybe it's just something wrong with my menu in particular for some reason.

**Comment by shiftyscales** [comment]
Could you look into your copy of your facets to see what is different about them compared to a stock one, @ModernBalloonie? Otherwise- are you aware of any other users that are having this issue with the prerelease build?

**Comment by Frooxius** [comment]
Does this still occur?

**Comment by ModernBalloonie** [comment]
It seems to have fixed itself. Maybe I should close it.
