### ISSUE TITLE
Type fields can no longer be filled out by typing 'simple' type strings

### ISSUE THREAD

**Issue by BlueCyro** [Yellow-Dog-Man/Resonite-Issues#2511]
### Describe the issue.

When typing into a TypeField on the prerelease branch of the client, you can no longer type simple type names like "Spinner" or "BoxCollider" into the text entry. You must now prepend "FrooxEngine" to the type, e.g. "FrooxEngine.Spinner" or "FrooxEngine.BoxCollider"

Whereas on the main branch (currently `2024.7.8.1285` at the time of writing), you can type just "Spinner" or "BoxCollider" without having to prepend anything.

### To Reproduce

1) Create an empty object
2) Attach a TypeField
3) Attempt to type a simple type name like the examples above
4) Note that the type returns to null

### Expected behavior

The field should behave as it does in the main branch of Resonite.

### Resonite Version Number

2024.7.8.1285

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-6C2UJFB - 2024.7.8.1285 - 2024-07-08 22_45_32.log](https://github.com/user-attachments/files/16137666/DESKTOP-6C2UJFB.-.2024.7.8.1285.-.2024-07-08.22_45_32.log)

### Additional Context

The above log file is me opening the game, going to a world, typing the two examples I showed above, and then subsequently typing the "FrooxEngine"-prepended variations and closing the game.

### Reporters

Myself

**Comment by Frooxius** [comment]
Fixed this in 2024.7.9.1044, thanks!
