### ISSUE TITLE
DataModelTypeStore does not generate UI

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#2521]
### Describe the issue.

DataModelTypeStore nodes do not generate UI properly.

### To Reproduce

Create or unpack a DataModelTypeStore!

### Expected behavior

The UI should include a textfield where you can input the name of the variable.

### Screenshots

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/2d632329-d686-4e3e-b570-61210be1490d)

### Resonite Version Number

2024.7.10.1077

### What Platforms does this occur on?

Windows

### Log Files

[Anonymous - 2024.7.10.1077 - 2024-07-10 22_22_08.log](https://github.com/user-attachments/files/16168685/Anonymous.-.2024.7.10.1077.-.2024-07-10.22_22_08.log)

**Comment by Frooxius** [comment]
I just checked this - this is not a breakage on the prerelease, it happens on the normal build too.

As requested in the instructions, please verify that you're finding breakages that are related specifically to the prerelease and not on the main build!

I'm removing the prerelease label.

**Comment by stiefeljackal** [comment]
This is also a duplicate of #1912.

**Comment by mpmxyz** [comment]
> This is also a duplicate of #1912.

Huh, I didn't see that one. I was more busy on figuring out #2522 tbh.

**Comment by Frooxius** [comment]
@stiefeljackal Ah good catch, thanks! Marking as duplicate.
