### ISSUE TITLE
Cannot select ProtoFlux node types with type arguments containing a "+"

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#2525]
### Describe the issue.

I cannot create nodes like `IntToEnum<ReflectionProbe+Type>`.

### To Reproduce

Try selecting the node type `IntToEnum<ReflectionProbe+Type>` from the node browser!

### Expected behavior

The type should be selected and one should be able to create it with double-primary.

### Screenshots

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/056d738a-e4d2-4db1-898d-341c368e8a09)

### Resonite Version Number

2024.7.10.1338

### What Platforms does this occur on?

Windows

### Log Files

[Anonymous - 2024.7.10.1338 - 2024-07-11 00_49_13.log](https://github.com/user-attachments/files/16169647/Anonymous.-.2024.7.10.1338.-.2024-07-11.00_49_13.log)

**Comment by XDelta** [comment]
Tried with `ValueInput<ReflectionProbe+Type>`, which I was also unable to select in the protoflux browser. I was however able to create it from a `ReflectionProbe` component directly.
![aeb2854572](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/1b4bfc73-0530-49ee-9bd4-f311ee1d9ae7)

**Comment by Frooxius** [comment]
Fixed in 2024.7.11.1165, thanks!
