### ISSUE TITLE
legacy world switcher

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2526]
### Is your feature request related to a problem? Please describe.

i have a proposal, with the legacy world switcher possibly being removed with a new update, why not make it a feature again?

### Describe the solution you'd like

a new shiny uptodate world switcher with features that may help people with one hand?
sort of as in, when a user has one controller on at a time, or just doesn't have a second controller/hand to hold said hardware.
the menu sort of hovers out in front of you?

### Describe alternatives you've considered

making a mod that re adds it back by stringing world orbs across a wire.

### Requesters

@charlie_san

**Comment by paradoxical-autumn** [comment]
While I agree that this would be a helpful addition in the meantime, there're two issues that I can see:
- It'll be superseded by #2393 (if implemented by default)
- What would the gesture to activate it be? If we choose to have it be the dash open/close button, anyone using facet anchors can't open their dash of they activate both. It'd have to be on a chord, making the feature obscure, which ruins the point of it.

**Comment by Frooxius** [comment]
We're not going to keep this one around unfortunately. The facet will supersede this and the code for this switcher will be removed.

The reason for this is that the code is old and buggy. Anytime we touch parts of the world system, we need to update this old code too, which presents maintenance burden and increases complexity of updates.

**Comment by JackTheFoxOtter** [comment]
I would think there's nothing stopping you from building a completely custom world switcher however you prefer. I haven't made one myself yet, but with the WorldsDataFeed and the FocusWorld ProtoFlux node, you should have everything necessary for this.

**Comment by badhaloninja** [comment]
> I would think there's nothing stopping you from building a completely custom world switcher however you prefer. I haven't made one myself yet, but with the WorldsDataFeed and the FocusWorld ProtoFlux node, you should have everything necessary for this.

There's currently no way to get the world relation between opened worlds, so it's not currently possible to remake this 

World relation being, opening a world as nested vs independent, 
you can see these as options on the OpenWorld node

The default behavior when opening a world from anywhere is Nested

This is what determines how the worlds branch from each other in the legacy world switcher

**Comment by TisFoolish** [comment]
What is 'independent' in this context?
