### ISSUE TITLE
Selecting active sessions selects the contacts sessions and vice versa

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2536]
### Describe the bug?

When selecting the tab "Contacts sessions", it will also select the "Active sessions" tab in the world browser and vice versa.

### To Reproduce

1. Open Resonite
2. Go to the worlds tab
3. Click on "Contacts sessions"
4. Observe the active sessions are also selected

### Expected behavior

Either tab should be selected and not the two of them.

### Screenshots

![RuIo2UKulH](https://github.com/user-attachments/assets/43c4634b-92ed-4438-95cc-623957922105)

### Resonite Version Number

Beta 2024.7.11.1293

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Quest Pro

### Log Files

[TETHYS - 2024.7.11.1293 - 2024-07-12 01_12_41.log](https://github.com/user-attachments/files/16184167/TETHYS.-.2024.7.11.1293.-.2024-07-12.01_12_41.log)

### Additional Context

Reporting this as a bug instead of content issue as the issue wasn't present with the previous stable version (2024.7.10.1399).

**Comment by coolymike** [comment]
Related: #2512

**Comment by shiftyscales** [comment]
I am going to close and merge this into the linked issue #2512. While it is different tabs that are exhibiting the issue- it otherwise seems to be a duplicate.
