### ISSUE TITLE
net8.0: Can't launch Headless with Resonite.exe on Linux

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2540]
### Describe the issue.

When trying to run the headless by running `dotnet Resonite.exe` on linux, an exception is thrown and the headless does not start.

Using latest `dotnet-runtime-8.0` installed through Microsoft's instructions on Debian Linux

### To Reproduce

Run Resonite headless on .net 8.0 on Linux

### Expected behavior

Headless to launch

### Resonite Version Number

2024.7.12.12

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

```
bredo@testheadless:~/Resonite/Headless/net8.0$ dotnet Resonite.exe
Error:
  An assembly specified in the application dependencies manifest (Resonite.deps.json) has already been found but with a different file extension:
    package: 'Resonite', version: '1.0.0'
    path: 'Resonite.dll'
    previously found assembly: '/home/bredo/Resonite/Headless/net8.0/Resonite.exe'
bredo@testheadless:~/Resonite/Headless/net8.0$
```

### Reporters

bredo

**Comment by bredo228** [comment]
From Raidriar on Discord:
![image](https://github.com/user-attachments/assets/dd84686f-fee8-4701-8684-0f1cda171766)

Looks like this works, however I get a separate issue of the headless not launching. Will open another issue

**Comment by sveken** [comment]
This happens for me too on windows

**Comment by sveken** [comment]
Seems to work the same way on windows too.

**Comment by Frooxius** [comment]
I've removed the `Resonite.exe` from the Linux version to make it less confusing in 2024.7.12.933

Let me know if there's still some issues. Otherwise closing, thanks!

**Comment by bredo228** [comment]
Launching `Resonite.exe` on windows directly (by double clicking it) appears to work fine
