### ISSUE TITLE
Headless hangs on startup when trying to log in to a user account

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2541]
### Describe the issue.

When a user account is specified through `loginCredential` and `loginPassword` in the headless, the headless will hang on launch.

Additionally, when hitting CTRL+C to kill the process, it'll start the shutdown procedure and then hang, so you need to kill the process for it to close.

### To Reproduce

Run headless with user account specified in Config.json

### Expected behavior

Headless to start up and start hosting world

### Resonite Version Number

2024.7.12.12

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

[testheadless - 2024.7.12.12 - 2024-07-12 13_00_39.log](https://github.com/user-attachments/files/16185842/testheadless.-.2024.7.12.12.-.2024-07-12.13_00_39.log)

### Reporters

bredo, Raidriar796

**Comment by ExoTheWicker** [comment]
Same issue here
[SA-NODE1 - 2024.7.12.12 - 2024-07-12 00_52_50.log](https://github.com/user-attachments/files/16185856/SA-NODE1.-.2024.7.12.12.-.2024-07-12.00_52_50.log)
[SA-NODE1 - 2024.7.12.12 - 2024-07-12 00_57_03.log](https://github.com/user-attachments/files/16185857/SA-NODE1.-.2024.7.12.12.-.2024-07-12.00_57_03.log)
[SA-NODE1 - 2024.7.12.12 - 2024-07-12 00_59_48.log](https://github.com/user-attachments/files/16185858/SA-NODE1.-.2024.7.12.12.-.2024-07-12.00_59_48.log)
[SA-NODE1 - 2024.7.12.12 - 2024-07-12 01_00_35.log](https://github.com/user-attachments/files/16185859/SA-NODE1.-.2024.7.12.12.-.2024-07-12.01_00_35.log)
[SA-NODE1 - 2024.7.12.12 - 2024-07-12 01_01_34.log](https://github.com/user-attachments/files/16185860/SA-NODE1.-.2024.7.12.12.-.2024-07-12.01_01_34.log)
[SA-NODE1 - 2024.7.12.12 - 2024-07-12 01_03_56.log](https://github.com/user-attachments/files/16185861/SA-NODE1.-.2024.7.12.12.-.2024-07-12.01_03_56.log)

**Comment by ExoTheWicker** [comment]
I also had to kill the process using Tmux.

**Comment by bredo228** [comment]
Looks like it's not just a linux issue - ran on my Windows server and had the same issue.

[WINSERVER - 2024.7.12.12 - 2024-07-12 13_15_19.log](https://github.com/user-attachments/files/16185920/WINSERVER.-.2024.7.12.12.-.2024-07-12.13_15_19.log)

**Comment by sveken** [comment]
Same issue on Win11 with dotnet8 freshly installed from winget
[GREGS-FLOW - 2024.7.12.12 - 2024-07-12 11_21_48.log](https://github.com/user-attachments/files/16185987/GREGS-FLOW.-.2024.7.12.12.-.2024-07-12.11_21_48.log)

**Comment by jae1911** [comment]
Same issue happens when launching the headless without a config and trying to use the `login` command.

[TETHYS - 2024.7.12.12 - 2024-07-12 10_10_55.log](https://github.com/user-attachments/files/16189992/TETHYS.-.2024.7.12.12.-.2024-07-12.10_10_55.log)

**Comment by troyBORG** [comment]
Same thing 
[03_30_04.log](https://github.com/user-attachments/files/16190938/03_30_04.log)

**Comment by TeknoCatron** [comment]
Same story

Debian 12 dotnet 8

[TRD-42300 - 2024.7.12.12 - 2024-07-12 16_05_04.log](https://github.com/user-attachments/files/16195936/TRD-42300.-.2024.7.12.12.-.2024-07-12.16_05_04.log)
[TRD-42400 - 2024.7.12.12 - 2024-07-12 12_05_01.log](https://github.com/user-attachments/files/16195937/TRD-42400.-.2024.7.12.12.-.2024-07-12.12_05_01.log)
[TRD-42400 - 2024.7.12.12 - 2024-07-12 16_04_58.log](https://github.com/user-attachments/files/16195938/TRD-42400.-.2024.7.12.12.-.2024-07-12.16_04_58.log)
[TRD-AfterDark - 2024.7.12.12 - 2024-07-12 12_05_02.log](https://github.com/user-attachments/files/16195939/TRD-AfterDark.-.2024.7.12.12.-.2024-07-12.12_05_02.log)
[TRD-AfterDark - 2024.7.12.12 - 2024-07-12 15_50_52.log](https://github.com/user-attachments/files/16195940/TRD-AfterDark.-.2024.7.12.12.-.2024-07-12.15_50_52.log)
[TRD-AfterDark - 2024.7.12.12 - 2024-07-12 16_12_58.log](https://github.com/user-attachments/files/16195941/TRD-AfterDark.-.2024.7.12.12.-.2024-07-12.16_12_58.log)

[TRD-42200 - 2024.7.12.12 - 2024-07-12 14_02_28.log](https://github.com/user-attachments/files/16195930/TRD-42200.-.2024.7.12.12.-.2024-07-12.14_02_28.log)
[TRD-42200 - 2024.7.12.12 - 2024-07-12 15_27_04.log](https://github.com/user-attachments/files/16195931/TRD-42200.-.2024.7.12.12.-.2024-07-12.15_27_04.log)
[TRD-42200 - 2024.7.12.12 - 2024-07-12 15_35_19.log](https://github.com/user-attachments/files/16195932/TRD-42200.-.2024.7.12.12.-.2024-07-12.15_35_19.log)
[TRD-42200 - 2024.7.12.12 - 2024-07-12 15_43_20.log](https://github.com/user-attachments/files/16195933/TRD-42200.-.2024.7.12.12.-.2024-07-12.15_43_20.log)
[TRD-42200 - 2024.7.12.12 - 2024-07-12 16_05_26.log](https://github.com/user-attachments/files/16195934/TRD-42200.-.2024.7.12.12.-.2024-07-12.16_05_26.log)
[TRD-42300 - 2024.7.12.12 - 2024-07-12 12_05_01.log](https://github.com/user-attachments/files/16195935/TRD-42300.-.2024.7.12.12.-.2024-07-12.12_05_01.log)

**Comment by Frooxius** [comment]
I think this should be fixed in 2024.7.12.933. Can you retest please?

**Comment by jae1911** [comment]
I can confirm this works both on Windows and Linux.

**Comment by shiftyscales** [comment]
Closing then. If others continue to have issues- please ensure you're on the latest build, and if it's still an issue report back here.

**Comment by bredo228** [comment]
> I can confirm this works both on Windows and Linux.

Can also confirm this works on both, thanks!
