### ISSUE TITLE
Directory "RuntimeData\AssemblyMetadata" exists in Resonite game directory on Linux

### ISSUE THREAD

**Issue by coolymike** [Yellow-Dog-Man/Resonite-Issues#2542]
### Describe the bug?

A directory named "RuntimeData\AssemblyMetadata" exists in the root of the game directory on the Linux native version of Resonite. This is likely a mistake, caused by the fact that Windows paths use `\` to indicate a subdirectory, and every other OS uses `/` to indicate a subdirectory.

I have not looked into which issues this could cause, but I assume it can cause issues with the AssemblyMetadata cache not being found.

### To Reproduce

Install the Linux native version of Resonite

### Expected behavior

"AssemblyMetadata" subdirectory should exist in "RuntimeData"

### Screenshots

![image](https://github.com/user-attachments/assets/662e08ea-030f-47a5-acbc-86993d21ae88)

### Resonite Version Number

2024.7.12.12

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Desktop

### Log Files

-

### Reporters

whippersnatchpumpkinpatch on Discord

**Comment by ExoTheWicker** [comment]
Exists on headless brach too

**Comment by ticpu** [comment]
It also causes issues starting the headless with a security profile as the parser for AppArmor doesn't recognize this as a valid path and require manual intervention to fix.  Someone missed a `Path.Join()` in the code.

**Comment by Frooxius** [comment]
Fixed in 2024.7.15.1359, thanks!

**Comment by coolymike** [comment]
I can confirm this is fixed in the latest release on Linux native.
