### ISSUE TITLE
[.NET8.0 Headless] Error when shutting down headless on linux

### ISSUE THREAD

**Issue by ExoTheWicker** [Yellow-Dog-Man/Resonite-Issues#2543]
### Describe the issue.

While testing the new .NET8.0 headless I observed an error when the headless shut down

![image](https://github.com/user-attachments/assets/187d876a-b893-405b-9d71-6ce5986de3e6)

### To Reproduce

Run the new .NET8 headless on Linux then shut it down using the normal commands.

### Expected behavior

For the headless to shutdown (operate normally but this is still in testing) normally without error

### Screenshots

![image](https://github.com/user-attachments/assets/41343305-86a0-474f-84bb-5eb15e4c7e72)

### Resonite Version Number

2024.7.12.12

### What Platforms does this occur on?

Linux

### What headset if any do you use?

N/A

### Log Files

[SA-NODE1 - 2024.7.12.12 - 2024-07-12 01_12_32.log](https://github.com/user-attachments/files/16186060/SA-NODE1.-.2024.7.12.12.-.2024-07-12.01_12_32.log)

### Additional Context

Just logging this for Froox

### Reporters

ExoTheWicker

**Comment by Frooxius** [comment]
Merged fix in 2024.7.15.1359, thanks!
