### ISSUE TITLE
ParticleBurst is not a Data Model Type, causes errors when creating ProtoFlux reference node to Bursts in ParticleEmitter components

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#2546]
### Describe the bug?

Errors when creating ProtoFlux reference node to `Bursts` `SyncLinear<ParticleBurst>` in ParticleEmitter components.

### To Reproduce

1) Spawn default particles from Dev Tool's Create New menu
2) Go to the SphereEmitter
3) Try to pull a ProtoFlux reference node to the Bursts member
4) Node looks strange and errors in log

### Expected behavior

ParticleBurst should be a Data Model type because it is used by ParticleEmitter components, ProtoFlux nodes should not cause errors when trying to use this type

### Screenshots

N/a

### Resonite Version Number

Beta 2024.7.12.12

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[DESKTOP-H976HO2 - 2024.7.12.12 - 2024-07-12 02_55_23.log](https://github.com/user-attachments/files/16186250/DESKTOP-H976HO2.-.2024.7.12.12.-.2024-07-12.02_55_23.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: `nytra`)

**Comment by Frooxius** [comment]
Fixed this in 2024.7.12.1147, thank you!
