### ISSUE TITLE
[Windows .NET 8 Headless] Other users can't connect to the session

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#2548]
### Describe the issue.

Using the default config (Not logged in) I can connect to the session from the same PC that the headless in running on, but other users cannot connect.

I have tried the regular headless and other users are able to connect to that one.

### To Reproduce

1) Start .NET 8 Headless on Windows using the default config file
2) If I connect to it from the same machine I can get in
3) If other users try to connect they cannot get in

### Expected behavior

Other users can connect

### Screenshots

N/a

### Resonite Version Number

Beta 2024.7.12.12

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[DESKTOP-H976HO2 - 2024.7.12.12 - 2024-07-12 06_12_36.log](https://github.com/user-attachments/files/16189133/DESKTOP-H976HO2.-.2024.7.12.12.-.2024-07-12.06_12_36.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: `nytra`)

**Comment by bredo228** [comment]
Doing some testing:

I've found the session will show in the session browser for people on the local network, but won't show outside of the local network.
![image](https://github.com/user-attachments/assets/8076bc9c-6fc1-4a94-9ad5-52a538b0a2ef)


LNL direct IP doesn't appear to work over LAN direct connect or through the "Open World" node - tried setting forcePort and wasn't able to connect through direct IP

It seems you can connect via the session URL over the internet using the open world node, but LAN tries direct IP when doing this and fails.

**Comment by bredo228** [comment]
For direct IP, it may be Windows Firewall causing issues - added a firewall rule to allow connections to the port I set in `forcePort` and was able to connect over LAN

**Comment by bredo228** [comment]
> For direct IP, it may be Windows Firewall causing issues - added a firewall rule to allow connections to the port I set in `forcePort` and was able to connect over LAN

Seems like it may be Windows Firewall - noticed in my test box that the regular Resonite headless client had a rule allowing traffic to it, while I had to manually add a firewall rule to allow traffic to the dotnet executable for LAN connections to work.

![image](https://github.com/user-attachments/assets/b8ee0333-1527-43b7-b9fc-4367ab08dce5)

It's likely working on the local machine as it's a connection to the same machine, and the session URL from remote users is likely working due to how LNL NAT punchthrough works.

Also tested inviting someone to the headless, the invite worked fine.

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius - it sounds like nothing is technically wrong here- there are no firewall rules being made- and thus external connections are refused- but is there anything we could do to ensure proper firewall rules are created while launching the headless from dotnet?

**Comment by Frooxius** [comment]
I don't think we can create firewall rules like that, that is up to the user to configure their firewalls properly.

**Comment by shiftyscales** [comment]
Closing then, thanks. :)
