### ISSUE TITLE
Add a way of displaying when a contact is in a incompatible session

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2551]
### Is your feature request related to a problem? Please describe.

Right now there's no way of knowing if your contact is in an incompatible session unless you go to your settings and turn on fetch incompatible sessions in this case it would show that the contact is in an incompatible session but that only works for Joinable sessions

For instance if they're in a private world it would just display that they're in a private world instead of being incompatible

### Describe the solution you'd like

A reliable way of displaying when your contact is in a incompatible session either by displaying the version number or just by having text saying that they're incompatible

### Describe alternatives you've considered

Turning on fetch incompatible sessions but this does not work for things like private sessions

### Requesters

@epicEaston197

**Comment by Frooxius** [comment]
Oh this is a consequence I haven't thought of - the incompatible sessions are filtered out from display, so we don't know that people are in them, so we can't show that they're in an incompatible session.

I'll have to see how to best approach this.

**Comment by Frooxius** [comment]
This is addressed in 2024.7.15.1359 now! Thanks!

**Comment by epicEaston197** [comment]
>- Remove Fetch Incompatible Sessions setting
-- Resonite now fetches all sessions

I feel like this would be extremely confusing for new users this will have to be clearly conveyed that they can't join

**Comment by Frooxius** [comment]
I recommend reading the rest of release notes - it is indicated. 

By default it doesn't show the sessions as it did before, it's just determined in the filtering options for World tab instead of Settings.
