### ISSUE TITLE
Join button from Session Invite is broken

### ISSUE THREAD

**Issue by r7uaz0n** [Yellow-Dog-Man/Resonite-Issues#2558]
### Describe the bug?

Received an invite to join session, but Join button is broken. Unable to join session from invite:

### To Reproduce

Receive session invite from user. 

### Expected behavior

There should be an active Join button. 

### Screenshots

![20240712104132_1](https://github.com/user-attachments/assets/c74a663b-2506-4fdc-bb8b-d319ee9e322f)
![image](https://github.com/user-attachments/assets/14e82479-08a6-4c70-acc5-1b3d0366459f)

### Resonite Version Number

Beta 2024.7.12.933

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[T1NKERB0T-LAB - 2024.7.12.933 - 2024-07-12 10_35_51.log](https://github.com/user-attachments/files/16197752/T1NKERB0T-LAB.-.2024.7.12.933.-.2024-07-12.10_35_51.log)

**Comment by Frooxius** [comment]
What version was the session hosted at? The Join button can be grayed out if the session is not compatible with your build.

**Comment by r7uaz0n** [comment]
Session is running  Beta 2024.7.12.12
Host will trying updating now.

**Comment by r7uaz0n** [comment]
It works now.  Thanks.  Closing.
