### ISSUE TITLE
Allow audio input changes when using Remote Play

### ISSUE THREAD

**Issue by glitchfur** [Yellow-Dog-Man/Resonite-Issues#2561]
### Is your feature request related to a problem? Please describe.

When using Steam Remote Play, Resonite forces the audio input device to be "Steam Voice" regardless of any other audio input settings. This may not necessarily be desirable if, for example, someone is using a wireless headset connected to a nearby PC running Resonite and controlling it elsewhere on the LAN with Remote Play. It is also not clear that this override is being done, as the settings will still show that it's either using the system default device or using the custom ordering of devices.

### Describe the solution you'd like

I'd like an option to disable the "Steam Voice" audio input override when using Remote Play, or otherwise for it to be treated as a normal audio input device.

### Describe alternatives you've considered

None at this time.

### Additional Context

This started occurring after the Settings UI update. Prior to that, audio inputs could be changed freely when using Remote Play.

### Requesters

@glitchfur

**Comment by Frooxius** [comment]
Added in 2024.7.15.1359 :3

Prioritized due to boyfriend privileges (and also taking less than 5 minutes to implement x3)
