### ISSUE TITLE
ObjectFieldDrive<Chirality?> node can't save to inventory.

### ISSUE THREAD

**Issue by chaixshot** [Yellow-Dog-Man/Resonite-Issues#2567]
### Describe the bug?
I spawn my item and resave it to inventory that make a **ObjectFieldDrive<Chirality?>** gone. 
 ![image](https://github.com/user-attachments/assets/17debacf-3386-419f-b975-0942c1d8507b)

### To Reproduce
1. Create new empty box.
2. Add **RootContextMenuItem** component to the box.
3. Drive **OnlyForSide** property with **ProtoFlu(X)** tool.
4. Pack **ObjectFieldDrive<Chirality?>** node to the box.
5. Save the box to inventory
6. Spawn the box and inspector slot **ObjectFieldDrive`1**
![image](https://github.com/user-attachments/assets/56b2c715-f49d-4a72-964f-3bab057d62fa)

### Expected behavior
Save item without make **ObjectFieldDrive<Chirality?>** node missing.

### Screenshots
Video: https://streamable.com/wxlfev

### Resonite Version Number
2024.7.12.1147

### What Platforms does this occur on?
Windows

### What headset if any do you use?
Valve Index, Desktop Mode

### Log Files
[HAMER_PC - 2024.7.12.1147 - 2024-07-13 11_59_32.log](https://github.com/user-attachments/files/16200948/HAMER_PC.-.2024.7.12.1147.-.2024-07-13.11_59_32.log)

### Reporters
H@mer

**Comment by chaixshot** [comment]
This is a remade from scratch.
https://streamable.com/da3sbu

**Comment by ModernBalloonie** [comment]
I think i'm having an issue related to this too. I tried to resave my tool that has some chirality drives in it and seems like it breaks.

**Comment by Frooxius** [comment]
Fixed this in 2024.7.15.917!

The saving was actually fine - it was loading the item back that was broken. Your items should be okay unless you re-saved the broken versions. 

Thanks for report!
