### ISSUE TITLE
OnAddComponentPressed on ConponentSelect to add a protoflux node, allowing any generic type

### ISSUE THREAD

**Issue by sjsanjsrh** [Yellow-Dog-Man/Resonite-Issues#2569]
### Is your feature request related to a problem? Please describe.

OnAddComponentPressed on ConponentSelect will select a protoflux node, but nodes of other than the specified type are not allowed.

### Describe the solution you'd like

It would be nice to be able to select any generic protofluxnode as its delegate for .

### Describe alternatives you've considered

I want to bookmark protofluxnode or create a custom node browser.

**Comment by Banane9** [comment]
Consider having a look at my [mod](https://github.com/ResoniteModdingGroup/ComponentSelectorAdditions/) which adds a search, favorites and recents for components and protoflux nodes.
