### ISSUE TITLE
New ProtoFlux Node: Async Sequence

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#257]
### Is your feature request related to a problem? Please describe.

Currently, there is no async sequence node.

### Describe the solution you'd like

An asynchronous sequence node analogous to the synchronous sequence, just that every call is awaited.

### Describe alternatives you've considered

Using a async for loop and an impulse demultiplexer.

**Comment by Frooxius** [comment]
I'll take this. I wanted to add it for a while and I just never get around to do it. It'll be pretty quick.

**Comment by Frooxius** [comment]
It wasn't pretty quick ;_;

In other news, we now support async call lists in ProtoFlux and have this node in 2023.10.18.449
