### ISSUE TITLE
My game crashes on start. 

### ISSUE THREAD

**Issue by Fakku777** [Yellow-Dog-Man/Resonite-Issues#2583]
### Describe the bug?

Hi,
 so up until a few days ago my game was running absolutely fine. I was 
using Proton experimental on arch linux (Gnome) and did a few meetups 
before then. And after my game updated I kept getting unity errors as 
soon as my game loaded. So I decided to try the Linux build, but it 
doesn't let me use VR and is a lot slower (20 ish fps) My contacts 
button is also missing and it say's I have a syncing error. 

### To Reproduce

Run under Linux and use proton in steam. I tried both Experimental and 9. 

### Expected behavior

Game starts under Proton with out issue. 

### Screenshots

![image](https://github.com/user-attachments/assets/1e23792e-304d-4268-8d98-09f2060aad61)
![image](https://github.com/user-attachments/assets/929f4363-9b28-407c-82c0-466c20eeedb6)
![image](https://github.com/user-attachments/assets/953e3ead-2e8d-42c2-9a2e-cdbd9a87f45c)

### Resonite Version Number

2024.7.12.1147 (Think? Idk how to get the exact version number)

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Desktop/Quest 2 with ALVR

### Log Files

[error.log](https://github.com/user-attachments/files/16230027/error.log)
[error.log](https://github.com/user-attachments/files/16230030/error.log)

**Comment by shiftyscales** [comment]
If possible, could you also include Resonite's log files as well as Unity's Player.log file in addition to the error logs you've posted, @Fakku777?

Details on the different kinds of logs produced is available on our wiki (although assumes a Windows install as far as specific path references, etc. are written).

https://wiki.resonite.com/Log_Files

**Comment by Fakku777** [comment]
[MakuPC - 2024.7.12.1147 - 2024-07-14 22_54_02.log](https://github.com/user-attachments/files/16241543/MakuPC.-.2024.7.12.1147.-.2024-07-14.22_54_02.log)
[Player.log](https://github.com/user-attachments/files/16241548/Player.log)
@shiftyscales Yes! I hope these are the right ones. Sorry for the late reply.

**Comment by shiftyscales** [comment]
Thanks. Those were the log types I was looking for yes. There have since been a couple of updates- could you try running on Proton again with the latest build of Resonite, @Fakku777?

If it crashes, please include new log files for it- the error.log, Resonite log, and Player.log.

Do the crashes on Proton only occur when attempting to run VR? Or does it occur in desktop mode as well?

**Comment by shiftyscales** [comment]
At the time of writing, the latest build is `2024.7.15.1359`.

**Comment by Fakku777** [comment]
@shiftyscales Yes, it seems to be working fine after the update. Idk what happened but what ever it was it seems to be fixed.

**Comment by shiftyscales** [comment]
Closing for now then- if you continue having issues with running under proton please feel free to open additional issues in future, @Fakku777. :)
