### ISSUE TITLE
Add Easing ProtoFlux Nodes

### ISSUE THREAD

**Issue by RyuviTheViali** [Yellow-Dog-Man/Resonite-Issues#2592]
### Is your feature request related to a problem? Please describe.

In the world of animation and design, there are a lot of various kinds of movement that can make aspects of things feel a certain way. Algorithms for these different kinds of movements have been around for decades, and can be seen everywhere in design, video production, and web design.

With this in mind, Resonite has the capacity to allow the creation of these algorithms via ProtoFlux, but some of the algorithms are rather large, and it makes using these algorithms cumbersome and slow as they have to be carefully constructed every time.

### Describe the solution you'd like

A solution to this is to add all of these "easing" algorithms as ProtoFlux nodes available for users to more easily utilize and add life to their creations.

Namely, ProtoFlux nodes could be added which make use of these common easing/tweening methods:
- Sine
- Quadratic
- Cubic
- Quartic
- Quintic
- Exponential
- Circular
- Rebound (Back)
- Elastic
- Bounce

All of the above methods also have three ways they can animate:
- In
- Out
- In/Out (Both)

A bonus feature would be for these methods to be available (to some degree) with Tween ProtoFlux nodes, to allow for better-timed shaping of things and events.

### Describe alternatives you've considered

Continue writing the easing algorithms manually in ProtoFlux, or wait for custom ProtoFlux nodes.

### Requesters

Ryuvi (Discord: `ryuvi`)

**Comment by Frooxius** [comment]
Merged this in 2024.10.4.923, thank you!
