### ISSUE TITLE
Scrolling Inspector Panels Causes Accidental Data Manipulation

### ISSUE THREAD

**Issue by RyuviTheViali** [Yellow-Dog-Man/Resonite-Issues#2594]
### Describe the bug?

Currently with inspector panels, namely the component browsing side of the panel, when scrolling up or down long lists of components, it's very easy to click and drag om any editable field or button, and change said field or activate said button. Because of this, one can only click and drag on very specific parts of the panel - and to new users this information is unknowable right off the bat, which leads to the inevitable unintended manipulation of data.

### To Reproduce

1. Create a Scene Inspector panel.
2. Navigate to a slot with many components on it (i.e. your own User Root slot).
3. Attempt to click and drag on any button, text field, checkbox, etc. in the component list to scroll said list.
4. Notice how whatever you clicked on either gets focused to, or gets changed unintentionally.

### Expected behavior

Clicking and dragging anywhere on the inspector window should not actively interact with the items on the panel, and instead just scroll it.

### Resonite Version Number

Beta 2024.7.15.1359

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[RYUVI-TOWER - 2024.7.15.1359 - 2024-07-16 03_35_01.log](https://github.com/user-attachments/files/16245630/RYUVI-TOWER.-.2024.7.15.1359.-.2024-07-16.03_35_01.log)

### Reporters

Ryuvi (Discord: `ryuvi`)

**Comment by JackTheFoxOtter** [comment]
Actually I was sure this was already reported, but apparently not! This is something I've been frustrated about quite frequently. It's especially frustrating when working with components that have a lot of buttons (like StaticTexture2D), as I'm always super paranoid about accidentally pressing one while scrolling and have to be extra careful.

The fix to this should be relatively easy though, I believe every UIX `Button` component on the generated UI panels (inspector etc.) should have the `RequireLockInToPress` option defaulting to "True". That way, you can't accidentally trigger button presses while scrolling.

**Comment by Readun** [comment]
It kinda was a topic before in previous ones, which were focussing on getting an easier scroll function:
#149 and #157 

We do really need something like those but also what Ryuvi described here. I regulary see new players being very frustrated with the lack of ability to scroll inspectors or that they accidently deleted bones or changed stuff while trying to scroll with the drag.

**Comment by 5H4D0W-X** [comment]
Related to #2529

**Comment by Frooxius** [comment]
Merged the fix for this in 2024.9.16.715! Thanks!
