### ISSUE TITLE
Add IsContextMenuOpen ProtoFlux Node

### ISSUE THREAD

**Issue by RyuviTheViali** [Yellow-Dog-Man/Resonite-Issues#2595]
### Is your feature request related to a problem? Please describe.

Currently there is no direct way to get if a user's context menu is open or not.

### Describe the solution you'd like

Create a ProtoFlux node `IsContextMenuOpen` which returns a Boolean value of whether or not their context menu is visible.

### Describe alternatives you've considered

Manually search the user's User Root slot for a slot named `Context Menu`, and determine it's visibility based on the active state of the child under that slot.

### Requesters

Ryuvi (Discord: `ryuvi`)

**Comment by JackTheFoxOtter** [comment]
This already exists! https://wiki.resonite.com/ProtoFlux:Is_Context_Menu_Open

**Comment by RyuviTheViali** [comment]
Welp, I'm blind, thanks for showing me! Closing.
