### ISSUE TITLE
Headless not launching

### ISSUE THREAD

**Issue by VTArxelus** [Yellow-Dog-Man/Resonite-Issues#2599]
### Describe the bug?

I just installed the headless today through Steam on a new location as I am migrating hardware. Except it seems that when the headless gets to a certain point of loading in the command prompt, it seems to unable to find a file and then forces an exit. I will attach the logs of my four attempts so far. I do have the .Net 8 Runtime installed, in case it were necessary.

### To Reproduce

Download headless as normal through steam, and run ".\Resonite.exe" from the Headless directory.

### Expected behavior

The client should proceed to "NO WORLD."

### Screenshots

![PXL_20240716_200035585 1](https://github.com/user-attachments/assets/c0fb9aaa-ae1b-468c-adb6-b1f280ada893)

### Resonite Version Number

Beta 2024.7.15.1359

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

[VINCENT-0110 - 2024.7.15.1359 - 2024-07-16 14_07_18.log](https://github.com/user-attachments/files/16257499/VINCENT-0110.-.2024.7.15.1359.-.2024-07-16.14_07_18.log)
[VINCENT-0110 - 2024.7.15.1359 - 2024-07-16 14_08_39.log](https://github.com/user-attachments/files/16257500/VINCENT-0110.-.2024.7.15.1359.-.2024-07-16.14_08_39.log)
[VINCENT-0110 - 2024.7.15.1359 - 2024-07-16 14_37_42.log](https://github.com/user-attachments/files/16257501/VINCENT-0110.-.2024.7.15.1359.-.2024-07-16.14_37_42.log)
[VINCENT-0110 - 2024.7.15.1359 - 2024-07-16 14_49_15.log](https://github.com/user-attachments/files/16257502/VINCENT-0110.-.2024.7.15.1359.-.2024-07-16.14_49_15.log)

### Additional Context

The only thing out of the ordinary that may have any impact is that I copied my config file from my old hardware to the new one to expedite operation resumption. However, I would not believe this to substantially impact operation.

### Reporters

VTArxelus

**Comment by Frooxius** [comment]
Looks like FreeImage is not installed. Do you have Visual Studio C++ redistributable installed? 
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022
