### ISSUE TITLE
Bot accounts show  up as Contacts.NoSession

### ISSUE THREAD

**Issue by ExoTheWicker** [Yellow-Dog-Man/Resonite-Issues#2604]
### Describe the bug?

After a recent update, I observed that my bot was listed as being online with Contacts.NoSession.

### To Reproduce

Log an account that is friended into a bot client and observe that it shows as Contacts.NoSession

### Expected behavior

For the bot to be displayed as using: version of bot

### Screenshots

![image](https://github.com/user-attachments/assets/4ea43fd1-a928-4200-9d77-70575f9d1b60)

### Resonite Version Number

Beta 2024.7.15.1359

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Index, Desktop

### Log Files

[DESKTOP-SA2J3CT - 2024.7.15.1359 - 2024-07-17 16_43_19.log](https://github.com/user-attachments/files/16274643/DESKTOP-SA2J3CT.-.2024.7.15.1359.-.2024-07-17.16_43_19.log)

### Additional Context

On non-resonite clients (Such as recon) log in the bot's version is displayed properly. 

### Reporters

ExoTheWicker

**Comment by ExoTheWicker** [comment]
This is what is expected 
![image](https://github.com/user-attachments/assets/07d760df-d42f-49d2-8a45-faf400234ffb)

**Comment by Readun** [comment]
Oh uh? I thought this were more widespread... whoups?
I tend to have 1-4 friends with that "Contacts.NoSession" status.
If I recall correctly, its been around since the large Datafeed/Type updates?

**Comment by ExoTheWicker** [comment]
I think that's when I remember it first cropping up.

**Comment by shiftyscales** [comment]
I believe this could possibly be related to the changes made to compatibility hash generation, and how version differences are reported.

Seeking input from @Frooxius - but I believe that what was being done in this case wasn't really intended to be used that way (it's intended to display a version number specifically, not a custom string), and this issue would be better resolved by other features like custom statuses #913.

**Comment by Frooxius** [comment]
I'll add custom string for the client type of "Bot" and "Chat Client" which can include the version string. You'll just need to properly indicate in the status that it's a bot or chat client and then it'll display properly.

**Comment by Frooxius** [comment]
Fixed up 2024.7.19.281, in thanks!
