### ISSUE TITLE
API endpoint for latest stable version

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2608]
### Is your feature request related to a problem? Please describe.

I am currently working on a way to have my headlesses auto-update when a new Resonite version comes out, but the system currently heavily Relies on a Steam feature to get the latest version.

### Describe the solution you'd like

Have an API endpoint that returns a string of the latest stable version, for instance:
```
2024.7.17.1173
```
Or alternatively:
```json
{
  "latest": "2024.7.17.1173"
}
```

### Describe alternatives you've considered

Currently, the method used is to query `https://store.steampowered.com/feeds/news/app/2519830`, parse the feed, and see if anything new is there.

### Additional Context

A dedicated endpoint would make it easier and would avoid things breaking if Steam decides to remove that feature from their platform, as sadly, a lot of websites have been removing RSS feeds.

### Requesters

U-j4 | j4.lc (Discord)

**Comment by shiftyscales** [comment]
There are a few existing issues which cover requests pertaining to wanting some mechanism to detect when a new update is available / auto-update the headless, e.g. #796, #2021.

This is something that could probably be improved by Molecule #1212.

They'd also further be improved by #702. As Frooxius said [here](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1139#issuecomment-1890391983):

> The other thing that should help in a number of cases is the rework of the data model and generalization: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/702
> 
> What this will do is that for a lot of updates, we don't actually need to push a new build - the new binaries will be automatically and dynamically downloaded - you just need to join/start a session with the updated ones. This would help overall, as you'd be able to run multiple versions seamlessly too, so from user perspective there's no need to "restart to update" unless we make changes to the core.

**Comment by ExoTheWicker** [comment]
I feel having an API endpoint for this could be useful for people making third-party applications. Having data on when a specific build was released and what the current versions are would be useful for all parties involved.

In addition, I think it would be nice to have an endpoint like 

https://api.resonite.com/stats/versions/ return data like:

``{
"main": "2024.xx.xxxx"
"pre-release": "2024.xx.xxxx"
"headless": "2024.xx.xxxx"
}``

and possibly have another endpoint like https://api.resonite.com/stats/builds/ return data like:

```
{
  "2024.06.21.3621": {"releaseDate": "2024.06.21", 
  "branchs":["main", "headless"], "notes":"Added X thing"},
  "2024.06.25.1143":{"releaseDate": "2024.06.25","branchs":["pre-release"],"notes":"Started implementing Y system."}
}
```

**Comment by Frooxius** [comment]
This would be implicitly handled by Molecule https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1212

Once of its concepts is that there are actual "release channels", which  you could query to determine what the latest version is. I'm closing this one as duplicate for that reason.
