### ISSUE TITLE
Australian bridge is down

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#2610]
### Describe the bug?

According to https://discord.com/channels/1040316820650991766/1202376038374707250/1262278590947659879 the Australian bridge has been down since the 15 of July, this in some cases causes Australian users to be forced through the Relay which isn't ideal.

This is also confirmed by it not showing up on the API https://api.resonite.com/networknodes

### To Reproduce

See https://api.resonite.com/networknodes or https://status.yellowdogman.com/

### Expected behavior

The bridge should be working normally.

### Resonite Version Number

2024.7.17.1173

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, HP reverb G2 (although, headset doesn't affect this issue)

### Log Files

N/A? 

### Reporters

Stellanora

**Comment by ProbablePrime** [comment]
I'm aware of this and will resolve it soon.

**Comment by Stellanora64** [comment]
@ProbablePrime the bridge seems to be back up but only at ~16% health according to https://status.yellowdogman.com/ is this issue good to be closed or are there still issues remaining?

**Comment by ProbablePrime** [comment]
16% refers to uptime not health, but in either metric it is abysmally low :(

But it will go up now! So yup resolved, Thank you!
