### ISSUE TITLE
Saving a slot with PhotoMetadata adds user to _exportedUsers

### ISSUE THREAD

**Issue by EuphieEuphoria** [Yellow-Dog-Man/Resonite-Issues#2611]
### Describe the bug?

When creating custom cameras, it is common practice to replicate the interactive camera and finger photo functionality by including your own photo metadata, allowing the user to save the photo as a screenshot or export the photo. This is commonly done by carrying a template photo within the camera itself to which the camera writes the metadata to. 

Currently, saving the camera while the photo template is a child of the camera will cause the _exportedUsers list to populate with the saving user, as if they attempted to export the photo itself. This occurs even if the PhotoMetadata component is disabled. 

This removes the ability for the saving user to use the smart "save as screenshot" function with any photos created by the camera.

### To Reproduce

Create an object with a child. On the child object, add the PhotoMetadata component. Observe the empty _exportedUsers bag. Save the item to your inventory. after spawing the item from your inventory, observe the now-populated _exportedUsers bag.

### Expected behavior

The _exportedUsers bag should not populate unless the image is exported from the game such as through the "save as screenshot" button or "Export as screenshot" button. 

Additionally, this bag should not populate if the component is disabled.

### Screenshots

https://github.com/user-attachments/assets/f2332ab2-4048-413a-b572-a1526febffca

### Resonite Version Number

Beta 2024.7.17.1173

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-LQAQ7BB - 2024.7.17.1173 - 2024-07-18 02_24_53.log](https://github.com/user-attachments/files/16278750/DESKTOP-LQAQ7BB.-.2024.7.17.1173.-.2024-07-18.02_24_53.log)

### Additional Context

This problem was presented to me after froox commented be was unable to "save as screenshot" the photos he was taking with my polaroid camera.

### Reporters

Discord: EuphieEuphoria

**Comment by EuphieEuphoria** [comment]
Ah that makes sense. Would this also solve the issue of the "save/export as screenshot" button appearing on the camera itself as you hold it?

**Comment by shiftyscales** [comment]
I believe in that case- it's just detecting the presence of that compoonent, and generating the required context menu button from there @EuphieEuphoria - so a similar check would need to made to prevent the display of the context menu button outright unless that component is enabled as @Frooxius suggested above to resolve the other issue with it.

**Comment by Frooxius** [comment]
@EuphieEuphoria No, that needs to be addressed separately, but that's easy enough to do too.

**Comment by EuphieEuphoria** [comment]
Should I make a feature request for disabling the export/save button when the component is disabled?

**Comment by Frooxius** [comment]
No, I'll handle this as part of this one.

**Comment by Frooxius** [comment]
Sorted this out in 2024.7.19.281, thanms!
