### ISSUE TITLE
Keyboard Shortcut for Primary Should Perform All Primary Actions

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#2614]
### Is your feature request related to a problem? Please describe.

Currently the keyboard shortcut for primary (`Y`) is missing some actions that the corresponding mouse press can perform.

### Describe the solution you'd like

The following missing functionality should be able to be done with the keyboard shortcuts:
* While holding an object, pressing primary should align it

There might be others, which I couldn't find at this time.

### Describe alternatives you've considered

There are no alternatives on devices which can not use left mouse and right mouse at the same time.

### Requesters

LuxKitty
LucasRo7

**Comment by shiftyscales** [comment]
If you are aware of other situations in which the primary key does not work the same as a mouse press, I'd recommend reporting them on #1067 for which this issue is a duplicate.

From my findings when investigating that issue previously- I believe this is a bug / oversight in how it was implemented:
> Replicated thanks.
> 
> I did observe that when using the Y key for primary, it keeps the "Strength" at 0 as seen in the input debugger. When using the LMB instead, the strength smoothly climbs to "1". I'm not sure if this is related, but is a likely cause/oversight that lead to this.
> 
> https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/54213390/3cd9bab2-dca4-4d63-a9a9-c10772e86674
