### ISSUE TITLE
Remove/restrict Moderation data from the Resonite API

### ISSUE THREAD

**Issue by bontebok** [Yellow-Dog-Man/Resonite-Issues#2619]
### Is your feature request related to a problem? Please describe.

This feature request is for the removal of account restrictions/ban information pertaining to users from the public Resonite API. ﻿This concern was recognized by Dante in the Resonite Volunteer Team Discord. Additionally, Stiefel should also be credited for being part of the conversation.

Account restrictions/ban information and other Moderation actions pertaining to users is exposed publicly through the Resonite API. The exposure of these values permits users to ascertain some Moderation actions (or potentially lack of action) taken privately by the Moderation Team against another user. I am also aware that the exposure of this data has also led to tools being created within and external to Resonite which can query and display these values. The exposure of this information has led to public and private debate/discussions related to Moderation actions, which I feel is best handled privately.

Note - This issue/request was initially reported via a Resonite Security report. Although the details regarding Moderation actions/bans/account restrictions are not explicitly defined as Private Data in Resonite's Security Policy, Moderation actions are considered and treated as private information by the Moderation Team. However, in the ticket response from Resonite, they did not agree this falls under the definitions in the Resonite Security Policy and recommended that this request is posted to GitHub.

### Describe the solution you'd like

Remove/suppress all Moderation data from the user endpoint in the API. Create a new API endpoint which indicates if the user is or is not permitted to join a session. The joining user should present a challenge response/one time key similar to the Record request for the user's Avatar upon request to join a world. This response be used to validated the request by the cloud. By authenticating the request from the joining user, this will prevent users from querying the API for Moderation data on other users.

Although some community tools will be impacted by the lack of Moderation data, I believe this is the right thing to do in order for Moderation actions to remain private between the Moderation Team and the individuals involved.

### Describe alternatives you've considered

None, other than do nothing and continue to expose Moderation data via the public API.

### Requesters

Dante, Rucio, StiefelJackal

**Comment by Frooxius** [comment]
I've implemented this in 2024.10.4.923, the information should no longer be available.

When users join a session, a one-time key is generated which allows accessing this information once during that join (both for joining user and host, since they need to verify each other). 

This should help improve the privacy significantly, since it requires an explicit action from the user (joining a session) for anyone to be able to access that information.

Thank you for reporting this!
