### ISSUE TITLE
Resonite logo as favicon on the official websites

### ISSUE THREAD

**Issue by ExoTheWicker** [Yellow-Dog-Man/Resonite-Issues#262]
### Is your feature request related to a problem? Please describe.

Not related to a problem I think it would be nice if it was added to the website

### Describe the solution you'd like

I think having the logo as a favicon (tab icon) on the website would make it easier to find in the tabs list on your browser.

### Describe alternatives you've considered

none

### Additional Context

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/00e0276a-3e76-4636-b365-9983d32a0e8f)
There is no icon for the Resonite website.

This also needs to be done for the moderation and support websites.

**Comment by ExoTheWicker** [comment]
The expected behavior should look something like this:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/0bc69198-fe67-42e5-a3bd-f8b47512cca0)

**Comment by RaithSphere** [comment]
Okay i have added favicons along with other things

- apple-touch-icon
- favicon
- msapplication

**Comment by RaithSphere** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Website/commit/05ed1203e6637ef23ac4d02104e0fd70a04fcb31
