### ISSUE TITLE
Custom Cloud Home is not loaded

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2622]
### Describe the bug?

My custom Cloud Home is not loaded in any case.

### To Reproduce

1. Open the game
2. Set Custom home
3. Click on "Open Home" facet
4. End up in the default template

### Expected behavior

Custom Cloud Home should be loaded.

### Resonite Version Number

Beta 2024.7.19.281

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro, Index, Desktop

### Log Files

[TETHYS - 2024.7.19.281 - 2024-07-19 08_00_08.log](https://github.com/user-attachments/files/16302294/TETHYS.-.2024.7.19.281.-.2024-07-19.08_00_08.log)

### Additional Context

Possibly related to #2624 

### Reporters

U-j4 | j4.lc (Discord)

**Comment by shiftyscales** [comment]
Likely entirely related to #2624. As I noted there:

> Per the devlog in our Discord, we are currently having various cloud issues- is this a new issue, @jae1911?
> 
> Were you previously able to load into your cloud home without issue / have you ever been able to do so on Resonite?

**Comment by jae1911** [comment]
Fixed with the workaround of 2024.7.19.1211.
