### ISSUE TITLE
Cloud Home is not loaded on startup

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2624]
### Describe the bug?

When starting Resonite, the Cloud Home is not automatically loaded, not even the template.

### To Reproduce

Pre-requisites: make sure "Load cloud home on startup" is on

1. Open Resonite
2. Observe that the cloud home is not launched

### Expected behavior

The Cloud Home should be loaded.

### Screenshots

![Resonite_6Wwlo5bAPB](https://github.com/user-attachments/assets/4aa86356-8378-416d-841f-3eb0fca541fb)

### Resonite Version Number

Beta 2024.7.19.281

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro, Index, Desktop

### Log Files

[TETHYS - 2024.7.19.281 - 2024-07-19 08_03_26.log](https://github.com/user-attachments/files/16302312/TETHYS.-.2024.7.19.281.-.2024-07-19.08_03_26.log)

### Additional Context

Possibly related issue: #2622 

Clicking on the "Open Home" facet of the dashboard will load the default template.

### Reporters

U-j4 | j4.lc (Discord)

**Comment by shiftyscales** [comment]
Per the devlog in our Discord, we are currently having various cloud issues- is this a new issue, @jae1911?

Were you previously able to load into your cloud home without issue / have you ever been able to do so on Resonite?

**Comment by jae1911** [comment]
> Were you previously able to load into your cloud home without issue / have you ever been able to do so on Resonite?

Yes. This particular issue started with `Beta 2024.7.19.281`.

What makes it especially weird is that loading the default template **does work** when clicking on the "Open Home Facet". Isn't the template World supposed to be loaded from a cloud variable as well or is it stored somewhere locally?

**Comment by jae1911** [comment]
Fixed with the workaround of 2024.7.19.1211.
