### ISSUE TITLE
Resonite headless cloud bug

### ISSUE THREAD

**Issue by Khauni** [Yellow-Dog-Man/Resonite-Issues#2625]
### Describe the bug?

Mine and scantf's headless's are looping the session status update

### To Reproduce

launch the headless

### Expected behavior

looping

### Resonite Version Number

2024.7.19.281

### What Platforms does this occur on?

Windows, Linux

### Log Files

[DESKTOP-JUV58OS - 2024.7.19.281 - 2024-07-19 01_08_25.log](https://github.com/user-attachments/files/16302382/DESKTOP-JUV58OS.-.2024.7.19.281.-.2024-07-19.01_08_25.log)

### Reporters

Khauni
sctanf

**Comment by Gyztor** [comment]
Was fine before but after update (2024.7.19.281) won't boot at all and just spams console with errors above
![image](https://github.com/user-attachments/assets/84537dff-eca3-438c-a487-9e7f34c96e55)

**Comment by Frooxius** [comment]
I'm confused by this, I don't see the bits in the screenshot in the log. 

This might be just due to the current cloud issues.

**Comment by Khauni** [comment]
I sent my log file and im unsure entirely what is fully happening, only about 8 people have my headless added so it shouldnt need to update like that

**Comment by Frooxius** [comment]
There's currently ongoing cloud issues, see #devlog channel in Discord.

**Comment by sveken** [comment]
[a76f0f454b61 - 2024.7.19.281 - 2024-07-19 05_29_30.log](https://github.com/user-attachments/files/16302550/a76f0f454b61.-.2024.7.19.281.-.2024-07-19.05_29_30.log)
These log files have the mentioned messages if required.

**Comment by Xlinka** [comment]
![image](https://github.com/user-attachments/assets/c3f1ff9e-9071-4c77-a6da-962a8e4f4a10)
can confirm weird issues the hub fails to connect then just INIT contacts

![image](https://github.com/user-attachments/assets/a0e09bbe-06bf-4fb2-88c0-5078f09c73ca)

**Comment by Frooxius** [comment]
Just a headsup - please don't post screenshots of logs - post actual logs please.

**Comment by sveken** [comment]
Latest update has stopped the log spam for me

**Comment by Khauni** [comment]
Yea, Froox posted an update so its fixed
