### ISSUE TITLE
setFromCurrentWorld() does not purge UserInfo entries when fired

### ISSUE THREAD

**Issue by EuphieEuphoria** [Yellow-Dog-Man/Resonite-Issues#2626]
### Describe the bug?

With the addition of the new SetFromCurrentWorld() proxy on PhotoMetadata components, firing this proxy multiple times adds the firing user to the UserInfos list without purging previous entries. 

This results in a massive list of the same user if the user takes multiple photos.

### To Reproduce

Create a slot with a PhotoMetadata component. Create a method proxy for the SetFromCurrentWorld() method. Observe as the component adds a duplicate entry every time you fire the pulse without removing the last.

### Expected behavior

The SetFromCurrentWorld() method should purge the existing UserInfos List to prevent duplicate entries.

### Screenshots

![image](https://github.com/user-attachments/assets/c69e005d-96af-4a58-b19e-a643f1660433)
![image](https://github.com/user-attachments/assets/85485a28-af69-4f79-85f7-c72680efcb34)

### Resonite Version Number

Beta 2024.7.19.281

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-LQAQ7BB - 2024.7.19.281 - 2024-07-19 01_35_02.log](https://github.com/user-attachments/files/16302562/DESKTOP-LQAQ7BB.-.2024.7.19.281.-.2024-07-19.01_35_02.log)

### Reporters

Discord: EuphieEuphoria

**Comment by Frooxius** [comment]
It's not supposed to. It assumes that you have a clean setup, you shouldn't be firing it more than once.

**Comment by EuphieEuphoria** [comment]
I see, I have created my templates by firing the method before duplicating, I will move the population flux to the duplicated template instead
