### ISSUE TITLE
Ukrainian translation

### ISSUE THREAD

**Issue by Antonneposeda** [Yellow-Dog-Man/Resonite-Issues#2634]
### Is your feature request related to a problem? Please describe.

No particular problem, but I would like to play with my native language.

### Describe the solution you'd like

I would like Ukrainian translation to be added.

### Describe alternatives you've considered

I would like to lead the Ukrainian translation effort for Resonite, if there was no such person or effort before me.

### Additional Context

I am flexible in the software that I'll need to use

### Requesters

@Antonne or @Antonneposeda on Discord.

**Comment by jae1911** [comment]
See instructions on the locale repo to add a new one: https://github.com/Yellow-Dog-Man/Locale/?tab=readme-ov-file#if-youre-contributing-a-new-language

**Comment by ProbablePrime** [comment]
Migrated over to: https://github.com/Yellow-Dog-Man/Locale/issues/468
