### ISSUE TITLE
Setup CI/CD & NuGet for a work of System.Net.Websockets

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#2638]
### Is your feature request related to a problem? Please describe.

We need our own NuGet package for our fork here: https://github.com/Yellow-Dog-Man/System.Net.WebSockets.Client.Managed

### Describe the solution you'd like

Setup CI/CD and NuGet package as with our other dependencies. 

### Describe alternatives you've considered

N/A

### Additional Context

@ProbablePrime @BlueCyro @Geenz any takers for this one?

**Comment by Geenz** [comment]
Done!
