### ISSUE TITLE
No LNL Bridges available

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2640]
### Describe the bug?

Currently, there are no LNL bridges available, causing LNL punchthrough to fail.

Visiting https://api.resonite.com/networkNodes shows nothing available.

### To Reproduce

Try to join a session, notice `No LNL Bridge nodes found, NAT Punchthrough will not function.` in logs and either notice the fallback to steam networking sockets or the connection to fail

### Expected behavior

LNL punchthrough to work

### Screenshots

![image](https://github.com/user-attachments/assets/259f13d9-cddc-46aa-a48f-62a650fd5c89)

### Resonite Version Number

2024.7.20.1115

### What Platforms does this occur on?

Windows

### Log Files

[ERIS - 2024.7.20.1115 - 2024-07-21 09_07_20.log](https://github.com/user-attachments/files/16322364/ERIS.-.2024.7.20.1115.-.2024-07-21.09_07_20.log)

### Reporters

bredo, t.o.a.s.t.e.r.

**Comment by Frooxius** [comment]
Fixing this now

**Comment by Frooxius** [comment]
Sorted! Thanks for report!
