### ISSUE TITLE
Add "Random FloatQ" Flux Node (different from the Random Rotation node)

### ISSUE THREAD

**Issue by GearBell** [Yellow-Dog-Man/Resonite-Issues#2642]
### Is your feature request related to a problem? Please describe.

I know there's work arounds for this but it would be nice if we had in the Random nodes a Random FloatQ exactly like how every other node in there works of a random floatQ between two sets of designated values. Right now there is only a Random Rotation node that doesnt let you define how much between two value sets. For instance, I want to do a random floatQ between 10x15y5z and -10x-5y-8z then just feed it into whatever Im driving.

### Describe the solution you'd like

Just like with all the other nodes in the Random folder for float/int/float3/etc have one for floatQ. A random floatQ node that allows 2 sets of values you want it to go between.

### Describe alternatives you've considered

At the moment I have to do Random Float3 then convert to a floatQ.

### Additional Context

I know this one is silly but it would be nice to have one node rather than flip around to get the conversion node to get a floatQ random.

### Requesters

GearBell

**Comment by Xlinka** [comment]
![image](https://github.com/user-attachments/assets/5094702a-1654-4ea2-a5cf-5d5ac9068001)
Don't know if I'm allowed to do this but as a reference tested this.
and the code seems to work but the inputs go red,  but still functions i don't know if this is normal.
code related is 

[Node](https://github.com/Xlinka/Project-Obsidian/blob/main/ProjectObsidian/ProtoFlux/Math/Random/RandomFloatQ.cs)

Randomx extension class for [floatQ](https://github.com/Xlinka/Project-Obsidian/blob/main/ProjectObsidian/ProtoFlux/RandomXExtensions.cs)

**Comment by ProbablePrime** [comment]
@Xlinka I think your node can output invalid quaternions. Im not sure, but double check it cant.

**Comment by Xlinka** [comment]
```
3:15:32 AM.352 (414 FPS)	Generated invalid quaternion: [0.08355223; 0.05593095; 0.04505131; 0.9879316]
3:15:32 AM.353 (414 FPS)	Generated invalid quaternion: [0.0214637; 0.1197848; 0.06143557; 0.9909747]
3:15:32 AM.356 (414 FPS)	Generated invalid quaternion: [0.03231037; 0.04954358; 0.05178431; 0.9904383]
3:15:32 AM.358 (414 FPS)	Generated invalid quaternion: [-0.02562636; 0.05492395; 0.04499396; 0.9904622]
3:15:32 AM.360 (414 FPS)	Generated invalid quaternion: [-0.002791198; 0.0954117; 0.07165606; 0.9924729]
3:15:32 AM.362 (414 FPS)	Generated invalid quaternion: [-0.06703975; 0.1191729; 0.06130539; 0.9876057]
3:15:32 AM.365 (414 FPS)	Generated invalid quaternion: [0.04374857; 0.1106816; 0.04680814; 0.9892461]
3:15:32 AM.367 (414 FPS)	Generated invalid quaternion: [-0.04815752; 0.09693831; 0.03896591; 0.9904296]
```
Ah sorry for the oversight as i rushed the node. i forgot to Normalize the output i have now pushed a change to fix this 

as show below 

```
3:20:03 AM.212 (394 FPS)	Generated valid quaternion: [-0.02487107; 0.08928174; 0.06945816; 0.9932703]
3:20:03 AM.216 (394 FPS)	Generated valid quaternion: [-0.06536729; 0.1223123; 0.06883624; 0.9879414]
3:20:03 AM.218 (394 FPS)	Generated valid quaternion: [-0.003680017; 0.06082575; 0.05833365; 0.9964356]
3:20:03 AM.221 (394 FPS)	Generated valid quaternion: [0.03594759; 0.09479826; 0.07097456; 0.9923123]
3:20:03 AM.224 (394 FPS)	Generated valid quaternion: [-0.01508994; 0.09521406; 0.06056561; 0.9934981]
3:20:03 AM.232 (394 FPS)	Generated valid quaternion: [-0.01647676; 0.1160716; 0.05041627; 0.9918236]
3:20:03 AM.234 (394 FPS)	Generated valid quaternion: [-0.0614878; 0.1059967; 0.06177334; 0.9905392]
3:20:03 AM.238 (394 FPS)	Generated valid quaternion: [0.08427173; 0.06778752; 0.0534769; 0.992695]
3:20:03 AM.242 (394 FPS)	Generated valid quaternion: [0.05649239; 0.06316628; 0.07242387; 0.9937673]
```

[Update](https://github.com/Xlinka/Project-Obsidian/commit/2c9cb805f07c87f978cc4ff2712221be9523c3d2)

[Node](https://github.com/Xlinka/Project-Obsidian/blob/main/ProjectObsidian/ProtoFlux/Math/Random/RandomFloatQ.cs)

**Comment by Frooxius** [comment]
Added in 2024.7.24.1106, thanks!
