### ISSUE TITLE
User Join/Leave Toast (No Sound)

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#2644]
### Describe the bug?

A while ago we got the toast thing where you can see if a user joins/leaves your world.   It has an option for Toast Only/Audio Only/Both/None.

I've noticed that when set to Both, I have never heard any sound when I user joins.   
Was there suppose to be something, but just set?  

### To Reproduce

Turn on User Join/Leave notification and set it Both and have a user join or leave and notice no sound plays

### Expected behavior

To hear a sound when a user joins/leaves.

### Screenshots

![image](https://github.com/user-attachments/assets/e8679cff-8630-4e63-9f21-338b18fe07f9)

### Resonite Version Number

2024.7.20.1115

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[DESKTOP-H0FLKOJ - 2024.7.20.1115 - 2024-07-21 00_51_41.log](https://github.com/user-attachments/files/16323223/DESKTOP-H0FLKOJ.-.2024.7.20.1115.-.2024-07-21.00_51_41.log)

### Additional Context

I use to have a mod that added it, I kind of wish I could maybe even set my own custom sound with a resrec link...

**Comment by epicEaston197** [comment]
This isn't a bug it's because it doesn't have a sound see #1926

**Comment by shiftyscales** [comment]
That is correct. As seen in #1926 - the sound hasn't yet been integrated. I'll check in on the status of that. Thank you for raising this issue.
