### ISSUE TITLE
RectMesh & AudioClipMetadata Crashes World

### ISSUE THREAD

**Issue by AmasterAmaster** [Yellow-Dog-Man/Resonite-Issues#2645]
### Describe the bug?

I was documenting components and listening to music using the audio stream controller and wanted to mess with the RectMesh to see how it functioned. I placed it onto the UIX panel and it worked fine, until other components were added. When a friend and I added the AudioClipMetadata to this RectMesh, would instantly crashed. We did this over and over again to make sure that it was not mods or other variables (like length of time in the world).

**This cannot be done by yourself, you need a friend in the world to do this.**

### To Reproduce

Setup Steps:
 - Open/Create any world

Creating Audio Mesh Steps:<s>
 - Spawn out the Panel Base (from the resonite essential folder -> UI Presets -> Panel Base), it is quick UIX for this.
 - Open the UIX Panel with the inspector
 - Go to Panel base -> Canvas -> Vertical layout -> Main Area</s>
 - Create an Empty Object
 - Open the components menu and add either the RectMesh(AudioSourceWaveformMesh) or RectMesh(AudioSourceXYMesh) components (In UIX -> Graphics -> RectMesh<M>)

<s>Audio Stream Steps:
 - Spawn the audio stream (and have your favorite music playing)
 - Open the stream with the inspector
 - Go to User's Audio Stream -> Audio Output
 - Use the source from the AudioOutput component for the RectMesh(AudioSourceWaveformMesh)</s>
You don't even need this step!

Attaching Final Component Steps:
 - Invite a friend to the world and wait for them to load up completely.
 - With that same attach component menu in the same slot (Main Area), go to Assets -> Utility -> AudioClipAssetMetadata, then add it.
 - Kaboom! World Crash!

### Expected behavior

It should not crash a world, that is for sure.

### Resonite Version Number

Beta 2024.7.20.1115

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index & Desktop

### Log Files

[ANDREW-SUPERPC - 2024.7.20.1115 - 2024-07-21 06_06_09.log](https://github.com/user-attachments/files/16324044/ANDREW-SUPERPC.-.2024.7.20.1115.-.2024-07-21.06_06_09.log)

### Additional Context

In the logs both when using mods and no mods, I received the following error: `System.ArgumentException: Type Elements.Assets.ChannelConfiguration is not registered type in assembly Elements.Assets`

### Reporters

 - AmasterAmaster
 - harmonicafenneccat

**Comment by HarmonicaAlex95** [comment]
[DESKTOP-IU9ITDT - 2024.7.20.1115 - 2024-07-21 19_22_41.log](https://github.com/user-attachments/files/16324057/DESKTOP-IU9ITDT.-.2024.7.20.1115.-.2024-07-21.19_22_41.log)

**Comment by AmasterAmaster** [comment]
Apparently from what I am hearing, that this could be even simpler to replicate by just using an empty object as the slot to hold the components.

**Comment by sveken** [comment]
[75dbf7778dbd - 2024.7.20.1115 - 2024-07-21 11_44_42.log](https://github.com/user-attachments/files/16324084/75dbf7778dbd.-.2024.7.20.1115.-.2024-07-21.11_44_42.log)

**Comment by AmasterAmaster** [comment]
Headlesses have an interesting side effect of still running and only the world being closed.

**Comment by Frooxius** [comment]
Fixed in 2024.7.22.1319, thanks for report!
