### ISSUE TITLE
[Regression] Other Platform Migration login failure

### ISSUE THREAD

**Issue by DanteTucker** [Yellow-Dog-Man/Resonite-Issues#2646]
### Describe the bug?

Since 2024.7.20.1115 Migration from Other Platform is no longer possible.
Migration fails on submitting account credentials, displaying "Loading..." forever.

From what I can see in the logs, this is likely due to the recent SignalR changes.

### To Reproduce

Start a new migration, provide account credentials and attempt to submit them.

### Expected behavior

Migration should proceed past login page.

### Resonite Version Number

2024.7.20.1115

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-TBLIEGS - 2024.7.20.1115 - 2024-07-22 08_26_46.log](https://github.com/user-attachments/files/16333095/DESKTOP-TBLIEGS.-.2024.7.20.1115.-.2024-07-22.08_26_46.log)

**Comment by Frooxius** [comment]
Fixed this in 2024.7.22.1319, thanks!
