### ISSUE TITLE
Mono Headless on Windows fails to launch after update to 2024.7.22.1319

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2649]
### Describe the bug?

On updating the mono headless to version 2024.7.22.1319, an exception is thrown on launch and the headless crashes on Windows.

Linux machines work fine.

Doubt this is a high priority considering the mono headless is being deprecated soon, but logging this regardless.

### To Reproduce

Launch mono headless on Windows after updating to build 2024.7.22.1319, observe the headless crashing.

### Expected behavior

Headless to start and not crash

### Resonite Version Number

2024.7.22.1319

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Headless

### Log Files

[WINSERVER - 2024.7.22.1319 - 2024-07-23 16_38_32.log](https://github.com/user-attachments/files/16343838/WINSERVER.-.2024.7.22.1319.-.2024-07-23.16_38_32.log)

### Reporters

bredo, ZachTheMicroHybrid

**Comment by epicEaston197** [comment]
Isn't the Mono Headless plan to be deprecated soon?

**Comment by shiftyscales** [comment]
Yes, following the completion of #2539 we will be removing support / use of mono entirely for the headless, @bredo228. Are there any user hosted events or similar you are aware of that are currently impacted by this issue? Otherwise, we'd probably recommend users to switch over to using .NET 8.0 since it'll be happening soon regardless if any additional critical issues are not identified by testing it.

**Comment by bredo228** [comment]
> Yes, following the completion of #2539 we will be removing support / use of mono entirely for the headless, @bredo228. Are there any user hosted events or similar you are aware of that are currently impacted by this issue? Otherwise, we'd probably recommend users to switch over to using .NET 8.0 since it'll be happening soon regardless if any additional critical issues are not identified by testing it.

There's no events running on the Windows mono headless that I'm aware of - discovered this because there was someone in Discord having this issue, which was solved by moving them to .NET 8. Only really logged this because it is a regression in functionality, despite the planned removal of support.

**Comment by Frooxius** [comment]
I've managed to fix this, it's just wrong version mapping.

I think it might be a bit moot, since we'll yeet the Mono headless anyways, but I at least added some extra useful logging to catch similar issues in the future.

**Comment by Frooxius** [comment]
Fixed this in 2024.7.24.1106. Thanks!
