### ISSUE TITLE
Youtube videos don't dislat video, only audio.

### ISSUE THREAD

**Issue by TisFoolish** [Yellow-Dog-Man/Resonite-Issues#2664]
### Describe the bug?

If you try to load any YouTube video the audio will be the only thing that loads is the audio. Tested as host and on a headless

### To Reproduce

Load any youtube video

### Expected behavior

Videos play

### Screenshots

As host
![2024-07-25 01 32 17](https://github.com/user-attachments/assets/71541123-d687-47fb-bb37-ddbe51d868f8)

On a headless
![2024-07-25 01 33 31](https://github.com/user-attachments/assets/b0813f54-073b-48ab-9fbd-de163d1e5f36)

### Resonite Version Number

Beta 2024.7.24.1106

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[CATBED - 2024.7.24.1106 - 2024-07-24 20_30_03.log](https://github.com/user-attachments/files/16370396/CATBED.-.2024.7.24.1106.-.2024-07-24.20_30_03.log)

### Additional Context

I was in a session where every single person, both modded and unmodded, had this same issue. It's definitely because Google is fighting adblockers.

### Reporters

Discord: foolishsnowmew

**Comment by Raidriar796** [comment]
This was fixed in nightly/master branch for a few days, but as of 4 hours ago the fix just released to the stable branch.
You can update it manually by opening the RuntimeData directory in Powershell (or use cd to change to it) and run `.\yt-dlp.exe -U`.

**Comment by Frooxius** [comment]
Updated yt-dlp in 2024.7.25.1115, which should fix this. Thanks for repot!
