### ISSUE TITLE
VirtualParent doesn't drive values unless _targetPos is set

### ISSUE THREAD

**Issue by Archytas79** [Yellow-Dog-Man/Resonite-Issues#2666]
### Describe the bug?

VirtualParent doesn't drive values unless _targetPos is set

### To Reproduce

Place a VirtualParent on a slot, set the OverrideParent and drive the rotation only. Notice it doesn't drive.

### Expected behavior

I'm trying to use VirtualParent as a way to copy the *rotation only* of another bone, but it currently requires I copy the position too. This is different than how constraints work in every other 3d application, where you can set different transform components separately from eachother.

### Resonite Version Number

2024.7.24.1106

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

Desktop

### Log Files

no logs required? seems pretty straightforward. lemme know if I should report logs.

**Comment by Frooxius** [comment]
This is expected behavior.

VirtualParent makes the object behave as if another Slot is its parent, even though "physically" it's not. In order to achieve that behavior, it needs to control the object's position, rotation and scale.

**Comment by Archytas79** [comment]
Is there a way to constrain rotations the same as Rotation Constraint in Unity or Copy Rotation in Blender? This feels like a core feature missing.

**Comment by Frooxius** [comment]
I don't know how those work exactly so I can't say. But that should be a separate issue.

**Comment by Dusty-Sprinkles** [comment]
> Is there a way to constrain rotations the same as Rotation Constraint in Unity or Copy Rotation in Blender? This feels like a core feature missing.

browsing through closed issues, if you didn't figure this out yet you can use CopyGlobalTransform to get rotation, position, or both for an object without automatically driving the others. Its used for digi legs a lot
