### ISSUE TITLE
Websockets no longer connect and fail

### ISSUE THREAD

**Issue by ScarsTRF** [Yellow-Dog-Man/Resonite-Issues#2670]
### Describe the bug?

When attempting to connect to a websocket, the connection will never be handled as there is a exception in the game.

### To Reproduce

1. Create a websocket component.
2. Enter a websocket URL.
3. Add your user as the handler.
4. Your client will NOT connect even if there is a server on the URL

### Expected behavior

The websocket should connect without issues.

### Resonite Version Number

Beta 2024.7.25.1115

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Quest Pro

### Log Files

[SCARS-WIN-VM - 2024.7.25.1115 - 2024-07-25 15_15_33.log](https://github.com/user-attachments/files/16383411/SCARS-WIN-VM.-.2024.7.25.1115.-.2024-07-25.15_15_33.log)

### Reporters

Discord: scarstrf
Resonite: ScarsTRF

**Comment by Frooxius** [comment]
I can't replicate this on my end, websockets seem to work correctly.

Can you check if there's a `System.Net.WebSockets.Client.Managed.dll` file in your install of Resonite? In the `Resonite_Data\Managed` subfolder?

**Comment by ScarsTRF** [comment]
Its is not, I validated my files and it's still not there

**Comment by Frooxius** [comment]
Hmm... This is really odd. The file exists in the build folder, so I'm not sure why ti's missing from your install. I'll have to investigate.

**Comment by lxw404** [comment]
Experiencing the same thing.  These are the only files with "WebSockets" in the filename in `Resonite/Resonite_Data/Managed`:

![explorer_Ldfv8TZgH9](https://github.com/user-attachments/assets/bbe8be26-1274-4059-a850-79e737695d5c)
![explorer_dMLcTByKFA](https://github.com/user-attachments/assets/01b49902-cb0f-4d5b-9381-9d0f888865cb)

**Comment by ScarsTRF** [comment]
Reinstalled the entire game just for safe measure, still nothing.

**Comment by Frooxius** [comment]
I have no idea how the file disappeared, but I just republished the build as 2024.7.25.1284

This seems to include the file. Closing this now, thanks!
