### ISSUE TITLE
Asset Variant System is down

### ISSUE THREAD

**Issue by Raidriar796** [Yellow-Dog-Man/Resonite-Issues#2675]
### Describe the bug?

Based on the #alerts channel in the discord, the Asset Variant System has been down for 15 hours as of writing.

### To Reproduce

n/a

### Expected behavior

The Asset Variant System should be running.

### Resonite Version Number

Beta 2024.7.25.1284

### What Platforms does this occur on?

Windows, Linux

### Log Files

n/a

### Additional Context

I'm starting to experience certain asset variants not loading. Also some shader variants may not be getting made as a configuration of unlit that I'm trying to do is causing unlit to stop updating but `Waiting for apply` still says false so I'm unsure if the shader is breaking or just trying to request a variant.

### Reporters

@Raidriar796 / raidriar796

**Comment by ProbablePrime** [comment]
Its backup, Generally if we have an alert in #alerts for it then a GH issue is not required. I was just sleeping a lot :( see, #2676 for the ultimate solve.
