### ISSUE TITLE
Resonite crashing on startup

### ISSUE THREAD

**Issue by defnoteid** [Yellow-Dog-Man/Resonite-Issues#2678]
### Describe the bug?

Loading seems to get stuck around 75%
The logs get cut off

### To Reproduce

idk

### Expected behavior

Resonite loading successfully

### Screenshots

![image](https://github.com/user-attachments/assets/2699aa34-09d0-4bce-9f72-4fd61f007b30)

### Resonite Version Number

2024.7.25.1284

### What Platforms does this occur on?

Windows

### What headset if any do you use?

None

### Log Files

[defnoteid - 2024.7.25.1284 - 2024-07-26 12_56_45.log](https://github.com/user-attachments/files/16387123/defnoteid.-.2024.7.25.1284.-.2024-07-26.12_56_45.log)
[Player.log](https://github.com/user-attachments/files/16387127/Player.log)

### Additional Context

resonite cache was cleared this week
this isnt my first time playing resonite
renamed local database

### Reporters

@defnoteid
@karasutengu

**Comment by defnoteid** [comment]
i honestly don't know how to reproduce this :/

**Comment by shiftyscales** [comment]
I have also had this happen in past, although it does seem rare / random when it does occur. Thanks for making this issue.

**Comment by stiefeljackal** [comment]
When this occurred, did you leave the startup screen in this frozen state for a few minutes before ending the process? Or did you force the process to end immediately after a few seconds?

**Comment by defnoteid** [comment]
> When this occurred, did you leave the startup screen in this frozen state for a few minutes before ending the process? Or did you force the process to end immediately after a few seconds?

I left it open for many minutes. I thought that it would've got past loading.

**Comment by stiefeljackal** [comment]
> I left it open for many minutes. I thought that it would've got past loading.

So it stops the stream for the log from being fully flushed as well. There is certainly a deadlock occurring during initialization if that is the case.

**Comment by defnoteid** [comment]
Installing NET 8 didn't help I guess
same result

**Comment by stiefeljackal** [comment]
> Installing NET 8 didn't help I guess same result

Installing .NET 8 will not address the issue since your issue involves the graphical client, which that still requires .NET Framework. .NET 8 is only applicable to the Headless Client, also known as the Headless Server Software.

**Comment by defnoteid** [comment]
> > Installing NET 8 didn't help I guess same result
> 
> Installing `.NET 8` will not address the issue since your issue involves the graphical client, which that still requires only `.NET Framework 4.6.2`. `.NET 8` is only applicable to the Headless Client (also known as Headless Server Software).

![image](https://github.com/user-attachments/assets/ebd609bf-cdb4-40a0-aeb5-8ff5cf524a44)

**Comment by stiefeljackal** [comment]
> ![image](https://private-user-images.githubusercontent.com/157801052/361100199-ebd609bf-cdb4-40a0-aeb5-8ff5cf524a44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ0ODI1NDIsIm5iZiI6MTcyNDQ4MjI0MiwicGF0aCI6Ii8xNTc4MDEwNTIvMzYxMTAwMTk5LWViZDYwOWJmLWNkYjQtNDBhMC1hZWI1LThmZjVjZjUyNGE0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQwNjUwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zY2IyODRkM2U3ZTgzNmQ1MWQ1YjViNzc2MjJlYTZiYzBkNGZlZmU2MGE0ZWViMWY5NTZlMDk0OTgyMzU4ZjQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nSmw5k3GvG1hjZo4i3XpV8Df5dGeLJBZ3f-ZOZT_-Nk) PS: `.NET 6.08` is already installed, I honestly have no idea on what I'm doing

Don't worry about .NET or .NET Framework. Unfortunately, the best thing I can say is if you witness the issue again and the log file happens to print more information than what you originally uploaded, then upload that new file.

**Comment by defnoteid** [comment]
Sorry for the necro, I got my PC fixed and now Resonite functions as expected
![image](https://github.com/user-attachments/assets/b11d5a6b-3665-45eb-80b5-d6d7195f43b3)
(I renamed my local database long before this screenshot was taken)

**Comment by shiftyscales** [comment]
I think I must have misunderstood the initial issue, @defnoteid - you were previously crashing **every** time you tried launching Resonite?

**Comment by defnoteid** [comment]
> I think I must have misunderstood the initial issue, @defnoteid - you were previously crashing **every** time you tried launching Resonite?

well that was **until** that comment

**Comment by shiftyscales** [comment]
Hmm- given there is no clear replication case / cause for this issue, and you seem to no longer have this issue, I think it would probably be best that we closed this issue. If you continue to have issues down the line- please make a new issue, or we can re-open this one, @defnoteid.
