### ISSUE TITLE
Unity crash when starting in VR

### ISSUE THREAD

**Issue by Uruloke** [Yellow-Dog-Man/Resonite-Issues#2689]
### Describe the bug?

Making this report on behalf of a friend of mine who keeps getting a Unity crash every time he tries to start Resonite in VR mode. All he sees is a brief moment of black screen with the Resonite logo before the Unity crash dialog pops up. This is 100% reproducible on his machine. Starting the game up in desktop mode works fine.

### To Reproduce

1. Start game in Steam VR mode.

### Expected behavior

Game should continue to show the loading bar and eventually load into the local world.

### Resonite Version Number

2024.7.25.1284

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[DESKTOP-O4HQE03 - 2024.7.25.1284 - 2024-07-28 19_09_24.log](https://github.com/user-attachments/files/16419298/DESKTOP-O4HQE03.-.2024.7.25.1284.-.2024-07-28.19_09_24.log)
[error.log](https://github.com/user-attachments/files/16419300/error.log)
[Player.log](https://github.com/user-attachments/files/16419301/Player.log)

### Additional Context

The logs seems to reference attempting to access invalid addresses in the AMD GPU driver so I've had him update to the latest drivers but it still seems to crash.

### Reporters

@uruloke
@nessunday

**Comment by shiftyscales** [comment]
The stack trace indicates the crash is likely related to SRanipal- so I believe this may be the same underlying issue as #1376, @Uruloke.

Could your friend try downgrading to an earlier SRanipal version, ideally an older one like 1.3.1.1 and see if the issue persists?

**Comment by Uruloke** [comment]
Looks like he did indeed have SRanipal installed. He doesn't even have face tracking so not sure why he'd have the software for it. After uninstalling it the game now seems to start normally.

**Comment by shiftyscales** [comment]
I see. I'll close this issue for now then thanks, @Uruloke.
