### ISSUE TITLE
Search bar for adding components and protoflux nodes

### ISSUE THREAD

**Issue by Quote-2004** [Yellow-Dog-Man/Resonite-Issues#271]
### Is your feature request related to a problem? Please describe.

Sometimes I forget in what category a certain node or component is and have to look trought almost all of them before I find it, it can be frustrating and time consuming at times.

### Describe the solution you'd like

A little search bar at the top of the menus to search for specific nodes and/or components would be helpful as a shortcut for finding that specific thing you want to add.

### Describe alternatives you've considered

No alternatives considered but anything that can help find nodes/components easier and faster

**Comment by Mawco** [comment]
Could also have a recently used components / Flux nodes list with favorites 🤷

**Comment by antrobot1234** [comment]
to add on to this, i really feel like they should at least give us the option to switch back to the grid view for flux nodes. Having them in a single column list is terrible for readability.

**Comment by antrobot1234** [comment]
@Mawco you should create a separate feature request for favoriting flux nodes or components. you should include that they can be nested in folders similar to how the current system works, just controlled by the user.
