### ISSUE TITLE
Discord: Allow users to mute topics

### ISSUE THREAD

**Issue by CybrixTheProot** [Yellow-Dog-Man/Resonite-Issues#2715]
### Is your feature request related to a problem? Please describe.

Currently, users can not mute topics
![image](https://github.com/user-attachments/assets/cb0b6801-0eb3-42f4-b23b-0418c59543ad)

### Describe the solution you'd like

Allow user to mute topics

### Describe alternatives you've considered

Muting the server entirly

### Requesters

Cybrix

**Comment by ProbablePrime** [comment]
I've been on a journey through a bunch of discords I am in that have forums and discovered a solution.

- You can only mute posts that you are "Following".
- If you're not following it, you cannot mute them. 

There's nothing we can do on our end to change this so I will close this issue as not planned.

**Comment by Dusty-Sprinkles** [comment]
If it helps at all, you can mute the forum that whatever topics you want to mute are associated with.
