### ISSUE TITLE
Driving tags and searching by tag with flux crashes game

### ISSUE THREAD

**Issue by bobjbo** [Yellow-Dog-Man/Resonite-Issues#2720]
### Describe the bug?

When I try to search and do stuff based off a findchildbytag node on a hierarchy with an object that is having its tag be driven causes my game to freeze completely

### To Reproduce

I don't know exactly how to reproduce but I have a snappable object that has a slot having its tag be driven and a piece of protoflux that uses the findchildbytag node and a while node to loop through all objects of a tag in the hierarchy but when you start the process on an object that has a driven tag it just freezes my client

### Expected behavior

I didn't expect it to freeze my client I expected it to just find the slot and continue onward, the same system doesn't cause a crash when the tag becomes un driven

### Screenshots

![image](https://github.com/user-attachments/assets/01140772-aaf6-4b29-885b-c3c47b078fc5)
![image](https://github.com/user-attachments/assets/53c7fe62-b5e5-49c1-be21-d7b2898eeb74)
![image](https://github.com/user-attachments/assets/5f04e87c-238e-4a0e-9c4e-2a9d11d56c2d)

### Resonite Version Number

2024.7.25.1284

### What Platforms does this occur on?

Windows

### What headset if any do you use?

This happens on desktop but I use a bigscreen beyond

### Log Files

[LAPTOP-OT5GN80K - 2024.7.25.1284 - 2024-08-05 07_11_17.log](https://github.com/user-attachments/files/16495586/LAPTOP-OT5GN80K.-.2024.7.25.1284.-.2024-08-05.07_11_17.log)

### Additional Context

first image is the searching flux, second image is the main avatar hierarchy and the third image is the snappable hierarchy that the flux searches

### Reporters

bobjbo

**Comment by JackTheFoxOtter** [comment]
This is very likely an issue of your code running into an endless loop. Make sure the condition of your while loop actually turns false eventually in all cases! I'm frequently driving names and tags, searching them works as expected. The field being driven shouldn't impact the functionality of the slot searching nodes.

**Comment by JackTheFoxOtter** [comment]
There's also https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/256, which is a bug that can happen if the last node in the chain of an "iteration" impulse modifies the loop's running condition, which can lead to endless loops even if the logic is correct, due to the missing cache invalidation. That can be mitigated by adding any non-operation node to the end of the chain, like an impulse display or just a relay.

**Comment by bobjbo** [comment]
but it works perfectly fine when i'm not driving the tag

**Comment by JackTheFoxOtter** [comment]
Well, there is a "set tag" I can see at the end of the code. If you're trying to set a tag that is driven, that will fail, as you can't write to a field if it's driven my something else.

**Comment by bobjbo** [comment]
I realize that now lol, I was very tired when I first tried this
