### ISSUE TITLE
Crashing to Desktop

### ISSUE THREAD

**Issue by Mr-Mumbles** [Yellow-Dog-Man/Resonite-Issues#2741]
### Describe the bug?

When Clicking on Certain things such as opening my menu, clicking a players name, spawning an item etc, resonite will crash to desktop.

### To Reproduce

I appear to **crash more in solo worlds**, such as at home (happens very quickly) and **even in a fresh blank world**. Every time it happens, my screen freezes just after performing an action such as opening my menu, spawning an item, or clicking on something such as a player or interactable. I seem to be **more stable in public worlds**, I will only crash in those if I happen to click on something at the wrong moment. **In single player worlds, I crash very quickly**. (Within minutes of being inside a solo world, but having it loaded seems fine?)

### Expected behavior

No Crashes, my laptop specs seem to be able to handle this game smoothly, and **I can run 2 other VR games very smoothly**. **All other Desktop games run just fine**.

### Resonite Version Number

2024.7.25.1284

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 1, Quest Link/ALVR ||| SteamVR Runtime/Meta Quest link

### Log Files

[error.log](https://github.com/user-attachments/files/16559217/error.log)
[Player.log](https://github.com/user-attachments/files/16559218/Player.log)

### Reporters

mumbles

**Comment by XDelta** [comment]
Can you provide your regular log file as well. The latest one from a crash in your `Resonite/Logs/` folder (https://wiki.resonite.com/Log_Files). Additionally does the game still crash when in desktop mode?

**Comment by XDelta** [comment]
Just saw a bit more from your thread in #questions-helps channel (https://discord.com/channels/1040316820650991766/1270307789327175731). Additional things that can narrow down options would be to not load the cloud home and just remain in the local home using either `-DoNotAutoLoadHome` in your launch arguments or the `Load cloud home on startup` option in Settings > Profile > Favorites. Another would be wearing a different avatar/default avatar in a world to maybe catch a case of something on the avatar is causing it.

**Comment by Mr-Mumbles** [comment]
I just tried desktop mode and did not appear to crash, although I only tested it for a few minutes. I then went back into VR and loaded a Grid world, after a few mins of playing around with some toys I crashed, here is the regular Log...
[Regular Log File.log](https://github.com/user-attachments/files/16561011/Regular.Log.File.log)

I will try using another avatar now, by the way thanks for the fast response! I was expecting to hear a reply in a few days, so sorry for not replying sooner!

**Comment by XDelta** [comment]
Probably a good test if you can run the desktop mode for a longer period of time than a few minutes. if the other crashes were occurring at some random times usually a few minutes in.

**Comment by Mr-Mumbles** [comment]
tested 40 mins in a solo grid world and no crashes, game ran fine, so that means its a VR issue....but is it on my end or resonites?

**Comment by XDelta** [comment]
Possibly a bit of both, Try with VR in just the local home and no other world open? Along with try in a world with a different or the default avatar? Could be related to a specific component that was a cause of a few crashes previously but most of those were remedied or significantly reduced. Other things to check would just be up to date graphics drivers

**Comment by Mr-Mumbles** [comment]
> Try with VR in just the local home and no other world open?

This worked, no crashes after 10 minutes

> Other things to check would just be up to date graphics drivers

All up to date.

> Along with try in a world with a different or the default avatar? 

This seemed to fix it!!!!!  I lasted more than 10 minutes using the default neos avatar, but after equipping my old avatar, a few mins later I then crashed.

I then went a few hours or so without crashing after staying on different avatars, in public and solo worlds. (and still no crashes, I just closed the game)
I believe that was the issue...possibly....

But anyways, thankyou so much for your help!

**Comment by shiftyscales** [comment]
If possible you should try and isolate what on your avatar is causing that issue, @Mr-Mumbles. If it can be isolated, it's possible it could be fixed. I'd recommend stripping your avatar and its systems down bit by bit and saving separate copies and seeing if you can isolate what is causing the crashes.

**Comment by Mr-Mumbles** [comment]
> If possible you should try and isolate what on your avatar is causing that issue,

Im sorry! I think I deleted the avatar without thinking. If I recall correctly, It was the mp cherubbot with a bunch of plugins installed.

> I'd recommend stripping your avatar and its systems down bit by bit

Im not very skilled in Resonite sorry, I wouldnt really know how.

Its a shame im not much help on narrowing down what the problem was, but if it makes things better or worse, I can close this issue if you want. If not, let me know what else I can do to help, im just happy you helped me fix the crashing!

**Comment by shiftyscales** [comment]
We can close this issue for now, then. If you happen to come across the issue again, please feel free to open a new issue, @Mr-Mumbles. Thank you.
