### ISSUE TITLE
Buggy behaviour for shorter avatars: Spawning out items, ProtoFlux nodes, and import files at a non-default scale. And strange behaviour when switching to different avatar.

### ISSUE THREAD

**Issue by theBaksoBoy** [Yellow-Dog-Man/Resonite-Issues#2742]
### Describe the bug?

Despite the shorter avatar being used having its scaling disabled, implying that the scale is set to the default, spawning out objects from your inventory, creating ProtoFlux nodes, and importing things such as 3D models, make the created object have a scale that is not (1, 1, 1), but rather something else (in this case (0.75, 0.75, 0.75)).

Another strange behaviour is that whenever you are in the shorter avatar, and switch to a different avatar, instead of your POV switching to the new avatar, the new avatar will instead teleport to your current POV, where the new avatar will also have its scale changed to match your height.

### To Reproduce

I unfortunately do not know how to reproduce this, nor want to publically share my avatar. I apologize for making this issue harder to resolve.

### Expected behavior

Spawned items, ProtoFlux nodes, and imported files to have a default scale of (1, 1, 1).
Changing avatar to move one's POV to that new avatar, instead of the new avatar teleporting to your new POV with that avatar's scale being modified.

### Screenshots

This video shows the buggy behaviour previously mentioned. Note that the scale of the short avatar is always set to "Scaling Disabled", and thus has the default scale. I forgot to show this when recording.
https://github.com/user-attachments/assets/92e86277-fe3b-4928-9481-85bea85a17ae

Video of me scrolling through all components on the root object of the avatar, in case some setting there is of interest.
https://github.com/user-attachments/assets/23447487-0cbb-4218-87f6-595b2b80f389

### Resonite Version Number

2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

Steps for what I did for the session that generated the log file:
1. Automatically go into my home world, which is a modified cloud home world. I have set the short avatar as my avatar, so I had it equipped by default.
2. spawn an object from my inventory (which gets an incorrect scale)
3. spawn out a ProtoFlux tip, and use the node browser to spawn out a node (which gets an incorrect scale)
4. spawn the default avatar from my inventory, go in to it to reset its scale, go back to the short avatar (works as intended), and then go back to the default avatar (which teleports to my POV and changes its scale)

Here is the log file:
[DESKTOP-B7G9V7U - 2024.8.5.1341 - 2024-08-09 15_36_03.log](https://github.com/user-attachments/files/16561950/DESKTOP-B7G9V7U.-.2024.8.5.1341.-.2024-08-09.15_36_03.log)

### Reporters

baksoBoy

**Comment by epicEaston197** [comment]
I wouldn't want this having it be smaller relative to my scale as preferable to me

**Comment by JackTheFoxOtter** [comment]
> Despite the shorter avatar being used having its scaling disabled, implying that the scale is set to the default, spawning out objects from your inventory, creating ProtoFlux nodes, and importing things such as 3D models, make the created object have a scale that is not (1, 1, 1), but rather something else (in this case (0.75, 0.75, 0.75)).

I think here lies the main misunderstanding. When the context menu shows "scaling disabled", that means the avatar is scaled to its default scale, but that default scale isn't (1, 1, 1). Most likely, the default scale of your avatar is set to (0.75, 0.75, 0.75) if that's what objects you spawn are scaled to by default. This is an intentional behavior. Things you spawn are supposed to always have the same *relative* size to you. Otherwise, if you were really small, any ProtoFlux node or inspector window scaled to (1, 1, 1) would be enormous and pretty much unusable, the same goes the other way around, where things would be too small to use properly if your avatar is really big.

**Comment by theBaksoBoy** [comment]
> > Despite the shorter avatar being used having its scaling disabled, implying that the scale is set to the default, spawning out objects from your inventory, creating ProtoFlux nodes, and importing things such as 3D models, make the created object have a scale that is not (1, 1, 1), but rather something else (in this case (0.75, 0.75, 0.75)).
> 
> I think here lies the main misunderstanding. When the context menu shows "scaling disabled", that means the avatar is scaled to its default scale, but that default scale doesn't have to be (1, 1, 1). Most likely, the default scale of your avatar is set to (0.75, 0.75, 0.75) if that's what objects you spawn are scaled to by default. This is an intentional behavior. Things you spawn are supposed to always have the same _relative_ size to you. Otherwise, if you were really small, any ProtoFlux node or inspector window scaled to (1, 1, 1) would be enormous and pretty much unusable, the same goes the other way around, where things would be too small to use properly if your avatar is really big.

Is there a way to change this, so that what you spawn in has a default world scale instead of a relative scale? If this is due to my avatar having a scale of (0.75, 0.75, 0.75), do you know where that could be? As the root of the avatar does have a scale of (1, 1, 1).

**Comment by theBaksoBoy** [comment]
> I wouldn't want this having it be smaller relative to my scale as preferable to me I like the existing behavior

That's fair. I guess it would be best if there were some kind of setting where you could chose if it scaled everything relative or not. Although honestly it does sound like that kind of already is a thing, as I'm pretty sure that my avatar isn't specifically 25% shorter than the default avatar, so it feels way too specific for spawned objects to have a scale of specifically 0.75. It definitely sounds like this is some mistake on my end whenever I created the avatar.

**Comment by shiftyscales** [comment]
Looked through the video and saw you have a DefaultUserScale of 0.75 set on the root of your avatar, @theBaksoBoy. It was at the very bottom when you scrolled through it. I assume that was set purposefully given the aesthetic of the avatar- presumably it's supposed to be shorter than a typical human scale.

As others had noted- it is by design that anything you spawn is scaled relative to your current scale- without that behaviour- it can cause issues when users are particularly large or particularly small.

Is there any particular reason you are wanting / needing to spawn everything out at a fixed unit (1) scale instead of relative to your current size?

**Comment by theBaksoBoy** [comment]
> Looked through the video and saw you have a DefaultUserScale of 0.75 set on the root of your avatar, @theBaksoBoy. It was at the very bottom when you scrolled through it. I assume that was set purposefully given the aesthetic of the avatar- presumably it's supposed to be shorter than a typical human scale.
> 
> As others had noted- it is by design that anything you spawn is scaled relative to your current scale- without that behaviour- it can cause issues when users are particularly large or particularly small.
> 
> Is there any particular reason you are wanting / needing to spawn everything out at a fixed unit (1) scale instead of relative to your current size?

@shiftyscales Oh oops, I didn't realize that I had changed that. Yeah you are probably right with me having done that on purpose (which I first thought wasn't the case in my previous comment), as the character that my avatar is off of has a specific height.

I understand that if stuff isn't relative to my avatar's scale that it can sometimes cause problems, however I don't think that it would be very bad, as my character's height is still decently close to the default scale/height. The reason I want everything to be at the default unit scale is simply just because I find that way easier to work with, if I were to for example collaborate with others, where everything would look weird due to everyone's protoflux being at different scales, or whenever I make 3D models of something with specific dimensions made in the model process, where I would then expect those dimensions to be the same once imported into Resonite. And just the general fact that I find it way more pleasing if everything is at an expected unit scale, unless the object has a specific reason for not having that.

Is it possible to make my avatar have a DefaultUserScale of 1 whilst still making it short? I tried changing the AvatarHeight parameter in the VRIKAvatar component, however unless I am mistaken, it serves a different purpose than setting the actual height of the player using the avatar.

**Comment by JackTheFoxOtter** [comment]
> Is it possible to make my avatar have a DefaultUserScale of 1 whilst still making it short?
No. The DefaultUserScale is the default scale.

> The reason I want everything to be at the default unit scale is simply just because I find that way easier to work with, if I were to for example collaborate with others, where everything would look weird due to everyone's protoflux being at different scales, or whenever I make 3D models of something with specific dimensions made in the model process, where I would then expect those dimensions to be the same once imported into Resonite.

I fully agree with that. What I did is put a context menu button on my avatar to scale me to exactly 1.0. I use that whenever I build something, and then reset my scale when I'm done.

**Comment by theBaksoBoy** [comment]
> I fully agree with that. What I did is put a context menu button on my avatar to scale me to exactly 1.0. I use that whenever I build something, and then reset my scale when I'm done.

Aah that sounds like a decent workaround. I think I'll add that to the avatar for now!

Do you think it would be reasonable for me to make a Feature Request for some avatar component having a bool for if spawned objects should spawn at unit scale or DefaultUserScale, or something like that?

**Comment by shiftyscales** [comment]
You certainly could put in a feature request to have spawned objects / nodes ignore your current user scale. You can link back to this issue by mentioning it #2742 if you wish to provide additional context to the issue.

In your request you could highlight the use-cases established, e.g. multiple users working on the same ProtoFlux causing nodes to spawn in at differing sizes.

It is also worth noting that there does exist user-made tools that snap / resize ProtoFlux to be the same size which could possibly augment your workflow if you decide that'd work better than having a button to reset yourself to 1 scale.

Can this issue be closed for now then, @theBaksoBoy? Did you have any other questions?

**Comment by theBaksoBoy** [comment]
Alright. I'll make a feature request about this. Thanks for the help!

**Comment by ko-tengu** [comment]
I will note as someone else who dislikes this function, there is a mod to disable or limit it.
https://github.com/hantabaru1014/SaveItemTweaks
