### ISSUE TITLE
Add JP names to the IK for humanoid bones

### ISSUE THREAD

**Issue by SilvyPaws** [Yellow-Dog-Man/Resonite-Issues#2748]
### Is your feature request related to a problem? Please describe.

When importing avatars that are using JP names, Resonite fails to assign the bones to the IK and detects it as not humanoid. 

### Describe the solution you'd like

For Resonite to properly recognize JP characters for IK assignment, I'm surprised this wasn't already a thing since it already can auto detect JP shapekeys for both visemes and facetracking

### Describe alternatives you've considered

There's no alternatives, it's pretty straight forward!

### Additional Context

If you'd like some resources on what JP calls bones and stuff, i'd recommend talking to some of our big JP Members like @orange3134 -- I tried finding some resources but couldn't find anything. Forestwind has some [free avatars](https://forestwind.booth.pm/items/2230144), the rikkor that has JP bone names you can look at for help. ALL of their avatars have japanese bone names so they're a pain to translate if someone hasn't already setup a package for the avatar. They're just one creator example that don't use english names. 

### Requesters

SilvyPaws

**Comment by Frooxius** [comment]
I do not speak Japanese, so I'd need a list of the Japanese bone names for this to happen.

**Comment by SilvyPaws** [comment]
I spoke with Orange and a few other Japanese users and they told me there isn't really a naming scheme for character bones so this request can't really be resolved. However, one of them suggested Resonite have an advance import feature that allows the user to manually assign bones into the IK before the IK is actually initialized. Similar to how it's done in Unity:
![image](https://github.com/user-attachments/assets/98b773ed-c3fc-41c9-a271-60c893ae140e)

**Comment by shiftyscales** [comment]
I'm going to close this out then, @SilvyPaws. If there isn't a consistent naming scheme we don't have any work to be done here, and your other request would be better suited as its own separate issue.
