### ISSUE TITLE
PlayOneShot, PlayOneShotAndWait moved to 'FrooxEngine/Audio' in ProtoFlux Browser

### ISSUE THREAD

**Issue by softestpoly** [Yellow-Dog-Man/Resonite-Issues#275]
### Describe the bug?

The PlayOneShot and PlayOneShotAndWait nodes have been displaced from the 'Media' category to the 'FrooxEngine/Audio' category in the ProtoFlux node browser.

### To Reproduce

Pull out a ProtoFluxTool, select Browse Nodes in the context menu, observe the 'FrooxEngine' category

### Expected behavior

PlayOneShot and PlayOneShotAndWait should be located in Media 

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7283258/5ad8565c-e5a8-4030-8fa5-2db8e1b73d6a)

### Resonite Version Number

Beta 2023.10.18.449

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2 (Virtual Desktop, Oculus Runtime)

### Log Files

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13023018/Player.log)
Spawned nodes. Issue is not visible from log files.

### Reporters

softest_poly

**Comment by ProbablePrime** [comment]
Yup, will take a look, thank you for the report.

**Comment by gameboycjp** [comment]
Can confirm, forgot to open an issue yesterday.

**Comment by jae1911** [comment]
Can confirm.
