### ISSUE TITLE
US West LNL bridge is down, LNL relay is non functional

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2767]
### Describe the bug?

The US West LNL Bridge appears to be down and the US West LNL Relay appears to be unresponsive.

### To Reproduce

Note US West bridge is showing as down at https://metrics.yellowdogman.com or at https://api.resonite.com/networknodes

Force use relay with US West relay preferred, note that the connection fails.

### Expected behavior

Bridge to be up and functional, relay to be responsive

### Resonite Version Number

Beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ERIS - 2024.8.5.1341 - 2024-08-16 21_10_42.log](https://github.com/user-attachments/files/16635372/ERIS.-.2024.8.5.1341.-.2024-08-16.21_10_42.log)

### Reporters

bredo, Ocelot342

**Comment by shiftyscales** [comment]
This issue is on @ProbablePrime's radar, it may take a bit yet to get to as some things need to be re-written. Thank you for your patience.

**Comment by ProbablePrime** [comment]
I've deployed the new .NET 8 Relay and Bridge(Now called network node), to the USWest node.

This should resolve this, I'll be monitoring it for the next while and then deploying to JP node.
