### ISSUE TITLE
The AlwaysOnFacetModule component doesn't work for Facet Anchors

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#2770]
### Describe the bug?

The AlwaysOnFacetModule component allows facets to specify sub-hierarchies that always remain enabled, even when the container (dashboard or dash page) isn't currently enabled, by reparenting the sub-hierarchies into an always enabled hierarchy. This is necessary for facets that require background code to run at all times to function. 

This doesn't work when attaching the facet to a facet anchor, which get disabled when the facet anchor is not visible.

### To Reproduce

Attach a component that uses AlwaysOnFacetModule to a facet anchor.

### Expected behavior

The AlwaysOnFacetModule component should function properly for all facet containers, including facet anchors.

### Screenshots

https://github.com/user-attachments/assets/ca8a766c-e6b5-4c29-8b94-132cfa71f1ac

### Resonite Version Number

Beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[J4-C - 2024.8.5.1341 - 2024-08-16 13_22_02.log](https://github.com/user-attachments/files/16636644/J4-C.-.2024.8.5.1341.-.2024-08-16.13_22_02.log)

**Comment by Zyzyl** [comment]
Important problem, but I think this is a dupe of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2236

**Comment by JackTheFoxOtter** [comment]
Oh, correct! I searched for duplicates, but must have missed that one. Closing!
