### ISSUE TITLE
Shirt in Resonite essentials has no grabbable

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2772]
### Describe the Underlying Issue

The basic shirt in the Resonite essentials folder has no grabbable.

### To Reproduce

1. Go to Resonite Essentials -> Assets -> 3D Models
2. Spawn "Baked T-Shirt Resonite"
3. Observe there are no grabbable component

### Expected Behavior

The shirt should be grabbable and scalable.

### Screenshots / Video

![Resonite_D26YrkMdtb](https://github.com/user-attachments/assets/eb9b1c12-00de-4c5b-a1e9-656f8ba038a4)

**Comment by SlyTheFloof** [comment]
i would say grabble by default
Scalable can be toggled on later for whatever reason but it should be by default scalable off and set to the scale that a real shirt would be

**Comment by TisFoolish** [comment]
Since when items are spawned their scale will be influenced by your avatar's scale and there are tons of users who's size falls well outside the realistic size range, not having scalable turned on by default would be incredibly annoying

**Comment by jae1911** [comment]
This got fixed at some point, not sure when.
