### ISSUE TITLE
Remaining instances of "Tooltip" language.

### ISSUE THREAD

**Issue by ShadeTheWinsomeWolf** [Yellow-Dog-Man/Resonite-Issues#2773]
### Describe the Underlying Issue

It took a short while (few days) when I joined to navigate the communication issue, I understand 'Tooltips' in Resonite means the Tools that attach to fingertips, but 'Tooltips' in the dictionary:
noun - Computing : A message which appears when a cursor is positioned over an icon, image, hyperlink, or other element in a graphical user interface.

Meaning it gives some text description, which ironically, no tools have any tooltips. There isn't a string/comment/FlavorText/description field for slots and item (only name and a picture in inventory) and fields and parts to the inspector for example. Yes I know there is a wiki, but tooltips are short and sweet descriptions verses whole wiki to get the simple idea.

### To Reproduce

![20240816151314_1](https://github.com/user-attachments/assets/c0dc522b-e4cd-4033-abd1-09b8d5b5ce20)

At tool ancher slot and below.

### Expected Behavior

In the picture given, please correct the few spelling errors to 'tool' from 'tooltips' labeling.
Please add Tooltip fields. <3

**Comment by ShrikeAlvaron** [comment]
They actually should just be called Tools everywhere now already, the Tooltip phrasing was changed for Resonite.  Some places as shown may still show ToolTip but those likely need to be corrected.

**Comment by lxw404** [comment]
Also just to note: people coming from a prior platform are already used to calling them "tooltips" (and you can still see this in old tutorials) so this confusion can come up even with the change in phrasing for Resonite.

**Comment by ProbablePrime** [comment]
This isn't a content a issue. There are some technical issues here so reclasifying.

In most places, we've swapped to using "Tool" but there's a few left over:
1. In the general vocabulary of our community. This one will just fade out over time.
2. In some areas in our code base that we haven't finished swapping over.

The one you pictured is the ToolAnchor area. These are just Slots within a default avatar and ideally we should be able to rename them easily.

We haven't yet though. The only reasons I can think of this are:
1. Lack of time - We're very busy
2. Backwards Compatibility - Look at your picture of a Slot Hierarchy. Some users probably rely on those names for some functionality in ProtoFlux.
