### ISSUE TITLE
An amazing free open source VR optimized water shader just dropped. Would be awesome to see added somehow if possible.

### ISSUE THREAD

**Issue by Zefnoly** [Yellow-Dog-Man/Resonite-Issues#2774]
### Is your feature request related to a problem? Please describe.

Making water looking shaders can be a hassle at times and requires a lot of work. Adding a specialized water shader could be really nice and help everyone get easy access to nice water.

### Describe the solution you'd like

This very neat open source free shader just dropped. It is optimized for VR and generally well optimized. Has functions like ripples when you collide with it, underwater shading and underwater specific fog. Supports variety of colors and settings

Youtube demo
https://youtu.be/-u3gEkhc8co

Github project link
https://github.com/zulubo/VWater

It was made for a game called Vertigo 2, the developer decided to make this shader free and open source. It could be a potentially great addition to the shader library for specialized shaders. Having inbuilt shader like this could put us one more step ahead of other platforms.

### Describe alternatives you've considered

You can make water yourself but requires work. And is not too easy to make nice looking compared to other games with specialized shaders due to limitations of how refraction shaders are handeled.

### Additional Context

Is free to be used commercially in any games, MIT license.

Also contains water masking shader for objects to hide water behind it, like boats.
Also a physics system if ever needed.

### Requesters

Zefnoly

**Comment by lxw404** [comment]
This is probably very unlikely to happen given the fact that this particular project is designed entirely around Unity while Resonite will eventually be completely divorced from Unity.

**Comment by shiftyscales** [comment]
Seeking input from @Geenz.

**Comment by Zefnoly** [comment]
> This is probably very unlikely to happen given the fact that this particular project is designed entirely around Unity while Resonite will eventually be completely divorced from Unity. Even with its permissive licensing, the effort for the team to specifically implement this one library of shaders and their corresponding scripting and then have to recreate it in the new rendering engine will probably not be worth it, whereas giving users the ability to recreate this themselves will be much more powerful long term.

I was asking for input from the team. No need to be passive aggressive about a suggestion. It was just a suggestion for an already made shader we could have while waiting for the potential divorce from unity when so happens... People will unlikely be able to make something this complex until then without a lot of workarounds anyways... And only if it wouldnt be too much work to implement.

**Comment by Frooxius** [comment]
I don't think we'd implement this unfortunately.

Adding this would add more complexity to moving towards custom rendering engine, because we'll have to re-create this shader for the new engine, which can be time costly and would delay the switch.

While implementing this now might not be as much work, it adds significantly more work to the eventual switch - it's a tradeoff we have to consider.

**Comment by Zefnoly** [comment]
> I don't think we'd implement this unfortunately.
> 
> Adding this would add more complexity to moving towards custom rendering engine, because we'll have to re-create this shader for the new engine, which can be time costly and would delay the switch.
> 
> While implementing this now might not be as much work, it adds significantly more work to the eventual switch - it's a tradeoff we have to consider.

That is understandable... My intention would be a placeholder shader that is not guaranteed to stay. I recon there are likely more shaders than just this that will have to be rebuilt either by the team or the users manually anyways... When the time comes it could just be removed with a disclaimer that "this is a temp solution, in the future this might be removed or replaced by entirely different system"

Although something I would love would be a PBR with proper refraction passthrough alongside the option for alpha transparancy, as that would allow for glass shaders with proper water already and also better glass with the ability to sustain the effects of opaque materials like shadows. I will make a different github request for this tho.

**Comment by shiftyscales** [comment]
> When the time comes it could just be removed with a disclaimer that "this is a temp solution, in the future this might be removed or replaced by entirely different system"

"Nothing is more permanent than a temporary solution."

Resonite is built with future-proofing in mind and ensuring that wherever possible, content will look and behave as close as it can to the way it was originally made forever. Having this shader included at all would mean that people will build things with it. And that would mean we'd either need to drop / break content that uses it eventually, which we're unwilling to do- or invest a significant amount of time in replicating / recreating the shader as Frooxius noted above- we are also unwilling to do at this time.

Thank you for your understanding.
