### ISSUE TITLE
The Components and ProtoFlux Nodes windows look the same; can they be made to look different?

### ISSUE THREAD

**Issue by Ralage86** [Yellow-Dog-Man/Resonite-Issues#2777]
### Is your feature request related to a problem? Please describe.

![20240818185113_1](https://github.com/user-attachments/assets/eb69f698-5893-4347-a096-0cccc330e3a2)
These two windows look the same.

### Describe the solution you'd like

Could you make the two windows look unique to each other in some way?

### Describe alternatives you've considered

Make a mod for it perhaps? I don't really think it's necessary to go that far though.

### Requesters

Ralage86 (name on Resonite and Discord)

**Comment by Frooxius** [comment]
They're technically the same UI, just differently scoped.

We don't plan on touching these, since they will be reworked completely, we have an issue for that here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/578
