### ISSUE TITLE
"Set Matrix Element" ProtoFlux node

### ISSUE THREAD

**Issue by RubberDuckShobe** [Yellow-Dog-Man/Resonite-Issues#2786]
### Is your feature request related to a problem? Please describe.

I'd like to write a ``double`` to a ``double4x4``, but I haven't yet figured out how to do this since there is no node to write an element to a matrix. There is, however, a node to *get* a matrix element by its row and column.

### Describe the solution you'd like

I'd like to have a ``Set Matrix Element`` node that allows for writing an element to a matrix by its row and column, using an ``Impulse`` as a trigger, like a ``Write`` node.
Attempts to read outside of the bounds of the matrix could be handled with an ``OnFail`` impulse as an output (like failed writes on a Write node)

### Describe alternatives you've considered

An alternative I've considered is to just wait until collections are supported in ProtoFlux.

### Additional Context

I am (ab)using a bunch of ``double4x4``s as a byte array. Of course, this is hardly an ideal solution, but I do think having a ``Set Matrix Element`` would make sense, even for uses that aren't... this.
Also see [this thread](https://discord.com/channels/1040316820650991766/1274786067559485441) on the Discord server.

### Requesters

m1nt_ (Resonite) / the_crescent_moon (Discord)

**Comment by Zyzyl** [comment]
I think this is a duplicate or subset of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/773
Specifically, that issues asks to:
> directly override a cell in a matrix

**Comment by RubberDuckShobe** [comment]
I saw that issue but didn't see that setting cells in a matrix was already
mentioned there. I guess I can close this
