### ISSUE TITLE
Default avatar does not get head override added

### ISSUE THREAD

**Issue by gameboycjp** [Yellow-Dog-Man/Resonite-Issues#2800]
### Describe the issue.

The AvatarUserViewHeadOverride and accompanying RenderTransformOverride does not get added when no favorite avatar is set. The Default Resonite Avatar in the Resonite Essentials/Avatars folder is

### To Reproduce

Unset your avatar or log out, and then either start a world or respawn with it unset. Look straight down and walk around a little, you will see the shrunken headset bobbing around. Look at the "VR_Headset" slot, and it will be missing the AvatarUserViewHeadOverride and RenderTransformOverride components

### Expected behavior

The components should be added, and the head should not be visible.

### Screenshots

https://youtu.be/gzasZcn2g6s

### Resonite Version Number

Beta 2024.8.22.1288

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-3EE2DAL - 2024.8.22.1288 - 2024-08-22 17_32_55.log](https://github.com/user-attachments/files/16720513/DESKTOP-3EE2DAL.-.2024.8.22.1288.-.2024-08-22.17_32_55.log)

### Reporters

@gamethecupdog

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius. I suspect this probably happens because the default head avatar already has a RTO applied to it?

**Comment by Frooxius** [comment]
Fixed this in 2024.8.27.55! Thanks for report!
