### ISSUE TITLE
HeadHorizonalBobOffset is bobbing different directions depending on what direction in the world you face.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#2803]
### Describe the issue.

I don't know if this is supposed to be a thing but I changed HeadHorizontalBobOffset to be really intense for this, but the direction HeadHorizontalBobOffset goes seems to be inconsistent depending on what direction you face.

![image](https://github.com/user-attachments/assets/e43a6189-68ab-4994-9ae3-4c73de68c7ab)

https://github.com/user-attachments/assets/1ecf6486-70c4-4344-a35c-b6d8804b1881

### To Reproduce

Try running forward, left and right while messing with the HeadHorizontalBobOffset parameter. You can see that it ends up bobbing different directions depending on your world direction.

### Expected behavior

For the horizonal bob to not bob different directions based off of the world direction.

### Screenshots

Video provided earlier.

### Resonite Version Number

Beta 2024.8.22.1328

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A, probably.

### Reporters

ModernBalloonie

**Comment by Frooxius** [comment]
Fixed this in 2024.8.27.55, thanks!
