### ISSUE TITLE
ForceUseFeetProxies state on VRIKAvatar not respected / Proxy transforms can't be written to

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#2836]
### Describe the issue.

User-made "pose" systems in Resonite make use of the `ForceUseFeetProxies` / `ForceUsePelvisProxy` properties of the VRIKAvatar component to allow the user to grab and manually pose their limbs by adjusting the positions of their pose proxies.

It appears that the procedural animation system currently overrides the position of the feet even when `ForceUseFeetProxies` is enabled, preventing use of these pose systems.

Checking `DoNotSimulate` on the `AvatarObjectSlot` components continues to drive the position of the proxies, and even if the drives are removed, their position is still fixed to the same place, even if the transforms of the proxy are written to directly by the pose system.

### To Reproduce

- Enable `ForceUseFeetProxies` on `VRIKAvatar`
- Observe that the feet do not position themselves at the avatar's proxy positions

### Expected behavior

`ForceUseFeetProxies` should disable simulation automatically when it is enabled. Feet should be posed at the position of the proxies when simulation is turned off for a given body node.

### Screenshots

Current behaviour of pose system on `Beta 2024.8.5.1341`. Enabling `ForceUseFeetProxies` positions feet at the proxies as-expected, and the position / rotation of the proxies can be written to.

https://github.com/user-attachments/assets/ca852255-1a7a-4eda-8e2f-b7c25e3fa743

Behaviour on `Beta 2024.8.29.33` demonstrating that the `ForceUseFeetProxies` checkbox is not respected, and feet are not positioned at the proxy position, even after simulation is diabled, and the drives on the transforms of the proxies are removed.

https://github.com/user-attachments/assets/0299bde4-ce77-4ef4-bbd4-585ab597b4ad

### Resonite Version Number

Beta 2024.8.29.33

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest

### Log Files

`Beta 2024.8.5.1341`
[SHIFTY-LAPTOP - 2024.8.5.1341 - 2024-08-29 17_10_30.log](https://github.com/user-attachments/files/16808599/SHIFTY-LAPTOP.-.2024.8.5.1341.-.2024-08-29.17_10_30.log)

`Beta 2024.8.29.33`
[SHIFTY-LAPTOP - 2024.8.29.33 - 2024-08-29 17_28_42.log](https://github.com/user-attachments/files/16808739/SHIFTY-LAPTOP.-.2024.8.29.33.-.2024-08-29.17_28_42.log)

### Additional Context

Follow-up from a comment made by Veer regarding an issue observed with their pose system on the prerelease branch.

### Reporters

@Veeridian
@shiftyscales

**Comment by Frooxius** [comment]
> It appears that the procedural animation system currently overrides the position of the feet even when `ForceUseFeetProxies` is enabled, preventing use of these pose systems.

I don't fully understand this part. ForceUseFeetProxies means that the proxies should be used when there's nothing driving them. When there's something driving those (such as animation system) it will not do anything.

However it sounds like the main issue is that the poser system just expected the feet to not be moved at all by another system? So it can set its own poses.

The main solution here would be that we just provide a mechanism to suppress the simulated poses.

**Comment by shiftyscales** [comment]
> The main solution here would be that we just provide a mechanism to suppress the simulated poses.

I agree, yes. That was what I thought the "Do Not Simulate" state was for. If it's a mechanism that's not yet implemented, I can test it again after. And yes, at least for the pose system I'm using, it writes the transforms to the proxies / assumes nothing else is controlling / driving them.

**Comment by Frooxius** [comment]
I've added mechanisms to make poses work in 2024.8.30.1213:

- Add Legacy Feature setting to suppress feet simulation (based on report by @shiftyscales, @veercollie, issue #2836)
-- Note this is to make certain features that hijack feet proxies work, like posers work without having to modify them
-- If you turn this on without using posers and similar feature, the animations will NOT look correct. Turn this off after you're done using posers
-- IMPORTANT: This will likely be removed at some point, we recommend upgrading posers to be compatible with the new system and automatically suppress the simulation when active
- Add LocomotionAnimationSupressor
-- Adding this under avatar and checking SuppressFeetSimulation will suppress the feet from being simulated
-- This is useful if you want to take control of the feet proxies, e.g. with a poser system

This should make the old posers work and adds mechanism for them to be updated so user doesn't need to toggle a setting to make them work.

Thanks for report! I'll close this now, if there are issues still, we can reopen this.

**Comment by shiftyscales** [comment]
Tested both the setting as a short-term option and it is immediately compatible with my existing community-made poser, and the `LocomotionAnimationSuppressor` also works as-intended with the system too with no additional tweaks needed to it.

Thanks @Frooxius.
