### ISSUE TITLE
The userspace dash can be visible in session thumbnails?

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#2840]
### Describe the bug?

Someone posted a screenshot on Discord of someone's dash visible in a session thumbnail as it was being closed/opened

Discord message link: https://discord.com/channels/1040316820650991766/1154514017981833249/1279504121489002507

I'm sorry, this issue will be bare-bones and there will be no log file, I wanted to create it just so this can be potentially looked into as it seems like it could be a privacy leak

### To Reproduce

Unknown

### Expected behavior

Dash not visible in session thumbnails

### Screenshots

![dashInThumbnail](https://github.com/user-attachments/assets/a71b18ad-e2aa-4097-9b10-11b871d6e899)

### Resonite Version Number

Beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

I don't have a log file for this

### Additional Context

N/a

### Reporters

Nytra (discord: nytra)

**Comment by Frooxius** [comment]
Normally dashes are private UI and won't render in thumbnails, this shouldn't happen.

Without any additional information we don't know if this is even a bug - they might have pasted a screenshot of dash into the world and that's what you see on the thumbnail. There's a lot of assumptions here. 

Without logs and way to replicate this, there's not much we can really do.

**Comment by TisFoolish** [comment]
It may be that the host has the mod that makes private UI visible to finger photos and cameras with the right tag. The mod may also be doing the same for the world orb camera for the host.

**Comment by Nytra** [comment]
I wonder if the setting to capture private UI in pictures could have caused it?

**Comment by 5H4D0W-X** [comment]
I'm pretty sure this is just a screenshot someone spawned. It's very zoomed in, neither the top nor bottom bars of the dash are visible and if it was actually in the middle of closing, there would be a colored border and particle effects. It also shows the desktop mode dash cursor (no laser visible) implying that the person who took the session thumbnail is in desktop, but then the dash wouldn't be in the world like that

**Comment by charlie-sans** [comment]
> Normally dashes are private UI and won't render in thumbnails, this shouldn't happen.
> 
> Without any additional information we don't know if this is even a bug - they might have pasted a screenshot of dash into the world and that's what you see on the thumbnail. There's a lot of assumptions here.
> 
> Without logs and way to replicate this, there's not much we can really do.

yeah, that's my picture lol. 
me and tumnus was confused as to what session easton was in and so i took a picture of my dash to bring in to the world to show him

**Comment by Nytra** [comment]
Makes sense, closing
