### ISSUE TITLE
Legs move too often while idle in VR

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#2852]
### Describe the issue.

Slightly shifting your position or looking around even slightly will trigger the animation system to take a step much too readily.

This also presents an issue if the user gestures with their head, e.g. nodding their head, shaking their head, tilting their head, or otherwise just moving their head at all will all trigger the animation system to take steps.

### To Reproduce

Be in VR, and look slightly from side to side, or shift your position in your seat slightly to the side.

### Expected behavior

The feet should remain planted if a user in VR has not moved a significant amount.

### Screenshots

Video depicting common user-gestures, e.g. nodding / shaking / tilting their head, moving slightly in their seat, etc.

https://github.com/user-attachments/assets/39da0629-5c7a-4f64-aa58-fff61db1a7f2

### Resonite Version Number

Beta 2024.9.2.1379

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest

### Log Files

N/A

### Additional Context

Follow-up from #2837 splitting it up into separate actionable issues per @Frooxius' request.

### Reporters

@shiftyscales

**Comment by Frooxius** [comment]
This should behave a lot better in 2024.9.16.715!
