### ISSUE TITLE
Client not able to login upon launch, stuck in local home world and Contacts empty

### ISSUE THREAD

**Issue by HarmonicaAlex95** [Yellow-Dog-Man/Resonite-Issues#2853]
### Describe the bug?

The client didn't login upon launch. After I enter my credentials, the contacts page is empty, didn't able to load myself into my default home world. 
I still able to launch myself into my home world with my set avatar. After some time, Active Session tab become empty after awhile as shown below
![20240904092334_1](https://github.com/user-attachments/assets/66577137-167c-45d3-9673-bba683129bad)

### To Reproduce

Start client as usual via "Play in screen mode" in Steam

### Expected behavior

Able to login and successfully loaded in into home world
All of the contacts will show up
All of the Active Session will show normally

### Resonite Version Number

Beta 2024.8.5.1341

### What Platforms does this occur on?

Windows

### What headset if any do you use?

PICO 4 via Virtual Desktop

### Log Files

[DESKTOP-IU9ITDT - 2024.8.5.1341 - 2024-09-04 11_59_06.log](https://github.com/user-attachments/files/16860608/DESKTOP-IU9ITDT.-.2024.8.5.1341.-.2024-09-04.11_59_06.log)

### Additional Context

I didn't test via VR due to I'm still working right now.

### Reporters

IGN: HarmonicaFennecCat / Discord: harmonicafenneccat

**Comment by sveken** [comment]
To add on to this, If its already mentioned ignore me. 
Troubleshooting wise we have checked the time is synced (it is) and done the restart computer step.

**Comment by troyBORG** [comment]
I am also experiencing this issue
![image](https://github.com/user-attachments/assets/d1e021c9-6d7a-4510-ab8e-466b999e5808)
![image](https://github.com/user-attachments/assets/b73113c5-7ef1-4b3d-87b5-0fe435b1cbec)

My log file:
[DESKTOP-H0FLKOJ - 2024.8.5.1341 - 2024-09-04 00_01_46.log](https://github.com/user-attachments/files/16861176/DESKTOP-H0FLKOJ.-.2024.8.5.1341.-.2024-09-04.00_01_46.log)

**Comment by troyBORG** [comment]
Well things seem be working now for me..

I ended up having to tell my router to Release/Renew its WAN IP.  That seemed to fixed it for me.

**Comment by HarmonicaAlex95** [comment]
The issue has been resolved by restarting the router/modem/internet box
