### ISSUE TITLE
Headless build hasn't been updated to Beta 2024.9.4.357

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2854]
### Describe the bug?

With the release of Beta 2024.9.4.357, the headless build hasn't been updated.

Tested completely fresh from Steam

### To Reproduce

Download Headless build from Steam, note the build downloaded is still Beta 2024.8.5.1341

### Expected behavior

Beta 2024.9.4.357 to be downloaded

### Resonite Version Number

Beta 2024.9.4.357

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Headless

### Log Files

No log files generated

### Reporters

bredo

**Comment by sveken** [comment]
Tried fresh containers. Can comfirm.

**Comment by Frooxius** [comment]
Checking.

**Comment by Frooxius** [comment]
I'm not sure what happened. I just reran the publishing script, it seems to be up now.

**Comment by bredo228** [comment]
> I'm not sure what happened. I just reran the publishing script, it seems to be up now.

Looks like that's fixed it. Thanks!

**Comment by Frooxius** [comment]
Thanks for report! Closing!
