### ISSUE TITLE
When Using Feet and Hip Trackers for Full Body, Tracker Visuals remain

### ISSUE THREAD

**Issue by Charizmare** [Yellow-Dog-Man/Resonite-Issues#2856]
### Describe the bug?

While using feet and a hip tracker in version Beta 2024.9.4.357 of Resonite the trackers at your feet will remain. Changing avatars, respawning ,  joining another session or restarting does not fix the issue.

### To Reproduce

1. Start Resonite in version Beta 2024.9.4.357
2. Load up any avatar that has a rig with feet and a hip tracker, the tracker visuals at the feet will still remain.

### Expected behavior

The track visuals should not be visible.

### Screenshots

Video on the bug in action: https://youtu.be/Bf3pwexvYpM

### Resonite Version Number

Beta 2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[DESKTOP-LOEURJJ - 2024.9.4.357 - 2024-09-04 03_31_31.log](https://github.com/user-attachments/files/16862748/DESKTOP-LOEURJJ.-.2024.9.4.357.-.2024-09-04.03_31_31.log)

### Reporters

Charizmare

**Comment by Frooxius** [comment]
Hmm this is a bit odd. I've tested this before release and it didn't occur on my end. I'll have to re-test this, but there might be some extra conditions for this to happen.

**Comment by HamoCorp** [comment]
Same is happening to me when launching the game and after recalibrating there still visable

![2024-09-04 14 03 07](https://github.com/user-attachments/assets/5d3c25e8-5e96-4662-82ac-f6ce6e089690)

**Comment by Frooxius** [comment]
Fixed this in 2024.9.6.626, thanks for report!
