### ISSUE TITLE
Held objects move with head Animation

### ISSUE THREAD

**Issue by HamoCorp** [Yellow-Dog-Man/Resonite-Issues#2858]
### Describe the bug?

In desktop mode when holding an object they will make small movements without moving the mouse

### To Reproduce

spawn an object on desktop, hold it in front of you, stay still don't move, wait for a few seconds it will start doing small movements

https://github.com/user-attachments/assets/a580a3f1-92c0-4fe1-8ac7-088501683c69

### Expected behavior

it seems to be a problem with head movement. since Editing headMaxLookDirectionAngle values stops it

https://github.com/user-attachments/assets/9e20eff3-7b9c-46ec-b519-39c666c66259

### Resonite Version Number

Beta 2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[THE-GERMAN-ROME - 2024.9.4.357 - 2024-09-04 13_06_04.log](https://github.com/user-attachments/files/16870369/THE-GERMAN-ROME.-.2024.9.4.357.-.2024-09-04.13_06_04.log)

### Reporters

HamoCorp

**Comment by shiftyscales** [comment]
Replicated thanks. Assigning @Frooxius.

**Comment by Frooxius** [comment]
Fixed this in 2024.9.6.626, thanks for report!
