### ISSUE TITLE
Feet Position Does Not Change When Entering Anchor

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [Yellow-Dog-Man/Resonite-Issues#2859]
### Describe the bug?

Previously, when entering an Anchor, the feet would change shape as if sitting on a chair. However, currently, the feet do not move and are embedded within the chair.

### To Reproduce

1. Open CloudHome  
2. Enter Anchor  

### Expected behavior

The feet should take the shape set by the Anchor.  

### Screenshots

![2024-09-04 13 50 16](https://github.com/user-attachments/assets/1cb5daf0-a69d-4355-b309-216fc4f0e70c)
![2024-09-04 13 50 40](https://github.com/user-attachments/assets/521dfd80-88da-49f0-a11e-f92c52d98c6f)
![2024-09-04 13 51 06](https://github.com/user-attachments/assets/39078d07-ee59-4363-99b6-28df60c94aa6)

### Resonite Version Number

Beta 2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-P16I6HJ - 2024.9.4.357 - 2024-09-04 22_48_36.log](https://github.com/user-attachments/files/16871604/DESKTOP-P16I6HJ.-.2024.9.4.357.-.2024-09-04.22_48_36.log)

### Reporters

Resonite: yoshi1123_
Discord: yoshi1123_

BlueTera, NeXuS15 and SilvyPaws

Wolf Seisenbacher

**Comment by Frooxius** [comment]
This is fixed in 2024.9.6.626, thanks for reporting!
