### ISSUE TITLE
CurrentOnGround Direct IK bool does not automatically update anymore

### ISSUE THREAD

**Issue by GearBell** [Yellow-Dog-Man/Resonite-Issues#2860]
### Describe the bug?

In the VRIKAvatar component of an avatar, the direct reference of CurrentOnGround bool is not updating anymore when you go off/on ground.

### To Reproduce

Use any avatar and find the bool, you will see it does not respond even when jumping around.

### Expected behavior

CurrentOnGround bool should automatically update when on/off the ground

### Resonite Version Number

Beta 2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

HTC Vive Pro Eye

### Log Files

[DESKTOP-SH9HHOE - 2024.9.4.357 - 2024-09-04 09_20_40.log](https://github.com/user-attachments/files/16873912/DESKTOP-SH9HHOE.-.2024.9.4.357.-.2024-09-04.09_20_40.log)

### Reporters

GearBell

**Comment by shiftyscales** [comment]
What are you using that for, @GearBell? Can you provide examples of content / use-cases where you've used it?

If you need to check if a character is on the ground, I'd recommend using the physics node `IsCharacterOnGround`.

![image](https://github.com/user-attachments/assets/f1665bec-e128-43c1-b0be-c903cab623d4)

**Comment by lxw404** [comment]
This seems to also affect the `IsCharacterOnGround` node in some way I can't replicate fully yet...  I need to do some more testing, but some of my systems that use it for detecting feet collision are now broken.  I'll return with some test cases tomorrow most likely.

**Comment by Frooxius** [comment]
I strongly recommend switching to IsCharacterOnGround node, because that'll be a lot more futureproof. 

I'll tackle this to fix existing systems though.

**Comment by shiftyscales** [comment]
@lxw404 - There was a slight delay added to the locomotion system to account for cases where the character controller momentarily becomes "airborne" when it shouldn't (e.g. a mesh collider with holes). This prevents the animation rapidly cycling between grounded and airborne states.

> Add mechanism to suppress rapid transition between OnGround and InAir state when walking over certain colliders (based on report by @shiftyscales and @veercollie, issue https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2837)

https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/2799#discussioncomment-10525533

The delay is currently ~0.2s for that purpose- I'd recommend you open a separate issue for that if you have broken content however. As far as I know though, the tweak is only applicable to the animation / pose system, so I don't think other content should be affected?

**Comment by Frooxius** [comment]
Should work again in 2024.9.6.626, thanks for reporting!
