### ISSUE TITLE
Foot rotation offset for the animation system

### ISSUE THREAD

**Issue by AegisTheWolf** [Yellow-Dog-Man/Resonite-Issues#2861]
### Is your feature request related to a problem? Please describe.

With the recommendation of creating a new empty object for any avatar that needs this rotation fix for the feet is a confusing ask for new and existing users rather than a setting to rotate the base feet rotation within the animation system natively. 
this will help tremendously when avatars may have feet rotated inward or outward when either existing imported avatars or imported avatars.

### Describe the solution you'd like

Simply a field in the feet metrics component with the offset similar to foot distance or like the knee swivel offset in the current IK system,

### Describe alternatives you've considered

i was recommended the solution to creating an empty object to offset the visual mesh of the model though im concerned with the ammount of avatars that would have this issue that would require a skeleton based update like this.

### Requesters

RueShejn, Aegis_Wolf,

**Comment by shiftyscales** [comment]
Which axis are you wanting to rotate the feet on, @AegisTheWolf? I see under the gaits there is `FootGroundAngle` which will adjust the pitch of the foot while it is in contact with the ground, does that resolve your issue?

If not, having photos of what it looks like / what is wrong could be useful to better understand the issue you are having.

**Comment by AegisTheWolf** [comment]
> Which axis are you wanting to rotate the feet on, @AegisTheWolf? I see under the gaits there is `FootGroundAngle` which will adjust the pitch of the foot while it is in contact with the ground, does that resolve your issue?
> 
> If not, having photos of what it looks like / what is wrong could be useful to better understand the issue you are having.

I forgot to @shiftyscales mention you.

**Comment by shiftyscales** [comment]
Was that issue not occurring before the animation update, @AegisTheWolf? What does the rig look like compared to other avatars that don't have this issue? From an initial reading- this sounds like something that should be fixed on the mesh itself.

Are the feet also incorrectly rotated if you use FBT? If so, does that persist if you reset the avatar's calibration in the avatar calibrator?

**Comment by AegisTheWolf** [comment]
after going through the avatars that have this issue after the update it seems to be users that had FBT or their avatar is having an issue with their bone structure with the feet facing outwards/inwards on import,

To fix this either that solution with the empty parent or re import of the avatar with a proper resting pose. (this narrows down the ammount of avatars that have this issue) i think this GH issue can be closed from this.

If the foot rotation offset could be changed via the IK potentially after import, this sounds like something to bring up once a rework of the IK is in the development cycle down the line.
