### ISSUE TITLE
Anchors are bugged like feet not going where they are supposed to.

### ISSUE THREAD

**Issue by BlueTera** [Yellow-Dog-Man/Resonite-Issues#2862]
### Describe the bug?

Feet not going into the anchor point like they did before the locomotion update.

### To Reproduce

Just go into an anchor i used Ren's easy seat to test.

### Expected behavior

Feet going to where they are supposed to. Like the actual anchor point.

### Screenshots

![2024-09-04 19 23 20](https://github.com/user-attachments/assets/bf7e7add-ed54-49df-b741-703562d6b683)
![2024-09-04 19 23 27](https://github.com/user-attachments/assets/835d0f96-d555-4278-a5d8-8741af0ffcaf)

### Resonite Version Number

2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

n/a

### Reporters

BlueTera, NeXuS15 and SilvyPaws

**Comment by BlueTera** [comment]
The Supress Feet Simulation also does not fix the issue.

**Comment by shiftyscales** [comment]
Thanks for the report, this seems like it's the same underlying issue as #2859, so I'm going to close and merge this issue into that one.
