### ISSUE TITLE
FBT Calibrate breaks when trying to adjust position

### ISSUE THREAD

**Issue by HamoCorp** [Yellow-Dog-Man/Resonite-Issues#2864]
### Describe the bug?

the fbt calibrator body is now moving everywhere when grabbing it. It makes it difficult to adjust the positions. this wasn't happening before the last update

### To Reproduce

I open fbt calibrator and start adjusting it then start moving everywhere

https://github.com/user-attachments/assets/c2d412ae-9231-46e8-a12a-77932fc1ccac

### Expected behavior

to move to where I want it

### Resonite Version Number

Beta 2024.9.4.357

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 3

### Log Files

[THE-GERMAN-ROME - 2024.9.4.357 - 2024-09-04 23_10_59.log](https://github.com/user-attachments/files/16881725/THE-GERMAN-ROME.-.2024.9.4.357.-.2024-09-04.23_10_59.log)

### Reporters

HamoCorp

**Comment by harumaki021** [comment]
I have confirmed that this issue also occurs in my environment. It did not occur in versions prior to Beta 2024.9.4.357. 
w/ Windows, Quest Pro, SlimeVR Trackers

**Comment by shiftyscales** [comment]
Thanks for the report @HamoCorp @harumaki021.

For now, if you need to adjust your avatar's calibration precisely, I'd recommend adjusting the target of the proxies directly to manually calibrate positions as-needed.

This should be something you only need to do once if you save your avatar- particularly if you ensure that your trackers are all placed in as close to the same position and rotation as possible between sessions.

**Comment by Frooxius** [comment]
This is fixed in 2024.9.6.626, thanks for reporting!
