### ISSUE TITLE
LocomotionAnimationColliderBlock is not under the correct category

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#2868]
### Describe the bug?

`LocomotionAnimationColliderBlock` appears to be under `Uncategorized` instead of `Users/Common Avatar System/Animation`

### To Reproduce

Look under `Uncategorized` to find the component.
Look under `Users/Common Avatar System/Animation` to not find the component in the location mentioned in the update post.

### Expected behavior

`LocomotionAnimationColliderBlock` to be found under `Users/Common Avatar System/Animation`

### Screenshots

![bc01c744a0](https://github.com/user-attachments/assets/090ec824-d376-41e2-a3e2-30901b3f7e55)

### Resonite Version Number

Beta 2024.9.4.357

### What Platforms does this occur on?

Windows

### Additional Context

`LocomotionAnimationColliderBlock` appears to extend from `Component` directly where as the other 4 components extend from `LocomotionAnimationParametersBase` which specifies the Category as "Users/Common Avatar System/Animation".

### Reporters

_deltawolf

**Comment by shiftyscales** [comment]
I assume this one was probably just missed / overlooked in categorization. Should be a very simple tweak. Assigning @Frooxius.

**Comment by Frooxius** [comment]
Fixed in 2024.9.6.626, thanks for report!
