### ISSUE TITLE
Toggle to Legacy Locomotion System

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#2878]
### Is your feature request related to a problem? Please describe.

a toggle to switch back to the old Locomotion System as my rex is legit janked up and i don't wanna go thrugh 15+ avatars to add the new systems to be perfect 

### Describe the solution you'd like

a toggle to switch back to the old Locomotion System as my rex is legit janked up and i don't wanna go thrugh 15+ avatars to add the new systems to be perfect 

### Describe alternatives you've considered

none

### Requesters

slythefloof

**Comment by Frooxius** [comment]
This isn't unfortunately something that can be resolved by a simple toggle. The systems got reworked and restructured to enable the new system, which means they can't be easily just toggled between in full - doing so would be a significant undertaking and require us to maintain two separate systems.

I'd recommend just reporting the issues with the new system instead, so we can address those.

**Comment by shiftyscales** [comment]
This is not possible, a lot of the existing system was reworked / stripped out in the process of developing this system, @SlyTheFloof. It would take significant engineering effort to restore the old janky system, and it's not worth the cost.

As indicated in the update notes- we will be improving the default values soon with work done by the community in https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/2799, and additional fixes / functionality should come eventually too.

You only need to apply tweaks now if you do not wish to wait for those tweaks / enhancements to the system to be added as new defaults.
