### ISSUE TITLE
Body tracking going to only one foot and displaying tracker visuals

### ISSUE THREAD

**Issue by Nexulan** [Yellow-Dog-Man/Resonite-Issues#2883]
### Describe the bug?

Body tracking only going to one foot and is showing the visuals that aren't being hidden

### To Reproduce

Set up full body tracking

### Expected behavior

Tracking on the right feet and no visuals for the tracker after calibrated.

### Screenshots

https://github.com/user-attachments/assets/0c5549a6-0440-48a0-a48b-a6358c1101ee

### Resonite Version Number

2024.9.4.357

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-810672E - 2024.9.4.357 - 2024-09-05 20_35_40.log](https://github.com/user-attachments/files/16902592/DESKTOP-810672E.-.2024.9.4.357.-.2024-09-05.20_35_40.log)

**Comment by shiftyscales** [comment]
Can you try again on the latest build `2024.9.6.626` @Nexulan? There were a few FBT fixes in the latest update.
