### ISSUE TITLE
Body calibration kicks out of avatar 

### ISSUE THREAD

**Issue by Nexulan** [Yellow-Dog-Man/Resonite-Issues#2884]
### Describe the bug?

Whenever I try to adjust the body for fullbody it kicks me out of my avatar and cant enter it 

### To Reproduce

Fullbody setup 

### Expected behavior

To be able to adjust the body without it kicking me out of the avatar 

### Screenshots

https://github.com/user-attachments/assets/50c010cd-be4b-4362-91f2-58bcc4a6ad00

### Resonite Version Number

2024.9.4.357

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-810672E - 2024.9.4.357 - 2024-09-05 20_35_40.log](https://github.com/user-attachments/files/16902605/DESKTOP-810672E.-.2024.9.4.357.-.2024-09-05.20_35_40.log)

**Comment by shiftyscales** [comment]
Can you try again on the latest build `2024.9.6.626` @Nexulan? There were a few FBT fixes in the latest update.
