### ISSUE TITLE
Auto-compute avatar metrics for existing avatars

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#2887]
### Is your feature request related to a problem? Please describe.

Currently for the locomotion animation system to look best, avatar's metrics should be calibrated, so the animation matches the avatar as closely as possible. This however requires manual calibration.

### Describe the solution you'd like

For any full body avatars, use the avatar's resting pose & IK to automatically compute the default metrics for that avatar.

### Describe alternatives you've considered

N/A

**Comment by charlie-sans** [comment]
when computing the metrics, is it once forever or once for the session?

**Comment by Frooxius** [comment]
Implemented in 2024.9.10.682!

@charlie-sans It's until you save your avatar with the computed metrics.
