### ISSUE TITLE
Paginated File Explorer

### ISSUE THREAD

**Issue by noblereign** [Yellow-Dog-Man/Resonite-Issues#289]
### Is your feature request related to a problem? Please describe.

the issue of accidentally opening a folder with like 200+ files and then having **the entire file explorer page** become **completely unresponsive until you restart the game**... it's existed since old platform, and still does to this day. it is one of **the most** painful experiences of all time. 😖

### Describe the solution you'd like

limiting the loaded items to say, enough to fill the page, and then having buttons to go forward/back. that would be infinitely better than accidentally giving yourself the CURSE OF RA.

### Describe alternatives you've considered

culling/optimizing the culling of off-screen buttons? _(if it even can be)_
only loading the first x items, sorted by last modification? _(who uses year-old files anyway?)_
kicking the user back to previous folder if processing takes too long?? _(this would probably be terrible UX but still better than a freeze)_
limiting the processing time to x ms, and forcing an update if it takes too long??? _(is this even possible???)_

### Additional Context

the lag scales with the amount of files you have. an easy repro would maybe be to just like fill a folder with a thousand empty text files or something and trying to navigate to it from within Resonite.
this same issue also happens in the Inventory so if you fix it for the File Explorer you could probably fix it there too.
it's just that usually people don't get to the point of a complete freeze in the Inventory because you'd be able to tell that the folder's gettin a little full and you'd make a new one. you don't get that same luxury on your desktop

**Comment by epicEaston197** [comment]
If this modification were to be made it would likely also affect the inventory as well another thing is that the file explorer and inventory are slated to be replaced in the other half of the UI rework but this is still a welcomed ideal for the UI we work

**Comment by epicEaston197** [comment]
If this modification were to be made it would likely also affect the inventory as well another thing is that the file explorer and inventory and other UI are slated to be replaced in the other half of the UI rework 

but this is still a welcomed ideal for the UI rework

**Comment by badhaloninja** [comment]
This would be very nice for both the file browser and the inventory browser. 

It would be especially nice if this was implemented _before_ the UI rework as some of us over time have ended up saving a lot of items and it just hurts to use the inventory because of the lag from the amount of items in certain folders that can't be reasonably moved without inventory management tools

I understand if it wont get added before the UI rework though

**Comment by Frooxius** [comment]
We plan to move away from paginated UI's in favor of this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1363

Closing this, as we won't do this because of the above, which I think is better solution to this problem.
