### ISSUE TITLE
LocomotionAnimationConfguration got reset after latest update.

### ISSUE THREAD

**Issue by BlueTera** [Yellow-Dog-Man/Resonite-Issues#2893]
### Describe the bug?

If you had a LocomotionAnimationConfguration component on your avatar it got reset after the latest update.

### To Reproduce

Not sure if you even can since reproduce it but i hope it will not happen again.

### Expected behavior

Uhh the component not resetting after an update.

### Resonite Version Number

2024.9.6.626

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

n/a

### Additional Context

I really hope this is a bug since it was not stated that it would be reset after the update.
It worked fine yesterday even saving and equipping the avatars again.
And also .resonitepackages also seems to be affected but i'm not 100% sure.

### Reporters

BlueTera, ForgottenSin, paradox

**Comment by paradoxical-autumn** [comment]
According to users on the resonite discord, this affects packages as well.

messages (requires account):
- https://discord.com/channels/1040316820650991766/1154514007479287942/1281692057534205985
- https://discord.com/channels/1040316820650991766/1154514007479287942/1281691459606806640

**Comment by Frooxius** [comment]
Do not resave any of these. I'll push a fix, which will make them load properly.

**Comment by Frooxius** [comment]
Fixed this in 2024.9.6.1185, thanks for report!
