### ISSUE TITLE
No response when submitting tickets from support website

### ISSUE THREAD

**Issue by brecert** [Yellow-Dog-Man/Resonite-Issues#2907]
### Describe the bug?

When submitting tickets there is no response, or confirmation email suggesting the ticket has been received.

### To Reproduce

visit https://support.resonite.com/open.php and attempt to create a new ticket

### Expected behavior

the email used in the creation of the ticket is sent an email confirming the ticket was made

### Resonite Version Number

Beta 2024.9.6.1189

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

A game log is not applicable for this issue.

### Additional Context

After submitting my first ticket with no response I realized I had used my domain email and maybe that had caused issues so I switched to my outlook email, after that I had started to think that maybe no response was policy since there was no indication after submitting the ticket that there would be an email confirming that the ticket was received.

More recently I asked a friend about it and they indicated that there should be a response, I saw that maybe Resonite's email was down the previous times I had submitted a ticket (#2723) so I submitted new tickets and a few weeks later I've still had no response.

It may be a good idea to indicate that there should be an email sent to confirm the ticket was received when submitting a ticket.

### Reporters

brecert

**Comment by stiefeljackal** [comment]
When you submitted your support ticket, did it take you directly to the Resonite web page or to a confirmation page?

**Comment by brecert** [comment]
> When you submitted your support ticket, did it take you directly to the Resonite web page or to a confirmation page?

It took me directly to the resonite web page

**Comment by stiefeljackal** [comment]
> > When you submitted your support ticket, did it take you directly to the Resonite web page or to a confirmation page?
> 
> It took me directly to the resonite web page

The form authentication is expiring too quickly. The expected behavior should take you to a confirmation page with an email sent to you later. However, if the form authentication expires, it just takes you back to the Resonite website. This means that the form does not get submitted to the Resonite team.

I and others have noticed this a few times when submitting issues on the support page.

**Comment by brecert** [comment]
Ah that makes sense, I'll close this issue then.

**Comment by stiefeljackal** [comment]
@brecert Oh no. I would keep this open because the form is expiring too quickly. It should have a longer timeout than what is currently set for it.

**Comment by stiefeljackal** [comment]
There might be other possible issues that are preventing the form from being fully submitted as well. The team should look into the support form issue.

**Comment by shiftyscales** [comment]
Assigning @DanteTucker to look into this.

**Comment by stiefeljackal** [comment]
Thank you @shiftyscales.

**Comment by shiftyscales** [comment]
A few updates- @DanteTucker has since given the system a test, and things seemed to go okay for them.

Prime currently suspects @stiefeljackal's guess about the form expiring after a timeout is the most likely problem, and will look into the available settings / code for osTicket to determine if this is something we can easily tweak.

Re-assigning @ProbablePrime for now.

**Comment by brecert** [comment]
> The form authentication is expiring too quickly. The expected behavior should take you to a confirmation page with an email sent to you later. However, if the form authentication expires, it just takes you back to the Resonite website. This means that the form does not get submitted to the Resonite team.
> 
> I and others (@bontebok) have noticed this a few times when submitting issues on the support page.

I can confirm that submitting the ticket a lot quicker worked worked for me, thank you

**Comment by shiftyscales** [comment]
@ProbablePrime @DanteTucker - We received another support ticket reporting this issue again today. If possible, it would be good to prioritize this as soon as is feasible to ensure this is working as-expected so user reports are not dropped unexpectedly.

**Comment by ProbablePrime** [comment]
I changed, User Session Timeout in our OSTicket settings to 0(disables it), also did the same for the agent side:
![Image](https://github.com/user-attachments/assets/9db7094e-2275-44ba-bc27-166a579f03fd)

I'm juggling a few things at the moment, so could someone please test this for me.

1. Loginto the ticket desk as a non-agent
2. Start writing a ticket
3. Wait awhile
4. Try submit.

Interestingly the default timeout was set to 30 minutes. I'm hoping that lines up with previous reports but let me know what comes up.

**Comment by stiefeljackal** [comment]
@ProbablePrime I have it up. Will have the form up and wait for more than 30 minutes before submitting.

**Comment by ProbablePrime** [comment]
Thank you!

I have another friend also testing. So for the benefits of our moderators. No more testers after this comment, thank you!

**Comment by stiefeljackal** [comment]
Submitted after 30 minutes while on the form; however, it went directly to https://support.resonite.com/index.php. I assume it timed out.

**Comment by ProbablePrime** [comment]
Thanks!

Looks like ill have to rummage in the PHP settings.

**Comment by ProbablePrime** [comment]
I added:
```
define('SESSION_TTL', $sttl);
ini_set('session.cookie_lifetime', $sttl);
ini_set('session.gc_maxlifetime', $sttl);
session_set_cookie_params($sttl);
```

To our OSTicket config, and have set $ttl to 1 day. This should hopefully fix it.

**Comment by stiefeljackal** [comment]
@ProbablePrime Do you need someone to verify?

**Comment by ProbablePrime** [comment]
I have some tabs open to test right now, so no need for testing atm.

**Comment by ProbablePrime** [comment]
I waited for 35 minutes and then submitted a ticket, it went through and i ahve a ticket number.

I think this is resolved!
