### ISSUE TITLE
Log spam: Session updated, forcing status update

### ISSUE THREAD

**Issue by CZakarya** [Yellow-Dog-Man/Resonite-Issues#2909]
### Describe the bug?

I've only played Resonite for a total of 4.5 hours, and my logs folder is 16 megabytes. Along withe errors, there is a ridiculous amount of "Session updated, forcing status update" lines. See attached log.

### To Reproduce

I don't know what is causing this

### Expected behavior

Less log spam I guess

### Resonite Version Number

2024.9.6.1189

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Desktop

### Log Files

[Sinister - 2024.9.6.1189 - 2024-09-09 19_03_46.log](https://github.com/user-attachments/files/16938477/Sinister.-.2024.9.6.1189.-.2024-09-09.19_03_46.log)

### Reporters

Discord: CZakarya
Resonite: Zakarya

**Comment by shiftyscales** [comment]
I've noticed the same thing in log files I've checked recently while triaging issues. @Frooxius had noted that log line occurs when session info is somehow updated for a session the user is in, forcing a SignalR update to be sent.

What is not yet known to me though is the source of what is causing so many session updates to occur so rapidly.

**Comment by CZakarya** [comment]
You'll need a good debugger for that one (I don't know how the code works, that's just a guess)

**Comment by troyBORG** [comment]
Can't we just find whatever is generating the:
`Session updated, forcing status update` and tell it not to send that to the log....


Like I've litterally just logged in, and sitting in my Local home.  and look at how many of them are in my log file already....
[DESKTOP-H0FLKOJ - 2024.9.13.672 - 2024-09-13 23_33_35.log](https://github.com/user-attachments/files/17001019/DESKTOP-H0FLKOJ.-.2024.9.13.672.-.2024-09-13.23_33_35.log)

**Comment by ProbablePrime** [comment]
No, we need to solve the root cause.

We can terminate the logging sure, but that means the status updates are still happening.

**Comment by Frooxius** [comment]
I've just fixed the underlying issue.

And yes, we don't want to remove the logging. The reason it's there is so in case there's way too many updates than there should be, we investigate and fix it. Just removing the logging would defeat the purpose of that.

**Comment by Frooxius** [comment]
This is now out in 2024.10.4.923! Thanks for report!
