### ISSUE TITLE
how is "Is user present" and "is user present in headset" working?

### ISSUE THREAD

**Issue by Ardescar** [Yellow-Dog-Man/Resonite-Issues#291]
### Describe the bug?

When tried using the "is user present" node i did check how the use for it should be and it was described as 

_**## true = User has the current world session focused and is wearing their headset ##**_ 

but currently it seems to be true also when i am in desktop mode.

Then in the same session i found that the node "is user present in headset" is true when i am in desktop. After starting resonite i have to put my headset on (vr hotswitching active) and put it down again for the node to show false.

### To Reproduce

Just check the bool value of the "is user present" 

and starting up resonite - the "is user present in headset" shows true before iam even in vr headset.

### Expected behavior

i would like to know when "is user present" should be true - or if some nodes are redundant.

and id expect that "is user present in headset" to be false when i start up the game in vr but desktop mode.

### Screenshots

User is Present - even tho i am in desktop
![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/63201013/2b2b6bb6-7027-43e8-a12b-cfc0ea51b174)

Is user present in Headset while i am in desktop (first startup without jumping into vr - hotswitching = on)
![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/63201013/8b07a8e1-58d1-452f-9f30-1552ce3fe35d)

### Resonite Version Number

beta 2023.10.18.449

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop and index

### Log Files

[DESKTOP-T7AIKEN - 2023.10.18.449 - 2023-10-18 19_21_57.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13031583/DESKTOP-T7AIKEN.-.2023.10.18.449.-.2023-10-18.19_21_57.log)

### Additional Context

- it is currently a bit confusing to know what of those nodes are giving reliable information.
- It seems to be affected by hotswitching

### Reporters

Ardes // ardescar

**Comment by troyBORG** [comment]
I'll have to look at this on my avatar.  As I have my materials driven so I had to create stuff so when I'm away in the world, or if I take off my headset it will put on my away materials.
If I use the VR hot switching it just goes to desktop and never does away textures so that doesn't break in that case.  But if I turn it off it acts like how it supposed to...
