### ISSUE TITLE
Debug Settings Component creates extra settings that don't go away unless deleted

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#2911]
### Describe the bug?

The DebugSettings component adds a category to your settings menu that can only be removed if it is manually deleted using a user inspector. This probably should be adjusted so that it either doesn't get added at all, or is removed similarly to how Cuteness Settings works for non-glitch users.

### To Reproduce

Create an empty object in a gridspace and attach the DebugSettings component to it.

Observe that you have a new settings category

### Expected behavior

Debug Settings not persisting

### Resonite Version Number

2024.9.6.1185

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

N/A since this is very shrimple to reproduce and I already closed the game for the day

### Additional Context

The main reason this is a problem is because of #2609 but it also feels somewhat unintentional so I felt like reporting it anyway.

### Reporters

Brecert (not in the discord)
Venport (dustysprinkles)

**Comment by ProbablePrime** [comment]
Debug components aren't designed for regular users. They're designed for super users or our team. As such their functionality can be a little confusing or undesirable.

Due to this it is unlikely, we'd prioritize this.

**Comment by Frooxius** [comment]
Anything in the "Debug" category is "Use at your own risk" kind of stuff. 

However since I don't need those anymore, I can just nuke those components, which is quick enough way to resolve this.

**Comment by Frooxius** [comment]
I've nuked the component in 2024.9.11.677, closing this!
