### ISSUE TITLE
Avatar hands will not map to user using Pico 4 controllers

### ISSUE THREAD

**Issue by ScarsTRF** [Yellow-Dog-Man/Resonite-Issues#2916]
### Describe the bug?

I've been in contact with a friend of mine using a Pico 4 headset and controllers and when they finally got into VR, they don't have any control over their hands of their avatar, that being the default, new, or spawned avatars that they would use. From observations it seems that their hands are stuck in the locomotion animation and will not fix if I were to either disable the locomotion animation via the `LocomotionAnimationSuppressor` or even the settings options of disabling the feet locomotion as well.

From more inspecting I did find out that their controllers are showing up on the user root and as well tracking as they would move around in the space as they would move it, both left and right. I did check and compare some components such as the `AvatarPoseNode` and it was not moving to the user, only the avatar movements, though on that component I did see `IsTracking` true, `SourceIsTracking` true, and `SourceIsActive` true possibly meaning that it was seeing the device but not mapping.

This issue alone is causing them more issues down the line with even attempting to interact with their dash as their laser and context menus are stuck to their avatar as well unless they move their controllers a significant distance away from the avatar to trigger the fallback.

### To Reproduce

Load into VR using Steam VR and Pico 4 headset and controllers,
Issue will instantly be apparent.

### Expected behavior

When loading into VR using the Pico 4, All movements and interactions should be normal like using a secondary headset like a Quest 2/3/Pro

The user should then have their avatar mapped properly to their devices such as their controllers and headset

### Screenshots

https://github.com/user-attachments/assets/2de69eb0-7400-4b6d-a371-aa58f6cd894b

### Resonite Version Number

Beta 2024.9.10.682

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Pico 4

### Log Files

[PC - 2024.9.10.682 - 2024-09-11 01_09_03.log](https://github.com/user-attachments/files/16956367/PC.-.2024.9.10.682.-.2024-09-11.01_09_03.log)

### Additional Context

The logs came from the user in question having the issue. I'm reporting on behalf of my observations to help this case.

### Reporters

Resonite: ScarsTRF | Drazion
Discord: scarstrf | axalon

**Comment by shiftyscales** [comment]
Thanks for the report @ScarsTRF, but Pico 4 is not a supported headset / controllers at present. There are a few existing issues about this. #468 / #2221.

In the latter issue it had been found that for some reason SteamVR skeletal input data is not being properly forwarded to Resonite. For now I'd suggest that you / the affected user work with other Pico 4 users to find if there are any existing community bindings that exist to get the controllers working as best they are able.
