### ISSUE TITLE
Make the Display node of type Color/ColorX display color

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#292]
### Is your feature request related to a problem? Please describe.

When pulling out a Display out of anything producing a Color or ColorX type, I expect to see the color. Instead, I get the array of color components.

### Describe the solution you'd like

Make the Display of these two types show color

### Describe alternatives you've considered

Try to guess what the color described by numbers looks like, I guess…

### Additional Context

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/29f096b5-7bf6-455a-88b4-36e3b597609c)

**Comment by Frooxius** [comment]
I'm taking this. It's something that was planned, just never got around to it yet.

**Comment by Frooxius** [comment]
This is now done in 2023.11.8.335, thanks!
