### ISSUE TITLE
Shoulder properties on LocomotionAnimationHandMetrics appear to have no effect

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#2920]
### Describe the bug?

I logged back into Resonite today, noticing my avatars arms were not how I left them.

I opened up my avatar's LocomotionAnimationHandMetrics and tried tweaking the parameters.

Previously I had configured:
1. Shoulder Separation 
2. Arm Length

I changed those parameters again and only saw an effect with Arm Length. 
Changing Shoulder Separation or Shoulder Offset did not have an effect.

Bredo came over and also tweaked theres to no effect.
Bredo went to another world to check it on a fresh world and reported that there was no effect.

I restarted Resonite to gather logs.

### To Reproduce

1. Load into an avatar that has LocomotionAnimationHandMetrics or add it to one that does not have it.
2. Inspect that avatar
3. Tweak the values on LocomotionAnimationHandMetrics
4. Observe no effect

I spawned an avatar I haven't used since before the locomotion animation update, and added LocomotionAnimationHandMetrics to that avatar and the settings also did nothing.

### Expected behaviour

LocomotionAnimationHandMetrics should continue to effect the locomotion animation, with all properties.

### Screenshots

https://www.youtube.com/watch?v=hcCX3tHBIF8 

Initial problem is displayed during first 30 seconds
Video is 2 minutes long as I continue to explore all the possible combinations of values on the component for more data.

### Resonite Version Number

2024.9.10.682

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ALFRED - 2024.9.10.682 - 2024-09-11 01_22_34.log](https://github.com/user-attachments/files/16960554/ALFRED.-.2024.9.10.682.-.2024-09-11.01_22_34.log)

### Additional Context

Swapping between Global and Local space, did occassionally show changes, like the metrics were updating but further value tweaks showed no effect. See the latter parts of above video

### Reporters

ProbablePrime, Bredo

**Comment by Frooxius** [comment]
This is intentional. The latest build introduced a system which computes them live for IK avatars, which overrides the static separation:
![image](https://github.com/user-attachments/assets/f5677127-52aa-434d-a1c2-fffcbc82582f)

Effectively this means that for avatars with VRIKAvatar, the shoulder will be exactly where the shoulders are - it won't get more accurate than that.

**Comment by ProbablePrime** [comment]
Thanks!
