### ISSUE TITLE
Source footstep events directly from user

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#2921]
### Is your feature request related to a problem? Please describe.

The newly added footstep events can currently only be sourced from colliders that are being walked on. For a system I'm building, I need to be able to get all footstep events of the user who's wearing an avatar, since it is a system that will be installed into avatars and should work without any setup in the world.

### Describe the solution you'd like

A way to source all footstep events of a user.

### Describe alternatives you've considered

N/A

### Requesters

Myself

**Comment by Frooxius** [comment]
Added this in 2024.9.12.772, thanks!
