### ISSUE TITLE
[Animation] Sidestepping / Strafing causes legs to unexpectedly judder and shift violently

### ISSUE THREAD

**Issue by Zyro1331** [Yellow-Dog-Man/Resonite-Issues#2922]
### Describe the bug?

When strafing slowly or at regular speed, my avatar will repeatedly nod its head while the feet keeps immediately resetting its placement. My personal avatar has a custom animation config applied to it, but this seems to be replicable with default settings and other avatars too.

Here's my personal avatar exhibiting the behaviour.

https://github.com/user-attachments/assets/cb9a7916-3e5f-4a7a-b383-43d7bc83d247

Now this is a default Full-body Reference avatar, that also has a default animation configuration.

https://github.com/user-attachments/assets/a9b7fbac-345a-4584-a3ac-36cdce154b70

### To Reproduce

- Wear an avatar, preferably a biped avatar with no custom animation configuration or special rigging tweaks (like digitigrade legs)
- Get a mirror from the Essentials folder, and set it to wide.
- Now slowly strafe in front of the mirror, and watch your legs strangely judder all over the place.
-- You may try different speeds, but sprinting may reduce the effect of the juddering as your legs move more rapidly.

### Expected behavior

This was not a behaviour seen in the previous version (Beta 2024.9.10.682) in my testing and configuration of various avatars. 
It seems that the stability of the legs has reduced quite a bit in the latest version.

### Resonite Version Number

Beta 2024.9.11.677

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MANGOVRG - 2024.9.11.677 - 2024-09-11 04_53_37.log](https://github.com/user-attachments/files/16963570/MANGOVRG.-.2024.9.11.677.-.2024-09-11.04_53_37.log)

### Reporters

@zyro1331

**Comment by Frooxius** [comment]
Can you replicate this with the debug visuals enabled?

**Comment by Zyro1331** [comment]
Here's the behaviour with Debug visuals enabled.

https://github.com/user-attachments/assets/85f5d07c-9c38-46f9-9057-165c4b005df9

Here's the same walking but with a SimulationSpeedRatio of 0.1

https://github.com/user-attachments/assets/8941da20-1a4b-4d9b-a51b-ed1a8d8b91a7

**Comment by Zyro1331** [comment]
At 0:16 on the last video, you can see the Debug visuals show three footsteps suddenly register, which might help explain the rapid switching / resetting of the feet when walking sideways

**Comment by Frooxius** [comment]
Thank you! This should now behave much better in 2024.9.12.772!
