### ISSUE TITLE
Adding a preset for avatars with the new locomotion system or having a resonite essentials folder with some presets of good walking annimation overrides 

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#2926]
### Is your feature request related to a problem? Please describe.

Adding a preset for avatars with the new locomotion system or having a resonite essentials folder with some presets of good walking animation overrides 

### Describe the solution you'd like

Adding a preset for avatars with the new locomotion system or having a resonite essentials folder with some presets of good walking annimation overrides 

### Describe alternatives you've considered

N/A

### Requesters

SlyTheFloof

**Comment by Frooxius** [comment]
We're already handling this through this discussion: https://github.com/Yellow-Dog-Man/Resonite-Issues/discussions/2799

Once things have settled enough, we'll swap out the default presets.
