### ISSUE TITLE
DebugLocomotionSimulator Crashes Sessions With People

### ISSUE THREAD

**Issue by AlanMoonbase** [Yellow-Dog-Man/Resonite-Issues#2927]
### Describe the bug?

When the component ``DebugLocomotionSimulator`` is attached to any slot in a session with other players, it crashes the session completely.

### To Reproduce

1. Enter a session with people (or host a session and invite people)
2. Attah the ``DebugLocomotionSimulator`` component to any slot in the world
3. Witness crash.

### Expected behavior

Session not to crash when attaching this component with people.

### Screenshots

None Applicable

### Resonite Version Number

Beta 2024.9.11.677

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[ALAN-VNMBLZR - 2024.9.11.677 - 2024-09-11 18_27_14.log](https://github.com/user-attachments/files/16972106/ALAN-VNMBLZR.-.2024.9.11.677.-.2024-09-11.18_27_14.log)

### Reporters

Moonbase (moonbase__)
Reproduce Subjects - Draconas (draconas_rayne), Orion_Moonclaw

**Comment by Frooxius** [comment]
Fixed this in 2024.9.12.772, thanks for report!
