### ISSUE TITLE
ingame wiki browser

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2929]
### Is your feature request related to a problem? Please describe.

when reading the wiki, most of the time you would have to take your headset off or pull it up to see the monitor just to read what the contents of the wiki is.

### Describe the solution you'd like

a ingame wiki viewer powered by uix if possible or some other form of viewing.

### Describe alternatives you've considered

creating a mod that provides the user with this functionality with the ingame components or just hopping into desktop mode for the duration of research

### Additional Context

it's just an idea at the moment.

### Requesters

charlie_san

**Comment by shiftyscales** [comment]
Thanks for the suggestion, but the needs of this issue would be implicitly covered by #956.

We would not be likely to make an in-game object out of native UI components as it would take a lot of work and overhead maintaining that solution, and doubling work when we could just have additional means for users to easily access the existing wiki pages.

I'd personally recommend use of the desktop tab and your desktop web browser at present- particularly as you can zoom in web pages in your browser to ensure they are legible even in VR.
