### ISSUE TITLE
Make "suppress feet simulation" a permanent setting

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#2930]
### Is your feature request related to a problem? Please describe.

For the feet suppression setting under misc it is noted it will be removed later. I request that it does not get removed due to its utility in easily disabling the IK / animation system for fully body tracking users that want a similar experience to other vr platforms (e.g. vrchat).

For instance, when sitting down with fbt the walking animation can be distracting.

### Describe the solution you'd like

Make the suppress feet simulation setting permanent.

### Describe alternatives you've considered

Adding the component manually to your avatar that achieves the same results, or adjusting the IK manually. 

### Requesters

Stellanora

**Comment by art0007i** [comment]
if u want to disable walking animation you can use the body horizontal angle setting (which is not going away) and set it to 0 to disable animation.

**Comment by Stellanora64** [comment]
@art0007i I know, I did mention editing the IK in the issue. The setting I believe is just more convent for newer users, and can be toggled on or off depending on if they are using fbt or not.

**Comment by Stellanora64** [comment]
@Frooxius That's fair, I did not know there was already a setting for this specifically for fbt. Sorry for the misunderstanding
