### ISSUE TITLE
Avatar Starts Running On its Own

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#2932]
### Describe the bug?

As of the current version `Beta 2024.9.12.772`, a specific avatar (and I suspect others like it) start to run/fly entirely on their own as if possessed.

### To Reproduce

Here is a reproduction avatar:
`resrec:///U-LuxKitty/R-6C6055597D0B6D2AABFF82B15789843CF1EF0888A85D3B78453695C4B035C56B`

Equip it, and go into any physical locomotion without pressing any keys/inputs.

### Expected behavior

The avatar should not be moving when there is no input.

### Screenshots

https://github.com/user-attachments/assets/418f717b-7a57-4196-80a6-b41136e2387b

https://github.com/user-attachments/assets/1ec41ad9-24b3-4e6e-93c7-35de58980338

You'll notice that there is zero keyboard/controller input of any kind during both of these.

### Resonite Version Number

Beta 2024.9.12.772

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[Spontaneous Avatar Running - 2024.9.12.772 - 2024-09-12 12_50_06.log](https://github.com/user-attachments/files/16983188/Spontaneous.Avatar.Running.-.2024.9.12.772.-.2024-09-12.12_50_06.log)

### Reporters

LuxKitty

**Comment by shiftyscales** [comment]
What are the qualities you consider for "others like it" @lxw404? Do you have any idea what is different about that avatar compared to others if other avatars are not having that issue?

Is there a character collider attached to the avatar anywhere? I wouldn't know how or why it would move on its own otherwise. Does it also happen in other physical locomotions like fly?

**Comment by shiftyscales** [comment]
It has a character collider on it, @lxw404. Walking into the side of it without even having it equipped and it blocks my avatar's movement.

You should source down the location of the character collider and remove it.

**Comment by shiftyscales** [comment]
Looks like somehow all of the armature colliders were flagged as CharacterColliders.

**Comment by lxw404** [comment]
That would make sense, but I don't ever remember it having character colliders on it previously, nor did it move like this.  Very strange.
