### ISSUE TITLE
UIX: Component+Protoflux to support scrolling lists with recycled elements

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#294]
### Is your feature request related to a problem? Please describe.

Creating long lists of UI is inefficient - so much that "inspecting root" became synonymous with freezing the engine for a few seconds. (long list of component UI)

### Describe the solution you'd like

There already exists solutions outside of Resonite:
-only generate the UI for visible elements
-insert new elements before reaching the edge of generated UI
-remove invisible elements and reuse them later (filled with new content)

I propose a component that detects when a ScrollRect reaches the bottom or top end and triggers callbacks that are supposed to generate new UI.
A Protoflux node should allow customizing the behaviour from within Resonite. (triggers impulses when requesting new top/bottom elements or when offering to remove a single element)
The scroll position of the ScrollRect must be adjusted after adding the new UI to avoid the elements shifting in position.
The generation of UI should be triggered early enough to allow rapid scrolling. Otherwise scrolling is forced to stop at the edge of generated UI.

I have an example object that was migrated into Resonite:
resrec:///U-TheAutopilot/R-9d94e6c0-6931-44a4-bab0-efdfb2bc6c3b
It observes the scroll position of the ScrollRect and calculates UIX positions/sizes to determine when to trigger UI generation. It also recomputes the scroll position when adding/removing UI elements.
Another feature demonstrated is the possibility to have two different sets of list elements. (here: prime/non-prime)

### Describe alternatives you've considered

Pagination buttons are an alternative but make the interaction more verbose for the user.
Instead of a new component the feature may also be implemented by extending the functionalities of the ScrollRect component.

### Additional Context

Here is the example object in action:
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8538547/58688ba5-cd2f-4a8c-aca4-8d2f7a4feeb7

The red/green spheres symbolize UI elements. The left column is a store of unused UI elements.

#289 could be solved by lazy loading the UI with such a system.

**Comment by Banane9** [comment]
> However, this"on demand" generating of UI would make it difficult to determine the height of the entire list if the items have varying sizes, which could make implementing scroll bars (#157) quite a bit more tricky.

I think this is usually solved by having some sort of function that calculates what the total height would be based on the different types of children.

Although I'd gladly accept a slightly wonky scrollbar over giant lag and no scrollbar.

**Comment by Frooxius** [comment]
Closing this one in favor of the official issue here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1363

I believe that would address this!
