### ISSUE TITLE
Resonite doesn't switch SteamLink Hand Tracked & Controllers properly & Crashes

### ISSUE THREAD

**Issue by SilvyPaws** [Yellow-Dog-Man/Resonite-Issues#2945]
### Describe the bug?

When switching between hand tracking & controller tracking, Resonite will switch to hand tracking properly but refuses to switch back to controllers. When switching back to hand tracking, Resonite doesn't switch back at all and requires a game restart.

### To Reproduce

1. Connect to SteamLink (This requires SteamLink Beta 2.0.11 to be installed on your headset for SteamVR to receive hand tracked OSC data)
2.  Launch Resonite.
3. Switch between Hand tracking & controller tracking

### Expected behavior

For Resonite to be able to switch between hand tracking and controller tracking without any Issues

### Resonite Version Number

Beta 2024.9.12.772

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[SILVYPAWSPC - 2024.9.12.772 - 2024-09-12 22_15_13.log](https://github.com/user-attachments/files/16987673/SILVYPAWSPC.-.2024.9.12.772.-.2024-09-12.22_15_13.log)

### Reporters

SilvyPaws

**Comment by ko-tengu** [comment]
This is related to both #927 and #2041

**Comment by Frooxius** [comment]
I've fixed the switching not working properly in 2024.10.23.15!

The crashing is actually a separate issue from this, which seems to be coming from Unity. I'll close this one, since we have issue for the crashing specifically here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3066

Thanks for reporting!
