### ISSUE TITLE
Can't connect to headless session

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#2949]
### Describe the bug?

Since I just updated my client (and headless server) to Beta 2024.9.13.672, I cannot connect to my headless anymore.

### To Reproduce

Try to connect to headless

### Expected behavior

Successful connection

### Resonite Version Number

Beta 2024.9.13.672

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[J4-C - 2024.9.13.672 - 2024-09-13 13_40_35.log](https://github.com/user-attachments/files/16993330/J4-C.-.2024.9.13.672.-.2024-09-13.13_40_35.log)

**Comment by Frooxius** [comment]
Do you have log from the headless too?

**Comment by JackTheFoxOtter** [comment]
No, but I can get one, I think. One moment.

**Comment by Frooxius** [comment]
Looks like it might be an LNL bridge issue:
`13:43:23.607 (120 FPS)	No LNL Bridge nodes available, NAT Punchthrough for lnl-nat://6a95325a-dbe2-4397-afda-f735285b5000/S-U-Jackless:Cloudscape will fail.`

@ProbablePrime Are you doing stuff with them now?

**Comment by ProbablePrime** [comment]
This was me yeah.

The ID for the new one was in uppercase, I'm lowercasing them right now.

**Comment by JackTheFoxOtter** [comment]
I fixed my headless logs not outputting to a file, wanted to reproduce it, but it connected now °^°

**Comment by ProbablePrime** [comment]
Yup, I fixed it on my end.

**Comment by ProbablePrime** [comment]
Yup, they're all now lowercase yay

https://api.resonite.com/networkNodes

Thank you for the report!
