### ISSUE TITLE
Supporter badge issues

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#2951]
### Describe the Underlying Issue

The new supporter badge has some issues:
- It's not scaled properly, it's bigger than the other badges
- It casts a shadow

### Expected Behavior

It should be sized like the other badges and not cast a shadow.

### Screenshots / Video

![image](https://github.com/user-attachments/assets/c0807ea4-48d0-491d-ba12-88c37e128cc5)

**Comment by epicEaston197** [comment]
It looks much better once it scale the mesh down to `0.5`
![image](https://github.com/user-attachments/assets/f95a5b29-921b-49ab-9135-adfc89065634)
![image](https://github.com/user-attachments/assets/05935106-a1b9-4e53-9537-9624bc8761b3)

**Comment by ProbablePrime** [comment]
Clearing assignees down to @RyuviTheViali who's the responsible person here for this feature.

**Comment by RyuviTheViali** [comment]
I've fixed the scale of the supporter badge - turns out it was saved at an incorrect (non-1;1;1) scale.
Closing, thanks!
