### ISSUE TITLE
RelayName UserNetworkStatistic does not show the relay you are on

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#2958]
### Describe the bug?

When using the RelayName UserNetworkStatistic, the relay being used is not shown.

### To Reproduce

Join a session using a LNL Relay

Attempt to get the name of the relay you are on using the RelayName UserNetworkStatistic, observe that it returns null.

### Expected behavior

The relay that is being used to be shown

### Screenshots

![2024-09-15_15-49-57_Resonite](https://github.com/user-attachments/assets/eb58c4fe-2d48-487a-aa3a-8cc9e21c1ee3)

### Resonite Version Number

Beta 2024.9.13.672

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ERIS - 2024.9.13.672 - 2024-09-15 15_47_49.log](https://github.com/user-attachments/files/17004527/ERIS.-.2024.9.13.672.-.2024-09-15.15_47_49.log)

### Reporters

bredo, Zyro

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius as a follow-up to #2751.

**Comment by Frooxius** [comment]
Fixed in 2024.10.23.15, thanks!
