### ISSUE TITLE
Supporter badge is a 3D model

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#2959]
### Describe the Underlying Issue

The supporter badge is a 3D model instead of a 2D plane texture like the other badges

### To Reproduce

Inspect the supporter badge you'll notice it is a 3D model

### Expected Behavior

It should be a 2D icon like the rest of the badges

### Screenshots / Video

![image](https://github.com/user-attachments/assets/06a9049b-5c78-47ec-9b39-55476b02a2f0)

### Additional Context

I did a test to see if I could do a similar look but with a 2D plane Using the white supporter badge from the essentials folder along with the normal map I was able to make this
![image](https://github.com/user-attachments/assets/a9a880c1-e3e9-48dd-a51a-f16b3c7735ba)
(This isn't dual sided due to PBS dual sided metallic not supporting cut out Not as if that matters because Nameplates face towards users)

### Reporters

@epicEaston197

**Comment by JackTheFoxOtter** [comment]
I mean... what's the issue with this being a mesh? If it's supposed to be shiny it has to be, I don't think there's a mechanism for 2D badges to have custom materials. The 2D badges are also meshes, quad meshes, on which a texture is rendered.

**Comment by epicEaston197** [comment]
> I don't think there's a mechanism for 2D badges to have custom materials.

Okay this might be more of an issue for engineering
It would be nice if 2D badges could have custom materials

**Comment by JackTheFoxOtter** [comment]
Huh? But... there is already a solution to this problem. 3D badges.

I'm asking again, why is this a problem to you?

**Comment by epicEaston197** [comment]
> I'm asking again, why is this a problem to you?

I don't know it's just a little strange
The mesh is so thin that you can't really see that it's a 3D model most people think it's a 2D badge

It's fine if it stays 3D

**Comment by kulzae** [comment]
> I mean... what's the issue with this being a mesh? If it's supposed to be shiny it has to be, I don't think there's a mechanism for 2D badges to have custom materials. The 2D badges are also meshes, quad meshes, on which a texture is rendered.

It's completely inconsistent with the rest of the badges to the point it looks weird and somewhat distracting

**Comment by ultrawidegamer** [comment]
The 3D model isn't a huge issue for me, but what is a major concern is that it's the only badge that drastically changes in lighting.

![2024-09-15 18 02 20](https://github.com/user-attachments/assets/b8e48263-7df0-4bf1-a52e-b65dbd3f3b14)
![2024-09-15 18 00 52](https://github.com/user-attachments/assets/e4c3df74-0a81-4bca-a966-b07340e5db41)

and it also looks drastically different than what shows in the session tab

![2024-09-15 18 13 24](https://github.com/user-attachments/assets/51b24e76-5c86-4b95-a4cd-a83db9c2457a)

**Comment by EuphieEuphoria** [comment]
I agree with @ultrawidegamer, the first thing I noticed about the badge was its reaction to lighting, a feature that no other official badges have currently. It is a little jarring and gives the badge an almost brown color in many lighting situations. I would personally prefer if it was unlit like other official badges.

**Comment by ItsAlphaNeon** [comment]
Just want to leave my opinion, for consistency with other system badges, I think it should match the 2D yellow badge displayed in the sessions users tab. I think its a cool idea, but it feels out of place compared to the other official system badges.

**Comment by shiftyscales** [comment]
As had been noted already, it's a 3D badge by necessity as it makes use of custom materials. For feedback about the choice of material there are other existing issues like #2954.
