### ISSUE TITLE
Avatar animations break since new update 

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#2972]
### Describe the bug?

Since the recent update, my legs seem to randomly break after a while, with my feet freezing in place. It seems the culprit is an exception getting thrown.

### To Reproduce

Run around for a while. (I was playing in VR)

### Expected behavior

Animations don't break

### Resonite Version Number

Beta 2024.9.16.715

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[J4-C - 2024.9.16.715 - 2024-09-16 19_02_17.log](https://github.com/user-attachments/files/17016932/J4-C.-.2024.9.16.715.-.2024-09-16.19_02_17.log)

**Comment by Frooxius** [comment]
Hmm... it seems something corrupts the state of the animation system by producing a NaN, but it's not clear what.

Do you (or anyone else) happen to notice if this happens while being stationary or when moving around?

**Comment by Frooxius** [comment]
Also do you have custom animation tuning on the avatar? If so, can you check what the "Standing still" values are on it?

**Comment by JackTheFoxOtter** [comment]
> Also do you have custom animation tuning on the avatar? If so, can you check what the "Standing still" values are on it?

This happened with the "standing still" values all set to 0 because I haven't tuned them yet since they were added. I was running around for a bit, and they only broke when I stood still for a moment.

**Comment by Frooxius** [comment]
@JackTheFoxOtter Can you give me a screenshot? The values shouldn't all be 0.

If they're all 0, it's probably because the system didn't upgrade them. Which might be the culprit here.

**Comment by JackTheFoxOtter** [comment]
This is the locomotion animation configuration on the avatar I was wearing when it broke:
![image](https://github.com/user-attachments/assets/4a559693-5b73-4e83-a634-4c2c577d1993)

**Comment by JackTheFoxOtter** [comment]
Like, the avatar had the component before those were added, so I assumed they would just be 0 until you modify them for older avatars.

**Comment by JackTheFoxOtter** [comment]
I also can't seem to reproduce it in desktop mode, it so far only happened in VR, but it happened 4 or 5 times in a short time, so pretty frequently.

**Comment by Frooxius** [comment]
Should be fixed in 2024.9.16.1105! Thanks!
