### ISSUE TITLE
Pasted Videos Autoplay and Start 30 Seconds In

### ISSUE THREAD

**Issue by Enverex** [Yellow-Dog-Man/Resonite-Issues#298]
### Describe the bug?

As per the title, if you paste in a YouTube video URL now (and select Video from the import window) not only will it auto-play, it starts 30 seconds in.

### To Reproduce

Grab a YouTube video URL (e.g. https://www.youtube.com/watch?v=mXCx50yaseA) and paste into a world. Select Video on the import dialogue. The video will appear, but it'll be (roughly) 30 seconds in and will auto-play.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/958670/ce2aa147-fcc2-49e0-ba4f-eb4c645481da)

Doesn't seem to matter what the length of the video is.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/958670/5b5177d1-775d-467e-b290-e2b03117f6e7)

### Expected behavior

For the video to spawn in at 0:00 and be paused/stopped.

### Resonite Version Number

2023.10.18.449

### What Platforms does this occur on?

Windows

### Log Files

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13034440/Player.log)

### Reporters

Also reported by Ardes in Discord.

**Comment by RyuviTheViali** [comment]
This issue has been fixed - videos should now only start when you choose to start them, and they start at the beginning. Thanks!
