### ISSUE TITLE
"Copy Image" Button No Longer Works

### ISSUE THREAD

**Issue by AlanMoonbase** [Yellow-Dog-Man/Resonite-Issues#2981]
### Describe the bug?

Ever since the latest update, the "Copy Image" context menu button you get when holding an image in game no longer functions.

### To Reproduce

1. Spawn out an image
2. Try to copy it using the context menu
3. Paste it somewhere only for it to paste in the previous thing in your clipboard or nothing at all

### Expected behavior

The image to be copied

### Resonite Version Number

Beta 2024.9.16.1105

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[ALAN-VNMBLZR - 2024.9.16.1105 - 2024-09-18 12_38_26.log](https://github.com/user-attachments/files/17049476/ALAN-VNMBLZR.-.2024.9.16.1105.-.2024-09-18.12_38_26.log)

### Reporters

Moonbase (moonbase__)

**Comment by ModernBalloonie** [comment]
Yup. can confirm.

**Comment by Frooxius** [comment]
Hmm I just tried this, but I can't replicate it, it works normally. Is it still an issue for you on the latest build?

**Comment by AlanMoonbase** [comment]
Beta 2024.9.30.1216, suddenly working, closing
