### ISSUE TITLE
Increased rates of email delivery issues

### ISSUE THREAD

**Issue by DanteTucker** [Yellow-Dog-Man/Resonite-Issues#2987]
### Describe the bug?

There has been a  noticeable increase in the rate of user complaints around emails not being delivered.

I have a suspicion. Back when Azure was having issues during the crowdstrike thing we switched our primary email service from Azure to Sendgrid.

We had previously had a lot of issues with sendgrid. And these new issues appear to line up in time with the switch.

### To Reproduce

N/A

### Expected behavior

Email verification, password reset and other emails should be reliably delivered.

### Resonite Version Number

2024.9.16.1105

### What Platforms does this occur on?

Windows, Linux

### Log Files

N/A

### Additional Context

It would be a good idea to attempt using Azure again as it’s issues were just temporary.

**Comment by shiftyscales** [comment]
Seeking input from @ProbablePrime.

**Comment by ProbablePrime** [comment]
I mostly handle non-skyfrost emails.

I know that I theoretically have access to update this now skyfrost wise but I am not confident. Redirecting to @Frooxius

**Comment by shiftyscales** [comment]
@Frooxius had indicated in today's team meeting that there was an issue previously with Azure's email service- if that particular issue has been resolved- it should be fairly easy for us to switch back to it.

**Comment by Frooxius** [comment]
I just checked, Azure has fixed the email issues with their service. I'll flip it back to use that one as main.

**Comment by Frooxius** [comment]
I've switched it back! Closing this, thanks!
