### ISSUE TITLE
headless crashes with discordsdk bug

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#2988]
### Describe the bug?

i'm trying to use my headless server on my machine through the graphical client and it's not allowing me to join for more than 5 secconds before discord sdk does something and crashes the headless

### To Reproduce

download the steam client, put in the headless code into the steam branch. 
switch to the headless branch and run the headless through the EXE or dll.
join the headless and watch as it gives you `Process terminated. A callback was made on a garbage collected delegate of type 'DiscordGameSDKWrapper!DiscordGameSDKWrapper.ActivityManager+FFIMethods+UpdateActivityCallback::Invoke'.`

### Expected behavior

the headless not crashing when i want to do anything with it.

### Resonite Version Number

Beta 2024.9.16.1105

### What Platforms does this occur on?

Windows

### Log Files

[CHARLIE - 2024.9.16.1105 - 2024-09-20 20_44_26.log](https://github.com/user-attachments/files/17075932/CHARLIE.-.2024.9.16.1105.-.2024-09-20.20_44_26.log)

### Reporters

charlie_san

**Comment by shiftyscales** [comment]
This issue should have been resolved in #2554 - going to close this issue as a duplicate and re-open that one @charlie-sans. Thanks for the report.
