### ISSUE TITLE
SlerpWithMagnitude

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#3009]
### Is your feature request related to a problem? Please describe.

Animating objects along a circular path without rotating them can be useful. (e.g. for conveyor systems or icons moving on a circular indicator)
Unfortunately `Slerp` is only defined for unit vectors.

### Describe the solution you'd like

An extension of Slerp that handles magnitude could be used to handle such movements.

### Describe alternatives you've considered

Manual computation can be applied but is much more complex to setup than a simple "move from A to B along a circle".

**Comment by Banane9** [comment]
Can't you just multiply the output of Slerp with the desired radius? Because it's a unit vector, that should put it exactly on that radius 🤔

**Comment by Frooxius** [comment]
You can do this manually, but this is actually something I have added internally recently into codebase, so we can just expose it to ProtoFlux.

It essentially splits the thing into two - interpolates the directions and magnitudes and then combines them back together.

**Comment by Frooxius** [comment]
I've added this in 2024.10.8.1349!
