### ISSUE TITLE
2D Slerp (possibly with magnitude)

### ISSUE THREAD

**Issue by mpmxyz** [Yellow-Dog-Man/Resonite-Issues#3010]
### Is your feature request related to a problem? Please describe.

The 2D variant of Slerp does not exist:
![grafik](https://github.com/user-attachments/assets/a2575855-ecc6-4d52-b6f9-d1749abca5f7)
Such values could be used to position indicators in UIX aligned around a circular indicator.

### Describe the solution you'd like

`Slerp_Float2` and `Slerp_Double2` as well as their `MultiSlerp` variants could be used here.

### Describe alternatives you've considered

Manual math is also possible as is the use of splines with enough anchor points,

### Additional Context

#3009 would also apply here.

**Comment by Frooxius** [comment]
What exactly do you expect the 2D Slerp to do?

Slerp is Spherical Interpolation, so the movement will follow surface of a sphere. My interpretation is that a 2D version would be "circular interpolation", so the movement of the vector will follow a circle (assuming input and output magnitude are the same).

Is that what you expect?

**Comment by mpmxyz** [comment]
That is correct.
You could already get the same result when appending Z=0 and discarding the extra dimension after `Slerp_Float3`.

**Comment by Frooxius** [comment]
Added in 2024.10.23.15!

Turns out we had them implemented internally the whole time, just not exposed to ProtoFlux >///>
