### ISSUE TITLE
New Component: Dictionary-style Multiplexer

### ISSUE THREAD

**Issue by Lixquid** [Yellow-Dog-Man/Resonite-Issues#3014]
### Is your feature request related to a problem? Please describe.

There is currently no generic way to index a dictionary-style (unordered keys to values) collection of items in a central, easy to manage place, making it difficult to implement sets or lookup tables.

Some example use cases I've run into:

- An easy to manage set of slots to ignore from a serialization process
- A lookup table from strings to integer bytecodes for a simple virtual machine
- A lookup of certain held objects to color values for changing lighting

### Describe the solution you'd like

A new component similar to `ValueMultiplexer<T>` such as `DictionaryMultiplexer<TKey, TValue>` that contains a list of keypairs, a key field, and a target value field.

### Describe alternatives you've considered

You can create a large number of ProtoFlux references and a First Index Of node to search for the key, then another multiplexer to get the value from a list that must be kept in sync with the keys; this requires unpacking / repacking to edit, needs manual effort to keep in sync, and is generally a pain to manage.

If you're just indexing by string (or something with a stable string representation), you can use a dynamic variable space, but this doesn't extend to types that don't have a stable string representation like references.

For slots you can set their tag and index based on that, but this doesn't extend if you need to use the tag for other purposes.

### Additional Context

This does not include a request for anything to programmatically edit the list of keypairs collection style (beyond the existing mechanisms that allow sourcing / driving individually indexed elements of a list).

### Requesters

Lixquid

**Comment by ProbablePrime** [comment]
Thanks for your issue, the functionality described is unfortunately covered by: #572 

While a dictionary/map/table structure might not at first seem to be a "collection", it can more easily be viewed as one when you think about it in terms of "N".

A dictionary contains n items with n keys and n values, means its a collection.

Due to this I will unfortunately, be closing this as a duplicate.

**Comment by Banane9** [comment]
They're not asking for protoflux support though, just a component similar to the existing Multiplexer one that supports other types of indices, essentially.

**Comment by Lixquid** [comment]
Hey, thanks for taking the time out to look at the request; just wanted to clarify since I don't think this is a duplicate of the issue mentioned.

While I know Dictionaries themselves are collections (fundamentally abstracted out to being lists of keypairs as you said), this is a request for a very specific subset of the behaviour that's directly analogous to the existing `ValueMultiplexer` component (not protoflux node); data, an indexing value, and a field to write the result. It should be completely orthogonal to protoflux considerations.

No manipulation of the list, no extra protoflux nodes or logic (beyond the already existing mechanisms that exist for every component's fields).

If the consideration is that we'd prefer to implement no new components or protoflux nodes at all related to collections until the Collections support is implemented, then that's perfectly fine; I'd just like to ensure there's no ambiguity in the request.

Thanks :)

**Comment by Banane9** [comment]
Yea, issue #572 only concerns protoflux and thus shouldn't make a duplicate out of a request for a component

**Comment by ProbablePrime** [comment]
Hmm, I see. We don't have a GH issue for Generic Collections, or collections within the inspector in general, but that would be the issue this is covered by. I was roping that into #572 .

If we re-open this and re-name it to generic collection support for component inspectors that might enable it to remain open.

**Comment by stiefeljackal** [comment]
> If we re-open this and re-name it to generic collection support for component inspectors that might enable it to remain open.

I almost agree. There is slight generic collection support already within components since a `ValueMultiplexer<T>` and a `ReferenceMultiplexer<T>` are effectively a List. Should retrieving the list size and performing list-specific operations be left to ProtoFlux, then you effectively have a generic list component support already. A HashMap would be different since you have a key and a value pair, two generics, where you fetch the value based on the key, something currently not available as a component.

If you plan to add support for other generic data structure components such as Linked List, Sets, Stacks, Queues, Tables, Trees, and Graphs, then generic collection support is the way to go.

**Comment by Lixquid** [comment]
I believe the understanding is that pretty much anything relating to collection support will be aimed to be implemented in one solid chunk, which is completely fine.

I was under the impression that #572 was specific to ProtoFlux only, but if it's also meant to include all the other associated capabilities such as collections components and new field types / UI work, we can keep this closed as a duplicate, then later when the Collections work is complete and the capability still isn't available or is too awkward, re-opened or recreated.

**Comment by stiefeljackal** [comment]
> I was under the impression that https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/572 was specific to ProtoFlux only, but if it's also meant to include all the other associated capabilities such as collections components and new field types / UI work, we can keep this closed as a duplicate, then later when the Collections work is complete and the capability still isn't available or is too awkward, re-opened or recreated.

If this is the case, then #572 should be updated to include the component aspect as well. That way, it is clear that collection support will span across both ProtoFlux and components.
