### ISSUE TITLE
External Account Deletion Tool

### ISSUE THREAD

**Issue by Canadian-Git** [Yellow-Dog-Man/Resonite-Issues#3018]
### Is your feature request related to a problem? Please describe.

To meet GDPR requirements, provide users with an avenue to delete their account if they would like to, without requiring access to the platform, preventing issues with account restrictions or other difficulties accessing the platform.

### Describe the solution you'd like

An external tool to allow users to delete their accounts if they wish.

### Describe alternatives you've considered

Currently, there is an on-platform command that allows this functionality, but this functionality could be extended to a tool outside the platform.

**Comment by shiftyscales** [comment]
Functionally- this has some overlap with #2892 - both requesting an external method to access account commands that are currently only possible by being signed in to the full client.

**Comment by Frooxius** [comment]
The intent here is actually a bit different. This will allow users to request their accounts being deleted when when the account is banned, even in instances where they cannot run any more commands.

The goal is to also make it a pretty simple process, you just enter your credentials, confirm you want to delete and that'll trigger the process.

**Comment by Frooxius** [comment]
Added this in 2024.9.30.1215!
