### ISSUE TITLE
importing a screenshot triggers a screenshot

### ISSUE THREAD

**Issue by jligeza** [Yellow-Dog-Man/Resonite-Issues#3019]
### Describe the bug?

When I import a screenshot, which is placed in `C:\Users\YourUser\Pictures\Resonite`, a duplicate screenshot is taken, the same that was imported. This is after selecting "import image" -> "screenshot (created here)".

I actually don't know what is the difference between "image / texture" and "screenshot", but since I import screenshots, I always use the latter.

### To Reproduce

- Go to dash
- files
- navigate to `C:\Users\YourUser\Pictures\Resonite`
- double press a screenshot
- select option "screenshot (created here)"
- a screenshot is imported and taken at the same time

### Expected behavior

A screenshot is imported, and nothing else happens.

### Screenshots

![2024-09-26 20 43 17](https://github.com/user-attachments/assets/9ba7ddbd-cc05-41a4-ae2f-6799c7d3c6b8)

### Resonite Version Number

2024.9.16.1105

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive

### Log Files

-

**Comment by Frooxius** [comment]
This is intentional behavior.

The screenshot option essentially treats the imported image as if it was image that you just captured in the world itself, and will trigger all the same things as normal screenshot would.

If you don't want that to happen, pick "Image / Texture" instead.
