### ISSUE TITLE
Strange Internal Error When Typing "type" Into The Wiki Search Bar

### ISSUE THREAD

**Issue by AmasterAmaster** [Yellow-Dog-Man/Resonite-Issues#3020]
### Describe the bug?

When i type "type" into the search bar in the search page on the Resonite Wiki, when the everything tab is selected, an internal error happens. (The search link: https://wiki.resonite.com/index.php?search=type&title=Special%3ASearch&profile=all&fulltext=1)

I am using both Firefox (130.0.1 (64-bit)) and Chrome (Version 129.0.6668.71 (Official Build) (64-bit)) and this happens on both browsers.

The conversation started here: https://discord.com/channels/1040316820650991766/1154514026177507438/1289511679310168125

I am unsure how this happened, but it seems I am the only one effected by this so far. Other people seem to search just fine.

### To Reproduce

* Go to the Resonite Wiki
* Go to the search page
* Make sure "Everything" is selected
* Type "type" into the search bar and search it.

### Expected behavior

It should pull up results for the query "type".

### Screenshots

![Resonite Internal Error_Type](https://github.com/user-attachments/assets/4d266e09-057a-460f-9bfb-2b168e46bfbf)

### Resonite Version Number

N/A

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

N/A

### Additional Context

This may be a cache issue.

### Reporters

* AmasterAmaster

**Comment by SincerelyAConcernedCitizen** [comment]
I've seen this before, I think, it looks familiar. 
This maintenance routine might fix it:
https://phabricator.wikimedia.org/T315737#8187139
"The failure has happen when building the search result. There must be a invalid title on the wiki which is part of the search result for that word.
Try to run cleanupTitles.php (first with --dry-run) to find that bad title. Or namespaceDupes.php if the namespace config was changed in the past.
It could be possible there is a page_id in revision, which is no longer part of the wiki (broken delete etc.), not sure if deleteOrphanedRevisions.php helps for that (run with --report first)"

**Comment by shiftyscales** [comment]
Replicated. Seeking input from @ProbablePrime.

https://wiki.resonite.com/index.php?title=Special:Search&profile=all&search=type&fulltext=1

```
[ccbc814a5731a4bfc5da3e9f] /index.php?title=Special:Search&profile=all&search=type&fulltext=1 Wikimedia\Assert\PreconditionException: Precondition failed: This Title instance does not represent a proper page, but merely a link target.

Backtrace:

from /var/www/html/vendor/wikimedia/assert/src/Assert.php(49)
#0 /var/www/html/includes/title/Title.php(3888): Wikimedia\Assert\Assert::precondition(boolean, string)
#1 /var/www/html/includes/title/Title.php(3869): MediaWiki\Title\Title->assertProperPage()
#2 /var/www/html/includes/Revision/RevisionStore.php(1838): MediaWiki\Title\Title->getId(boolean)
#3 /var/www/html/includes/Revision/RevisionStore.php(1743): MediaWiki\Revision\RevisionStore->ensureRevisionRowMatchesPage(stdClass, MediaWiki\Title\Title)
#4 /var/www/html/includes/Revision/RevisionStore.php(1621): MediaWiki\Revision\RevisionStore->newRevisionFromRowAndSlots(stdClass, NULL, integer, MediaWiki\Title\Title, boolean)
#5 /var/www/html/includes/Revision/RevisionStore.php(2361): MediaWiki\Revision\RevisionStore->newRevisionFromRow(stdClass, integer, MediaWiki\Title\Title)
#6 /var/www/html/includes/Revision/RevisionStore.php(1302): MediaWiki\Revision\RevisionStore->loadRevisionFromConds(Wikimedia\Rdbms\DBConnRef, array, integer, MediaWiki\Title\Title)
#7 /var/www/html/includes/search/RevisionSearchResultTrait.php(53): MediaWiki\Revision\RevisionStore->getRevisionByTitle(MediaWiki\Title\Title, boolean, integer)
#8 /var/www/html/includes/search/RevisionSearchResult.php(18): RevisionSearchResult->initFromTitle(MediaWiki\Title\Title)
#9 /var/www/html/includes/search/SqlSearchResult.php(37): RevisionSearchResult->__construct(MediaWiki\Title\Title)
#10 /var/www/html/includes/search/SqlSearchResultSet.php(61): SqlSearchResult->__construct(MediaWiki\Title\Title, array)
#11 /var/www/html/includes/search/SearchResultSet.php(76): SqlSearchResultSet->extractResults()
#12 /var/www/html/includes/search/SearchResultSet.php(187): SearchResultSet->count()
#13 /var/www/html/includes/search/SearchEngine.php(206): SearchResultSet->shrink(integer)
#14 /var/www/html/includes/search/SearchEngine.php(162): SearchEngine->maybePaginate(Closure)
#15 /var/www/html/includes/specials/SpecialSearch.php(467): SearchEngine->searchTitle(string)
#16 /var/www/html/includes/specials/SpecialSearch.php(248): MediaWiki\Specials\SpecialSearch->showResults(string)
#17 /var/www/html/includes/specialpage/SpecialPage.php(727): MediaWiki\Specials\SpecialSearch->execute(NULL)
#18 /var/www/html/includes/specialpage/SpecialPageFactory.php(1653): MediaWiki\SpecialPage\SpecialPage->run(NULL)
#19 /var/www/html/includes/actions/ActionEntryPoint.php(506): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#20 /var/www/html/includes/actions/ActionEntryPoint.php(153): MediaWiki\Actions\ActionEntryPoint->performRequest()
#21 /var/www/html/includes/MediaWikiEntryPoint.php(185): MediaWiki\Actions\ActionEntryPoint->execute()
#22 /var/www/html/index.php(55): MediaWiki\MediaWikiEntryPoint->run()
#23 {main}
```

**Comment by ProbablePrime** [comment]
Fixed, thank you!
