### ISSUE TITLE
Allow typing values directly into Global variables

### ISSUE THREAD

**Issue by ShrikeAlvaron** [Yellow-Dog-Man/Resonite-Issues#303]
### Is your feature request related to a problem? Please describe.

Currently setting Global values is extremely awkward and unintuitive, usually involving creating a Drive for the Global and using that to enter the value.  

### Describe the solution you'd like

Being able to type or drop values directly into a Global variable is the behavior more people expect upon first seeing them, and would greatly improve the experience of using them.

### Describe alternatives you've considered

Driving, writing or using an inspector to manually set the Global are the only current alternatives to directly editing them and all are undesirable for long-term usage.

### Additional Context

A mod currently exists that adds this behavior, but suggesting new users install mods is pretty undesirable.

**Comment by Frooxius** [comment]
I'm taking this. This is something that was already planned, but I didn't get the time to implement this before release.

**Comment by XDelta** [comment]
In the meantime and as it was mentioned, I have a mod that allows doing this https://github.com/XDelta/ResoniteDirectEditGlobal

**Comment by Frooxius** [comment]
This is now supported in 2023.11.13.1343!
