### ISSUE TITLE
[Meta] Enable enhanced GitHub issues public preview on org

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#3034]
### Is your feature request related to a problem? Please describe.

This issue is not related to a particular problem, I just thought it could be a nice QoL enhancement.

### Describe the solution you'd like

A few days ago, GitHub rolled out a public preview of an upcoming update to how issues are handled (see link below for the announcement).

Given this preview contains several features that could be useful, I think it would be great to enable it in the yellow-dog-man org.

Those new features include:
- Nested issues - that have more clarity on which items are required or related, and eases the process of having a "hub" issue for larger reworks (for instance, adding a new child of #1116 would automatically list the referenced issue there)
- A better search system - allowing more and the combination of multiple parameters as well as new ways to sort issues altogether

This preview also brings some updates to the issues UI like easier issue sharing.

Links:
- Announcement: https://github.blog/changelog/2024-10-01-evolving-github-issues-public-preview/
- Nested issues: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues
- Advanced search features: https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/filtering-and-searching-issues-and-pull-requests#building-advanced-filters-for-issues

### Describe alternatives you've considered

Staying with the current system until the new one is rolled out globally.

### Additional Context

Being a heavy GitHub user for my job, I've been fiddling with those new features quite a lot in the past days, and I think they do bring some nice-to-have enhancements.

### Requesters

U-j4 | j4.lc (Discord)

**Comment by ProbablePrime** [comment]
I requested access.

**Comment by JackTheFoxOtter** [comment]
It's definitely different looking now! Will poke around a bit and see what changed.

**Comment by jae1911** [comment]
> It's definitely different looking now! Will poke around a bit and see what changed.

Don't forget to send feedback to https://gh.io/issues-updates-feedback !

**Comment by ProbablePrime** [comment]
We have access, I like it. I do apologize if I broke anyone's muscle memory though.

As a bonus when GitHub makes this change site-wide it should be good.
