### ISSUE TITLE
Add the hyphen "-" as a valid character for dynamic variable names

### ISSUE THREAD

**Issue by Epimonster** [Yellow-Dog-Man/Resonite-Issues#3038]
### Is your feature request related to a problem? Please describe.

Currently, dynamic variables only support a limited number of non-alphanumeric characters. I would like to request that hyphens be added to the list of valid characters for a dynamic variable name. This would make creating convenient variable names derived from fields such as user ID (U-Gareth48) and locale code (zh-cn) much more convenient as opposed to requiring adjustments to the naming scheme to create them. 

### Describe the solution you'd like

I would like to request that the hyphen be added to the list of valid characters for naming dynamic variables.

### Describe alternatives you've considered

As I mentioned above you can program specific handlers to automatically convert this character, but this can lead to inconsistencies and weird edge cases.
 
As an example, people can have hyphens in their username which prevents their name from being used as a dynamic variable. If you replace it with a different character (like an underscore) it can lead to a conflict that's difficult to resolve since people can also have underscores in their name. 

### Requesters

badhaloninja, Gareth48

**Comment by Frooxius** [comment]
You make a good argument with the dashes in the user ID's. I think we can add the dash into list of allowed characters.

**Comment by Frooxius** [comment]
I've added this in2024.10.4.923, thanks!
