### ISSUE TITLE
passthrough protoflux displays

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#3039]
### Is your feature request related to a problem? Please describe.

when trying to read a value or object from protoflux or even a impulse node, you have to disconnect and reconnect variable lines when you finish viewing the contents.

### Describe the solution you'd like

a passthrough display for impulses and value/object displays that allow the user to view the impulse or "content" of the wire while being able to keep it ran into the other nodes.

### Describe alternatives you've considered

creating a protoflux node that provides said implementation.

### Requesters

charlie_san

**Comment by Frooxius** [comment]
We're not going to add this for a few reasons:
- Generally anything debug related should ideally be removable from the code without affecting its functionality, but this will effectively make the code dependent on the debugging nodes, where removing them would break the code. This is something we will avoid on principle
- You can connect values to a display while also connecting them to other functional bits - value outputs can be connected to multiple inputs, there is no reason to have them pass through display only
- We do have a general ProtoFlux debugging system issue here already to improve the overall tooling: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1122

**Comment by charlie-sans** [comment]
i was also thinking of it could be protoflux's version of component comments aswell
