### ISSUE TITLE
Add the new easing functions as shaping nodes

### ISSUE THREAD

**Issue by BaxterOttoman** [Yellow-Dog-Man/Resonite-Issues#3041]
### Is your feature request related to a problem? Please describe.

The new easing options for tweens are excellent, but there's not currently a way to use them outside of tweening. The shaping nodes in the Math>Shaping section of the flux menu are scarcely populated, and these functions would make excellent additions to that section and allow these easing curves to be used for many more scenarios than value tween alone can provide.

### Describe the solution you'd like

I would like to see nodes in the Math>Shaping section that take a float value and map it to each easing function the value tween node uses. The section currently has individual nodes for each shape, but I could also see it implemented as a node that takes a float and a `CurvePreset` and outputs the input value mapped onto the specified curve.

### Describe alternatives you've considered

Tweening a float and using that or writing my own easing functions.

### Requesters

Baxter
Baxter ModernBalloonie

**Comment by JackTheFoxOtter** [comment]
> The new easing options for tweens are excellent, but there's not currently a way to use them outside of tweening.

You sure? In the update post Froox mentioned the following:

> -- There are also three ProtoFlux nodes for each - In, Out and InOut

So from my understanding there should be a LOT more shaping nodes included in this update, or are you talking about a different kind of node?

**Comment by Frooxius** [comment]
These nodes already exist. They're under Math > Easing:

![Image](https://github.com/user-attachments/assets/57d42c85-704c-40fc-88e8-b66d08cb696d)
