### ISSUE TITLE
Bezier Curve Nodes Disconnect From Everything When Saved and Spawned

### ISSUE THREAD

**Issue by blllrpy** [Yellow-Dog-Man/Resonite-Issues#3042]
### Describe the bug?

Any bezier curve node that is spawned, whether it is packed or not, disconnects from all inputs and outputs when it is saved to the inventory and loaded.

### To Reproduce

Spawn any bezier curve node into the world, then add any arrangement of input and output nodes, either pack flux and save it, or just save it as flux, then spawn it from the inventory.

### Expected behavior

The bezier curve node was expected to retain all of it's ingoing and outgoing connections through saves and loads.

### Screenshots

Attached is a video showing off the issue [https://www.youtube.com/watch?v=pKgaCkrlZU4](url)

### Resonite Version Number

2024.10.4.923

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Meta Quest 2

### Log Files

[DESKTOP-JKSRBLO - 2024.10.4.923 - 2024-10-05 08_02_08.log](https://github.com/user-attachments/files/17265217/DESKTOP-JKSRBLO.-.2024.10.4.923.-.2024-10-05.08_02_08.log)

### Additional Context

The node only disconnects when it is saved and loaded. Duplicating the node or the object it is under as a whole does not affect it.

### Reporters

blllrpy, GyztorMizirath

**Comment by Frooxius** [comment]
@BlueCyro Can you look at this one?

**Comment by BlueCyro** [comment]
Yeah I'll look at this

**Comment by Frooxius** [comment]
I've merged this in 2024.10.8.1349, thanks!
