### ISSUE TITLE
Can't save the world in screen mode through the session menu.

### ISSUE THREAD

**Issue by Rixx-vr** [Yellow-Dog-Man/Resonite-Issues#3054]
### Describe the bug?

While playing Resonite in screen mode only, I am unable to open the save dialog either by clicking on "Save As..." or "Save Copy..." in the session menu, even when in a valid folder. The same action works in VR and when hotswapping into desktop mode.

The logs reveal this error once the save is clicked:
```
Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at FrooxEngine.WorldOrb.UpdateInfoPositions () [0x0002c] in <192860a1cf6840a78484d3e6ee254d70>:0 
  at FrooxEngine.WorldOrb.OnStart () [0x00123] in <192860a1cf6840a78484d3e6ee254d70>:0 
  at FrooxEngine.ComponentBase`1[C].InternalRunStartup () [0x00009] in <192860a1cf6840a78484d3e6ee254d70>:0 
  at FrooxEngine.UpdateManager.RunStartups () [0x00039] in <192860a1cf6840a78484d3e6ee254d70>:0 
10:41:01 PM.255 (189 FPS)	Restoring currently updating root. Stack:
```

### To Reproduce

- Start Resonite through Steam and select "Play in screen mode."
- Try saving a world through the session menu.
- The World Orb with the save options does not appear.

### Expected behavior

The Save World Orb should appear just like it does in VR or when hotswapping from VR to Desktop.

### Screenshots

https://github.com/user-attachments/assets/5f035554-a336-4672-8daf-8f323e28cb5e

### Resonite Version Number

2024.10.4.923

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-39NTKHQ - 2024.10.4.923 - 2024-10-08 22_40_09.log](https://github.com/user-attachments/files/17299370/DESKTOP-39NTKHQ.-.2024.10.4.923.-.2024-10-08.22_40_09.log)

### Reporters

[Rixx](https://github.com/Rixx-vr)

**Comment by shiftyscales** [comment]
Could you go into third person or free-cam and look around you @Rixx-vr? This sounds like it might be a duplicate of #2941.

**Comment by Nytra** [comment]
The context menu prompt is beneath your feet due to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2941, use F5 or F6 to look at it and press it.

**Comment by Rixx-vr** [comment]
> Could you go into third person or free-cam and look around you [@Rixx-vr](https://github.com/Rixx-vr)? This sounds like it might be a duplicate of [#2941](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2941).

Yes indeed the dialog pops up like described in [#2941](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2941). Ok this is a duplicate then.
