### ISSUE TITLE
System Notifications For When Your Promoted Or Demoted In A World

### ISSUE THREAD

**Issue by AlanMoonbase** [Yellow-Dog-Man/Resonite-Issues#3057]
### Is your feature request related to a problem? Please describe.

When someone is promoted or demoted, they are not notified unless the person who did it tells them. This can be inconvenient if the promotion or demotion was accidental.

### Describe the solution you'd like

Show a notification similar to a message or user join that tells them they have been demoted or promoted to a specific role.

Example: "You've been promoted to Builder by <Username>!"

### Describe alternatives you've considered

Someone could make a mod or someone could implement an in-world role visualizer above peoples nametags.

### Requesters

Moonbase, Draconas Rayne, ModernBalloonie

**Comment by Frooxius** [comment]
Added in 2024.10.23.15! Thanks!
