### ISSUE TITLE
Spout protocol support

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#3061]
### Is your feature request related to a problem? Please describe.

I would like to be able to use the [Spout](https://github.com/leadedge/Spout2) video protocol to capture video from Resonite's cameras directly. This is a useful protocol to support capturing from multiple distinct cameras without having to involve the main game window, allowing desktop mode users to have streaming cameras, or to help VR players stay private by never capturing their actual game window. It's widely supported in software such as OBS.

### Describe the solution you'd like

A component to attach to cameras to allow them to act as a Spout Sender

It would also be nice to have the ability to send a Spout stream into Resonite, though this would require a lot of additional work for encoding and transmitting the stream as a normal video.

### Describe alternatives you've considered

Capturing the desktop window.

### Additional Context

I thought this issue already existed but I can't find it.

**Comment by jae1911** [comment]
The existing issue is logged as #1421 :)

**Comment by ko-tengu** [comment]
why on earth does that not appear searching for "spout"
