### ISSUE TITLE
when turning on hand tracking with quest virtual desktop, the game will randomly crash.

### ISSUE THREAD

**Issue by charlie-sans** [Yellow-Dog-Man/Resonite-Issues#3068]
### Describe the issue.

in the new beta trying out if my fingies still work and whenever i turn on hand tracking, it has a chance to crash the game outright.

### To Reproduce

open virtual desktop and start steamVr
start resonite
turn on hand tracking ether through the menu or tapping the controllers and watch the game just die.

### Expected behavior

for resonite to support my hands and not crash.

### Resonite Version Number

Beta 2024.10.10.1348

### What Platforms does this occur on?

Windows

### What headset if any do you use?

oculus quest 1 with virtual desktop

### Log Files

[CHARLIE - 2024.10.10.1348 - 2024-10-11 14_03_41.log](https://github.com/user-attachments/files/17337229/CHARLIE.-.2024.10.10.1348.-.2024-10-11.14_03_41.log)

### Reporters

charlie_san

**Comment by ohzee00** [comment]
As said in the session you were in there is a open github issue on it here: 
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3066

**Comment by charlie-sans** [comment]
ah cheers
