### ISSUE TITLE
"Dawn Assets" has empty folders, missing items

### ISSUE THREAD

**Issue by dragos240** [Yellow-Dog-Man/Resonite-Issues#3079]
### Describe the Underlying Issue

Ever since the "Dawn Modular Set" was reorganized into what is now "Dawn Assets", I've noticed that a few folders are completely empty when they shouldn't be. One example is "Dawn Sky". It also seems like some structures that were in "Dawn Modular Set" are not in this new folder. Is this a known issue?

### To Reproduce

Go to Resonite Essentials->Assets->Resonite Assets->Dawn Assets->Dawn Sky. It will be empty.

### Expected Behavior

The folders should at the very least have what they had before and should not be empty.

### Reporters

natosaka
gamethecupdog: Suggested some things to add to this issue

**Comment by dragos240** [comment]
A suggestion: If a folder is a work in progress, there should be some kind of indicator that it is, rather than be left blank. Several user public folders have something like an item/folder called WIP to tell the person viewing the folder the current state. A user that's new to the platform would probably be confused that there are blank folders with no indicators of why in the official assets.

**Comment by shiftyscales** [comment]
Seeking input from @AegisTheWolf, @RueShejn, or @RyuviTheViali - if there are empty folders- it is possible that there was a sync issue and objects were not properly uploaded to those folders.

**Comment by AegisTheWolf** [comment]
Ill delete these folders, we were gonna populate them then other things got prioritized, ive been sorting the essentials on my own in my off time but these things take time.
