### ISSUE TITLE
Camera Component Motion Blur toggle Stacks AO effects

### ISSUE THREAD

**Issue by RueShejn** [Yellow-Dog-Man/Resonite-Issues#3092]
### Describe the bug?

Toggling the motion blur option on the Camera Component Stacks AO effects as its toggled on and off
doing this will make the preview image darker and lower FPS the more the option is pressed
Side by Side of the effect
![Image](https://github.com/user-attachments/assets/ec216130-499d-46e6-8fee-a8aace9a514f)

Note: this dose not effect screenshots taken with the camera only the preview render texture

### To Reproduce

1. Spawn a camera using the dev tip and inspect it
2. locate the Motion Blur option radio bubble
3. Toggle the Motion Blur option multiple times and watch the effect stack and gradually darken the image

### Expected behavior

the option to toggle motion blur should not persist or effect the camera in this way when toggled

### Resonite Version Number

Beta 2024.10.8.1349

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-L6KVB13 - 2024.10.8.1349 - 2024-10-17 19_00_12.log](https://github.com/user-attachments/files/17426330/DESKTOP-L6KVB13.-.2024.10.8.1349.-.2024-10-17.19_00_12.log)

**Comment by gameboycjp** [comment]
Is this the same as what I saw in #2353, by chance?

**Comment by shiftyscales** [comment]
I believe entirely so @gameboycjp - thanks for the link. When @RueShejn had mentioned this issue I was pretty sure I remembered having seen it before, but couldn't find your issue when I searched- so I encouraged him to make another issue anyway. Going to close and merge this into your existing issue, thanks.
