### ISSUE TITLE
Better Inventory Management

### ISSUE THREAD

**Issue by TheSpecterLemon** [Yellow-Dog-Man/Resonite-Issues#31]
### Is your feature request related to a problem? Please describe.

To move an item between folders, you must spawn it out and re-save it to the desired folder. This makes inventory management take more time and causes more load on the server in order to re-save the items.

### Describe the solution you'd like

- Drag-and-drop inventory items to different folders
- Ability to rename folders
- Multi view for inventory directories

### Describe alternatives you've considered

Using the legacy inventory allows you to "hold" an inventory directory and allows you to save things a little faster without having to re-navigate to the desired directory.

### Additional Context

I understand an inventory overhaul is a planned feature. You may discard this ticket if it is not necessary.

**Comment by Nammi-namm** [comment]
Cut, copy and paste functions would be really neat. I'll gladly accept either that or drag and drop.

**Comment by FlameSoulis** [comment]
Saw someone new who also had this issue. Please end this missing feature's lack of existence. Even if it's just a humble 'copy' and 'paste' (since cut can just be done by deleting the undesired version in the meantime).

**Comment by Frooxius** [comment]
All of the requested things are actually things that are planned to be addressed by the Inventory UI rework itself: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1119

I'm closing this one as duplicate in favor of the main one.
