### ISSUE TITLE
"Contact has not migrated" when migrating from resonite accound to another resonite accound

### ISSUE THREAD

**Issue by carson-coder** [Yellow-Dog-Man/Resonite-Issues#3100]
### Describe the bug?

I made a new resonite account and when I started a migration task to migrate my old account to my new account.after doing that I get a message `Contact has not migrated` on all my contacts and I cannot join contacts and contacts plus sessions

### To Reproduce

Create a new resonite account and migrate contacts from one account to the new one.

### Expected behavior

contacts show their actual status and I can join contacts and contacts plus sessions

### Screenshots

![Image](https://github.com/user-attachments/assets/e7c97b13-95e1-4865-8393-21e2ad047446)

### Resonite Version Number

Beta 2024.10.8.1349

### What Platforms does this occur on?

Windows under proton

### What headset if any do you use?

oculus quest 2 and alvr

### Log Files

I cannot find the log files from when I migrated and I was using mods when migrating

**Comment by Frooxius** [comment]
Hmm, this is a problematic one. We can't actually make those contacts show up properly - from their perspective you're a new account, while your old one still exists, which makes this situation a bit weird.

It would essentially mean we'd have to add another contact to *their* contact list, which I'm not sure is a good idea to do on their behalf to have suddenly a new contact appear.

The best thing we can do is just clear those out and make it so when migrating from one Resonite account to another, you can't migrate contacts.

The other alternative is we "move" the contacts from one account to another - meaning your original account you migrate from loses them as contact. This would be more similar to just renaming your account.

**Comment by carson-coder** [comment]
I have also noticed that removing and re adding people does not fix this.

**Comment by Gyztor** [comment]
I have also had this problem as well though it seemed to disappear after 2 days and most people re-adding the contact back. maybe just having the game recognize better and show something about the contact being sent instead of migrated and letting the person receiving the contact have a clear indicator it was because of a migration would be something that might help in those cases, though I don't know how possible that is at this current time.

**Comment by carson-coder** [comment]
My contacts are now fixed. It looks like it just takes time.
