### ISSUE TITLE
Local (HDD) screenshot organization

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#3105]
### Is your feature request related to a problem? Please describe.

With the settings update you added a field to organize the screenshots saving into our Resonite Inventory.
But what about our Local HDD storage?

### Describe the solution you'd like

Right now when you take screenshots they are saved locally in your: `C:\Users\troyBORG\Pictures\Resonite` folder.

I'd like if it would organize them folders like: `YYYY-MM`
Or maybe even allow some of the same variables in game to pick your naming scheme.

### Describe alternatives you've considered

https://github.com/hantabaru1014/ResoniteScreenshotExtensions/

### Additional Context

![Image](https://github.com/user-attachments/assets/8c222774-c8c8-448a-ac4c-5172853da1c1)

**Comment by shiftyscales** [comment]
This is a duplicate of #983. Thank you for your suggestion.
