### ISSUE TITLE
Resonite packages corrupt when overwritting an existing file with the same name and extension.

### ISSUE THREAD

**Issue by 989onan** [Yellow-Dog-Man/Resonite-Issues#3109]
### Describe the bug?

Exporting a resonite package with the exact name and extension as another resonite package in the same folder corrupts the file. It does not create a new package, and the resulting corrupted file cannot be opened by an archiver like 7zip or winrar.

### To Reproduce

Import resonite package from a folder.
Export resonite package to same folder without renaming it.
Try to import same resonite package again.
Gets stuck on decoding package and throws an error in the logs.

### Expected behavior

We should be able to overwrite a package of the same name with new contents without corrupting the resulting file.

### Resonite Version Number

Beta 2024.10.8.1349

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[CHEW-PC - 2024.10.8.1349 - 2024-10-22 10_53_25.log](https://github.com/user-attachments/files/17478336/CHEW-PC.-.2024.10.8.1349.-.2024-10-22.10_53_25.log)

### Reporters

989onan
Venport
KarasuTengu

**Comment by epicEaston197** [comment]
Huh I knew I wasn't going crazy I've had the same issue as well and a friend had to manually rebuild the zip file in order for me to get the model back

**Comment by shiftyscales** [comment]
Does this only occur when the package is exported multiple times from the same session, or does the issue persist after restarting the client and overwriting the package as well, @989onan?

Are there any other file types that get corrupted in this way? Or is it just specific to .ResonitePackage files?

**Comment by Frooxius** [comment]
This is an easy fix, we just need to switch it so it overwrites the existing file completely.

**Comment by Frooxius** [comment]
Fixed this in 2024.10.29.1229, thanks for report!
