### ISSUE TITLE
Hang on account registration

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#3110]
### Describe the bug?

When trying to register an account, it will load indefinitely and never register said account.

### To Reproduce

1. Start Resonite
2. Hit "Create an account"
3. Fill out the information
4. Observe the registration window will hang and will not register the account

### Expected behavior

Account should be registered.

### Resonite Version Number

Beta 2024.10.8.1349

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[TETHYS - 2024.10.8.1349 - 2024-10-22 20_10_07.log](https://github.com/user-attachments/files/17479874/TETHYS.-.2024.10.8.1349.-.2024-10-22.20_10_07.log)

I can see
```
20:11:17.397 (144 FPS)	Server Error running POST request to https://api.resonite.com/users. Remaining retries: 10. RequestTime: 5.44s, Total Elapsed: 5.46s
20:11:23.190 (140 FPS)	Server Error running POST request to https://api.resonite.com/users. Remaining retries: 9. RequestTime: 5.54s, Total Elapsed: 11.25s
20:11:29.125 (144 FPS)	Server Error running POST request to https://api.resonite.com/users. Remaining retries: 8. RequestTime: 5.43s, Total Elapsed: 17.19s
20:11:35.691 (144 FPS)	Server Error running POST request to https://api.resonite.com/users. Remaining retries: 7. RequestTime: 5.57s, Total Elapsed: 23.75s
```

### Additional Context

Basic troubleshooting steps were done like Syncing the clock and removing all mods.

### Reporters

U-j4 | j4.lc (Discord)
axochou (Discord; original reporter in the French language channel)
toki_pouce (Discord; second reporter in French language channel)

**Comment by Frooxius** [comment]
I pushed a fix to the cloud. It should work now, thank you for the report!
