### ISSUE TITLE
When Get Finger Type is plugged into Compose Finger but the output of Get Finger Type is -1 due to not being a finger, the world crashes.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3112]
### Describe the bug?

When Get Finger Type is plugged into Compose Finger but the output of Get Finger Type is -1 due to not being a finger, the world crashes.

This seems to happen with any body node that isn't a finger, like let's say you have Hips in the Get Finger Type node, the game will crash as well, but not if the body node is actually a finger.

I did check the log and it seems there is an exception related to Invalid Finger.

### To Reproduce

Get a Get Finger Type node and then plug it into Compose Finger, then try to read the output of Compose Finger, the game crashes.

### Expected behavior

For the world not to crash.

### Screenshots

https://github.com/user-attachments/assets/ea6260c7-0792-44f7-af45-ccf15141e47e

### Resonite Version Number

Beta 2024.10.8.1349

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-QBGCSAQ - 2024.10.8.1349 - 2024-10-22 15_32_55.log](https://github.com/user-attachments/files/17482825/DESKTOP-QBGCSAQ.-.2024.10.8.1349.-.2024-10-22.15_32_55.log)

### Reporters

ModernBalloonie

**Comment by Frooxius** [comment]
Fixed in 2024.10.23.15! Thanks!
