### ISSUE TITLE
Switching between hand tracking and controllers in game while using SteamLink crashes the game

### ISSUE THREAD

**Issue by Mrdabup** [Yellow-Dog-Man/Resonite-Issues#3139]
### Describe the bug?

When switching between the SteamLink's handtracking and controller tracking, the game crashes.

### To Reproduce

1. Own a Quest 2 or greater (latest being Quest 3S)
2. Have hand tracking enabled & have auto detection between hand tracking and controllers enabled
3. Download SteamLink and hop into the public beta branch
4. Connect SteamLink with your PC
5. Make the controller schemas be the hand tracking, any community or DIY binding is fine
6. Launch Resonite
7. Once at local or cloud world, start switching between controllers and hand tracking (it may take a while, have an action like jumping going on meanwhile you switch controllers)
8. Game Crashes

### Expected behavior

I expect it not to crash and switch between controllers normally.

### Resonite Version Number

Beta 2024.10.23.15

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2 via SteamLink

### Log Files

[DESKTOP-893KKM6 - 2024.10.23.15 - 2024-10-26 15_15_02.log](https://github.com/user-attachments/files/17531739/DESKTOP-893KKM6.-.2024.10.23.15.-.2024-10-26.15_15_02.log) 

### Reporters

Mrd.a (Discord)

**Comment by Mrdabup** [comment]
I changed the title to reflect on the issue a bit better.

**Comment by Frooxius** [comment]
We already have issue for this here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3066

Closing this as duplicate.

**Comment by Frooxius** [comment]
Also note - for crashes we need the crash dump logs as well. If you can share those in the other thread that can be useful.
