### ISSUE TITLE
Log file spammed with `Error running discord action Callbacks, with result Ok and message: NotRunning`

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#3143]
### Describe the bug?

I noticed this message spamming my headless log file and graphical client log file. It started after I closed the Discord process.

### To Reproduce

Start Resonite while Discord is running and then close the Discord process

### Expected behavior

The log file does not get spammed with this message

### Resonite Version Number

Beta 2024.10.29.1229

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

Headless log: [DESKTOP-H976HO2 - 2024.10.29.1229 - 2024-10-30 08_42_59.log](https://github.com/user-attachments/files/17578372/DESKTOP-H976HO2.-.2024.10.29.1229.-.2024-10-30.08_42_59.log)

Graphical client log: [DESKTOP-H976HO2 - 2024.10.29.1229 - 2024-10-30 20_08_04.log](https://github.com/user-attachments/files/17578463/DESKTOP-H976HO2.-.2024.10.29.1229.-.2024-10-30.20_08_04.log)

### Additional Context

Probably a continuation of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1522

### Reporters

Nytra (Discord: nytra)

**Comment by ProbablePrime** [comment]
Ill take a look, I really dislike the Discord Game SDK :(

**Comment by ProbablePrime** [comment]
Looks like the Discord SDK is throwing a [ResultException](https://github.com/Jannify/DiscordGameSDKWrapper/blob/main/DiscordGameSDKWrapper/Core.cs#L749)

With its Result set to "ok" and its message set to "Not Running". Whereas one would expect the result to be NotRunning.

I'll dig into this more.

**Comment by ProbablePrime** [comment]
Perusing through the wrapper we use, this is uh impossible https://github.com/Jannify/DiscordGameSDKWrapper/blob/main/DiscordGameSDKWrapper/Core.cs#L1107

But *shrug*, I added, "OK" as one of the items we won't log.

**Comment by Frooxius** [comment]
The fix has been merged in 2024.11.12.1329! Thank you!
