### ISSUE TITLE
optional system for radial submenu to persist after exiting

### ISSUE THREAD

**Issue by antrobot1234** [Yellow-Dog-Man/Resonite-Issues#315]
### Is your feature request related to a problem? Please describe.

I find it annoying when I have to completely restart a sub menu chain when i am trying to use a complex tool or avatar control system. it is also annoying to repeatedly enter the same sub menu over and over again when you need to change things frequently.

### Describe the solution you'd like

I feel like a way to fix it would be to give the user the option to 'remember' the sub menu they were on when they exit the sub menu. This way, they would not need to go back to the sub menu. obviously, with this option enabled, there would need to be a system to exit a sub menu they had open. My suggestion for this is that instead of a sub menu closing whenever you move your hand away from it, it would instead go to next layer up until reaching the base menu. the option to enable this would be in the main settings menu.

### Describe alternatives you've considered

I have considered replacing the default menu. the problem is that it would be very context specific and wouldn't help for a majority of the situations.

**Comment by FlameSoulis** [comment]
I think you can still trigger a menu's slot destination while engaging any actions on click, which would replicate part of what you want.

However, something that can allow a 'last slot' menu value to exist would be interesting, as it could then be used to address your issue, while respecting creators who might rely on not having such recall functions existing.

**Comment by Frooxius** [comment]
This seems more like something that's up to you and content creators who make those menu systems, rather than something we'd do on our end - we don't control how people structure their custom menus.

If you don't want to start over, then don't make your menus exit after you select option. You can simply just keep it open and have button to go back a level up.

Exiting the menu means that "I'm now completely done with this" and I don't think we should change that, as that could be confusing to users. Just don't exit the menu if you're not done with it and you want to interact with other options.

Am I missing something here?

**Comment by antrobot1234** [comment]
@Frooxius my issue with that argument is that there is no way to keep the radial menu open without keeping one hand stuck in the radial menu, as it would close if you move your hand away. Sometimes I want to pick up where I left off rather than starting from the root menu every time I need to do something with that hand.

My reasoning behind this suggestion is that often times there is a submenu that you would need to access several times to interact with it, but you also need to be able to move the hand with the tool to use it. One example of this would be the standard multi tool, which has a lot of different sub menus that need to be traversed frequently to use it.

If you don't want to implement this as default functionality, you could at least expose the last active radial menu and provide a system that allows the user to set a "default" submenu to open when you first open your radial wheel. These two functionalities would allow a user to implement this feature on their own without explicitly making it a feature.
