### ISSUE TITLE
/requestRecordUsageReport only shows records post name-change

### ISSUE THREAD

**Issue by shiftyscales** [Yellow-Dog-Man/Resonite-Issues#3152]
### Describe the bug?

I've recently switched my account name from Shifty to Laura. Everything else seems to be working correctly, and my U-id is still correctly listed as U-Shifty. Likewise, the report correctly reports "Laura" as the account- but the only records counted / sent in email are ones created post-display name update.

### To Reproduce

- Change your account name
- Send the `/requestRecordUsageReport` command

### Expected behavior

The generated report should properly list all records associated with a Resonite account.

### Resonite Version Number

Beta 2024.10.29.1229

### What Platforms does this occur on?

Windows

### Log Files

N/A

### Additional Context

I am running low on space (usage ~99GB) and wanted to identify possible legacy assets I could clean up. The generated report only showed recent records post display name change.

Seeking help from @Frooxius.

### Reporters

@shiftyscales

**Comment by shiftyscales** [comment]
The records themselves all seem to still be present and functional as I can spawn old items from my inventory without issue. I just generated another report and it has the same issue- only reporting my most recent records post display name change, @Frooxius. Only 5.17GB reported for the raw sum.

**Comment by shiftyscales** [comment]
Thank you!

**Comment by Frooxius** [comment]
I've fixed this in 2024.11.12.1329.

This was actually more serious than it seemed - the name change would end up clearing the asset manifest in the database. I've made changes so this doesn't happen again with anything else.

The missing asset manifests were also all rebuilt, so it should work properly now!

Thanks for report!
