### ISSUE TITLE
(flux) Guids don't plug into things

### ISSUE THREAD

**Issue by LimeProgramming** [Yellow-Dog-Man/Resonite-Issues#3155]
### Describe the bug?

Guid types only plug into format string node, a write or a dynamic node just don't work, wire gets stuck to flux tip.

I've seen it a few times before with different nodes depending on how they are spawned. 

### To Reproduce

try plugging Random Guid into a write node or anything that isn't a "format string" node

### Expected behavior

Guid threads plug into things that take guid threads

### Screenshots

https://github.com/user-attachments/assets/cd0220be-1d2d-46a7-b2f7-ca6cb22fa51c

### Resonite Version Number

2024.10.29.1229

### What Platforms does this occur on?

Windows

### What headset if any do you use?

pico 4

### Log Files

I'm open to discussing the issue further if you'd like, though I won’t be sharing logs in this case, as I feel they’re unnecessary here and their exclusion is not a valid excuse to dismiss this issue.

### Reporters

U-Calamity-Lime
@calamitylime

**Comment by Frooxius** [comment]
We need logs for this.

They *are* necessary, if you don't provide us with the information to resolve issue, we won't look into it.

**Comment by LimeProgramming** [comment]
I've reported the issue as far as I am willing to/feel necessary to. 
If you choose not to look into it, that's up to you.
Have a good day.

**Comment by Frooxius** [comment]
You're not giving us the necessary information to resolve the issue. This is not up to us, it's up to you.

If you don't want to give us the info we need to look into this and resolve the issue, that's your choice, not ours.

**Comment by Dusty-Sprinkles** [comment]
> I've reported the issue as far as I am willing to/feel necessary to. If you choose not to look into it, that's up to you. Have a good day.

Its more necessary to see why you're having issues than you think, connecting GUIDs to writes seems to work fine as far as I can tell, even overwriting the types is fine

![Image](https://github.com/user-attachments/assets/20a02c9b-bb06-4ad7-9215-0912c1b043a4)

Usually if you're asked for logs after the issue it means that they genuinely are needed or something could be going wrong on your end that could be solved
