### ISSUE TITLE
Add a flux node to remove Locomotion Modules properly

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Yellow-Dog-Man/Resonite-Issues#3158]
### Is your feature request related to a problem? Please describe.

#3156 
I want to temporarely grant locomotion modules for various different things
Removing them currently is not properly supported.

### Describe the solution you'd like

A flux node to "Remove locomotion module" by slot or name.

### Describe alternatives you've considered

Deleting the slot leaving null references behind blocking other modules from being accessable. See #3156

An alternative to my specific problem is to disable the slot above the modules so I can lock someone in place temporarely. Rather than giving them a temporary locomotion module.

Though this is an overarching issue and a generalized solution would be a lot better.

### Additional Context

Currently I tend to use locomotion modules as a temporary "way of getting somewhere" or as a way to safely grab other people or similar shenanigans.

I want to grant temporary locomotion modules to anyone and be able to remove them again one way or another.

### Requesters

3x1t_5tyl3

**Comment by ClimberJ** [comment]
I already created an issue for this a while ago: #1330

**Comment by 3x1t-5tyl3** [comment]
Closing this as it's a duplicate. Thanks @ClimberJ !I'll link the other issues to there :P
