### ISSUE TITLE
desktop menu does not work with multiple monitors

### ISSUE THREAD

**Issue by antrobot1234** [Yellow-Dog-Man/Resonite-Issues#317]
### Describe the bug?

if the user has multiple monitors, the desktop menu will only show the first one.

### To Reproduce

open desktop menu with multiple monitors.

### Expected behavior

an option to switch monitors, or ideally a way to have both.

**Comment by FlameSoulis** [comment]
Just tested with my setup, but cannot validate this bug.
What operating system are you using?

![Screenshot (3)](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/6835457/d08440af-5a22-412a-aefd-1d8575ac12d6)
![Screenshot (1)](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/6835457/0b2b5457-a739-43fb-b98a-831c785cfab3)
![Screenshot (2)](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/6835457/fb1c34b1-a09b-4a9d-8c1d-d5e8d8b5904c)

**Comment by NatBard** [comment]
![secret funtion](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/122479819/d9fa907f-db27-42bd-8c18-8044b0e59f51)
Just press the context menu button when in the desktop tab. Yeah kind of a secret feature perhaps an enhancement would be calling this feature out in the UI.

**Comment by antrobot1234** [comment]
@NatBard That still does not address the issue of having multiple monitors opened simultaneously. also yes that feature really should be advertised because i asked multiple people in the game and they all assumed you could just only use one monitor. I guess that's just because not a lot of people have multiple monitors.

**Comment by antrobot1234** [comment]
closed this issue in favor of two related feature requests: #323 #324
