### ISSUE TITLE
Null equip names showing locale string

### ISSUE THREAD

**Issue by Gyztor** [Yellow-Dog-Man/Resonite-Issues#3171]
### Describe the bug?

Null equip names showing locale string

### To Reproduce

Step 1: have a tool that has a null equip name
Step 2: click to equip and see local string

### Expected behavior

To not show local string and have null handling

### Screenshots

![Image](https://github.com/user-attachments/assets/cf9ad103-49a0-4528-8aa5-580970550dc9)
![Image](https://github.com/user-attachments/assets/3fafba9e-58d7-4b74-bce6-8e93a017a0fc)

### Resonite Version Number

Beta 2024.11.12.1329

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

Quest 3 on VD

### Log Files

Shouldn't be needed but if so let me know so I can clear mods. other people without mods see problem as well

### Reporters

Gyztor Mizirath, Lixquid, alizard

**Comment by shiftyscales** [comment]
It appears there was a typo in the locale key in the locale file, @Frooxius - The locale file contains `Interaction.NamedEquipTools.Default` the code is looking for `Interaction.NamedEquipTools.Default`.

Considering the named tools key is `Interaction.NamedEquipTool` that seems like the proper convention and we should probably just update the key in the locale file itself- thoughts?

**Comment by Frooxius** [comment]
Fixed this in 2024.11.19.479, thanks for report!
