### ISSUE TITLE
Add in-game page for news/events

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#3173]
### Is your feature request related to a problem? Please describe.

Honestly never feels great missing events.  For example, I've regularly missed out on festa despite wanting to participate, simply because there's near no visibility on these kind of events.  I'm not a discord user, I rarely check over there, and I don't have the time to comb through every channel looking for things that don't get posted in announcements and updates.

### Describe the solution you'd like

Addition of a "news" page or similar to the dashboard, to serve a similar purpose to the updates, community news, meetups, announcements, etc type channels.  This feature would greatly benefit community engagement, and boost awareness of what's going on in the community.

### Describe alternatives you've considered

The resonite bot could be used for this purpose without further investment into UI, however I would rather see that functionality moving into a dedicated space, especially one which would allow for graphical elements.

### Additional Context

I continue to remain salty about missing festa (and the cool festa badges) for yet another year >:(

### Requesters

zangooseoo

**Comment by Frooxius** [comment]
We already have issue for events here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2948

I do also plan to add system for "feeds/posts" as well, which would tie into this.

**Comment by gentlecolts** [comment]
> We already have issue for events here: [#2948](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2948)

oh, that's good to see!
This ticket is probably redundant then, though there's a point I'd like to call out here at least, which is that your ticket seems to be an "open to the public" feed.  With this ticket, I had official/semi-official events in mind, and I believe it'd be important to separate that from purely community-generated listings.  Does your proposal align with that?

**Comment by shiftyscales** [comment]
I believe ultimately it'd still be part of the same work / system- it'd just be a matter of how the information is filtered / displayed. E.g. there could be a feed made specifically for official / promoted events.

I do think in general it will be good for us to move as much of our communications about the platform onto the platform in some form or another, and that would likely be a good avenue for it.

E.g. in past, Frooxius had also conceptualized a system with which patch notes could be compiled and displayed to the user when they log in, showing them all that has been changed / updated since their last time using Resonite.

**Comment by Frooxius** [comment]
I don't think we need two separate feeds/calendars for official / community events, that would probsbly just confuse things and add clutter.

We can just add filtering options, so you can filter out what you'd see and we'd automatically subscribe users to the official feeds.

**Comment by shiftyscales** [comment]
> I don't think we need two separate feeds

I agree- sorry if that was unclear in my above statement- I meant feed as in "a filtered view of all content" not a separate data source. E.g. in the context of Bluesky- "Feeds" are just filters / different ways to present a selection of the entirety of the content that exists on the platform.

To a layperson feed and filter are effectively synonyms.

**Comment by gentlecolts** [comment]
It does sound like froox's proposal is compatible with the idea of having platform announcements.  I definitely agree with the idea of having only one ingame page for it (give or take in-world info as well), my main concern was avoiding a case where a flood of user generated news hurts the visibility of official platform news.  I'll close this and leave my comments on the other ticket
