### ISSUE TITLE
Upgrade the cloud to .NET 9

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#3179]
### Is your feature request related to a problem? Please describe.

With the release of .NET 9 to public, we can now upgrade our cloud infrastructure to the new framework from .NET 9

### Describe the solution you'd like

Switch to .NET 9 for the cloud infrastructure. This is expected to be likely just a quick switch, but we'll need to test things to make sure that nothing has exploded.

### Describe alternatives you've considered

N/A

### Additional Context

This can improve the cloud performance thanks to new .NET 9 improvements.

**Comment by Frooxius** [comment]
The main cloud API service is now running on .NET 9!

![Image](https://github.com/user-attachments/assets/c380ed68-612d-4077-b00a-a7e1a202d3bc)

**Comment by jae1911** [comment]
I don't know if it's only me but I think the upgrade broke `https://api.resonite.com/stats/cloudStats`:

```
 me@tethys ~  curl https://api.resonite.com/stats/cloudStats -v --trace-ascii -
Warning: --trace-ascii overrides an earlier trace/verbose option
== Info: Host api.resonite.com:443 was resolved.
== Info: IPv6: 2603:1020:206:6::24
== Info: IPv4: 20.105.232.38
== Info:   Trying [2603:1020:206:6::24]:443...
== Info: Connected to api.resonite.com (2603:1020:206:6::24) port 443
== Info: schannel: disabled automatic use of client certificate
== Info: ALPN: curl offers http/1.1
== Info: ALPN: server accepted http/1.1
== Info: using HTTP/1.x
=> Send header, 95 bytes (0x5f)
0000: GET /stats/cloudStats HTTP/1.1
0020: Host: api.resonite.com
0038: User-Agent: curl/8.9.1
0050: Accept: */*
005d:
== Info: Request completely sent off
== Info: schannel: remote party requests renegotiation
== Info: schannel: renegotiating SSL/TLS connection
== Info: schannel: SSL/TLS connection renegotiated
<= Recv header, 25 bytes (0x19)
0000: HTTP/1.1 204 No Content
<= Recv header, 37 bytes (0x25)
0000: Date: Mon, 18 Nov 2024 22:25:24 GMT
<= Recv header, 17 bytes (0x11)
0000: Server: Kestrel
<= Recv header, 68 bytes (0x44)
0000: Request-Context: appId=cid-v1:c67db067-bfe9-4b23-8b13-24e00de6cc
0040: 83
<= Recv header, 2 bytes (0x2)
0000:
== Info: Connection #0 to host api.resonite.com left intact
```

No content is returned be it on browser or cURL.

`https://api.resonite.com/sessions` works with the same command though.

**Comment by Frooxius** [comment]
The stats worker was going through the update as well, so it went briefly down.

**Comment by Frooxius** [comment]
This is now out! Closing this!
