### ISSUE TITLE
Exception thrown when loading youtube videos (related to yt-dlp parsing)

### ISSUE THREAD

**Issue by dragos240** [Yellow-Dog-Man/Resonite-Issues#3183]
### Describe the bug?

Youtube videos are not loading right now. I originally thought this was a yt-dlp not being updated issue, so I updated y-dlp. This didn't fix the issue and videos still do not load. I looked in the logs directory for weirdness. It seems to be that an exception is thrown when attempting to load videos. See attached file

### To Reproduce

Copy `https://www.youtube.com/watch?v=VYPMzHAYSRc` into your clipboard, paste into Resonite and select the default video option. A picture of headphones will appear, the video will not load

### Expected behavior

The video will load

### Resonite Version Number

2024.11.12.1329

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Bigscreen Beyond, but was testing in desktop mode

### Log Files

[DESKTOP-1CP07IP - 2024.11.12.1329 - 2024-11-14 14_32_47.log](https://github.com/user-attachments/files/17756858/DESKTOP-1CP07IP.-.2024.11.12.1329.-.2024-11-14.14_32_47.log)

### Additional Context

Look for the following in the log file as it contains a full stack trace that may help:
```
2:34:16 PM.709 (  0 FPS)	Exception trying to load video URL https://www.youtube.com/watch?v=HGl75kurxok from video service:
System.Exception: Error parsing youtube-dl output. Raw Output:
null
  at NYoutubeDL.Services.InfoService+<GetDownloadInfoAsync>d__0.MoveNext () [0x00260] in <4b5ef518ca6d411389395c3518968f2d>:0 
--- End of stack trace from previous location where exception was thrown ---
```

### Reporters

Nat Osaka

**Comment by Frooxius** [comment]
I've been looking into this. It seems that YouTube is now restricting the higher quality options. I've checked what yt-dlp actually outputs:
```WARNING: [youtube] YouTube said: ERROR - The caller does not have permission
WARNING: [youtube] Unable to download API page: HTTP Error 403: Forbidden (caused by <HTTPError 403: Forbidden>)
WARNING: Only images are available for download. use --list-formats to see them
ERROR: [youtube] 94AVfJcfLMU: Requested format is not available. Use --list-formats for a list of available formats
null```

I can revert the change which made it use the higher quality options, but the videos will likely be a lower quality as a result, but at least they will play.

**Comment by dragos240** [comment]
Depending on how it's implemented, you could keep the new change and have it default to old behavior if a specific format is not available to prevent an exception from being thrown. I say this because I'm sure the yt-dlp people are working on restoring functionality, so eventually the failing command may work again.

**Comment by Frooxius** [comment]
Do you have anything to indicate they're working to restore this functionality?

To me it seems like YouTube changed it so you need authentication now, since it's giving 403 Forbidden result, so I'm not confident it would come back.

**Comment by dragos240** [comment]
I do not, unfortunately. I was not aware of the specific problem, just that historically they've been able to fix this sort of thing.

**Comment by TisFoolish** [comment]
> Do you have anything to indicate they're working to restore this functionality?

I dug around in the yt-dlp github issue tracker and learned that they are not.  [What is broken is OAuth and the yt-dlp devs say that it'll be going away forever.](https://github.com/yt-dlp/yt-dlp/issues/11518)

It is recommended that users supply their own cookies for YT

**Comment by Frooxius** [comment]
I don't think that's the same issue, we don't really use OAuth. They are also getting 400 error instead of 403.

I've disabled the medialink in 2024.11.14.1195 which should fix the videos not loading for now, even though they're at lower quality. We'll have to investigate alternatives for higher quality following things.

Thanks for report!

**Comment by troyBORG** [comment]
> If you try running yt-dlp with no args except the URL, you get a combined format of `617+140`

I know a while ago I remember them saying something about the fact it splits the Video and Audio into two files.  
And I think it has to parse as one file to prevent sync issues or something?

![Image](https://github.com/user-attachments/assets/c60d7e4d-6367-465c-a0af-f47ab1ef4e65)

Which looks like
```18      mp4   640x360     30  2 │ ≈ 103.18MiB   437k https │ avc1.42001E          mp4a.40.2       44k 360p```

Is the only one with it as one file?  
Which is probably why we only getting 360p in game..
![Image](https://github.com/user-attachments/assets/75cfc5f7-93bb-4876-bf08-a77c61e60229)

**Comment by Frooxius** [comment]
If this is about improving quality, let's make a new issue please. 

This issue is about the exception being thrown, which was resolved.

**Comment by TisFoolish** [comment]
To me it seems to actually be about trying to understand what caused the
original exception/404 and trying to fix that instead of creating a
workaround

**Comment by Frooxius** [comment]
It's not.

We know what causes the original 403 - requesting formats with media connect client ID.

None of above is relevant to that.
