### ISSUE TITLE
BlackBodyColorX Node disconnects on save.

### ISSUE THREAD

**Issue by troyBORG** [Yellow-Dog-Man/Resonite-Issues#3188]
### Describe the bug?

When I use the BlackBodyColorX node, when you pack the Flux, save the object, then spawn it back out, nodes will be disconnected

### To Reproduce

Drive something using BlackBodyColorX node, then save, then spawn it out, flux will be disconnected
If you use BlackBodyColor it seems to work though.  As shown in attached pictures and 2nd video link.

### Expected behavior

For it to stay connected

### Screenshots or Videos
https://troyborg.us-southeast-1.linodeobjects.com/2024-11/2024-11-16%2002-33-25.mp4

Before Save:
![Image](https://github.com/user-attachments/assets/b9d0d28d-1f2a-4031-b4aa-752f2a3b4320)

After Save:
![Image](https://github.com/user-attachments/assets/23bd043e-21b4-46e2-b750-7a0d2500f85e)

https://troyborg.us-southeast-1.linodeobjects.com/2024-11/2024-11-17%2013-00-47.mp4

### Resonite Version Number

2024.11.14.1195

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop / Quest Pro

### Log Files
[DESKTOP-H0FLKOJ - 2024.11.14.1195 - 2024-11-16 02_33_26.log](https://github.com/user-attachments/files/17784017/DESKTOP-H0FLKOJ.-.2024.11.14.1195.-.2024-11-16.02_33_26.log)

### Additional Context
Originally I noticed this effecting the Lantern on my Avatar as I used that to drive color temp on it for visual and a local light source.  
I had updated this issue a few times as I tested and shown it effected multiple things, not just my avatar.

I know BlackBodyColor got updated https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1402#issuecomment-2445309986

**Comment by Frooxius** [comment]
@BlueCyro can you have a look at this one ASAP please?

**Comment by Frooxius** [comment]
Merged Cyro's fix in 2024.11.19.479, thank you!
