### ISSUE TITLE
Make the version copyable from the dashboard facet

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Resonite-Issues#320]
### Is your feature request related to a problem? Please describe.

When creating bug reports, it's required to put the version of Resonite into the form. This requires having the game open and copying it manually from the facet or copying it from a log.

### Describe the solution you'd like

Make the version copyable from the facet, either by just clicking on it or having a hover button like text messages.

### Describe alternatives you've considered

Keep things as is.

**Comment by Zyzyl** [comment]
Duplicate of https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/211

(Request now implemented apparently)

**Comment by Banane9** [comment]
Well then
