### ISSUE TITLE
Make the movement animation work on npcs

### ISSUE THREAD

**Issue by alexderpyfox** [Yellow-Dog-Man/Resonite-Issues#3202]
### Is your feature request related to a problem? Please describe.

Or add animation clips support like in unity so that can be used for walking Animation which is also more performant than calculated movement animation 

### Describe the solution you'd like

Animation clips support like unity has 

### Describe alternatives you've considered

There is none I just want the npcs to have walking Animation again 

### Additional Context

Performance update because animations for walking is more performance

**Comment by Frooxius** [comment]
I don't understand what do you mean by "NPCs"? We currently do not have any sort of NPC support.

**Comment by alexderpyfox** [comment]
Not planned even wow
