### ISSUE TITLE
Input condition shows True after while loop ended

### ISSUE THREAD

**Issue by Zozokasu** [Yellow-Dog-Man/Resonite-Issues#321]
### Describe the bug?

When very light while loop (its condition input depends on Data Store Model and this value rewrites in loop iteration) ended, condition input shows True.

### To Reproduce

I confirmed the bug happens in this ProtoFlux at least.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/13605108/020f4c20-1af9-4ee4-aa3f-266514ecec7b)
resrec:///U-Zozokasu/R-906fa7c0-7604-414c-b58a-7f8e7be96ee4

This flux is:
_Each inpluse writes TEST+1%10, so the value TEST increases by 1 in each inpluse and when TEST was 9 it will be 0.
This caluclation runs when this while loop starts and each iterations run, and when TEST % 2 == 0, or TEST is even number, while loop will stop. So the value of TEST will transition 0, 2, 4, 6, 8, 0, 2..._

But in this case, condition shows True after while loop ended and TEST transition 1, 3, 5, 7, 9, 1...

However, at least add any nodes (Pulse Display and If node) after Write, it works correctly.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/13605108/f015c459-fda6-498a-a921-ff2774c7d023)

### Expected behavior

Both of those flux program output same results.

### Resonite Version Number

Beta 2023.10.18.449

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-5IMSSDD - 2023.10.18.449 - 2023-10-19 23_51_58.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13044538/DESKTOP-5IMSSDD.-.2023.10.18.449.-.2023-10-19.23_51_58.log)

### Reporters

kinoko_b
zozokasu

**Comment by shadowpanther** [comment]
Looks like a duplicate of #256

**Comment by Zozokasu** [comment]
> Looks like a duplicate of #256
Thank you for your notice, I confirmed.
I close this issue.
