### ISSUE TITLE
Dashboard Visibility Toggle for Cameras

### ISSUE THREAD

**Issue by Sukadia** [Yellow-Dog-Man/Resonite-Issues#3211]
### Is your feature request related to a problem? Please describe.

When using the First Person Steady Camera mode for streaming/recording, it does not show any of the dashboard menus. This makes it really hard to show people what I'm doing on a stream or similar.

### Describe the solution you'd like

A toggle that can enable the visibility of the dashboard for the camera would be the perfect solution.

### Describe alternatives you've considered

The only other way I know of is to not use the Steady Camera, which is a very cropped right eye view, not suitable for recording or streaming.

**Comment by JackTheFoxOtter** [comment]
That already exists! You can enable "show private UI" on the camera control panel! It's in one of the submenus on the right.

**Comment by Sukadia** [comment]
Thank you! It's definitely a bit hidden, but glad it's there. For anyone else; it's here:

![Image](https://github.com/user-attachments/assets/0a95a833-3793-4b11-8638-b911d4e2b8db)

**Comment by AmasterAmaster** [comment]
When this part of the ui gets reworked, hopfully some of these settings can be easier to see and use. :3
