### ISSUE TITLE
Locale issues when registering account

### ISSUE THREAD

**Issue by Armored-Dragon** [Yellow-Dog-Man/Resonite-Issues#322]
### Describe the bug?

When registering an account, should you use (what I assume to be is) a banned word, you will be prompted with broken locale.

### To Reproduce

1: Logout if logged in.
2: Type the word "Resonite" in the username anywhere.
3: Attempt to register.

### Expected behavior

It should tell you why the registration failed

### Screenshots

![localebug](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/43324896/e509b147-29b3-486c-9bb6-dd44ccef6ef1)

### Resonite Version Number

Beta 2023.10.18.449

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-8BJVNOL - 2023.10.18.449 - 2023-10-19 08_56_53.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13044841/DESKTOP-8BJVNOL.-.2023.10.18.449.-.2023-10-19.08_56_53.log)

### Reporters

Armored Dragon

**Comment by XDelta** [comment]
Looks like the current keys for this are `UserContainsBlockedTerms` and `Register.UserContainsBlockedTerms.Description` in https://github.com/Yellow-Dog-Man/Locale/blob/main/en.json#L469-L470

**Comment by ProbablePrime** [comment]
*dies* This was me

I'll grab it.
