### ISSUE TITLE
Add UploadJobs & RecordPreprocessJobs to online Metrix + Alerts when they rise

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#3222]
### Is your feature request related to a problem? Please describe.

Recently we had an issue with syncing breaking: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3210

We also currently track number of record preprocess jobs and asset upload jobs in our cloud, both of which are involved in the syncing process, but they are currently not visualized on `metrics.yellowdogman.com`, which decreases the visibility of issues arising with those.

### Describe the solution you'd like

Add the RecordPreprocesJobs & UploadJobs to `metrics.yellowdogman.com`, so we can more easily monitor them.

Additionally add alerts when they rise too high (I'm not sure what a good number is right now, since I haven't seen them evolve in time - I'd probably add the metrics first and then watch it a little), so we will know that something is up in case we have another incident.

### Describe alternatives you've considered

N/A

**Comment by ProbablePrime** [comment]
J4, has historic stats: https://dash.resonite.observer/d/f64edbf0-d33b-493f-81fe-201fa3cc817e/resonite-observer-dashboard?from=now-30d&to=now&timezone=browser&viewPanel=panel-19 we can use to structure alerting.

Here's Upload Jobs
![Image](https://github.com/user-attachments/assets/9ee07184-637a-4b78-8b1e-d0a667dc9da9)

Here's Record Preprocess Jobs
![Image](https://github.com/user-attachments/assets/85602aee-7c3c-42c6-b823-a2ae6766d627)

Im not seeing much actionable insight in the Upload Jobs graph.
Maybe the record jobs can have an alert though?

What do you think @Frooxius ?

**Comment by ProbablePrime** [comment]
Sure! Ill get it sorted.

**Comment by ProbablePrime** [comment]
I've added these https://metrics.yellowdogman.com/d/fcc45b49-dbff-43e3-8e80-58829195d0e6/resonite-metrics?orgId=1&viewPanel=28 is a direct link to the UploadJobs graph for example!

We'll tweak these as we go. I half expect them to alert within a day after me adding them :D
