### ISSUE TITLE
Expanded Gizmo selection/deselection options

### ISSUE THREAD

**Issue by ko-tengu** [Yellow-Dog-Man/Resonite-Issues#3231]
### Is your feature request related to a problem? Please describe.

Currently when you're working around other people it's very easy to disrupt and interfere with your fellow builders due to the nature of gizmos and selections in Resonite. Needing to deselect an item for visibility can only be done by forcibly deselecting all items for all users in a session, working in close proximity with another user results in overlapping gizmos and gizmo snapping to become disruptive quickly, and even things such as displaying collider volumes can be in the way of someone else trying to work.

### Describe the solution you'd like

I would like at minimum a way to deselect only objects I've personally selected, but I would also like ways to hide (but not strictly deselect) gizmos from other users when it becomes necessary. This is already a common enough feature in single user 3d development, with Blender and the Unity Editor both allowing you to toggle which gizmos are visible and having a simple toggle all function.

![Image](https://github.com/user-attachments/assets/aeb4504e-d043-4992-8e5b-2b9c730e5946)
![Image](https://github.com/user-attachments/assets/768e3396-fcd9-49f7-b4ac-308d34c6312a)

### Describe alternatives you've considered

There's a [mod that gives the ability to deselect only your own gizmos](https://github.com/badhaloninja/DeselectOwnGizmos/), but the other issues do not have an alternative.

### Additional Context

https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2806 is a somewhat related issue, but more focused on entirely hiding the work tools from other users.
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2731 is potentially related due to being a very common problem when working with others.

**Comment by ko-tengu** [comment]
An immediate example of ways that completely normal gizmo work can be disruptive is a desktop user choosing to do work on their avatar's head or an object that is targeting the user's head (such as some skybox systems). They stop being able to interact with anything until they Deselect All, which will also interrupt everyone else in the world.
![Image](https://github.com/user-attachments/assets/5721ff6b-cc72-47d3-b229-ee0e86700eb3)

Having a gizmo stuck between your eyes can be uncomfortable for a VR user also, making this a generally applicable issue.

**Comment by Frooxius** [comment]
We already have an official issue for this here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/599

Closing as duplicate.
