### ISSUE TITLE
Steam Listing for "Resonite" Does Not Come Up When Using "VR" Checkbox While Using "Advanced Filtering Options"

### ISSUE THREAD

**Issue by RabbitRetro** [Yellow-Dog-Man/Resonite-Issues#3234]
### Is your feature request related to a problem? Please describe.

When I sort my list of games in my Steam library, if I check off the "VR" keyword check box, a number of games appear (including VRChat), but not Resonite.![Image](https://github.com/user-attachments/assets/e5a4ed90-4b03-4947-89b1-d995f29deb1d)

### Describe the solution you'd like

Please make it so when we click that checkbox when we select the "Advanced Filtering Options", Resonite will appear in our Library of games filtered list.

### Describe alternatives you've considered

Can't think of any alternate solutions.

**Comment by RabbitRetro** [comment]
Ack. how the heck did I miss that?  I could have sworn it didn't work when I tried it the other day. Oh well. Sorry about that.

**Comment by RabbitRetro** [comment]
Oh wait, I see... it is visible in Windows 10 Steam, but not my Linux Mint Steam install.
![Image](https://github.com/user-attachments/assets/e743febb-1bc4-49c3-965d-49e7e9d30895)

**Comment by AwesomeTornado** [comment]
Are you sure this isn't a steam issue?

**Comment by shiftyscales** [comment]
As seen on the store page- Resonite is flagged as VR supported- so that sounds like it likely is a Steam issue specifically, @RabbitRetro.

![Image](https://github.com/user-attachments/assets/727110a1-c97f-4bcf-9d55-48703779e4ab)

**Comment by ProbablePrime** [comment]
Related/duplicate: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/583
