### ISSUE TITLE
Simple performance profiler in the inspector

### ISSUE THREAD

**Issue by tractorbeam0** [Yellow-Dog-Man/Resonite-Issues#3243]
### Is your feature request related to a problem? Please describe.

I've noticed in more popular worlds where creation is encouraged (such as the creator jam), the host spends the vast majority of their time cleaning up, looking for whatever might be lagging up the instance (emphasis on 'might') and removing it, checking back to the fps counter to see if it made a difference, looking elsewhere, etc. It's an incredibly tedious process.

### Describe the solution you'd like

What could solve this problem and generally be a useful addition is placing the processing time for an object and its children next to it in the inspector's object list.

### Describe alternatives you've considered

As far as I've considered, there are no other solutions that would take such little effort to implement and have as great an impact on pretty much anybody who uses the inspector.

### Additional Context

Of course this may have a performance impact in and of itself (assuming Resonite doesn't already process these in the background), but that's nothing that can't be solved by making it toggleable.

### Requesters

tractorbeam

**Comment by Frooxius** [comment]
Thank you for making the issue. We already have one for this kind of tool here: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/233

I'm going to close this one as duplicate.
