### ISSUE TITLE
projection360 render first button

### ISSUE THREAD

**Issue by Redd56** [Yellow-Dog-Man/Resonite-Issues#3253]
### Is your feature request related to a problem? Please describe.

When making a skybox there are two routes you can go, using the projection360 and "using" the projection 360

when actualy using it you set the skybox component to use the projection 360 as the actual skybox material itself, this comes with the upside of it being a proper skybox that is uneffected by near or far clipping, and not drawing over terraign ever. but the downside of whatever the median color of the skybox is thats now the background (ambient) light level and color

when "using" the projection 360 you set the skybox component to something useless, say a gradient skybox material set to black, then set up a large sphere mesh with the projection 360 on it. the upsides are that your world isnt infiltraded by skybox ambient lighting. the downsides are that a: that mesh is only so big, there can be instances where objects exit it, and b: you can exit this sphere; some people (like me) get arround this by smacking it to a massive size  (have a radius about 1.1x the worlds size so nothing ever exits) and having it follow the user with a positionAtUser set to local user. but that only works so well, if you fly away from the world or fall out of it things dissapear behind it. or if your too big or small near and far clipping occur

### Describe the solution you'd like

theres two solutions i see idk which is easier: 
A: a single boolean toggle on the projection 360 material to set it to be the first material in the render queue other than the skybox and let everything draw over it other than the skybox (aka a skybox mode button)

b: a boolean toggle in the skybox component to make it ignore the color of the inputed skybox mat (projection360 included) and set ambient color to none

### Describe alternatives you've considered

messing with the render queue, using the projection 360 as a skybox (ambient light is anoying), using current solutions that are not quite on par with what i would want

### Additional Context

this issue has been entirely rewritten from the ground up as new information has been brought to my attention (cubemaps) 

### Requesters

Redd56

**Comment by shiftyscales** [comment]
What have you tried to resolve this issue so far, @Redd56? It should be possible to get the outcome you desire if you modify the material properties of each skybox so they are properly sorted / ordered in the render queue.

**Comment by Frooxius** [comment]
This isn't necessarily as simple as making a toggle at material level, because materials don't control near/far cliping

One thing you could try is put them in very early render queue, say like 1000 and have them ignore the ZTest (you can set that to Always) and do not write to ZBuffer.

**Comment by Redd56** [comment]
unlit doesnt have ztest control

**Comment by shiftyscales** [comment]
You should be using Projection360 instead of Unlit for a skybox, @Redd56.

**Comment by Redd56** [comment]
> What have you tried to resolve this issue so far, [@Redd56](https://github.com/Redd56)? It should be possible to get the outcome you desire if you modify the material properties of each skybox so they are properly sorted / ordered in the render queue.

didnt see this reply till just now sorry, ive tried fiddling with the render queue but it doesnt seem to effect anythign but uix. or if they are very very high (i mean about 100k range) then they start rendering over everything cause high priority in rendering queue.

**Comment by Redd56** [comment]
just realized skybox can take in a projection360. it does however effect ambient light

**Comment by shiftyscales** [comment]
Yes, but if you use the Projection360 for the "fake" skybox as well you can get around that.

> on higher res ones yes but due to my skybox being stylized (low res and point filtering) it causes major pinching (see image attached for example)

Did you try creating a cubemap using the cubemap creator (Dev Tool > Create New > Editor > Cubemap Creator) and using that in the Projection360?

![Image](https://github.com/user-attachments/assets/c8b01d9e-518b-4b58-98ce-5dabcf21cedd)

As the name implies- a cube map maps the inputted texture in a cube shape which can then be used in the Projection360 material by placing it in the `Cubemap` field. You should not need to surround the world in a cube yourself directly (except as mentioned- if you wish to utilize a 'fake' skybox so it does not influence global illumination in the world).

As Frooxius mentioned in his initial response however- your proposal does not seem suitable / is not a simple / trivial thing to implement- so it would be best to utilize existing mechanisms to achieve your desired result.

If you need further help troubleshooting / debugging your creations, I would recommend doing so in our Discord, or seeking out the help of a user on-platform, @Redd56.

**Comment by Redd56** [comment]
did not know that was a thing, will try and close if sufficent

**Comment by Redd56** [comment]
well ive managed to make the cubemap work with projection 360, quite a handy thing, thank you for letting me know
but still wish there was a way to have projection 360 render behind every single object, but ill modify the issue to reflect this need directly instead of the broader term its on now as my need for unlit is now gone with the discovery of "cubemap my beloved" ™️ © redd 2024 inc llc corp co ltd ov uhmarikah

**Comment by Redd56** [comment]
updated.
