### ISSUE TITLE
[PhotonDust] Disabling A Slot That Has A ``ParticleSystem`` Component Doesn't Unrender Particles

### ISSUE THREAD

**Issue by AlanMoonbase** [Yellow-Dog-Man/Resonite-Issues#3260]
### Describe the bug?

When disabling a slot that contains a ``ParticleSystem`` component, the renderer doesn't unrender the particles.

### To Reproduce

1. Create A Particle System On The ``prerelease`` Version Of Resonite
2. Disable The Created Parent Slot
3. Observe The Particles Stay In Place Instead Of Disabling

### Expected behavior

The particles to disappear upon simulation end.

### Screenshots

![Image](https://github.com/user-attachments/assets/efd51043-9c51-483e-aee3-490804f0bfae)
![Image](https://github.com/user-attachments/assets/d2acb87a-6610-4c1a-919f-f1ab902d3c3f)

### Resonite Version Number

2024.12.4.1182

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[DESKTOP-918A6QV - 2024.12.4.1182 - 2024-12-04 12_58_24.log](https://github.com/user-attachments/files/18014183/DESKTOP-918A6QV.-.2024.12.4.1182.-.2024-12-04.12_58_24.log)

### Additional Context

This could be intended behavior for the new particles but I'm unsure.

### Reporters

Moonbase__ (moonbase__)

**Comment by Frooxius** [comment]
Fixed this in 2024.12.5.546, thanks for report!
