### ISSUE TITLE
Photon Dust - Moving a component world crash

### ISSUE THREAD

**Issue by RueShejn** [Yellow-Dog-Man/Resonite-Issues#3261]
### Describe the bug?

when moving a component that is in the modules list crashes the user out of the world

### To Reproduce

Grab a component that is listed in modules from a default particle systems and try to move it to another slot

### Expected behavior

Moves component without crashing

### Resonite Version Number

Beta 2024.12.4.1182

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-L6KVB13 - 2024.12.4.1182 - 2024-12-04 14_31_09.log](https://github.com/user-attachments/files/18014315/DESKTOP-L6KVB13.-.2024.12.4.1182.-.2024-12-04.14_31_09.log)

**Comment by ModernBalloonie** [comment]
Having this too.

**Comment by ProbablePrime** [comment]
> Having this too.

Reminder that if you have nothing additional to add, then please just thumbs up it. Commenting "me too" reduces our ability to respond to issues as we have to filter through comments that do not have additional details.

**Comment by Frooxius** [comment]
Fixed this in 2024.12.5.546, thanks for report!
