### ISSUE TITLE
[PhotonDust] Skinned Mesh Emitters do not seem to emit even when a mesh is set to Readable

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#3263]
### Describe the bug?

While testing the prerelease today I discovered that I was unable to make the `SkinnedMeshEmitter` ever emit particles, and no matter what I changed it would not emit, even after setting the mesh to readable.

### To Reproduce

Remove the existing Emitter from a default ParticleSystem and add a Skinned Mesh Emitter, Add the particle system and set the mesh on the Skinned Mesh Renderer you want to emit from to Readable, then observe that no particles are generated even by the particle system

### Expected behavior

Particles emit in the shape of my mesh

### Resonite Version Number

Beta 2024.12.4.1182

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[Skinned Mesh Emitter Test.txt](https://github.com/user-attachments/files/18014850/Skinned.Mesh.Emitter.Test.txt)

### Additional Context

I figured that while this isn't phase 2 since its strictly a photondust bug with new emitters it would be worth reporting now

### Reporters

venport/dustysprinkles

**Comment by Dusty-Sprinkles** [comment]
Never mind- it just seems like you need to keep the particle system under the slot of the mesh

also readable isnt required

**Comment by sjsanjsrh** [comment]
![Image](https://github.com/user-attachments/assets/baa19994-27ae-4712-b6a2-3437d2062b74)
I'm still having a bit of trouble with not emitting, but I'm sure it's something simple that I can fix. How should I go about doing that?

**Comment by Dusty-Sprinkles** [comment]
for me I had to put the particle system directly under the mesh slot in whatever I was working on, and make sure it was the same scale as the mesh (since it can get kinda big or small if its not consistent)
