### ISSUE TITLE
[Photon Dust] Adding a Module of a kind that is already on the Particle Style crashes the editor from the world, even if it's a replacement.

### ISSUE THREAD

**Issue by NukiRaccoon** [Yellow-Dog-Man/Resonite-Issues#3264]
### Describe the issue.

Several others have been talking about this one, but I have made it happen multiple times.

I am not sure of the exact set of steps to do this, but adding a module to the Particle Style of the same kind as one that is already on there causes the user to crash from the world they tried it in, and can potentially crash the entire world.

### To Reproduce

- Pull Out DevTip
- Create Two New Particle Systems
- Drag and Drop one of the Modules from one to the other, attempting to replace

### Expected behavior

This is such a common action, it should in no way be crashing the world.  If there is an issue, it should fail gracefully, and if there are two of the same kind (not even the case here) it should not do that.

### Resonite Version Number

2024.12.4.1182

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MSI - 2024.12.4.1182 - 2024-12-04 17_47_55.log](https://github.com/user-attachments/files/18015026/MSI.-.2024.12.4.1182.-.2024-12-04.17_47_55.log)

### Reporters

Nuki, others can chime in

**Comment by epicEaston197** [comment]
Hmmm?
I added two modules of the same Kind and I had nothing happen except the two effects stacking atop of one another this was specifically with radial force so there might be something special with that

**Comment by Frooxius** [comment]
Fixed this in 2024.12.5.546, thanks for report!
