### ISSUE TITLE
Photon Dust - Adding two of the same Initliaizers to a ParticleStyle crashes world

### ISSUE THREAD

**Issue by decoybird** [Yellow-Dog-Man/Resonite-Issues#3265]
### Describe the issue.

When adding two ColorConstantInitializer components to the ParticleStyle, the world crashes.
This could be related or similar to issue #3264 

### To Reproduce

- Create two ColorConstantInitializer components
- Add both to the Modules list in the ParticleStyle component

### Expected behavior

If component conflicts, remove one or fail to add.

### Screenshots

https://github.com/user-attachments/assets/1016ba4c-c823-4f11-977a-2aa45669302b

### Resonite Version Number

2024.12.4.1182

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive, Desktop

### Log Files

[URAGAAN - 2024.12.4.1182 - 2024-12-05 03_14_48.log](https://github.com/user-attachments/files/18016023/URAGAAN.-.2024.12.4.1182.-.2024-12-05.03_14_48.log)

**Comment by orange3134** [comment]
Adding GravityForce and LinearForce at the same time causes a crash.

[MENTAIKO - 2024.12.4.1182 - 2024-12-05 11_28_42.log](https://github.com/user-attachments/files/18016489/MENTAIKO.-.2024.12.4.1182.-.2024-12-05.11_28_42.log)

**Comment by Frooxius** [comment]
Fixed this in 2024.12.5.546, thanks for report!
