### ISSUE TITLE
Photon Dust - Moving a Module component attached to a ParticleStyle component causes crash.

### ISSUE THREAD

**Issue by Zozokasu** [Yellow-Dog-Man/Resonite-Issues#3268]
### Describe the issue.

Moving a module component (SomethingInitializer, SomethingModule, etc.)  already attached to a ParticleStyle component causes world crashing.

If the person who moved the component was not the session host, only the person who moved it is disconnected from the session.

### To Reproduce

1. Create New... -> create Particle System
2. Move a Initilizer or Module component to a other slot
3. World crashes

### Expected behavior

a component will be moved.

### Screenshots

https://github.com/user-attachments/assets/ef8d580c-6423-4881-b2a7-8e4f876df97f

### Resonite Version Number

Beta 2024.12.4.1182

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[ZOZOKASU - 2024.12.4.1182 - 2024-12-05 17_16_39.log](https://github.com/user-attachments/files/18019814/ZOZOKASU.-.2024.12.4.1182.-.2024-12-05.17_16_39.log)

### Reporters

Zozokasu

**Comment by Frooxius** [comment]
Fixed this in 2024.12.5.546, thanks for report!
