### ISSUE TITLE
Configure particle systems in a specific order, the new particle systems will not work.

### ISSUE THREAD

**Issue by mirpasec** [Yellow-Dog-Man/Resonite-Issues#3271]
### Describe the issue.

When I place and connect components in a certain order, the ParticleSystem seems to stop working.

### To Reproduce

Fail case
1. Add "ParticleSystem"
2. Add "ParticleStyle"
3. Add "BillboardParticleRenderer"
4. Mapping ParticleStyle to ParticleSystem.Style
5. Mapping BillboardParticleRenderer to ParticleStyle.Renderer
....
n. Particle system not work.

### Expected behavior

Until the particle configuration is complete, ensure that the ParticleSystem's behavior is valid (Particles: 0 <- this value blinks randomly)

### Screenshots

![Image](https://github.com/user-attachments/assets/29095547-3714-4513-8db7-5cf947b01ec0)

### Resonite Version Number

2024.12.5.546

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[EARTH - 2024.12.5.546 - 2024-12-06 00_18_22.log](https://github.com/user-attachments/files/18025519/EARTH.-.2024.12.5.546.-.2024-12-06.00_18_22.log)

### Additional Context

It looks like when linking references, an error occurs if a particular item is not previously referenced.

**Comment by Frooxius** [comment]
This is fixed in 2024.12.5.1194, thanks for reporting!
