### ISSUE TITLE
Adding AngularVelocityInitializer will cause particles to stop working

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#3272]
### Describe the issue.

Adding the AngularVelocityInitializer will cause the particles to stop working.
Duplicating it will make it work.

### To Reproduce

1. Create a ParticleSystem with DevTool.
1. Attach RotationSimulatorModule and AnglarVelocityConstantInitializer.
1. Add them to Modules of ParticleStyle.
1. Particles will stop working.

### Expected behavior

Particles do not stop

### Screenshots

https://youtu.be/wxgx8Q_n9lE

### Resonite Version Number

Beta 2024.12.5.546

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MENTAIKO - 2024.12.5.546 - 2024-12-06 00_25_13.log](https://github.com/user-attachments/files/18025648/MENTAIKO.-.2024.12.5.546.-.2024-12-06.00_25_13.log)

### Additional Context

This occurs with all four components listed below.

- AngularVelocity3DConstantInitializer
- AngularVelocity3DRangeInitializer
- AngularVelocityConstantInitializer
- AngularVelocityRangeInitializer

### Reporters

orange3134

**Comment by Frooxius** [comment]
Fixed this in 2024.12.5.1194, thanks for report!
