### ISSUE TITLE
Headless client does not update it's world status properly

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Yellow-Dog-Man/Resonite-Issues#3273]
### Describe the bug?

When using the headless it does not always show all worlds that are unhidden.

### To Reproduce

Not sure. I have yet to figure out exactly why.

### Expected behavior

Non-Hidden worlds should all show up on the headless account when browsing to it.

### Screenshots

![Image](https://github.com/user-attachments/assets/0a08dd78-96b2-41a3-949e-4a64bf4c2ac3)

### Resonite Version Number

Beta 2024.12.2.1188

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

I will provide these in private only. Message me on discord please: `3x1t_5tyl3`

But TL;DR some of the sessions are not sending "BroadcastSession" status'.

### Additional Context

This occurs also on the client, but far less frequently (assumedly due to the lesser amount of restarts/sessions starts) though I'm speculating.

EDIT: There's ways to ""circumvent"" this issue by just sitting in the world for a minute. But that's not a solution.

### Reporters

3x1t_5tyl3

**Comment by shiftyscales** [comment]
This sounds similar to #3325. As a sanity check, could you sign in to the account hosting the headlesses and ensure that it is not currently set to invisible as its default status / remembered status, @3x1t-5tyl3?

**Comment by shiftyscales** [comment]
Well we will still need log files for this. If there is any information you need to scrub before you feel comfortable submitting them- please redact as much as desired, but as little as possible.

Reaching out to you in DM is not a scalable solution.

**Comment by shiftyscales** [comment]
What are your world browser filter properties set to? If the sessions are visible in the contacts tab, they should be in the world browser as well if the world browser is set accordingly to not filter out those sessions.

**Comment by 3x1t-5tyl3** [comment]
> What are your world browser filter properties set to? If the sessions are visible in the contacts tab, they should be in the world browser as well if the world browser is set accordingly to not filter out those sessions.

Default.

Most of the redactions are IP Adresses, brson paths, connections, machineid's and the session id's, as they are permanent. If anythign is required of those let me know. But I refuse to just put those on the internet at random.

But I do see in the logs (see attached log) that it just doesn't even broadcast the session.

There's a total of 5 sessions, 1 hidden contacts, 2 contacts, 1 contacts+ and 1 public

the contacts+ session is not broadcast. It is also not hidden.
This is seemingly already know and *IS* broadcast as soon as there's at-least 1 person in the session. Until then the session is *not* broadcast.
[logs-redacted.txt](https://github.com/user-attachments/files/18081556/logs-redacted.txt)
