### ISSUE TITLE
PhotonDust - Particles don't reflect local transform

### ISSUE THREAD

**Issue by Zozokasu** [Yellow-Dog-Man/Resonite-Issues#3277]
### Describe the issue.

Particle transform will not change even if a slot is assigned to `LocalSpace` in ParticleSystem and the slot's scale has been changed.

### To Reproduce

1. create particle system
2. assign a slot to LocalSpace in ParticleSystem
3. change scale of the slot assigned to LocalSpace

### Expected behavior

Scale of particles (, ribbons, and trails) will change.

### Screenshots

https://github.com/user-attachments/assets/9f1ad995-55f2-42c7-a674-825bdeb0b5e4

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[ZOZOKASU - 2024.12.5.1194 - 2024-12-06 06_05_24.log](https://github.com/user-attachments/files/18029815/ZOZOKASU.-.2024.12.5.1194.-.2024-12-06.06_05_24.log)

### Reporters

zozokasu

**Comment by badhaloninja** [comment]
I ran into this problem in my home world, I have made a demo of this behavior, simplifying the issue in my home world

Here is a demo in the release build
https://github.com/user-attachments/assets/d810069b-dbf9-4057-b5c1-10f110b05d93


And here is a demo in the Prerelease build
https://github.com/user-attachments/assets/6e9143b4-ae76-49d1-b4bc-1613c76ad70b


It seems PhotonDust inversely compensates for the scale of the simulation space or something
Making the particles them selves to go smaller, the emitter positions being wrong, and the particles staying in the same location


Here is a link to the folder containing this demo
`resrec:///U-badhaloninja/R-9596A737636F542F6D23183DFE48F8F8F653C7ADA545F22EA88192C168CBB917`

And here is the object directly (Object recs currently spawn at 0,0,0 when pasted for some reason)
`resrec:///U-badhaloninja/R-aa50b286-17fd-4276-9ad4-957069520ec0`

**Comment by shiftyscales** [comment]
> Edit: hmm those videos aren't embedding properly it seems

Yeah- weird quirk with GitHub- for some reason it wants a line break above videos to embed properly. I've updated your post to add a line break so they embed properly.

Thanks for including replication objects / footage. :)

**Comment by Frooxius** [comment]
Thank you for report, this has been fixed in 2024.12.11.501!
