### ISSUE TITLE
Add the Controls Facet to Resonite Essentials

### ISSUE THREAD

**Issue by PointerOffset** [Yellow-Dog-Man/Resonite-Issues#328]
### Describe the bug?

At the moment there is no easy way to access the Controls facet that displays a list of control mappings to users based on their current headset (or lack thereof in screen mode). With the wiki currently unpublished this makes it very difficult for users to discover some basic controls functions that aren't covered in the tutorial. A primary example being the Ctrl+Click focus mode for desktop users. I've seen multiple users not realize this is even a feature, leading them to believe they must use FPS controls and aiming to work on worlds and ProtoFlux.

### To Reproduce

1. Start Resonite
2. Access the Inventory tab on your dashboard
3. Access the `Resonite Essentials` folder
4. Explore subfolders. None of the folders contain the Controls facet.

### Expected behavior

The `Resonite Essentials` folder should contain the Controls facet either:

- At the root along side the camera and mirror. This is a very generally useful facet and I would expect its utility to be on-par with these other items.
- In `/Resonite Essentials/Facets` or `/Resonite Essentials/Facets/Templates` along side all of the other facets.

It also may be worth considering finding a place for this facet to live in the default cloud home. So future new users can be easily exposed to this information and can easily discover it when they are ready to explore more advanced controls.

### Screenshots

An image of the facet in question:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/61102129/c9d7ae76-dacf-4f6f-ba10-b36a7371df6f)

### Additional Context

I understand the core of this issue is not inherently due to this facet being missing from the Resonite Essentials folder. However, improved documentation and additional content that might teach users these controls is a longer-term ask that I already expect the Content Team to be considering. This is a request to help fill the gap in the meantime while we wait for a wiki and any additional content to teach users more complex interactions.

### Reporters

- Discord: Spex, GitHub: @PointerOffset
- Discord: Eai, GitHub @eai04191

**Comment by AegisTheWolf** [comment]
There is a facet now within the Facets folder of the Essentials. It is a version we worked on that shows the user's current control layout when it is in their local space on their dash. We will make another one that resembles something like what is posted above to make it desktop accessible since there isn't a way to add facets to dash in desktop. (I do not recall any of us on content making something like that yet off the top of my head).

**Comment by AegisTheWolf** [comment]
![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/65252793/e7582122-6e5d-4e81-a92e-7c7573a0308b)

There is now a UIX panel basically the same as shown in the original screenshot above in the essentials folder thanks to @Ryuvi
