### ISSUE TITLE
Legacy Particle Systems converted to PhotonDust. Inconsistencies, and performance.

### ISSUE THREAD

**Issue by VirgilCore** [Yellow-Dog-Man/Resonite-Issues#3280]
### Describe the issue.

Particle emitters after conversion to Photon dust seem to be either positioned or scaled incorrectly compared to the original legacy counterparts. As well as a large amount of particles in a world being converted resulting in lower performance than the legacy particles. Additionally, trails seem to be calculated/scaled incorrectly (reported in #3277 ). being either larger or longer than the legacy ones. (also i just remembered as well that the forces applied to some particles are less than the legacy ones, so they travel slower.)

[Attached is a video with all the above shown on some of my items and one of my worlds.](https://www.youtube.com/watch?v=HuL7621SzhY)

### To Reproduce

For the items shown in the video, They can be spawned from this folder: resrec:///U-Virgil/R-C52BF501589D3AB13A3E30D9941214AC31A2A8D240993E835BE046071A4F0D50
For the world shown in the video, That can be found here: resrec:///U-Virgil/R-d798fa70-8438-465f-974d-7ee5619e77f4

### Expected behavior

Emitters should be in the same place as they used to be, and the scale of the spaces particle systems are in should be respected properly as in the legacy system. Additionally, these performance dips should not be happening.

### Screenshots

![Image](https://github.com/user-attachments/assets/6d8d7c73-0270-4877-8dc7-0ae760b5944b)
![Image](https://github.com/user-attachments/assets/df0340cd-8b1b-406b-8f9d-38fc8875306e)
![Image](https://github.com/user-attachments/assets/339868c5-4427-4121-aaba-d838c7ef4a3b)

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-249E6C2 - 2024.12.5.1194 - 2024-12-05 15_13_55.log](https://github.com/user-attachments/files/18029990/DESKTOP-249E6C2.-.2024.12.5.1194.-.2024-12-05.15_13_55.log)

### Reporters

Resonite: anquietas-sys / Discord: anquietas_sys

**Comment by Frooxius** [comment]
It sounds like you're talking about lots of different issues at the same time.

Can you split this into individual issues so we can focus on each one on its own please? We generally request not to combine multiple issues into a single GitHub issue as that makes it much harder for us to work through them.

Right now it's difficult for me to tell what all the issues even are from this.

**Comment by VirgilCore** [comment]
I dont have the time today to split this issue, or the video. I have other things i have to take care of today.

**Comment by Frooxius** [comment]
It doesn't have to be today, but we probably won't work on this until it is.

**Comment by VirgilCore** [comment]
![Image](https://github.com/user-attachments/assets/99d429e4-4564-47b9-96df-9fff8a3e0969)
Line emitters are now even more offset and particles are not emitting light anymore.

Version: Beta 2024.12.10.538

**Comment by VirgilCore** [comment]
![Image](https://github.com/user-attachments/assets/f3ccda55-3ac6-479b-8340-7e61048f103a)
Trails seem to still be too bright.

**Comment by Frooxius** [comment]
Like I requested above, please split this into individual issues.

**Comment by VirgilCore** [comment]
Sorry for continuing to clutter but at this point this issue is more for my own personal tracking than anything, since easton was making seperate issues for me. 
Version : Beta 2024.12.11.501
![Image](https://github.com/user-attachments/assets/9c86b4ea-b160-4487-ac25-8e8e8fc03c65)
The line emitters are fixed now, They look almost identical now to the old particles, note the ribbons are a little different but theres already an issue up for that. along with the lights also not working, but there's also an issue for that too already.
