### ISSUE TITLE
[photon dust] Converted content has incorrect gravity

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#3281]
### Describe the issue.

Converted content has incorrect gravity applied resulting in falling much slower than usual

### To Reproduce

1. Download the replication item below
2. At first Import the package without converting it to Photon dust
3. You'll notice that the particles have gravity that drag them down (Make sure to look up)
4. Import the package again except convert it to Photon dust
5. You'll notice that the particles are moving significantly slower

### Replication item

**Warning The replication item contains a particle system that's not very good for performance if it spawned out for too long your game will screeched to a grinding halt so make sure you only spawn it out for the necessary amount of time to replicate the issue**
[Gravity issue.zip](https://github.com/user-attachments/files/18031159/Gravity.issue.zip)

### Expected behavior

Gravity should be consistent between the legacy and new particle system

### Screenshots

https://github.com/user-attachments/assets/04857562-59d4-4227-a008-ae68d0ed1b13

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[EPICEASTON197 - 2024.12.5.1194 - 2024-12-05 17_03_23.log](https://github.com/user-attachments/files/18030212/EPICEASTON197.-.2024.12.5.1194.-.2024-12-05.17_03_23.log)

### Reporters

@epicEaston197

**Comment by esnya** [comment]
I got the same issue on 2024.12.5.1194/Windows/Desktop.

The gravity of the new particles seems to be about 10 times weaker than the legacy particles. (or is it 9.81?)

 ![Image](https://github.com/user-attachments/assets/afdbf267-fedb-496b-b653-99fb0d8409b2)

**Comment by Fukuro99** [comment]
I noticed the same thing with the items I converted.
The left is before conversion, and the right is after conversion.
The Gravity value for both was 0.1, but the gravity after conversion seemed much weaker than before.

https://github.com/user-attachments/assets/378fa767-3966-40e6-bf25-b24912c0f9de

**Comment by epicEaston197** [comment]
@esnya @Fukuro99 Thank you for the additional information

**Comment by 5H4D0W-X** [comment]
This looks like gravity used to be a multiplier of earth gravity (1 is earth) while now it's the actual acceleration (9.81 is earth), meaning conversion results in about a tenth of the intended gravity. That's just a guess though

**Comment by epicEaston197** [comment]
> This looks like gravity used to be a multiplier of earth gravity (1 is earth) while now it's the actual acceleration (9.81 is earth), meaning conversion results in about a tenth of the intended gravity. That's just a guess though

Huh that actually makes a lot of sense as that's also the default gravity for the locomotion module so it would make sense for the gravity to be consistent with the rest of [Froox](https://github.com/Frooxius) engine

**Comment by epicEaston197** [comment]
> This looks like gravity used to be a multiplier of earth gravity (1 is earth) while now it's the actual acceleration (9.81 is earth), meaning conversion results in about a tenth of the intended gravity. That's just a guess though

I took the gravity and times did by 9.81 And the particles started falling correctly

**Comment by Frooxius** [comment]
This is fixed in 2024.12.10.523! Thanks for report!
