### ISSUE TITLE
DirectionMode on BoxEmitter false conversion "BoxEmitter+LegacyDirectionConverter"

### ISSUE THREAD

**Issue by Nordwig** [Yellow-Dog-Man/Resonite-Issues#3282]
### Describe the issue.

When the Iteam " resrec:///U-Nordwick/R-b9b71cbd-b659-41eb-812c-fd9fb230d032 " by Joshtiger is converted to PhotonDust the DirectionMode is set to ClosestFaceNormal, resulting in different behavior than in LegacyBoxEmitter. Changing the DirectionMode to "fixed" is fixing the issue.

The conversion uses the "AlwaysForceDirection" as DirectionMode. 

It seems the LegacyBoxEmitter is ignoring the "AlwaysForceDirection" setting (I cant see changes when toggling) and behaves like PhotonDust in "fixed" DirectionMode.

Converting to default "True" on the "BoxEmitter+LegacyDirectionConverter" is maybe a solution. 

### To Reproduce

1. Spawn Iteam " resrec:///U-Nordwick/R-b9b71cbd-b659-41eb-812c-fd9fb230d032 " without conversion.
2. Move the box around the particles have a velocity in the vector of movement. 
3. Spawn Iteam " resrec:///U-Nordwick/R-b9b71cbd-b659-41eb-812c-fd9fb230d032 " with conversion.
4. Move the Box around the Particles spawn in a circle around the box without directional movement.
5. Open the Particle System and change the Value on the BoxEmitter+LegacyDirectionConverter to true
6. now the Particles behave like in Legacy.

### Expected behavior

Converting DirectionMode on BoxEmitter to default "True" ( "BoxEmitter+LegacyDirectionConverter" Value ) 

### Resonite Version Number

2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[DESKTOP-HU8JOJP - 2024.12.5.1194 - 2024-12-05 22_38_33.log](https://github.com/user-attachments/files/18030285/DESKTOP-HU8JOJP.-.2024.12.5.1194.-.2024-12-05.22_38_33.log)

### Additional Context

The Iteam  ~~"resrec:///U-Nordwick/R-571a71f3-59b7-4c61-8727-34443e87c332 "~~  " resrec:///U-Nordwick/R-6f4e410d-e9d0-4fb5-a2d3-14574f34f2d5 " is saved with LegacyBoxEmitter "AlwaysForceDirection" = True 
now the conversion works without a problem. There is no differens in Legacy System (messed up the saving ( sorry ) updatet iteam now)

### Reporters

Jackson, Nordwick

**Comment by Nordwig** [comment]
Sorry had Mods active...

Retestet without modes same behavior new LogFile below.

[DESKTOP-HU8JOJP - 2024.12.5.1194 - 2024-12-05 23_22_21.log](https://github.com/user-attachments/files/18030454/DESKTOP-HU8JOJP.-.2024.12.5.1194.-.2024-12-05.23_22_21.log)

**Comment by Frooxius** [comment]
I can't spawn any of the resrec:/// items. Are they set to public?

**Comment by Nordwig** [comment]
@Frooxius Updated the resrec:/// Links in the original post (sorry again)

**Comment by Frooxius** [comment]
Thanks! I've checked the item and it seems it's already been fixed with the other updates! I'm gonna close this.
