### ISSUE TITLE
[Photon dust] Converted Particle sprites don't go to the last index

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#3283]
### Describe the issue.

It appears that photon dust sprites do not go to the last index

### To Reproduce

1. Import the package below (Without converting it to Photon dust)
2. You'll notice **_the hundreds of eyes around you_** can open their eyes fully
3. Now import the same package but convert it to photon dust
4. You'll notice that the eyes around you don't open fully

### Replication item
[もぺもぺほう - Layer Sprite Error .zip](https://github.com/user-attachments/files/18030401/-.Layer.Sprite.Error.zip)

### Expected behavior

The sprites on the particle system should be able to go through their full index and be consistent with the legacy particle system

### Screenshots

https://github.com/user-attachments/assets/19779d68-3b85-492d-bf54-86552d17197b

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[EPICEASTON197 - 2024.12.5.1194 - 2024-12-05 17_26_01.log](https://github.com/user-attachments/files/18030477/EPICEASTON197.-.2024.12.5.1194.-.2024-12-05.17_26_01.log)

### Reporters

@epicEaston197

**Comment by Frooxius** [comment]
Fixed this in 2024.12.10.1414, thanks for report!
