### ISSUE TITLE
Photon dust doesnt align local space particle rotations correctly.

### ISSUE THREAD

**Issue by AegisTheWolf** [Yellow-Dog-Man/Resonite-Issues#3284]
### Describe the issue.

Either im doing it wrong or this is a bug with the alignment of particles, this will break certain converted particle systems as some particles respect the rotation space of the object its parented under if its set to either the local space or its parent space.

### To Reproduce

When rotating the particle system as its emitting it keeps its alignment but on the X axis being rotated but scales itself down when its rotated on the Y axis and doesnt rotate at all on the Z axis.

I will make an example particle system (photon dust) and legacy one side by side and provide video of it below.

To replicate, simply make a particle that is easy to tell its facing direction, make it face the direction of the billboard to "local", set force direction to the Z axis of 1 for example on the emitter with no random direction, see it move in global space then set the space to local and rotate the system using a dev tool and see the odd behavior.

### Expected behavior

What is expected is the particles to follow its local space direction properly, this is useful for making particle systems that are attached to moving objects without worrying about the particles leaving a trail behind them or not present when it moves very fast.

### Screenshots

![Image](https://github.com/user-attachments/assets/1cc34358-4cd2-4218-acdf-dd1b119f812e)
![Image](https://github.com/user-attachments/assets/26ed90a1-59c7-4e5d-adfa-9289d979c785)
![Image](https://github.com/user-attachments/assets/fc55a972-f94f-4c5a-a51b-8ccb5bfbe2d1)
![Image](https://github.com/user-attachments/assets/a3d2f688-f97a-4156-bc6e-e165ffb37efd)
![Image](https://github.com/user-attachments/assets/6e34394f-4e4a-4a10-974d-345330e5c206)
![Image](https://github.com/user-attachments/assets/bd7c457d-aa62-47ea-bc9f-9d4da9cd8a3f)

### Resonite Version Number

Beta 2024.12.5.546

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[DESKTOP-SH3F0U4 - 2024.12.5.546 - 2024-12-05 16_06_23.log](https://github.com/user-attachments/files/18030530/DESKTOP-SH3F0U4.-.2024.12.5.546.-.2024-12-05.16_06_23.log)

### Additional Context

If this is something that can be fixed via a missing component that i forgot to add id like to know in case when i look for it when converting old legacy particle systems that do this.

### Reporters

Aegis_Wolf

**Comment by Frooxius** [comment]
Do you have any items that are broken with this behavior?

**Comment by AegisTheWolf** [comment]
> Do you have any items that are broken with this behavior?

Ill test some conversion cases that do this and attach them here

**Comment by AegisTheWolf** [comment]
![Image](https://github.com/user-attachments/assets/53aeba92-814e-4ecc-8b24-35a98c246363)
you made me also think about saving the existing setup into my inventory of the old legacy one and spawn it out when i have the debug conversion switch on to see if that simple setup works from conversion....nope still has the weird rotations.

**Comment by AegisTheWolf** [comment]
ill get more examples with this gathered in a bit while i have the conversion on

**Comment by AegisTheWolf** [comment]
![Image](https://github.com/user-attachments/assets/40cacae8-e815-46dc-9507-b39c23104f69)
![Image](https://github.com/user-attachments/assets/4b272ce7-b029-4cfc-8b59-19b96f9dc83f)
![Image](https://github.com/user-attachments/assets/11317d67-291e-4702-94c0-9a01253cc23d)
definately consistent issue

**Comment by AegisTheWolf** [comment]
hopefully this helps @Frooxius !

**Comment by ModernBalloonie** [comment]
To add to this issue, this isn't just rotations, but also scale. (it could be related). I made a legacy particle system that has a space under it that's scaled to 10, and the emitter also seems to get scaled when converted to PhotonDust.

![Image](https://github.com/user-attachments/assets/81947676-a5ab-42a0-9726-63a03def886c)

[DESKTOP-QBGCSAQ - 2024.12.5.1194 - 2024-12-05 16_25_26.log](https://github.com/user-attachments/files/18031204/DESKTOP-QBGCSAQ.-.2024.12.5.1194.-.2024-12-05.16_25_26.log)

And here's a log.

**Comment by ModernBalloonie** [comment]
And here's a resonite package![Legacy Particles that have a bug.zip](https://github.com/user-attachments/files/18031273/Legacy.Particles.that.have.a.bug.zip)

**Comment by Frooxius** [comment]
I'm a bit confused with this issue. The scale issue seems to be unrelated from the initial issue and it's something that's already been reported in other issues - please don't do this in general, if you ever go along the lines of "and there's also this problem" - that needs to be separate issue.

But there are no replication objects for the initial issue, so I have no way to verify or test it. 

@AegisTheWolf Can you check if this has been maybe fixed? If not can you please provide unconverted items for testing? I'm not able to work on this otherwise.

**Comment by AegisTheWolf** [comment]
I am sorry for the confusion, I created a legacy particle system and saved it as a resonite package that is a particle attached to a box going in a local Z direction, if you convert it to a photon dust one you can see it warps the scale and direction of the particles as you rotate the box.

[LegacyParticleSystem (Local Rotation Test).zip](https://github.com/user-attachments/files/18101629/LegacyParticleSystem.Local.Rotation.Test.zip)

**Comment by Frooxius** [comment]
Thanks! I'll have a look!

**Comment by ModernBalloonie** [comment]
> I'm a bit confused with this issue. The scale issue seems to be unrelated from the initial issue and it's something that's already been reported in other issues - please don't do this in general, if you ever go along the lines of "and there's also this problem" - that needs to be separate issue.
> 
> But there are no replication objects for the initial issue, so I have no way to verify or test it.
> 
> [@AegisTheWolf](https://github.com/AegisTheWolf) Can you check if this has been maybe fixed? If not can you please provide unconverted items for testing? I'm not able to work on this otherwise.

Sorry about that.

**Comment by Frooxius** [comment]
This is now fixed in 2024.12.12.1243! Thanks for report!
