### ISSUE TITLE
[photon dust] Converted Trails are completely missing or are dramatically reduced

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#3286]
### Describe the issue.

When converting trails from legacy content they are either completely missing or are dramatically reduced

### To Reproduce

1. Import the package below (Without converting it to photon dust}
2. You'll notice trails going all crazy around you (Photosensitivity warning)
3. Now do the same thing but converted to proton dust
4. You'll notice that the trails are completely gone

### Replication item
[もぺもぺほう - Layer trails error.zip](https://github.com/user-attachments/files/18030652/-.Layer.trails.error.zip)

### Expected behavior

The trails should be consistent with the legacy particle system

### Screenshots

https://github.com/user-attachments/assets/810e8fb4-34f5-48e6-8ee4-44368ce76b99

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[EPICEASTON197 - 2024.12.5.1194 - 2024-12-05 18_02_09.log](https://github.com/user-attachments/files/18030738/EPICEASTON197.-.2024.12.5.1194.-.2024-12-05.18_02_09.log)

### Reporters

@epicEaston197

**Comment by Frooxius** [comment]
This is partially fixed in 2024.12.11.501. There's still some issues that make it look different, so I'll have to investigate some more.

**Comment by Frooxius** [comment]
This is now all fixed in 2024.12.11.1386! Thanks for report!
