### ISSUE TITLE
PhotonDust - Particle Drag Support

### ISSUE THREAD

**Issue by ItsAlphaNeon** [Yellow-Dog-Man/Resonite-Issues#3288]
### Is your feature request related to a problem? Please describe.

This is a Unity particle feature, and would fit in well with the system.

### Describe the solution you'd like

A module for PhotonDust that allows particle Drag to be simulated.

### Describe alternatives you've considered

No other modules can simulate "drag"

**Comment by Frooxius** [comment]
Just a note, PhotonDust is a custom system, it doesn't use the Unity Particle system for any stage of the simulation.

**Comment by Frooxius** [comment]
Added this in 2024.12.13.1342! Thanks!
