### ISSUE TITLE
[Photon dust] Particles don't properly die after the slot is disabled

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#3289]
### Describe the issue.

Particles don't properly die if the slot is disabled
eg: If a particle is emitted and slot is disabled and reenabled it will just continue moving in the same direction it did before And not properly die

### To Reproduce

1. Import the package below
2. You'll notice particles emitting from above (Make sure to look up)
3. Disable and re enable the particles
4. You'll notice that the particles are still There

### Replication item
**Warning The replication item contains a particle system that's not very good for performance if it spawned out for too long your game will screeched to a grinding halt so make sure you only spawn it out for the necessary amount of time to replicate the issue**
[Particle death issue.zip](https://github.com/user-attachments/files/18031149/Particle.death.issue.zip)

### Expected behavior

When a particle system is disabled all admitted particles should immediately die

### Screenshots

https://github.com/user-attachments/assets/36d06bdc-aaef-424c-adb6-10943e1253eb

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[EPICEASTON197 - 2024.12.5.1194 - 2024-12-05 19_14_40.log](https://github.com/user-attachments/files/18031130/EPICEASTON197.-.2024.12.5.1194.-.2024-12-05.19_14_40.log)

### Reporters

@epicEaston197

**Comment by Frooxius** [comment]
Fixed this in 2024.12.10.523, thanks for reporting!
