### ISSUE TITLE
PhotonDust - Trying to use ColorOverLifetimeTexture causes particle system to freeze.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3291]
### Describe the issue.

I had this texture on the right set to "Readable" but it caused the particle system to freeze when I put it in the ColorOverLifetimeTexture component.

### To Reproduce

Put a texture into ColorOverLifetimeTexture, and the particle system will freeze. It seems in the log there's an issue with reading from the BC1 format.

### Expected behavior

For this to work.

### Screenshots

![Image](https://github.com/user-attachments/assets/98479e0b-63b8-4654-b06a-9162b7dc7e88)

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-QBGCSAQ - 2024.12.5.1194 - 2024-12-05 17_05_17.log](https://github.com/user-attachments/files/18031434/DESKTOP-QBGCSAQ.-.2024.12.5.1194.-.2024-12-05.17_05_17.log)

### Reporters

ModernBalloonie

**Comment by Frooxius** [comment]
Fixed in 2024.12.10.523, thanks for report!
