### ISSUE TITLE
PhotonDust - When particle systems with lights are duplicated and deleted fast, it causes the dashboard and UI to become inoperable.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3293]
### Describe the issue.

I was shooting the battle nights sub machine gun, and noticed with the particle systems on it, it causes major performance problems using PhotonDust, causing you to not be able to use your menus and all of that. This can also happen with the architech.

### To Reproduce

One way of doing it is you could spam-fire the architech (if you have it). To find it, go to the "Edge of reality" by Ryuvi.

### Expected behavior

For my dash and every UIX panel to be usable and not totally freeze up.

### Screenshots

First video is the legacy particle system.

https://github.com/user-attachments/assets/845623e9-c813-444c-a0fd-8270c76c3c56

Second video is PhotonDust.

https://github.com/user-attachments/assets/0147c48b-2ae6-4776-ac1e-2c2c8155deb8

As you can see that when it's happening on photondust, EVERYTHING becomes unusable, including your dash.

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro/Desktop

### Log Files

[DESKTOP-QBGCSAQ - 2024.12.5.1194 - 2024-12-05 20_09_53.log](https://github.com/user-attachments/files/18032647/DESKTOP-QBGCSAQ.-.2024.12.5.1194.-.2024-12-05.20_09_53.log)

### Additional Context

I feel like this is a *very* bad issue.

### Reporters

ModernBalloonie

**Comment by epicEaston197** [comment]
Hmmm
My only ideal here is that the dash and UI is running on the same thread as photon dust that's probably not the case but I'm just throwing out ideals here

**Comment by ModernBalloonie** [comment]
Was looking more into it and it seems this could be an issue when particle systems are created and destroyed really fast.

**Comment by ModernBalloonie** [comment]
AHA, I think I finally narrowed it down! It's to do with the lights module! When particle systems with lights get duplicated then destroyed really fast, it can kill all particles and the UI.

**Comment by Frooxius** [comment]
Do you have a replication item for this that's triggering the effect with rapid emissions out of the box?

Can you make a replication item that just triggers this?

**Comment by ModernBalloonie** [comment]
> Do you have a replication item for this that's triggering the effect with rapid emissions out of the box?
> 
> Can you make a replication item that just triggers this?

I sent you an item in Resonite DMs that triggers it.

**Comment by shiftyscales** [comment]
Could you please also upload the unconverted replication object from the main build here as well, as either a ResonitePackage, or record link, @ModernBalloonie?

It's easier for all involved if replication objects are included on the issue they are relevant to- keeping everything in one place.

**Comment by ModernBalloonie** [comment]
> Could you please also upload the unconverted replication object from the main build here as well, as either a ResonitePackage, or record link, [@ModernBalloonie](https://github.com/ModernBalloonie)?
> 
> It's easier for all involved if replication objects are included on the issue they are relevant to- keeping everything in one place.

The problem is that I don't think I can share the item unfortunately, it's a battle nights thing and aegis gave it to me for testing purposes, but aegis gave me permission to give it to Froox so, yeah.

**Comment by shiftyscales** [comment]
Did you not create a simplified replication object as requested above then, @ModernBalloonie? You can strip away everything that isn't strictly necessary to cause the issue, including any proprietary assets, etc.

That is the preferred way to submit replication objects so that as many pieces are removed as possible to focus the item exclusively on just the bugged behaviour and the minimal setup required to trigger it.

**Comment by Frooxius** [comment]
I could not replicate this issue with the latest build. Can you check with 2024.12.12.1243 and see if it still occurs?

**Comment by ModernBalloonie** [comment]
> I could not replicate this issue with the latest build. Can you check with 2024.12.12.1243 and see if it still occurs?

Hmm, so, I've just tried to reproduce it again. It doesn't seem to be happening as easily, however, it could be an issue when you get a lag spike, It still happened on this new build, but it took a bit more effort to pull off. I had to be firing the weapon i sent you two times, but then open a large DM with a friend on the contacts list to pull off so it gets "stuck" because it loads the messages.

Here's a video of it happening, When I get back home (gotta go to the dentist) I can make a world to reproduce it exactly like this if you want.https://github.com/user-attachments/assets/6c05f024-f385-4867-9b51-553a8d3b1e87

As you can see, it takes a bit for everything to "catch up" at the end, so the flux wires are just stuck in limbo for a bit.

**Comment by Frooxius** [comment]
When this happens, can you mash the F8 key on your keyboard a bunch? This logs the current tasks being processed by background threads, so that might help a fair bit.

**Comment by epicEaston197** [comment]
> When this happens, can you mash the F8 key on your keyboard a bunch? This logs the current tasks being processed by background threads, so that might help a fair bit.

I think frukes meant to say F3 As that is the logging key, F8 will boot you between desktop and VR mode

**Comment by ModernBalloonie** [comment]
> When this happens, can you mash the F8 key on your keyboard a bunch? This logs the current tasks being processed by background threads, so that might help a fair bit.

Will do when I get back from the dentist!

**Comment by Frooxius** [comment]
> > When this happens, can you mash the F8 key on your keyboard a bunch? This logs the current tasks being processed by background threads, so that might help a fair bit.
> 
> I think Froox meant to say F3 As that is the logging key, F8 will boot you between desktop and VR mode

Ooops. I didn't mean F3, but F9 instead.

**Comment by epicEaston197** [comment]
Huh I didn't know F9 did that that's interesting

**Comment by ModernBalloonie** [comment]
> > > When this happens, can you mash the F8 key on your keyboard a bunch? This logs the current tasks being processed by background threads, so that might help a fair bit.
> > 
> > 
> > I think Froox meant to say F3 As that is the logging key, F8 will boot you between desktop and VR mode
> 
> Ooops. I didn't mean F3, but F9 instead.

[DESKTOP-QBGCSAQ - 2024.12.12.1243 - 2024-12-12 20_50_16.log](https://github.com/user-attachments/files/18121454/DESKTOP-QBGCSAQ.-.2024.12.12.1243.-.2024-12-12.20_50_16.log)

Here's a log, I also pressed f3 around where I started pressing f9.

**Comment by epicEaston197** [comment]
Great the best of both worlds

**Comment by Frooxius** [comment]
Thanks for the log! I found what this is! It's actually nothing to do with lights at all, it has to do with the particle system itself being destroyed too fast.

This results in the particle system trying to submit new visuals to one that's already been destroyed and throwing exception. When they are destroyed rapidly, this leads to A LOT of exceptions, which wrecks the asset integration thread.

I'm closing this now as it should be fixed in 2024.12.13.1342.

Can you give it another test on your end though please? If it still occurs, we'll reopen.

**Comment by ModernBalloonie** [comment]
> Can you give it another test on your end though please? If it still occurs, we'll reopen.

![Image](https://github.com/user-attachments/assets/4ff790d9-be0f-44e4-9e50-c2434d70f971)

Stress test complete, It's fixed! Thank you!
