### ISSUE TITLE
[PhotonDust] Particle System conversion issue example

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#3296]
### Describe the issue.

A particle system on an object I use is exhibiting strange behaviour, I'm not exactly sure why but I have it linked here

### To Reproduce

1. spawn a copy of `resrec:///U-Venport/R-e9bba2dd-6deb-4340-9726-22bb18cb6cd0` before turning on conversion to observe its usual properties
2. turn on conversion and spawn another
3. witness that it looks completely different

### Expected behavior

conversion is similar/equivilant

### Screenshots

![Image](https://github.com/user-attachments/assets/c4defdd5-42ee-46f3-9661-24148158ec28)

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[DESKTOP-GCR6JOJ - 2024.12.5.1194 - 2024-12-06 00_10_22.log](https://github.com/user-attachments/files/18033695/DESKTOP-GCR6JOJ.-.2024.12.5.1194.-.2024-12-06.00_10_22.log)

The log doesn't appear to have anything terribly interesting as to why it happened, though I did use the debug testing key to signal when I spawned both in.

### Additional Context

Photon Dust

### Reporters

venport/dustysprinkles

**Comment by Dusty-Sprinkles** [comment]
Update, as of Beta 2024.12.11.501 the two particle systems are more similar now, though still subtly off, the underlying issue may be trail-related

![Image](https://github.com/user-attachments/assets/f9a020fa-0782-47e3-9c1c-6eeb47641698)

**Comment by Frooxius** [comment]
This is now fixed in 2024.12.12.1243! Thanks for report!
