### ISSUE TITLE
[photon dust] Converted Trails does not inherits legacy `ParticleSizeAffectsTrailWidth`

### ISSUE THREAD

**Issue by esnya** [Yellow-Dog-Man/Resonite-Issues#3297]
### Describe the issue.

Legacy Particle Styles are:
- `Min/MaxParticleSize` is 0
- `ParticleSizeAffectsTrailWidth` is False

Trail is not visible in the converted particle system.

### To Reproduce

My public item is here: resrec:///U-esnya/R-3123fb5d-3b58-4be7-a7e4-31687b305019

### Expected behavior

`ParticleSizeInheritance` of `ParticleTrailsModule` to be `None`.

### Screenshots

https://github.com/user-attachments/assets/1312c4d9-0144-456d-8c8e-4f8eedc43527

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[TSUKUYOMI - 2024.12.5.1194 - 2024-12-06 15_31_53.log](https://github.com/user-attachments/files/18033819/TSUKUYOMI.-.2024.12.5.1194.-.2024-12-06.15_31_53.log)

(It seems to be works fine on log.)

### Additional Context

May be related -> #3286

**Comment by Frooxius** [comment]
I can't spawn the provided item. Is it set to public?

It's possible this was already fixed through other issues too, can you check?

**Comment by esnya** [comment]
![Image](https://github.com/user-attachments/assets/e48938ec-9d9c-40de-adaa-81fbba87c64f)

It works fine on the "Beta 2024.12.11.1386". Thanks you for your great work.

(I copied the URL from my shared folder. It's a very old and migrated item. Just in case, I made ResonitePackage with the release branch: https://drive.google.com/file/d/1nOA9a05rVfrElTQtc58yAN7eiQK15em2/view?usp=sharing)

**Comment by Frooxius** [comment]
Ah thank you! Closing this then!
