### ISSUE TITLE
The direction of particles emitted from the Cylinder emitters is different before and after conversion.

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#3298]
### Describe the issue.

The legacy Cylinder Emitter emits particles in the direction normal to the cylinder.
(When RandomDirection or ForceDirection is not used)

PhotonDust's Cylinder emitter allows you to choose the direction of emission with DirectionMode.
This is set to RadialUniform after conversion, which changes the appearance of the particles after conversion.
By setting it to CircleUniform, the appearance will be identical.

### To Reproduce

1. Create legacy particles with CylinderEmitter.
Here is the ResonitePackage.
Do not unzip it. Change the extension to .resonitepackage.
[LegacyCylinder.zip](https://github.com/user-attachments/files/18033842/LegacyCylinder.zip)

2. Convert it to PhotonDust.

3. You will see that the particles are emitted in different directions.

### Expected behavior

The particles should look the same after conversion.

### Screenshots

![Image](https://github.com/user-attachments/assets/0c96dc22-4f88-4679-afc8-2f2e660577ab)

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MENTAIKO - 2024.12.5.1194 - 2024-12-06 15_50_53.log](https://github.com/user-attachments/files/18033876/MENTAIKO.-.2024.12.5.1194.-.2024-12-06.15_50_53.log)

### Reporters

orange3134

**Comment by orange3134** [comment]
Note: In the above screenshot, the particles are set to face the direction of travel to make it easier to see the difference in the direction of particle emission.

**Comment by Frooxius** [comment]
Fxied on 2024.12.12.547, thank you for reporting!
