### ISSUE TITLE
Publishing content: avatars, inventory items, props, and search

### ISSUE THREAD

**Issue by InconsolableCellist** [Yellow-Dog-Man/Resonite-Issues#33]
### Is your feature request related to a problem? Please describe.

Currently there's no way (that I know of) to make content widely available. It's all word-of-mouth.

### Describe the solution you'd like

It seems like there needs to be an entire publishing system and search engine so you can publish and search for all content: avatars, props, inventory items, documents, etc. Users should be able to tag their creations, publish it (perhaps with a limit on how much you can publish in a certain time period), and then others can discover it and download the content. Perhaps there could even be statistics on how often your creations are downloaded, and/or links to your Gumroad, Patreon, etc. to support your work.

### Describe alternatives you've considered

Word-of-mouth is currently the only alternative. Going to worlds and getting lucky by hearing about something cool or finding what you're looking for.

**Comment by Frooxius** [comment]
Closing this one in favor of our official issue now: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1473

Thanks for submitting this though!
