### ISSUE TITLE
LineEmitter emission direction is different before and after conversion

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#3300]
### Describe the issue.

When the legacy LineEmitter is converted to PhotonDust, the emission direction is different.

Oddly enough, the difference in emission direction varies with the angle of the object.
See the video in the ScreenShot section.

When the object's rotation is 0,0,0, the emission directions are consistent, but as the object rotates, the difference in emission direction increases.

### To Reproduce

1. Create legacy particles with LineEmitter.
Here is the ResonitePackage.
Do not unzip it. Change the extension to .resonitepackage.
[LegacyLineEmitter.zip](https://github.com/user-attachments/files/18034719/LegacyLineEmitter.zip)
Spinners are added to visualize the change in emission direction due to object rotation.
1. Convert it to PhotonDust.
1. You will see that the particles are emitted in different directions.

### Expected behavior

The direction of particle emission should be consistent.

### Screenshots

https://github.com/user-attachments/assets/66dd4f4a-019f-4fb7-9abf-d628f8a76ec2

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MENTAIKO - 2024.12.5.1194 - 2024-12-06 17_16_59.log](https://github.com/user-attachments/files/18034797/MENTAIKO.-.2024.12.5.1194.-.2024-12-06.17_16_59.log)

### Reporters

orange3134

**Comment by Frooxius** [comment]
Fixed this in 2024.12.10.1414, thanks for report!
