### ISSUE TITLE
If a ParticleSystem's parent Slot is spawned while it is inactive, the particles will not be visible the first time the parent Slot is activated.

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#3302]
### Describe the issue.

If an item is saved to inventory while the ParticleSystem's parent Slot is inactive, and then the item is spawned from inventory to activate the parent Slot, the particles will not be visible the first time.

If you deactivate the parent Slot again and then reactivate it, the particles will appear.

This will only happen if you deactivate the parent Slot and save it.
It does not occur if the ParticleSystem-attached Slot itself is deactivated and saved.

### To Reproduce

1. Create a ParticleSystem from DevTool.
1. Create a parent Slot of ParticleSystem.
1. Deactivate the parent Slot and save it to inventory.
1. Spawn the saved one from inventory.
1. Activate the parent Slot in the ParticleSystem. Particles will not be visible.
1. Deactivate the parent Slot and then activate it again. Particles will be visible.

Minimum items to reproduce this
Do not unzip it. Change the extension to .resonitepackage.
[PhotonDustParentActiveIssue.zip](https://github.com/user-attachments/files/18037047/PhotonDustParentActiveIssue.zip)

### Expected behavior

When the parent Slot is first activated, particles should become visible.

### Screenshots

https://github.com/user-attachments/assets/6ccb97fb-aaee-463a-92bb-8ad52fe384cc

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MENTAIKO - 2024.12.5.1194 - 2024-12-06 19_54_14.log](https://github.com/user-attachments/files/18037114/MENTAIKO.-.2024.12.5.1194.-.2024-12-06.19_54_14.log)

### Additional Context

This also occurs when the parentSlot converts an inactive LegacyParticleSystem.

### Reporters

orange3134

**Comment by orange3134** [comment]
Additional Information
We noticed that the behavior is different when converting from inventory and when converting from ResonitePackage.

This video is the case of converting from ResonitePackage.
The green and blue particles are generated from the same location, but only the red particles are generated from different locations.
I do not know why the difference occurs between inventory and ResonitePackage.
https://github.com/user-attachments/assets/d90637df-193f-4489-bf96-97fbcc01705f

**Comment by Frooxius** [comment]
Fixed this in 2024.12.10.1414, thanks for report!
