### ISSUE TITLE
[PhotonDust Phase 2 test] Converted particles not initialising consistently when slot enabled/disabled

### ISSUE THREAD

**Issue by Lexevolution** [Yellow-Dog-Man/Resonite-Issues#3303]
### Describe the issue.

When going through a world which enables and disables particles by enabling/disabling the slots, the particles would not show up most of the time when they were "activated".

### To Reproduce

- Turn on particle conversion
- Launch my Particle Exhibition world, `resrec:///U-Lexevo/R-8599fdfa-2af6-422f-981a-0db077c8e514`
- Go through the exhibition as normal, pressing buttons to activate the particle effects.

### Expected behavior

For all particles to show as in previous versions.

### Screenshots

No screenshots, but two videos of me walking through the world from the current release version (2024.12.2.1188) and the current prerelease version with converted particles (2024.12.5.1194).

Before conversion: https://www.youtube.com/watch?v=qRxyAGxnc0s
After conversion: https://www.youtube.com/watch?v=3NybPelkmDM

### Resonite Version Number

2024.12.5.1194

### What Platforms does this occur on?

Windows

### Log Files

From before conversion in older version: [LEXDESKTOP - 2024.12.2.1188 - 2024-12-06 20_29_18.log](https://github.com/user-attachments/files/18037131/LEXDESKTOP.-.2024.12.2.1188.-.2024-12-06.20_29_18.log)
From after conversion in prerelease version: [LEXDESKTOP - 2024.12.5.1194 - 2024-12-06 20_35_12.log](https://github.com/user-attachments/files/18037137/LEXDESKTOP.-.2024.12.5.1194.-.2024-12-06.20_35_12.log)

### Additional Context

I eventually got some of the particles to work, and the mesh one had weird gravity, which I think is already an issue created. There is also some major issues with the one with the connected trails, which I don't really know how to describe, or how to put it in a separate issue if needed.

### Reporters

Lexevo

**Comment by Frooxius** [comment]
Fixed this in 2024.12.10.1414, thanks for report!
