### ISSUE TITLE
Randomness is lost in the converted BoxEmitter.

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#3304]
### Describe the issue.

In LegacyParticle, when duplicating a ParticleSystem with a BoxEmitter, particles were emitted from different positions in each system.

When this particle is converted in PhotonDust, all BoxEmitters emit particles at the same position.
This causes an unintended appearance after conversion.

It is difficult to explain in words, please see the video in the Screenshot section.

Perhaps there is some internal value like a random seed?

### To Reproduce

1. Create particles using BoxEmitter.
2. Duplicate them and give them different materials.
3. Particles with different materials will be emitted from different positions.
4. Convert them to PhotonDust. All particles will be emitted from the same position and will have an unintended appearance.

Minimum items to reproduce this
Do not unzip it. Change the extension to .resonitepackage.
[BoxEmitterPositionIssue.zip](https://github.com/user-attachments/files/18037571/BoxEmitterPositionIssue.zip)

### Expected behavior

The particles should look the same as they did before conversion.

### Screenshots

https://github.com/user-attachments/assets/340c540c-b2ec-4335-a53a-f7d7f1fbf304

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MENTAIKO - 2024.12.5.1194 - 2024-12-06 20_34_47.log](https://github.com/user-attachments/files/18037615/MENTAIKO.-.2024.12.5.1194.-.2024-12-06.20_34_47.log)

### Reporters

orange3134

**Comment by orange3134** [comment]
Additional Information
I noticed that the behavior is different when converting from inventory and when converting from ResonitePackage.

This video is the case of converting from ResonitePackage.
The green and blue particles are generated from the same location, but only the red particles are generated from different locations.
I do not know why the difference occurs between inventory and ResonitePackage.

https://github.com/user-attachments/assets/d90637df-193f-4489-bf96-97fbcc01705f

**Comment by Frooxius** [comment]
Fixed this in 2024.12.10.1414, thanks for report!

Good catch, this was very peculiar issue, but easy to fix!
