### ISSUE TITLE
Offline Mode: Resonite doesn't initialize on launch

### ISSUE THREAD

**Issue by JackTheFoxOtter** [Yellow-Dog-Man/Resonite-Issues#3309]
### Is your feature request related to a problem? Please describe.

When starting Resonite without an internet connection, both the dashboard & the local home don't initialize, leaving me to believe that the engine gets stuck attempting to log in.

### Describe the solution you'd like

Resonite should be able to initialize without an internet connection, allowing you to at least access your (last cached or default) dashboard & properly load the local home.

### Describe alternatives you've considered

None

### Additional Context

Easton mentioned this in #3307 and I can confirm this behaviour (currently on the train on my Steam Deck)

### Requesters

EpicEaston, Myself

**Comment by JackTheFoxOtter** [comment]
Actually this is a duplicate of #2517

**Comment by epicEaston197** [comment]
> Actually this is a duplicate of [#2517](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2517)

That issue is really broad and it's not targeting a specific problem I prefer this issue because it's targeting the dash in local home not properly initializing when you don't have an Internet connection
