### ISSUE TITLE
[PhotonDust] Particles emitting from 4 directions instead of 1

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#3310]
### Describe the issue.

PhotonDust particles(right side of video) look different than the legacy particles(left side of video)

### To Reproduce

Import the resonitepackage file provided and observe the differences

### Expected behavior

It is expected that the particles will look like the ones on the left side of the video

### Screenshots

https://github.com/user-attachments/assets/d6b8e47b-4482-4ec7-9613-e65799efcd82

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[DESKTOP-3VH8L1D - 2024.12.5.1194 - 2024-12-06 15_54_26.log](https://github.com/user-attachments/files/18043155/DESKTOP-3VH8L1D.-.2024.12.5.1194.-.2024-12-06.15_54_26.log)

### Additional Context

[SparksTest.resonitepackage.zip](https://github.com/user-attachments/files/18043203/SparksTest.resonitepackage.zip)

### Reporters

ultrawidegamer

**Comment by Frooxius** [comment]
Fixed this in 2024.12.10.1414, thanks for report!
