### ISSUE TITLE
[PhotonDust] Particles are not respecting TrailWorldSpace setting

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#3312]
### Describe the issue.

After conversion the particle trails do not appear to respect the TrailWorldSpace setting

### To Reproduce

Import the resonitepackage file provided and observe the differences

### Expected behavior

It is expected that the particles will look like the ones on the left side of the video

### Screenshots

https://github.com/user-attachments/assets/b86e4ed9-6ad9-4120-822a-8b85f5071e4e

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2 

### Log Files

[DESKTOP-3VH8L1D - 2024.12.5.1194 - 2024-12-06 15_57_55.log](https://github.com/user-attachments/files/18043310/DESKTOP-3VH8L1D.-.2024.12.5.1194.-.2024-12-06.15_57_55.log)

### Additional Context

[TrailWorldSpaceTest.resonitepackage.zip](https://github.com/user-attachments/files/18043307/TrailWorldSpaceTest.resonitepackage.zip)

### Reporters

ultrawidegamer

**Comment by Frooxius** [comment]
This is fixed in 2024.12.11.1386 now. Thanks for report!
