### ISSUE TITLE
Incorrect conversion ParticleLightModule

### ISSUE THREAD

**Issue by HamoCorp** [Yellow-Dog-Man/Resonite-Issues#3313]
### Describe the issue.

how the world should look ![Image](https://github.com/user-attachments/assets/ceaccc59-8f6d-4e15-99dc-fa0b38bf3b14)
after converting, very blue ![Image](https://github.com/user-attachments/assets/12750e54-467e-40c4-acda-a5afa653ff8b)

### To Reproduce

open the world Cosy Train with convert particle systems enabled resrec:///U-HamoCorp/R-fef1033f-f84f-4e9d-b579-7821c92d7e36
open inspector and navigate to particle systems disabling particleLightsModule fixes it

https://github.com/user-attachments/assets/5c5c6d3e-a8d0-4b11-ab90-bf64c7904cbd

### Expected behavior

not so blue

### Screenshots

old particle system
![Image](https://github.com/user-attachments/assets/3906f011-6a47-4660-a0ab-08f8085f72ca)

new system
![Image](https://github.com/user-attachments/assets/4ddcd449-57ef-4809-9a83-6baf11eb1a0f)

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

desktop

### Log Files

[THE-GERMAN-ROME - 2024.12.5.1194 - 2024-12-06 19_42_03.log](https://github.com/user-attachments/files/18043207/THE-GERMAN-ROME.-.2024.12.5.1194.-.2024-12-06.19_42_03.log)

### Reporters

HamoCorp

**Comment by VirgilCore** [comment]
Lights on certain particles are too weak or desaturated. Version:Beta 2024.12.11.501
![Image](https://github.com/user-attachments/assets/a3f3f56d-34cf-40f8-8a66-55f14eeda0fc)
Bottom is legacy, Top is PhotonDust. 
Example object here: resrec:///U-Virgil/R-31870CCE08D76E4889F5E2DC8464F8DD1E99FFB3CFCDA72CE4E8191116FA4478

**Comment by Frooxius** [comment]
Thanks for the report! This was due to the template light actually being a directional light, which the legacy particle system just ignored.

This is now fixed in 2024.12.11.1386, which emulates this old behavior!
