### ISSUE TITLE
Clarifications needed for RadialForce / component misbehaviour

### ISSUE THREAD

**Issue by jae1911** [Yellow-Dog-Man/Resonite-Issues#3316]
### Describe the issue.

To start off, as a full disclaimer, this whole issue might be me misunderstanding how to use this component.
Please feel free to correct me, and I will close this issue, then document this on the Wiki.

---

When trying to use the `RadialForce` module for PhotonDust, I cannot manage to reproduce the behaviour shown in the dev log video showcasing this component (https://youtu.be/g-505WwQfsM).  
Instead, the component acts more like some rough gravity that only bends the particle flow, instead of really creating an effect in which they are completely circular.

### To Reproduce

Following the same steps as within the dev log video (https://youtu.be/g-505WwQfsM):

1. Create a particle system
2. Set the `Rate` to 100 on the `PointEmitter`
3. Turn `RandomDirectionWeight` down to 0
4. Create an empty object
5. Move the `PointEmitter` to this new empty object
6. Select the particle system slot and add a new `RadialForce` component
7. Add the component in the module list of the `ParticleStyle`
8. Add or subtract force with the slider present on the `RadialForce`
9. Observe the result isn't the same as with the dev log

### Expected behavior

It should create a circular particle flow instead of just bending it.

For instance, taken from the video:

![Image](https://github.com/user-attachments/assets/1c3e7da3-466b-403e-ade6-c41cfc963db8)

### Screenshots

https://github.com/user-attachments/assets/068f0dae-65af-43f8-ae3b-1bed5fd7242f

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[TETHYS - 2024.12.5.1194 - 2024-12-07 11_44_05.log](https://github.com/user-attachments/files/18047918/TETHYS.-.2024.12.5.1194.-.2024-12-07.11_44_05.log)

### Additional Context

As an additional note, since the video in question, the component now has more options, which is why I think this is just a *me* issue.

### Reporters

U-j4 | j4.lc

**Comment by Zozokasu** [comment]
@jae1911 
I think using `SpeedConstantInitializer` instead of `SpeedRangeInitializer` will fix that.

**Comment by jae1911** [comment]
> [@jae1911](https://github.com/jae1911) I think using `SpeedConstantInitializer` instead of `SpeedRangeInitializer` will fix that.

Testing this, seems it somehow made it worse. Now it only just slightly bends the particle flow.

https://github.com/user-attachments/assets/3e8f9f5e-3663-4e27-a165-c224cd5a1094

**Comment by Zozokasu** [comment]
Press `use Local Space` on `RadialForce`.
In that state, the center of force is [0, 0, 0] (that is the origin of the world).

**Comment by jae1911** [comment]
I was indeed missing something, thanks.

Time to document this.
