### ISSUE TITLE
[PhotonDust] Converted particles will break alignment of aligners

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#3329]
### Describe the issue.

When converting a particle system, resonite will generate new child slots that contain the particle system parts. If the original particle system contained an aligner (ex. CircleAligner) with the AutoAddChildren checkbox enabled, it will throw off the expected alignment of the child slots

### To Reproduce

Import the resonitepackage file provided and observe the differences

### Expected behavior

It is expected that the particles will not mess with the alignment of the child slots and for in the image to have the right's alignment to look like the one on the left

### Screenshots

![Image](https://github.com/user-attachments/assets/8c399d20-814c-4acd-9f38-b7f808cc347b)

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[DESKTOP-3VH8L1D - 2024.12.5.1194 - 2024-12-09 10_53_58.log](https://github.com/user-attachments/files/18063235/DESKTOP-3VH8L1D.-.2024.12.5.1194.-.2024-12-09.10_53_58.log)

### Additional Context

[AlignerTest.resonitepackage.zip](https://github.com/user-attachments/files/18063241/AlignerTest.resonitepackage.zip)

### Reporters

ultrawidegamer

**Comment by Frooxius** [comment]
Hmm... I can just make it dump everything on the single slot, but it'll make it messier to work with.

Alternatively, add a heuristic that only does this specifically if aligner is detected, but there might be other non-aligner systems that this will also affect.

**Comment by TisFoolish** [comment]
What about a tag that makes the aligner ignore that slot? Granted, this feels more like a feature request, but it was the only other thing I could think of besides making the aligner on its own slot child to the particle system and updating references to the slot elsewhere; this however could have complicated knock on effects and might not necessarily work with everything.

**Comment by ultrawidegamer** [comment]
I mean it is possible that something else could break on conversion as well from this... but this is a semi common scenario and also a tag would not work as the purpose of this is to preserve as much of the legacy content as possible without needing to edit it. Also, the single slot would not solve the issue either as it would still offset it by one.

Probably the only way to keep the same functionality as the legacy content is to detect if the slot has an aligner, and if it does... inject all of the new components to the same one as the aligner

**Comment by TisFoolish** [comment]
> but this is a semi common scenario and also a tag would not work as the purpose of this is to preserve as much of the legacy content as possible without needing to edit it

I was suggesting that the conversion system add that tag to the particle system slots that it creates

**Comment by Frooxius** [comment]
That's just overcomplicating this and the aligners, which now need to deal with something that's not even relevant to them.

The easiest thing is to just detect any aligner and then put all the components on the same Slot.

**Comment by Frooxius** [comment]
I've done some testing and I actually ended up going with the tags route in the end.

The aligner detection turned out to be a bit trickier option, due to load/upgrade execution order issues.

This should now be fixed with 2024.12.12.1243! Thanks!
