### ISSUE TITLE
Logging in doesn't work properly on the pre-release.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3330]
### Describe the issue.

Oddly, I can log in on the normal build, but on the pre-release it puts me into this weird state where i'm halfway logged in. I'm assuming this is because the cloud stuff updated.

### To Reproduce

Login with 2FA on the pre-release build, You'll be in a weird half-way logged in state.

### Expected behavior

To properly login.

### Screenshots

![Image](https://github.com/user-attachments/assets/72f23e5e-6139-48c2-9a0e-d75f3134da1d)

It "logs in" but nothing works.

### Resonite Version Number

Beta 2024.12.5.1194

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

I assume this stuff is sensitive information so idk if I should put the log file here for this due to it being an account login issue.

### Reporters

ModernBalloonie

**Comment by ModernBalloonie** [comment]
> [@ModernBalloonie](https://github.com/ModernBalloonie) - As of an hour ago Frooxius had noted the cloud was having some issues- but those cloud issues reportedly should be resolved by now.
> 
> Could you set a new datapath temporarily to try logging in from a fresh database and see if you still have issues now?

So i'm able to log in onto the main build, I don't really think it's a cloud issue, rather it's just an issue with the pre-release build. I logged in onto an alt fine that's not using 2fa, it's just i'm using 2fa on my main account and the pre-release seems to have an issue with that.

If you want me to still test the datapath thing though I could, it's just I don't think that's the problem, because everything works fine on the current release build.

**Comment by shiftyscales** [comment]
I have 2FA on my main account and just logged in to the prerelease with no issue just now. So I do not think your issue is related to either of 2FA nor is it specific to the prerelease based on my initial investigation into it. Please try the above as mentioned, yes.

**Comment by ModernBalloonie** [comment]
> I have 2FA on my main account and just logged in to the prerelease with no issue just now. So I do not think your issue is related to either of 2FA nor is it specific to the prerelease based on my initial investigation into it. Please try the above as mentioned, yes.

Just tried that, and I got the same result.

**Comment by ModernBalloonie** [comment]
I also just tried verifying my files, still didn't work.

**Comment by shiftyscales** [comment]
I'd suggest trying again in a while- and if it persists, we likely would need a log file.

I don't know what the issue would be though if it isn't just a transient cloud issue- because as mentioned- under the same conditions, I do not have the same issue on my account.

**Comment by shiftyscales** [comment]
Even though you are only "half-logged in" perhaps you could also try loging out and back in?

**Comment by Frooxius** [comment]
This is due to cloud changes. I need to push a new pre-release with the same update as on public. I'll do so as soon as I can.

**Comment by shiftyscales** [comment]
Oh weird- good to know. I don't know why things worked without issue for me then. Thanks for the update. :)

**Comment by Frooxius** [comment]
The login breaks specifically if you're a Patreon supporter, because that will add entities to your account that cause breakage.

**Comment by Frooxius** [comment]
This is now fixed up on 2024.12.10.523!
