### ISSUE TITLE
Youtube DL needs updating

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#3332]
### Describe the bug?

Youtube videos no longer load due to outdated version of Youtube DL

### To Reproduce

Import youtube video only audio only headphones icon

### Expected behavior

Youtube videos should load when YouTube DL is updated

### Resonite Version Number

Beta 2024.12.9.1159

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

No log files needed youtube DL just needs updating

### Additional Context

I updated YouTube DL manually and YouTube video started working again as expected

### Reporters

@epicEaston197

**Comment by AmasterAmaster** [comment]
I am also having the same issue in my theater world when inputting and loading youtube links.

**Comment by Frooxius** [comment]
Updated in 2024.12.10.482! Thanks!
