### ISSUE TITLE
Add a proper way to report issues with logs through more private manners

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Yellow-Dog-Man/Resonite-Issues#3334]
### Is your feature request related to a problem? Please describe.

Currently I need to go through my logs and redact a bunch of info (typically session id's as they are permanent but I really don't think necessary for anyone else to know who doesn't need them) in order to upload the log in a manner I think is safe.

### Describe the solution you'd like

Some way, either through secondary logs, uploading the log to a private link offered by resonite, or some other way of making sure either the log is (when public) redacted from some information (such as session id's and user join requests) or is only viewable by those that need it.

I am personally biased towards a "redacted but public facing" way for logs to be distributed.

### Describe alternatives you've considered

Redacting them manually.

### Additional Context

This is mostly a "Noone needs to know" about:
Who connects to who.
What the session ID's are. (As they can be with headless' clients more permanent, but may not be public facing)

As the platform grows this will become an ever growing issue and discourages certain people from potentially reporting issues.

### Requesters

3x1t_5tyl3

**Comment by JackTheFoxOtter** [comment]
I think a secure way to upload log files in a non-public manner (while still linking them to GitHub issues) would be a good approach. In the meantime, @mpmxyz released a third-party open-source log cleaner to strip private information from the log files, which could maybe help you out: https://github.com/mpmxyz/ResoniteLogCleaner
