### ISSUE TITLE
UIX - A way to get current user inputs

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Yellow-Dog-Man/Resonite-Issues#3336]
### Is your feature request related to a problem? Please describe.

Currently in order to do both capturing #3335 and using the inputs for other things than movement is not possible.

### Describe the solution you'd like

A component or otherwise a flux a node, or some way to get the current users inputs of who is interacting, hovering ect, (Though I can foresee problems with locallity here, so maybe a toggle for local user only?) such as secondary, primary, stick input, touchpad ect.

### Describe alternatives you've considered

Not currently possible without needing to basically anchor them and this also doesn't allow button interactions (such as CommonUI components and similar)

### Requesters

3x1t_5tyl3

**Comment by shiftyscales** [comment]
As with your other issue, #3335 - I am not certain I understand your use-cases / what you are trying to do.

There already exist nodes that will give you the kind of information you are after. There are the [controller nodes](https://wiki.resonite.com/Category:ProtoFlux:Devices:Controllers) which will inform you what inputs the user is using, [Anchor Locomotion Data](https://wiki.resonite.com/ProtoFlux:Anchor_Locomotion_Data) in the context of anchors, [TouchableData](https://wiki.resonite.com/Component:TouchableData) and [Touchable Events](https://wiki.resonite.com/ProtoFlux:Touchable_Events) for more specific information about how a canvas is being interacted with, etc.

**Comment by shiftyscales** [comment]
> (without anchoring the user, which isn't always a good solution)

Why is that not a good solution?

**Comment by JackTheFoxOtter** [comment]
Anchoring the user parents them to a different point in the hierarchy. In the case of a camera, it would be weird to anchor the user to the camera. You'd need to first spawn a sort of global anchor outside of the camera, then anchor the user there. But then they also aren't affected by physics anymore, unless you also put a character controller on the anchor. It creates a lot of design overhead when (ab)using features for use-cases they weren't meant for. I'm also not sure if you can anchor someone without moving their avatar proxies, but I also haven't tried that before. At least from my understanding this wouldn't really be using them in the way they are intended to be used.

As a game engine, I do think Resonite should allow creators some deeper control over how inputs are processed, at least in regards to those that are used by default systems, like locomotion.

**Comment by ko-tengu** [comment]
You also can't anchor someone that's already anchored, and anti-anchor scripts are insanely common and will happily break your anchor based systems.

**Comment by shiftyscales** [comment]
> Anchoring the user parents them to a different point in the hierarchy.

If you set the anchor to `LocalUserSpace` it will anchor them in-place without moving them in the hierarchy at all. You can also set the position / rotation restore, etc. to none so it will keep the user exactly where they are and drop them off.

> You also can't anchor someone that's already anchored

Yes you can. How are you trying to anchor them?

> anti-anchor scripts are insanely common and will happily break your anchor based systems

Users purposefully breaking content is not a valid reason to avoid using the intended systems to do things. But there will be better methods for users to control the kinds of content / components, etc. that can be brought into their sessions, or what kinds of systems can affect them in the form of #1103.

**Comment by JackTheFoxOtter** [comment]
> If you set the anchor to LocalUserSpace it will anchor them in-place without moving them in the hierarchy at all. You can also set the position / rotation restore, etc. to none so it will keep the user exactly where they are and drop them off.

I wasn't aware of that! That does make it a much more viable option, yeah.
