### ISSUE TITLE
Taken usernames should be replaced with placeholders

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Yellow-Dog-Man/Resonite-Issues#3338]
### Is your feature request related to a problem? Please describe.

The problem here is mostly confusion, where when searching for me "Andromeda" (recently changed) the name of the account which previously held the username would still *also* be called "Andromeda" which could lead into confusion where when someone searches me, they might find 2 accounts.

Profileimages notoriously don't load either at the moment sometimes so that compounds. (That is a seperate issue I can't seem to find rn)

Edit: Updated image whoops.
![Image](https://github.com/user-attachments/assets/4fd7ceb5-8d46-41ff-a8d5-89d07620645a)

### Describe the solution you'd like

Give the account which has the username taken from a temporary name until they decide to migrate (if ever) and then letting them choose a new one.

### Describe alternatives you've considered

List the ID of a user next to the username in the tab to make sure?
Seems rather debuggy than an actual feature and even then I presume not until the contacts UI rework #1116 

### Additional Context
EDIT: To be clear it has been a day or two since I changed my username and I have relogged several times.

### Requesters

3x1t_5tyl3

**Comment by shiftyscales** [comment]
> Profileimages notoriously don't load either at the moment sometimes so that compounds. (That is a seperate issue I can't seem to find rn)

That sounds like https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1088 which can be mitigated by updating the profile picture on the affected account.

The rest sounds like the same underlying issue as https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/364.

I feel like your proposal of having "placeholder" names would cause more problems than it solves- e.g. it would make it a lot more difficult to tell which migrated contact belonged to who.

If the user doesn't exist on the new infrastructure yet- then it doesn't really hurt anything to have it reflect the old name as that was the name they were on the previous infrastructure- and the only person that would see that name is the person that migrated who knows who that contact was.

If they do already exist on the new infrastructure that is migrated to- it'd be better to just resolve the underlying issue #364 instead.
