### ISSUE TITLE
Don't force users into tutorial after logging in

### ISSUE THREAD

**Issue by Banane9** [Yellow-Dog-Man/Resonite-Issues#3339]
### Describe the bug?

When launching Resonite on a fresh install, one is prompted to select a language and can then login or create an account. After that, one is forced into the tutorial, even when logging in with an existing account that has already gone through the tutorial.

### To Reproduce

Launch a fresh install of Resonite. Log into an existing account when prompted. Be forced into the tutorial as it's the only button available.

### Expected behavior

When logging into an existing account, one should automatically bypass the tutorial or at least have the option of skipping it. This could be based on a flag on the account as well.

### Resonite Version Number

Beta 2024.12.10.482

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[MPI-PF2D40B5 - 2024.12.10.482 - 2024-12-11 15_07_53.log](https://github.com/user-attachments/files/18097232/MPI-PF2D40B5.-.2024.12.10.482.-.2024-12-11.15_07_53.log)

### Reporters

[Bb]anane9

**Comment by Banane9** [comment]
> This is currently done by design. It does not make sense for us to assume a given users' familiarity with the platform just based on ownership of an account.

But it does tell you, that they might not be interested in being forced through it again.

> They may have made it at launch, used it for a day, if at all, and then not again for a year- perhaps they are a returning user after a long time, or we've updated the introductory tutorial flow and a refresher of some basic ideas could be beneficial to them.

Which could easily be checked by looking at the last online date - if I last used Resonite _today_, I definitely don't need a tutorial now.

_But_ if you used Resonite to any extent more than launching and closing on a machine, it will not load the tutorial regardless of how long you took a break. Having more than 20 records in the local DB prevents that, even when not auto-logging-in.

> There also already exist multiple existing mechanisms that can be used to skip the tutorial. There is the `-SkipIntroTutorial` [command line argument](https://wiki.resonite.com/index.php?title=Command_Line_Arguments#Misc) for those who might need to do this more routinely

Sure, but that's hardly discoverable for anyone who doesn't already know or memorized all argument features.

> additionally, entering UI edit mode will unlock the dash / allow the user to exit the tutorial worlds at will.

Not possible in desktop anyways.

---

Providing a "Skip" button when logging into an existing account would easily solve this problem. Additionally showing the tutorial option for someone logging in on a previously used machine after a long time would add what you described as an existing feature.

**Comment by ModernBalloonie** [comment]
I just always start the game with -SkipIntroTutorial.

**Comment by Frooxius** [comment]
Yes this is by design. 

Based on our experience, there were people who did have an account, but did not play in a while. After joining back, they'd end up confused, because they would not be familiar with any updates - or perhaps they made an account while back and didn't really play.

This hurts the user retention, so we will not be making this change.

You can either use the command-line argument above or enable Edit mode briefly (F2 in desktop) to skip tutorial.
