### ISSUE TITLE
Updates<Int>or Updates Timer

### ISSUE THREAD

**Issue by Azavit** [Yellow-Dog-Man/Resonite-Issues#334]
### Is your feature request related to a problem? Please describe.

Sometimes you want to trigger a call every x updates rather than every update (to help reduce possible slowdowns of a complex system).

Using the current timer may be overkill as you want something to happen within a time span of an amount of updates rather than based on elapsed time.

### Describe the solution you'd like

An Int Input into the updates/local updates node (or a new updates node with an Int input) that allows for slowing down the number of updates that must pass before it fires.

or

Updates Timer where it functions exactly as the Timer node but rather than running every x seconds it runs every x updates.

Both of these two options will effectively function identically for the end user it really matters on the underlining behaviors of these nodes which one is the best used for this situation and that is better left to the people who understand the back-end more.

### Describe alternatives you've considered

Current alternatives:

Making an Async While (True) Updates Delay

This not only requires a call to start it but is also a bit clunky for something that may need to run mostly constantly.

**Comment by Frooxius** [comment]
Added in 2023.11.11.1231, thanks!
