### ISSUE TITLE
[PhotonDust] Particle Trails set to Tile are inccorectly converted to Stretch

### ISSUE THREAD

**Issue by Dusty-Sprinkles** [Yellow-Dog-Man/Resonite-Issues#3343]
### Describe the issue.

The magic flinging wand from Gearbell's toyshop folder has ribbon trails of sparkles that follow the particle, but it seems like conversion swapped the TextureMode to Stretch instead of Tile

### To Reproduce

1. Spawn out `resrec:///U-GearBell/R-69fc1203-46c8-4d1a-84f2-d020365581ca` and a converted version of it
2. Compare the trail appearance
3. Yippee

### Expected behavior

Trails look the same

### Screenshots

Pre-Conversion
![Image](https://github.com/user-attachments/assets/fdf38578-e43f-4151-bbd1-ad8e3f588d47)

Post-Conversion
![Image](https://github.com/user-attachments/assets/8ff3e5ed-c997-4289-bdc5-5d3bad178ada)

### Resonite Version Number

2024.12.11.1386

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index

### Log Files

[DESKTOP-GCR6JOJ - 2024.12.11.1386 - 2024-12-11 17_29_44.log](https://github.com/user-attachments/files/18103713/DESKTOP-GCR6JOJ.-.2024.12.11.1386.-.2024-12-11.17_29_44.log)

### Additional Context

interestingly related to #3297 since it also has that turned off but does seem to convert properly

### Reporters

Venport/dustysprinkles

**Comment by Frooxius** [comment]
Fixed this on 2024.12.12.547, thanks for reporting!
