### ISSUE TITLE
IPV6 Hub Issue

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#3345]
### Describe the bug?

Now that we have sub issues on GH, I wanted to collate all issues preventing IPV6 working on Resonite into a parent issue.

### To Reproduce

N/A

### Expected behavior

N/A

### Resonite Version Number

N/A

### What Platforms does this occur on?

Windows

### What headset if any do you use?

N/A

### Log Files

N/A

### Additional Context

N/A

**Comment by ProbablePrime** [comment]
Nevermind I will collate in #143

**Comment by ProbablePrime** [comment]
Hi 2 years ago Prime, I disagree with you!

**Comment by j4lc** [comment]
v6 time
