### ISSUE TITLE
[PhotonDust] MeshParticleRenderer will not render static meshes, only procedural meshes

### ISSUE THREAD

**Issue by mxjessie** [Yellow-Dog-Man/Resonite-Issues#3348]
### Describe the bug?

While trying to compare the performance of procedural mesh particles vs. its baked equivalent, I found that baking the mesh into a StaticMesh stops it rendering entirely. I'm not able to get any StaticMesh to render through a MeshParticleRenderer. StaticMesh rendering does work on legacy particle systems, in both release and prerelease.

Couldn't find a related issue reported already. Thanks for all the hard work here!

### To Reproduce

Create a new ExperimentalParticleSystem
Attach a MeshParticleRenderer
Create a new 3D Model > Box
Add BoxMesh and its material to MeshParticleRenderer
Replace BillboardParticleRenderer in ParticleStyle with MeshParticleRenderer. Procedural cube particles are rendered correctly
Click "Bake mesh" in the BoxMesh component. Cube particles disappear. The BoxMesh reference is updated correctly to the new StaticMesh, and the particle system continues to simulate, but with no visuals.

Any arbitrary StaticMesh also exhibits this behavior; it does not appear to be specific to a baked procedural mesh.

I have not yet tested if this affects converted particle systems.

### Expected behavior

Static meshes should be rendered by MeshParticleRenderers

### Screenshots

![Image](https://github.com/user-attachments/assets/ae4c87ef-0a62-41de-8943-dfbab428d0b2)

![Image](https://github.com/user-attachments/assets/816794d0-0f7e-43b9-9d34-c8a27a25fc48)

### Resonite Version Number

2024.12.11.1386

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[LOADLOCK - 2024.12.11.1386 - 2024-12-11 23_33_26.log](https://github.com/user-attachments/files/18107455/LOADLOCK.-.2024.12.11.1386.-.2024-12-11.23_33_26.log)

### Reporters

qualia

**Comment by shiftyscales** [comment]
Oop- just noticed this issue was in the wrong tag. While working on the prerelease build, please use the prerelease issue template instead of the bug template, @mxjessie.

I can not reproduce this issue, however. I created a particle system with a static mesh, and saved that- I then ran the conversion on that system and it displays as-expected without issue.

Is there something I'm missing, @mxjessie?

**Comment by 5H4D0W-X** [comment]
By default, meshes are only stored on the GPU, in VRAM. To make them accessible to the particle system – which runs on the CPU – you need to enable the Readable property on the mesh, which copies it to RAM. Procedural meshes are generated on the CPU and thus are always Readable, hence why they work in the particle system without modifications.

**Comment by Frooxius** [comment]
I think I know what this is. The new system doesn't automatically mark the mesh as readable on assignment.

**Comment by Frooxius** [comment]
This should be fixed in 2024.12.13.1342. Can you give it a test please?

**Comment by mxjessie** [comment]
@shiftyscales Ah, my apologies, will do going forward. I suppose the conversion process correctly flips the Readable bit on relevant meshes.

@5H4D0W-X That makes sense, thank you for the explanation.

@Frooxius Yes, that fixed it! Both baked procedural meshes and one-off meshes now immediately begin to render, as expected. Thank you!
