### ISSUE TITLE
TrackedDevicePositioner causes a performance issue

### ISSUE THREAD

**Issue by esnya** [Yellow-Dog-Man/Resonite-Issues#3351]
### Describe the bug?

The `TrackedDevicePositioner` components for feet are causing significant heap memory allocation during every update frame. This is extending frame times and is likely leading to GC, negatively impacting performance.

This issue appears to have been introduced when the `Suppress Feet Simulation` option was added to the settings.

### To Reproduce

This issue occurs in any world where a User slot exists.

### Expected behavior

Expensive operations should only occur during initialization, such as in an Awake event, and should be skipped on subsequent updates based on a completion flag, rather than running during every frame update.

### Resonite Version Number

Beta 2024.12.10.482

### What Platforms does this occur on?

Windows

### What headset if any do you use?

VIVE XR Elite, Desktop

### Log Files

[TSUKUYOMI - 2024.12.10.482 - 2024-12-13 14_25_08.log](https://github.com/user-attachments/files/18121711/TSUKUYOMI.-.2024.12.10.482.-.2024-12-13.14_25_08.log)

The attached logs do not appear to show any entries related to this issue.

### Additional Context

The issue might be related to the Suppress Feet Simulation flag not being correctly handled. A simple adjustment, such as ensuring the flag is properly set to `true`, could likely resolve the problem.

**Comment by Frooxius** [comment]
What are you basing this information on? Is this just a speculation?

We don't have any tools to measure this right now, so I'm a bit confused where would you get this specific information from?

**Comment by esnya** [comment]
I apologize for the earlier lack of clarity in my report. During personal experimentation with dotTrace, I stumbled upon this issue.

While validating the tool, I noticed a significant performance spike in the engine Update steps. This spike consistently manifests as a frame-by-frame call to `Settings.RegisterValueChanges`.

In the attached trace from dotTrace, you can observe that this specific call accounts for **17.1% of the frame time** in this example. This strongly suggests that the function is being executed unnecessarily every frame, leading to a notable performance impact.

Based on my observations, my hypothesis is that the `TrackedDevicePositioner._settingRegistered` flag is never set to true. This could explain why `Settings.RegisterValueChanges` is invoked repeatedly.

Although I used an evaluation version of the tool for this analysis, my intention is to contribute to improving Resonite's performance and overall user experience. I hope the attached FrameGraph provides sufficient detail to aid your investigation.

Please let me know if additional information or clarification is needed.

![Image](https://github.com/user-attachments/assets/d3f9b7d3-2f24-4aec-9454-4dc895ffbcfd)

**Comment by esnya** [comment]
Just to add, the measurements I shared were taken on Desktop in the Local Home environment. 

My guess is that a Unity project would be able to reproduce a similar graph using the built-in profiler.

**Comment by Banane9** [comment]
> Based on my observations, my hypothesis is that the `TrackedDevicePositioner._settingRegistered` flag is never set to true. This could explain why `Settings.RegisterValueChanges` is invoked repeatedly.

You are correct, it is only written to (set to false) in the component's OnDispose and Unregister methods. It is being checked in BeforeInputUpdate before calling the register method, but not set to true afterwards.

**Comment by shiftyscales** [comment]
Thank you for the additional information @esnya @Banane9.

**Comment by Frooxius** [comment]
Fixed this in 2024.12.16.1304! Thanks for this, it's a good catch!
