### ISSUE TITLE
(PhotonDust) Cylinder emitter direction conversion not correct.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3354]
### Describe the issue.

Cylinder emitters have some strange directions. If you rotate them in different directions, the particles end up being forced into a different direction depending on the world space direction.

### To Reproduce

Here's a replication object, Try rotating this different directions.

[CylinderEmittersPackage.zip](https://github.com/user-attachments/files/18132861/CylinderEmittersPackage.zip)

### Expected behavior

For the conversion to not have this result.

### Screenshots

![Image](https://github.com/user-attachments/assets/b998bf05-f17f-4cc8-a615-4fa3b9a4914e)

As you can see, I have a photondust and legacy system here, The cylinderemitters are facing up, However, if I rotate it forward...

![Image](https://github.com/user-attachments/assets/3074a066-8465-417a-8f2a-19417b37ce70)

You get this. This also changes with the world directions.

![Image](https://github.com/user-attachments/assets/fdc6fad9-2b2d-4e11-aa31-ce436daad504)

So this picture is me facing left compared to that other picture.

### Resonite Version Number

Beta 2024.12.13.1342

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

I don't think this is in need of a log file because it's just a conversion issue.

### Reporters

ModernBalloonie

**Comment by Frooxius** [comment]
Fixed this in 2024.12.17.538, thanks for report!
