### ISSUE TITLE
Angular Velocity initial Rotation jitter after enabeling it on Photon dust

### ISSUE THREAD

**Issue by AegisTheWolf** [Yellow-Dog-Man/Resonite-Issues#3357]
### Describe the bug?

A jittering of the initial rotation of a particle as it moves while having an angular velocity applied to it using the module and rotation simulator
(to clarify its the regular angular velocity not 3d) 
(also i'll note that there is no rotation initializer on this and having a constant rotation initializer on a static value it doesn't fix this when i tried).

### To Reproduce

the easiest way is to make a particle system with a shape that can be easily seen rotating and make them move on the Z axis, set its direction in the renderer to local, add a rotation simulator module and a constant angular velocity module (Not the 3d one). and observe the odd behavior.

I will include a Resonite package for the example shown in the screenshots below.

[Angular Velocity Bug Test.zip](https://github.com/user-attachments/files/18133806/Angular.Velocity.Bug.Test.zip)

### Expected behavior

Having the particles start at the same rotation in the beginning unless using a rotation initializer and seeing them rotate at a constant rate to create spiraling designs using the particle system.

### Screenshots

The checkbox is connected to the rotation simulator module component enable state, i took images of it off, of it first starting(which looks fine) and one a few seconds later (the odd offsets) 
I also included screenshots of the particle setup

![Image](https://github.com/user-attachments/assets/cce69652-c5bd-443d-83e4-c2da7607c1d5)
![Image](https://github.com/user-attachments/assets/1cd5ee6a-5b21-4a88-825e-82421278325e)
![Image](https://github.com/user-attachments/assets/9e5095da-b54c-43e2-b289-638eb857eabc)
![Image](https://github.com/user-attachments/assets/1f70b49c-c255-4728-aa17-c906b21a5b24)
![Image](https://github.com/user-attachments/assets/653b151c-07f6-4b05-8ab5-f8f3f0c0d108)
![Image](https://github.com/user-attachments/assets/6c11aa9b-f78d-4f11-b6cd-1fdf022a78be)
![Image](https://github.com/user-attachments/assets/4f1735b3-0983-4b5d-a964-06840e5c64cc)
![Image](https://github.com/user-attachments/assets/ecbcb48c-b646-43d1-a9a7-86f88c1cca61)

### Resonite Version Number

Beta 2024.12.13.1342

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[DESKTOP-SH3F0U4 - 2024.12.12.1243 - 2024-12-13 19_02_02.log](https://github.com/user-attachments/files/18133814/DESKTOP-SH3F0U4.-.2024.12.12.1243.-.2024-12-13.19_02_02.log)

### Additional Context

This was fine in prior updates as i had an example that was working and noticed after recreating it having this wierd behavior. though i thought it was part of the local transform space oddness that unity did.

### Reporters

Aegis_Wolf

**Comment by stiefeljackal** [comment]
The prerelease tag is missing on this issue.

**Comment by Frooxius** [comment]
Fixed in 2024.12.18.477! Thanks for report!
