### ISSUE TITLE
(PhotonDust) If a Particle System and Emitter is deleted, but not the particle style, Ribbons persist forever until the object is deleted.

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#3363]
### Describe the issue.

If a ParticleSystem and Emitter are connected to a ParticleStyle on a different slot, but let's say you have a weapon that you're duplicating the ParticleSystem and Emitter on each time it fires a projectile, When the particlesystem and emitter are deleted, the ribbons freeze mid air and stay there indefinitely until the whole object is deleted. This is an issue I found out with the Battle Nights grenade launcher.

### To Reproduce

Download this Resonite Package: [Deleting Emitter And System Package.zip](https://github.com/user-attachments/files/18138297/Deleting.Emitter.And.System.Package.zip)

Try it as legacy, and delete this slot that I have selected here:
![Image](https://github.com/user-attachments/assets/b08d6dc2-5d3c-48c5-a6b7-f4e8a43a29fc)

Now try it as PhotonDust and delete the slot again, the ribbons will persist indefinitely until you delete the object.
![Image](https://github.com/user-attachments/assets/5bed8a80-2903-415c-ae24-f48a608ae114)

### Expected behavior

For the ribbons to die normally.

### Resonite Version Number

Beta 2024.12.13.1342

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-QBGCSAQ - 2024.12.13.1342 - 2024-12-14 16_35_56.log](https://github.com/user-attachments/files/18138325/DESKTOP-QBGCSAQ.-.2024.12.13.1342.-.2024-12-14.16_35_56.log)

### Reporters

ModernBalloonie

**Comment by Frooxius** [comment]
Fixed this in 2024.12.17.538! THanks for reporting!
