### ISSUE TITLE
Cursor size is host-setting based.

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Yellow-Dog-Man/Resonite-Issues#3369]
### Describe the bug?

See title

### To Reproduce

have more than 2 users in a session.
Change the cursor size.

### Expected behavior

For it to not be host based? lmao?

### Screenshots

![Image](https://github.com/user-attachments/assets/cc21c2bd-214a-4dd3-ac55-36cf689d2e94)

### Resonite Version Number

Beta 2024.12.16.1304

### What Platforms does this occur on?

Windows

### What headset if any do you use?

vive pro eye

### Log Files

[DESKTOP-FO9K87D - 2024.12.16.1304 - 2024-12-16 22_56_26.log](https://github.com/user-attachments/files/18158065/DESKTOP-FO9K87D.-.2024.12.16.1304.-.2024-12-16.22_56_26.log)

### Reporters

3x1t_5tyl3, Charizmase, Xau, Lilosa, Tacusin

**Comment by ProbablePrime** [comment]
Can you elaborate on what you're seeing?

Which cursors are affected by the host? Dash and Worldspace?

**Comment by 3x1t-5tyl3** [comment]
> Can you elaborate on what you're seeing?
> 
> Which cursors are affected by the host? Dash and Worldspace?

When changing the setting it changes for everyone in the session.
It shortly after reverts to their on setting.
It applies in world space and localspace for everyone

**Comment by ProbablePrime** [comment]
Gonna have to see this in person to understand what's going on.

**Comment by 3x1t-5tyl3** [comment]
> Gonna have to see this in person to understand what's going on.

I have a session open. I'll invite ya.

**Comment by 3x1t-5tyl3** [comment]
![Image](https://github.com/user-attachments/assets/0fa11e44-ff38-4378-82b6-e03720a4ef82)
Another note!
Due to this a headless has a size of 0.

**Comment by 3x1t-5tyl3** [comment]
Also another sideeffect, host in vr means the cursor is also 0 for me on desktop

**Comment by ProbablePrime** [comment]
Custom cursors in world space is intentional. Its part of the way things work now.

As for headless, it looks like I clamped the size to a minimum of 0.01f.

That minimum looks too small, so i'll up the clamp

**Comment by ProbablePrime** [comment]
Found it, Need to change up where the settings are registered. 

Will take care of it.

I still dont think, that headless cursors should be 0 based on what im reading, but I'll play around some more!

**Comment by 3x1t-5tyl3** [comment]
> Found it, Need to change up where the settings are registered.
> 
> Will take care of it.
> 
> I still dont think, that headless cursors should be 0 based on what im reading, but I'll play around some more!

Realistically it doesn't matter. That's a sideeffect of it being datamodel synced lol.

**Comment by ProbablePrime** [comment]
Got a fix, testing now :)

**Comment by ProbablePrime** [comment]
Ok the fix now works and preserves multi-user scenarios that's good!

Gonna briefly test Headless stuff too!

**Comment by ProbablePrime** [comment]
I found a fix for this which is now implemented. Expect to see it in a build coming soon.
