### ISSUE TITLE
Cursor disappearing when host is in VR

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#3370]
### Describe the bug?

When the host is in VR and a desktop user hovers over any button, it removes the cursor from the desktop user for the rest of the session, making it very difficult to click on anything.

### To Reproduce

join a session where you are in desktop and the host is in VR
hover over any button
your cursor will now be missing

### Expected behavior

cursors to not disappear forever in desktop mode

### Screenshots

https://github.com/user-attachments/assets/5484e679-4b50-471a-890f-796068311782

### Resonite Version Number

2024.12.16.1382

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-3VH8L1D - 2024.12.16.1382 - 2024-12-16 22_36_27.log](https://github.com/user-attachments/files/18159432/DESKTOP-3VH8L1D.-.2024.12.16.1382.-.2024-12-16.22_36_27.log)

### Additional Context

not 100% sure, but im thinking the fix that was done in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3369 will resolve this issue as it will make it not host dependent anymore 

### Reporters

ultrawidegamer

**Comment by ProbablePrime** [comment]
I think this is also: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3369

**Comment by ProbablePrime** [comment]
As mentioned over in #3369 I found a fix for this which is now implemented. Expect to see it in a build coming soon.

**Comment by Frooxius** [comment]
Fix merged in 2024.12.17.538, thanks for report!
