### ISSUE TITLE
Photon dust legacy conversion fails on certain particles with color and alpha over lifetime data

### ISSUE THREAD

**Issue by Epimonster** [Yellow-Dog-Man/Resonite-Issues#3373]
### Describe the bug?

Some particles with color and alpha over lifetime keyframes fail to accurately convert 1-1 to photon dust particles

### To Reproduce

Public folder of offending items:
resrec:///U-Gareth48/R-4821EBB6C83A164105B8CD13B844EA2E9B52844045A813BEE5FCB4EDA0D609D7

Contains:
- original particle system
- converted particle system
- large number of miscellaneous color and alpha over lifetime particles (called nuke) in case you need more data points

1. Using the data found in this public folder spawn out the first legacy particle system
2. Enable the Legacy Conversion option
3. Spawn out the same legacy particle system
4. Observe the incorrect conversion

### Expected behavior

The particles should be converted 1-1 without discrepancies.

### Screenshots

![Image](https://github.com/user-attachments/assets/d8c66274-e0cd-463d-877a-352c64dabc55)

### Resonite Version Number

2024.12.16.1382

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[BEASTMANS-BOON - 2024.12.16.1382 - 2024-12-17 01_09_32.log](https://github.com/user-attachments/files/18160983/BEASTMANS-BOON.-.2024.12.16.1382.-.2024-12-17.01_09_32.log)

### Additional Context

One note from doing some research, if the blend mode is changed from additive to alpha or transparent they look identical. From this we can conclude the issue is somewhere in the color data

### Reporters

@gareth48

**Comment by Frooxius** [comment]
Fixed this in 2024.12.18.477!

Turns out, that old system would just ignore the alpha in the color gradient, but the new one doesn't. I made it strip the alpha info on conversion.
