### ISSUE TITLE
Reset Settings to Default

### ISSUE THREAD

**Issue by ProbablePrime** [Yellow-Dog-Man/Resonite-Issues#3374]
### Is your feature request related to a problem? Please describe.

All of our settings have defaults.

Sometimes a user might want to reset those settings to default and right now there is not an easy way to do this.

For example if they've accidentally messed too much with the numbers.

### Describe the solution you'd like

Improvements to the settings UI, to enable users to reset to default:
1. Individual Values
2. Entire Setting Components.

### Describe alternatives you've considered

N/A

### Requesters

This is a part of an internal business contract request.

**Comment by ProbablePrime** [comment]
@RyuviTheViali We'll need some UI here.

I haven't started this item and therefore there is no urgency here. 

But I did want to get your input on functionally how this should look. As it is likely you'll be involved when I do get to this item.

I was taking a look at: https://www.gameuidatabase.com/index.php?&set=1&text=settings&scrn=26

And see that in most cases games have a reset button that does "all" settings, to me that sounds kinda silly though as we have so many.

Thank you!

**Comment by RyuviTheViali** [comment]
@ProbablePrime Given we have so many settings relating to many different things, I think there should be at least a couple tiers of setting reset:
- Reset all settings
- Reset settings in category
- Reset individual setting

All reset buttons would have confirmation (double-click) actions so they don't get reset haphazardly.

For resetting all settings, I could see a standalone button for that in the Misc. category.
For resetting settings per category, I could see a button at the bottom of each category (Audio, Controls, etc.) for doing that, or alternatively a reset button per setting group (i.e. Earmuff, Laser Smoothing, Volume, etc.).
For resetting individual settings, I could see adding a small button per setting, maybe on the right side (and additionally possibly on hover only, to reduce visual clutter), which allows that singular setting and its values to be reset.

**Comment by Nytra** [comment]
Should I close my issue in favor of this one? https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1750

**Comment by ProbablePrime** [comment]
We'll actually close in favor of yours, Froox has some info there that's good.

#1750 it is!

**Comment by ProbablePrime** [comment]
Re-collating over to: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3374

Sorry >.<
