### ISSUE TITLE
[PhotonDust]The Skinned Mesh Emitter is not synchronized with the movement of the original mesh renderer

### ISSUE THREAD

**Issue by Fukuro99** [Yellow-Dog-Man/Resonite-Issues#3385]
### Describe the bug?

When I used a SkinnedMeshEmitter to insert an avatar's SkinnedMesh, I noticed that it was not synchronized with the avatar's movement.
It seems that it can be synchronized by manipulating the component values.

### To Reproduce

Put the avatar's SkinnedMeshRenderer into the SkinnedMeshEmitter and it will work.

### Expected behavior

SkinnedMeshEmitter should now match the behavior of SkinnedMeshRenderer

### Screenshots

Sorry for the cut off video.
It's only synchronized when you are changing the component's value.

https://github.com/user-attachments/assets/74c4053a-499d-4a2f-828c-79dce3c178a5

### Resonite Version Number

Beta 2024.12.13.1342

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-D13OE44 - 2024.12.17.538 - 2024-12-17 21_29_02.log](https://github.com/user-attachments/files/18169530/DESKTOP-D13OE44.-.2024.12.17.538.-.2024-12-17.21_29_02.log)

### Reporters

Resonite:fukuro
Discord:fukuro8232

**Comment by Frooxius** [comment]
Fixed this in 2024.12.18.477! Thanks for report!
