### ISSUE TITLE
RadialForce Particle Module - Add a "minimum size" and "maximum size"

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [Yellow-Dog-Man/Resonite-Issues#3413]
### Is your feature request related to a problem? Please describe.

Currently when using radial force even with low numbers particles gain an ***insane*** amount of speed when they hit the center of a radialForce component.

### Describe the solution you'd like

A way to define radial force as a sphere with min and maximum size.

### Describe alternatives you've considered

maybe a custom texture 3d that'd limit the velocity? But this requires texture 3d knowledge which i don't quite have yet and i feel like shouldn't be needed.

### Additional Context

Realistically I'm sure there's another way I'm missing? I'd love to learn more but as it stands rn it seems rather annoying that radial force makes particles gain basically an insane amount of speed (kinda like reaching a blackhole ig lol?)

It does however make sense mathematically. Which is not the issue. I'm sure there's usecases for this.
Why I came up with the idea of defining a "minimum" and maximum size.

That or being able to boolean out radial forces with eachother?
Ideas are grand here.

### Requesters

3x1t_5tyl3

**Comment by Frooxius** [comment]
Added this 2024.12.26.1378!

Also wanted to note: 
> (kinda like reaching a blackhole ig lol?)

That's pretty much what this is! The system by default uses the inverse square law, so it's kinda like reaching the singularity - it's going to slingshot you quite fast.
