### ISSUE TITLE
[PhotonDust] Constant force toggle for Radial Force

### ISSUE THREAD

**Issue by BaxterOttoman** [Yellow-Dog-Man/Resonite-Issues#3429]
### Is your feature request related to a problem? Please describe.

The radial force module for PhotonDust allows for some very neat effects. It appears to apply the force inversely proportional to the distance between the point and the particles, which makes sense for simulating a number of real world natural forces. There are some less than realistic effects I would like to use a radial force to produce, however, and they would benefit from a constant force towards a target directly.

### Describe the solution you'd like

I would like to see a toggle added for the radial force module that causes the module to apply constant force to the particle, in the same way linear force does, but in the direction of the target point.

### Describe alternatives you've considered

There aren't many good alternatives I can think of. You can't apply linear force with different values per particle.

### Requesters

Baxter

**Comment by Frooxius** [comment]
I think this could be added. I think best would actually be enum, with three modes for the force attenuation:
- InverseSquare
- Linear
- Constant

**Comment by Frooxius** [comment]
I've added the modes in 2024.12.26.1378!
