### ISSUE TITLE
PhotonDust HSV Range Initializer

### ISSUE THREAD

**Issue by gameboycjp** [Yellow-Dog-Man/Resonite-Issues#3431]
### Is your feature request related to a problem? Please describe.

When I tried making confetti using the new particles, I noticed that there was no randomization for hue in particular.

### Describe the solution you'd like

I'd like an initializer module that generates colors based on an HSV range rather than RGB.

### Describe alternatives you've considered

Multiple RGB initializers is the best I could come up with, but it still isn't quite what I'm after. 

### Requesters

@gamethecupdog

**Comment by Frooxius** [comment]
This is easy enough!

**Comment by Frooxius** [comment]
Added in 2024.12.26.1378! Thanks!
