### ISSUE TITLE
Option to display a debug visual for PhotonDust emitter

### ISSUE THREAD

**Issue by LeCloutPanda** [Yellow-Dog-Man/Resonite-Issues#3442]
### Is your feature request related to a problem? Please describe.

Being unable to determine the shape of an emitter makes it a bit difficult to line them up with models/etc

### Describe the solution you'd like

A debug mesh similar to the debug meshes that you can trigger for rigs and depending on the emitter type it would just use the different procedurals.

### Describe alternatives you've considered

Cranking the emission rate of the particles and emitting from shell to see the general outline

### Requesters

[Panda (LeCloutPanda on discord)](https://github.com/lecloutPanda)

**Comment by Redd56** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/3262 already an issue

**Comment by Frooxius** [comment]
Closing as duplicate. Thanks!
