### ISSUE TITLE
Launch command -DontAutoOpenCloudHome doesn't work

### ISSUE THREAD

**Issue by TisFoolish** [Yellow-Dog-Man/Resonite-Issues#346]
### Describe the bug?

Simply put, the launch parameter `-DontAutoOpenCloudHome` doesn't work. I still load into my cloud home, despite not wanting to. I know Sloppy McFloppy has also experienced the same

### To Reproduce

Add `-DontAutoOpenCloudHome` to your launch parameters and see that you still load your cloud home.

### Expected behavior

To not load my cloud home

### Resonite Version Number

2023.10.18.449

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index, Desktop

### Log Files

[log file](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13050104/CATBED.-.2023.10.18.449.-.2023-10-19.23_49_24.log)

### Reporters

Res: Foolish (myself), Sloppy McFloppy

**Comment by XDelta** [comment]
@TisFoolish This is no longer the correct launch argument. Try `-DoNotAutoLoadHome`

**Comment by ProbablePrime** [comment]
@XDelta is correct, we renamed this option.

Due to this I'll be closing this.
