### ISSUE TITLE
Usage of `Thread::Abort` is not safe or future-proof

### ISSUE THREAD

**Issue by Nihlus** [Yellow-Dog-Man/Resonite-Issues#354]
### Describe the bug?

FrooxEngine uses `Thread::Abort` in certain places to terminate background worker threads. While a common method in the past, modern runtimes and architectural designs strongly recommend against using hard aborts (to the point of  .NET 5 and above outright having disallowed its use entirely).

The issues with `Abort` primarily stem from its rather merciless termination of a thread, particularly when aborting a thread that is not the current thread, as it is not known which state the target thread is in (and, by extension, which code may or may not have executed). This can cause both managed and unmanaged resources to leak and might leave external code in unpredicatable states. At present, `WorkProcessor::ThreadWorker::Abort` is perhaps the most obvious place where this happens.

Several alternatives exist, but perhaps the most direct replacement would be `Thread::Interrupt` - this method allows the thread to continue running, but at the first instance of the thread transitioning into a waiting state, a `ThreadInterruptedException` will be thrown, which can be handled normally and allows for controlled cleanup of acquired resources.

### To Reproduce

The issue is not directly reproducible in the desktop or headless client, as they run on the Mono runtime, but both are affected on shutdown. The nature of `Abort` is such that hard-to-diagnose and execution-dependent problems of a wide variety could occur, depending on what the aborted thread was (or wasn't) doing at the time.

### Expected behavior

Threads should terminate in a controlled fashion, allowing for predictable cleanup and shutdown instead of being forcibly aborted.

### Resonite Version Number

2023.10.19.620

### What Platforms does this occur on?

Windows, Linux

### Log Files

No relevant log files are available.

### Additional Context

While this problem may not typically affect normal users of Resonite, the issue has been encountered in the wild when developing external tooling for Resonite and FrooxEngine. The problem usually occurs on shutdown when objects are disposed in a manner not perfectly consistent (order, number of disposal calls) with the desktop client.

### Reporters

Jax (Resonite), jgullberg (Discord)

**Comment by TisFoolish** [comment]
Is this still an issue with the.NET 8 Headless prerelease? Meaning is it still in use. I know that one instance of Abort caused an exception, was reported in https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2543, and subsequently fixed soon after.

**Comment by Geenz** [comment]
This has been fixed.
