### ISSUE TITLE
big color picker buttons don't scale translated text

### ISSUE THREAD

**Issue by Muppeq** [Yellow-Dog-Man/Resonite-Issues#359]
### Describe the bug?

The two big buttons at the bottom of the color picker panel display the translated content (german in the screenshot) too big, this forces a linebreak. I have not tested other translations.

### To Reproduce

Switch language to german and open a color picker, for example in the cloud home tablet to set the light colors. Screenshot was taken in Beta 2023.10.20.831.

### Expected behavior

Decrease the text size so that 'Abbrechen' and 'Speichern' are printed on a single line.

### Screenshots

![color_picker_german](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147259359/210120ab-1ddc-40a0-818c-9aec08c8baca)

### Reporters

Muppeq

**Comment by JackTheFoxOtter** [comment]
I already reported this in https://github.com/Yellow-Dog-Man/Locale/issues/30.
My suggestion there was adding <nobr>, but really it should just auto-scale.

**Comment by RyuviTheViali** [comment]
I've gone ahead and fixed this on the color picker! Turns out horizontal auto scaling wasn't enabled on those button's text fields. Thanks!
