### ISSUE TITLE
Dawn Modular Set - Snapper Sets Transforms to 0

### ISSUE THREAD

**Issue by Konshu** [Yellow-Dog-Man/Resonite-Issues#362]
### Describe the bug?

When attempting to use the Dawn Modular Set to create a home, some snapper attempts result in no snap point being shown, and a click will reset the snappable objects transforms to 0.

Issue captured on video:
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/157110/fc55721f-e410-4f79-b740-6f4992c67809

### To Reproduce

1. Spawn two snappable objects, in test case I used "Corridor Straight Slope 1.5m Solid Right" and "Corridor Straight Slope 1.5m Solid Left".
2. Spawn and equip Snapping tool.
3. Select slope side of right object and attempt to snap to left object slope.
4. Notice the original right object disappears, it now has transforms value of 0.

Issue captured on video:
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/157110/fc55721f-e410-4f79-b740-6f4992c67809

Initial Transform Values:
![Dawn_bug_03](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/157110/a7870f0d-ff2f-40ad-abc8-1aba80f72dd3)

Final Transform Values:
![Dawn_bug_04](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/157110/8bd37b52-5efc-46e3-b4eb-b84e9d20d534)

### Expected behavior

The expected behavior is that snappable surface of two slopes should snap cleanly to each other. If snapping fails a prompted error should be visible. 

### Additional Context

Attempt was in fresh world with Dawn Module Set items spawned on version 2023.10.20.831

### Reporters

Konshu, Elektrospy

**Comment by RyuviTheViali** [comment]
I've fixed this issue! Now when you perform an action with the tool which is invalid in some way, nothing happens instead of the selected item going to world origin. Closing this, thanks!
