### ISSUE TITLE
Eye tracking data

### ISSUE THREAD

**Issue by The-furf-of-July** [Yellow-Dog-Man/Resonite-Issues#370]
### Is your feature request related to a problem? Please describe.

Eye tracking has a lot of fun possibilities, but currently the only way to utilise it is by modifying your avatar to expose the values for use. It is currently impossible to make any content for use by users with eye tracking without requiring per-person modification or establishing a standard for dynvars.

There is no way to test its potential without prohibitively exclusive setup and prep.

### Describe the solution you'd like

Flux nodes to detect if a user has eye-tracking support or not, and retrieve values from the tracking such as the looking position, eyeclosed values, etc.

Having privacy options to disable people's access to this information would make sense, but I don't think it should be on by default, so that people can make experiences tailored to eye tracking without requiring setup.

### Describe alternatives you've considered

Standardising a naming convention for eye tracking dynvars, and either convincing eye tracking users to use them, or getting them built into the eye manager.
Even if eye manager values were exposed by default we'd need the ability to tell if it was default eye movement or if they have an eye tracking data source.

**Comment by ProbablePrime** [comment]
You can already do this.
1. Slap Users-> Common Avatar System -> Face -> Avatar Raw Eye Data on a slot
2. Set the user property of this component to your target user
3. Check the "is tracking" booleans are "true"
4. Access the raw data from the other fields.

This works wirelessly(as in without a direct reference to the eye manager).

Does this solution meet your needs?

**Comment by The-furf-of-July** [comment]
I could've sworn this wasn't an option in Neos. Would it still work if driven with Local User?

**Comment by ProbablePrime** [comment]
Im not sure if driving would work, but you can try.

I mostly use a button to write to it or sometimes I use OnStart events or whatever.

It has been around forever, I actually have 2 pending research papers that use it.
