### ISSUE TITLE
Legacy Steam VR Input Handling

### ISSUE THREAD

**Issue by ScranerSaphora** [Yellow-Dog-Man/Resonite-Issues#374]
### Is your feature request related to a problem? Please describe.

Not really, the feature I'm requesting would allow my hands to function while using a cloud computer service (while I travel). This feature was accessible during the Neos Platform.

In the old Neos Launcher the option was called "Force Legacy Steam VR Input Handling" Which is what I'm requesting to be brought into Resonite.

### Describe the solution you'd like

Bring the old "Force Legacy Steam VR Input Handling" option (originally in the NeosVR launcher) into Resonite by either making a launcher with an option. Or by making a steam launch command to initiate it (if one already exists, please inform me what it is).

### Describe alternatives you've considered

n/a

### Additional Context

The reason for this request is the fact that I use a Quest 2 stand alone device when I travel rather than bringing my whole rig (I use my Index while I'm at home). This whole setup involves using a paid cloud computer service. Without the feature I'm requesting , my hands won't function in Resonite.

**Comment by ProbablePrime** [comment]
Hello,

You can add `-LegacySteamVRInput` to your Steam Launch Options, https://help.steampowered.com/en/faqs/view/7D01-D2DD-D75E-2955

To enable this feature.
