### ISSUE TITLE
Add Copy Value to the Drive Field Menu

### ISSUE THREAD

**Issue by mralext20** [Yellow-Dog-Man/Resonite-Issues#382]
### Is your feature request related to a problem? Please describe.

the addition of the Drive / Drive (write back) menu when dropping a field onto another field is very helpful! however, not always am i trying to drive a field, but simply copy the value from A to B. 

### Describe the solution you'd like

add a Copy Value or One Time Copy to the Drive / Drive (Write Back) menu that pops up when dropping a field onto another field  ( 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/4016295/ef38413a-d766-4bdc-87f3-f909e5f2f7a1)

### Describe alternatives you've considered

copying the individual values from one field to another, this takes more time when coping a float3 or colorX values

**Comment by Nytra** [comment]
I guess it would work similar to the ValueProxyExtensions mod. https://github.com/art0007i/ValueProxyExtensions

**Comment by TisFoolish** [comment]
ValueProxyExtensions is the mod that adds this extra button, right?
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38511571/b170b4aa-dc44-4da4-817e-c48c9f2c3c98)

I *really* like how intuitive that is and it doesn't require an extra button click like adding it to the context menu would.

**Comment by mralext20** [comment]
I mainly propose adding it to the drive / drive wire back menu as it's an
existing UI, and in the exact place I would expect such a feature to be
added to.

**Comment by TisFoolish** [comment]
It's also slower and by the time something like this would get added it'll break peoples muscle memory.

**Comment by mralext20** [comment]
Yeah this works. Thanks!
