### ISSUE TITLE
Short Form ColorX to Hex code not working correctly

### ISSUE THREAD

**Issue by ImErinTheBunny** [Yellow-Dog-Man/Resonite-Issues#384]
### Describe the bug?

The ColorXToHexCode node while using Short Form is not clamped correctly. If you use a 1 for any of the RGB values the output will be 10 for that channel rather than F. This will make the hex code invalid because the character count is off.

### To Reproduce

Using a ColorXToHexCode node with the ShortForm bool set to true, input a color with any of the R, G, or B values greater than or equal to 1. Whichever channel you use will output 10 instead of a single character.

### Expected behavior

The maximum for any single color channel should be F. All channels should also only be one character long and the full output should be 3 characters without alpha.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/148178510/7b41462e-7b29-448b-a3a7-8eaab47225ad)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/148178510/e45d9820-bf8a-44cc-ab00-07a8cea408f4)

### Resonite Version Number

Beta 2023.10.20.831

### What Platforms does this occur on?

Windows

### Log Files

[PC - 2023.10.20.831 - 2023-10-21 19_53_28.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13062179/PC.-.2023.10.20.831.-.2023-10-21.19_53_28.log)

### Additional Context

While you are editing the node, you should fix the text of the node saying Color XTo Hex Code where X and To are one word. I just noticed it while writing this and dont want to make another bug report for that silly thing.

**Comment by PJB3005** [comment]
This appears to still be broken in Beta 2024.2.12.1430

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8107459/2ea1da9b-b8dd-4df5-af08-4424bebcee04)

**Comment by ProbablePrime** [comment]
related https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1404

**Comment by ProbablePrime** [comment]
I've fixed this again, I applied the fix previously to some auto-generated code and not the generator for said code so the next time we ran the auto-generator it broke the fix.

I have now applied the fix to the generator, so once this is merged in. It won't happen again.

**Comment by Frooxius** [comment]
Merged fix in 2024.7.4.1347, thanks!
