### ISSUE TITLE
Enhancement: Add Instragram Support

### ISSUE THREAD

**Issue by FlameSoulis** [Yellow-Dog-Man/Resonite-Issues#385]
### Is your feature request related to a problem? Please describe.

As per Discord user SpikeTheRikkor's [initial statement](https://discord.com/channels/1040316820650991766/1165427981611696180/1165427981611696180):
> Can we make links work from Instagram like they did with Twitter [because] I tried to copy a link to a video and it just pasted the actual link instead of the video when I put it in.

This was tested and validated with a random link from Instagram.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/6835457/214c7014-e3f6-45f6-9858-6e298d14fa2c)

### Describe the solution you'd like

Current services like Twitter and YouTube's media links correctly import into the world for videos. If at all possible, add Instagram to the same support lineup.

### Describe alternatives you've considered

The only other solution would be to download the video and upload it that way locally, but without tools, this would not be user-friendly.

### Additional Context

This ticket was created on behalf of another user.

**Comment by Frooxius** [comment]
This should be quick enough, just need to add it to whitelist, assuming yt-dlp supports it.

**Comment by Frooxius** [comment]
Added in 2024.2.12.1430, thanks!
