### ISSUE TITLE
Ability to Delete/Rename Groups.

### ISSUE THREAD

**Issue by Zandario** [Yellow-Dog-Man/Resonite-Issues#394]
### Is your feature request related to a problem? Please describe.

For those of us who inherented a group from migrated accounts or have old groups we'd like to use for something else, it would be nice if we were able to either rename or just out right delete old groups.

### `/renameGroup <group> <name>`

Renames the public name of the group.

### `/DeleteGroup <group>`

Fully deletes the group "account". 
Additionally it might be a good idea for additional confirmation for deletion.

### Describe alternatives you've considered

Other alternatives I've considered would require a inventory rework, such as:
* Secondary press for a drop-down menu with a edit group option
* * Furthermore this could currently use the current inventory selection options and use something like `Edit World Metadata`, but this would require much more work to implement.

### Additional Context

I have an old group called `The Neo-Illuminate`, an Avali group I either want to rename to something more platform themed, or delete/rename it for one of my other projects.

**Comment by MargoSizemore** [comment]
> Renaming groups is already possible, but is currently a command only available to platform admins, @Zandario. In the interim, if you wish for the group's name to be changed, please submit a ticket at https://support.resonite.com/.

I believe they mean they want you to create a command to rename groups, like how previously only admins could rename people, but now they can use a command to do it.

**Comment by Frooxius** [comment]
Merged this in 2024.9.30.1215, thanks!
