### ISSUE TITLE
Add a default facet to the home screen of the dash to show worlds that you are currently in

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#396]
### Describe the bug?

This would be extremely helpful for new and experienced users alike because it would make it very easy to see which worlds you are in and to focus or close out of them.

I think new users often don't immediately understand the concept of being in multiple worlds at once, and this would help get that point across and also maybe help them to more easily close worlds that they don't want to keep open as a way to increase performance.

There is a facet made by ProbablePrime called the WorldsYou'reInFacet and this is an example of the kind of facet that should be made default. (resrec:///U-ProbablePrime/R-cb3d5f03-ffa6-4e09-adf2-e07757b9b3e8)

### To Reproduce

N/a

### Expected behavior

N/a

### Screenshots

N/a

### Additional Context

N/a

### Reporters

Nytra (Discord: nytra)

**Comment by MargoSizemore** [comment]
Yes, I see new users in 5 worlds at once all the time.

**Comment by amplified1** [comment]
Either this or improving how the worlds you are in are communicated in the worlds menu, the world system really isn't intuitive to a lot of new users.

**Comment by MargoSizemore** [comment]
> Either this or improving how the worlds you are in are communicated in the worlds menu, the world system really isn't intuitive to a lot of new users.

Yeah, maybe separate and label them more.

**Comment by Stellanora64** [comment]
Could I propose the facet be placed in the worlds tab instead of the home tab?

something like this (the facet shown can be found here under facets: `resrec:///U-art0007i/R-8DD3F38F960FFA10E71D909CC7F09587D1EA9FD14F4E44F96EE5E357F78F6BE4` ) : 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91010433/a000e96b-a80b-4df9-b2f8-9a96067d9124)

**Comment by MargoSizemore** [comment]
> Could I propose the facet be placed in the worlds tab instead of the home tab?
> 
> Mainly as that way everything worlds related would be all in the worlds tab. The downside to this is that less worlds can be shown to the user at any given time.
> 
> something like this? (the facet shown can be found here under facets: `resrec:///U-art0007i/R-8DD3F38F960FFA10E71D909CC7F09587D1EA9FD14F4E44F96EE5E357F78F6BE4` ) : ![image](https://user-images.githubusercontent.com/91010433/281380473-476b5f98-9c54-445d-81d5-b14d76bdced0.png)

I like this! It being like tabs in a browser is something users are likely already experienced with, so it may help them to see it like this.

**Comment by AegisTheWolf** [comment]
This Facet will require some changes code-wise to properly make this a feature additionally to creating the facet itself.

**Comment by shiftyscales** [comment]
Seeking input from @Frooxius - it could also be useful to have a similar facet to replace the legacy world switcher since we have hand containers for facets now.

**Comment by MargoSizemore** [comment]
> Seeking input from @Frooxius - it could also be useful to have a similar facet to replace the legacy world switcher since we have hand containers for facets now.

Hm? What's this mean?

**Comment by shiftyscales** [comment]
There is a setting which allows you to enable the legacy world switcher- this is an old function which shows all of the sessions you are currently in, and allowed you to switch between them by clicking on them, @MargoSizemore.

**Comment by MargoSizemore** [comment]
> There is a setting which allows you to enable the legacy world switcher- this is an old function which shows all of the sessions you are currently in, and allowed you to switch between them by clicking on them, @MargoSizemore.

I always used that, is hand facet containers a new things that it replaces if you enable it?

**Comment by shiftyscales** [comment]
It's a separate feature, @MargoSizemore- but has overlap as it can functionally replace the legacy world switcher by letting the user place a facet on their hand which can do the same things.

**Comment by ProbablePrime** [comment]
Superseeded by #2393
