### ISSUE TITLE
Migrated content using fresnel unlit shader does not appear as expected

### ISSUE THREAD

**Issue by kulzae** [Yellow-Dog-Man/Resonite-Issues#40]
### Describe the bug?

When migrating content the fresnel unlit shader appears differently between the two

### To Reproduce

View content using fresnel unlit shader in platform using gamma lighting and view the same content in resonite

### Expected behavior

The content will look similar or as close as possible

### Screenshots

Visor in gamma platform
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40366296/fdda62be-718f-4b90-b79c-7059bdc20165)

Visor in resonite after migration
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40366296/6bb21b28-33ab-476d-b79e-27d1dddf022f)

Visor in resonite after applying correction listed below
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/40366296/8c3865d8-4d82-4c9c-9da1-8ef184a37f1c)

### Resonite Version Number

2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Vive Pro Eye

### Log Files

[RENEGADE - 2023.10.13.743 - 2023-10-13 18_23_21.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12899826/RENEGADE.-.2023.10.13.743.-.2023-10-13.18_23_21.log)

### Additional Context

To correct this set the gamma curve parameter to 1 and:

If the far color is brighter than the near color multiply exponent by 2.2
If the far color is darker than the near color  multiply exponent by 0.454545

This will adjust the values of the shader to be similar

### Reporters

Kulza

**Comment by kulzae** [comment]
An example of uncorrected migrated content can be found in the vending machines in the VBLFC pool hangout resrec:///G-VBLFC/R-1cec65cc-877a-4b51-8d4e-250fd6f76b9a

**Comment by Geenz** [comment]
Fixed in SU1.
