### ISSUE TITLE
Make typing complex variable/object types less obscure

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#427]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I see a type that I need to provide somewhere (for example the `Nullable<Chirality>` on the context menu items), but I don't know how to type that as a custom type for creating a component or a Flux node. Some types are less obscure than others, but I had to ask others for this ``System.Nullable`1[[FrooxEngine.Chirality, FrooxEngine]]``.

### Describe the solution you'd like

Add functionality for the component attacher to accept types typed as shown in the Inspector.

### Describe alternatives you've considered

Asking those who know, because there's no plausible way to figure out these types yourself.

### Additional Context

https://discord.com/channels/1040316820650991766/1166506573363957841/1166512609755934730

**Comment by badhaloninja** [comment]
I'm like 95% sure you don't need the FrooxEngine reference like `System.Nullable`1[FrooxEngine.Chirality]`
I'm pretty sure that's only needed for non System or FrooxEngine types

Anyway, having the component selector recognize the displayed format would be really nice

**Comment by Frooxius** [comment]
This is something we can do, but we'll have to write our own parsing system for this. Right now we're just piggybacking off the .NET's type parsing.

**Comment by stiefeljackal** [comment]
Since is it encouraged to point out community solutions and mods, there is currently a mod called [Resonite-TypeType](https://github.com/Earthmark/Resonite-TypeType) by Earthmark that demonstrates parsing the type by its display name. I just thought to point that solution out to give you an idea, @Frooxius.

**Comment by stiefeljackal** [comment]
@Frooxius I believe this has been satisfied with the release of `2024.4.30.495`, correct?

> Implement custom nice type parser to simplify type input
> * You can now use the simplified Type<GenericArgument> format, similar to type definition directly in C# instead of the internal .NET type format
> * All types are displayed using the nice format as well

**Comment by ProbablePrime** [comment]
Closing
