### ISSUE TITLE
Force Load Texture toggle

### ISSUE THREAD

**Issue by Sharkmare** [Yellow-Dog-Man/Resonite-Issues#438]
### Is your feature request related to a problem? Please describe.

Currently, when a Texture is set to readable, it can ONLY be read once it is loaded (i assume into VRAM) just having the asset stored somewhere on the object does not allow you to read the texture if it is not used on any material.

### Describe the solution you'd like

Either, a separate toggle that forces textures to load (into VRAM?) despite not being assigned to a material or a change in how the Readable property functions on Texture assets so that textures that are not on a material can still be read. separately.

The reason this may be good as a separate toggle is there may be cases where the texture not being accessible until it is on a material may be intended

### Describe alternatives you've considered

Just make a dummy material to "initialize" the texture

**Comment by Frooxius** [comment]
You can already do this. 

Attach AssetLoader<A> component from Assets/Utility and make it reference the texture. This system is generic and supports any asset.
