### ISSUE TITLE
Security Policy page is titled "User Guidlines"

### ISSUE THREAD

**Issue by ExoTheWicker** [Yellow-Dog-Man/Resonite-Issues#439]
### Describe the bug?

When browsing the policies page I noticed that the "Security Policy" page has the same title as the "User Guidelines" page.

### To Reproduce

Go to the policies page and click on "Security Policy".

### Expected behavior

The expected behavior is for the page to be titled "Security Policy"

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/70044982/e30e68ca-6589-47e7-9426-77a627175799)

### Resonite Version Number

N/A (Website)

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Web Browser

### Log Files

N/A

### Additional Context

This issue occurs on the website not in the game.

### Reporters

ExoTheWicker

**Comment by Ardescar** [comment]
Thank you :-) but that was posted here https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/411

**Comment by ProbablePrime** [comment]
Closing as duplicate of #411
