### ISSUE TITLE
Soft Driving Fields (Driver Override)

### ISSUE THREAD

**Issue by lxw404** [Yellow-Dog-Man/Resonite-Issues#440]
### Is your feature request related to a problem? Please describe.

Right now in order to allow fields to be driven from multiple sources they have to go through some sort of monstrous multiplexing which reduces the re-usability and configurability of independent systems.

It would be much more manageable and modular if there was some sort of way to "soft drive" or "speculative drive" a field that is currently being driven to allow for that field's driver to be overridden temporarily while it is still technically being "driven" by the original, then relinquish its control eventually back to the original.  This would allow for systems such as animations which can temporarily override VRIK, dynamic bones, etc. and then give back control to the original drivers after the animations are complete without having to build excessive multiplexing Flux specific to each overridden target.  It would also allow for the ability for gesture overrides, ragdoll physics conceivably in the future, and many other systems which shouldn't have to know about one another in order to interact.

### Describe the solution you'd like

A "soft drive" would refer to a drive target that can be overridden by another driver or soft driver.

A soft drive target keeps track of all of the prior drivers in a stack, and whenever the target gets overridden, that new driver is pushed to the top of the stack.  In the exclusionary case, only the top driver on the stack would affect the output target.  Elements are popped off of the stack when they stop driving and when no element remains, the soft drive target is undriven.

For example, I have a soft drive target on my blendshape `Smile`, then attach a driver from `System A` on it.  Later I override it with something from `System B`, then `System C`, so the drive stack looks like the following:

- `System C Driver`
- `System B Driver`
- `System A Driver`

Whenever either of those stop driving, or get disabled possibly, then the corresponding driver is popped off the stack.  Let's say `System B` stops soft driving, the stack will look as follows:

- `System C Driver`
- `System A Driver`

An additional yet complex version of this could be to implement weights to each element on the stack and combine them additively/average/min/max/etc. which would allow smooth transitions between driving elements (similar to blend trees in other software).

### Describe alternatives you've considered

The current alternative to this is to pre-plan all of the subsystems that have to be able to override a particular driver well in advance  and create a very large (or continuously increasing in size) multiplexer for them.

`Min`, `Max`, and `Average` flux nodes can be utilized for various effects, but get unwieldly just the same.

Alternatively the `FieldHook` node in Flux can be used to try to accomplish this, however it doesn't allow for overlapping systems to drive the same output and will instead ignore all later drivers, only allowing the first driver to assert itself and forgetting about past drivers, and it is also extremely painful to set this up for overriding even just the VRIK.

Long term this is not very scalable since it requires all of the independent systems to be combined and merged together.

**Comment by Frooxius** [comment]
This is already supported by the data model - drivers can "hook" the fields, which means they can still be modified by external sources, but those changes get proxied to the component that is doing the driving, which can then do whatever it needs.

For example Spinner component does this, where you can rotate the object that's being spun and it will recalculate its properties.

Driving mechanisms can be arbitrary complex though, which means that some systems do not allow this, as they do not have a way to reconcile external changes easily and for some it has not been implemented. 

For ProtoFlux you can use the "Hook" node to achieve this.

In either case, as a general mechanism, this already exists in a way, so I'm closing this issue.

**Comment by lxw404** [comment]
I didn't know that a field hook can remove drives, however the main crux of the issue still stands even with field hook; there is no way to restore the controlling driver after hooking to it.  In the case of trying to tie two systems together, they now have to have complete knowledge of each other and which things may take control.

I'd say that warrants another solution, either with some way for field hooks to restore control back, or write the reference of the prior controlling hook.  Even with just that simple addition though, there's no way to go back multiple steps.

**Comment by Nytra** [comment]
A way to get the ActiveLink ILinkRef would be nice, then it could be stored, and maybe there could be nodes added such as Link and ReleaseLink for ILinkable fields.

**Comment by Frooxius** [comment]
Field hook doesn't remove a drive. It's a way to drive something and get notified when non-driving elements are trying to modify it.

You can use that to design systems where you need a system that has exclusive control, but still want to accept external changes.

If you want to move drives between systems, you should probably design them to do that. But generally that is something that's a bit odd - you should have just one thing driving a system, it's not something that should go back and forth. That to me indicates some oddity in the design.

**Comment by lxw404** [comment]
I would agree that drives are generally a single term thing, but in reality the way we've been building systems around that premise leads to some issues...  Let's consider just the case where you want things to control a blink blendshape.  The Eye Manager might need to control it, a headpat controller might need to override it as well, then maybe a nose boop, then maybe an additional future system, but all of them would have to be coalesced into one final system with a max/min that you didn't really intend to make starting out probably...  It's a bit unwieldly to assume at the start that you know about those future additions ahead of time and it leads to a lot of monolithic code unfortunately.  Unless I'm not thinking of the right way to modularize things which want to take control of an output or coalesce multiple things, I believe there should be a way to make things more modular, or even just specify that this particular output is something you want to be able to override.
