### ISSUE TITLE
NaN input into MultiCubicLerp or MultiCosineLerp node crashes the user evaluating

### ISSUE THREAD

**Issue by marsmaantje** [Yellow-Dog-Man/Resonite-Issues#443]
### Describe the bug?

When you try to evaluate the MultiCubicLerp or MultiCosineLerp node with a display with NaN as input for the lerp progress the world crashes for that specific user

### To Reproduce

1. grab either MultiCubicLerp or MultiCosineLerp node
2. set its lerp progress input to NAN
3. Pull out a display from the interpolation node
4. Observe

resrec:///U-marsmaantje/R-3d8366db-10b4-435f-bccb-0a9367bd1fe9

### Expected behavior

The node either outputs NaN as well, or defaults to lerp progress 0

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/60362806/ee92c1c3-cd6d-461b-9a9a-5f8222652a09)

### Resonite Version Number

2023.10.20.831

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[DESKTOP-K2H0L1O - 2023.10.20.831 - 2023-10-26 02_36_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13171813/DESKTOP-K2H0L1O.-.2023.10.20.831.-.2023-10-26.02_36_35.log)

### Additional Context

Accidentally came across this when the lerp input came from a divide node with both inputs set to zero, thus resulting in NaN

### Reporters

marsmaantje

**Comment by Frooxius** [comment]
Fixed this in 2023.11.13.1343, thanks!
