### ISSUE TITLE
New cloud home briefly starts set to Anyone

### ISSUE THREAD

**Issue by DanteTucker** [Yellow-Dog-Man/Resonite-Issues#448]
### Describe the bug?

When loading into a newly generated cloud home, the session will be set to Anyone for a short time. 
Users are able to successfully join during this time.

I have seen the timespan range from 1 seconds, to 10 seconds. Depending on the users loading speed and various conditions.

### To Reproduce

Log in without a cloud home.

### Expected behavior

Cloud home should always start private.

### Resonite Version Number

2023.10.20.831

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-TBLIEGS - 2023.10.20.831 - 2023-10-26 14_13_03.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13181298/DESKTOP-TBLIEGS.-.2023.10.20.831.-.2023-10-26.14_13_03.log)

### Reporters

Dante

**Comment by ProbablePrime** [comment]
As described in #2284, Depending on how long it takes to load a world, we were applying the access level late.

We now apply it before it even opens, so that it is set the moment it exists as part of creation.

**Comment by Frooxius** [comment]
Fixed in 2024.9.4.357, thanks!
