### ISSUE TITLE
Since SteamVR 2.0 update FPS has been limited to 30 FPS on HP Reverb G2

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#451]
### Describe the bug?

Since the SteamVR 2.0 update FPS has been limited to 30 FPS even though I have a refresh rate of 90 Hz on my reverb g2.

Resonite also seems to detect this as the fps display is not maxed out but refuses to go higher than 30 fps, this is even in the local home with the Steam VR resolution set to the lowest I could make it.

### To Reproduce

launch Resonite with the latest build of Steam VR stable with a HP Reverb G2.

### Expected behavior

The HP Reverb G2 should not be capped at 30 fps but instead 90.

### Screenshots

![20231027184541_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91010433/e5e6d26d-55ad-457c-aeb6-8caa0383deca)

### Resonite Version Number

2023.10.20.831

### What Platforms does this occur on?

Windows

### What headset if any do you use?

HP reverb G2

### Log Files

[DESKTOP-F65B6FQ - 2023.10.20.831 - 2023-10-27 18_43_21.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13188120/DESKTOP-F65B6FQ.-.2023.10.20.831.-.2023-10-27.18_43_21.log)

### Reporters

Stellanora

**Comment by antrobot1234** [comment]
Have you tried restarting your PC? I had the same issue going on with Quest 2 via airline but restarting my PC fixed it.

**Comment by Crusher50** [comment]
> Have you tried restarting your PC? I had the same issue going on with Quest 2 via airline but restarting my PC fixed it.

I have re-started my pc and still capped at 30 fps

**Comment by Geenz** [comment]
Is this reproducible in other games?

**Comment by Crusher50** [comment]
not that I'm aware of. 

Also an update on this, I force quit Resonite due to my dash being frozen and once I re-opened it, it's now fixed?

Not sure why shutting down Resonite manually would be any different than restarting my PC, nothing else changed that I'm aware of. I'll leave this issue up if there is possibly something in the logs you could find but feel free to close it if no one else is experiencing this issue.

**Comment by Crusher50** [comment]
second update, the bug is back after I restarted my PC for something else

**Comment by Geenz** [comment]
To be clear we can't handle SteamVR bugs.  We need more information on this though, including performance data from other applications.

**Comment by Crusher50** [comment]
VRChat performs as expected, and I can confirm the bug in Resonite is still occurring
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91010433/f65e578e-67fe-49ef-97f0-0e89d49c59f0)

**Comment by Crusher50** [comment]
I was about to close this issue, as after WMR bugged out and I had to force quit that the issue has once again fixed itself, but other users have also noticed a similar issue so I will leave this up for now.

There is a discord thread here with some discussion on the issue: https://discord.com/channels/1040316820650991766/1168967307188514897

**Comment by Krzeszny** [comment]
I've never experienced this issue and I started playing in January.

**Comment by Stellanora64** [comment]
@Krzeszny yeah I almost closed this issue before, but I then saw some users that were stuck at 45 fps and thought it might be related.

I haven't really experienced this for awhile though, kind of forgot about this issue >-> 

I think I might just close it at this point. Not entirely sure what fixed it but it might have been an issue with SteamVR and not Resonite itself. Don't really remember though.
