### ISSUE TITLE
Keyboard does not visually show symbols on number row

### ISSUE THREAD

**Issue by FlameSoulis** [Yellow-Dog-Man/Resonite-Issues#458]
### Describe the bug?

There have been reports from users that could not complete registration because they could not find the '@' symbol on the virtual keyboard, requiring the use of desktop mode to complete the setup. While this may be common knowledge to people who type a lot, not everyone is used to knowing where all keys are on a keyboard, especially shifted ones.

### To Reproduce

1. Spawn an interface that requires the use of the keyboard.
2. Notice the lack of indication that additional symbols exist.

### Expected behavior

1. Spawn an interface that requires the use of a keyboard.
2. Keyboard indicates keys that have alternative symbols when Shift is pressed.

### Screenshots

![20231027043919_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/6835457/8d5c0b12-7f1a-4e59-9d60-da3f73a4185a)
![20231027043906_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/6835457/64b96667-1f7b-433a-acf8-2fb05cd32340)

### Additional Context

On most modern keyboards, Shifted symbols are usually displayed where present, such as the number row, the ?, brackets, etc.

This was noticed previously by other people, but the [discussion on the Steam Community](https://steamcommunity.com/app/2519830/discussions/0/3879347633291918590/) highlighted the need to bring this up.

Additionally, the general fix demonstrated in the screenshots just has a text label on the lower right, a mild offset, and reversed symbol logic. This was just for demonstration purposes.

### Reporters

Discord: flamesoulis; IGN: U-Flame-Soulis

**Comment by RyuviTheViali** [comment]
The default keyboard has been updated to include visual indicators on symbol buttons to show the alternate symbol when shift is enabled. Attached are two screenshots of the new keyboard changes. Thank you, closing!

![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/32752458-b6b4-4def-b7bc-ed50fa3dae37)
![Image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/d9f859a9-9655-41c0-a6a5-567ebeb3b993)
