### ISSUE TITLE
add count expose to component multiplexers

### ISSUE THREAD

**Issue by antrobot1234** [Yellow-Dog-Man/Resonite-Issues#464]
### Is your feature request related to a problem? Please describe.

currently, component multiplexers do not expose the total amount of slots the multiplexer has. This is odd, considering their flux counterparts do.

### Describe the solution you'd like

I would suggest having a field where you can drop in int value reference that the component drives to mach it's slot count (this is to prevent it from being able to be written.)

### Describe alternatives you've considered

the current alternative is to have a manual component value field for each of your component multiplexers and update that manually whenever you add or remove content from your multiplexer. this system is not very dynamic or ease to use.

### Additional Context

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/21179158/d6792678-1c22-4711-8eb2-88533fea660b)

**Comment by JackTheFoxOtter** [comment]
This might be another case of "problem will disappear once we have collection support" as this will allow you to get the size of ANY list that's used in components. I think this makes more sense than building it into every one individually.

**Comment by Frooxius** [comment]
Yes we would handle this generically through collection support - there would be a generic "Count" node and you just feed it the source you want to count: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/572

The alternative is we hunt every component down that has lists and add extra code to each to handle this, which doesn't scale well.
