### ISSUE TITLE
Default keyboard to be in Resonite essentials public folder

### ISSUE THREAD

**Issue by win189** [Yellow-Dog-Man/Resonite-Issues#470]
### Is your feature request related to a problem? Please describe.

I had an issue the other day where my Onscreen in-game keyboard wouldn't load i was using Turks I was not bothered by that but could not find it in  my inventory anymore to cycle it off and go to default

### Describe the solution you'd like

The default keyboard to be in the "Resonite Essentials" public folder  for easy trouble shooting

### Describe alternatives you've considered

just saving it in my folder

**Comment by RyuviTheViali** [comment]
I have added all of the default UI elements into a new folder in Resonite Essentials under "Default UI". Closing this, thanks!
