### ISSUE TITLE
Ctrl+V does not keep pasting when held.

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#481]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when trying to paste the same thing multiple times into a text field since auto-key-repeat does not work for Ctrl+V.

### Describe the solution you'd like

Holding Ctrl+V should keep pasting, the same way that holding A keeps typing A.

### Describe alternatives you've considered

Not doing this. (Why?)

**Comment by Frooxius** [comment]
This is now supported in 2023.11.13.1343! Thanks!
