### ISSUE TITLE
Group names appear with quotation marks

### ISSUE THREAD

**Issue by ClimberJ** [Yellow-Dog-Man/Resonite-Issues#482]
### Describe the bug?

Groups with spaces in their name will have their name shown in quotation marks in the Inventories tab.

### To Reproduce

Create or join a group with spaces in its name and allocate storage to it. Then look under Inventories in your Inventory.

### Expected behavior

I expect the name of a group to be shown without quotation marks.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/98227175/84008bf1-6e40-4a58-9bcd-0b29acc95429)

### Resonite Version Number

2023.10.19.620

### What Platforms does this occur on?

Windows

### Log Files

Not applicable

### Reporters

Climber (climber._)
Virgil (virgilcore)
DetectiveBot (reality.exe)

**Comment by shadowpanther** [comment]
Was the group just created with quotation marks as part of its name?
I'm in `Creator Jam` group, and I don't see any quotes there.

**Comment by ClimberJ** [comment]
It was a error on my part. I for some reason thought that names that included spaces required quotation marks.
