### ISSUE TITLE
Light Tool Tooltip with incorrect or broken translation string for "Change color".

### ISSUE THREAD

**Issue by Nammi-namm** [Yellow-Dog-Man/Resonite-Issues#483]
### Describe the bug?

The light tool "Change color" option does not seem to be using localisation properly.
![image](https://github.com/Yellow-Dog-Man/Locale/assets/3219044/96046b90-a292-4cc7-a0a7-0c717e7acb88)
Japanese is reporting as 100% translated. So if its there it should be there. 

I've also tried to find the exact string by name in en.json and found both `"Tooltips.Brush.ChangeColor" : "Change Color",` and `"Tooltip.Color.Picker": "Color Picker",` which both would open up the same window. But it seems the tool is expecting something along the lines of `"Tooltip.Light.ChangeColor"` or `Tooltip.Light.Color.Picker` instead perhaps?

I found out that the Geometry Line brush does show "Change color" correctly.
![image](https://github.com/Yellow-Dog-Man/Locale/assets/3219044/ca94c322-8524-4806-84a6-a3b200b8a352)

### To Reproduce

find the Light Tool in Inventory > Resonite Essentials > Tools. Or press 6 on your keyboard in desktop mode. Opening up your radial menu you'll see the change colour option is not translated in any language that is 100% translated. But it is correct on the Geometry Line Brush Tool in the same spot in the inventory.

### Expected behavior

The light tool should have all its strings localised just like the Geometry line brush tool.

### Screenshots

See above.

### Additional Context

This was included as a missing string in https://github.com/Yellow-Dog-Man/Locale/issues/89 and was merged into Resonite. 

I'm not sure if I should have posted this here or there. Since there are existing strings in en.json I don't see why the Light tool can't re-use already existing strings for the exact same button. So I'm not sure if the tool needs fixing or there's just a missing translation string.

### Reporters

Nammi / "namminamm"

**Comment by Banane9** [comment]
It's missing localization in the code (in `LightTool.GenerateMenuItems()`)
![change color missing localization](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2124570/2cc5ff52-89a7-4525-b88e-3a536e96089f)

**Comment by Frooxius** [comment]
Merged this in 2024.6.24.1317, thanks!
