### ISSUE TITLE
Alternatives to Patreon?

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#497]
### Is your feature request related to a problem? Please describe.

I have been trying to support Resonite for over a month now and Patreon keeps declining my card... Contacted my bank and they said it is not on their end as it is declined before it gets to them... Contacted Patreon support and after waiting a week for a reply (because they dont offer a number to call for support and only really slow email support)  they said it is that it is something on the banks side... all other non-patreon payments have been going through fine and at this point i am extremely frustrated, no longer have my complimentary storage and have no reasonable way of contacting Patreon to figure this out. 

### Describe the solution you'd like

Implement alternative options for supporting Resonite like ko-fi or direct payment?

### Additional Context

This issue has gotten so bad that both parties (Patreon and my bank) have directly suggested me to use another bank 🙃

**Comment by gentlecolts** [comment]
Perhaps somewhat tangential but I'd also like to add that displaying a means of acquiring storage ingame would be a nice addition to this request as well, I can't count how many times I've had people ask "how do i get more storage"

**Comment by ProbablePrime** [comment]
> Perhaps somewhat tangential but I'd also like to add that displaying a means of acquiring storage ingame would be a nice addition to this request as well, I can't count how many times I've had people ask "how do i get more storage"

This would be a separate issue. Thank you.

**Comment by alexderpyfox** [comment]
Steam payment needs to be added all those other things won't work in countrys that swift has sanctioned

**Comment by FuzzyFoxe** [comment]
I was wondering similarly; is it possible for twitch commands to be accessible to patrons, or perhaps storage be linkable to twitch subscription too? It'd be nice to save money on these things.. ^^;

**Comment by Mr-CostlessClaw** [comment]
@Frooxius Moving to Ko-Fi. The savings from Patreon could equal an additional 1,700$ a month.  
https://youtube.com/shorts/uZwugrR5jks?si=z34zw6AUwLuWKFqr

**Comment by Geenz** [comment]
We do have plans to introduce alternative payment methods, including but not limited to direct payments through our website.  Stay tuned.

**Comment by Frooxius** [comment]
@Mr-CostlessClaw Yes, we've found similar values in our analysis, so it's definitely something we're actively looking into, but there's no ETA on it yet.

**Comment by AmasterAmaster** [comment]
I would like for there to be a permanent storage alternitive option, even if the prices were significantly higher for that, just due to the nature of resonite having so many awesome things and i wish to save them (and not everything has a public folder for said things)

But yea, just my hope for that.

**Comment by Frooxius** [comment]
When you say permanent storage alternative option, do you mean paying for storage once and you get it forever?

**Comment by WinterCaverns** [comment]
> When you say permanent storage alternative option, do you mean paying for storage once and you get it forever?



PCloud would be a great option but yes it's one massive payment for a permanent amount of storage, exporting from resonite to files then to PCloud.. this also would eliminate patreon, thus wouldn't work out.

**Comment by AmasterAmaster** [comment]
Basically yes, but i know that it can be difficult on the business side of things. But i can also see it from the consumer side where they would be buying you the hard drives to store their stuff in. Of course it would have to go through your channels and decions to make that a possible thing. So it could go either way i feel.

**Comment by Frooxius** [comment]
We're very unlikely to provide permanent storage like that. The upfront payment would have to be huge, like probably thousands of dollars, if not more.

The hard-drives and actual storage isn't really the main problem here. What gets costly is everything around it - running the harddrives (electricity, redundancy with failures...), running API & compute servers to make that data accessible, running other services to make it usable and so on.

Don't forget that development & support of the platform itself is also paid from the support. Having storage tiers is just easiest way to "sell it", but it covers way more stuff than just raw storage.

**Comment by WinterCaverns** [comment]
> Don't forget that development & support of the platform itself is also paid from the support. Having storage tiers is just easiest way to "sell it", but it covers way more stuff than just raw storage. 

This is what I was referring too overall, if another storage site was cheaper for permanent storage people would resort to that, and it would stop the flow funding for the platform.

So as much as you would want an external storage site, it's not possible that storage site would share a cut of the money that was being paid into it by a good amount

**Comment by AmasterAmaster** [comment]
For an example, I would love to have 1TB of storage, and I dont mind paying for it in full, plus shipping and handling, plus any taxes and import/export costs, plus services fees you (the dev team) have decided for me to pay extra for the privilege to have that kind of storage (under your full discretion)

And yes, I understand that the service part is the cost as well, so maybe adding a fee that requires that amount of storage to be used for a certain amount of time, and then after that time if a significant amount has been used, it can then be kept (incentivizing people to make and keep content on the platform as well).

Granted it is unlikely, but I also feel it would be an option available to those that are not fond of the subscription plan option.

**Comment by Frooxius** [comment]
It's missing an important point too though - external storage site itself is insufficient to run Resonite. Without the API servers, compute and so on, the storage would be useless - you wouldn't be able to do anything with it.

**Comment by WinterCaverns** [comment]
> It's missing an important point too though - external storage site itself is insufficient to run Resonite. Without the API servers, compute and so on, the storage would be useless - you wouldn't be able to do anything with it. 

^ this

**Comment by AmasterAmaster** [comment]
I feel that is kinda implied with Resonite being always online currently, I feel consumers would know what they are getting themselves into by that point, but I digress.

**Comment by WinterCaverns** [comment]
I would say this topic has exhausted its potential at this point. There is nothing that can be done as of this time and stage.

**Comment by WinterCaverns** [comment]
> I feel that is kinda implied with Resonite being always online currently, I feel consumers would know what they are getting themselves into by that point, but I digress.

You dingus

**Comment by TheNovaBeast** [comment]
> ### Is your feature request related to a problem? Please describe.
> 
> 
> 
> I have been trying to support Resonite for over a month now and Patreon keeps declining my card... Contacted my bank and they said it is not on their end as it is declined before it gets to them... Contacted Patreon support and after waiting a week for a reply (because they dont offer a number to call for support and only really slow email support)  they said it is that it is something on the banks side... all other non-patreon payments have been going through fine and at this point i am extremely frustrated, no longer have my complimentary storage and have no reasonable way of contacting Patreon to figure this out. 
> 
> 
> 
> ### Describe the solution you'd like
> 
> 
> 
> Implement alternative options for supporting Resonite like ko-fi or direct payment?
> 
> 
> 
> ### Describe alternatives you've considered
> 
> 
> 
> ### Additional Context
> 
> 
> 
> This issue has gotten so bad that both parties (Patreon and my bank) have directly suggested me to use another bank 🙃 


I'd like Steam payment at least to be able to get more storage and a supporter badge in game, Resonite linking themselves to steam services though is quite a struggle.

**Comment by Geenz** [comment]
I'm closing this in favor of #2819.  We will create additional issues as needed for other payment processors as we add them.

**Comment by gentlecolts** [comment]
No plan for other options, such as steam payments?

**Comment by Geenz** [comment]
Please see #2819.  Additional payment methods will be announced as we get there.  I'll also note that Steam takes a whopping 30% for any payments and subscriptions processed through their platform.

**Comment by Frooxius** [comment]
If you'd like to see more specific payment options, you can open an issue for those specifically. We can then discuss their specifics, because each one is unique, so that's easier than one megaissue.

**Comment by TheNovaBeast** [comment]
> If you'd like to see more specific payment options, you can open an issue for those specifically. We can then discuss their specifics, because each one is unique, so that's easier than one megaissue.


PayPal balance 🥺 all my other subscriptions use this

**Comment by shiftyscales** [comment]
@TheNovaBeast - As indicated above- if you have a request for a specific payment method you would need to [open a new issue](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/new?assignees=shiftyscales&labels=enhancement&projects=&template=feature-request.yml).

**Comment by TheNovaBeast** [comment]
> @TheNovaBeast - As indicated above- if you have a request for a specific payment method you would need to [open a new issue](https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/new?assignees=shiftyscales&labels=enhancement&projects=&template=feature-request.yml).

I've opened a new issue before and got redirected here so no thank you

**Comment by shiftyscales** [comment]
Re-opened #2380 for you @TheNovaBeast as I believe there are still possible options that could be explored there in future.
