### ISSUE TITLE
ListEditors when viewed in inspectors have uneven alignment

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#521]
### Describe the bug?

ListEditors like the ones for bones and materials in SkinnedMeshRenderers are misaligned which looks bad and also could make it slightly more difficult to click the buttons on the left side.

### To Reproduce

Open an inspector and find a component which has a list.

### Expected behavior

The list elements are aligned in a consistent way which looks better.

### Screenshots

![2023-11-04 09 31 35](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/a7779d06-aecc-41eb-b7b2-fed56f263a46)

In this image I have edited the component UIX on the right to have better alignment. I did this by lowering the text size of the numbers on the left so that they dont affect the positioning of the UIX to the right of the numbers.
![2023-11-04 09 28 53](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/33497204-a876-4a6e-8d2a-4537655e856c)

### Resonite Version Number

Beta 2023.10.20.831

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[DESKTOP-H976HO2 - 2023.10.20.831 - 2023-11-04 03_33_33.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13256277/DESKTOP-H976HO2.-.2023.10.20.831.-.2023-11-04.03_33_33.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: nytra)

**Comment by Nytra** [comment]
![2023-11-25 21 05 59](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/53ca45a5-7edd-4204-aa8f-6c8894993064)

I think this could be fixed by setting the PreferredWidth on the LayoutElement of the Panel slot to a really high number so it uses all of the available space.

**Comment by Frooxius** [comment]
I'm closing this, as I don't think this is serious enough to really be worth our time, considering that the inspector UI will be reworked completely.
