### ISSUE TITLE
Resonite Infrastructure Uses Mono Incompatible SSL Certificates

### ISSUE THREAD

**Issue by Enverex** [Yellow-Dog-Man/Resonite-Issues#523]
### Describe the bug?

This is actually a continuation of https://github.com/Neos-Metaverse/NeosPublic/issues/3613 which was never resolved, but the fix should be easy enough.

Basically Mono has a garbage SSL certificate store and doesn't work properly with Let's Encrypt, at least not reliably. The workaround for this is to either A) not use Mono or B) use any SSL certificate other than Let's Encrypt. Actual SSL certificates are stupidly cheap these days so that shouldn't be an issue, alternatively there's a handful of free SSL providers now (some even compatible with certbot) that could be used instead, none of which have this issue (that I'm aware of).

### To Reproduce

Use a Linux server running Mono. You'll see errors like:
```
Exception running PUT request to https://skyfrost-archive.resonite.com/assets/(redacted). Remaining retries: 6. Elapsed: 3.88s
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception. ---> Mono.Btls.MonoBtlsException: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

... resulting in those connections outright failing.

### Expected behavior

For the connection to succeed.

### Resonite Version Number

2023.10.19.620

### What Platforms does this occur on?

Linux

### Log Files

Headless log showing the issue:

[headless.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13256804/headless.log)

### Additional Context

Tangently this is also why https:// links to some content content outside of Neos/Resonite in worlds didn't work, again I assume due to the use of Mono so it's all round best that anyone also hosting content for the game outside of the platform itself also avoid using Let's Encrypt.

**Comment by Banane9** [comment]
I remember having to make a custom "Validate() => Yes" kinda certificate-validator to make a telegram bot run properly on Mono, back in the day... 😩

**Comment by Frooxius** [comment]
Since this is a continuation of past project, we cannot accept this unfortunately, as stated on our guidelines for making issues here: https://github.com/Yellow-Dog-Man/Resonite-Issues

You are free to make a new similar issues affecting specifically Resonite though.

**Comment by Banane9** [comment]
> You are free to make a new similar issues affecting specifically Resonite though.

But Enverex specifically described what the issue is for Resonite as well, only linking back to the old issue for continuity / further details 🤔

**Comment by Enverex** [comment]
> Since this is a continuation of past project, we cannot accept this unfortunately, as stated on our guidelines for making issues here: https://github.com/Yellow-Dog-Man/Resonite-Issues
> 
> You are free to make a new similar issues affecting specifically Resonite though.

This does affect Resonite, that's why I posted it...

**Comment by Frooxius** [comment]
That doesn't matter. If you read our guidelines, they state:
> Do not refer to projects we worked on in the past we're unable to use materials or issues from past projects.

Since you explicitly stated at the beginning this is a continuation of issue from past project, we cannot use this. I'm sorry.

**Comment by Banane9** [comment]
> Since you explicitly stated at the beginning this is a continuation of issue from past project, we cannot use this.

So, any link at all back to old issues makes the whole report void? What about comments linking it?

**Comment by Geenz** [comment]
Expanding upon Froox' comments-

If this is an issue on _this_ platform, please submit it as a new issue with current diagnostics collected on Resonite.  Please leave other platforms (even if you believe it's a continuation of another issue from another platform) out of it - we do not and cannot support those platforms, nor can we say for certain that issues affecting those platforms have the same root causes.

We do this to keep a clean flow of issues that are directly actionable on Resonite.  Do not include them.
