### ISSUE TITLE
Storage stays full forever

### ISSUE THREAD

**Issue by TravisTheTaidum75** [Yellow-Dog-Man/Resonite-Issues#533]
### Describe the bug?

The storage usage amount suddenly started saying I'm at 1 GB and 100% full and started deleting any recently saved item or avatar. This issue will not fix itself no matter what I do.

### To Reproduce

I don't know how to, this just randomly happened, I'm stuck like this and it won't fix in any way to be able to reproduce it.

### Expected behavior

The storage usage amount should say that I'm at about half usage, because I calculated the amount of megabytes each item used myself, and it did not equal 1GB, it equaled 500 ish megabytes.

### Screenshots

![20231105155825_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/149972905/a18cc059-f555-432a-bdd8-6ab31d3fb3fb)
![20231105163201_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/149972905/e40c359b-c430-48b3-9eb7-e9a8253fee9f)
![20231105163206_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/149972905/6e77bdae-6d6c-4e19-bed6-a48280382653)

### Resonite Version Number

2023.10.20.831

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro with Valve Index controllers

### Log Files

I cannot replicate the issue, I don't know how this happened at all, but I can try giving the most recent log file I have.
[DESKTOP-9M35Q2V - 2023.10.6.1038 - 2023-10-09 13_44_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13260869/DESKTOP-9M35Q2V.-.2023.10.6.1038.-.2023-10-09.13_44_10.log)

### Additional Context

I deleted almost everything of what I had, the storage usage amount never changed. Even through restarting the game, it never updated to the actual amount I'm using, it just stayed the same and kept deleting any recent things I save. My avatar isn't even that big of a file size either, it's 88-ish megabytes.

**Comment by ProbablePrime** [comment]
Hey, Thank you for making this issue.

Based on what I'm reading the issue might be due to hidden or unclear storage usage on your account. 

Send `/requestRecordUsageReport` to the Resonite bot in your contacts screen. It will email you a report about what is taking up space.

**Comment by TravisTheTaidum75** [comment]
Storage usage report for TravisTheTaidum75:

Raw Sum: 1.99 GB (this is NOT total usage, as it counts each instance of shared asset)
Name: U-TravisTheTaidum75 Home
Path:
Id: R-Home
Type: world
IsMessageItem: False
IsPublic: False
Size: 1.50 GB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-7344ad5e-2358-4738-a19c-f50fed3d4e25
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-3d2a3437-e943-4fa0-9af1-e5e4333a3e98
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-798102d9-b376-4a19-98f9-fe1fcd026946
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-b6226996-9992-4aa5-ace9-dac9f007d8c7
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: Battery Level and Controller Indicator
Path: Inventory\Wawa
Id: R-a43a5df8-c6b8-41aa-aac5-3a5be3dd0823
Type: object
IsMessageItem: False
IsPublic: False
Size: 28.52 MB
-------------------
Name: Grip Grappler 2.1
Path: Inventory\Wawa
Id: R-893157cc-1fdc-43c5-805d-8d90d345465e
Type: object
IsMessageItem: False
IsPublic: False
Size: 22.55 MB
-------------------
Name: Battery Level Indicator - dankpods edition
Path: Inventory\Wawa
Id: R-97806675-bd5c-4a35-a4f0-af5e13e0769c
Type: object
IsMessageItem: False
IsPublic: False
Size: 20.67 MB
-------------------
Name: UserCompass
Path: Inventory\Wawa
Id: R-b957730d-bf29-4c6e-a8d5-a8c83d20ddc4
Type: object
IsMessageItem: False
IsPublic: False
Size: 18.17 MB
-------------------
Name: Playlist 2.1
Path: Inventory\Wawa
Id: R-257d904f-dd2c-48be-b335-0597cac7974e
Type: object
IsMessageItem: False
IsPublic: False
Size: 17.83 MB
-------------------
Name: TravisTheTaidum's Hangout Home
Path: Inventory\Worlds
Id: R-178bce9d-45e9-42cd-9b7a-98dd05456659
Type: object
IsMessageItem: False
IsPublic: False
Size: 17.77 MB
-------------------
Name: Local Clock
Path: Inventory\Wawa
Id: R-689d658e-0eae-4528-9fab-69a9b0c5e585
Type: object
IsMessageItem: False
IsPublic: False
Size: 17.56 MB
-------------------
Name: IrixFreshTaidum.fbx
Path: Inventory\Wawa
Id: R-d609a896-813d-482c-b821-9bd0d87a2317
Type: object
IsMessageItem: False
IsPublic: False
Size: 7.38 MB
-------------------
Name: Spinning banana bread
Path: Inventory\Wawa
Id: R-f3c8ca01-6838-4ef5-aa23-b245e1ea7cef
Type: object
IsMessageItem: False
IsPublic: False
Size: 1.76 MB
-------------------
Name: sandvic
Path: Inventory\Wawa
Id: R-fa465418-0111-4e63-a76d-e3028f6decd9
Type: object
IsMessageItem: False
IsPublic: False
Size: 817.85 kB
-------------------
Name: DarkSugar Sticker
Path: Inventory\Wawa
Id: R-46008567-457d-4a68-81be-c98fd778e7ec
Type: object
IsMessageItem: False
IsPublic: False
Size: 375.69 kB
-------------------
Name: Ueueeu v1.0 Installer
Path: Inventory\Wawa
Id: R-1d29e26d-e7d4-4405-8e41-1131d0fc011e
Type: object
IsMessageItem: False
IsPublic: False
Size: 196.42 kB
-------------------
Name: Voice Message
Path:
Id: R-30074e51-2ac8-4396-8ab5-bc4a3c5f104e
Type: audio
IsMessageItem: True
IsPublic: False
Size: 13.41 kB
-------------------
Name: Settings
Path:
Id: R-Settings
Type: object
IsMessageItem: False
IsPublic: False
Size: 2.07 kB
-------------------

Mind you, I have only added a few things to the home world that were only megabytes in size

**Comment by TravisTheTaidum75** [comment]
Storage usage report for TravisTheTaidum75:

Raw Sum: 1.99 GB (this is NOT total usage, as it counts each instance of shared asset)
Name: U-TravisTheTaidum75 Home
Path:
Id: R-Home
Type: world
IsMessageItem: False
IsPublic: False
Size: 1.50 GB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-7344ad5e-2358-4738-a19c-f50fed3d4e25
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-3d2a3437-e943-4fa0-9af1-e5e4333a3e98
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-798102d9-b376-4a19-98f9-fe1fcd026946
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: InfTravisTaidum.fbx
Path: Inventory\Wawa
Id: R-b6226996-9992-4aa5-ace9-dac9f007d8c7
Type: object
IsMessageItem: False
IsPublic: False
Size: 88.72 MB
-------------------
Name: Battery Level and Controller Indicator
Path: Inventory\Wawa
Id: R-a43a5df8-c6b8-41aa-aac5-3a5be3dd0823
Type: object
IsMessageItem: False
IsPublic: False
Size: 28.52 MB
-------------------
Name: Grip Grappler 2.1
Path: Inventory\Wawa
Id: R-893157cc-1fdc-43c5-805d-8d90d345465e
Type: object
IsMessageItem: False
IsPublic: False
Size: 22.55 MB
-------------------
Name: Battery Level Indicator - dankpods edition
Path: Inventory\Wawa
Id: R-97806675-bd5c-4a35-a4f0-af5e13e0769c
Type: object
IsMessageItem: False
IsPublic: False
Size: 20.67 MB
-------------------
Name: UserCompass
Path: Inventory\Wawa
Id: R-b957730d-bf29-4c6e-a8d5-a8c83d20ddc4
Type: object
IsMessageItem: False
IsPublic: False
Size: 18.17 MB
-------------------
Name: Playlist 2.1
Path: Inventory\Wawa
Id: R-257d904f-dd2c-48be-b335-0597cac7974e
Type: object
IsMessageItem: False
IsPublic: False
Size: 17.83 MB
-------------------
Name: TravisTheTaidum's Hangout Home
Path: Inventory\Worlds
Id: R-178bce9d-45e9-42cd-9b7a-98dd05456659
Type: object
IsMessageItem: False
IsPublic: False
Size: 17.77 MB
-------------------
Name: Local Clock
Path: Inventory\Wawa
Id: R-689d658e-0eae-4528-9fab-69a9b0c5e585
Type: object
IsMessageItem: False
IsPublic: False
Size: 17.56 MB
-------------------
Name: IrixFreshTaidum.fbx
Path: Inventory\Wawa
Id: R-d609a896-813d-482c-b821-9bd0d87a2317
Type: object
IsMessageItem: False
IsPublic: False
Size: 7.38 MB
-------------------
Name: Spinning banana bread
Path: Inventory\Wawa
Id: R-f3c8ca01-6838-4ef5-aa23-b245e1ea7cef
Type: object
IsMessageItem: False
IsPublic: False
Size: 1.76 MB
-------------------
Name: sandvic
Path: Inventory\Wawa
Id: R-fa465418-0111-4e63-a76d-e3028f6decd9
Type: object
IsMessageItem: False
IsPublic: False
Size: 817.85 kB
-------------------
Name: DarkSugar Sticker
Path: Inventory\Wawa
Id: R-46008567-457d-4a68-81be-c98fd778e7ec
Type: object
IsMessageItem: False
IsPublic: False
Size: 375.69 kB
-------------------
Name: Ueueeu v1.0 Installer
Path: Inventory\Wawa
Id: R-1d29e26d-e7d4-4405-8e41-1131d0fc011e
Type: object
IsMessageItem: False
IsPublic: False
Size: 196.42 kB
-------------------
Name: Voice Message
Path:
Id: R-30074e51-2ac8-4396-8ab5-bc4a3c5f104e
Type: audio
IsMessageItem: True
IsPublic: False
Size: 13.41 kB
-------------------
Name: Settings
Path:
Id: R-Settings
Type: object
IsMessageItem: False
IsPublic: False
Size: 2.07 kB
-------------------

Mind you, I have only added two things to the home world that were only small double digit megabyte size

**Comment by TravisTheTaidum75** [comment]
Also my bad for closing and re-opening the thread, misclicked

**Comment by ProbablePrime** [comment]
From the looks of it your home world is at fault here, I would suggest changing/deleting it to another world. 

Unfortunately this is not a bug, your home world is just too big.

**Comment by TravisTheTaidum75** [comment]
I tried that already and it didn't fix the problem though, I tried the smallest worlds possible and nothing changed

**Comment by gameboycjp** [comment]
Maybe see if you've got the large home world causing issues under the Worlds tab, under the My Worlds category.
