### ISSUE TITLE
[Linux Headless] RuntimeData folder not in the correct location

### ISSUE THREAD

**Issue by TisFoolish** [Yellow-Dog-Man/Resonite-Issues#543]
### Describe the bug?

The RuntimeData folder is in the root directory of the headless software instead of in ./Headless

### To Reproduce

Run a headless on Linux, see it not find folder

### Expected behavior

Fully boot

### Resonite Version Number

2023.11.7.274

### What Platforms does this occur on?

Linux

### What headset if any do you use?

Headless

### Log Files

[log.txt](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13276793/log.txt)

**Comment by shadowpanther** [comment]
There was an update pushed to fix the headless after the main client update. Didn't it fix this?

**Comment by bredo228** [comment]
> There was an update pushed to fix the headless after the main client update. Didn't it fix this?

It did not.

**Comment by foxworth42** [comment]
As a temporary fix I was able to just create the missing directory and launch the headless afterwords.

**Comment by liny-fox** [comment]
I've noticed that just making the missing directory makes the headless unable to shutdown properly and hang after issuing the shutdown command, while copying the RuntimeData folder to the proper location fixes the shutdown problem.

**Comment by Frooxius** [comment]
The folder was missing due to the build now having split Windows and Linux headless folders and I forgot to copy it to the other one. Fixed in 2023.11.8.335, thanks!
