### ISSUE TITLE
Slashes in Dynamic Variable Names

### ISSUE THREAD

**Issue by gameboycjp** [Yellow-Dog-Man/Resonite-Issues#55]
### Is your feature request related to a problem? Please describe.

For organizational purposes, I categorize my impulses, variables, and so forth with a folder style structure, but slashes cause dynamic variables not to work.

### Describe the solution you'd like

I'd like for slashes to be supported in DynVar names.

### Describe alternatives you've considered

Even more than just slashes would be nice too, I'm sure someone could make use of such.

### Additional Context

Just recently I've made preparations for a clothing system with dozens of dynamic variables, all variables using many slashes to categorize things. But I discovered after setting up the variables on both my item base and my avatar that slashes break dynamic variables.

**Comment by RileyGuy** [comment]
Clarification on this: Slashes are used in variable names for direct bindings.

For instance, if you're under "MyVariableSpace" but want to reference the world's space, you'd name your variable "World/MyWorldVariableName"

**Comment by gameboycjp** [comment]
That doesn't help with something like KarIO/Clothes/Cirvulp/Apron/Equipped where KarIO is already the space I'm using. If I make dynvar spaces for each of these layers, will it work?

**Comment by RileyGuy** [comment]
I think perhaps it might be wiser to work with the system. Underscores work just fine, so you could segment your variable names with underscores rather than slashes, as those are used for binding directly to certain variable spaces.

**Comment by gameboycjp** [comment]
I mean, am I not doing that already? Slashes after the first causing variables to seemingly be ignored seems more arbitrary than anything to me. If slashes after the first were used in the name instead of blocking off variables entirely, it would probably be a pretty decent change.

**Comment by TheJebForge** [comment]
You could also use dots instead of slashes, I don't think having multiple slashes will ever be supported due to slash being the separator between Dynamic Variable Space and the actual variable name. But they should at least implement some highlighting to tell that the variable name is invalid and will not link

**Comment by gameboycjp** [comment]
Dots are a good idea, thank you. I don't know if I'll be able to replace
the thousands of slashes in my dynvars, but if I find a way I'll do that.

**Comment by Banane9** [comment]
The first time I used DynamicVariableSpaces, I expcted it to work like nesting namespaces too - but every namespace is available to the entire hierarchy under it, unless there's a repeated one with the same name.

So as RileyGuy pointed out, use `.` for structuring - you can use those inside the variable space names too, if you want.
