### ISSUE TITLE
Dropping value fields into inspector are not undoable

### ISSUE THREAD

**Issue by ohzee00** [Yellow-Dog-Man/Resonite-Issues#555]
### Describe the bug?

When dropping a value from a Protoflux display node into the inspector, there is no undo step created. 

I have tested ColorX, Float3 and Float2 and I assume other dropped values will do similar. 

I'm unsure if this is intended, as dragging and dropping other values like slots and such into a inspector are undoable.

### To Reproduce

1. Spawn out a display node for colorx
2. Open a inspector on a material/slot with color
3. Grab the value on the Protoflux display node
4. Drop value onto a color in the inspector
5. Notice there is no undo step created for the action

### Expected behavior

Dropped values should be undoable.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/d539e833-4620-47fe-914d-7aa9740de69b

### Resonite Version Number

2023.11.8.335

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-V75BHJO - 2023.11.8.335 - 2023-11-08 00_55_55.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13292788/DESKTOP-V75BHJO.-.2023.11.8.335.-.2023-11-08.00_55_55.log)

### Additional Context

I was unsure if this was a feature request or not, though given that other values placed in the inspector _do_ have undo states, I'm more inclined this is a bug/oversight. 

### Reporters

Ohzee

**Comment by Frooxius** [comment]
Done in 2023.11.11.1231, thanks!
