### ISSUE TITLE
Add ValueProxySource to fields in inspectors.

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#558]
### Is your feature request related to a problem? Please describe.

With the new value proxy update we can drop ValueProxies on top of fields to set their value.
But currently there isn't really a way to get these ValueProxies outside of the ProtoFlux display nodes.

### Describe the solution you'd like

I think it would be useful if you could get a ValueProxy for colors by grabbing the color preview and potentially allow receiving on that area too.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/ea389e77-ffbf-4519-bb56-8b838c03a043)

### Describe alternatives you've considered

using this mod which functionally does exactly what I described in this issue https://github.com/art0007i/ColorDrop

**Comment by Frooxius** [comment]
I thought about this, but the problem I have is that this only works specifically for colors. The solution I want to implement should be generic, so you can do this for any datatype, including vectors, quaternions and so on.

I'll see what I can do, I might end up adding some extra visual to all of them which represents the actual value that you'll be able to grab.

**Comment by art0007i** [comment]
that makes sense. I actually have a different mod which does add a generic implementation of a little pick button to the side of most fields. https://github.com/art0007i/ValueProxyExtensions

this is what it looks like:
![value proxy extensions buttons inside of an inspector](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/3573f901-085e-4b2c-acdb-e015a24185b8)

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/d5cba0e9-4b47-4b87-8610-1c6f600cb7b7

**Comment by TisFoolish** [comment]
I *really* like Art's solution. It's fast, easy to understand, and doesn't require any additional clicks like a context menu would, which is slow.

**Comment by Frooxius** [comment]
Yeah that's what I was thinking, just add a little "something" that you can pick up values from. We could potentially even add some extra visualizations for various datatypes.

**Comment by Frooxius** [comment]
I've added a mechanism to grab those and any other type in 2023.11.11.1231, thanks!
