### ISSUE TITLE
Allow ValueReceiver component to cast valueproxies it receives.

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#561]
### Is your feature request related to a problem? Please describe.

Currently if you have a `ValueProxy<int>` and want to drop it into a `ValueReceiver<float>` you cannot.
I think it would be nice to have an option for the ValueReceiver to receive these easily castable types.

### Describe the solution you'd like

A checkbox on the `ValueReceiver` component (true by default) that would make it so the component attempts to cast ValueProxies.
This should be an option as for example it's possible to have both a `ValueReceiver<int>` and `ValueReceiver<float>` and have them do different things.

### Describe alternatives you've considered

Using a `ValueProxy<string>` and putting it into a `PrimitiveMemberEditor`

**Comment by Frooxius** [comment]
Added in 2024.5.30.68, thanks!
