### ISSUE TITLE
WebAssembly integration

### ISSUE THREAD

**Issue by moonheart08** [Yellow-Dog-Man/Resonite-Issues#573]
### Is your feature request related to a problem? Please describe.

At this time, integrating existing libraries and software into resonite is not doable without external services. By adding support for WebAssembly-based processes, most native libraries could be ported with some effort to a resonite-compatible API and ABI, allowing Protoflux to call into those libraries and for those libraries to interact with some (not all, as webassembly is not meant to be a Protoflux replacement) game functionality. 

### Describe the solution you'd like

This is merely one approach to this form of integration, the one I personally took during prototyping. My work in progress prototype is available [here](https://github.com/moonheart08/KaylieNodeLib/tree/master/KaylieNodeLib/WebAssembly) and is mostly functional at a surface level. Happy to discuss it one-on-one if necessary, and discuss design choices, what i didn't do, why, and what's left to do.

Webassembly can be integrated similarly to how websockets work, with state stored in a WebAssemblyProcess component. This component is used to expose WASM exports and provide an execution context, with each export given it's own component (i.e. WebAssemblyMemory, WebAssemblyFunc<T,...>, WebAssemblyGlobal<T>, etc) that exposes information about the export and allows interaction with it.

One can then use these exports to interface with an active process by calling functions within it, accessing it's memory, reading/modifying globals, etc.

Due to the lack of a stable WASM ABI (WASI is plain unsuitable, unfortunately), a custom resonite-oriented ABI can be provided instead. This is ultimately implementation defined but the approach I took for v1 is:
- __resonite_v1_alloc(int) -> int | Allocate some space on the heap for arguments. The receiver, some given WASM function, is required to free this memory itself before returning.
- __resonite_v1_dealloc(int) | Deallocate some given result. Any WASM function that returns an ABI type that is passed by reference (i.e. any non-primitive, including structs) can expect the Resonite provided implementation to call this function to free the result data.
- __resonite_v1_str_format: int | This global contains the string representation expected by the WASM module, which can be length-data UTF16, UTF32, and UTF8, or null-terminated UTF8 (not implemented in my prototype yet).

The general ABI is that all primitives (byte, sbyte, ushort, short, uint, int, ulong, long, bool) are passed by-value as their appropriate WASM equivalent (i32, i32, i32, i32, i32, i32, i64, i64, i32).
All other types, i.e. structs like `float2`, are first allocated and copied into WASM memory, and then passed by pointer (for WASM32, the only supported WASM mode, this is an `i32`.)
WASM `externref` is not used at this time due to poor support in LLVM and other languages, which would make writing bindings unnecessarily difficult. In the future in a v2 or later version of the ABI, this could be changed.
Resonite automatically performs the appropriate allocations/etc as part of WebAssemblyFunc<T,...>'s exposed sync delegate (chosen to avoid declaring another few hundred nodes just for WASM), allowing the resonite-side user to simply call it like a normal function. Impulse-less evaluation is not currently supported.
To avoid WASM potentially running overtime or otherwise killing the game, a hard execution ceiling using `wasmtime`'s fuel system is used, giving any given function call `1000000` fuel to use for execution. Additionally, every WASM process is capped at 16MiB of allocated memory to avoid unbounded memory use.

Additionally, one can directly read/write values in WASM memory using "memory view" components, which allow directly reading and writing some given address. My prototype provides `WebAssemblyValueMemoryView<T>` (which provides a view for any primitive type) and `WebAssemblyProceduralTexture` (which provides a view for an arbitrary texture). Additional views, i.e. audio, mesh, etc can be supported, and would allow existing libraries to be used to complement planned DSP features, for example integrating existing audio plugins (i.e. VSTs).

### Describe alternatives you've considered

Continuing to use websocket IPC for this form of integration, which places extra overhead on the user but is functional.

**Comment by Narazaka** [comment]
I think WASM is a very good solution to other problems with Protoflux. #952

**Comment by Frooxius** [comment]
We are heavily considering webassembly support to be added to the engine as a general principle, but I'm not sure if it would follow the solution requested in this issue - I feel it's going way too much into implementation details, but we need to consider higher level integration. 

I will make an official issue for this at some point, since this is going to be one of the most major features for Resonite.

**Comment by moonheart08** [comment]
> We are heavily considering webassembly support to be added to the engine as a general principle, but I'm not sure if it would follow the solution requested in this issue - I feel it's going way too much into implementation details, but we need to consider higher level integration.
> 
> I will make an official issue for this at some point, since this is going to be one of the most major features for Resonite.

I am ultimately a low level integrator here, with the idea being these are building blocks one could build a higher level ABI atop of.

**Comment by moonheart08** [comment]
The API described allows for very fine grained control of the VM and exposes details like memory. A higher level tool could then build a pretty user-side API for this on both ends (resonite and in-language) while leaving room for people to use the low level tools if they need them.

**Comment by Frooxius** [comment]
If you want very specific low level integration, then we are more likely to just close the issue, as we might not implement things in this particular way - generally we don't recommend focusing too much on the fine details with issues first, but on the bigger picture.

The higher level mechanisms will be what ends up informing how will the fine details end up looking like - that's ultimately our job to design and implement.

**Comment by moonheart08** [comment]
I'm not asking for this low level implementation, i'm asking for *a* low level API.

**Comment by Frooxius** [comment]
In that case it's too soon for this kind of request.

We will have to consider and design the implementation first and how it will integrate with the engine overall, before we start going into low level details.

I cannot guarantee that those low level details will be as you ask for in this issue at this point.

**Comment by moonheart08** [comment]
"This is merely one approach to this form of integration, the one I personally took during prototyping."

**Comment by Frooxius** [comment]
We have made an official issue for WebAssembly support, where we focus more on the higher level integration goals and plans: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1211

I'm going to close this one, but thank you for submitting this!
