### ISSUE TITLE
ProtoFlux Node Slots should be sacled 1.0 by default.

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#575]
### Is your feature request related to a problem? Please describe.

Currently protoflux nodes are 1.25 scale, this makes them slightly more difficult to work with because when trying to write any code that interacts with the node's scale you have to hardcode a 1.25 constant somewhere.

I think the nodes being at 1 scale would just be cleaner.

### Describe the solution you'd like

The nodes should spawn at 1 scale.
If that makes the visuals too small then the <NODE_UI> slot default scale could be increased to match the current node scale.

### Describe alternatives you've considered

making a creation that makes all nodes that I spawn out scaled to 1 scale, but this would be inconsistent with other users nodes.

**Comment by Frooxius** [comment]
This is simple enough, I can move the scale to the <NODE_UI> instead.

**Comment by Zyro1331** [comment]
If the ProtoFluxTool could get an option that just forces all nodes to spawn at a certain scale regardless of the user scale, I feel that it would help significantly.

**Comment by Frooxius** [comment]
Made the change in 2023.11.11.1231, thanks!
