### ISSUE TITLE
Function support

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#58]
### Is your feature request related to a problem? Please describe.

It is very daunting to have large blocks of code with ribbons all over the place and it is also a bit of a nuisance to not have reusable code

### Describe the solution you'd like

I would love to have function support where when you are done editing it will get packed into a custom node like format that can be used all over the place with inputs, outputs and an indicator that it is a function as to not confuse people with the node name

### Describe alternatives you've considered

I have considered using impulses to create a pseudo function like feature... but this requires a lot of boilerplate and causes performance issues if they need to be called a lot

**Comment by DaryeDev** [comment]
Bump!

**Comment by mpmxyz** [comment]
A note on Dynamic Impulse performance:
They work faster if you limit the target hierarchy.
If your target is a single node you could target that node's slot explicitly. (more boilerplate, though)

**Comment by FlameSoulis** [comment]
Mayhaps this could be how NodeRed allows 'custom' nodes to be created. This would mean the introduction of 'input' and 'output' flux nodes, but this could very heavily improve performance if the system caches the custom flux nodes in memory for execution purposes, but separate memory profiles per node in usage.

**Comment by Frooxius** [comment]
Closing this one in favor of the official issue: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/564
