### ISSUE TITLE
Resonite cannot be added to "Game Collector" section of steam profile

### ISSUE THREAD

**Issue by gentlecolts** [Yellow-Dog-Man/Resonite-Issues#583]
### Describe the bug?

Steam profiles allow users to display a curated selection of games, and I would like to add Resonite to mine, but I cannot

### To Reproduce

Edit or change showcase -> game collector -> try to edit a slot, type in resonite > no result

### Expected behavior

Ability to display resonite on my profile

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/15dd603d-d7af-4d07-8c98-aefe52754019)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/34f28a5a-b72a-40df-b170-eb72171385a4)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/c200a3ad-7b94-4439-9540-2086ff421834)

### Resonite Version Number

n/a

### What Platforms does this occur on?

Windows, Linux

### Log Files

n/a

### Reporters

zangooseoo

**Comment by Frooxius** [comment]
I don't think this is something we have control over.

**Comment by ProbablePrime** [comment]
This is caused by Steam: 
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8791132/c7a71aa5-043a-4bb5-a3ec-8400a6a6efb7)


It should resolve itself in a few months.

**Comment by gentlecolts** [comment]
> It should resolve itself in a few months

It's...more than a few months now, still seeing this issue

**Comment by Electronus** [comment]
![Image](https://github.com/user-attachments/assets/9a77f9e7-dd18-4f3b-b863-36019a8755de)
just taken

**Comment by Frooxius** [comment]
I'm not really sure what can we do to fix this on our end. I don't really have time to do the research right now in case anyone wants to have a look.

**Comment by Dusty-Sprinkles** [comment]
A quick google search shows [this page](https://partner.steamgames.com/doc/marketing/profile) which just seems to imply resonite isn't popular enough for profile features

**Comment by shiftyscales** [comment]
@Dusty-Sprinkles is correct- this is out of our control. By some metrics that are mostly unknown to us Steamworks may enable this functionality at some future point as part of an automated process if and when we meet their criteria to do so.
