### ISSUE TITLE
ValueDisplay<bobool3ol> crashes the world

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#588]
### Describe the bug?

I was playing around with bobool3ol and managed to accidentally crash my world. It turns out the ValueDisplay<bobool3ol> is very dangerous and can easily crash the world you are in.

### To Reproduce

1. Create a bobool3ol node
2. Pull out a display for it
3. Disconnect the wire, this can be done either by deleting the node, pulling out another input from the display node, creating a relay or using the cut line

### Expected behavior

the world does not crash

### Resonite Version Number

2023.11.8.335

### What Platforms does this occur on?

Windows

### Log Files

[ROTHORN - 2023.11.8.335 - 2023-11-09 00_29_34.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13302271/ROTHORN.-.2023.11.8.335.-.2023-11-09.00_29_34.log)

**Comment by Frooxius** [comment]
Fixed in 2023.11.11.1231, thanks for report!
