### ISSUE TITLE
FurMaterial performance issues in VR

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#590]
### Describe the bug?

The VR performance of a basic FurMaterials drops drastically when walking up to and looking closely at the FurMaterial. Ive also had a few people in desktop do the same test in desktop mode without any change in performance

### To Reproduce

create a low resolution FurMaterial and tile it on a quad (image of what i used in the material is included in the screenshots)

### Expected behavior

shell based rendering is a high performance and old technology and should not have a major performance hit when you use it

### Screenshots

Grass using FurMaterial
![2023-11-07 17 13 59](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/f3c3dcf7-1f54-48c6-bb5c-ba9a6a08c1ef)

Performance when looking at grass from where it shows in grass picture
![2023-11-07 17 03 49](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/27429259-5194-4329-9867-bda711eaef7e)

Performance when walking up to and looking at grass
![2023-11-07 17 04 21](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/5a0b69c6-4ef0-408f-b0da-204d3f249083)

Setting im using for FurMaterial 
![2023-11-09 00 20 01](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/fc0c3260-5579-4742-aa1d-7095ef51683b)

### Resonite Version Number

2023.11.8.335

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

N/A

### Additional Context

all lines showing on the graph are in milliseconds, so the higher the lines the worse the performance

### Reporters

ultrawidegamer

**Comment by Zandario** [comment]
The reason it hurts when you get close to it is due to overdraw, when you are in VR you can think of having at least 3 rendering outputs (VR and desktop screen) all doing massive overdrawing, not sure what can really be done about that

**Comment by Geenz** [comment]
I'm going to close this one out as the fur shader is pretty performance intensive due to how it fundamentally works.  There can be a ton of overdraw and re-evaluation of fragment visibility due to the _extensive_ usage of alpha cutout and geometry shells.
