### ISSUE TITLE
UDIM Support

### ISSUE THREAD

**Issue by DysFox** [Yellow-Dog-Man/Resonite-Issues#591]
### Is your feature request related to a problem? Please describe.

I have a few models that I'd like to view in Resonite, but they rely on UDIMs to be properly textured. Technically I could solve this issue by breaking up the mesh into different materials and overlaying the UVs, but this feels like a very inefficient solution. 

### Describe the solution you'd like

Ideally, UDIM support could be added to the in-built PBS and other materials, allowing seamless importing of assets that utilize them. 

### Describe alternatives you've considered

As stated above, it is possible to overlap the UVs and just use different materials to accomplish effectively the same thing, but this is very messy and difficult to maintain. UDIM support would make it much easier to integrate Resonite into various content creation pipelines.

**Comment by DoubleStyx** [comment]
That's probably going to be after Sauce's release. Here's what Geenz had to say about UDIMs:

https://officehours.probableprime.co.uk/episodes/geenz-2023-10-25/

156
00:07:49,690 --> 00:07:54,690
Uh Let's see, purple juice asks any plans with [UDIMs] in the future.

157
00:07:54,769 --> 00:08:00,670
So I answered this one at the last one, the answer is no. The reason for no is

158
00:08:00,959 --> 00:08:03,269
you didn't have a tendency

159
00:08:03,559 --> 00:08:04,940
to make your shader

160
00:08:05,350 --> 00:08:08,649
pretty bloated, depending on number of tiles. You want to support

161
00:08:08,829 --> 00:08:09,989
a bunch of things like that.

162
00:08:10,369 --> 00:08:15,149
Um This is probably not a right now thing for the current unity setup.

163
00:08:15,160 --> 00:08:19,089
We're probably, I mean, once we have custom shader through sauce, of course,

164
00:08:19,100 --> 00:08:23,130
you can build uh these out however you want to so you could of course add you

165
00:08:23,279 --> 00:08:23,899
support

166
00:08:24,079 --> 00:08:27,390
yourself. Um But right now the answer is no, sorry.

**Comment by DysFox** [comment]
While I understand that this would have to come after Sauce, the way Geenz worded his response during office hours makes it sound like even after Sauce, it would not be implemented first-party and would be up to users to add the support themselves. Given that many people, myself included, are not knowledgeable of shader code or how to add such a feature, it would very much be preferrable to have it officially implemented as a first-party solution.

**Comment by Geenz** [comment]
UDIM is a complex ask- although it’s useful for many offline or otherwise “non-realtime” applications, it does result in a ton of shader bloat that at this time we’re just not up to maintaining. With custom shaders you’ll be able to do whatever you like however- and it’s possible we may add a UDIM sampler node at some point after we have custom shaders. But right now that’s not planned. Asked again when we have custom shaders.
