### ISSUE TITLE
World crash when using Default nameplates.

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#595]
### Describe the bug?

When I join a session with a large number of people with the nameplate status set to "Use default nameplates" from the dash menu, I get an indication that the world crashed a dozen seconds after joining.
In reality, the world has not crashed and you are the only one who is ejected from the session.

`System.ArgumentException: Cannot reference local targets from non-local reference.`
When this occurs, the log always records the same exception.
The full text is in the log section.

### To Reproduce

1.Select "Use default nameplates" from the dash menu.
2. Join a session with many people.
3. After a while, you will see that the world has crashed.

There is no certainty in the second step.
I think it is the world or something in the avatar, but I am not sure.

### Expected behavior

World should not crash.

### Screenshots

![20231109212303_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/e0ecda0b-b9ed-4f6b-b728-b4fe3fa32c28)

### Resonite Version Number

2023.11.8.335

### What Platforms does this occur on?

Windows

### What headset if any do you use?

VIVE Pro

### Log Files

There are three logs.
Common to all three is this error.

`System.ArgumentException: Cannot reference local targets from non-local reference.`

[MENTAIKO - 2023.11.8.335 - 2023-11-09 21_14_28.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13309396/MENTAIKO.-.2023.11.8.335.-.2023-11-09.21_14_28.log)
[MENTAIKO - 2023.11.8.335 - 2023-11-09 21_17_23.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13309397/MENTAIKO.-.2023.11.8.335.-.2023-11-09.21_17_23.log)
[MENTAIKO - 2023.11.8.335 - 2023-11-09 21_19_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13309398/MENTAIKO.-.2023.11.8.335.-.2023-11-09.21_19_36.log)

### Additional Context

When I have it set to "Allow custom nameplates" this problem does not occur.
I have had other people select "Use default nameplates" and they have the same problem.

### Reporters

orange3134

**Comment by Frooxius** [comment]
Fixed in 2023.11.11.1231, thanks!
