### ISSUE TITLE
Neos to Resonite Migrations Not Processing

### ISSUE THREAD

**Issue by Enverex** [Yellow-Dog-Man/Resonite-Issues#597]
### Describe the bug?

We've had several people complain about their migrations not starting over quite a few hours now. This still seems to be ongoing. This was taken last night:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/958670/062db95d-7844-4120-a4de-bc98748e2a89)

A few hours later Prime mentioned it was up to 59. It seems to be flip-flopping between a value and that value minus one, while overall growing.

Longer scale over time:
<img width="1614" alt="image" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/958670/bdca9b26-8b5a-4776-b7ad-c36121a7e667">

### Expected behavior

For migrations to proceed.

**Comment by ProbablePrime** [comment]
Acknowledged, Seeing what I can do.

**Comment by shadowpanther** [comment]
Looks like the +/-1 jitter has stopped, but no migrations actually processed:
<img width="816" alt="image" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/1c9aba25-02d0-485d-9b8b-76e83fa19090">
The red line is around the time when you closed the issue.

**Comment by ProbablePrime** [comment]
We're continuing to make some changes, I'll re-open this till the queue empties.

**Comment by xXFaZeGaMeR900Xx** [comment]
Is it fixed this is me Plasma

**Comment by shadowpanther** [comment]
Users are reporting that their migration tasks get cancelled.
And even though the queue size seems to be decreasing, the records/minute metric only rarely jumps up from zero.
<img width="660" alt="image" src="https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/9914a96e-d9b1-4d95-8609-616da2e7f0f1">

**Comment by ProbablePrime** [comment]
Do we have any logs or error messages?

**Comment by shadowpanther** [comment]
I suppose most of this happens on the cloud's side. So client logs would most likely not contain anything unusual.
I've asked whether the user got the email and what the migration tab says for that task.

**Comment by ProbablePrime** [comment]
Ahh yes, that would be helpful thank you

**Comment by shadowpanther** [comment]
In the meanwhile, I've tried to start a new migration task on my empty backup account, and it started almost right away, even though the monitoring still shows 40 tasks queued. So maybe the old ones are stuck and new ones get to the front?

My small migration of 14 (of 16) items and 3 contacts finished in about 15 minutes.
