### ISSUE TITLE
'FreeImageAPI.Plugins.PluginRepository' threw an exception.

### ISSUE THREAD

**Issue by TeknoCatron** [Yellow-Dog-Man/Resonite-Issues#604]
### Describe the bug?

Headless refuses to start with Beta 2023.11.8.335
Throwing an exception and killing the startup.

Beta 2023.10.20.831 Does work and starts up normal, but people cannot connect to these sessions as their not compatible?

### To Reproduce

Setup Debian12 with latest Mono.
Run headless as normal.

Operating System: Debian GNU/Linux 12 (bookworm)  
Kernel: Linux 5.15.108-1-pve
rchitecture: x86-64

Mono JIT compiler version 6.12.0.200 (tarball Tue Jul 11 21:32:10 UTC 2023)

### Expected behavior

It to continue with it's normal startup.

### Screenshots

![Screenshot 2023-11-10 110755](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14295952/b073de91-250d-4674-bced-989ec2b2b7fd)

### Resonite Version Number

Beta 2023.11.8.335

### What Platforms does this occur on?

Linux

### What headset if any do you use?

N/A

### Log Files

[TRD-42200 - 2023.11.8.335 - 2023-11-10 10_47_41.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13318186/TRD-42200.-.2023.11.8.335.-.2023-11-10.10_47_41.log)

### Additional Context

[TRD-AfterDark - 2023.11.8.335 - 2023-11-10 10_47_39.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13318188/TRD-AfterDark.-.2023.11.8.335.-.2023-11-10.10_47_39.log)
[TRD-42300 - 2023.11.8.335 - 2023-11-10 10_47_43.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13318189/TRD-42300.-.2023.11.8.335.-.2023-11-10.10_47_43.log)
[TRD-42400 - 2023.11.8.335 - 2023-11-10 10_47_45.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13318191/TRD-42400.-.2023.11.8.335.-.2023-11-10.10_47_45.log)

### Reporters

Tekno Catron / teknocatron / 281806404891836416

**Comment by Frooxius** [comment]
Is this affecting anyone else? This seems like something what would've broken all headlesses, so I'm wondering if there's something specific to your setup.

**Comment by TeknoCatron** [comment]
Well, I just copy over the Headless folder and copy over the Runtime folder like I always do. and after doing that it gave me this error.

**Comment by TeknoCatron** [comment]
![Screenshot 2023-11-11 072130 Ubuntu 23 10](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14295952/28e09395-b1ac-430e-9ac8-3aef1232ccbd)
Did a full rebuild on Ubuntu server 23.10 with Mono 6.12.0.200

Issue still exists

**Comment by TeknoCatron** [comment]
Enverex suggested to download the files through steamcmd instead of copying this over from the windows download.

Once those headless files where downloaded and moved to the locations they should be at, everything started booting up like a charm.

"Enverex — Today at 5:36 PM
It's a different depot, the Linux version grabs different files.
[5:36 PM]
So there's likely small differences that were creating issues."

**Comment by Frooxius** [comment]
So this is good to close?

**Comment by TeknoCatron** [comment]
Yes please. Issue was a Windows Build attempting to run on Linux. Sorted with using SteamCMD in order to get the right dependencies when downloading the headless.
