### ISSUE TITLE
Button to open the slot that a component is attached to from a worker inspector

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#608]
### Is your feature request related to a problem? Please describe.

When you have one of those single worker inspectors, you cannot open the slot that the component is on.
For example when you click "Edit Material" with a material tip, you cannot open the slot that the material attached to.

### Describe the solution you'd like

An extra button on single worker inspectors that would open the slot that the worker is located on.

### Describe alternatives you've considered

using a mod that implements this functionality https://github.com/art0007i/ShowComponentSlot

### Additional Context

This is what the mod does, and what I would expect something like this to look like:
![worker inspector with the desired button](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/a631990c-2462-410c-a6fe-d9369607715a)

**Comment by Frooxius** [comment]
Hmm this is a bit niche, but would be useful for inspectors and editors. We'd probably switch to using this as it's more modular too with the official system once it's reworked.

**Comment by ScarsTRF** [comment]
Would honestly state that it shouldn't be right next to the delete button, I've had too many issues where trying to open it and I accidentally delete the component with that mod. Just my own insight on this if it does get implemented natively. Another mod by someone else has is on the opposite side away from the delete button as seen here.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/23484495/510593a1-7ebf-4b59-b83a-71775f8a732d)

**Comment by XDelta** [comment]
The slot can be found and opened without mods but it is tedious to get to by inspecting the WorkerInspector and finding the title button which has a `ButtonRefRelay<Worker>` then click on the first up arrow on the Argument field.

![282266232-717b3dbf-a9b0-406a-ad76-4e767a010873-1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/821ac23e-b4b7-4d6f-8cf1-f1d196e279fe)


Another mod that adds this functionality is [XDelta/ResoniteShowSourceLocation](https://github.com/XDelta/ResoniteShowSourceLocation)

**Comment by lxw404** [comment]
I would no longer call this a niche feature.

I run into this wall of trying to find the slot that a worker inspector is opened to all of the time now, especially now that we have the ability to find what is driving a value.  When you open the drive source you're always given a worker inspector, but most of the time you really want to find where exactly that driver is located, so adding this is a necessity to improve that workflow.

**Comment by shiftyscales** [comment]
As highlighted by @Zyro1331 in #2067:

> It's entirely possible to figure out where a component is located by grabbing the header of the component and pressing the "Open Inspector" button in your context menu as you hold the component reference. Then the newly opened Inspector will show the slot the component is attached to.

I was not aware of this functionality, but will likely be using it often now that I do.

It doesn't supersede this issue however, as it would still be useful to have this functionality exposed on worker inspectors so it is more visible.

**Comment by Frooxius** [comment]
Added button in 2024.7.24.1106, thanks!
