### ISSUE TITLE
Video URLs from X.com get pasted as text

### ISSUE THREAD

**Issue by glitchfur** [Yellow-Dog-Man/Resonite-Issues#615]
### Describe the bug?

I don't like the "rebrand" either, but I guess it has to be acknowledged somehow.

As of recently using the "Copy link" item from the Share menu on Twitter/X videos will copy a link using the `x.com` domain instead of `twitter.com`. Consequently, pasting these links into Resonite will paste the URL literally instead of importing the video.

### To Reproduce

1. Find a video on Twitter/X, copy the link using the **Share** button, then **Copy link**
2. Paste the copied link into Resonite
3. The URL will be imported as text

### Expected behavior

Resonite should offer options for how to import the video as it does with `twitter.com` links.

### Screenshots

![Screenshot comparing what happens after posting a video URL from Twitter.com and X.com.](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14147284/c13f8df7-f10c-4c27-9030-cf5f9ad9eccd)

### Resonite Version Number

Beta 2023.11.8.335

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

Log file includes the events of starting Resonite, loading into the default home world, pasting a Twitter.com video URL followed by a X.com video URL, and then exiting.

[TECHCAT-PC - 2023.11.8.335 - 2023-11-10 13_13_24.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13322585/TECHCAT-PC.-.2023.11.8.335.-.2023-11-10.13_13_24.log)

### Reporters

@glitchfur across GitHub, Twitter/X, Telegram, and Discord.

**Comment by MargoSizemore** [comment]
If you right click the video and click "copy video link", this does not happen.

**Comment by Enverex** [comment]
> If you right click the video and click "copy video link", this does not happen.

That's because that provides you with a twitter.com link instead, which is likely to change in the not too distant future.

The issue is because Resonite has a hard-coded list of "parse this as media" domains that it uses to make this decision. X.com just needs to be added to that list.

**Comment by MargoSizemore** [comment]
> > If you right click the video and click "copy video link", this does not happen.
> 
> That's because that provides you with a twitter.com link instead, which is likely to change in the not too distant future.
> 
> The issue is because Resonite has a hard-coded list of "parse this as media" domains that it uses to make this decision. X.com just needs to be added to that list.

I know, just stating it so anyone who wants a temporary workaround has one.

**Comment by Frooxius** [comment]
Confirmed you cuteness in 2023.11.11.1231, thanks!
