### ISSUE TITLE
Alias "slot" to "Slot" in reference selection menu

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#620]
### Is your feature request related to a problem? Please describe.

While creating a DynamicReferenceValue component (as well as in some other cases), inputting "slot" returns "Invalid type" rather than returning the "Slot" type. This differs from the "Uri" type, which will recognize several similar inputs such as "URL", "url", and "uri".

### Describe the solution you'd like

Make it so that the lowercase string "slot" is recognized as the "Slot" reference type when creating components. Additionally consider applying the same logic to inputs for the "User" reference type.

### Describe alternatives you've considered

The existing alternative is to capitalize the input properly.

**Comment by Nytra** [comment]
I think it may be better to just make the input be not case-sensitive, so you would be able to put in any type string in lowercase and it would still work

**Comment by MrVoltz** [comment]
Also when we're at it, it would be great if you could write nested generic types in a human readable way. For example `IAssetProvider<Material>` instead of ``IAssetProvider`1[FrooxEngine.Material]``.

**Comment by shadowpanther** [comment]
> Also while we're at it, it would be great if you could write nested generic types in a human readable way. For example `IAssetProvider<Material>` instead of `` IAssetProvider`1[FrooxEngine.Material] ``.

I've already made that a feature request: #427

**Comment by Frooxius** [comment]
@MrVoltz Please do not hijack issues for other features/requests. 

If you have a additional feature/request, it needs to be another issue.

**Comment by Frooxius** [comment]
I've made the whole system be case-insensitive in 2023.11.11.1231, which should resolve this. Thanks!

**Comment by Nytra** [comment]
Just want to say that I have noticed that the case-insensitivity got lost at some point, e.g. `slot` does not work but `Slot` does.

**Comment by TisFoolish** [comment]
This should be a new bug report since it's an internal system that broke
