### ISSUE TITLE
Headless missing Twitch interface

### ISSUE THREAD

**Issue by RaithSphere** [Yellow-Dog-Man/Resonite-Issues#622]
### Describe the bug?

Twitch chat shows "No Twitch Interface"

**TwitchLib.Communication.dll in headless is outdated**

### To Reproduce

Spawn out a twitch chat in the world and the world will crash instantly

### Expected behavior

World won't crash and twitch chat will spawn

### Resonite Version Number

Headless 2023.11.8.335

### What Platforms does this occur on?

Windows, Linux

### Log Files

There is nothing in the log files regarding the crash

**Comment by RaithSphere** [comment]
This is a small report as there is no data from the headless logs, however doing a diff on the files and then replacing **TwitchLib.Communication.dll** in the headless solves the issue

**Comment by shadowpanther** [comment]
Already reported in #592

**Comment by RaithSphere** [comment]
Closed given this is reported over at https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/592 - i only did a quick report for my notes
