### ISSUE TITLE
Resonite Logo Loading Bar

### ISSUE THREAD

**Issue by SpaceGaytor** [Yellow-Dog-Man/Resonite-Issues#629]
### Describe the bug?

Have already experimented with another user, seems to only be in my userspace. Doesnt matter if its a new world, cloud home, local, it always seems to be there at the spawnarea. Doesnt seem to cause any issues other than its just there, load bar seems to be animating still but I am not loading anything anymore (That can be seen on my end).

### To Reproduce

This is a more recent issue as it was not happening before. I originally had issues with the worlds tab not loading anything in it, so I had reset my dash several times until finally the worlds tab started to work again and I no longer held the resetdash comman in the launch options.

After such I noticed the loading resonite logo staying up at spawn of my cloud world and local home, and now it doesnt matter what world I join its just there, stationary at spawns.

Doesnt matter if I start Resonite in Screen mode or SteamVR

### Expected behavior

For the loading logo thing to not be there?
It wasnt before and it is now, I dont want it to stare at me...menacingly. 

### Screenshots

![Resonite 1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/150499776/4a553ebf-1b3a-455b-a2f1-710ccf3687c6)
![Resonite 2](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/150499776/fea0343d-fc5b-4809-aa29-2dc4085984fe)
![Resonite 3](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/150499776/09c1f53f-2628-4d02-a60d-4668b1a366ba)

### Resonite Version Number

2023.11.8.335

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[SPARTAN118 - 2023.11.8.335 - 2023-11-10 21_33_36.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13324392/SPARTAN118.-.2023.11.8.335.-.2023-11-10.21_33_36.log)

### Reporters

SpaceGaytor

**Comment by Frooxius** [comment]
This is very odd. Can you please share the Player.log file as well?

**Comment by SpaceGaytor** [comment]
[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13389239/Player.log)
Sorry about that, had trouble finding it

**Comment by PrimoGeo** [comment]
Same Issue Here.
I tried Nuking all Resonite and YellowDogMan Caches in Appdata and elsewhere, including deleting the App from Steam folders.
Is still there. For me right now is only Worlds I create or own.
Other Worlds made and Hosted by others does not show.

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13418312/Player.log)


![Photo in Local](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/151567561/3d8e09f9-1753-4ec1-90f5-62692e9d451c)
![Photo in PrimoGeo World](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/151567561/dfd40675-6d35-4d93-8118-218902892cab)
![Photo in Rabbitusan](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/151567561/146c87ef-5a12-46da-968d-df12b763e266)

**Comment by PrimoGeo** [comment]
Oh sorry here 
[INFINITY - 2023.11.18.1263 - 2023-11-20 11_52_16.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13418364/INFINITY.-.2023.11.18.1263.-.2023-11-20.11_52_16.log)

**Comment by SpaceGaytor** [comment]
Yea that looks like the same thing happening to me. It started not too long before BLFC had happened. Everything loads and theres nothing stuck in debug or anything, just kinda sits there with that last little bit, almost like it hitches and doesnt recieve command to disappear when finished loading or something.

stays in my local, Cloud home and any world I join whether my own or someone elses, including headless servers.

**Comment by Frooxius** [comment]
I've never seen it happen myself, so I'm a bit confused on what could be the culprit, since this part of code should run pretty much the same way for everyone. 

I don't have a way to replicate it on my end.

I might need to add some more diagnostics to the startup process to see what could be the cause and have you send us the logs once that's in.

**Comment by SpaceGaytor** [comment]
Im not actually familiar with the Userspace Inspector, or really editing my userspace at all. Id be down to meetup on Res to see if it is?

**Comment by Nytra** [comment]
I think the loading bar is rendered and managed by Unity so it shouldn't appear in any inspector.

**Comment by Frooxius** [comment]
Just nothing here - yes this won't show up in the inspector, it exists completely outside FrooxEngine.

**Comment by Frooxius** [comment]
There's a potential fix in 2023.11.24.1379 and some additional diagnostics.

Can you check if the issue still persists on this version?

If so, please post new logs.

**Comment by SpaceGaytor** [comment]
Ok, here are the new logs.

[SPARTAN118 - 2023.11.24.1379 - 2023-11-24 18_07_17.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13462619/SPARTAN118.-.2023.11.24.1379.-.2023-11-24.18_07_17.log)

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13462621/Player.log)

After Downloading the update,
I started Resonite, the icon and logo disappeared, but I do not load into my Cloud Home and cannot load into any world. Upper right hand corner says Sync Error. I tried twice, Resonite Loads but I stay in Local, unable to sync, and have no ability to exit other than Alt+F4.

I was unable to leave Resonite normally so I had to Alt+F4

![Untitled](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/150499776/020cfd6d-c571-4986-aff4-6dbc034fe8e4)

Hope this helps.

**Comment by shadowpanther** [comment]
The not-loading is being currently fixed in #780

**Comment by SpaceGaytor** [comment]
Thats not the issue in this thread, thanks though

**Comment by SpaceGaytor** [comment]
I will be creating a New Issue as the Logo Loading Bar disappears now, so this issue has been fixed.

**Comment by PrimoGeo** [comment]
Can Confirm here as well Loading logo/Bar is gone.
