### ISSUE TITLE
Can't press some options in context menu when UI aligned

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#634]
### Describe the bug?

Sometimes I am unable to press context menu buttons when they are opened while in UI align mode on an inspector mainly but it can happen on other canvases as well. Notably this doesn't always seem to happen or seems to only affect about half of the context menu while allowing the other half to work fine. (shown in the recording)

### To Reproduce

UI align to an inspector and do an interaction that opens a context menu such as moving a component around or the new extra buttons for opening the driver for a field or resetting to default. 

### Expected behavior

Always able to press the context menu buttons.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/35e29ad9-ae87-45d5-b4fd-149bc0b9dbb1

![Resonite_2023-11-11_12-54-33](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/f3e5d830-3f70-4b3e-a154-7f69523a930d)

### Resonite Version Number

2023.11.11.1231

### What Platforms does this occur on?

Windows

### Additional Context

This did occur before this update but rarely came up.

### Reporters

_deltawolf

**Comment by Frooxius** [comment]
Tweaked the laser priority in 2023.11.15.1100 which fixes this. Thanks!
