### ISSUE TITLE
default avatar eyes go too far sometimes

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#637]
### Describe the bug?

When looking at the default avatar sometimes it's eyes decide to go into one direction far enough to where they aren't visible anymore.

### To Reproduce

1. Equip default avatar
1. Move and rotate your head and look at the eyes

### Expected behavior

The eyes aren't able to go so far that you can't see them anymore.

### Screenshots

![20231112005457_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/4d8dda5d-e549-4506-b12a-17a85adcfd17)

**Comment by RyuviTheViali** [comment]
The maximum eye swing has been adjusted on the default headset. Closing this, thanks!
