### ISSUE TITLE
Inspectors stop working if they are deactivated for the host

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#638]
### Describe the bug?

Inspectors stop working if they are deactivated for the host. This is mainly a problem in worlds that implement local culling systems. If you are in a slot that is locally deactivated for the host and you try to spawn an inspector it won't work correctly.

### To Reproduce

1) Join a world that someone else is hosting.
2) Put yourself into a slot and locally drive the slot so it is deactivated for the host (You can use ValueUserOverride)
3) Spawn an inspector. Observe that trying to use it doesn't work.

### Expected behavior

The inspector works even when it is deactivated for the host.

### Screenshots

N/a

### Resonite Version Number

Beta 2023.11.11.1231

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

Log file is not really applicable for the issue

[DESKTOP-H976HO2 - 2023.11.11.1231 - 2023-11-12 00_00_18.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13326812/DESKTOP-H976HO2.-.2023.11.11.1231.-.2023-11-12.00_00_18.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: nytra)

**Comment by Nytra** [comment]
This might be fixed by https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/563

**Comment by Frooxius** [comment]
Yes, we'd fix this by #563, which would make sure they run on the user interacting with them.

I'll close this issue as there's no plan to fix this for current implementation of inspectors.
