### ISSUE TITLE
Value buttons in list elements don't generate on SkinnedMeshRenderer

### ISSUE THREAD

**Issue by ScarsTRF** [Yellow-Dog-Man/Resonite-Issues#639]
### Describe the bug?

Certain Sync fields inside of list elements on things like `SkinnedMeshRenderer` don't generate preventing values from being dropped onto or the new `Open Link/Drive source` or `Break Link/Drive` that were introduced in update `2023.11.11.1231`

### To Reproduce

1. Generate a object that has a skinned mesh renderer.
2. In the skinned mesh renderer add items inside the Material, MaterialPropertyBlocks, Bones, BlendShapeWeights.
3. Your issue will be preset as they don't have any field buttons.

### Expected behavior

Field Buttons should generate next to the fields within a list to allow you to transfer values or to Open/Break Drives

### Screenshots

![Issue](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/23484495/7da99050-a835-4018-b885-58701ebce1cc)

### Resonite Version Number

2023.11.11.1231

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

Quest Pro, Vive Pro Eye

### Log Files

[LOGS.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13326811/LOGS.log)

### Reporters

Discord: scarstrf
Resonite: ScarsTRF

**Comment by Frooxius** [comment]
Fixed in 2024.5.29.27, thanks!
