### ISSUE TITLE
Show component slot via a component inspector

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#644]
### Is your feature request related to a problem? Please describe.

Currently there is no way to easily find the slot that a component is attached to via a component inspector.

This makes the newly added drive source ability only allowing you to find the component that may be driving a field, but not the slot it's attached to.

### Describe the solution you'd like

A button in the component inspector UI that opens a new inspector for the slot the component is attached to.

### Describe alternatives you've considered

There is a mod that can be found here: https://github.com/art0007i/ShowComponentSlot/tree/2.0.0

### Additional Context

Here is what it looks like with the mod:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91010433/1f31e15f-8f6c-4a50-8930-ed54d875cff8)

**Comment by shadowpanther** [comment]
Is this the same as #608?

**Comment by Stellanora64** [comment]
yes, closing as duplicate
