### ISSUE TITLE
Index of child on world root crashes the world

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#651]
### Describe the bug?

When you connect root slot into the "index of child" node it will crash the world when evaluated

### To Reproduce

1. Create index of child node
1. Create root slot node
1. Connect root slot node to index of child node
1. Create a display for the index of child node

### Expected behavior

It doesn't crash the world

### Screenshots

Picture of how to replicate it
![moments before disaster](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/eb90de1c-9ac7-4059-b337-4324751ec3df)

### Resonite Version Number

Beta 2023.11.11.1231

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Log Files

[Exception.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13327900/Exception.log)

**Comment by epicEaston197** [comment]
Can you display the number of slots in a different manner like a two string to a text object?

**Comment by art0007i** [comment]
its not the number of slots, it is the index of child.
and everything crashes it not just displays.

**Comment by Frooxius** [comment]
Please provide full logs

**Comment by Frooxius** [comment]
Merged fix in 2024.7.4.1347!
