### ISSUE TITLE
Headless requires steam_appid.txt in order for SteamAPI to function.

### ISSUE THREAD

**Issue by zahndy** [Yellow-Dog-Man/Resonite-Issues#653]
### Describe the bug?

I never got Steam networking sockets to work.
Logs didn't give me a lead but i found out that in order to use steam sockets you need a steam app id. 
The headless does launch with SteamAPI if you copy the steam_appid.txt over to the headless folder.

### To Reproduce

Launch headless/resonite.exe
Observe connection to SteamAPI fail
```javascript
4:21:19 PM.584		Steam
4:21:19 PM.737	SteamAPI failed to initialize

   at System.Environment.GetStackTrace(Exception e, Boolean needFileInfo)
   at System.Environment.get_StackTrace()
   at Elements.Core.UniLog.Error(String message, Boolean stackTrace) in C:\Workspace\Resonite\FrooxEngine\Elements.Core\UniLog.cs:line 59
   at FrooxEngine.SteamConnector.<Initialize>d__39.MoveNext() in C:\Workspace\Resonite\FrooxEngine\FrooxEngine\Interfacing\SteamConnector.cs:line 130
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at FrooxEngine.SteamConnector.Initialize(PlatformInterface platformInterface)
``` 

### Expected behavior

It should just connect to steam, and it does when you give it a steam_appid.txt
```javascript
4:17:40 PM.726		Steam
4:17:41 PM.248	Local User SteamID: 76561198127642009
4:17:41 PM.251	Steam Voice Initialized
4:17:41 PM.254	SteamAPI initialized
4:17:41 PM.255	Supported network protocols: lnl-nat, lnl, res-steam
4:17:41 PM.257	Initializing SkyFrost Interface...
``` 

### Resonite Version Number

2023.11.11.1231

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-AD85R8R - 2023.11.11.1231 - 2023-11-12 16_37_32.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13328466/DESKTOP-AD85R8R.-.2023.11.11.1231.-.2023-11-12.16_37_32.log)

**Comment by art0007i** [comment]
pretty sure this is just the steamapi dll doing that so might be out of resonite's control. I'd say the best way to fix this would be to actually include the steam_appid file inside of the headless download if it isn't already

**Comment by Frooxius** [comment]
Is this still an issue with latest version? I believe we added steam_appid.txt to the build process already.

**Comment by zahndy** [comment]
Re-downloaded to check. 
This is no longer an issue. steam_appid.txt is included now.
