### ISSUE TITLE
Recovery command returns 7bson

### ISSUE THREAD

**Issue by 989onan** [Yellow-Dog-Man/Resonite-Issues#656]
### Describe the bug?

The recovery command returns a zip containing files with a ".7bson" extension when emailing the user, even with items made within Resonite that were recently deleted.

### To Reproduce

Use recovery command to recover a file deleted from the cloud (any file). Then look inside the zip file the bot gives. The files have a .7bson extension.

### Expected behavior

The files in the recovery zip should have ".brson" extensions when given to the user, since those import properly

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29756848/135a30e9-ad90-4aba-81b3-bfe95680c166)

### Resonite Version Number

Beta 2023.11.11.1231

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[CHEW-PC - 2023.11.11.1231 - 2023-11-12 13_11_51.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13328771/CHEW-PC.-.2023.11.11.1231.-.2023-11-12.13_11_51.log)

### Additional Context

There is an alternative method to fix this, where you rename the file to .brson and import that. Most people don't know the internals of Resonite, so this is a high task for most users of Resonite who expect their recovered files to just import.

### Reporters

Discords (will auto format when pasted):
<@434468177062133772>

**Comment by Frooxius** [comment]
This should work in 2024.1.24.834 now!
