### ISSUE TITLE
Logger improvements

### ISSUE THREAD

**Issue by rassi0429** [Yellow-Dog-Man/Resonite-Issues#665]
### Describe the bug?

Hello. Thank you for the many updates.

When Resonite crashes, it seems that the log remaining in the logger's buffer is not output and the stack trace is not left in the log.

Log excerpt
```
21:35:00.116 ( 45 FPS)	Session updated, forcing status update
21:35:26.785 ( 38 FPS)	Engine has been unresponsive for over 10 seconds.
LastUpdateTime: 2023/11/01 12:35:03
FocusedWorld: World ぐりっど1. Focus: Focused, State: Running, InitState: Finished, FailState: None, FailReason: , IsDestroyed: False, IsAuthority: False, SyncTick: 1193, StateVersion: 242957, Time: 1348.06882431247, TimeSinceLastUpdate: 23.24053
WorldStage: RefreshBegin
Wo (←End of File)
```

### To Reproduce

I don't understand. 

If Resonite crashes? normally, <<< LOG END >>> will be displayed.

### Expected behavior

the crash log should be included all the way to the end.

Also, it may be useful if the log is output to standard output using startup options.

### Resonite Version Number

2023.11.11.1231

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, Varjo Areo

### Log Files

[DESKTOP-UPS4R4A - 2023.11.11.1231 - 2023-11-14 01_58_22.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13341968/DESKTOP-UPS4R4A.-.2023.11.11.1231.-.2023-11-14.01_58_22.log)
[DESKTOP-UPS4R4A - 2023.11.11.1231 - 2023-11-14 03_30_02.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13341969/DESKTOP-UPS4R4A.-.2023.11.11.1231.-.2023-11-14.03_30_02.log)
[DESKTOP-5IMSSDD_-_2023.10.20.831_-_2023-11-01_21_32_40 (2).log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13341970/DESKTOP-5IMSSDD_-_2023.10.20.831_-_2023-11-01_21_32_40.2.log)
[DESKTOP-5IMSSDD_-_2023.10.20.831_-_2023-11-01_21_29_01 (1).log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13341972/DESKTOP-5IMSSDD_-_2023.10.20.831_-_2023-11-01_21_29_01.1.log)

### Reporters

Resonite: kokoa0429
Discord: kokoa

**Comment by Frooxius** [comment]
Unfortunately this is not fixable due to nature of crashes.

For the log to be finished, the app would need to continue running to complete writing the log. However crash is an unexpected condition, which prevents the code of the app from running further and therefore we cannot complete writing the log.
