### ISSUE TITLE
Menu buttons do not work on LegacyAudioPlayer

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#669]
### Describe the bug?

Menu buttons (Loop, Stop, Spatial) on LegacyAudioPlayer do not work.

By nature of this being a legacy feature, it may not get fixed or may be given a low priority to fix, however these players are still quite common and it is annoying that they don't work properly.

### To Reproduce

1) Spawn or find a LegacyAudioPlayer (There is an example one in this public folder: `resrec:///U-Nytra/R-7BB5C9FD2C70DA29621CE6D45838C546765F0BE2A326A7370F52E548341E20FA`)
2) Observe that the menu buttons don't work

### Expected behavior

The menu buttons work.

### Screenshots

![2023-11-14 00 13 01](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/f59f8962-05a3-4cac-ab4e-8b0a31b8b142)

### Resonite Version Number

Beta 2023.11.13.1343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[DESKTOP-H976HO2 - 2023.11.13.1343 - 2023-11-14 00_11_21.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13343145/DESKTOP-H976HO2.-.2023.11.13.1343.-.2023-11-14.00_11_21.log)

### Additional Context

N/a

### Reporters

Nytra (Discord: nytra)

**Comment by Frooxius** [comment]
We could potentially fix this, but I don't know if this is worth prioritizing.

**Comment by Nytra** [comment]
This seems to be fixed in the prerelease as a side effect of some other stuff, so once that build goes to public this can be closed.

**Comment by Nytra** [comment]
Closing because this is fixed
