### ISSUE TITLE
Implementing a Flux node that performs Base64 encoding of images

### ISSUE THREAD

**Issue by Fukuro99** [Yellow-Dog-Man/Resonite-Issues#673]
### Is your feature request related to a problem? Please describe.

Currently, there are only a limited number of ways to send image data externally, and all of them are labor-intensive and time-consuming.
I believe that being able to send image data externally at high speed will greatly expand the possibilities of Resonite.

### Describe the solution you'd like

Implement a node to encode images in Base64.
It takes an ITexture2D as input and outputs a String.
It is preferable to use a format that outputs when a trigger is received.

### Describe alternatives you've considered

There are two commonly used methods.
・Save the image and send the recording URL externally
・Use sampleColor to obtain color information for each pixel and summarize it into a string

The first method requires the user to save the image. The second method is too time consuming

**Comment by Frooxius** [comment]
This will require this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/572

We're unlikely to provide node that encodes images specifically to Base64 - there's lots of different ways to do that (different pixel encoding/ordering, compressed, uncompressed, headers...). Instead we'll likely add nodes that encode input byte array to Base64 and nodes to extract image data from the image, which you could . That way you could compose this functionality yourself from those however necessary.

**Comment by Fukuro99** [comment]
I see.!That method is more widely applicable!

**Comment by shiftyscales** [comment]
Closing this in favour of #2078 which requests more general nodes for handling encoding/decoding Base64, and since the proposed solution of the initial issue was considered unsuitable.
