### ISSUE TITLE
Clicking on an active session of a world you have previously visited causes no session to be shown

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#675]
### Describe the bug?

In the session browser, if you click on an active session of a visited world, it causes no session to be shown in the overlay.

A visited world is one which shows the "visited" text in the corner of the thumbnail. These are worlds which have been stored in the local database as visited.

### To Reproduce

1) Go to active sessions in the session browser and find a session which shows the "visited" text in the corner of the thumbnail.
2) Click on it.
3) Observe that it doesn't show the session in the overlay, and instead just shows the world.
3.1) It also won't show any active sessions in the sidebar.

### Expected behavior

When you click on the active session, you should be shown that session in the overlay.

### Screenshots

![visited1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/95371f1f-a5e9-481f-8a63-6b620586c469)

![visited2](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/0fe1aa3d-8888-4cf7-a2fb-fe7d901fedfe)

![visited3](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/14206961/30772f30-8acf-4895-ad08-8825b899df6d)

### Resonite Version Number

Beta 2023.11.13.1343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[DESKTOP-H976HO2 - 2023.11.13.1343 - 2023-11-14 07_43_31.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13346086/DESKTOP-H976HO2.-.2023.11.13.1343.-.2023-11-14.07_43_31.log)

### Additional Context

Maybe somehow my local database is storing bad data because I do occasionally run mods, however I have seen that other people have reported this problem as well.

For example I talked about this problem a bit here https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/164

However I have decided to make this into its own issue now because I believe it is caused by a separate bug (local database world visited status) as opposed to the other problem which is when sessions show as worlds in the browser, which does not seem to be related to the world's visited status.

### Reporters

Nytra (Discord: nytra)

**Comment by Readun** [comment]
This still seems to be an issue, which makes joining an Empty Headless a hassle, as we need to Invite ourself into it or specific worlds.
On Normal active sessions, they can sometimes be seen, but vanish in a span of 1-10 seconds.
