### ISSUE TITLE
Some walls in Resonite Cloud Home do not have collider

### ISSUE THREAD

**Issue by eai04191** [Yellow-Dog-Man/Resonite-Issues#677]
### Describe the bug?

`Box Collider.129` in the window on the left side of the theater room does not have a collider component.
Therefore, if the player bumps into this area, they will fall out of the room unintentionally.

### To Reproduce

1. Open “Resonite Cloud Home” by “Resonite Team”
2. Head to the theater room
3. Hit the window shown in the screenshot
4. You will fall through the glass

### Expected behavior

There should be a collider here to keep you from falling.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/65ad78c4-3abd-4ac7-b6ce-98726a4a2fdd)

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/37afe2d1-c0d5-4461-a265-b7bbc3a5942d

### Additional Context

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/bfb72387-55a1-45e8-8c5d-66300372acf3)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/f87d7cef-0c6e-4500-b33f-b8a2e60a939f)

`Wall Window Circle Type 2` included in Resonite Essentials has collider set correctly.

### Reporters

IGN: Eai
Discord: `<@132779412771962880>` (`@eai`)

**Comment by AegisTheWolf** [comment]
The hole in the wall collider has been patched, closing this issue.
