### ISSUE TITLE
TypeObjectInput does not have a UI to input the type

### ISSUE THREAD

**Issue by marsmaantje** [Yellow-Dog-Man/Resonite-Issues#679]
### Describe the bug?

Currently when you create a ProtoFlux input of type Type there is no UI to give it a value.

### To Reproduce

Create an input of type Type
(eg. from the TypeColor node)

### Expected behavior

There is a UI to input a type

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/60362806/8d9eb616-df7d-45e2-896b-f69173295f90)

### Resonite Version Number

2023.11.131343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[LAPTOP-C_-_2023.11.13.1343_-_2023-11-14_19_18_17.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13353937/LAPTOP-C_-_2023.11.13.1343_-_2023-11-14_19_18_17.log)

### Reporters

marsmaantje
Zyzyl

**Comment by Frooxius** [comment]
Changing away from bug to enhancement. This is just a feature that's not implemented yet.

**Comment by Frooxius** [comment]
2024.1.24.834 now has proper UI! Thanks for report!
