### ISSUE TITLE
AnimJ Unable to Parse `floatQ` Value

### ISSUE THREAD

**Issue by stiefeljackal** [Yellow-Dog-Man/Resonite-Issues#686]
### Describe the bug?

Importing a track with the `valueTrack` value of `floatQ` will not parse the value in the `keyframes` items described in the JSON file. Instead, the value properties are either set to the default value `floatQ` or `NaN`. You can specify `x`, `y`, `z`, and `w` in the object, but these values will never be parsed as specified in the previous statement.

### To Reproduce

1. Create a Cube.
2. Import the provided [floatq_parsing_bug.animj.json](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13359106/floatq_parsing_bug.animj.json) as an .animj file. (GitHub does not allow uploading .animj files, so the file extension must be renamed to .animj).
3. Add an `Animator` component in the slot that was created when importing the .animj file.
4. Drag the `StaticAnimationProvider` component into the `Clip` field located in the `Animator` component.
5. Press the **Add** button in the `Animator` component.
6. Inspect the Cube.
7. Drag the Cube's `Rotation` field into the empty `0:` field in the `Animator`'s list.
8. Start the animation.

### Expected behavior

The Cube should be performing the following animation:

1. Rotating 180 degrees within 0.1 seconds
2. Staying in that rotation for 1.65 seconds
3. Rotating 180 degrees again within 0.1 seconds

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/20023996/6905bd11-d09c-47e7-9d66-a47058876266

### Resonite Version Number

2023.11.13.1343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index, Desktop

### Log Files

[JACKAL_MK2 - 2023.11.13.1343 - 2023-11-14 20_50_10.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13359221/JACKAL_MK2.-.2023.11.13.1343.-.2023-11-14.20_50_10.log)

### Reporters

* StiefelJackal
* Rucio
* Rixx
* Stella
* Storm_DPD

**Comment by Frooxius** [comment]
We didn't actually have support for these implemented. I've added it in 2023.11.15.1100, thanks!
