### ISSUE TITLE
"OnDestroy" node doesn't call on destruction.

### ISSUE THREAD

**Issue by zahndy** [Yellow-Dog-Man/Resonite-Issues#690]
### Describe the bug?

I have a thing on my avatar that cleans up a slot on my user when the avatar gets destroyed/swapped, since migrating my account this stopped working.
Upon further inspection I found that the On Destroy node doesn't call when it gets deleted.

### To Reproduce

Equip proto tip.
Spawn out Flow/Events/OnDestroy.
Pull out a display.
Destroy the OnDestroy node(tried radial and inspector).
The display does not get a call.

### Expected behavior

For the display or any attached logic to get a call upon destroying the OnDestroy node.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/491f6f4d-5180-4e9a-9c57-7f25e99bc836

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/662702/7f081665-1828-49f5-8a5a-4b724a8bebb6

### Resonite Version Number

2023.11.13.1343

### What Platforms does this occur on?

Windows

### Log Files

[HORIZON7 - 2023.11.13.1343 - 2023-11-15 07_31_07.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13361063/HORIZON7.-.2023.11.13.1343.-.2023-11-15.07_31_07.log)

**Comment by Frooxius** [comment]
This might be normal behavior, depending on how your object is structured. OnDestroy is called when the individual items are actually being destroyed. It is possible that the nodes that receive the event get destroyed before the node that triggers the event.

Generally OnDestroy isn't super useful unless you're careful about where the signal goes and the order of the objects so they get destroyed in the right order. I'd suggest using OnDestroying instead, which is specifically called before the actual destruction occurs.

**Comment by zahndy** [comment]
I guess its intended behavior.
Thanks for the explanation, I will use OnDestroying or try DestroyProxy again.
