### ISSUE TITLE
Can't return to Welcome Tab if navigated away from it

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#691]
### Describe the bug?

Launching the game and signing into an existing account on a new computer and clicking a notification while on the welcome screen can 'soft' lock you out of the rest of the dash until restarted. The Exit screen is always available at least.
Alternatively clicking on the exit tab will not allow returning to the Welcome screen.

You can get back to the contacts tab at least by clicking on a new notification but other than that, all the tabs stay disabled.

### To Reproduce

Launch the game on a new device/cleared database
Sign into an existing account with contacts
On the Welcome screen when it asks about the tutorial, instead click on a notification to take you to the Contacts tab or Click the Exit tab
The Welcome screen is not able to be re-clicked on and all tabs except for Exit are disabled
If you click away from the contacts tab, you can't go back to it.

### Expected behavior

The dash to unlock itself after some period of time and/or leaving the "Welcome" tab always enabled and clickable while available

### Screenshots

![3ad3c342ae](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/6bdf042c-387d-4cbf-a3f9-12dd1121a38b)

### Resonite Version Number

2023.11.13.1343

### What Platforms does this occur on?

All

### Log Files

Provided by ErrorJan: [JAN-ARCHPC - 2023.11.15.1158 - 2023-11-15 20_55_59.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13369144/JAN-ARCHPC.-.2023.11.15.1158.-.2023-11-15.20_55_59.log)

### Reporters

_deltawolf, ErrorJan

**Comment by Frooxius** [comment]
Fixed in 2023.11.24.1379. Thanks!
