### ISSUE TITLE
The menu displayed by pressing the Extras button in the Inspector cannot be selected in freeform mode.

### ISSUE THREAD

**Issue by eai04191** [Yellow-Dog-Man/Resonite-Issues#693]
### Describe the bug?

The menu item that is displayed by pressing the **extras button** in the inspector added in [2023.11.11.1231](https://discord.com/channels/1040316820650991766/1154514012143362151/1172998867105624145) cannot be selected when in freeform mode or at random angle.

### To Reproduce

1. Press F6 to switch to freeform mode
2. Open Inspector
3. Press the extras button to bring up the menu
4. Check that the item is not selectable

### Expected behavior

Menu items should be selectable regardless of screen mode.
The context menu that opens by pressing T can also be selected in freeform mode.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/53f624a8-aed4-41a2-bc81-9d2b9e27fd84)

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/37516ebc-546e-41fe-b9f8-5ee5ef78e6fb

### Resonite Version Number

Beta 2023.11.13.1343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[SOY - 2023.11.13.1343 - 2023-11-15 22_20_38.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13365187/SOY.-.2023.11.13.1343.-.2023-11-15.22_20_38.log)

### Reporters

Resonite: Eai
Discord: `<@132779412771962880>` (`@eai`)

**Comment by ohzee00** [comment]
Oh yeah this issue, beat me to listing it. I _believe_ the inspector itself blocks the context menu for some reason with how it spawns, this behavior also happens for the Drive and Drive with writeback context menu while in UI focus mode.

**Comment by 5H4D0W-X** [comment]
It looks like when the menu is not opened via the dedicated button or key (i.e. by ValueCopying, clicking the extras button), it doesn't get the same laser priority as when it is, so the inspector can block it. I just checked and it does always have priority over regular objects, but inspectors (iirc because of the Developer tag?) seem to have equal or higher priority

**Comment by Frooxius** [comment]
This is same issue as this, closing as duplicate: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/634
