### ISSUE TITLE
Timer node becomes a Missing Component

### ISSUE THREAD

**Issue by orange3134** [Yellow-Dog-Man/Resonite-Issues#694]
### Describe the bug?

Timer nodes included in items migrated from previous platform become Missing Component.

I remember that at least in version 2023.11.8.335 they were properly converted, but now (2023.11.13.1343) it does not seem to be working.

### To Reproduce

1. Spawn this item.
resrec:///U-rhenium/R-a86487d7-e8b5-41c3-87da-8b9ccffad515
2. Open the item's inspector and check "UserInfoList by rhenium/LogiX/Timer".
3. You will find Missing Component.

You can confirm that not only this item but also other items that used Timer have the same problem.

### Expected behavior

The Timer node should be converted to ProtoFlux.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56525091/7670dcf2-9158-4091-9d43-1f55cec241f9)

### Resonite Version Number

2023.11.13.1343

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[SHIRUKO2 - 2023.11.13.1343 - 2023-11-16 01_22_50.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13367046/SHIRUKO2.-.2023.11.13.1343.-.2023-11-16.01_22_50.log)

### Additional Context

I believe the name of Timer has recently been changed to Seconds Timer. Is that the cause?

### Reporters

orange3134
motomaid
0_vex_0

**Comment by Frooxius** [comment]
Fixed in 2023.11.15.1100, thank you!
