### ISSUE TITLE
Default Chirality input on ProtoFlux nodes is "-1"

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#703]
### Describe the bug?

Despite not being a valid input for the enum, the default input for Chirality for nodes like HasTool is "-1". This causes the node to simply not function in its default state.

### To Reproduce

- Spawn a HasTool ProtoFlux node
- Use a ProtoFlux tip to pull out the default Chirality input

### Expected behavior

The input should default either to Left or RIght

### Screenshots

![Resonite_S7arD3hRVT](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/44bb5ffd-4def-4319-8b73-2af533d74353)

### Resonite Version Number

Beta 2023.11.15.1158

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### What headset if any do you use?

Index

### Log Files

[DESKTOP-1E2V3A8 - 2023.11.15.1158 - 2023-11-15 11_43_31.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13368990/DESKTOP-1E2V3A8.-.2023.11.15.1158.-.2023-11-15.11_43_31.log)

### Reporters

code807

**Comment by Frooxius** [comment]
This is intentional.

We don't want to assume either Left or Right as default for this node, because this can be confusing. 

The default value is intentionally set to invalid value, forcing the user to make an explicit choice on whether they want Left or Right.
