### ISSUE TITLE
The audio sliders in the settings panel should be linear

### ISSUE THREAD

**Issue by TisFoolish** [Yellow-Dog-Man/Resonite-Issues#709]
### Is your feature request related to a problem? Please describe.

Right now the audio sliders in the settings panel are non-linear, which is confusing to new and old users alike. Most people expect to put an audio slider at halfway for audio to be 50%, not 25%.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38511571/4db8e0fd-96ce-4b37-bdc9-352fc9d1d106)

From an end user's perspective, this doesn't make sense for audio sliders.

### Describe the solution you'd like

Set the power on the slider component for each audio slider to 1. That will allow the sliders to behave more like people would expect

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/38511571/386e2b04-97ff-41b3-869c-1c857efffc58)

### Describe alternatives you've considered

There is a mod that redoes the settings panel entirely and allows for linear sliders, but a mod isn't really a proper fix.

https://github.com/XDelta/SettingsRedux/

**Comment by Frooxius** [comment]
This will be addressed with the Settings UI rework.

**Comment by TisFoolish** [comment]
Why not beforehand? All it requires is setting the power to 1 on the sliders. It's not an addition or even a huge change, just a small tweak.

**Comment by ProbablePrime** [comment]
Any settings work we perform now will be wasted as it is under re-work.

**Comment by TisFoolish** [comment]
I disagree. It's a very small amount of work that'll instantly benefit everyone, ***especially*** new users. That isn't a waste, that is a fantastic work to benefit ratio, even if that work will eventually be replaced. with something better.

**Comment by ProbablePrime** [comment]
Unfortunately, we will have to agree to disagree. We'll target this after the settings rework. Thank you.

**Comment by Frooxius** [comment]
It is a waste. Doing this means that a different issue does not get addressed instead. Spending engineering time on same issue twice in a short time vs spending the time on two different issues is objectively worse.

It is more complicated too - you want the audio sliders to be logarithmic, because that's how our hearing works, but the displayed value to be linear instead.

**Comment by Frooxius** [comment]
This has been resolved via the new Setting UI released in 2024.4.15.1407
