### ISSUE TITLE
When Raycaster hits LocalNameBadge, world crashes when driving its output

### ISSUE THREAD

**Issue by lill-la** [Yellow-Dog-Man/Resonite-Issues#712]
### Describe the bug?

When Raycaster hits LocalNameBadge, world crashes when driving its collider(slot) output

### To Reproduce

Convert the HitCollider output of the Raycaster node to a Slot with the GetSlot node and drive to a Reference (e.g. ReferenceField<Slot>) that is a SyncRef<Slot>.
Then, from the DashMenu, set the state to "Use default nameplates" and apply Raycaster to NameBadge and the world will crash.

### Expected behavior

Do not crash

### Resonite Version Number

Beta 2023.11.15.1158

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[FEIRIL - 2023.11.15.1158 - 2023-11-16 11_44_38.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13371751/FEIRIL.-.2023.11.15.1158.-.2023-11-16.11_44_38.log)

### Reporters

lill (Discord: `lill.la`)

**Comment by liny-fox** [comment]
A very easy reproduction for this is to attempt to stick a sticky note to someone who has "Use default nameplates" set to their nameplate.

**Comment by Banane9** [comment]
I feel like I saw an issue here involving assigning references from userspace to something in a world, which could be related, depending on how local nameplates are done. I can't seem to find it however.

Alternatively, it could be a problem with references to local slots / components on them 🤔

**Comment by Zyzyl** [comment]
@Banane9 Are you thinking of this one https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/18? In the patch notes Froox mentions:
> Add guard against writing references to local elements to non-local dynamic variable spaces.
-- This fixes crash when writing haptic sampler output to dynamic variables (issue #18)
-- Dynamic variable nodes now have a new continuation OnFailed. This will fire when invalid write has been attempted

**Comment by Banane9** [comment]
> @Banane9 Are you thinking of this one #18? In the patch notes Froox mentions:
> 
> > Add guard against writing references to local elements to non-local dynamic variable spaces.
> > -- This fixes crash when writing haptic sampler output to dynamic variables (issue #18)
> > -- Dynamic variable nodes now have a new continuation OnFailed. This will fire when invalid write has been attempte

Yup, that's the one I was thinking of. And it was about local elements and not userspace (which would be weird anyways?), so it makes even more sense with my second theory.

> it could be a problem with references to local slots / components on them

**Comment by Nytra** [comment]
I had to help recover someones MMC world which was crashing due to this, so it's still an issue in Beta 2024.2.12.1430

**Comment by ProbablePrime** [comment]
I'll pick this up as a part of my #1175 work which is mostly other crashes.

**Comment by ProbablePrime** [comment]
I took a look at this one, the error is deep within the sync/datamodel code within Resonite. I am very not famliar with this so will have to pass to froox.

**Comment by Frooxius** [comment]
Fixed this in 2024.5.29.27!
