### ISSUE TITLE
"Reset to default" button in inspectors should be undoable

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#713]
### Is your feature request related to a problem? Please describe.

The "Reset to default" button is currently not undoable. If you click this button to reset a field value to default you cannot use undo to go back to the previous value.

### Describe the solution you'd like

The button should be undoable.

### Describe alternatives you've considered

Trying to remember what the previous value was.

### Additional Context

N/a

**Comment by shadowpanther** [comment]
Related to #707

**Comment by Frooxius** [comment]
Tweaked in 2023.11.18.1263! Thanks!
