### ISSUE TITLE
Userspace Context Menu for "Overwrite World" Spawns at [0,0,0]

### ISSUE THREAD

**Issue by PointerOffset** [Yellow-Dog-Man/Resonite-Issues#722]
### Describe the bug?

While trying to update a world using the World Overwrite feature it was discovered that overwriting worlds is non-functional. Holding a world orb, placing my laser through the intended target of the overwrite, and clicking does present the overwrite option. Clicking the option doesn't seem to result in any action at all. Nothing is even logged in my log file.

I think the intention is for a confirmation prompt to ask if I'm sure I want to overwrite. It seems like that prompt is never being called upon. Since I can't confirm the overwrite, nothing happens.

This was originally replicated when trying to overwrite a world belonging to a group. However, for this bug, I also replicated the issue myself with world orbs I own. The behavior was identical in both cases.

### To Reproduce

1. Spawn two different world orbs.
2. Grab the orb you intended to use as new data for the overwrite with your laser.
3. Position your laser so it passes through the world orb you intended to overwrite.
4. Click your primary button.
5. Select "Overwrite [WORLD ORB NAME]" from the context menu

### Expected behavior

Attempting to overwrite one world orb with another will trigger a confirmation choice in the context menu. When confirmed, the target world will be overwritten with the new world data from the held orb. Declining will cancel the action.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/61102129/3d3d6558-c85b-4f04-a8b1-f9873ebc2459

### Resonite Version Number

2023.11.15.1158

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Oculus Queset Pro w/ Virtual Desktop, Desktop/Screen Mode

### Log Files

[DESKTOP-3NG8JGV - 2023.11.15.1158 - 2023-11-16 17_34_32.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13386040/DESKTOP-3NG8JGV.-.2023.11.15.1158.-.2023-11-16.17_34_32.log)

### Additional Context

This feature isn't particularly well know so I imagine it's not often used. However, at least for our group's workflow, it's becoming somewhat essential.

We're using a pattern of Build World -> Publish -> Save new "Dev Branch" Copy -> Develop updates on "Dev Branch" -> Overwrite Published World w/ "Dev Branch" Copy

With this feature broken it unfortunately means we have to make changes directly in the published production world. We can get around the difficulties of this process by developing in another world, saving a slot in our inventory that's effectively the whole world root, and transplanting it into the production world.

This workaround can create tedious pain points though. Such as accidentally overriding Dynamic Variable values if we aren't mindful of Dynamic Variable Space names that might collide during the replacement.

### Reporters

GitHub: @PointerOffset. Discord: @spexcat
GitHub/Discord: @badhaloninja
GitHub: @RileyGuy, Discord: BlueCyro

**Comment by PointerOffset** [comment]
I was digging into this more with @RileyGuy, attempting to make a mod to get around the issue for now. We discovered the nature of the bug is very different. It turns out the confirmation prompt is being spawned. However it's not spawning in the correct location in *most* cases.

Instead of not working at all, the Userspace Context Menu is spawning at `[0,0,0]` in Userspace making it *seem* like it did not spawn. In my case I was able to get the confirmation menu to come up consistently in the expected location with the following steps:

1. Spawn two world orbs
2. Grab one orb with a laser
3. Position the grabbed orb behind the other orb so the laser passes through the other orb
4. Click the primary button to open the context menu for overwrite
5. **Release the grabbed orb while the context menu is open.**
6. While the context menu is open, position yourself at least 1 meter away from the world orbs
7. Click the "Overwrite" option in the context menu

The Userspace confirmation dialog will pop up as expected in front of the user.

**Comment by PointerOffset** [comment]
As an additional note: The same bug may be affecting other Userspace Context Menus. I am experiencing similar inconsistency with the confirmation dialog on removing SimpleAvatarProtection.

**Comment by PointerOffset** [comment]
Apologies for not getting around to replicating this sooner in VR.

I have a video attached here. The bug still occurs, it's just slightly different. If you are holding the sphere when you click the overwrite button, you don't get the UserSpace context menu to confirm. If I let go of the sphere _then_ click the overwrite button, the menu appears as expected.

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/61102129/087a4ec6-8eb0-43fb-ad61-aca82c7aad40

**Comment by gentlecolts** [comment]
Ran into something that I think might another example of this same issue.  Issue can occur with the save world options as well, requiring third person to interact with depending on your view orientation (and dash orientation?) when spawned:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/6eda922d-ae89-467c-b251-ad0ea8a270fa)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/9acd0875-c1ef-4264-a7cb-ea1e0c417d16)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/2545023/e62fe689-04bc-486b-826f-45eff42699d4)

**Comment by shiftyscales** [comment]
Seeking input from @ProbablePrime - this is potentially related to similar issues such as #2855 which you'd recently resolved and #2941 which recently came up.

**Comment by ProbablePrime** [comment]
I'm going to merge this with #2941 As it is the same root cause and ryuvi's working on it.

Thank you! Not quite a duplicate but still better to centralize.
