### ISSUE TITLE
_scaleCompensation of AvatarAudioOutputManager set incorrectly by headset height

### ISSUE THREAD

**Issue by Duskitten** [Yellow-Dog-Man/Resonite-Issues#73]
### Describe the bug?

I've been having many issues with voice normalization doing absolutely nothing via the settings outside of making my mic sound like it's at max volume, various sources have told me when you get close to the ground the system compensates for your voice, which is causing this, however using a smaller avatar 24/7 this seems to be a large issue. Turning it off however, my mic is incredibly quiet and nobody can hear me.  So something with this system isn't working quite right.

### To Reproduce

Afaik, Use a small avatar, get your head close to the ground, and then go away from it, you will be insanely loud. Or just turn voice normalization on, it's pretty 50/50 with most people.

### Expected behavior

I would assume voice normalization would allow for your voice to simply be heard at a somewhat level sound instead of blasting people's ears out

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Rift S, Desktop

### Reporters

Duskitten
Ohzee
Nutcake

**Comment by Enverex** [comment]
I'm logging an issue for voice being an issue in general, but this is also definitely not helping. Normalisation basically means that everyone is maxed out at all times. Doesn't matter what I do, this is the result:

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/958670/08b7266c-8952-4959-80b1-3f8b8f95ea9a)

Every sound anyone ever makes is MAX VOLUME.

**Comment by Frooxius** [comment]
@ProbablePrime I'm looking at Earmuff settings right now, but through chain of underlying issues I ended up here.

I feel that it might be best to address this first, then the voice roll-off, then Earmuff maybe, but you have this issue right now.

Would you mind if I steal it? Or would you want to handle this independently from the chain? (though I feel that'll make the other issues more difficult, as this is causing some inconsistencies for other issues).

**Comment by Frooxius** [comment]
I strongly disagree with that. 

From engineering perspective, if there's a bug resulting in inconsistent behavior, then fixing other things that this inconsistent behavior might affect becomes much harder, because all the testing data end up being potentially "tainted" and confusing.

Generally I will always try to fix bugs affecting something first, before I start tweaking it, because otherwise it becomes hard to distinguish which feedback is affected by the bug and which is not and that adds a lot more "noise", that's harder to deal with.

**Comment by Frooxius** [comment]
This should be fixed in 2024.5.1.68! Keep on a lookout if the issue still persists!
