### ISSUE TITLE
'Type Input' Protoflux Node should have Text Box

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#731]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when I need a type input in protoflux because I cannot just write the type into the node.
Instead I need to inspect it and type the name of the type into the component.

### Describe the solution you'd like

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/60073468/dcc9f8e0-ab77-40d7-ac0d-0b1cc99c1680)
This node should have a text field just like a string input node.

### Describe alternatives you've considered

Not doing this. (why?)

### Additional Context

None

**Comment by Frooxius** [comment]
This is duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/679

Closing
