### ISSUE TITLE
Mirror normal maps make the mirror pink

### ISSUE THREAD

**Issue by Stellanora64** [Yellow-Dog-Man/Resonite-Issues#735]
### Describe the bug?

when applying a normal map to a mirror / render material the material becomes pink.

### To Reproduce

Apply a normal map to a render material.

### Expected behavior

The normal map should be applied to mirror /  renderer materials correctly and not break.

### Screenshots

![20231119145428_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/91010433/c1451f25-bc47-4a85-ae1e-a0cb8ddc5bb1)

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop, HP reverb G2 (although, headset doesn't affect this issue)

### Log Files

[DESKTOP-F65B6FQ.-.2023.10.20.831.-.2023-11-02.17_39_13.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13402516/DESKTOP-F65B6FQ.-.2023.10.20.831.-.2023-11-02.17_39_13.log)

### Additional Context

Reproduction item: `resrec:///U-Crusher/R-2D77E270D4AD5F64B92D15A15FCA0E74CD8B628765C2902F8DEF2E7B8A942A6A`

### Reporters

Stellanora

Grafflesnark

Storm_DPD

**Comment by Garfflesnark** [comment]
Can confirm this is consistent and definitively broken.

Affects the reflective water and other effects that I use for various installations.

**Comment by shadowpanther** [comment]
Duplicate of #174

**Comment by Stellanora64** [comment]
> Duplicate of #174

You are correct, closing as duplicate.
