### ISSUE TITLE
Colors of buttons connected to RefEditors are set on every interaction

### ISSUE THREAD

**Issue by 5H4D0W-X** [Yellow-Dog-Man/Resonite-Issues#740]
### Describe the bug?

When a RefEditor has a button with non-driven color values associated with it, the colors in the button get set every time the editor is interacted with, e.g. every time a slot is dropped into a slot field.

### To Reproduce

- inspect any refeditor, for example the Parent field of a slot in an inspector
- change the colors in the button
- change the slot reference that the refeditor is controlling, e.g. by pressing the null button
- observe the colors being reset to default values

### Expected behavior

The colors are kept at their set values.

### Screenshots

Before Interaction ![2023-11-21 03 02 26](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/99607717/cdd547c5-a933-41c4-92a2-3fd16eb17921)
After Interaction ![2023-11-21 03 02 41](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/99607717/4e904d4e-cd0f-4606-9e03-5e40582b1c07)

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

N/A

### Additional Context

this breaks the visuals on migrated items due to the default values going from white to a dark color, and makes it annoying to create custom RefEditor fields

### Reporters

ShadowX / @ shdw_x

**Comment by Frooxius** [comment]
This is intentional behavior, to ensure they're always the right color. This can change at any time to reflect status, like links or drives.
