### ISSUE TITLE
Ability to download our Resonite content to our own machines as a local backup

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#744]
### Is your feature request related to a problem? Please describe.

I think having the means to make local backups of our content would be very useful. Consider years from now if the Resonite cloud servers go offline. It could mean that a lot of content would get lost or become inaccessible.

### Describe the solution you'd like

Allow us to download our Resonite content to our own machines as a local backup.

### Describe alternatives you've considered

Hoping that the Resonite cloud servers never go offline.

### Additional Context

https://en.wikipedia.org/wiki/Lost_media

**Comment by RockstarRaccoon** [comment]
Currently the only way to keep these on your own computer is through a mod, or by manually exporting them all and hoping you don't lose too much of the important data.

**Comment by Nytra** [comment]
I guess this is solved with the addition of the AccountDump tool
