### ISSUE TITLE
SRanipal is not released properly at quit of resonite

### ISSUE THREAD

**Issue by hantabaru1014** [Yellow-Dog-Man/Resonite-Issues#746]
### Describe the bug?

SRanipal is not released properly at quit of resonite.
When Vive Pro Eye or FacialTracker is connected but none of the software is in use, the SRanipalRuntime robot icon in the task tray is orange. And green if any of the software is in use. Thus, when resonite starts, it turns green and functions, but does not return to orange when resonite exits.
This is not a major problem, but while green, SRanipalRuntime constantly consumes CPU resources.

### To Reproduce

1. Start SRanipalRuntime with ViveProEye and FacialTracker connected. The SRanipalRuntime icon in the task tray will be orange.
2. Start up resonite with VR mode. The icon will be green.
3. Quit resonite
4. The icon in the task tray is still green

### Expected behavior

In step 4, the icon returns to orange.

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows

### What headset if any do you use?

ViveProEye

### Log Files

This does not cause any errors, so I think there is no corresponding part in the Log.

### Additional Context

I think ViveProEyeTrackingDriver.Destroy() is not being called correctly because of the process kill immediately after Application.Quit() in FrooxEngineRunner.Shutdown()
So just calling ViveProEyeTrackingDriver.Destroy() on engine shutdown should solve this problem!

### Reporters

resonite: baru3(U-hantabaru1014)
discord: baru14

**Comment by ProbablePrime** [comment]
Possible Duplicate/Related to: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/296

**Comment by Frooxius** [comment]
I've looked at both and it's not a duplicate, these are distinct issues, but they are related. They are sufficiently independent of each other that we can keep both open.

**Comment by ProbablePrime** [comment]
Ok great! at least they are tagged as related now.

**Comment by Frooxius** [comment]
This has been fixed in 2023.11.24.1379, thank you!
