### ISSUE TITLE
Standard Controller doesnt support jump button

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#750]
### Describe the bug?

When using a generic controller to play (xbox one, steam deck, etc) there is currently no support for getting the jump button on the standard controller flux node

### To Reproduce

open a standard controller flux node and have it listening to a generic controller. when pressing the jump button, none of the booleans will change to true

### Expected behavior

i expect to have a jump button mappable like the rest of the controller layouts

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/c087f46a-7aa7-4c39-b765-cb1195197203)

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

N/A

### Log Files

N/A

### Reporters

ultrawidegamer

**Comment by Frooxius** [comment]
This is not a bug.

The "Standard Controller" represents a minimal set of buttons & inputs that works across wide variety of controllers. 

Jump is not part of this minimal set.

You'll need to use more specific nodes or request node for accessing buttons of standard gamepad layouts and such (there might be issue for this already, I recommend searching first).
