### ISSUE TITLE
switch color picker to use unlit

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#751]
### Describe the bug?

color picker currently does not show an accurate color when picking your color and the material should be switch to use unlit instead of PBS

### To Reproduce

pull out color picker tool, select a color and observe that the tool does not appear to be the correct color 

### Expected behavior

i expect something like a color picker to always have very accurate color and not to have things like lighting and shading affect it 

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/a4996f9f-45c8-46d4-a040-3e837b8efd6d)

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows, Linux

### What headset if any do you use?

Quest 2

### Log Files

N/A

### Reporters

ultrawidegamer

**Comment by AegisTheWolf** [comment]
Both the color tool and multi-tool have been updated with the new material edit. The one in the cloud home will update the next time we work on the cloud home.

**Comment by AegisTheWolf** [comment]
Updated color tool in cloud home now, closing issue.
