### ISSUE TITLE
OnGrabbableGrabbed and IsGrabbableGrabbed both dont work on first grab from grab instancer

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#753]
### Describe the bug?

When pulling an object out of a grab instancer for the time it does not trigger an OnGrabbableGrabbed impulse and also does not enable the IsGrabbableGrabbed boolean for the very first time pick up event from the grab

### To Reproduce

create a simple grab instancer an track the OnGrabbableGrabbed and IsGrabbableGrabbed both of these values will not be tracked 

### Expected behavior

i expect to get impulses and boolean updates from the grab instancer grabs

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/d633ab3a-e403-49dc-a1e3-5b7582bf9dbd)

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

N/A

### Reporters

ultrawidegamer

**Comment by ohzee00** [comment]
I think this not fully a bug, can you test on the grab instancer itself OnGrabbableGrabbed?
I believe when you first grab, the item for the instancer isn't even made, so you're technically grabbing the instancer itself, not the item it duplicates.

**Comment by ultrawidegamer** [comment]
i have tested on the grab instancer as well and get the same result

**Comment by ohzee00** [comment]
https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/33611545/774b307b-4f6c-41fc-920b-b886a4ba3c1e

Are you certain? I did a test case with a grab instancer, with the instance having protoflux underneath to show the event and bool.
The grab instancer gets a event, but is not marked as grabbed, however the opposite is true for the instanced object, has no event but is marked as grabbed.

**Comment by ultrawidegamer** [comment]
hmm, maybe that is what the difference is? i was also setting the instance to be itself... i will do a little more quick testing and report back

**Comment by ohzee00** [comment]
In my case I made the instance a slot underneath the Grab instancer if that helps, I can see there being a problem if you make the grab instancer instance itself.
It could work if the grabbable has a higher grab priority though(compared to the instancer), at least if physically grabbed

**Comment by ultrawidegamer** [comment]
ya i just tried everything again and cant reproduce the issue anymore even after having it for multiple days and having multiple people looking at it... if i run into the issue again i will create a new issue with a link to a public version of the broken item

**Comment by Frooxius** [comment]
Merged this in 2024.9.4.357!
