### ISSUE TITLE
Missing swapping image colors

### ISSUE THREAD

**Issue by ultrawidegamer** [Yellow-Dog-Man/Resonite-Issues#756]
### Describe the bug?

when viewing the list of buttons that can be applied to images i notice that some of the color swap modes are missing 

### To Reproduce

open an image and view the buttons at the bottom

### Expected behavior

all color swaps are available 

G <--> R
B <--> R
B <--> G

are missing

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/147885362/fb480b76-f746-4549-9d34-b95cb8613aae)

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

N/A

### Reporters

ultrawidegamer

**Comment by Frooxius** [comment]
This is intentional. Those options are equivalent to each other.

R <---> G is swapping red and green
G <---> R is swapping... also red and green

The order here doesn't matter.
