### ISSUE TITLE
If Japanese is used in the path to the Resonite installation, the Importing files with Asset Class will be unknown.

### ISSUE THREAD

**Issue by FRICK-ELDY** [Yellow-Dog-Man/Resonite-Issues#758]
### Describe the bug?

If Japanese is used in the path to the Resonite installation, the Importing Model files will be unknown.

### To Reproduce

1. Install Resonite in a path with Japanese characters, such as `D:\フォルダ\game\スチーム\steamapps\common\Resonite`
2. login.
3. Drag and drop a 3D model such as FBX or GLB onto the Resonite screen.

4.The model importer does not appear and a binary file appears.

### Expected behavior

If Resonite is installed in a non-English language file path, the experience may be compromised by the inability to import avatars.

### Screenshots

![2023-11-22_03 15 35](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/50221317/6421669f-7ba1-4965-871e-27ba56ff7527)
Normally, I would like to see the model importer on the right, but the binary file on the left appears.
![2023-11-22_03 15 59](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/50221317/fd20de12-82cb-4fd8-8414-d433ca9aa12f)
Pressing the import button should bring up the model importer, but it is not responding.

I assume this is because Importing files with Asset Class is Unknown, as shown in the log below.

If the Resonite installation path does not include Japanese, the problem does not occur.

### Resonite Version Number

2023.11.18.1263

### What Platforms does this occur on?

Windows

### Log Files

* Importing files with Asset Class Unknown 
[DESKTOP-Q9JF59U_-_2023.11.18.1263_-_2023-11-22_12_19_15.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13434089/DESKTOP-Q9JF59U_-_2023.11.18.1263_-_2023-11-22_12_19_15.log)

* Importing files with Asset Class Model
[FRICK - 2023.11.18.1263 - 2023-11-22 12_43_29.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13434084/FRICK.-.2023.11.18.1263.-.2023-11-22.12_43_29.log)

### Reporters

Discord:frick_no96

**Comment by Frooxius** [comment]
This should be fixed in 2023.12.15.22!

Please reopen if you still experience issues!
