### ISSUE TITLE
color picker does change values / show values different

### ISSUE THREAD

**Issue by Ardescar** [Yellow-Dog-Man/Resonite-Issues#776]
### Describe the bug?

When someone is overdriving the values of the colors over 1 then the other values (RGB) get reduced in that moment.
This happened to me by accident when i entered numbers and other allready entered values did get changed.

And the other issue that confused me:
When a color Value is above 1 allready (in inspector) and i open the color picker window then the value shown is 1 even tho it is above 1. Also the the Gain is higher and shows that something is off.

### To Reproduce

Open the Color Picker window on a color that has values over 1 - you see it does not show values correct.

And the second issue is when i change the value above 1 - by accident or on purpose - you can see that the other RGB values are getting reduced. 

### Expected behavior

That it shows the color values correctly and does not change the other values.

### Screenshots

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/63201013/30852164-a95b-4078-b78d-afc58cfe2bcd)
Normal

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/63201013/2e175387-af59-4db5-a7f6-04f932beea14)
if I enter a 2 into blue - the other values are getting reduced by the picker - (if i repeat that other colors are at some point at 0)

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/63201013/cf9ebc4b-5d1a-47d2-a424-dd6dafb8b60b)
i save the value like this.

![grafik](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/63201013/4ed05245-97da-4ed1-aea1-1285c5d7338a)
When i open the picker again the value shown is 1 but the color is overdriven still.  it should show 10.73 for blue.

### Resonite Version Number

Beta 2023.11.18.1263

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Index - Desktop

### Log Files

I can provide in a bit.

**Comment by JackTheFoxOtter** [comment]
It's increasing the gain because that's a multiplier for all channels. Having that as a separate slider makes it easier to make colors glow without changing the hue. However, you should not use values > 1 for sRGB color space, since that is not actually defined, and might look different / break in the future. (That's the reason the gain slider is disabled on sRGB).

If you want to use values > 1 (so anything that glows) you are supposed to use linear color space. There you can increase the gain directly.

**Comment by Ardescar** [comment]
Yeah you are right. Sometimes its confusing. But it should still not change other values when i enter a value?
I was setting up some Values and then did type in new values in a different color and the other values did change.
So i had to type them in again. just because i entered a value to high while typing.
