### ISSUE TITLE
2023.11.24.1379 Brought a few New issues

### ISSUE THREAD

**Issue by SpaceGaytor** [Yellow-Dog-Man/Resonite-Issues#782]
### Describe the bug?

-I am now stuck in my Local Home.
-Cloud Home does not Load
-I have intermittent sync Errors, When I open, it will either sync or not sync.
-I have tried to load into other worlds and am stuck in a looping load and do not leave Local Home.
-Im unable to send messages
-I "was" unable to exit Resonite for the first few tries, but seems to be working again as the last time I was able to exit normally.

### To Reproduce

Im unable to leave Local
![Untitled](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/150499776/a02cafa2-76d0-41b6-a2dc-c9389c8457b4)

### Expected behavior

Load in Local, Then load into Cloud Home, Sync normally, able to load into other worlds.

### Resonite Version Number

2023.11.25.12

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[SPARTAN118 - 2023.11.25.12 - 2023-11-24 18_26_02.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13462664/SPARTAN118.-.2023.11.25.12.-.2023-11-24.18_26_02.log)

[Player.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13462668/Player.log)

### Additional Context

I was able to use Resonite Properly before the Hotfix, The Phantom Logo issue I had before is gone but now this has changed everything else.

### Reporters

SpaceGaytor

**Comment by SpaceGaytor** [comment]
To Add to this, I was not using any mods during these tests

**Comment by shadowpanther** [comment]
On your screenshot the version is the previous one, before the assets loading hotfix from #780 
That would be worlds not loading. It's fixed now, but the saving is broken, fix incoming.

**Comment by SpaceGaytor** [comment]
I used the picture from before because nothing has changed

**Comment by shadowpanther** [comment]
2023.11.25.12 has loading fixed, wait for #781 to be fixed before re-confirming your current issue.

**Comment by SpaceGaytor** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/150499776/7873a99d-3fc5-466a-a096-06e2f8bbbf95)

decided not to Crop it

**Comment by SpaceGaytor** [comment]
Should I just wipe everything clean and reinstall?
