### ISSUE TITLE
allow an option to import a rigged mesh that fails to recognized as a biped anyway

### ISSUE THREAD

**Issue by Kirv-goldblade** [Yellow-Dog-Man/Resonite-Issues#799]
### Is your feature request related to a problem? Please describe.

i've been encountering errors with importing an avatar where despite having all needed bones somehow some of them are failing to recognise. i'd like to be able to upload it anyways and see what fails when i try ti use it as an avatar

### Describe the solution you'd like

simple. when a rigged model fails to be recognized as bipedal in addition to the import report that is generated normally give us an "import anyway?" prompt to allow user to potentially bypass a detection error  

### Describe alternatives you've considered

at present there seem to be no other solutions other then waiting on improvements to the rigging detection

**Comment by Frooxius** [comment]
I don't understand. The failed detection does not prevent the mesh from being imported, it just won't auto setup IK and other aspects of it.

What are you seeing happen on your end? Does the mesh disappear?

**Comment by Kirv-goldblade** [comment]
yeah the mesh just vanishes assuming it even rendered in the first place

**Comment by Kirv-goldblade** [comment]
so i found that the mesh was uploading just being shrunken down to a pin point size. however the mesh acts completely unrigged

**Comment by Frooxius** [comment]
Are you not able to move the bones through the inspector? It would help to provide pictures or videos.

**Comment by Kirv-goldblade** [comment]
without converting to an avatar the rigging seems to work fin. but the moment i try converting to an avatar the entire model seems to become unrigged (the bones are still present but none of the react to avatar movement (legs don't walk etc))

**Comment by Frooxius** [comment]
That is expected behavior. If it doesn't recognize biped, it can't setup the biped.

I don't really see an actual issue here at this point, it just seems more like misunderstanding.

**Comment by Kirv-goldblade** [comment]
Is there any way to force identify bone to the system? It seem to be failing to see the bones in the Hierarchy despite seeing the bones and them being rigged in a manner that worked on a different version of the same avatar (I was able to import a prefab version of the avatar with the exact same skeleton and had it work fine but why I try with the custimiszable versions the arm and hand bones are not recognized (specificly it seem the upper arm are the ones missing from the hierarchy and because they are the lower arm and hand are considered missing too)

**Comment by Kirv-goldblade** [comment]
i won't call the original issue solved per say but i was eventually able to to work around it (oddly the failure only happens some of the time and i was eventaully able to complete an import that actually recoginzed all the bones). i still had a scaling issue (thankfully only ending up about 3/4th the intended size as opposed to microscopic) in import but that is less troublesome so i'm going to take the win where i can get it and call this solved

**Comment by Frooxius** [comment]
It's not something you can "force". The system needs to understand and recognize the rig as biped, otherwise it won't know how to set it up.

If it's not recognizing the biped, despite the skeleton being one, you can make an issue with that specifically and provide the rig that we can look at and we can see if we can fix that.

But if you want it to set it up as biped when it doesn't understand it - this is not possible.

**Comment by Kirv-goldblade** [comment]
this issue some how resolved itself while trying to upload a fresh copy to provide more info with (well more accurately it imported partially successfully ending us with the VRIK but lacking the the biped rig, next attempt it had the biped rig but it only the debug only had the had bones detected, then finally i managed to upload a version that possessed the VRIK, the biped rig and recognized all the necessary bone and i was able to make a working avatar) (this was all done attempting to upload the same fbx file without making any changes between uploads
