### ISSUE TITLE
Make inspector the scale of 1,1,1

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#806]
### Is your feature request related to a problem? Please describe.

Similar to the ProtoFlux scale fix the same would be for inspectors as well for consistency reasons

### Describe the solution you'd like

I would like the inspector to be 1,1,1 scale relative to the user scale and have the inspector content inherit the slot scale

### Describe alternatives you've considered

None really unless you want to have a mod to have a custom inspector

**Comment by art0007i** [comment]
ideally I'd say the inspector should utilize the UnitScale canvas property to scale the object to 1,1,1. this way the canvas size represents how large the inspector should be in meters, which makes it easier to think about than canvas units
![image of how I'd change the inspector](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/ee65ce5e-628c-4ddc-bc2e-85bb6ac29e77)
