### ISSUE TITLE
The ability to select individual UIX elements

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#807]
### Is your feature request related to a problem? Please describe.

When inspecting to see how a thing works it can be quite tedious going through the UiX hierarchy to find the thing you want. 

like for example how does the volume slider on the default video player work? 
Being able to select the volume slider and open the inspector on it directly makes it way way easier to navigate and figure out how a thing works especially for debugging

### Describe the solution you'd like

I want the ability to use my dev tool to select UiX elements and be able to open them in the inspector panel additionally I would like the translate gizmo and scale gizmo to scale their respective fields on the rec transform component

This example image describes what I want
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/141cb9fd-1fad-43fd-9aa8-0338da6a4451)

### Describe alternatives you've considered

Using this Mod https://github.com/Banane9/ResoniteBoundedUIX

**Comment by VirgilCore** [comment]
See #599

**Comment by epicEaston197** [comment]
Should this issue be closed? or should it remain so we can have discussion about this particular feature?

**Comment by VirgilCore** [comment]
It's already planned.
