### ISSUE TITLE
Adding Animation Option/Update the StaticAnimationProvider.

### ISSUE THREAD

**Issue by RedStarHunter** [Yellow-Dog-Man/Resonite-Issues#811]
### Is your feature request related to a problem? Please describe.

The problem i run into with keeping track of all the animations i have to go through when importing in resonite and all of the animation being placed into a single slot with no names referencing What they were.

### Describe the solution you'd like

What i would like to see, would be the following:
1. When exporting to Resonite in the advance option add a Place animation into a Dedicated Slot with a subslot holding the individual Animations providers.

### Describe alternatives you've considered

2. Update the Static Animation provider to have a extra field for a String field that would have the Name of the animations exported.
\=StaticAnimationProvider
-Persistent
-Update Order
-Enabled:
-String: "Name" of animation
-URL:

**Comment by Zyzyl** [comment]
Highly related to https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/465 if not a duplicate

**Comment by shiftyscales** [comment]
Yes, this seems to cover the same underlying issue- animations being difficult to identify following their import into Resonite. Closing this as a duplicate and merging it into #465, thanks.
