### ISSUE TITLE
expose information of migrated account creation date

### ISSUE THREAD

**Issue by jligeza** [Yellow-Dog-Man/Resonite-Issues#822]
### Is your feature request related to a problem? Please describe.

Resonite respects migrated account bread day, which is cool, as some users (like myself) might use it for celebration of this special day. The bread with candle badge is visible, but the date is not accessible anywhere; it is a shame, because it would be nice to read it with some tools/toys to remind yourself when it is. It also shows how "old" a user is, which is nice to know.

### Describe the solution you'd like

Expose migrated account creation date in `CloudUserInfo` component, next to `RegistrationDate` property.

### Describe alternatives you've considered

It could be added to another component or protoflux node.

### Additional Context

Whatever you do, **please don't** override original bread day with resonite account creation date, because almost everybody who migrated has the same account creation date, which isn't special at all.

**Comment by Frooxius** [comment]
This has been exposed in 2023.12.11.1259, thanks!
