### ISSUE TITLE
Migration Did not import saved video`s

### ISSUE THREAD

**Issue by win189** [Yellow-Dog-Man/Resonite-Issues#824]
### Describe the bug?

i was going threw some of my old videos from neos and it is still showing Neosdb as the source and was wondering if that is normal 

### To Reproduce

check video`s that u had on neos

### Expected behavior

shouldnt it be hosted resdb

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/24577138/20304870-c75a-4f3a-aca5-0b78a4535a16)

### Resonite Version Number

Beta 2023.11.25.49

### What Platforms does this occur on?

Windows

### What headset if any do you use?

why dose it mater

### Log Files

none needed not a log related item

**Comment by win189** [comment]
shouldnt it be showing Res Db and not Neos db

**Comment by RileyGuy** [comment]
> If you change it to resdb it should work
> 
> The URLs don't always get automatically changed

URLs with incompatible schemas should be internally interpreted as resdb, so I don't know if this will actually help if the file doesn't exist on the resonite servers.

**Comment by win189** [comment]
> Log files are still important and should be included, even if you don't believe they are relevant, @win189. In this case, it would show the attempted (and failed) attempt at gathering/loading the video asset- and also gives more context for actions surrounding it.
> 
> Please attach a log file demonstrating the issue of failing to load these videos.
> 
> As others have suggested- can you try to alter the URL to point towards the proper asset server and see if the asset exists?
> 
> Are these assets that you had in your inventory, or a world? Where are they being loaded from?
> 
> Can you please also include the asset URL to one of these videos you are unable to load?

we aren't saying we can't upload video we are stating that after having migrated which we wont have logs for server-side items like this it is still showing Neosdb rather then resdb
