### ISSUE TITLE
Resonite should not capture cursor on every startup.

### ISSUE THREAD

**Issue by Psychpsyo** [Yellow-Dog-Man/Resonite-Issues#831]
### Is your feature request related to a problem? Please describe.

I'm always frustrated when starting Resonite in desktop mode because it locks my cursor in the center of my screen even if it is fully behind other windows.

### Describe the solution you'd like

Resonite should only capture my cursor when I explicitly click into it.

### Describe alternatives you've considered

1. Not doing this (annoying)
2. Making Resonite force itself to be the top window (also annoying)

**Comment by ProbablePrime** [comment]
Closing as duplicate
