### ISSUE TITLE
GPU instancing is not working as expected

### ISSUE THREAD

**Issue by Zyzyl** [Yellow-Dog-Man/Resonite-Issues#837]
### Describe the bug?

I have tried using RenderDoc (v1.29) and NVIDIA Nsight Graphics (2023.4.0) to profile frame rendering performance in Resonite in screen mode. In doing so, I noticed that all of the draw events logged were DrawIndexed() without any DrawIndexedInstanced() calls.

I'm concerned that one of the following may be the case:
- I have misunderstood the criteria for and mechanics of GPU instancing.
- I have misunderstood the meaning of DrawIndexed() vs. DrawIndexedInstanced() events being recorded.
- There is some incompatibility between the rendering performed in Resonite and the profiler programs I've tried.
- GPU instancing may not be ocurring as it should in Resonite.

I made this issue since, whatever the problem ends up being, it will be useful to have this checked and/or explained futher.

### To Reproduce

RenderDoc is available from https://renderdoc.org/
NVIDIA Nsight Graphics is available from https://developer.nvidia.com/nsight-graphics

I tested by opening up this very simple world resrec:///U-Zyzyl/R-b3fe0fc6-10ae-460d-be62-fee4487c7f36
I moved such that the set of objects were roughly centered in view as shown in the screenshot and performed a frame capture using either of the two softwares.
![Screenshot 2023-12-03 123351](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/66165438/270a35f0-8c57-4054-977b-61df36ade5e7)

### Expected behavior

There were ~100 objects in view where the MeshRenderer components referenced exactly the same StaticMesh and PBS_Metallic components. I expect that, when many visible MeshRenderer components reference exactly the same StaticMesh and compatible material (such as PBS_Metallic), some or all of those objects will be drawn using GPU instancing.

Additionally, I checked an almost identical scene in a different platform which uses an older version of the FrooxEngine and I did see DrawIndexedInstanced() calls where I'd expect them in both profiler programs. I assume that GPU instancing is indicated by DrawIndexedInstanced() calls being recorded based on using profiling tools in comparable software.

### Resonite Version Number

2023.11.28.1365

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Tested only in Desktop mode

### Log Files

Note: log file is from a session where I was _not_ using any frame profiling software.
[DESKTOP-SIS8AVA - 2023.11.28.1365 - 2023-12-03 12_45_11.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13538804/DESKTOP-SIS8AVA.-.2023.11.28.1365.-.2023-12-03.12_45_11.log)

### Reporters

Zyzyl (zyzylian in Discord)

**Comment by Zyzyl** [comment]
Edited the title to reflect that Geenz confirmed that GPU instancing wasn't working correctly due to some Unity-related factors. Listen to his office hours session from 2024-05-25 starting at ~43:00 for details https://officehours.probableprime.co.uk/episodes/geenz-2024-05-25/

It was also stated there that the problem _may_ be fixed with the completion of https://github.com/Yellow-Dog-Man/Resonite-Issues/milestone/1?closed=1 which needs to be tested.

**Comment by shiftyscales** [comment]
Shader Update 1 has shipped in the latest update- are you able to confirm / retest this issue to see if it is still a problem then, @Zyzyl?

**Comment by Zyzyl** [comment]
I just tested the reproduction world with both profiler programs and I see all the spheres being drawn using an DrawIndexedInstanced() call. As far as I understand, that indicates this is fixed!

I'll close this now and will re-open if I notice problems in other contexts.
