### ISSUE TITLE
No audio when using steam link for Quest 2

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#840]
### Describe the bug?

When I'm using steam link I do not hear audio from the "speakers (steam streaming speakers)" audio driver putting on my headphones and switching the audio driver to my headphones does not fix the issue

this is only for Resonite by the way I've played other VR games without issue

### To Reproduce

Use a Quest 2 or higher then download the steamlink app from the Oculus store and open Resonite you will notice that you can't hear the music in the local home

### Expected behavior

the "speakers (steam streaming speakers)" audio driver should output game audio

### Resonite Version Number

2023.11.28.1365

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest 2

### Log Files

[DESKTOP-DAN95E7 - 2023.11.28.1365 - 2023-12-03 10_40_59.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13539617/DESKTOP-DAN95E7.-.2023.11.28.1365.-.2023-12-03.10_40_59.log)

### Additional Context

It is possible that this is not a Resonite issue but a steam VR issue with the steam link app but I've tried every VR app I own and it works perfectly so I'm assuming this is a Resonite issue

### Reporters

@epicEaston197

**Comment by shadowpanther** [comment]
Okay then. In Resonite, select default (first in list) device both for output and input.

**Comment by shadowpanther** [comment]
Still, make sure that all four "Steam" audio devices do exist and are enabled. My guess is it needs all four to properly route the audio in software.

**Comment by Nytra** [comment]
I tried it and it worked for me, so this is probably an issue with your specific setup

**Comment by epicEaston197** [comment]
??????????????

I have no idea what's going on then all four audio drivers do exist but I can't see it they are enabled having Windows 10 instructions would help greatly. Also if all of them are not enabled then why can I hear audio from my desktop and other VR games?

**Comment by epicEaston197** [comment]
okay from what i can see they're enabled
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/7c6d6720-406d-4cd2-b111-f464b1d167da)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/eb802391-0516-4034-bb4e-bbcb1d5058ed)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/ae18f671-2945-4bec-8f85-66392185fffc)

**Comment by epicEaston197** [comment]
Nope...

**Comment by shadowpanther** [comment]
Works just fine for me with default devices selected for both input and output in Resonite.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/3d72b890-5051-4b72-9607-6b4caac1b5ad)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/675104/b93c096f-d846-4235-9a38-027e5eb4965f)

**Comment by epicEaston197** [comment]
Yeah I tested it out still no dice

**Comment by Zyro1331** [comment]
Hi! I fixed this issue myself, it's something not with Resonite but instead just an issue with Steam's Virtual Audio device drivers it installs. These Instructions are formatted for Windows 11, but are pretty similar for Windows 10 as well.

I'd recommend creating a [system restore point](https://support.microsoft.com/en-us/windows/create-a-system-restore-point-77e02e2a-3298-c869-9974-ef5658ea3be9) before doing this as you will be messing with device drivers. 

You'll want to grab the Steam Link Audio Drivers to manually install, which are available at this [GitHub repository](https://github.com/FCGWolfe/SteamLinkAudioDrivers)
Just click the green "Code" button at the top right and download and extract the zip file.

Make sure Steam is completely closed during this whole process.

1. Start by opening **Settings**, go to **System** -> **Sound** and scroll down until you see **More sound settings**. 
2. You'll see a small white window titled "Sounds" revealing all the sound devices on your computer, scroll until you find **"Steam Streaming Speakers"**, then right-click it and click **Disable** first, then right-click it again and select **Properties**. 
3. Another window will appear, then you'll see a category called **Controller Information** with the information "Steam Streaming Speakers" and "Valve Corporation Audio DDK". To the right of those details will be another **Properties** button, select that and then *another* window will appear, then click the button near the bottom of the window that says "Change settings" with a shield icon on it. 
4. You'll see the window reopen and then you can head to the **Driver** tab, then click the **Uninstall Device** button. 
A small confirmation window will appear, **please make sure the "Attempt to remove the driver for this device" checkbox is unchecked**, if this option is enabled Windows might try to completely uninstall Steam as well. 
5. Once you've made sure of that, then proceed to click the **Uninstall** button.

Repeat steps 2 through 5 for the *Steam Streaming Microphone* device as well.

Now you have completed uninstalling all the Steam Link audio drivers, it's time to manually install them again. 
Make sure you've got the new Audio drivers from before downloaded and extracted. 

1. Go to the extracted folder for your Steam Link audio drivers.
2. You likely have an x64 system, so you'll need to go through the folders like so;
`SteamLinkAudioDrivers\Steam VAC\drivers\Windows10\x64`
3. Right click the `SteamStreamingSpeakers.inf` and `SteamStreamingMicrophone.inf` and click **Install**. 
You'll just have to follow Windows during this installation procedure. 
5. Open the **Start menu** and search for "Device Manager"
6. Near the top of the window, click the **Action** tab then click **Add legacy hardware**
7. Select *"Install the hardware that I manually select from a list (Advanced)"* then click Next. 
8. Click on “Show All devices” and click Next. 
9. You'll see a Manufacturer list on the left side, scroll until you see *"Valve Corporation Audio DDK"* and then select it, and then under Model, click "Steam Streaming Speakers". Click Next/Finish until installation is done.

You may need to repeat step 6 through 9 to install your Microphone as well. 

And that's how I fixed the garbled/silent Audio that Steam Link had.

**Comment by epicEaston197** [comment]
okay the new settings menu has fixed my issue
