### ISSUE TITLE
Excessive lines in logging making log files annoying to read / unnecessarily big.

### ISSUE THREAD

**Issue by bredo228** [Yellow-Dog-Man/Resonite-Issues#843]
### Is your feature request related to a problem? Please describe.

Currently, when you try and view a log file there is an excessive amount of `Session updated, forcing status update` logged. This appears to vary in frequency - in some cases, I've seen this happening multiple times a second.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/4dc1e313-1a0f-4c3d-9dce-8ba9dbbec8f2)

This results in some rather large log files and unnecessary clutter when trying to find something in a log, for a message that might not have a use depending on what it is indicating.

For example, in a log file with 237,000 lines total the line `Session updated, forcing status update` is repeated 118,686 times.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/29470709/0ce8d5c0-6db0-423c-8f55-034424ffcf14)

### Describe the solution you'd like

Excessive logging of the same lines kept to a minimum, making log files easier to read, reducing the number of writes to the disk and using less disk space.

### Describe alternatives you've considered

No alternatives in this case, considering it is part of Resonite's logging.

**Comment by sveken** [comment]
I am noticing this on my headless servers too, I am noticing the log file grow by about 1MB per 1-3 minutes in some cases simply from "Session Updated" 

It would also be nice to not hammer the flash memory as much with as many useless lines.

**Comment by Frooxius** [comment]
I'm sorry, bit we need to keep this in for now, because there are some issues that happen sporadically with the session updates and we need this to diagnose.

**Comment by regalialong** [comment]
I don't mean to sound rude but why not move it to a toggle or a launch option? I initially thought this was a bug.

**Comment by ProbablePrime** [comment]
If it were a toggle, users would turn it off and then when they experienced the issues we're looking for than their log files would be useless.
