### ISSUE TITLE
Adding a form of signature to assets to verify authenticity

### ISSUE THREAD

**Issue by EmergencyTemporalShift** [Yellow-Dog-Man/Resonite-Issues#847]
### Is your feature request related to a problem? Please describe.

Being able to know an asset was created by a specific account could help people establish that a tool is legitimate, especially if it’s author doesn’t have a public folder.

### Describe the solution you'd like

Public key signing is a well known way to authorize authenticity of a file, I assume (perhaps improperly) that it should be straightforward to implement. (Notice that I’m not actually interested in encryption in this thread, that can be discussed somewhere else.)

### Describe alternatives you've considered

Pulling assets from a public folder would likely be safer, but not all creators necessarily have one to share.  

### Additional Context

I am not a security expert nor do I have any idea the difficulty/scope/utility of this. I do think that a discussion is warranted, given how freely things can move around the platform though.
Also, something being signed shouldn’t necessarily prevent it from being edited at all, I’m just imagining it could help grant piece of mind. Please discuss, though if you actually do know what you’re talking about and have security considerations about this, please follow the security policy.

**Comment by Frooxius** [comment]
I don't think this would really be a good solution to this and it would be over-engineering a problem.

Keep in mind that objects in-game can be composed from multiple files and you're not always pulling the original file, but can be pulling variants of it too.

If somebody doesn't go to the effort of publishing their work in the first place, so you can't get it from an official source (where you know it's authentic), why would they go to the effort to apply digital signatures to their work?

We do plan to introduce an easier way for people to publish their work via public workshop (similar how worlds are published). If somebody wants to publish their work and make it available to others, they can publish it that way as an official source.

**Comment by EmergencyTemporalShift** [comment]
Fair enough
