### ISSUE TITLE
NearestUserFoot node does not work at all.

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#859]
### Describe the bug?

I hope I'm not missing anything obvious but I could not get the nearest user foot node to output anything at all.

### To Reproduce

0. Make sure you are wearing an avatar which has feet
1. Spawn the NearestUserFoot node
2. Pull out any of the outputs, they will show that it has not found anything

### Expected behavior

The node finds the nearest user foot

### Resonite Version Number

2023.11.28.1365

### What Platforms does this occur on?

Windows

### Log Files

[ROTHORN - 2023.11.28.1365 - 2023-12-08 15_59_20.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13615723/ROTHORN.-.2023.11.28.1365.-.2023-12-08.15_59_20.log)

**Comment by Ardescar** [comment]
Same ^^ i was about to create a Issue too. And i also wondered if i missed something to make it work.

**Comment by mralext20** [comment]
Can someone check if this also happens with a tracked foot? (Vive trackers or otherwise)

**Comment by Frooxius** [comment]
Fixed in 2024.1.24.834, thanks!
