### ISSUE TITLE
IsNullOrRemoved node

### ISSUE THREAD

**Issue by art0007i** [Yellow-Dog-Man/Resonite-Issues#860]
### Is your feature request related to a problem? Please describe.

sometimes when storing references inside a Store variable I need to check whether that reference is valid, which currently this requires at least three nodes (IsNull, OR, IsRemoved) 
I think it would be convenient to have a node which handles both of these cases since at least for me this is a pretty common pattern.

### Describe the solution you'd like

A "Is Null Or Removed" node which checks whether something is null, or is removed

also potentially a "Is Not Null And Not Removed" node which is the same node but inverted

### Describe alternatives you've considered

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/0429effa-8fd1-4a79-b0c8-c69e075a06a1)

**Comment by Zyzyl** [comment]
Would it not make more sense for the IsNull check to return True in the case of a removed reference?

**Comment by Banane9** [comment]
> > Would it not make more sense for the IsNull check to return True in the case of a removed reference?
> 
> I personally don't think so. the object is there but it's a stale reference to something that's been removed from the world

I mean, the functional result is the same: you can't use the reference to do anything.

Making a combined node makes sense though.

**Comment by badhaloninja** [comment]
I could see having the IsNull check contain the IsRemoved check by default potentially causing issues or confusion down the line once more things are exposed to protoflux.

It also generally makes more sense to just have the combined check as a separate node

**Comment by Frooxius** [comment]
The IsNull node definitely should not return true if the element has been removed. In some cases, you might need to do some cleanup or something else with a removed object and this would make you unable to distinguish whether the object is removed, but you still have reference to it or it's actually been unassigned.

One alternative is to potentially have IsRemoved just return true if you give it a null as a default. That way you can just use this node for all use-cases. 

I'm not sure if this would cause too many issues though, as it would change the behavior a bit.

**Comment by Frooxius** [comment]
That's just naming really. I feel if we go for shorter name, it'd be something like "Exists"? IsValid feels a bit generic and you could have objects that are not removed, but are not valid for some reason. 

IsRemoved is sufficient, as that covers both destroyed and/or disposed.

**Comment by Nytra** [comment]
Actually I just realized that there is already a node called `ElementExists` which does this.

**Comment by art0007i** [comment]
well the node I requested is the opposite of the element exists node, but I actually didn't know that it does this. in that case I think keeping the current nodes and their behaviors is ok, we just need more awareness on what they all do

**Comment by Frooxius** [comment]
Oh I forgot about this node. You could potentially just use that one? We could add inversion as well potentially, but it feels a bit redundant.

**Comment by art0007i** [comment]
yeah, I can use that
