### ISSUE TITLE
Default camera skews and distorts image when in 3d mode

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#866]
### Describe the bug?

While taking a 3d photo with the default camera in Resonite Essentials, the preview image becomes distorted. The photos it produces in 3d mode look correct, but the preview is highly inaccurate.

### To Reproduce

- Spawn default camera from Resonite Essentials
- Use the mode select to switch the camera to 3d photo mode
- Tilt the camera

### Expected behavior

The preview should show an accurate view of what's in front of it, with no distortion.

### Screenshots

![Resonite_KLMSrTAIIT](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/7ad53f1f-2d22-4a39-ad9e-f41955004acc)

### Reporters

LuxKitty
code807

**Comment by RyuviTheViali** [comment]
This issue has been fixed - the camera available in the Resonite Essentials folder now renders stereo mode properly. Closing this, thanks!

**Comment by code807** [comment]
Upon further testing, it appears that all images captured using stereo mode are wider than they should be.
