### ISSUE TITLE
Add an option to save a photo as PNG

### ISSUE THREAD

**Issue by shadowpanther** [Yellow-Dog-Man/Resonite-Issues#870]
### Is your feature request related to a problem? Please describe.

Currently, there's only two options to save photos taken - as a "native" WEBP or as a "system" JPEG.
JPEG is lossy, so sometimes you wouldn't want it.
WEBP is not very compatible with various software, for example you can't drag-and-drop a WEBP onto a GitHub editing window, and have instead to open the photo in an editor, copy it to clipboard and paste, which converts it to PNG on GitHub side.

### Describe the solution you'd like

An option to save the photo taken as a PNG. Alternatively, a selector of format to save the photo in - WEBP, JPEG, PNG, etc. (formats could be added, provided Resonite knows how to encode that format).

### Describe alternatives you've considered

Wait for the photo to spawn in-world, export it as PNG. Time-consuming, extra steps for a simple conversion.

**Comment by Frooxius** [comment]
We could add more format settings once the settings UI is reworked, but not before then.

One thing to keep in mind though - PNG is significantly slower to encode than either JPG or WebP.

There's also one more thing to consider - on the InteractiveCamera component, you can select your encode format using the Format field. This already supports PNG.

**Comment by shadowpanther** [comment]
InteractiveCamera maybe has the setting (is it exposed on the default camera?), but finger camera doesn't have any settings at the moment.

**Comment by Frooxius** [comment]
I know, I was stating that as a potential workaround for the time being before this is implemented if you really need PNG.

**Comment by Banane9** [comment]
> One thing to keep in mind though - PNG is significantly slower to encode than either JPG or WebP.

Perhaps encode as WebP for ingame / asset system, while exporting as whatever the saving user's preferred format is? Would be sweet if it applied to any screenshot, whether taken yourself or saved using the Export as Screenshot context menu entry. And slower encoding would not be a factor then, as it only happens for the saving process that's in the background anyways.

**Comment by Frooxius** [comment]
@Banane9 That's what the system already does. Internally it's saved as WebP by default from the camera and then if you don't have "Keep original screenshot format" it converts it to JPG. We can add options there to what it gets converted to.

You still have to be somewhat vary of background processes, because there's a lot of other stuff that runs on background processing too, so the more/longer tasks you have, the slower will everything get overall.

**Comment by epicEaston197** [comment]
This issue is particularly annoying with my avatar if you attempt to take a no background picture of me my body is almost entirely invisible because the background is completely black
![2024-02-29 18 26 01](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/2248a2c2-179a-4ec6-a718-a590c0ced3d6)

**Comment by Frooxius** [comment]
This has been added in 2024.4.17.1420, thanks!

**Comment by shadowpanther** [comment]
@Frooxius even though the finger photo saving is set to PNG for me, desktop photos and camera photos are still saved as JPG.

Can't take finger photos to check whether those save as PNG.

**Comment by shiftyscales** [comment]
Hmm- I took a quick capture photo in desktop mode and it output in PNG as expected.

Do you have the "Keep original screenshot format" option enabled in the "Windows Settings" under "Misc", @shadowpanther?

I feel like the settings could probably be consolidated- but that should be raised as a separate issue. As far as I can tell from a quick glance there isn't a bug here, I suspect you likely have the aforementioned option disabled.

**Comment by shadowpanther** [comment]
> Do you have the "Keep original screenshot format" option enabled in the "Windows Settings" under "Misc", @shadowpanther?

No, it is disabled. Also, as far as I know, this option should keep the format as WEBP if enabled.

> As far as I can tell from a quick glance there isn't a bug here, I suspect you likely have the aforementioned option disabled.

If I have:
Keep original format == false
Encode format == PNG
I expect that photos would be saved as PNG, so in my opinion this is a bug.

What you are telling is - the Encode format option only takes effect when the Keep original format is on. In my understanting, Keep original format when turned on should ignore the Format setting and save as a native WEBP instead.

So, yes, the options should be consolidated, but the Keep original format should invert its effect.

Keep original format == true ==> disable Encode format, save as WEBP
Keep original format == false ==> enable Encode format, save as specified format

Alternatively, as Encode format also has a WEBP option, the Keep original format option should be deprecated as every possible combination could be achieved with Encode format option.

**Comment by Banane9** [comment]
> Alternatively, as **Encode format** also has a WEBP option, the **Keep original format** option should be deprecated as every possible combination could be achieved with **Encode format** option.

Yea, that's what I would say too - **Keep original format** has now been superseded by the **Encode format** option.

**Comment by shiftyscales** [comment]
> Keep original format option should be deprecated as every possible combination could be achieved with Encode format option.

That is what I meant when I said:
> I feel like the settings could probably be consolidated- but that should be raised as a separate issue.

@shadowpanther @Banane9

However, there is still value in having separate options, e.g. encode format/capture format, and export format.

Photos can be saved not just to the user's PC, but also the Resonite inventory. Likewise, as the description of the "Keep original screenshot format" alludes to- certain formats might not work as well in external programs.

Similarly- for on platform use, webp encodes **much** faster, which is beneficial for on-platform finger photo use, and getting to see the result of the photo much quicker.

So it is beneficial to have save- webp as the capture/encode format, and png/jpg as the export format for compatibility/space saving reasons.

The primary issue is just that there isn't a way to set the exported photo's encode format directly like you can with the initial capture encoding format.

**Comment by shadowpanther** [comment]
> However, there is still value in having separate options, e.g. encode format/capture format, and export format.

Okay, there should be a separate option for saving format for Inventory saving (as opposed to hard drive saving). That one would be a separate issue, I agree.

Currently, the way the combination of two options works is non-intuitive.

> Likewise, as the description of the "Keep original screenshot format" alludes to- certain formats might not work as well in external programs.

This description of the **Keep original format** says, and I quote: "**Enable** this to _avoid converting captured screenshots to JPG or PNG_ when saving them to the Documents folder in Windows". Sounds opposite to the way it works.

So, the current behaviour is indeed a bug.

**Comment by shiftyscales** [comment]
No...? I think you have the option backwards in your head, @shadowpanther.

If it's keeping the original format, it's keeping whatever format it was initially encoded on in Resonite. E.g. if the option is ON it keeps the original format, if the option is OFF it re-encodes it (in your case above- to jpg.)

It does exactly as the description says. It avoids converting them while the setting is ON. Meaning- it preserves whatever it was encoded in.

As the description says- you turn the setting on to avoid re-encoding, and keep the original format of the photo.

**Comment by shadowpanther** [comment]
> No...? I think you have the option backwards in your head, @shadowpanther.

Or maybe it's backwards in your head instead? Why are you being so overprotective? Or are you trying to gaslight me? Mean!

I'm reading the description of the option and how it is implemented is different from how it's described.

> If it's keeping the original format, it's keeping whatever format it was initially encoded on in Resonite. E.g. if the option is ON it keeps the original format, if the option is OFF it re-encodes it (in your case above- to jpg.)

Consider the original issue wording. I've asked for a way to select the hard drive saving format.

Before this implementation, there were two behaviours:
Keep original == false ==> save to inventory as WEBP, save to disk as JPG
Keep original == true ==> save to inventory as WEBP, save to disk as WEBP

So the inventory saving was not being affected at all.

What the new implementation should've been in my wording:
(option 1) ==> save to inventory as WEBP, save to disk as WEBP
(option 2) ==> save to inventory as WEBP, save to disk as JPG
(option 3) ==> save to inventory as WEBP, save to disk as PNG
… other formats.

What was implemented instead is the selector of in which format the photo is being saved to the inventory, which is not what I've asked for. It's nice to have, but it does not implement my request.

---

I think the proper way to have the best of both worlds would be to:
* deprecate the **Keep original format** option
* keep current **Encode format**, but make sure to point out in the name and description that this is the inventory saving format ("In-game encode format" or "Inventory encode format")
* add another selector of **Disk encode format** which would allow to select the file format separately from the first one

**Comment by shiftyscales** [comment]
> I've asked for a way to select the hard drive saving format.
Yes, and I said above, for the third time now, that this should be a separate issue. I am not gaslighting you, I'm not trying to be protective- I agree there is improvement that could be made, as I highlighted above in my initial response- but- that should be a separate issue.

I already also said all of what you just said above- I explained that there is use for having separate encoding formats on-platform, vs. exported to disk- hence, my above statement:

> The primary issue is just that there isn't a way to set the exported photo's encode format directly like you can with the initial capture encoding format.

We are saying the same things. Please take it to a new issue if you are looking for a setting to directly set/control the export encoding format, @shadowpanther.

**Comment by shadowpanther** [comment]
> Yes, and I said above, for the third time now, that this should be a separate issue.

The current issue is not implemented as requested, so it should be reopened. That's what I'm saying here. What you are saying is that it is implemented and works as requested, which is not true at all.

**Comment by shiftyscales** [comment]
Frooxius had implemented what you asked for:
> An option to save the photo taken as a PNG.

If you were looking for a setting to control the export encoding format directly, you should have been more specific in your request. For the last time, please make a separate issue.

In the meantime, if you set your encoding format to PNG, and keep the original screenshot format, you will have exported photos that are saved to your disk as PNG as I already tested and confirmed works above.
