### ISSUE TITLE
DDS files imported with custom mipmaps sometimes flip mipmaps vertically

### ISSUE THREAD

**Issue by Epimonster** [Yellow-Dog-Man/Resonite-Issues#877]
### Describe the bug?

When importing DDS files with custom mipmaps, sometimes mip levels will import vertically flipped.

### To Reproduce

- Import a custom mipmap (I've included my own as a test, feel free to use it)
- Enable the KeepOriginalMipMaps boolean on the texture inspector
- Move away from the image and observe it mips to a flipped image
- Increasing the mipmap bias makes this transition obvious closer to the source
- Feel free to use the one provided in my public folder

Source DDS File:
[Lava.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13642301/Lava.zip)

In game import:
resrec:///U-Gareth48/R-DAD57FA8D72A3EF29826B7E8CEDC3C5D1AD057AFB2B948BB2204994BBC729FDD

### Expected behavior

The mipmaps should maintain the same orientation as they were authored with and not be flipped vertically.

### Screenshots

Blue arrow provided to help with clarity

![2023-12-12 00 42 05](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/46454766-dbbb-44e8-a589-49ea8d4229a0)
![2023-12-12 00 44 55](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/5fa1c93b-b785-4387-9f70-3029e09692f0)

### Resonite Version Number

2023.12.11.1259

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-IKI1CHO - 2023.12.11.1259 - 2023-12-11 19_55_14.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13642385/DESKTOP-IKI1CHO.-.2023.12.11.1259.-.2023-12-11.19_55_14.log)

### Additional Context

Other textures occasionally would only have a single mip flipped (couldn't secure that example but it was from Oculus files), the one I provided was the most extreme example since all mips were flipped.

### Reporters

Gareth48
Cyro

**Comment by Frooxius** [comment]
When you say "sometimes", does this mean that some mip maps work correctly and are not flipped and work correctly? Would you be able to provide an example of such?

**Comment by Epimonster** [comment]
> When you say "sometimes", does this mean that some mip maps work correctly and are not flipped and work correctly? Would you be able to provide an example of such?

Chatted with Cyro about this and it turns out we were mistaken and the one we previously observed as correct was not.

I discovered something penitent to the bug however. The behaviour is much more consistent than I thought. The flip always happens on the mip level representing 64
[mip_test.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13643372/mip_test.zip)

![2023-12-12 03 42 55](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/bb393612-53e6-4dda-8ff5-d3c171b42a77)
![2023-12-12 03 42 46](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/6400902d-c763-41e0-a943-b60e812c5e87)

**Comment by eai04191** [comment]
Testing by me confirmed that it flips vertically when the mip you are viewing is 64x64 or smaller.

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/6889f122-e9c1-41c1-8267-812d380aea2a

<details>
<summary>Some additional information</summary>


![2023-12-12_23-18-47_nvtt_export](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/3516343/2c9bc7d4-5846-44f6-b7a6-237eafcfdd6e)

This texture contains 9 mips ranging from 256x256 to 1x1.

This texture is a dxt5 format DDS created by dxtex.exe that comes with the DirectX SDK.

[Texture1.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13649433/Texture1.zip)

</details>

**Comment by Frooxius** [comment]
This should be fixed in 2024.1.19.687!

Any already uploaded DDS files will need to have their variants cleared. If you collect their hashes/URL's and open an issue, we'll clear them.
