### ISSUE TITLE
Enabling "DirectLoad" on DDS files corrupts the image

### ISSUE THREAD

**Issue by Epimonster** [Yellow-Dog-Man/Resonite-Issues#878]
### Describe the bug?

Enabling the directload boolean causes visual artifacts to appear on the texture.

### To Reproduce

- Import a custom DDS file (the one that caused this issue I've included below)
- Enable DirectLoad in the texture settings

[Lava.zip](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13643440/Lava.zip)

### Expected behavior

The texture should not display visual artifacting.

### Screenshots

![2023-12-12 03 55 25](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/fd7bc8f2-b29d-495a-9486-451964ad6db4)
![2023-12-12 03 55 50](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/44652736/b919cabc-362a-4842-8e60-01243f7622a6)

### Resonite Version Number

2023.12.11.1259

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-IKI1CHO - 2023.12.11.1259 - 2023-12-11 23_02_46.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13643524/DESKTOP-IKI1CHO.-.2023.12.11.1259.-.2023-12-11.23_02_46.log)

### Additional Context

This isn't something I'd realistically ever want to do in most cases, I just discovered it by accident when I missed another checkbox. 

### Reporters

Gareth48
Cyro

**Comment by Epimonster** [comment]
As I've looked into this more, I've discovered that ticking direct load also tends to cause unity crashes sometimes, but not all the time. I've included a log from NezzKryptic that they got after they crashed.

[R2D4_-_2024.1.3.1265_-_2024-01-03_17_48_35.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13835787/R2D4_-_2024.1.3.1265_-_2024-01-03_17_48_35.log)

**Comment by Frooxius** [comment]
This has been fixed 2024.1.19.687, thanks for report!
