### ISSUE TITLE
Impulse based version of search nodes (searchSlotByTag, searchSlotByName)

### ISSUE THREAD

**Issue by ClimberJ** [Yellow-Dog-Man/Resonite-Issues#882]
### Is your feature request related to a problem? Please describe.

Searching large hiarchies continuously can lead to unnecessary decreases in prformance, but some projects require it.

### Describe the solution you'd like

My solution would be impulse based versions of these nodes. This would decrease unnecessary processing load. This would also allow for staged searching in common locations, instead of immediately seaching from, for instance, root.

### Describe alternatives you've considered

I can't think of any alternatives, as the issue is performance related.

### Additional Context

Some projects require searching from root, but only once or twice instead of continuously.

**Comment by Frooxius** [comment]
You can already use existing nodes this way - they only perform search when evaluated.

They will not search continuously on themselves, unless you plug them into something continuous, like a drive or display node - it's those nodes that will continuously evaluate them, causing the expensive searches.

If you want to use them with impulse - use them with an impulse. It's simple as that. E.g. you can perform some operation on impulse, that will use a value from this node to perform and then it's done. Or if you need to re-use the value, write it into a variable with an impulse.
