### ISSUE TITLE
ProtoFlux display node should stop evaluating its input when it is packed

### ISSUE THREAD

**Issue by Nytra** [Yellow-Dog-Man/Resonite-Issues#886]
### Is your feature request related to a problem? Please describe.

If you create a display node it will constantly evaluate its input similar to a continuous relay, which is fine. However if you pack the display node it doesn't seem to stop evaluating, which can cause performance issues. When the node is packed it isn't visible and isn't in use so it shouldn't keep updating.

### Describe the solution you'd like

A packed display node should not evaluate its input continuously.

### Describe alternatives you've considered

Remembering to delete all display nodes before packing ProtoFlux. This works for new creations, however for migrated creations from another platform there may be a lot of display nodes which would cause poor performance.

### Additional Context

N/a

**Comment by Frooxius** [comment]
This is something I wanted to implement at some point, it should help with some things taking more performance than they should. 

It's somewhat relevant to this: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/814 

But I think it's distinct enough - we want those nodes to stop updating even when active, just when they're packed.

**Comment by Frooxius** [comment]
This is done in 2024.1.3.393 thanks!
