### ISSUE TITLE
Transparency doesn't work on the PBS Color Mask materials

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#887]
### Describe the bug?

Transparency just straight up does nothing on the PBS Color Mask materials. (Maybe ForceZWrite does nothing either?)

### To Reproduce

Try to use transparency on the color mask materials, You'd expect the alpha to do something but it doesn't do anything when in transparent mode.

### Expected behavior

For transparency to work on the material.

### Screenshots

![20231212174716_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82356528/abdbe3b2-acf1-43d3-981e-1851c5c3bd26)
As you can see, I have a 0 alpha 1 blue SolidColorTexture in the ColorMask on both materials, Transparency does nothing.

### Resonite Version Number

2023.12.11.1259

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-QBGCSAQ - 2023.12.11.1259 - 2023-12-12 17_42_57.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13654961/DESKTOP-QBGCSAQ.-.2023.12.11.1259.-.2023-12-12.17_42_57.log)

### Reporters

modernballoonie

**Comment by Geenz** [comment]
This is expected behavior.  We don't support transparency on these materials - that field is more an effect of all PBS materials inheriting that field.
