### ISSUE TITLE
Quick bug: missed shrinking some 4k textures on the default tools

### ISSUE THREAD

**Issue by shininghero** [Yellow-Dog-Man/Resonite-Issues#897]
### Describe the bug?

The light tool and the character collider setter tool have a few textures on their materials that are at 4k, while the rest are at 1k.  This takes up extra VRAM, and also large quantities of space on avatars baking the default tools for quick access.

### To Reproduce

For the light tool:

- open the metallic body material on Light Socket Tool Baked Lowpoly Base and check the occlusion map.

For the character collider setter tool:

- open the blue crystal texture on the front rings and spinning rings.

### Expected behavior

The tools don't have leftover 4k textures.

### Screenshots

![20231213222635_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/17071843/ddb43388-6e21-4776-8602-a641d5a3cc2f)

### Additional Context

I was able to fix it on my end pretty quickly by using the "longest side" option to essentially wipe the 2k and 4k variants from the offending materials.  Saved 15MB of space from both tools.

### Reporters

Shininghero (both platforms)

**Comment by shininghero** [comment]
On further checking, the crystal material for the character collider tool is duplicated.  The main body has a mat with the expected 1k textures, but the rings have a different one with the errant 4k texture.  Copying the material reference fixes it too.

**Comment by AegisTheWolf** [comment]
Added updated 1k downscaled textures on tools to tools folder, multi-tool, and cloud home. Closing issue
