### ISSUE TITLE
Website Feedback Devlog 12/13/2023

### ISSUE THREAD

**Issue by TehTurk** [Yellow-Dog-Man/Resonite-Issues#898]
### Describe the bug?

I really enjoyed the presentations and concepts they had a really organic feel to it, and positively presents the platform. I just had a few issues if that's the full direction going forward ( I saw request for feedback so hello 👋🏻 ), or if I could at least input, and welcome others to chime in on what's the best way to go about it for featuring creators on the website.

I like the concept of having handpicked creators to feature on the website, but from experience I feel like it'd cause some issues? (Who gets picked over others, people being catty, etc etc) 

Would it be more easier to recommend a Creator/Creation of the Month based on metrics of some sort and avoiding repeat creators? Or alternatively, allowed folks to make a creator profile of some sort, link to their creations, and then have them linked if folks see their creations featured on a blog post or page. (Because one hand, are you making a yellow-book for creators, or are you trying to ease the access or knowledge of these notable creators by doing this. Featuring em is one thing, having them be constantly at reach is also another)

There's also other aspects, where when you set specific areas of interest for folks that are highlight on a page as such, it also limits what focus may focus on creating within the community too. (Gadgets, Live Perf, Avatar Makers etc)

I'm ok with us highlight notable, or noteworthy creators as you noted being hands on with creators being represented but I'm also wary of it becoming too echo chambery with how things develop over time, because there are issues with constant spotlights vs momentary spotlights and people slot-ing themselves heavily in a slice to get recognized as well.

### To Reproduce

N/A

### Expected behavior

N/A

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/26357446/7f46bbe2-744f-4efc-a31e-5c9e4c2a5d56)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/26357446/79903071-3c4f-4710-b795-42e8860e0c77)

**Comment by ChromaShiba** [comment]
Totally agree on being careful about how we approach additions to this page, my current thought process is that this will be an open call to the community to submit themselves (pending content standards review) to this page. I like the idea of a "Creator Account", though the implementation of that at this moment is a little further off in my knowledge (something I'll bring up though). 

Have some more thoughts, but will post when I get more of a chance.
