### ISSUE TITLE
ShadowRampMask on XiexeToon is non-functional

### ISSUE THREAD

**Issue by StarfishHidari** [Yellow-Dog-Man/Resonite-Issues#90]
### Describe the bug?

The ShadowRampMask field on XiexeToon does not work, and has not worked since XiexeToon was originally implemented as far as I could find.

This was originally reported back in 2021 here; https://github.com/Neos-Metaverse/NeosPublic/issues/2091

### To Reproduce

- Create a new XiexeToon material
- Put any texture into the ShadowRampMask field
- You will notice this has no effect on the shadowramp when a light is shone on the surface

### Expected behavior

When using a ShadowRampMask, it should mask where the shadow ramp affects. 

### Screenshots

In this screenshot you can see that both of these spheres have identical material setups, except one has a texture in the ShadowRampMask field, but the shadows are the same on both meshes.
![shadow machine is out of service](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/11951324/446fd21f-d443-495c-86bd-e282b5f39447)

### Resonite Version Number

Beta 2023.10.13.743

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Valve Index

### Log Files

[DESKTOP-MU428FM - 2023.10.13.743 - 2023-10-13 19_36_57.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/12900594/DESKTOP-MU428FM.-.2023.10.13.743.-.2023-10-13.19_36_57.log)

### Additional Context

This also has no effect on shadow rims either, though I am unsure if it is intended to affect shadow rims or not.

### Reporters

Hidi

**Comment by SupersonicNK** [comment]
Actually, it works as intended. It's just not self-explanatory.
ShadowRampMask actually determines the Y coordinate the shadows sample from the ShadowRamp texture- try putting a separate gradient on the top and bottom halves of the ramp. The darker the color is, the lower on the texture it samples.
See this image: (Note that the ramp texture is clamped vertically, otherwise the White part of the ramp would sample from the top of the texture again.)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/63344191/2e56834e-d25f-416c-a966-83f3047294bb)

**Comment by StarfishHidari** [comment]
> Actually, it works as intended (by the shader's creator). It's just not self-explanatory. ShadowRampMask actually determines the Y coordinate the shadows sample from the ShadowRamp texture- try putting a separate gradient on the top and bottom halves of the ramp. The darker the color is, the lower on the texture it samples. See this image: (Note that the ramp texture is clamped vertically, otherwise the White part of the ramp would sample from the top of the texture again.) ![image](https://user-images.githubusercontent.com/63344191/275091080-2e56834e-d25f-416c-a966-83f3047294bb.png)

Ahh, thank you for the info! I hadn't been able to find any information on this in the past so this helps a lot. Hopefully a wiki will be up soon so this can be documented somewhere more accessible ^^

**Comment by The-furf-of-July** [comment]
Is the mask based on the lighting, or the UV map of the mesh?

I might be getting confused by the term "lower" here, due to the rotation of the textures.

**Comment by SupersonicNK** [comment]
> Is the mask based on the lighting, or the UV map of the mesh?
> 
> I might be getting confused by the term "lower" here, due to the rotation of the textures.

The mask is based on UVs. The ShadowRampMask picks which row of pixels to use for shading from the ShadowRamp texture on the given UV. 
The closer the mask's color at that UV is to black, the **lower** the row on the ShadowRamp texture.

The sphere has an unfortunate rotation in the image I provided, so it looks like the mask is flipped horizontally (evidently, that confused me too as I said the white part of the mask would "sample from the top again" if not clamped, when it would have wrapped back to the _bottom_). That's my bad.
