### ISSUE TITLE
Error when accessing World URL's

### ISSUE THREAD

**Issue by SlyTheFloof** [Yellow-Dog-Man/Resonite-Issues#902]
### Describe the bug?

When clicking on world URL (Specifically https://go.resonite.com/record/U-1Ov31BF65Fg/R-e3e6b196-5084-4870-98ee-dfe85dcc2d98) 
it gives a SSL cert like error and then once proceeded it gives 403 (the server understands the request but can't provide additional access)

### To Reproduce

Just click on any world URL and you should get a error 

### Expected behavior

World Links to work

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/dfb0e8c3-a08b-4acc-86e0-92cbf95657de)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/1967a222-0b8d-4037-81fd-32567930a3dd)

### Resonite Version Number

Beta 2023.12.13.87

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

logs to big for github
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/56106431/16100030-02bd-4774-b4ad-7ae1953bd628)

### Reporters

SlyTheFloof

**Comment by eai04191** [comment]
Perhaps it's the same problem as #160?
