### ISSUE TITLE
Please Rename DataModelBooleanToggle back to Boolean Latch in the Node Browser

### ISSUE THREAD

**Issue by GreaterKiba** [Yellow-Dog-Man/Resonite-Issues#908]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/128842498/0249116a-00e8-4ef0-863a-cea84d5a89a3)
Transitioning from Neos into Resonite, a lot of language in the 'visual node coding' world of the platforms seem to be getting confused due to the renaming of a lot of essential nodes. There are a few nodes that have already had some of their names changed that I can tolerate, but I feel this rename doesn't work, especially since it wasn't hard to find this node on the previous platform.

I am open to changing and correcting the wording of these nodes that might be more 'code' or 'programmer' accurate, but I can't seem to wrap my head around this one. It feels like it's a work-in-progress name and feels unintuitive.

Boolean Latch being renamed "DataModelBooleanToggle" probably makes sense in its actual function . . . if it also reflected that in the node that it spawned. It's still called "Boolean Latch" when you spawn it probably because "DataModelBooleanToggle" is too long. If that's the case why even change it? 

These are all Assumptions at the moment, but trying to understand why this decision was made so I'm as educated on the subject as possible is ideal. There are essentially two names for the same thing and it's confusing when trying to memorize what the node does and its purpose. 

I've heard rumors that the protoflux node browser will be updated soon, so I want to make sure this issue is made aware to the developers for when that time comes.

### Describe the solution you'd like

There are two ways I could see this working for easy readability and memorization of the node.

1. Rename DataModelBooleanToggle back to Boolean Latch **(Prefered)**
or
2. Rename Boolean Latch on the node to DataModelBooleanToggle

### Describe alternatives you've considered

Memorizing that DataModelBooleanToggle is Boolean Latch(?)

And in turn, remember that DataModelBooleanToggle is Boolean Latch(?)

**Comment by Frooxius** [comment]
As stated in our submission guidelines, we cannot use materials from previous works, if you want to make a suggestion, it has to stand on its own: https://github.com/Yellow-Dog-Man/Resonite-Issues

Furthermore, regardless of other instances, specifying the boolean is stored in the data model is important part of name of this node in context of ProtoFlux and how it functions and integrates into FrooxEngine and it follows naming convention of other "DataModel" nodes, such as "DataModelStore", therefore we will not remove that part of the name.

We'll likely add more types, such as LocalBooleanToggle and StoreBooleanToggle variants as well, which will make the name distinction even more important.
