### ISSUE TITLE
Additional Status Option ("please poke / message" status?)

### ISSUE THREAD

**Issue by Cometstreak** [Yellow-Dog-Man/Resonite-Issues#909]
### Is your feature request related to a problem? Please describe.

I struggle letting others know that I want to be joined or messaged. having to directly contact people that I am open leaves me feeling shy and nervous, especially not wanting to become a bother.

### Describe the solution you'd like

A new status color (maybe blue?) to represent open to friends poking to join.

### Describe alternatives you've considered

Alternatives might include
Messaging everyone on friends list until they respond
asking people to join on discord
Having a status like discord where you can type it out.

### Additional Context

I would assume something like this would be an addition after the finished UI update.

**Comment by Frooxius** [comment]
This is something I've actually been pondering about for a bit - a sort of "please do bother me, I'm up for hanging out / talking" kind of status. 

I'd definitely like to add something like this, but there's a bunch ways this could be approached. I think the status itself would be a good start, but I do wonder how do we handle visibility with that.

There's a few things we could do:
- Sort people with this status even above online users, so they pop up
- Whenever someone switches to this status, we make notification appear to users (we'll make these configurable too once we have better settings, alongside with the "online")
- Perhaps a dedicated "friends looking to hang out" facet?

There's other stuff with status as well - like setting a custom one, setting mood (creative, socializing, tired...) and so on, that could be part of this as well - there's a few things to consider how exactly would this function and combine with these other things.

Any thoughts on how would status like this function? Or what would you like from it? Or what could be problematic with it? (e.g. people spamming it or something like that)

**Comment by Azavit** [comment]
I was thinking "wouldn't that just be custom status?" but Froox really makes some good points.
This really should be it's own status as well as the possibility of custom statuses of any of the main options including this one. (though I'm guessing that should be it's own issue)

I do like the idea of it showing up above "Online" as that gives it a purpose beyond custom statuses. but at least allowing users to not order their friends lists like this if they choose would probably be a good idea as everyone likes to have their lists ordered differently hence #41 being an issue.

A notification may be a bit much however, If I'm not looking to hang out my self getting a notice that someone else wants to would be annoying (though if it was only for those also with that same status then that may be helpful)

dedicated "friends looking to hang out" facet feels a bit too "out of the way" most people will be checking their contacts lists to see who is on to hang out with anyways so having it be there is best.

**Comment by TehTurk** [comment]
At that point it's also whether you'd like the status to reflect a user's online state, or type of social engagement akin to actually how VRC operates currently. [Blue (Auto Accept), Green(Request but Visibile), Orange (Request no Visibility, Red (Nothing)] but that has also had it's fair criticisms in the past. I bring this up as a learning/jumping off point to consider from.

I do think a status you could set would genuinely go a long way, but I'd suggest more caution on adding socially directed features without a more solid overall gameplan (custom statuses outside of a simple string) . When you start overlapping them, it does kind of instigate mental gymnastics with some folks who are more paranoid with those type of setups.

There's also other aspects where the concept of a blue autojoin (from experience) can override the host's ability to limit users or who may or may not join a session if hidden or private if I can speak from experience too.

**Comment by Frooxius** [comment]
Yeah, I mentioned in my original post, these would be toggle-able. Keep in mind that currently "Online" status is also indicated with a notification already and frequent changes are filtered too, so this isn't that far from here to get a separate "xyz is looking to hang out" kind of notification.

That way it also works from both ends - if you don't care about people reaching out and you're in private, you turn off your notifications or set yourself to busy and you won't get anything.

------------------------

The separate facet could still work I think if it's something that's small and that is on your home screen on dash for example. You'd still see it in the Contacts. And if you don't want it there, you toss it. It's just additional option for users who want to see friends who want to hang out quicker.

------------------------

The other part would be the custom status. I think this should be something that's on top of all statuses, so it's actually independent of this, but can be combined for better effect. E.g. you set your status to "please poke/invite me" and then custom status to "I want to hang out" or "I'd like to build something".

Or you set your status to "Busy" and your custom one to "Working on my project" or "Watching a movie" if you want to to provide more context. Let's separate this out of this thread and focus on the "Please poke/invite me" status.

------------------------

For the VRC statuses, we don't have plans to make those work/mean the same things as there necessarily, I don't think it should be goal to copy their model, since our system already seems to be different, so I'd rather focus at the actual features and how it would integrate to Resonite itself.

**Comment by TehTurk** [comment]
I realize that and don't insinuate that in the slightest for VRC status. Just saying it's something to gleam knowledge and understanding from as in the past our menus have overwhelmed folks with the amount of options and people have had expectations due to their conventions as well.

**Comment by Frooxius** [comment]
I don't really use VRC myself, so for me it's helpful to put these things more in context of Resonite.

**Comment by Frooxius** [comment]
I've started on this, but there's one issue: How to name this status? 

So far the best I got is either "Sociable" and "Available". Could potentially be "Engage Me" so it's a bit more clear too.

**Comment by hazre** [comment]
Available sounds good to, as someone else suggested it on twitter. And it sounds professional too.

Default still should be Online.

In terms of colors, I think blue should be good. Kinda like VRChat I suppose.

Green - Online 
Blue - Available 
Yellow - Away
Red - DND
No color - Invisible

**Comment by Banane9** [comment]
Some ideas:

* Chatty
* Up to Chat
* Looking for Fun
* Join Me!

I like Sociable, but Available seems fine too.

**Comment by Electronus** [comment]
Honestly Available is good. That ones got my vote.

**Comment by TisFoolish** [comment]
To me "Available" is synonymous with "Online" when viewed without the context of it being a "Chatty" status and i can see new users getting confused by that. If it's set to available i can see people having to explain there status to new users. 

I think Chatty works

**Comment by Frooxius** [comment]
> Chatty
> Up to Chat
> Looking for Fun

These are a bit too specific. It might not be necessarily looking to chat or be chatty, but also to hang out with people. It needs to be more generic.

> Join Me!
This is kinda the opposite - this status is for users who wanted to be messaged or invited by others. If people want someone to join them, they can just open up the session.

> Available 
This is a bit too similar to Online like mentioned before, and a bit too passive. I'm looking for something that is a bit stronger on "Please engage with me".

There's also a bit of a subtext used with dating apps and such for that, which I want to avoid.

**Comment by Electronus** [comment]
hmmm. 

Reach out? something like that?

**Comment by Banane9** [comment]
> but also to hang out with people.

Maybe just "Hang out with Me" then? or "Up to Hang Out" 🤔

**Comment by TrebleSketch** [comment]
Trying to keep this to as few words as possible while also convey intent while also being considerate of UI space and possible translations too xP

"Invite Me"
"Curious to Join"
"Looking for Worlds"
"Open Communications" - too long
"Socialising" - not clear on intent
"Open Invite" - doesn't feel clear, especially for newbies

**Comment by Banane9** [comment]
Maybe [Gregarious](https://www.thesaurus.com/browse/gregarious) although that's not super common - but it does mean sociable / up for contacts. "Kontakfreudig" in German, literally "happy for contact".

**Comment by Nytra** [comment]
I like "Interact with me" or "Engage me"

**Comment by SlyTheFloof** [comment]
or have a field where you can just type what your feeling

**Comment by SpaceGaytor** [comment]
You could call it "Resonate"

When someone wants to hangout with others on Resonite, they'd want to Resonate with them????

Since being social, active, creative is something people on Resonite, Resonates with ^-^

**Comment by TrebleSketch** [comment]
> or have a field where you can just type what your feeling

I think a Status feature is coming in the future, so it would be separate.

**Comment by RustybotPrime** [comment]
For what it's worth we had "Ping Me!" in Anyland which worked well though I understand that not everyone might make the connection that pinging means inviting (it was actually _called_ pinging in Anyland).

**Comment by Frooxius** [comment]
Thank you everyone! I kept it as "Sociable", since that seems most clear out of them and there's not really one where I'd feel like would be "it".

The new status is now available in 2024.5.31.37!

**Comment by GearBell** [comment]
It would be wise to have the pinging turned off by default - New users will not know about this and will be bothered by it until someone mentions it to them that you can turn it off.

**Comment by hazre** [comment]
Honestly I don't see any problem with this new status. The sound thing though, that should not be enabled by default, especially because it would be really annoying for people with 100+ contacts.

That's my only nitpick about it.

**Comment by shiftyscales** [comment]
There is a request to add a discrete notification sound for the sociable status notifications here, @GearBell @hazre: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2177

Likewise, there is a separate request to allow the notification type to be granularly configured to disable either (or neither) of the notification toast/sound based on the users setting. https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/2189

Those tweaks should resolve a lot of the issue I've seen reported about this feature.

**Comment by GearBell** [comment]
oh, mine wasnt about the sound, it was about the whole popup.

**Comment by shiftyscales** [comment]
That is also covered under that same issue @GearBell. The request submitted is to allow users to disable the popup, or the sound similar to other notifications.
