### ISSUE TITLE
Unity to Resonite converter

### ISSUE THREAD

**Issue by ModernBalloonie** [Yellow-Dog-Man/Resonite-Issues#916]
### Is your feature request related to a problem? Please describe.

This usually is a problem with porting worlds from Unity to Resonite, It could be long and painful, or you use a converter.

### Describe the solution you'd like

A Unity to Resonite converter. It would convert all the lights, the colliders and the positions of all the objects. Material work would still have to be done in-game, but that's okay. Just to get a bulk of a unity scene in to make life easier.

### Describe alternatives you've considered

Using a converter for another platform, and then migrating it over.

**Comment by gameboycjp** [comment]
#6?

**Comment by ModernBalloonie** [comment]
> #6?

Oh, crap i didn't see. Oops.

Great to know though!

**Comment by Banane9** [comment]
You could close this issue if it's a duplicate of that one
