### ISSUE TITLE
Floating Point String Parsers crash when changed to HexNumber while being evaluated

### ISSUE THREAD

**Issue by Zandario** [Yellow-Dog-Man/Resonite-Issues#922]
### Describe the bug?

When using the `Parse_Double` and `Parse_Float` node (any single floating point ftr), it'll crash if you change the `NumberStyle` to `HexNumber`.

### To Reproduce

1. Create a `Parse_Float`.
2. Pull out **any output**.
3. Proceed to pull out the `NumberStyle` and flip it to `HexNumber`.

### Expected behavior

For floating point singles to not crash when switching to `HexNumber` on their parsers.

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/5cd54f10-d260-4029-84d2-d92f5cd25efb

### Resonite Version Number

2023.12.15.22

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Quest Pro

### Log Files

[HAUSVONZAN2 - 2023.12.15.22 - 2023-12-17 12_18_16.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13697678/HAUSVONZAN2.-.2023.12.15.22.-.2023-12-17.12_18_16.log)
[HAUSVONZAN2 - 2023.12.15.22 - 2023-12-17 12_15_22.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13697679/HAUSVONZAN2.-.2023.12.15.22.-.2023-12-17.12_15_22.log)

### Additional Context

The crash only happens when you change it while there is an active output. If you remove all outputs, change it, THEN pull out an output, it's fine.

### Reporters

@Zandario @Ukilop

**Comment by Frooxius** [comment]
Fixed this in 2023.12.21.109 thanks! I didn't find anything that would make it matter when it's being evaluated, from the description it shouldn't really matter much, it probably just influenced where did the exception go?

Regardless it should be fixed.
