### ISSUE TITLE
Constant Value driver

### ISSUE THREAD

**Issue by BaxterOttoman** [Yellow-Dog-Man/Resonite-Issues#925]
### Is your feature request related to a problem? Please describe.

The Smooth Value/Smooth Transform drivers do a good job for allowing a value to approach a target, but they move by fractions. A component that allows a value to approach a target by a given constant amount would be a welcome companion to those components.

### Describe the solution you'd like

I would like to see Constant Value/Constant Transform driver components that you can use to drive a field towards a target as there is with the Smooth components, where the speed value determines the magnitude of change per second.

### Describe alternatives you've considered

This task can be accomplished with Flux, but since the smooth version of the drivers exist, I feel it's worthwhile to suggest single component solutions as well.

**Comment by Frooxius** [comment]
There are ValueConstantLerp nodes. To clarify, are you asking for a component version of these?

**Comment by BaxterOttoman** [comment]
Yes, I think a component version that can be used like the smooth value and smooth transform driver components would be very useful.

**Comment by Frooxius** [comment]
Ok thanks! Those are simple enough to add.

**Comment by Frooxius** [comment]
Added ConstantLerpValue<T> in 2023.12.21.109, thanks!
