### ISSUE TITLE
Invalid discord link on the website

### ISSUE THREAD

**Issue by Chundelac** [Yellow-Dog-Man/Resonite-Issues#931]
### Describe the bug?

When trying to access discord thru the website https://resonite.com/ the link will report as `Invite invalid`
The current link leads to https://discord.com/invite/Jm4nsEGq
Working link for the resonite discord is https://discord.gg/resonite

### To Reproduce

Open https://resonite.com/  
Open Socials category in the navigation  
Click on the Discord link

Tested on desktop and phone

### Expected behavior

Discord invite should work for accessing resonite discord, most likely using the https://discord.gg/resonite link

### Resonite Version Number

Not applicable

### What Platforms does this occur on?

Windows

### Log Files

Not applicable

### Reporters

Chundelac

**Comment by Chundelac** [comment]
Note: this is not related to Resonite client, but the website. I did not find more appropriate form to report this so I used this template.

**Comment by ProbablePrime** [comment]
@ChromaShiba you can fix this.

use discord.gg/resonite

**Comment by ChromaShiba** [comment]
This has been fixed! Thanks for the report @Chundelac !
