### ISSUE TITLE
Option to unclamp Lerp

### ISSUE THREAD

**Issue by BaxterOttoman** [Yellow-Dog-Man/Resonite-Issues#934]
### Is your feature request related to a problem? Please describe.

I would like to suggest adding an option to Value Lerp to allow it to perform unclamp the t input to allow for values outside the 0 to 1 range.

### Describe the solution you'd like

Add a boolean argument to the Value Lerp flux node to allow extrapolation of values.

### Describe alternatives you've considered

I can write my own Lerp that isn't clamped, but it would be useful to toggle the behavior on the existing Value Lerp Flux node

**Comment by Frooxius** [comment]
We will not add this as boolean (that's not a good idea for such simple operation - it requires conditional testing on every single evaluation), but instead expose the LerpUnclamped functions to ProtoFlux. 

We have those internally. If you want unclamped version, you'll just use that version of the node.

**Comment by BaxterOttoman** [comment]
That'd be fine too!

**Comment by Banane9** [comment]
You could also use Remap to do this, as it acts like an unclamped lerp with the right inputs (i.e. `1` for the max input and your regular lerp values for the output min and max)

**Comment by Frooxius** [comment]
Added unclamped versions in 2023.12.21.109, thanks!
