### ISSUE TITLE
Anchor locomotion data doesn't work

### ISSUE THREAD

**Issue by epicEaston197** [Yellow-Dog-Man/Resonite-Issues#938]
### Describe the bug?

Anchor locomotion data doesn't output anything with WASD clicking primary etcetera heard it doesn't work for VR either
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/7ff2bf0c-ad72-4ed4-b1c4-9abf50daefc4)

### To Reproduce

1: Get an anchor

2: input it into anchor locomotion data

3: observe all outputs and you will see that nothing happens

### Expected behavior

1: For desktop mode it should output a zero to 1 depending on if you're hitting W or S for strafing it should do multiple directions for VR it should act in a similar fashion

2: the primary press bull should become true when primary is pressed same goes for secondary

3: "has primary" and "has secondary" should appear as true when the player has primary and secondary available

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/76523692/46c212af-8445-418c-8bd3-a49d2d3911e9)

### Resonite Version Number

2023.12.15.22

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-DAN95E7 - 2023.12.15.22 - 2023-12-19 16_32_33.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13720562/DESKTOP-DAN95E7.-.2023.12.15.22.-.2023-12-19.16_32_33.log)

### Reporters

@epicEaston197

**Comment by art0007i** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/19620451/da48fc28-a349-4738-ad40-381dee59ce53)
those values are actually only present within the context of the OnLocomotionUpdate impulse. you have to write it or use it from that pulse

**Comment by ProbablePrime** [comment]
@art0007i is correct, that's how you use the node.

Thank you for making this issue but we'll be closing
