### ISSUE TITLE
[Presskit] Presskit issues

### ISSUE THREAD

**Issue by Zandario** [Yellow-Dog-Man/Resonite-Issues#939]
### Describe the issue

The Presskit is filled with duplicate and strange outliers that rub me as if they were overlooked/forgotten (it happens to the best of us)

e.g. here's all the identical duplicates
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/a6277872-9ccb-4677-8ef0-6ba8e52fc356)

This looks like it wasn't intended to be there
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/412c3c28-c583-4728-b52d-213fa3734c36)

Really should just be called Recycle, it doesn't need to be 1:1 to delegate/function names
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/c4df1ba1-d93b-4931-8ecd-b77e951cdf24)

Already addressed the duplicate duplicate (hah), though I'd say the icons with the border should have a modifer, i.e `ContextDuplicate` or at least `BoxedDuplicate` (could be work-shopped)
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/eb698aa0-6ac4-4498-9c89-6f2e886b7155)

The boxed version is named `Add` but this is `GreenPlus`?
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/f42b7fb6-bdf1-42d0-9725-bf1e402f550b) ![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/5afcdfe7-6f26-42ef-b648-b6c64630b55f)

Should just be Menu?
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/8f6ebad4-bf3a-45a6-b1a5-64a867961f7a)

Tophat
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/a6c767d6-9504-42d9-a5e6-c26e1e6bebda)

This is the only world icon that's plural
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/acaca108-ca95-4fae-86c3-30bbf709ca2f)

<details>
<summary>Original content</summary>

~A good chunk of the UI icons are named after what they're used for, instead of what they are. This may seem like a pointless criticism, but this generally discourages using certain icons outside of a very-specific use-case. It also increases duplicate items which you can already see with loop and skip back (forgot the specific name)~

~Instead I suggest icons should be named on either what they look like.~

~Examples:~

~1. Moderator -> Shield~
~2. Chainlink-> Link~
~3. Settings -> Gear~

</details>

### Additional Context

I've had way too many issues looking for specific icons as this is the only non-semantic icon library I've used

### Reporters

@Zandario

**Comment by Banane9** [comment]
not too familiar with other icon sets, but would it make sense to include both in the name? at least for unfamiliar people that would seem useful: e.g. someone who doesn't know that the moderator icon is a shield wants to find that.

**Comment by Zandario** [comment]
> not too familiar with other icon sets, but would it make sense to include both in the name? at least for unfamiliar people that would seem useful: e.g. someone who doesn't know that the moderator icon is a shield wants to find that.

Here's a couple icon sets used all over

Google
https://fonts.google.com/icons

Microsoft
https://github.com/microsoft/fluentui-system-icons/blob/main/icons_regular.md

Apple
https://developer.apple.com/sf-symbols/
https://github.com/brendanballon/sfsymbols-svg/tree/master/symbols

**Comment by Zandario** [comment]
Rewrote the issue body (the original content is there still), pretty much just talking about the weirdness I see in the kit

**Comment by Banane9** [comment]
Looking at the icon sets you linked, they all seem to have mixed use of stating exactly what something shows and stating what it's used for. E.g. Microsoft's "alarm" icons, which are really bells with different bits around them. Or Google's "neurology" icon, which is a brain. While more general purpose icons like arrows are usually just named something like "arrow <direction>".

To apply this to your (old) example: the moderator icon is not just any shield that can be used for other things, it's specifically the icon of moderators and should only be used for moderation related things.

**Comment by Zandario** [comment]
> Looking at the icon sets you linked, they all seem to have mixed use of stating exactly what something shows and stating what it's used for. E.g. Microsoft's "alarm" icons, which are really bells with different bits around them. Or Google's "neurology" icon, which is a brain. While more general purpose icons like arrows are usually just named something like "arrow ".

This is why I redacted what I said in that regard


> To apply this to your (old) example: the moderator icon is not just any shield that can be used for other things, it's specifically the icon of moderators and should only be used for moderation related things.

tbf the moderator one was a bad example. I wrote the original examples when I didn't have them on hand (there's no download link rn)
