### ISSUE TITLE
Cannot change username capitalization with /changeUsername

### ISSUE THREAD

**Issue by DanteTucker** [Yellow-Dog-Man/Resonite-Issues#944]
### Describe the bug?

The /changeUsername command currently does not allow you to change your name to a differently capitalized version of your current name. eg. Changing from Dante to dante. This results in an error that the name is already in use.

### To Reproduce

Attempt to change your name to a differently capitalized version of itself.

### Expected behavior

The name should be changed.

### Resonite Version Number

Beta 2023.12.15.22

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Log Files

N/A

### Reporters

Dante and shadowjonathan

**Comment by ShadowJonathan** [comment]
I got hit by this, where my previous username was `j0j0`, and I tried to make it `J0J0`

I got suggested to change it to another username, and change a week back, and i'll see if it works.

**Comment by ShadowJonathan** [comment]
It doesn't work, it keeps telling me the name is too similar.

I'd like to have a pretty short username, possibly JoJo or J0J0, but I don't know what part of the system is trying to prevent such a name :(

**Comment by ShadowJonathan** [comment]
@shiftyscales i've basically done a longer version of that chain, but even then i dont understand why the four-letter area around my original name seems to congested;

(`j0j0` -> `ShadowJonathan` -X-> `J0J0`)

**Comment by Frooxius** [comment]
This has been fixed in 2024.1.19.687, you should now be able to change capitalization directly! Thanks for report!

**Comment by ShadowJonathan** [comment]
I wasn't sure if I could change my username back (considering I already switched "away" from that username), but I just did this today, and it worked, thanks a lot! :D
