### ISSUE TITLE
PDF is not imported from URL.

### ISSUE THREAD

**Issue by rassi0429** [Yellow-Dog-Man/Resonite-Issues#948]
### Describe the bug?

If paste the pdf URL with Ctrl+V, the PDF will not load.

### To Reproduce

[For example this Oracle pdf link](https://docs.oracle.com/cd/E19641-01/802-1948/802-1948.pdf) 
`https://docs.oracle.com/cd/E19641-01/802-1948/802-1948.pdf`

when paste with Ctrl+V, nothing happens

### Expected behavior

The pasted PDF URL should be displayed in a PDF viewer.

### Resonite Version Number

2023.12.21.109

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[DESKTOP-UPS4R4A - 2023.12.21.109 - 2023-12-21 11_19_00.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13734394/DESKTOP-UPS4R4A.-.2023.12.21.109.-.2023-12-21.11_19_00.log)

(There is a log around line 1007)

### Additional Context

It works fine when I put the external URL in the StaticDocument component, so it's probably a clipboard issue.

### Reporters

kokoa0429

**Comment by Frooxius** [comment]
Fixed in 2023.12.21.339, thanks!
