### ISSUE TITLE
Official PDF viewer UI

### ISSUE THREAD

**Issue by Frooxius** [Yellow-Dog-Man/Resonite-Issues#949]
### Is your feature request related to a problem? Please describe.

Recent build has introduced support for rendering PDF files. The default UI is very barebones and is only meant to serve as a fallback.

### Describe the solution you'd like

We need to build an official UI for this in-game and set it up. This UI would not only have proper visual polish, but also offer additional functionality, such as:
- Automatically size itself based on the currently displayed page
- Show optional list of thumbnails for pages for easier navigation
- Selection for quality (this affects the rendering resolution)
- Ability to pop-out the current page - essentially spawn another instance at the current page
- Ability to zoom in to a region of the page
- More(?)

Here's a rough sketch of a possible layout, but it doesn't need to follow this:
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/8838625/ff23f2fc-d4f5-4100-b46f-fd46666a1b3c)

### Describe alternatives you've considered

N/A

**Comment by TisFoolish** [comment]
Can rendering resolution be local? I might want to see a page at double the default resolution, but that doesn't mean everyone else in the session should also have to regenerate the image as well

**Comment by Frooxius** [comment]
@RyuviTheViali @AegisTheWolf  What's the status on this?

**Comment by RyuviTheViali** [comment]
The UI panel is nearly complete, I'm finishing up some tweaks to the zooming feature and then it will be ready.

**Comment by TisFoolish** [comment]
Something I forgot to mention was zooming via hover with laser, although now it's a bit late to mention it.

**Comment by MkEE-Konecny** [comment]
Mentioned this in features discussion, will mention it here as well - it would be very nice to have graceful (auto render target resolution) handling of large sheet formats of source documents. It is not unheard of to be using ISO A0+ sizes for mechanical engineering production drawings, having to manually tweak it every time after import is tedious.

**Comment by Frooxius** [comment]
@RyuviTheViali @AegisTheWolf What is the status on this? We should really finish this one up, so we have a proper PDF viewer.

**Comment by RyuviTheViali** [comment]
The document viewer is ready to publish, however it was discovered there is an issue with rendering the panel for some users, which has prompted me to create an issue for this ( https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/1374 ).

**Comment by RyuviTheViali** [comment]
The new default PDF viewer panel has been released. Closing, thanks!
