### ISSUE TITLE
Protoflux text representation

### ISSUE THREAD

**Issue by Narazaka** [Yellow-Dog-Man/Resonite-Issues#952]
### Is your feature request related to a problem? Please describe.

Protoflux is a node programming language that can only be operated with a GUI, but it has the following disadvantages over (most) programming languages that have textual representation.

- It takes a lot of time for programming, whether in VR or desktop mode
  - This is due to the fact that the keyboard, which is hardware specialized for this purpose, has an absolute advantage in inputting a variety of information, and no matter how proficient one becomes at GUI input, it is difficult to overturn this with current technology.
- It takes time to read and decipher because it is not searchable
- Cannot use good off-the-shelf version control tools

ProtofluxはGUIでのみ操作可能なノードプログラミング言語ですが、テキスト表現がある（大半の）プログラミング言語に対して以下のようなデメリットがあると思います。

- VRにしてもデスクトップモードにしても、プログラミングのために時間がかかります
  - これは多様な情報を入力することにおいてそれに特化したハードウェアであるキーボードが絶対有利であることに起因し、GUI入力にいくら習熟したとしても現在の技術では覆しがたいと思います。
- 検索不可能なために読み解くのに時間がかかります
- 既製の優れたバージョン管理ツールが使えません

### Describe the solution you'd like

I think we need a textual representation of Protoflux.
If the textual representation of the Protoflux node-based program itself is difficult, another programming language such as Prototext, which is compiled into the same assembly, could be used.
Prototext can be managed in git, etc., and can be edited in Visual Studio Code and other good code editors, so that it can be linked inside and outside of Resonite.

Protofluxのテキスト表現が必要だと思います。
Protofluxのノードベースプログラムそれ自体のテキスト表現が難しければ、同じアセンブリにコンパイルされるPrototextなどの別のプログラミング言語等でもよいと思います。
Prototextがgit等で管理でき、またVisual Studio Codeを初めとした優れたコードエディタで編集できるなどResonite内外を連携できるようにすることでその価値は増すと思います。

### Describe alternatives you've considered

For example, if it is most important that Protoflux be somewhat understandable to everyone, including users with no programming experience, then the textual representation of Protoflux may be a disadvantage  (In terms of convenience of collaboration, I don't see much difference, considering the existence of Live Share, etc.).
For me, the major complaints about Protoflux are that it takes a long time to program and that it is not version-controlled, but the former is more important.
Since Resonite is not afraid to create something that is not bound by the existing UX, it may be possible to solve this problem by developing an input method that allows faster node programming, etc.

たとえばプログラミングの経験の無いユーザーも含めて誰にでもProtofluxがある程度理解しやすいことが最も重要である場合は、Protofluxのテキスト表現はデメリットになる可能性があります（なお共同作業の利便という面ではLive Shareなどの存在を考慮して大差ないと感じます）。
私にとってProtofluxの大きな不満は「プログラミングに時間がかかること」と「バージョン管理できないこと」ですが、より重要なのは前者です。
Resoniteは既存のUXに囚われないものを作り出すことに躊躇が無いため、より高速にノードプログラミングできる入力方式を開発する等でもこの問題は解消可能かも知れません。

**Comment by JackTheFoxOtter** [comment]
I don't think translating ProtoFlux nodes 1:1 to text would be a good idea, it probably wouldn't look like traditional programming languages you are used to. That said, it doesn't have to be a 1:1 mapping.

#573 Suggests WebAssembly support, which I think would offer a good alternative to ProtoFlux's visual nodes.

I disagree with the development time argument however. I would say once you get fluent enough with it, there isn't much of a difference in regards to how fast you can create a program. The bottleneck in programming (at least for me) is rarely ever typing speed, it's more like, designing and refining the algorithms, troubleshooting and testing. And that's not really made more difficult by the visual format.

**Comment by Frooxius** [comment]
ProtoFlux is specifically designed to be a visual node based programming language. As such, we don't have plans for a text based representation for it officially.

One planned feature is ability to compile ProtoFlux setup into a static binary asset, which can then be loaded. This could be a compilation target for third party tools in the future: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/962

For text-based programming, we haven't decided on a specific solution yet, but we're most likely going to use WebAssembly for this purpose. This will allow wide variety of text-based languages to be compiled and used with Resonite.

**Comment by Narazaka** [comment]
I was very irritated with Protoflux about the development time.
I also think wasm is a good alternative.
