### ISSUE TITLE
[Website] Horizontal scrolling bug

### ISSUE THREAD

**Issue by Chundelac** [Yellow-Dog-Man/Resonite-Issues#959]
### Describe the bug?

Currently the main website and all pages that use the same layout are very slightly horizontally scrollable, also showing the horizontal scrolling bar on the bottom of a browser.

### To Reproduce

Open the website https://resonite.com/ in a browser, horizontal scrolling is possible. If not try browser mentioned in Additional Context.

### Expected behavior

Unless there is content in the website that would benefit from horizontal scrollability the website should not be horizontally scrollable.

### Resonite Version Number

Not applicable

### What Platforms does this occur on?

Windows

### Log Files

Not applicable

### Additional Context

Tested on:
Chrome on Windows (Version 120.0.6099.109)
Chrome on Android (Version 120.0.6099.115)
Firefox on Windows (Version 120.0.1)

### Reporters

Chundelac

**Comment by Chundelac** [comment]
### Suggested code changes:
_These are just an example of a working fix for me, they should not be used directly without further verification as I did not do testing outside the platforms mentioned in original issue post_

Changing the css file `resonite-website-a2201f.webflow.css` to remove unnecessary margins that cause horizontal scrolling.
`.body` - remove `margin-right: 3px;`
`.background-video` - change `margin: 75px -5px 0;` to `margin: 75px 0 0;`
`.flex-block-8` - remove `margin-left: -5px;` and `margin-right: -5px;`
`.testimonial-column-dark` - remove `margin-left: -5px;` and `margin-right: -5px;`
`.footer-dark-3` - remove `margin-left: -5px;` and `margin-right: -5px;`
`.pricing-overview` - remove `margin: -1px -5px;`

Here are the same changes visualized in chrome changes tab:
![changes](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/11510682/fc0558ec-8842-480f-9525-d5b82d1023ac)

The whole edited css file can be provided if requested, I just cannot upload it here directly as it is not a supported file type.

### These changes fix the horizontal scrolling on following pages:
index.html
features.html
case-studies.html

### This does not fix the page case-studies/live-production.html
On this page the horizontal scrolling is caused by the image carrousels right arrow as `.gallery-slider-right` has `right: -50px` as an addition to the previously mentioned margins.
![live-production](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/11510682/a903a0f0-f422-4ef7-b013-56f12f9bc7e3)

**Comment by ChromaShiba** [comment]
I'm fairly certain about what would be causing this issue, will look into it with the next website update.
