### ISSUE TITLE
No "Set Document Viewer" button in inventory

### ISSUE THREAD

**Issue by JayKubJK** [Yellow-Dog-Man/Resonite-Issues#960]
### Describe the bug?

With the new addition of the Document/PDF Viewer came the DocumentInterface component. In the patch notes, it says that this component can be used like the other Interface components to have a custom interface for various things. The issue with this component in particular is that trying to set a custom document viewer like any custom interface doesn't work. I disabled the "IsInterface" boolean like usual with these things and saved it to my inventory to set it to my custom one, but I didn't see such button pop up.

### To Reproduce

1. Have an object with the DocumentInterface component in it and disable the "IsInstance" boolean
(Alternatively, you can use this: resrec:///U-JayKub/R-39d4050a-4e26-40e2-9b15-b1353053116e)
2. Save the item to your inventory
3. Click once on the saved item in your inventory

### Expected behavior

I expected there to be a button with text something along the lines of "Set Document Viewer" within the array of buttons on the top.

### Screenshots

![20231221055152_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/82873987/0dc20f3e-b559-4867-8a82-60dc5f09ebd9)

### Resonite Version Number

Beta 2023.12.21.339

### What Platforms does this occur on?

Windows, Linux, Android / Quest

### Log Files

N/A

### Reporters

JayKubJK
LuxKitty

**Comment by Frooxius** [comment]
Ooops, fixed in 2023.12.21.1127, thanks!
