### ISSUE TITLE
Local Home does not show when local database is cleared.

### ISSUE THREAD

**Issue by Charizmare** [Yellow-Dog-Man/Resonite-Issues#971]
### Describe the bug?

When clearing my local database to free up some space on my pc, I noticed that when I relogged to cache my avatar and my cloud home I no longer start Resonite in my local home.

### To Reproduce

To reproduce:

1. Locate C:\Users\(YOURUSERHERE)\AppData\LocalLow\Yellow Dog Man Studios\Resonite\Assets

2. Delete every file in there.

3. Start Resonite. The first world you spawn in from now on is your cloud home.

### Expected behavior

When starting up Resonite after clearing the local database it is expected for the files to be redownloaded along with the ui and other core visuals.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/73861779/89d270bd-6152-4a2f-af07-5de887fc2b98)
This photo show that the only world that I am in is my cloud home. My local home is nowhere to be seen.

### Resonite Version Number

Beta 2023.12.21.1127

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Desktop

### Log Files

[CHORMATIC-ABERR - 2023.12.21.1127 - 2023-12-22 05_13_19.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13751430/CHORMATIC-ABERR.-.2023.12.21.1127.-.2023-12-22.05_13_19.log)

### Reporters

charizmare

**Comment by XDelta** [comment]
Normal startup should load you into your cloud home and the local home. Additionally the local home won't show on the 'My worlds' tab, it will however show on the 'Everything' tab along with the active sessions tab while it is focused. Did you used to use `-DoNotAutoLoadHome` as a launch option by chance? that will make the cloud home not open automatically.

**Comment by XDelta** [comment]
Also while on desktop, you can use Ctrl+Tab to flip between all your open sessions/worlds

**Comment by Charizmare** [comment]
@XDelta I made sure that I'm not using the launch option that you specified and I'm not.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/73861779/95e820fc-a79e-499a-a911-8d60339dcefa)

I also tried pressing Ctrl + Tab and nothing happens.

Going to the 'Everything' tab doesn't show my local home either.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/73861779/88b91917-a01f-4d4a-9bb9-f185d78a6f01)

**Comment by XDelta** [comment]
Ah hm, now checking your log, it mentioned it failed for some reason. Not sure what could cause that and it doesn't look like there is much detail about why.
```
5:13:46 AM.765 (  0 FPS)	Loading a Machine Home World, failed. State: OK with error: 
5:13:46 AM.765 (  0 FPS)	Halting creation of default Machine Home World
```

**Comment by Frooxius** [comment]
You can't just delete the files in that path, without clearing all the others in the folder above - this is not supported. 

What you have essentially done is corrupt the database, by removing a lot of its files but not all. So it's trying to load  files that should be there, but are now missing, resulting in the behavior.

You'll need to clear all the files there to fix this.

There's not really anything on our end to do for this that I can see.
