### ISSUE TITLE
UsersAssetLoadProgress Not listing all users in session but appears to briefly cause the AssetLoadState to match FullyLoaded when a user compares against themself.

### ISSUE THREAD

**Issue by XDelta** [Yellow-Dog-Man/Resonite-Issues#976]
### Describe the bug?

Trying to narrow down what specifically is occurring but it appears that 2 things seem to be occurring. One is not all users in the session are showing in the `UsersAssetLoadProgress` component (Myself and Arito are in the session), When the user isn't showing in the list for the host the fire on true seems to pulse once when changing to 'FullyLoaded' on the enum despite being 'unloaded' (as far as the host can tell?). Packing and unpacking the protoflux appears to re evaluate the list? (everyone is on it after doing so).

Seems likely that the host and other users may have mismatched lists where the other user has themself on the list and returns their local value because of the fire on true but the host doesn't have them on the list for some reason.

### To Reproduce

resrec:///U-Delta/R-1E38FBB4E5FBAE654EDC6845312ABEA8107E88761673CB4F432A9D43AEE4BF96

### Expected behavior

ProgressInfo list to show all users and return the correct LoadState for users

### Screenshots

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/833f37ff-e920-4900-9e58-1912799eb02e

https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/f6a9d3cb-ec09-4e18-8507-e2531fe486f5

### Resonite Version Number

2023.12.21.1127

### What Platforms does this occur on?

All

### Additional Context

The intended usage in this case is for each user in a world to locally see a placeholder image then switch to the fully loaded asset when it is done.

### Reporters

_deltawolf

**Comment by Frooxius** [comment]
I've reworked how this works in 2024.6.5.198, which should be a lot more accurate. Thanks!

**Comment by XDelta** [comment]
Will need to do some more extensive testing but atleast some of the more visual effects from this still seem to occur. Will add additional details when I have the chance to do more testing. Might another separate issue but related.

**Comment by XDelta** [comment]
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/7883807/7304a30a-1748-4757-9ef7-320ad0ceffa9)
For some users, the list of users appears to have nulls, additionally noticed that this list may otherwise become out of sync with some users seeing everyone and some seeing a subset of users missing one or two.

**Comment by XDelta** [comment]
Adding that this was still observed as an issue in `Beta 2024.6.25.1149`

**Comment by shiftyscales** [comment]
Re-opening- it seems there might still be some issues here, @Frooxius.

**Comment by Frooxius** [comment]
Can we get a new report on this please with reproduction steps and such? 

This is actually a different issue from the original - it's a problem with the new implementation.
