### ISSUE TITLE
Send a Destroying event when destroying slots via the Inspector

### ISSUE THREAD

**Issue by Zyzyl** [Yellow-Dog-Man/Resonite-Issues#978]
### Is your feature request related to a problem? Please describe.

One particular usecase for the OnDestroying node is to script emergency cleanup behaviour in objects or systems. This can help to make systems more robust against ending up in unintended states. Currently the "destroy" and "destroy preserving assets" buttons in the inspector do not appear to send a destroying event, meaning that there are common cases where Slots are destroyed which cannot be caught by the OnDestroying node.

### Describe the solution you'd like

The "destroy" and "destroy preserving assets" buttons would trigger a destroying event in the hierarchy to be destroyed.

### Describe alternatives you've considered

Adding a note in documentation for tools/systems that using the "destroy" and "destroy preserving assets" buttons in the inspector may cause unintended behaviour.

OnDestroy may be a viable alternative in some cases, however it's not reliable when one needs to use references or variables which are stored on the hierarchy which is being destroyed.

### Additional Context

In my specific use case, I have a system which creates objects which can be assigned to one or more groups. Objects and groups are represented by separate Slot hierarchies and the relationships encoded in variables which reference each other. 

One object may be in multiple groups and will contain references to each. Similarly, one group may contain references to multiple objects. Ideally, when an object is destroyed, I would cleanup all references to it within all the relevant groups (and vice-versa when a group is destroyed). Currently I can use the OnDestroying node to catch certain situations where objects/groups are destroyed (e.g. via ProtoFlux or context menu) but not via the Inspector.

**Comment by Frooxius** [comment]
The "Destroy preserving assets" button should already send the event. Is this not the case in your testing?

The "Destroy" one doesn't send events by design, because it is a raw destruction, that bypasses the typical destruction process. This is specifically when you need the events skipped and everything just nuked, so for that button not receiving the event is expected.

**Comment by Zyzyl** [comment]
Ok, thanks for explaining the intended behaviour Froox! I must have made a mistake when testing because the "Destroy preserving assets" does seem to trigger OnDestroying. I'll close this since it sound like the system is working as intended.
