### ISSUE TITLE
DocumentPageTexture Does Not Update Resolution When PageRegion Is Updated

### ISSUE THREAD

**Issue by RyuviTheViali** [Yellow-Dog-Man/Resonite-Issues#982]
### Describe the bug?

Using the new DocumentPageTexture component for viewing PDFs, I've noticed that the returned resolution and subsequently the aspect ratio when using the texture in, say, a SpriteProvider always shows the original document's resolution (as set via the Size property in the DocumentPageTexture component). i.e. say I set the component's PageRegion rect to [0.5; 0; 0.5; 1] (only showing the right half of the document). The aspect ratio (and therefore returned resolution) does not change in this, or any other case involving the PageRegion rect.

### To Reproduce

- Import a PDF document
- Find the DocumentPageTexture component on the imported visual
- Set the PageRegion rect parameter to anything other than [0; 0; 1; 1]
- Notice the output resolution does not change, and subsequently the output aspect ratio also does not change

### Expected behavior

The output resolution of the DocumentPageTexture component should update according to the new size or aspect ratio of the texture based on the PageRegion parameter input.

### Screenshots

An example of a normal DocumentPageTexture with a rect of [0; 0; 1; 1] behaving normally.
![20231222234257_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/3f690886-5c45-4ec4-a09a-cd79cca74697)

An example of the same DocumentPageTexture with a rect of [0.5; 0; 0.5; 1] (just the right-half of the document) sharing the same width/height of the full document image, and a stretched/incorrect aspect ratio.
![20231222234315_1](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/15852289/8cb85aa6-180b-42dd-857b-657e17d4d69e)

### Resonite Version Number

Beta 2023.12.21.1127

### What Platforms does this occur on?

Windows

### What headset if any do you use?

Vive Pro Eye

### Log Files

[RYUVI-TOWER - 2023.12.21.1127 - 2023-12-22 23_53_08.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13758120/RYUVI-TOWER.-.2023.12.21.1127.-.2023-12-22.23_53_08.log)

### Reporters

Ryuvi (Discord: ryuvi)

**Comment by Frooxius** [comment]
Fixed in 2024.1.3.393 thank you!
