### ISSUE TITLE
Pixel Art imported images compressed by default, smaller images get distorted

### ISSUE THREAD

**Issue by code807** [Yellow-Dog-Man/Resonite-Issues#986]
### Describe the bug?

When importing pixel art images using the Pixel Art import option, the resulting textures are compressed by default. This leads to noticeable color distortion, and requires manual manipulation to make pixel art images look correct.

### To Reproduce

Import a low resolution image using the pixel art import option. I have tested for this issue with sizes up to 200x200.

### Expected behavior

Imported pixel art should look the same in-game as it does elsewhere, without missing/altered colors or a modified resolution.

### Screenshots

![Resonite_JW2zzBPHbX](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/18963a54-facb-4c2c-a3ef-bbfe541ea061)
![Resonite_7ZKViQLc4n](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/10662276/d3064ea9-faa0-4eed-9a55-be8f65ee8772)

### Resonite Version Number

Beta 2023.12.21.1127

### What Platforms does this occur on?

Windows

### Log Files

[DESKTOP-1E2V3A8 - 2023.12.21.1127 - 2023-12-23 00_35_53.log](https://github.com/Yellow-Dog-Man/Resonite-Issues/files/13758777/DESKTOP-1E2V3A8.-.2023.12.21.1127.-.2023-12-23.00_35_53.log)

### Reporters

code807

**Comment by LeCloutPanda** [comment]
I wanna bump this as of 1/2/2024 basically the start of MMC I need uncompressed pixel art so having an option like "Pixel art(Uncompressed)" or just make the default one not compress the art would be a life saver as I make iterations to my pixel art and needing to bring it in and manually uncompressing it through an inspector it adds a lot of down time.

**Comment by VirgilCore** [comment]
I dont understand why it should be compressing it in the first place.
The whole point of having a pixel art import is for it to show the raw pixels as they were.

**Comment by Frooxius** [comment]
@LeCloutPanda You can turn the compression off after importing.

As a general rule, we don't recommend just "bumping" issues (see https://github.com/Yellow-Dog-Man/Resonite-Issues/blob/main/HOW_WE_PRIORITIZE.md ). I'm a bit hesitant to prioritize this on the grounds of MMC, since we'd be helping your entry and not others that don't need this, so it might be a bit unfair towards others.

@VirgilCore It compresses it, because that's the default behavior for textures - most of them you want to have compressed. We need to do additional work to change the default.

**Comment by VirgilCore** [comment]
Pixel art is _supposed_ to be uncompressed. Its integral to how the art form works.

**Comment by LeCloutPanda** [comment]
> @LeCloutPanda You can turn the compression off after importing.
> 
> As a general rule, we don't recommend just "bumping" issues (see https://github.com/Yellow-Dog-Man/Resonite-Issues/blob/main/HOW_WE_PRIORITIZE.md ). I'm a bit hesitant to prioritize this on the grounds of MMC, since we'd be helping your entry and not others that don't need this, so it might be a bit unfair towards others.
> 
> @VirgilCore It compresses it, because that's the default behavior for textures - most of them you want to have compressed. We need to do additional work to change the default.

I understand that but MMC aside pixel art should just import as uncompressed or at least have the option to do so.

Multiple times in the past from both my self and people around me I've noticed that they use point filtered textures and do the same stuff as me where they see an issue and go back and forth and every time they do they need to reimport and manually uncompress it to look right.

**Comment by Frooxius** [comment]
We will prioritize this at some point, since it's a good tweak, but it's not the highest priority right now over other issue, since you can still do this manually.

**Comment by Frooxius** [comment]
Made changes in 2024.6.5.198! Thanks!
