### ISSUE TITLE
make content caching less cancer

### ISSUE THREAD

**Issue by vegasmurp** [Yellow-Dog-Man/Resonite-Issues#990]
### Is your feature request related to a problem? Please describe.

I don't every random jpeg from worlds I join - cached individually with zero encryption, obfuscation and/or compression,
I don't want to have to manually clear the cache and the end of every session / between worlds.

### Describe the solution you'd like

more granular settings similar to that of a browser.
cache to ram only
ram cache size
disk cache sze
clear cache on exit/start
clear cache between worlds
encryption, obfuscation and compression.
more security options so that this platform can scale while accounting for bad actors.

### Describe alternatives you've considered

suffering
crying louder

**Comment by Banane9** [comment]
you can enable filesystem compression in the location where you have your cache - it's also already "obfuscated", at least in terms of filenames. Clearing the cache extremely frequently with no regard for _what_ is being cleared is also not very useful and will only lead to complaints about long load times - while also causing unnecessary strain on the CDN infrastructure, which directly translates to higher costs to run the platform.

**Comment by Frooxius** [comment]
Unfortunately I have to close this issue for a number of reasons:
- [Our guidelines](https://github.com/Yellow-Dog-Man/Resonite-Issues) request that you use objective and neutral language, which this post is very much not. We expect at least a cursory level of professionalism and politeness if we are to engage with issues here
- There are multiple issues in this one, some of which we already have issues for: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/140
- It is unclear what some of the requests actually want - e.g. the database is already obfuscated and most assets are compressed. There is encryption used in parts of the process too. We would need more details on what exactly are you requesting.

You are free to open new issues as long as you adhere to the guidelines.

**Comment by vegasmurp** [comment]
fair enough
