### ISSUE TITLE
Graphs on https://status.yellowdogman.com/ have been broken for the past few days

### ISSUE THREAD

**Issue by liny-fox** [Yellow-Dog-Man/Resonite-Issues#994]
### Describe the bug?

See title.

### To Reproduce

Look at https://status.yellowdogman.com/ and look at the graphs, everything shows 0.

### Expected behavior

The graphs to work.

### Resonite Version Number

Website

### What Platforms does this occur on?

Windows

### Log Files

N/A

**Comment by ProbablePrime** [comment]
Duplicate of: https://github.com/Yellow-Dog-Man/Resonite-Issues/issues/930

**Comment by liny-fox** [comment]
Whoops, and im normally catching dupes.
