### ISSUE TITLE
There are two different IVariables

### ISSUE THREAD

**Issue by Zandario** [Yellow-Dog-Man/Resonite-Issues#995]
### Describe the bug?

`IVariable` is being inherented and used in two major locations and aren't compatible due to this.

IIRC, one is from `ProtoFluxBindings` and one is from `ProtoFlux.Core`

### To Reproduce

Create a source from the `IVariable` on a direct write and a indirect write and try to connect them together in a operator (maybe like ??)
Alternatively you can check the Type on the protoflux tip to see their namespace

### Expected behavior

For there to be one IVariable source otherwise change their names.

### Screenshots

![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/470aed92-c1fd-4ce5-86de-3575cad64f7b)

This image contains the same two types, top to bottom of course.
![image](https://github.com/Yellow-Dog-Man/Resonite-Issues/assets/34761877/58c8cddd-f84d-44e1-9828-d239cfb02808)

### Resonite Version Number

2023.12.21.1127

### What Platforms does this occur on?

Windows

### Log Files

N/A (Will provide one when I can anyways)

### Additional Context

While working on a JSON parser that used IVariables, I quickly noticed that if I were to use the type from direct actions, they were incompatible with indirect actions, even though on the surface they look the same.

### Reporters

@Zandario

**Comment by Zandario** [comment]
Not home atm and will post more info when I am

**Comment by Frooxius** [comment]
This is normal, there are supposed to be two.

ProtoFluxBindings creates "shims" for interfaces, so the type references can be replicated for the generated bindings, but aren't the actual interfaces - they cannot implement those, because they are just bindings, which replicate and translate the structure, but don't do the actual "work"

**Comment by Zandario** [comment]
> This is normal, there are supposed to be two.
> 
> ProtoFluxBindings creates "shims" for interfaces, so the type references can be replicated for the generated bindings, but aren't the actual interfaces - they cannot implement those, because they are just bindings, which replicate and translate the structure, but don't do the actual "work"

It doesn't change the fact there's multiple IVariables being used in ProtoFlux nodes that are invisibly incompatible?

**Comment by Zandario** [comment]
You literally can't tell the difference other than inspecting the full type

**Comment by Frooxius** [comment]
The fact that there are two is not a bug - it is expected that there are two, which are not compatible with each other. One is the original, the other one is the shim for that original. Both are necessary for ProtoFlux to function in FrooxEngine.

If you're working with bindings on FrooxEngine side you always need to use the bindings version, you'll never need the other unless you're working with ProtoFlux's internals.
